### PR TITLE
cmake/OpenCVGenPkgconfig.cmake: rework opencv.pc generation

### PR DESCRIPTION
**Pull request by tSed**
Hi all,

Here is a patch refactoring the opencv.pc file generation.
This fixes link-time failure of project linking with opencv.

Thought this PR is done for the 2.4 branch, this patch can be properly cherry-picked with no conflict on top of master.

Futher details about the changes in the commit message.

Regards,

Samuel

### CODE REVIEW

**Comment by tSed** [comment]
Hi,

This patch is not yet on master (i.e. opencv-3).
Is it because it conflict with [1]?
If so, let me know, I can refresh the patch and do a new PR.

[1] https://github.com/Itseez/opencv/commit/a5a510da4bbb0bb73b4ec82570f1d60bbe1af481

Regards,

**Comment by SpecLad** [comment]
2.4 is not being merged into master nowadays. You can create a new PR to master, if you want the change there.

**Comment by tSed** [comment]
Sorry for the delay,
PR done: https://github.com/Itseez/opencv/pull/3882

Thx,

**Comment by Dikay900** [comment]
this should be port done #4032 label can be detached

**Pull request merged**
