### PR TITLE
android: make optional "cpufeatures", build fixes for NDK r15

### LINKED ISSUE #8945: NEON doesn't get enabled on ARM
##### System information (version)

- OpenCV => master ( b21b6944447c95e364433c924dd560a16b91bffb )
- Operating System / Platform => Linux ARM32bit / Linux ARM64bit
- Compiler => GCC 4.8.4, 5.4.0 

##### Detailed description
 * CPU dispatch option is introduced, but it keeps blocking to activate the NEON on ARM platform
 * The main problem comes from obsolete options ```ENABLE_NEON``` [here](https://github.com/tomoaki0705/opencv/blob/b21b6944447c95e364433c924dd560a16b91bffb/CMakeLists.txt#L305-L306
)
```cmake
OCV_OPTION(ENABLE_NEON                "Enable NEON instructions"                                 "${NEON}" IF CMAKE_COMPILER_IS_GNUCXX AND (ARM OR AARCH64 OR IOS) )
OCV_OPTION(ENABLE_VFPV3               "Enable VFPv3-D32 instructions"                            OFF  IF CMAKE_COMPILER_IS_GNUCXX AND (ARM OR AARCH64 OR IOS) )
```
 * and [here](https://github.com/tomoaki0705/opencv/blob/b21b6944447c95e364433c924dd560a16b91bffb/cmake/OpenCVCompilerOptimizations.cmake#L79-L80)
```cmake
ocv_optimization_process_obsolete_option(ENABLE_VFPV3 VFPV3 OFF)
ocv_optimization_process_obsolete_option(ENABLE_NEON NEON OFF)
```
 * This macro ```ocv_optimization_process_obsolete_option``` will check the obsolete option and pass it to the "new" dispatch option, but I think [there is a bug in this macro ](https://github.com/tomoaki0705/opencv/blob/b21b6944447c95e364433c924dd560a16b91bffb/cmake/OpenCVCompilerOptimizations.cmake#L57 ) which ends up always switching flags to OFF 
```cmake
    if(${legacy_flag}) # !!!! this will not be evaluated as ON/OFF !!!!
      if(NOT ";${CPU_BASELINE_REQUIRE};" MATCHES ";${OPT};")
        set(CPU_BASELINE_REQUIRE "${CPU_BASELINE_REQUIRE};${OPT}" CACHE STRING "${HELP_CPU_BASELINE_REQUIRE}" FORCE)
      endif()
    else()
      if(NOT ";${CPU_BASELINE_DISABLE};" MATCHES ";${OPT};")
        set(CPU_BASELINE_DISABLE "${CPU_BASELINE_DISABLE};${OPT}" CACHE STRING "${HELP_CPU_BASELINE_DISABLE}" FORCE)
      endif()
    endif()
```
 * as a conclusion, the ```NEON``` flag and ```FP16``` flags always become false because those flag always go to ```CPU_BASELINE_DISABLE``` option.
 * I'll push a fix for this issue.

##### Steps to reproduce
 * on ARM 32bit (Jetson TK1)
```
cmake -DCPU_BASELINE=NEON ..
```
 * on ARM 64bit (Jetson TX1)
```
cmake ..
```

### PR DESCRIPTION
**Pull request by alalek**
- Added `WITH_CPUFEATURES` CMake option
- fixed `NEON` detection for builds with CMake toolchain from Android NDK r15
- fixed `FP16` detection (but it is not available for `Android AARCH64`)
- x86 / x86_64 Android builds pass
- fixed `NEON`/`FP16` for `Linux AARCH64` (with fixes in carotene library)
- fixed carotene library for GCC 5.x
- resolves #8945

### CODE REVIEW

**Comment by tomoaki0705** [comment]
My additional suggestion is to make dependency between the option flag ```FP16``` and ```NEON```, [here](https://github.com/opencv/opencv/blob/cf93b5a923a373f6b3e26a36b483936be59f6424/cmake/OpenCVCompilerOptimizations.cmake#L260)
```cmake
    ocv_update(CPU_FP16_FLAGS_ON "-mfpu=neon-fp16")
    ocv_update(CPU_FP16_IMPLIES "NEON")
```

The situation is very similar between ```FP16``` and ```AVX``` on ```x86_64``` around [here](https://github.com/opencv/opencv/blob/cf93b5a923a373f6b3e26a36b483936be59f6424/cmake/OpenCVCompilerOptimizations.cmake#L166)
```cmake
    ocv_update(CPU_FP16_IMPLIES "AVX")
```

**Comment by alalek** [comment]
@tomoaki0705 Thank you for review!
You are right! I have added mentioned line for both ARM/AARCH64 code paths.

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
