### PR TITLE
Updated To Modern Version of Aravis USB 3 Vision Protocol Library

### PR DESCRIPTION
**Pull request by SentToDevNull**
Confirmed working with Aravis-0.8 and my Pixelink USB 3 Vision protocol camera.

Aravis updated its API to make most function calls take in GObject data to write errors to (in addition to returning error codes); OpenCV doesn't use GObject, so we just don't pass a pointer to a GObject. Additionally, I removed a deprecated function call.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by SentToDevNull** [comment]
The reason the build failed on the Windows machine was because the server timed out when the build system was trying to `curl` some content...

**Comment by asmorkalov** [comment]
Related to https://github.com/opencv/opencv/pull/20126

**Comment by asmorkalov** [comment]
cc @ArkadiuszRaj

**Comment by JoeHowse** [comment]
This patch works for me on Manjaro Linux with the `aravis` package (version `0.8.19-1`) from the AUR repository. I tested it successfully with a USB3 camera: Point Grey Research Grasshopper3 FS3-U3-23S6M.

I suggest merging the patch as-is.

**Review by alalek — APPROVED** [review]

**Pull request merged**
