### PR TITLE
Fixed broken links of images

### PR DESCRIPTION
**Pull request by MauryaRitesh**
None of the images were displayed earlier due to broken links/wrong image formatting.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
There are no problems with images: https://docs.opencv.org/4.x/d3/d52/tutorial_windows_install.html

Direct links on GitHub should not be used (they are invalid as they doesn't support version control features).

**Comment by MauryaRitesh** [comment]
Sir, I was going through the docs on GitHub and the images there were not displayed.

**Comment by alalek** [comment]
It is not supposed. These files are input for doxygen documentation generator.

**Comment by MauryaRitesh** [comment]
Okay, Thanks.

**Pull request closed without merging**
