### PR TITLE
Fix missing FFmpeg include needed for av_get_pix_fmt_name

### PR DESCRIPTION
**Pull request by asmorkalov**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
build_image:Custom=ubuntu:14.04
```

### CODE REVIEW

**Comment by alalek** [comment]
Which FFmpeg version requires this?

**Comment by asmorkalov** [comment]
It's libav installed on Ubuntu 14.04. The symbol itself appeared in 2012.

**Comment by mshabunin** [comment]
Oh, I've tested _libav_ (https://github.com/mshabunin/videoio-ffmpeg-check/blob/c88bc86d23912f55c587433981f425fd7882eae5/download.sh#L31-L33), but decided that we won't support it anymore as this library seem to not be active anymore.

**Review by mshabunin — APPROVED** [review]

**Comment by asmorkalov** [comment]
I use Jetson tk1 for ARM v7 testing. It freezes with Ubuntu 14.04 and I have to deal with minor build issues here and there.

**Pull request merged**
