### PR TITLE
[CUDA] Fixed Filter bug

### LINKED ISSUE #6742: cv::cuda::Filter thread safety
cv::cuda::Filter created by cv::cuda::createGaussianFilter(...) is not thread safe. And I don't mean the classical thread-safety of accessing one instance from multiple cpu threads. It is not safe to create separate instances of the Filter in multiple threads.
### system info
- OpenCV version: 3.1.0
- Host OS: Linux (Ubuntu 14.04)
- GPU: GeForce GTX TITAN X
- compiler: g++ 4.8.4
### Expected behaviour

filter_1
filter_2
### Actual behaviour

filter_1
filter_2
(not deterministic... each execution outputs slightly different results, but the first image is almost always badly distorted)
### Code example to reproduce the issue

```
#include <iostream>
#include <string>
#include <thread>
#include <opencv2/core/core.hpp>
#include <opencv2/cudafilters.hpp>
#include <opencv2/highgui/highgui.hpp>

void show(const std::string& win_name, const cv::Mat& im) {
  cv::Mat to_show;
  double min, max;
  cv::minMaxIdx(im, &min, &max);
  im.convertTo(to_show, CV_8UC1, 255 / (max-min), -min);
  cv::namedWindow(win_name, CV_WINDOW_NORMAL);
  std::cout << win_name << " - min: " << min << "; max: " << max << std::endl;
  cv::imshow(win_name, to_show);
  // cv::imwrite(std::string("/tmp/")+win_name+".png", to_show);
}

void filter_it(const cv::cuda::GpuMat& d_src, int ksize, cv::Mat& h_dst) {
  cv::cuda::GpuMat d_dst(d_src.rows, d_src.cols, CV_32FC1);
  cv::Ptr<cv::cuda::Filter> filter =
      cv::cuda::createGaussianFilter(CV_32FC1, CV_32FC1, cv::Size(ksize,ksize), 0, 0);
  filter->apply(d_src, d_dst);
  h_dst = cv::Mat(d_dst);
}

int main(int argc, char *argv[])
{
  cv::Mat dot1;
  const int size = 65;
  dot1.create(size, size, CV_32FC1);
  dot1.at<float>(size/2, size/2) = 1.0f;

  cv::Mat dot2;
  dot1.copyTo(dot2);

  cv::cuda::GpuMat d_src1(dot1);
  cv::cuda::GpuMat d_src2(dot2);

  cv::Mat h_dst1;
  h_dst1.create(size, size, CV_32FC1);
  cv::Mat h_dst2;
  h_dst2.create(size, size, CV_32FC1);

  std::thread thr1(&filter_it, std::ref(d_src1), 31, std::ref(h_dst1));
  std::thread thr2(&filter_it, std::ref(d_src2), 3,  std::ref(h_dst2));
  thr1.join();
  thr2.join();

  show("filter_1", h_dst1);
  show("filter_2", h_dst2);
  cv::waitKey(0);
  return 0;
}
```

### PR DESCRIPTION
**Pull request by souch55**
### This pullrequest changes

This pull request resolves filter related issue #6742

### CODE REVIEW

**Comment by sovrasov** [comment]
:+1:

**Comment by alalek** [comment]
Is this problem reproduced on CUDA device and does this fix help really?

**Comment by sovrasov** [comment]
@alalek I tested this PR on my device. The problem reproduced, bot this patch doesn't fixes it.

**Comment by sovrasov** [comment]
@souch55 did you test the patch?

**Comment by souch55** [comment]
Hi sovrasov there is some more work around we have to do, if the bug is reproducible,as reported by you.

**Pull request closed without merging**
