### PR TITLE
Optimize exp32f with AVX2

### PR DESCRIPTION
**Pull request by woodychow**
Pretty straight forward. I just translated the SSE code to AVX2.

### CODE REVIEW

**Comment by alalek** [comment]
Looks good to me. Thanks you!
Performance improvement for 1M(2**20) floats from 2.44ms (SSE2) to 1.64ms (AVX2) on i5-6600.

Could you please add `checkHardwareSupport(CV_CPU_AVX2)` check, `vzeroupper()` call and replace `#elif CV_SSE2` like here: #8391

**Comment by vpisarev** [comment]
thank you! can you, please, refactor your code to support runtime dispatching? See https://github.com/opencv/opencv/pull/8399 for details

**Comment by woodychow** [comment]
I did not add checkHardwareSupport(CV_CPU_AVX2) because there is no checkHardwareSupport(CV_CPU_SSE2) in the same function. Anyhow, I will take care of everything when we reach a conclusion in #8399

**Comment by vpisarev** [comment]
We decided not to put checkHardwareSupport(CV_CPU_SSE2) everywhere. People have option to disable SSE2 optimization at compile time if: a) they build OpenCV for archs different from x86/x64 (then SSE2 is disabled automatically) or b) they want to check/try pure C branches of the code.

But if SSE2 is enabled at compile time, we don't need to check for it. The target hardware supports SSE2 with 99.9% probability (the first chip, supporting SSE2, Pentium 4, was released in 2000). On 64-bit Intel/AMD CPUs SSE2 is supported with 100% probability. So if we omit unnecessary checks for SSE2 support.

**Comment by woodychow** [comment]
Thanks for the detailed explanation. OK!

**Comment by alalek** [comment]
This will be auto-merged with #8441

**Pull request merged**
