### PR TITLE
add universal intrinsics for HSV2RGB_b

### PR DESCRIPTION
**Pull request by K-Shinotsuka**
```
force_builders=Custom,armv7,armv8
docker_image:Custom=powerpc64le
```

### CODE REVIEW

**Comment by K-Shinotsuka** [comment]
@vpisarev 
Thank you for your advice.
I'll delete v_load_deinterleave_expand().
But I'll create v_load_deinterleave_q() or v_load_deinterleave_half().
And I'll use v_expand() and convert s32 to f32.

**Comment by vpisarev** [comment]
@K-Shinotsuka, ok, that can be also the solution. Just a few small notes:

1. it would be better to add `v_load_deinterleave_low()` (that would load and deinterleave 8 pixels, producing v_uint16x8 x 3). It should have pretty good implementations for NEON and SSE. The problem is that PPC64 build will be broken unless you provide some default implementation for it as well.
2. if you want, you may add v_expand universal intrinsic that would convert u16 to f32 via conversion to u32, then reinterpretation to s32, then conversion fo f32. This intrinsic may be replicated 1:1 on each backend, because it can be implemented using existing universal intrinsics.
3. we have now the tradition to cover all important functionality, including the newly added universal intrinsics, with tests. So, you need to provide some regression tests for the newly added intrinsics.

**Comment by vpisarev** [comment]
@K-Shinotsuka, it looks like the latest version of your patch does not pass the regression tests on ARM. Could you please look at it?

**Comment by vpisarev** [comment]
superseded by #11637

**Comment by K-Shinotsuka** [comment]
@vpisarev 
Ah!
I haven't finished it yet, because I'm so busy with work.

**Comment by K-Shinotsuka** [comment]
Maybe I'll recommit it.

**Pull request closed without merging**
