### PR TITLE
feat(android): add parameter for choose modules for android

### LINKED ISSUE #12689: Help to build only selected modules for android
I am trying to build *.so files for android modules which iam looking are core,imgproc and java files.

Below code works fine it generates java wrapper files which here is "libopencv_java400.so"

`cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_LIST=${OPEN_CV_BUILD_MODULES} -D BUILD_ANDROID_PROJECTS=OFF -D WITH_FFMPEG=OFF -D WITH_IPP=OFF -D WITH_OPENEXR=OFF -D BUILD_EXAMPLES=OFF -D BUILD_ANDROID_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D BUILD_DOCS=OFF -D BUILD_opencv_python2=OFF -D BUILD_opencv_python3=OFF -D BUILD_SHARED_LIBS=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF .. && make -j8`

But when i run to generate for arm64 it doesnt generate java files and libopencv_java400.so file

```
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
        -D ANDROID=ON \
        -D ANDROID_ABI="arm64-v8a" \
        -D BUILD_LIST="imgproc,java" \
        -D BUILD_ANDROID_PROJECTS=OFF \
        -D BUILD_SHARED_LIBS=ON \
        -D CMAKE_TOOLCHAIN_FILE=../platforms/android/android.toolchain.cmake \
        -D ANDROID_NATIVE_API_LEVEL=19 \
        -D ANDROID_FORCE_ARM_BUILD=OFF \
        -D ANDROID_STL_FORCE_FEATURES=OFF \
        .. &&\
        make -j$NUM_CORES && \
        make install
```

Can any one share working cmake code to geneate.

Thank you

here is my dockerfile code

https://gist.githubusercontent.com/Rajeshr34/43fc08179bcb8c787d6630e0dd926a74/raw/788c41f4699ba72ee0c31eea025d2852d2c720bd/DockerFile

### PR DESCRIPTION
**Pull request by miguelps**
### This pullrequest changes
build_sdk.py, which compiles OpenCV-SDK for Android.

Added an option/parameter for build only selected modules (for Android), like a whitelist.
Care should be take to include modules which are required to others (this is not checked).

==============
call sample:
==============
python2 ../platforms/android/build_sdk.py \
--modules_list core,imgcodecs,improc \
~/projects/opencv/build \
~/projects/opencv

### CODE REVIEW

**Comment by asmorkalov** [comment]
@miguelps Thanks for the contribution, please restore empty lines in the script.

**Comment by hannesa2** [comment]
I at least would love to see such call examples
```
python2 ../platforms/android/build_sdk.py
--modules_list core,imgcodecs,improc
~/projects/opencv/build
~/projects/opencv
```

in this file https://github.com/opencv/opencv/blob/master/platforms/android/README.android

**Comment by miguelps** [comment]
Hi Alexander
Empty lines restored.
But
https://github.com/opencv/opencv/blob/master/platforms/android/README.android
refers to an HTML page (it is only a link).
How can I suggest updates to HTML page(s)?

**Comment by alalek** [comment]
`README.android` is not a good place right now. Also there is no easy process for contributing updates to HTML pages on opencv.org.

Please remove unused files (.sh) and squash commits into one (before rebasing, see below).

---

This patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

**Comment by miguelps** [comment]
ok, done!

**Pull request merged**
