### PR TITLE
speed up HOG using NEON as well as SSE2

### PR DESCRIPTION
**Pull request by vpisarev**
### What does this PR change?

 - speed up HOG using NEON as well as SSE2

### Former #6699

### CODE REVIEW

**Comment by vpisarev** [comment]
@cuda-geek, could you please review it?

**Comment by cuda-geek** [comment]
@tomoaki0705, could you please provide the performance numbers for your version, original OpenCV and measure achieved uplift. You can use OpenCV's performance testing framework to get all the data. Please, mention the hardware you used to benchmark.

**Comment by tomoaki0705** [comment]
I tried this on [PINE64](https://www.pine64.com/)
It seems opencv_perf_objdetect doesn't have performance test for HOG (only for OpenCL)
So, I ran opencv_test_objdetect three times.

Test name | average (SIMD) | median (SIMD) | average (normal) | median (normal) 
------------ | ------------- | -------------  | ------------- | -------------
Objdetect_HOGDetector.regression | 8789.3 | 8769 | 10382 | 10413 
Objdetect_HOGDetector_Strict.accuracy | 8121.3 | 8118 | 8489.3 | 8464

**Comment by alalek** [comment]
Actually "OCL_*" tests is T-API (Transparent API) tests and should work on CPU in case of platforms without OpenCL support (or disabled OpenCL, for example, via `OPENCV_OPENCL_DEVICE=disabled` environment variable).

**Comment by cuda-geek** [comment]
@tomoaki0705, I agree with @alalek. We should try to reuse this tests

**Comment by vpisarev** [comment]
ok, I suggest to merge it in, because there is clearly some effect from optimization :+1:

**Comment by tomoaki0705** [comment]
@alalek , @cuda-geek and @vpisarev Thank you for your time, review and suggestion.
Just to make sure, I ran the OCL_HOGFixture_HOG.HOG test from opencv_perf_objdetect.

Test name | SIMD | normal 
------|------|------
OCL_HOGFixture_HOG.HOG (average) | 690.90 | 810.63
OCL_HOGFixture_HOG.HOG (median) | 689.13 | 808.42

So, it did speed up. Thank you.
Best regards.

**Pull request merged**
