### PR TITLE
js: update build js

### PR DESCRIPTION
**Pull request by alalek**
- support emscipten 1.38.12 ([wasm is ON by default](https://github.com/kripken/emscripten/blame/dc5c6841ae36cf59748de21b152176e9fdd0c2d2/src/settings.js#L735), need to disable explicitly)
- verbose build messages
- use builtin Math functions

```
force_builders=Custom
docker_image:Docs=docs-js
docker_image:Custom=javascript
```

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by dkurt** [comment]
@alalek, With `WASM=0` it takes about 12MB for opencv.js (about 6.5MB with `WASM=1` or with a previous versions of emscipten).

**Comment by alalek** [comment]
Currently we using Emscripten 1.37.21 on build machines. Size of `opencv.js` is about 6.5Mb.

Fresh installation on new machine installs Emscripten 1.38.12 / 1.38.13 (emsdk install latest)
There is result without `WASM=0` (current infrastructure doesn't expect `.wasm` files):
```
$ ll bin/opencv*
-rw-rw-r-- 1 alalek alalek  298280 Oct 11 20:38 opencv.js
-rw-rw-r-- 1 alalek alalek  297682 Oct 11 20:38 opencv_js.js
-rw-rw-r-- 1 alalek alalek 5781636 Oct 11 20:38 opencv_js.wasm
```

Rollback to 1.37.12:
```
$ ./emsdk activate sdk-tag-1.37.21-64bit
...
$ ls -al bin/opencv*
-rw-rw-r-- 1 alalek alalek 13086095 Oct 11 23:13 bin/opencv.js
-rw-rw-r-- 1 alalek alalek 13085497 Oct 11 23:13 bin/opencv_js.js
```

/cc @huningxin Any thoughts?

**Comment by huningxin** [comment]
If you don't want `opencv_js.wasm`, you may append `-s SINGLE_FILE =1` into emscripten build command https://github.com/opencv/opencv/blob/master/modules/js/CMakeLists.txt#L94. It will embed the wasm file into JS with base64 encoding. Please refer to https://github.com/kripken/emscripten/blob/dc5c6841ae36cf59748de21b152176e9fdd0c2d2/src/settings.js#L935 for details.

**Comment by alalek** [comment]
@dkurt I have checked opencv.js size on docs.opencv.org:

```
$ ls -al 3.4/opencv.js 3.4.3/opencv.js 3.4.2/opencv.js 3.4.1/opencv.js 3.4.0/opencv.js 3.3.1/opencv.js
-rw-r--r-- 1 user user  6941168 Oct 24  2017 3.3.1/opencv.js
-rw-r--r-- 1 user user 11450132 Dec 23  2017 3.4.0/opencv.js
-rw-r--r-- 1 user user 11537949 Feb 26  2018 3.4.1/opencv.js
-rw-r--r-- 1 user user 11986193 Jul  4 14:05 3.4.2/opencv.js
-rw-r--r-- 1 user user 12133473 Aug 29 10:38 3.4.3/opencv.js
-rw-r--r-- 1 user user 13083490 Oct 12 03:00 3.4/opencv.js
```

Could you please check what OpenCV commit provides opencv.js with 6.5 Mb size on your side? And what emscipten version is used (see `~/.emscripten`).

**Comment by exist2disappear** [comment]
Why add the “-s SINGLE_FILE=1” opt ?
this make me can't get opencv.wasm on opt: --build_wasm
most time it work; but have err on android+chrom...

**Pull request merged**
