### PR TITLE
CMake install path fixes

### PR DESCRIPTION
**Pull request by olesalscheider**
This pull request contains a few fixes for the CMake build system.
They move all target-specific files from share to lib (where they belong) and also allow to override the "share" path.

This is important for distributions like Exherbo that install all architecture-independent files to /usr/share and all other files to /usr/${host}/share, so that a package can be installed for multiple architectures in parallel.

### CODE REVIEW

**Comment by olesalscheider** [comment]
The tests on Linux seem to be failing now because the build script passes a wrong value for "OpenCV_DIR".

**Comment by alalek** [comment]
> They move all target-specific files from share to lib

Could you add some links about this. We will take a look

**Comment by olesalscheider** [comment]
Sure.

CMake's packaging tutorial that mentions to install the config files to lib/cmake/...:
https://cmake.org/Wiki/CMake/Tutorials/Packaging#Package_Configuration_Files

Exherbo's multi-arch:
- https://exherbo.org/docs/multiarch-pr.html (High-level description, PR)
- http://exherbo.org/docs/multiarch.txt (Technical details)

I guess it's obvious why the .a/.so libraries should be moved (see second commit). If you are interested in any other links feel free t ask.

**Comment by alalek** [comment]
@olesalscheider
Most part of fixes looks valid and should be done, but there are some issues include "compatibility" changes (like OpenCV_DIR and broken "include" directories) that we need to resolve without serious impact to users (I will take a look on this).

BTW, Why JARs should be moved out from the "share" folder? I believe, they are platform-independent in general.
For example, Debian project uses this check: https://lintian.debian.org/tags/jar-not-in-usr-share.html

**Comment by olesalscheider** [comment]
> `OPENCV_JAR_INSTALL_PATH` controls `opencv_java` native binary installation. So this should be moved out from "share" directory also.

Yes, that's why I adjusted `OPENCV_JAR_INSTALL_PATH`. I don't really know if the jar itself could be in share while the native binaries are in lib, though. Maybe someone who knows a bit more about Java can comment on that...

**Comment by olesalscheider** [comment]
Are there any news on this?

**Comment by olesalscheider** [comment]
@alalek What is the plan with this? Did you have a chance to look at the issues you mentioned?

**Comment by alalek** [comment]
This problem should be fixed with #5980 (when it will be completed and merged)

**Comment by mshabunin** [comment]
Problem should be fixed in another PR.
@olesalscheider , please check if that fix works for you. If you have an updated version of your fix, please create new pull request, since this one is broken.

**Pull request closed without merging**
