### PR TITLE
change parameter input to the CommandLineParser interface

### PR DESCRIPTION
**Pull request by StevenPuttemans**
### This pullrequest changes

Adds the more generic interface of CommandLineParser to parse the input arguments!

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by StevenPuttemans** [comment]
Hmm @alalek this seems quite straightforward and working, but for one reason or the other, when running this code now, I get a `The image folder given does not exist. Please check again!` whenever running this command `opencv_annotation -a /data/vliegje/annotations.txt -i /data/vliegje/data/` or `opencv_annotation --annotations /data/vliegje/annotations.txt --images /data/vliegje/data/`

So I will look into this and provide a fix for it!

**Comment by StevenPuttemans** [comment]
It has something to do with the line `mkdir(image_folder.c_str(), 0777) != -1` which is no longer working on the extracted string using the parser.

**Comment by StevenPuttemans** [comment]
So adding a 

`    cerr << image_folder << endl;
    cerr << image_folder.c_str() << endl;`

Right before line 259 returns

```
true
true
The image folder given does not exist. Please check again!
```

**Comment by alalek** [comment]
Did you try to replace std::string with cv::String?

**Comment by StevenPuttemans** [comment]
> Did you try to replace std::string with cv::String?

Just did

``` 
String image_folder = parser.get<String>("images");
String annotations_file = parser.get<String>("annotations");
cerr << image_folder << endl;
cerr << annotations_file << endl;
```

And got again 2 times output true. So that is not the case!

**Comment by alalek** [comment]
Use "=" to specify value of option:
`--annotations /data/vliegje/annotations.txt`
=>
`--annotations=/data/vliegje/annotations.txt`

CommandLineParser tests are here:
https://github.com/opencv/opencv/blob/master/modules/core/test/test_utils.cpp

**Comment by StevenPuttemans** [comment]
Yep it seems that was doing the trick! Seems the commandline interface is a bit counter intuitive to existing behaviour but we will get the hang of it!

**Pull request merged**
