### PR TITLE
Fix drawing

### LINKED ISSUE #7785: cv::putText regression
##### System information (version)
- OpenCV => master
- Operating System / Platform => Win7 x64
- Compiler => **MSVS 2010 32-bit** (MSVS 2012/2015 32/64-bit are fine)

##### Detailed description

Example of generated input data for test: `Videoio_Video.seek_random_synthetic`

OpenCV 3.1.0:
opencv-3 1 0

OpenCV master:
opencv-master

Probably related: #7458 #7161

### PR DESCRIPTION
**Pull request by chacha21**
A flat polygon does not need to be filled since the contours are enough.
fixes #7785

### CODE REVIEW

**Comment by alalek** [comment]
Could you try patch from #7959?

**Comment by chacha21** [comment]
#7959 work for me; do we also keep #7963 ?

**Comment by chacha21** [comment]
Honestly, I am a little lost in the GitHub tools. The perf_fill.cpp test was not intended to be commited. What should I do ? I don't even know how to cancel the PR.

**Comment by chacha21** [comment]
There is a mess with my two branches fix_drawing and drawing_performance, I really don't understand what git is doing here...

**Pull request closed without merging**
