### PR TITLE
[IE][VPU]: Refactor vpu configs

### PR DESCRIPTION
**Pull request by Maxim-Doronin**
related PR in openvino
https://github.com/openvinotoolkit/openvino/pull/1334

**MUST BE** merged after merging related PR's

### CODE REVIEW

**Comment by alalek** [comment]
Please take a look on discussion about API breaking changes and merging process: #17888

**Comment by dkurt** [comment]
If I'm not mistaken, there should be a macros for it, `VPU_CONFIG_KEY`. May we ask to change to
```cpp
config.emplace(VPU_CONFIG_KEY("DETECT_NETWORK_BATCH"), CONFIG_VALUE(NO));
```
?

**Comment by Maxim-Doronin** [comment]
> If I'm not mistaken, there should be a macros for it, `VPU_CONFIG_KEY`. May we ask to change to
> 
> ```c++
> #include <vpu/vpu_plugin_config.hpp>
> //...
> config.emplace(VPU_CONFIG_KEY("DETECT_NETWORK_BATCH"), CONFIG_VALUE(NO));
> ```
> 
> ?

`DETECT_NETWORK_BATCH` is a private plugin config. To use it as a variable, not as a string, we should include myriad plugin targets explicitly

**Comment by Maxim-Doronin** [comment]
@dkurt, the main PR openvinotoolkit/openvino#1334 was merged. Could you take a look once again?

**Pull request merged**
