### PR TITLE
fix incorrect imshow behavior

### LINKED ISSUE #15745: Imshow incorrect behaviour
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc

##### Detailed description

The [documentation claims](https://docs.opencv.org/master/d7/dfc/group__highgui.html#ga453d42fe4cb60e5723281a89973ee563) that imshow maps [0,1] to [0,255] for float matrices, however it seems to also be including negative values, i.e., [0, -1] is also mapped to [0,255]. Previously, negative values were clamped to 0. See examples below

##### Steps to reproduce

Note the negative values in the matrices.

```python
import cv2 as cv
import numpy as np

mat1 = -1*np.ones([500,500])
cv.imshow("mat1", mat1)
mat2 = np.tile(np.linspace(-1, 1, 500), (500,1))
cv.imshow("mat2", mat2)
cv.waitKey(0)
```
This produces:
imshow_error

### PR DESCRIPTION
**Pull request by TH3CHARLie**
### This pullrequest changes
incorrect imshow behaviors
resolves #15745

### CODE REVIEW

**Comment by asmorkalov** [comment]
Hello @TH3CHARLie thanks for you contribution. Could you rebase you branch on top of 3.4 and re-target the PR. OpenCV team merges only bug fixes and improvements there and then merge all collected fixes from 3.4 to master time to time. It allows to support both 3.4 and 4.x branches and reduce maintenance issues.

**Comment by alalek** [comment]
> rebase you branch on top of 3.4

This patch is not applicable to "3.4" branch.

**Comment by TH3CHARLie** [comment]
@alalek is correct, this bug seems to happen in 4.x @asmorkalov. And the logic in `src/precompute.hpp` is pretty different from 3.x to 4.x

**Comment by asmorkalov** [comment]
Thanks for contribution. Yes, my fault, it's for master branch only, 3.4 is not affected.

**Pull request merged**
