### PR TITLE
objc: rework headers import

### PR DESCRIPTION
**Pull request by alalek**
- 'AdditionalImports' can be removed from misc/objc/gen_dict.json

/cc @komakai 

```
force_builders_only=docs,ios,Custom Mac
Xbuild_image:Custom Mac=osx_framework
build_image:Custom Mac=osx_framework-test
buildworker:Custom Mac=macosx-2
build_contrib:Custom Mac=OFF
```

### CODE REVIEW

**Comment by komakai** [comment]
Still hitting the Apple `NO` macro conflict problem

**Comment by alalek** [comment]
Related error message:

```
In file included from build/build-armv7-iphoneos/modules/objc/gen/objc/calib3d/Calib3d.mm:9:
In file included from build/build-armv7-iphoneos/modules/objc/gen/objc/core/Double3.h:10:
In file included from build/build-armv7-iphoneos/install/include/opencv2/opencv.hpp:86:
In file included from build/build-armv7-iphoneos/install/include/opencv2/stitching.hpp:51:
build/build_ios/build/build-armv7-iphoneos/install/include/opencv2/stitching/detail/exposure_compensate.hpp:47:4: warning: Detected Apple 'NO' macro definition, it can cause build conflicts. Please, include this header before any Apple headers. [-W#warnings]
#  warning Detected Apple 'NO' macro definition, it can cause build conflicts. Please, include this header before any Apple headers.
   ^
build/build_ios/build/build-armv7-iphoneos/install/include/opencv2/stitching/detail/exposure_compensate.hpp:66:12: error: expected identifier
    enum { NO, GAIN, GAIN_BLOCKS, CHANNELS, CHANNELS_BLOCKS };
           ^
```

---

> opencv.hpp

I believe problem comes from here.
Need to cleanup its usage.

**Comment by komakai** [comment]
> I believe problem comes from here.
Yes that's it
> Need to cleanup its usage.
Maybe just go for a breaking changes like here and resolve this once and for all:https://github.com/komakai/opencv/commit/b3513b8b27292c4c486506f07721752c2b1584b4

**Comment by alalek** [comment]
:+1:

**Pull request merged**
