### PR TITLE
core, stitching: revise syntax to support Visual C++ 2013

### PR DESCRIPTION
**Pull request by JoeHowse**
This pull request makes minor revisions to syntax in the core and stitching modules to improve support for Visual C++ 2013.

I am testing with a configuration similar to the following:

```
CALL C:\TBB\bin\tbbvars.bat ia32 vs2013
cmake -DCMAKE_BUILD_TYPE=RELEASE ^
      -DWITH_OPENGL=ON ^
      -DWITH_TBB=ON ^
      -DOPENCV_SKIP_PYTHON_LOADER=ON ^
      -DPYTHON2_LIBRARY=C:/Python27/libs/python27.lib ^
      -DPYTHON2_INCLUDE_DIR=C:/Python27/include ^
      -DWITH_ADE=OFF ^
      -DWITH_QUIRC=OFF ^
      -G "Visual Studio 12 2013" ^
      Z:/SDKs/OpenCV/fork
```

### CODE REVIEW

**Comment by JoeHowse** [comment]
The automated builds seem to be failing for reasons that are unrelated to this pull request.

**Comment by alalek** [comment]
> unrelated

Related.

BTW, MSVS 2019 is almost here (preview).

**Comment by JoeHowse** [comment]
> > unrelated
> 
> Related.

Sorry about that. You're right. I've fixed the issue and the automated builds pass now.

> BTW, MSVS 2019 is almost here (preview).

I have clients who use Visual C++ 2013.  If at least some configurations of OpenCV 4 support Visual C++ 2013, this is valuable to them.

In general, the OpenCV 4 source code does contain macros that seem to target Visual C++ 2013 compatibility, but the release notes and documentation are not specific about which compilers are supported or tested.  The release notes just say, "requires C++11-compliant compiler", which may leave doubt in users' minds about whether the level of C++11 compliance in Visual C++ 2013 (or 2015 or whatever) is "good enough".

If you are implying that Visual C++ 2013 is _not_ really supported (or in general, say, testing focuses on compilers that are less than 5 years old), it would be good to have this documented.  Your thoughts on the idea of documenting the supported or tested compilers would be appreciated.  Thanks!

**Comment by alalek** [comment]
We don't support or test MSVS 2013 builds (list of tested configurations is [here](http://pullrequest.opencv.org/buildbot/grid?tag=scheduled-master)).
Support of MSVS 2013 is community-driven activity (#11979)

BTW, don't forget to run OpenCV accuracy tests locally (some compiler bugs or strange behavior may break functionality).

**Pull request merged**
