### PR TITLE
Update to libtiff 4.0.10

### PR DESCRIPTION
**Pull request by tailsu**
Sources copied from the master download mirror: https://download.osgeo.org/libtiff/tiff-4.0.10.tar.gz

4.0.10 has fixed multiple security vulnerabilities.

### CODE REVIEW

**Comment by tailsu** [comment]
I've just noticed that I haven't included the new zstd and webp codecs from libtiff

**Comment by tailsu** [comment]
I added the new files to the project. Their code is disabled and they produce no symbols, like a bunch of the other formats.

**Comment by alalek** [comment]
Thank you!

Please remove "! test" commit and squash commits into one (including my commit).

**Comment by tailsu** [comment]
Ok, done. Will you merge the commit into 4.0 yourself or should I open separate PR's for that?

**Comment by alalek** [comment]
Thank you!
Patches from 3.4 will be merged into master on next week (during regular merge-3.4 process).

**Pull request merged**
