### PR TITLE
Fix infinit loop in tf 3.4 branch

### PR DESCRIPTION
**Pull request by zihaomu**
Backport: Related PR https://github.com/opencv/opencv/pull/22725

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Review by asmorkalov — APPROVED** [review]
:+1:

**Comment by XiabachaoXy** [comment]
MOCUTE-VTF12-058-L

**Comment by alalek** [comment]
> Fix infinit loop in tf 3.4 branch

vs

> zihaomu wants to merge 1 commit into opencv:4.x


3.4 or 4.x?

**Review by alalek — APPROVED** [review]
Thank you :+1:

**Comment by alalek** [comment]
BTW, GitHub actions results are still on 4.x branch.

**Comment by zihaomu** [comment]
I will try to force commit the PR to retrigger the GitHub action.

**Pull request merged**
