### PR TITLE
persistence: fixing crash with space-only values

### LINKED ISSUE #6781: Invalid YML when storing strings containing only spaces
### Please state the information for your system
- OpenCV version: 3.1

### In which part of the OpenCV library you got the issue?
- persistence

### Expected behaviour
Strings containing only spaces should be serialized as ``key: "    "``

### Actual behaviour
Such strings are serialized as ``key:    ``, breaking the indentation. When reading the file again, OpenCV crashes with the exception

> OpenCV Error: Parsing error (dummy.yml(3): Incorrect indentation) in icvYMLSkipSpaces

The file generated by the code below looks like this:
```
%YAML:1.0
test:  
test2: other
```

### Code example to reproduce the issue / Steps to reproduce the issue
Please try to give a full example which will compile as is.
```
#include <opencv2/core.hpp>
#include <iostream>

int main(int argc, char **argv)
{
    cv::FileStorage fs("dummy.yml", cv::FileStorage::WRITE);
    fs << "test" << "    ";
    fs << "test2" << "other";
    fs.release();
    cv::FileStorage fs2("dummy.yml", cv::FileStorage::READ);
    std::string test;
    fs2["test"] >> test;
    std::cout << "test is: " << test << std::endl;
    return 0;
} //main
```

### PR DESCRIPTION
**Pull request by PhilLab**
resolves #6781

### CODE REVIEW

**Comment by savuor** [comment]
:+1: 
@PhilLab could you also add checks for last character to load strings like "   some string   " as they were saved?

**Comment by PhilLab** [comment]
@savuor: finally, took some attempts :smile:

**Comment by PhilLab** [comment]
Hm, @opencv-pushbot did not react

**Comment by alalek** [comment]
> Checking for ability to merge automatically…
> Hang in there while we check the branch's status.

Looks like this PR is dead. There is some GitHub issue related to OpenCV repositories transfer. And this is the first PR which is created and broken after transfer.

@PhilLab Please close this PR and create new one.

**Comment by PhilLab** [comment]
@alalek: Thanks for the tip, I created a new one

**Pull request closed without merging**
