### PR TITLE
Eliminating compilation warnings when using lto in gcc12 and later versions

### PR DESCRIPTION
**Pull request by buyuer**
If use -flto in gcc12.1, then will be warning appear.
```
lto-wrapper: warning: using serial compilation of 57 LTRANS jobs
lto-wrapper: note: see the ‘-flto’ option documentation for more information
```

Reference:
https://stackoverflow.com/questions/72218980/gcc-v12-1-warning-about-serial-compilation
https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

>Use -flto=auto to use GNU make’s job server, if available, or otherwise fall back to autodetection of the number of CPU threads present in your system.

### CODE REVIEW

**Comment by mshabunin** [comment]
Does it work with Ninja generator?

**Comment by buyuer** [comment]
> 

yeah，I tested using ninja

**Comment by asmorkalov** [comment]
I can confirm the issue and the fix works for me with Ubuntu 22.04 and GCC-12 (apt repo). Command line to build:
```
cmake -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -DENABLE_LTO=ON ../opencv
make -j4 opencv_test_core
```

**Review by asmorkalov — APPROVED** [review]
:+1:

**Pull request merged**
