### PR TITLE
hogsvm compatibility with python3

### PR DESCRIPTION
**Pull request by jmlich**
I was trying hogsvm tutorial with python3 and it wasn't working well. Here are necessary changes. 

I have added list() call to map() to be able run tutorial with python3.
```
-hogdata = [map(hog,row) for row in deskewed]
+    hogdata = [list(map(hog,row)) for row in deskewed]
```

I have also added if __main__ and corresponding whitespaces:
```
if __name__ == "__main__":
```

please use "git diff -w" to see changes without whitespaces.

### CODE REVIEW

**Comment by alalek** [comment]
> if __name__ == "__main__"

This file is tutorial example, it is not expected to be imported anywhere as python module.

**Comment by jmlich** [comment]
I thought the "main == __name__ " is good habit in python scripts. I am not going to modify pull request. Merge it if you like it. Reject it if you don't.

**Comment by alalek** [comment]
Python3 fix works. Thank you :+1:
Unnecessary changes are reverted from this patch.

**Comment by jmlich** [comment]
Thanks :thumbsup:

**Pull request merged**
