### PR TITLE
tabulation to proper spaces

### PR DESCRIPTION
**Pull request by cv3d**
Merge with opencv/opencv_contrib#1815

### This pullrequest changes
This PR ensures format compatibility with the [contribution guidelines](https://github.com/opencv/opencv/wiki/How_to_contribute), and I have reviewed it line by line..

### CODE REVIEW

**Comment by vpisarev** [comment]
@cv3d, it went too far. Your PRs waste too much of our time. For now I've just closed them all. Before submitting next PRs, please, discuss it with us, _one_ at a time - please do not spam us with issues/questions, value your and our time. If you keep submitting PRs or open many issues/questions, I'll have to contact github support team and ask them to resolve this situation.

**Comment by cv3d** [comment]
You are the admin here, and you decide how this project goes! Yet, it is a pity that these PRs gets closed, despite that some of them (not this one of course) are important and needed... I still hope you are serious about reopening them, although that does not sound like happening, given that you never left even a single one open...

> it went too far

Indeed, I have the same impression!

> I'll have to contact github support team and ask them to resolve this situation

You do not need to, as I do not feel like contributing anymore, thanks to your closing-before-talking way of discussion. Besides, I wonder if you are the one who should contact github in such a situation!

Here are some of my points:
- I already filed 12 open issues, and there are major issues that I would expect your opinion at (i.e. #12569 or #12584), even if you are super busy. If you replied to any of my previous issues, and showed the willingness to discuss, I would not mind to always open an issue before opening a PR, but have you replied/discussed even once?
- Even if you say to open an issue before making a PR, I wonder why have you closed PRs corresponding to open issues as well?
- If you expressed that you cannot keep up (by dialogue rather than closure actions which you started just recently, given that some PRs have been there for a very long time), I would understand and would close the less-important ones myself. The only instance I remember you suggesting closure of some PRs was when they were dealing with the same issue in different modules, but you were not asked to take them into consideration first, and it was clear they all depend on #12487 thus does not consume your time, any by the way, you froze that PR as well since 27 days until the moment...
- If you left at least one PR open, which you currently take under consideration, I would somehow understand.

I suppose admins shall act professionally, and I wonder if this is the case here..

**Comment by cv3d** [comment]
@vpisarev Now that I have calmed down from the why-to-close-without-discussion state, I believe I owe you an apology for irritating you by making some PRs that I failed to proof their usefulness, and instead, just argued about their usefulness... I can understand how you feel about them, and how it sounds like only-wasting-your-time, but I still hope you would consider at least the good intent behind them. On the other hand, I ask you to excuse me if I felt you are taking it personally, since PRs are supposed to be separated entities from their authors and should be handled solely based on their respective content.

That being said, I really appreciate the time and efforts of all admins and contributors, including you, @alalek and @tomoaki0705 to name a few, in this open society which I wish to be part of as well, as I believe we all have the same goal: making OpenCV better.

**Comment by vpisarev** [comment]
@cv3d, it's good that there is some understanding now.

We host opencv repository on github since 2012, I believe, and during those 6 years we merged many thousands of PRs from hundreds of contributors. Believe it or not, this is the _only_ case of "PR spam" that I remember. So if you think that we treat you somehow differently - this is absolute true; we have to, unfortunately.

Now, we are releasing OpenCV 4.0 beta very soon and 4.0 final in the end of October - beginning of November (work week 44). So, before work week 45 (November 5th), please, do not submit any PRs and do not submit any questions. We have really a lot of work to do, and we do not want to be distracted. After that we can try to resume our collaboration, with the following important rules:

1. each PR that is just "changes for the sake of changes" to make you look more active and more valuable contributor than you really are, e.g. adding extra digits to constants CV_PI etc., replacing tabs with spaces, replacing NULL with nullptr, adding support for new data types to existing functions etc. will be closed down immediately and we will have to review perspectives of our further collaboration once again, and probably for the last time.

2. each PR that might be useful but changes dozens or hundreds of files should be done _only_ after conversation by e-mail or in our bug tracker (http://github.com/opencv/opencv/issues) and _only_ _after_  our explicit approval. Also, please, do not submit PRs that depend on other PRs that are being reviewed. We ourselves do it sometimes, but very rarely; you made it a regular practice and that just makes our backlog of PRs a real mess.

3. ideal PRs that can be submitted after Nov 5th are bug fixes, optimizations etc. For now, please, do not add any new features and do not do any refactoring. I shall warn your again here that we will have to react and we will react on any attempt to artificially boost your visibility by spamming us with PRs.

**Comment by cv3d** [comment]
@vpisarev I am afraid this message would not please you, but sometimes, we need to consider our actions as well.. Please bear with me, and kindly read through the message I want to convey to you.

If one side gives an apology, it does not mean the other side is allowed to continue oppression, or forget about own faults!  Yes, you got my apology that I proposed some PRs without proving their usefulness, but that does not mean you are not overreacting here, and taking the last two PRs as a chance to attack all my contributions, framing them as spam or mere questions.. Unfortunately, you did not stop there, but after receiving an apology, you started attacking me personally as someone who "looks more valuable than what he really is"... I believe there is no employer who might list **insulting others** as part of an employee duties in any job, anywhere!

If you cannot be just, or admit your overreacting and over generalization, then how about at least be professional, and discuss any concerns you have in corresponding PRs, not here, without involving your feelings towards the author or your resistance towards external contributions that touch the core of the library? 

> make you look more active and more valuable contributor than you really are

If I were you, I would not take the chance of a tabulation changes to attack the person, rather, I would forget about people and separate my job from my feelings, and only focus about the potential PRs proposed.. After all, all PRs are not the same even if proposed by the same author, are they?

Again, if you have any concern with any particular PR, then kindly be asked to discuss it there, rather than giving unjust generalizations. Let's be professional, not straw men!

@vpisarev @alalek @mshabunin @dkurt @pengli
All I ask for is a professional consideration of #12729 for a merge. Can anyone of you kindly do that? Thank you very much for your time and efforts in advance.

**Pull request closed without merging**
