### PR TITLE
updating python tutorials + providing necessary data

### PR DESCRIPTION
**Pull request by StevenPuttemans**
Solves an issue reported at the [Q&A](http://answers.opencv.org/question/72388/where-to-get-simplejpg) where several images, related to the python tutorials are missing.

Stilling missing and not able to retrieve:

[Geometric Transformations of Images](http://docs.opencv.org/master/da/d6e/tutorial_py_geometric_transformations.html) is missing: drawing.png

[Image Thresholding](http://docs.opencv.org/master/d7/d4d/tutorial_py_thresholding.html) is missing: noisy2.png

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
For the moment, the `noisy2.png` and `drawing.png` are still missing and could not be retrieved from the web...

**Comment by sovrasov** [comment]
Why did you add a copy of `768x576.avi`? I think that `768x576.avi` should be renamed into `vtest.avi`.

**Comment by StevenPuttemans** [comment]
Ah damn that was what I was aiming for! Will fix it.

**Comment by sovrasov** [comment]
:+1:

**Comment by StevenPuttemans** [comment]
Thank you!

**Comment by earv94** [comment]
this is the real noisy2.png? http://esl.ait.ac.th/courses/AT74.06/noisy2.png

**Pull request merged**
