### PR TITLE
Fix undefined behavior in line drawing.

### PR DESCRIPTION
**Pull request by vrabaud**
Shifts of negative values are implementation defined until C++20 as detailed at https://en.cppreference.com/w/cpp/language/operator_arithmetic#Bitwise_shift_operators.
Left shift can be replaced by a multiplication while for right shift, we make sure that we always shift a positive value.
A test is useless as there is no UBSAN on the build farm.

This is a follow-up on https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44270
and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44386

The pull request #21512 was incomplete.

As shown here: https://godbolt.org/z/zhcj4h1xz, there is no speed regression.

### Pull Request Readiness Checklist

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work

### CODE REVIEW

**Comment by vrabaud** [comment]
The buildfarm error is unrelated: https://pullrequest.opencv.org/buildbot/builders/precommit_android/builds/31012/steps/init/logs/stdio

**Comment by vrabaud** [comment]
I added a link to cppreference in the description.

**Comment by vrabaud** [comment]
@vpisarev , do we give up on that ?

**Comment by vpisarev** [comment]
@vrabaud, @asmorkalov, I suggest to close it and put necessary flags to the tool instead. There are many places in OpenCV where we perform right shift on positive and negative values and expect the shift operation to fill the most significant bits with the sign bit. I don't know of a single architecture where it's different. I suspect that a lot of software uses the same assumption, so it must be a flag to disable such warnings.

**Pull request closed without merging**
