### PR TITLE
support saving 32FC1 as tiff image, fix issue 7762

### PR DESCRIPTION
**Pull request by jasjuang**
fix issue #7762

### CODE REVIEW

**Comment by alalek** [comment]
> img.convertTo(img8U, CV_8UC1);

**Implicit** unexpected data loss **in encoders** must be avoided.

IMHO, `isFormatSupported` should be extended to support channels information too (possible problems related to ABI should be workarounded).

**Comment by vpisarev** [comment]
it may be also confusing, because some people assume that floating-point images have value range `[0, 1]`, i.e. 0 is black and 1 is white, not `[0, 255]`. So, this patch cannot be accepted in the current form

**Comment by jasjuang** [comment]
@vpisarev  OpenCV is able to save CV_32FC1 mat into pngs and jpgs as if it's CV_8UC1, and this is verified by reading it back with imread. I am not sure how OpenCV handles it, but couldn't we apply the same process to tiffs?

**Comment by vpisarev** [comment]
We decided not to put such implicit conversion into OpenCV. Please, call Mat::convertTo() prior to imwrite().

**Pull request closed without merging**
