### PR TITLE
DNN(ONNX): Enabled several OpenCL conformance tests

### PR DESCRIPTION
**Pull request by alexlyulkov**
The tests also work in 5.x

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by opencv-alalek** [comment]
Please add "DNN(ONNX): " prefix due to misleading of current commit message.

**Comment by asmorkalov** [comment]
I tested the patch with integrated Intel GFX (Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz):
```
./bin/opencv_test_dnn --gtest_output=xml:./test_dnn.xml --gtest_filter=Test_ONNX_conformance*
...
[  FAILED  ] 15 tests, listed below:
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_logsoftmax_large_number_OCV_OCL_FP16, where GetParam() = (test_logsoftmax_large_number, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_logsoftmax_large_number_expanded_OCV_OCL_FP16, where GetParam() = (test_logsoftmax_large_number_expanded, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_pow_OCV_OCL_FP16, where GetParam() = (test_pow, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_reduce_prod_default_axes_keepdims_example_OCV_OCL_FP16, where GetParam() = (test_reduce_prod_default_axes_keepdims_example, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_reduce_prod_default_axes_keepdims_random_OCV_OCL_FP16, where GetParam() = (test_reduce_prod_default_axes_keepdims_random, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_reduce_prod_do_not_keepdims_random_OCV_OCL_FP16, where GetParam() = (test_reduce_prod_do_not_keepdims_random, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_reduce_prod_keepdims_random_OCV_OCL_FP16, where GetParam() = (test_reduce_prod_keepdims_random, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_reduce_prod_negative_axes_keepdims_random_OCV_OCL_FP16, where GetParam() = (test_reduce_prod_negative_axes_keepdims_random, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_reduce_sum_square_default_axes_keepdims_random_OCV_OCL_FP16, where GetParam() = (test_reduce_sum_square_default_axes_keepdims_random, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_reduce_sum_square_do_not_keepdims_random_OCV_OCL_FP16, where GetParam() = (test_reduce_sum_square_do_not_keepdims_random, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_reduce_sum_square_keepdims_random_OCV_OCL_FP16, where GetParam() = (test_reduce_sum_square_keepdims_random, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_reduce_sum_square_negative_axes_keepdims_random_OCV_OCL_FP16, where GetParam() = (test_reduce_sum_square_negative_axes_keepdims_random, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_softmax_large_number_OCV_OCL_FP16, where GetParam() = (test_softmax_large_number, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_softmax_large_number_expanded_OCV_OCL_FP16, where GetParam() = (test_softmax_large_number_expanded, OCV/OCL_FP16)
[  FAILED  ] Test_ONNX_conformance.Layer_Test/test_tan_OCV_OCL_FP16, where GetParam() = (test_tan, OCV/OCL_FP16)

```

**Comment by asmorkalov** [comment]
@alexlyulkov friendly remined.

**Review by asmorkalov — APPROVED** [review]

**Comment by asmorkalov** [comment]
Tested with Intel(R) Core(TM) i3-7100U and integrated graphics.

**Pull request merged**
