### PR TITLE
Opening development branch for OpenCV 4.x

### PR DESCRIPTION
**Pull request by alalek**
[OpenCV 4.0 overview/planning](https://github.com/opencv/opencv/wiki/OE-4.-OpenCV-4)

Code branch changes:
- master: OpenCV 4.x development branch
- 3.4: code for next OpenCV 3.4.x maintenance releases. Changes on this branch will be merged into master regularly (~weekly/biweekly) until release of OpenCV 4.0 (4.1?).
- 2.4 (no changes): we accepting critical bug fixes only

Wiki pages:
- [How_to_contribute](https://github.com/opencv/opencv/wiki/How_to_contribute)
- TODO: [Coding style guide](https://github.com/opencv/opencv/wiki/Coding_Style_Guide) updates for OpenCV 4.x: C++11, auto, `parallel_for()` with lambda, migration to C++ classes (`cv::Ptr`/`cv::String`/`cv::Mutex`/etc)

```
allow_multiple_commits=1
docker_image:Custom=ubuntu-cuda:16.04
```

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by hrnr** [comment]
nice, really looking forward to OpenCV 4.0. What is the plan for cv::String? Is it really going away?

**Comment by StevenPuttemans** [comment]
@alalek just wanted to point out that this broke down a lot of packages like caffe, if you built those with latest master, by forcing C++11 compiler. Its kind of weird that the master still has 3.4.11 tag and thus people do not expect that ... might want to add a tag for certainty!

Errors that occur:

```
/usr/local/include/opencv2/core/cvdef.h:421:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"  #  error "OpenCV 4.x+ requires enabled C++11 support"
```

and then followed by a shitload of others :dagger:

**Comment by StevenPuttemans** [comment]
ow and if you want to test quickly, this is the docker file

```
FROM nvidia/cuda:8.0-cudnn5-devel

# Then reload everything
RUN apt update -y
RUN apt upgrade -y

# Pre-requisites
RUN apt install -y vim git cmake \
libprotobuf-dev protobuf-compiler libleveldb-dev libsnappy-dev \ 
libhdf5-serial-dev  libboost-all-dev \
libopenblas-dev libatlas-base-dev \
libgflags-dev libgoogle-glog-dev liblmdb-dev \
libtbb2 libtbb-dev libhdf5-dev

# Pre-install OpenCV3 for image handling
WORKDIR /home/Github/
RUN git clone https://github.com/opencv/opencv.git
WORKDIR /home/Github/opencv
RUN mkdir build
WORKDIR /home/Github/opencv/build
RUN cmake -DWITH_TBB=ON -DCUDA_ARCH_BIN=6.1 -DCUDA_ARCH_PTX=6.1 -DENABLE_IMPL_COLLECTION=ON -DTBB_ENV_INCLUDE=/usr/include -DTBB_ENV_LIB=/usr/lib/x86_64-linux-gnu/libtbb.so -DTBB_VER_FILE=/usr/include/tbb/tbb_stddef.h ..
RUN make -j $(nproc)
RUN make install

# Install a valid caffe installation
WORKDIR /home/Github
RUN git clone https://github.com/StevenPuttemans/caffe-segnet-cudnn5/
WORKDIR /home/Github/caffe-segnet-cudnn5
RUN ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial.so /usr/lib/x86_64-linux-gnu/libhdf5.so
RUN ln -s /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so /usr/lib/x86_64-linux-gnu/libhdf5_hl.so
RUN make -j $(nproc) all
```

**Comment by StevenPuttemans** [comment]
Adding a checkout on 3.4.0 seems to solve it for now

**Comment by alalek** [comment]
> Adding a checkout on 3.4.0

That is:

```
git checkout 3.4
```

to use the latest 3.4.x code.

**Pull request merged**
