### PR TITLE
cmake: enable c++ 11 by default

### PR DESCRIPTION
**Pull request by sovrasov**
**WIP**
Test

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
@sovrasov just wondering why OpenCV all of a sudden decided to do this? Still a lot of systems based on OpenCV have no C++11 support embedded. That was the main idea behind not switching I know of. Can you elaborate?

**Comment by sovrasov** [comment]
The final decision hasn't been accepted yet. This PR is just a test.

**Comment by StevenPuttemans** [comment]
> The final decision hasn't been accepted yet. This PR is just a test.

:+1:  uhu, but still it might be nice to know why we are considering to move on?

**Comment by sovrasov** [comment]
OpenCV is very conservative library and there are plans to change this before 4.0 release. That's all I can say for now.

**Comment by dkurt** [comment]
I think that we can close it now. C++11 has been enabled by default starts from OpenCV 4.

**Pull request closed without merging**
