### PR TITLE
Solves #19754

### LINKED ISSUE #19754: Wasm perf tests RuntimeError: abort(TypeError: cv.Size is not a constructor).
I am attempting to run perf tests using node. I think I built with:

`emcmake python3 platforms/js/build_js.py build_wasm --build_wasm --simd --build_wasm_intrin_test --build_perf `

using emscripten 2.0.15. 

Everything builds fine, with the perf tests located here: 

`opencv/build_wasm/bin/perf`

In fact from here I can launch a server and use a chrome (after enabling flags for "experimental-webassembly-features", "webassembly-simd", and "webassembly-threads") and run a test such as perf_threshold.js

However when I go into the same folder and try to run with node ... first doing "npm install" and then running from that directory with: 

`node --experimental-w
asi-unstable-preview1  --experimental-wasm-simd --experimental-wasm-threads --experimental-wasm-type-reflection --experimental-wasm-mv   perf_imgproc/perf_threshold.js`

I have two issues/questions. (1) One there is a lot of text printed which clogs and takes a long time to scroll .. I assume it is printing out ascii values for some file being processed but I am only guessing. I assume it is not expected behavior because of the user experience but I am hoping for confirmation. (2) The second thing is that there is the same runtime error reported no matter the test `RuntimeError: abort(TypeError: cv.Size is not a constructor)`. I thought my version of node (the very latest release) was using too old a V8 since it was older than Chromes, but even after downloading head the error remains. I assume I am just running wrong, but I followed instructions here:  https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html.

### PR DESCRIPTION
**Pull request by lionkunonly**
resolves #19754

This is a Pull Request for the Issue 19754

For the perf tests in OpenCV.js, the scripts can not run successfully on Node.js. In this PR, I modify the scripts in perf tests so that the functions imported from other modules can run successfully in perf tests.

<cut/>

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
buildworker:Docs=linux-4,linux-6
build_image:Docs=docs-js:18.04
build_image:Custom=javascript
buildworker:Custom=linux-4,linux-6
```

### CODE REVIEW

**Comment by alalek** [comment]
@lionkunonly Thank you!

@jlb6740 Could you please check this patch in your environment?

**Comment by jlb6740** [comment]
Hi @alalek @lionkunonly, sorry only noticed this update here. Yes!  I tried the patch and indeed it appears to resolve the issue. The steps I followed were:

#using emscripten 2.0.15
emcmake python3 platforms/js/build_js.py build_wasm --build_wasm --simd --build_wasm_intrin_test --build_perf

cd build_wasm/bin/perf

# using node 14.15.5
node --experimental-wasi-unstable-preview1 --experimental-wasm-simd --experimental-wasm-threads --experimental-wasm-type-reflection --experimental-wasm-mv --wasm-atomics-on-non-shared-memory perf_imgproc/perf_threshold.js

I also tested cvtColor.js which worked fine.

**Comment by alalek** [comment]
@jlb6740 Thank you for checking this!

@lionkunonly
This patch should go into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first.
We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

Please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

**Comment by alalek** [comment]
@lionkunonly I'm not able to update PR source branch because [your fork](https://github.com/lionkunonly/opencv) is not forked from opencv/opencv repository:

```
lionkunonly / opencv
forked from huningxin/opencv
```

You can grab rebased commit from here: https://github.com/alalek/opencv/commits/pr19771_r

**Review by alalek — APPROVED** [review]

**Pull request merged**
