### PR TITLE
VideoCapture get property with range and default value support

### LINKED ISSUE #15219: where to get the value range of property of VideoCapture::set(id, value)?
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

### PR DESCRIPTION
**Pull request by iamgd67**
**RFC**
resolves #15219
### This pullrequest changes

VideoCapture get properties support range and default value, add msmf and dshow backend implemention

### CODE REVIEW

**Comment by iamgd67** [comment]
@alalek are we waiting others opinion?

**Comment by iamgd67** [comment]
@mshabunin could you please help review this pr? It has been opened for some days and not know what to continue.

**Comment by mshabunin** [comment]
@iamgd67 , similar problem have been addressed differently in V4L backend:
https://github.com/opencv/opencv/blob/2fef9bc1d8ba47d253a034b9efcb26591d6011a6/modules/videoio/src/cap_v4l.cpp#L1779-L1791

VideoCapture can be switched to NORMALIZED_PROPERTIES mode and selected properties will accept and return values from range `[0, 1]`:
https://github.com/opencv/opencv/blob/2fef9bc1d8ba47d253a034b9efcb26591d6011a6/modules/videoio/src/cap_v4l.cpp#L323-L330

I think it is better to use similar approach in other backends.

**Comment by asmorkalov** [comment]
@alalek @asmorkalov @vpisarev @vladimir-dudnik decided to close the PR on weekly meeting by the following reasons:
- The solution breaks compatibility and the same functionality can be achieved with several `cv::VideoCapture::get()` calls.
- The solution is proposed for one backend only and does not cover other cases.

**Pull request closed without merging**
