### PR TITLE
Add Python support for error message handlers.

### PR DESCRIPTION
**Pull request by dan-masek**
Based on [this StackOverflow question](https://stackoverflow.com/questions/49602465/how-to-stop-opencv-error-message-from-printing-in-python) I took an inspiration in the current `highgui` callback wrappers, and implemented a wrapper for `cv::redirectError`.

I attempted to address the concerns I've raised in issues #11205 and #11206, and also added support for resetting to a default handler.

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for the contribution!

> redirectError(onError [, param])

"param" is not needed in Python. Language itself supports closures, so no need to pass "userData" or similar things.
(we plan to drop these "param" args from other functions with callbacks in the future releases).

**Comment by alalek** [comment]
BTW, `redirectError` is C API legacy function.
Consider using Python "try/except" instead.

**Comment by dan-masek** [comment]
"Consider using Python "try/except" instead."

That's not the point, setting a custom error handler doesn't stop the exceptions. The main intent is to stop the default error handler from printing into stderr even when you catch the exception.

See: https://github.com/opencv/opencv/blob/3.4.1/modules/core/src/system.cpp#L888

As far as I can see, this is the simplest way to solve it, given that the functionality already exists and just misses a Python binding.

**Comment by dan-masek** [comment]
Implemented your suggestions.

Here is a Python script to show the functionality:

```
import cv2
from functools import partial

def verbose_error_handler(status, func_name, err_msg, file_name, line):
    print "Status = %d" % status
    print "Function = %s" % func_name
    print "Message = %s" % err_msg
    print "Location = %s(%d)" % (file_name, line)
    
def extended_error_handler(status, func_name, err_msg, file_name, line, userdata):
    verbose_error_handler(status, func_name, err_msg, file_name, line)
    print "User Data = %s" % userdata
    
def silent_error_handler(status, func_name, err_msg, file_name, line):
    pass
    

print "** Default handler"
try:
    cv2.imshow("", None) # This causes an assert
except cv2.error as e:
    pass

print "** Using verbose handler"
cv2.redirectError(verbose_error_handler)
try:
    cv2.imshow("", None) # This causes an assert
except cv2.error as e:
    pass
    
print "** Using extended handler"
cv2.redirectError(partial(extended_error_handler, userdata=42))
try:
    cv2.imshow("", None) # This causes an assert
except cv2.error as e:
    pass

print "** Using silent handler"
cv2.redirectError(silent_error_handler)
try:
    cv2.imshow("", None) # This causes an assert
except cv2.error as e:
    pass

print "** Back to default handler"
cv2.redirectError(None)
try:
    cv2.imshow("", None) # This causes an assert
except cv2.error as e:
    pass

```

Output:

```
** Default handler
OpenCV(3.4.1) Error: Assertion failed (size.width>0 && size.height>0) in cv::imshow, file F:\GitHub\opencv\modules\highgui\src\window.cpp, line 364
** Using verbose handler
Status = -215
Function = cv::imshow
Message = size.width>0 && size.height>0
Location = F:\GitHub\opencv\modules\highgui\src\window.cpp(364)
** Using extended handler
Status = -215
Function = cv::imshow
Message = size.width>0 && size.height>0
Location = F:\GitHub\opencv\modules\highgui\src\window.cpp(364)
User Data = 42
** Using silent handler
** Back to default handler
OpenCV(3.4.1) Error: Assertion failed (size.width>0 && size.height>0) in cv::imshow, file F:\GitHub\opencv\modules\highgui\src\window.cpp, line 364

```

**Comment by alalek** [comment]
@dan-masek I added small test based on your code snippets.

**Comment by dan-masek** [comment]
@alalek Good call. Thanks.

**Comment by srihamat** [comment]
Sorry to disturbed, but since this change was merged into main OpenCV, why do I still cannot redirect error from opencv cpp raised error which I use python ? does someone already overwrite it back or make it's not working at all ?

**Comment by sturkmen72** [comment]
it works on Python 3

```
import numpy as np
import cv2
from functools import partial

def verbose_error_handler(status, func_name, err_msg, file_name, line):
    print("Status = %d" % status)
    print("Function = %s" % func_name)
    print("Message = %s" % err_msg)
    print("Location = %s(%d)" % (file_name, line))
    
def extended_error_handler(status, func_name, err_msg, file_name, line, userdata):
    verbose_error_handler(status, func_name, err_msg, file_name, line)
    print("User Data = %s" % userdata)
    
def silent_error_handler(status, func_name, err_msg, file_name, line):
    pass
    

print("** Default handler")
try:
    cv2.imshow("", None) # This causes an assert
except cv2.error as e:
    pass

print("** Using verbose handler")
cv2.redirectError(verbose_error_handler)
try:
    cv2.imshow("", None) # This causes an assert
except cv2.error as e:
    pass
    
print("** Using extended handler")
cv2.redirectError(partial(extended_error_handler, userdata=42))
try:
    cv2.imshow("", None) # This causes an assert
except cv2.error as e:
    pass

print("** Using silent handler")
cv2.redirectError(silent_error_handler)
try:
    cv2.imshow("", None) # This causes an assert
except cv2.error as e:
    pass

print("** Back to default handler")
cv2.redirectError(None)
try:
    cv2.imshow("", None) # This causes an assert
except cv2.error as e:
    pass

image = np.zeros((200, 200, 3), dtype = np.uint8)
cv2.imshow("", image)
cv2.waitKey()
```

**Pull request merged**
