### PR TITLE
backport to 3.4 for supporting yolov4x-mish

### PR DESCRIPTION
**Pull request by erikguo**
To fix for #19876 

@asmorkalov 

<cut/>

<details>

```
force_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2021.2.0:20.04
build_image:Custom Win=openvino-2020.3.0
build_image:Custom Mac=openvino-2021.3.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

</details>

### CODE REVIEW

**Comment by arnaud-nt2i** [comment]
@alalek @YashasSamaga @asmorkalov up for merging

**Comment by arnaud-nt2i** [comment]
@alalek @YashasSamaga @asmorkalov @dkurt Why is merging is still blocked If all checks have passed ?

**Comment by alalek** [comment]
@arnaud-nt2i Please read the contribution guidelines first.

**Comment by arnaud-nt2i** [comment]
> @arnaud-nt2i Please read the contribution guidelines first.

I have read them and indeed, since all checks have passed, i'm confused about why no reviewers are assigned...

Sorry to sound pushy, I just wanted to make sure the subject wasn't buried

**Comment by alalek** [comment]
Checks passed because there are no checks for added functionality.
Reviewers should not accept changes of new functionality without the tests.
There is red label for this PR. I believe anyone can see that.

This PR is incomplete.

**Comment by arnaud-nt2i** [comment]
> Checks passed because there are no checks for added functionality.
> Reviewers should not accept changes of new functionality without the tests.
> There is red label for this PR. I believe anyone can see that.
> 
> This PR is incomplete.

ok thank you very much for your explanations

**Comment by asmorkalov** [comment]
@erikguo Friendly reminder about tests.

**Comment by asmorkalov** [comment]
@erikguo Friendly reminder.

**Comment by rogday** [comment]
Replaced by https://github.com/opencv/opencv/pull/20671

**Pull request closed without merging**
