### PR TITLE
add new frontal face detection model, VISAPP2017 contribution

### PR DESCRIPTION
**Pull request by StevenPuttemans**
Adding a newly generated frontal face model that is more robust and efficient than the currently existing one inside the OpenCV repository, based on cascade classifiers and local binary pattern features. We only introduce our most advanced detection model, called `IterativeHardPositives+` inside the paper.

This model is part of the paper `Improving Open Source Face Detection by Combining an Adapted Cascade Classification Pipeline and Active Learning` where we aimed at improving open source frontal face detection and make it publicly available.

Some results when comparing the performance:

 * Precision-Recall curve on the FDDB face dataset, compared to OpenCV and our in between models

overall

 * True Positive Rate curves (evaluation metric of FDDB face dataset) comparing our improvement towards recent deep neural network based approaches

tprcurves

 * We investigated our improvement in invariance towards slight deformations from a clear frontal view compared to the original OpenCV model

rotation

The paper is currently submitted and accepted as a short paper to appear in the conference proceedings of the `12th International Conference on Computer Vision Theory and Applications`. Once the paper has been presented, the full text version will be available through the proper channels.

**_Thanks to @canergun for helping me in creating this model and the accompanied research!_**

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Ping :dancer:

**Comment by StevenPuttemans** [comment]
Ello @vpisarev and @alalek is there a reason why this is being left in the cold? xD

**Comment by vpisarev** [comment]
:+1:

**Comment by StevenPuttemans** [comment]
@vpisarev thank you!

**Pull request merged**
