### PR TITLE
Added exposure and gain props, maximized pixel clk

### PR DESCRIPTION
**Pull request by nibeh**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@andy-held Have you have a chance to look at the patch?

**Comment by andy-held** [comment]
Yeah, I gave it a thumbs-up : )

I would even have said that pixel clock maximization makes sense currently, while there is no direct way to modify it. But I would accept it either way. Very nice that people use this.

**Review by asmorkalov — APPROVED** [review]

**Comment by asmorkalov** [comment]
@alalek Could you merge the patch?

**Pull request merged**
