### PR TITLE
findEssentialMatrix: 2 camera matrices

### PR DESCRIPTION
**Pull request by vpisarev**
updated variant of #17551 by @tompollok with a little smoke test for the new function.

<cut/>

### Pull Request Readiness Checklist

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by tompollok** [comment]
Thanks for adding the tests. Keep in mind the threshold issue that i explained in the closed PR. Any idea of how to deal with this?

**Comment by tompollok** [comment]
Btw five-point.cpp has 18 locations of cv:: usage. Shouldnt it be completely removed according to opencv coding style. Should i make a separate pr after merge or do you want to fix it within this pr.

**Comment by asmorkalov** [comment]
@tompollok I propose to stay as is to fix only one issue at a time.

**Comment by vpisarev** [comment]
@tompollok, you are welcome :)

regarding the RANSAC threshold:
1. first of all, the threshold is exposed. Users can adjust it if they get bad results
2. in this GSoC we have RANSAC improvement projects. One of things that we will probably do is make the new RANSAC algorithm to find the proper threshold automatically. That would be, of course, the best solution.

on the "cv::" use – we can easily fix it afterwards, no problem :)

**Comment by vpisarev** [comment]
:+1:

**Comment by vpisarev** [comment]
@tompollok, btw, what do you think about possible modification of your function where after point undistortion we scale points again to bring them to some average matrix matrix between the two supplied ones (?), e.g.

```
[(fx1 + fx2)/2, 0, (cx1+cx2)/2;
0, (fy1+fy2)/2, (cy1+cy2)/2;
0, 0, 1]
```
at least, in this case the supplied threshold should be more relevant, as the difference in focal length between the camera matrices is likely within 2x, it's not 1000x difference between a typical camera matrix and the unity matrix.

**Comment by tompollok** [comment]
@vpisarev That could be a temporal solution until ransac has improved without additional exposure of parametes.
Aren't normalized values better for solving linear systems? I dont know if these values are normalized internally again.
But your approach seems a bit better than scaling the thresh value.

**Comment by tompollok** [comment]
Once this is ready, i would also like to add a variant of recoverPose that decomposes the essential matrix and outputs cv::Mat& R, cv::Mat& t. Are these changes planned for 4.4?

**Comment by tompollok** [comment]
maybe a short comment would be good in case somebody ever tries to understand what and why its being done? also a comment in the documentation might helpful.

**Comment by vpisarev** [comment]
@tompollok, good point! done!

**Comment by vpisarev** [comment]
regarding your question about 4.4. Not sure. Hopefully, this will be merged into 4.4. If not, we will merge it after and use for 4.5/5.0. 4.4. is going to be out this week

**Comment by tompollok** [comment]
Ok lets see. How about python bindings? Is there something that has to be done to make this function available in python?

**Comment by asmorkalov** [comment]
`CV_EXPORTS_W` macro triggers wrapping to Python and java. It'll be great if you add Python and Java tests to ensure that function is called without crash at least. C++ accuracy test is usually enough. Python tests for calib3d: https://github.com/opencv/opencv/tree/master/modules/calib3d/misc/python/test, Java tests: https://github.com/opencv/opencv/tree/master/modules/calib3d/misc/java/test

**Comment by vpisarev** [comment]
@tompollok, @asmorkalov, I suggest to add Python bindings later. If we agree on the C++20/GCC/Clang trick for OpenCV 5, I would prefer to make a single findEssentialMat function with structure of parameters and wrap it.

**Comment by tompollok** [comment]
Does that mean that opencv 5 will require C++20?

**Comment by vpisarev** [comment]
@tompollok, nope, the minimum required version will still be C++11. C++20 (or GCC or clang) users will probably get some extra syntactic sugar

**Comment by asmorkalov** [comment]
@mshabunin Could you take a look.

**Pull request merged**
