### PR TITLE
Fix for cv_videowriter filename pattern issue in Android when digits are missing

### PR DESCRIPTION
**Pull request by isatyamks**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by shyama7004** [comment]
You should remove the trailing spaces to avoid doc build error.

**Comment by isatyamks** [comment]
@shyama7004 The issue has been resolved. Kindly review it and proceed with the merge if everything looks correct

**Comment by isatyamks** [comment]
@asmorkalov The issue(#26606) has been resolved. Kindly review it and proceed with the merge if everything looks correct

**Comment by opencv-alalek** [comment]
Need to revert excessive formatting changes. No way to understand that is really changed.

Keep single commit in PR with clear description. There are should not be "merge" commits in the PRs. Use "git rebase -i" for cleanup.

If there is problem with digits, then it is not related to Android only. It could be reproduced on other platforms too. So prepare reproducer tests.

**Comment by isatyamks** [comment]
@opencv-alalek kindly check the new PR https://github.com/opencv/opencv/pull/26612

**Pull request closed without merging**
