### PR TITLE
fix spelling error

### LINKED ISSUE #11429: Where should I raise the documentation spelling errors?
Ex :

1. You need to figure out when it is safe to release your unused objects and make sure you do so before the program finishes or you could have troublesome memory `leeks`.

Link :  https://docs.opencv.org/3.3.0/df/de5/tutorial_interoperability_with_OpenCV_1.html

2. Luckily OpenCV `threats` these two in the same manner, with the same C++ class. So here's what you'll learn in this tutorial:

Link : https://docs.opencv.org/3.3.0/d5/dc4/tutorial_video_input_psnr_ssim.html

I have found spelling issues(and some grammatical mistakes) in other parts for the documentation as well.

### PR DESCRIPTION
**Pull request by abhi-jha**
resolves #11429

### This pull request changes : 

- An spelling error.

### CODE REVIEW

**Comment by alalek** [comment]
This patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into 3.4 branch. So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).

We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

**Comment by abhi-jha** [comment]
Done. For future reference, should I always commit to 3.4?

**Comment by alalek** [comment]
Yest, if patch contains bug fixes / optimizations or can be applied without breaking of existed functionality / compatibility.

**Comment by abhi-jha** [comment]
Ah. Thanks.

**Pull request merged**
