### PR TITLE
Update solvepnp.cpp

### PR DESCRIPTION
**Pull request by sergarrido**
`useExtrinsicGuess` was not working in `solvePnP()` function in version 2.4.
The parameter was ignored since input vectors `rvec` and `tvec` were being overwritten.

### CODE REVIEW

**Comment by sergarrido** [comment]
I think we dont have to squash our commits anymore for PRs, right?
https://help.github.com/articles/about-pull-request-merge-squashing/

**Comment by alalek** [comment]
Currently we don't use GitHub "Merge" button, so this "magic" is not available.
You need to squash commits yourself.

**Comment by sergarrido** [comment]
Done

**Comment by PhilLab** [comment]
Thanks for the fix!

*(A little OT)* And I think it is good to leave the squashing responsibility to the committer since in some cases a merge is better understandable if it consists of several commits.

**Comment by vpisarev** [comment]
the PR will be reopened because of CI issues

**Pull request closed without merging**
