### PR TITLE
dnn: rename caffe.proto

### PR DESCRIPTION
**Pull request by alalek**
Should resolve caffe issues like [these](https://www.google.com/search?q=File+already+exists+in+database%3A+caffe.proto):
> [libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: caffe.proto

### CODE REVIEW

**Comment by dkurt** [comment]
@alalek, Shall we do the same for TensorFlow definitions?

**Comment by alalek** [comment]
I plan to do this in a separate PR after merging this.

**Comment by vpisarev** [comment]
looks good! :+1:

**Comment by ribalda** [comment]
I am still getting an error when I import cv2 via python

```
root@qt5122:~# python3
Python 3.5.3 (default, Nov 18 2017, 22:27:37) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
[libprotobuf ERROR google/protobuf/descriptor_database.cc:111] Symbol name "caffe.BlobShape" conflicts with the existing symbol "caffe.BlobShape".
[libprotobuf FATAL google/protobuf/descriptor.cc:1315] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
Aborted
root@qt5122:~# 

```

DISCLAIMER: I backported the patch to 3.3.0

**Comment by alalek** [comment]
@ribalda Could you please attach these dumps to GitHub comments (via .txt files):
```
$ LD_DEBUG=files python3 -c 'import cv2'
$ LD_DEBUG=files,symbols python3 -c 'import cv2'
```

**Comment by ribalda** [comment]
@alalek The second command is 320 MB are you sure that you need it?
[files.txt](https://github.com/opencv/opencv/files/1496525/files.txt)

**Comment by alalek** [comment]
@ribalda Could you check this patch: #10139 ?

**Comment by ribalda** [comment]
[renamed.patch.txt](https://github.com/opencv/opencv/files/1496555/renamed.patch.txt)
I am trying with this patch. I will try with that afterwards

**Comment by alalek** [comment]
@ribalda Looks like tests don't pass for mentioned patch =(

**Comment by ribalda** [comment]
as soon as I get some results from my patch I will share it here (and send it as a PR if you want)

**Comment by ribalda** [comment]
Seems that it worked (for me :P)

**Pull request merged**
