### PR TITLE
Fix false positives of face detection network for large faces

### PR DESCRIPTION
**Pull request by dkurt**
### This pullrequest changes

resolves https://github.com/opencv/opencv/issues/15106 after PR https://github.com/opencv/opencv/pull/10216

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/644

<cut/>

before:
out

with changes:
out_correct

### CODE REVIEW

**Comment by dkurt** [comment]
@alalek, perhaps, we will need to update `opencv_face_detector.prototxt` on CI. Or it's better to replace tests to use an origin `deploy.prototxt`?

**Comment by alalek** [comment]
Update file hash here too: https://github.com/opencv/opencv_extra/blob/3.4/testdata/dnn/download_models.py#L227-L229

And probably we need to change target branch to 3.4 in URL (I'll change that to master during 3.4 merging)

**Comment by alalek** [comment]
In case of breaking of existed tests - add and use updated file under a new name, like `opencv_face_detector_20190722.prototxt`.

**Comment by dkurt** [comment]
@alalek, please let's wait for @lubagov feedback before merge.

**Comment by lubagov** [comment]
Red box, with original padding (pad: 0, on both), blu box, from this commit.

Frame_screenshot_23 07 2019

My opinion, `Conv_9 *` does not work at all, although `Conv_8 *` works. I think, if the resolution is less than 300x300, then the image needs to be scaled to 300x300. Or use protopxt, without the last one, or two SSD blocks. Depending on how much less resolution.

**Comment by dkurt** [comment]
@lubagov, Thanks for quick response! May I ask you to share an origin image as well?

**Comment by lubagov** [comment]
tstimg2
OpenCV_screenshot_23 07 2019_1
OpenCV_screenshot_23 07 2019_2

**Comment by lubagov** [comment]
Please check, train.prototxt file also. Because it also has wrong padding, and wrong train network.

**Comment by dkurt** [comment]
@lubagov, Will be fixed by https://github.com/opencv/opencv/pull/14938. Thanks!

**Pull request merged**
