### PR TITLE
imgproc: optimize blend using universal intrinsic

### PR DESCRIPTION
**Pull request by tomoaki0705**
**Merge with opencv_extra**: https://github.com/opencv/opencv_extra/pull/325

### This pullrequest changes
 - optimize blend using universal intrinsic
 - add more channels/depth performance test for blend
 - performance test will follow shortly

### CODE REVIEW

**Comment by tomoaki0705** [comment]
Windows 7 Pro 64bit (Corei7 3720QM 2.60GHz) VS2012
condition|before|after
------|----------|---------
(640x480, 32FC1)|0.80|0.26
(640x480, 32FC3)|1.73|0.80
(640x480, 32FC4)|2.31|1.06
(640x480, 8UC1)|0.62|0.15
(640x480, 8UC3)|1.84|0.51
(640x480, 8UC4)|2.98|0.71
(1280x720, 32FC1)|1.28|1.04
(1280x720, 32FC3)|3.69|2.55
(1280x720, 32FC4)|4.92|3.33
(1280x720, 8UC1)|1.31|0.44
(1280x720, 8UC3)|3.94|1.17
(1280x720, 8UC4)|6.40|1.53
(1920x1080, 32FC1)|2.90|2.45
(1920x1080, 32FC3)|8.26|5.68
(1920x1080, 32FC4)|11.16|7.36
(1920x1080, 8UC1)|3.15|1.25
(1920x1080, 8UC3)|9.46|2.59
(1920x1080, 8UC4)|15.10|3.64
(3840x2160, 32FC1)|11.28|9.62
(3840x2160, 32FC3)|34.56|22.77
(3840x2160, 32FC4)|51.33|29.23
(3840x2160, 8UC1)|13.46|4.86
(3840x2160, 8UC3)|39.58|9.49
(3840x2160, 8UC4)|63.50|13.04

**Comment by alalek** [comment]
> No regression data for dst argument

@tomoaki0705 Could you please add perf sanity data via opencv_extra repository? (run tests with `--perf_write_sanity` option)

**Comment by tomoaki0705** [comment]
@alalek, thank you for your review and your suggestion.
```--perf_write_sanity``` !!  I should have known that great option.

**Comment by alalek** [comment]
Thank you! :+1:

**Pull request merged**
