### PR TITLE
refactor thresh function

### PR DESCRIPTION
**Pull request by vpisarev**
by @K-Shinotsuka:

The purpose is speeding up "thresh function"
I move "if statement" to out of "for loop".
I put "thresh function" together for using template.

### Former #6698

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
> I move "if statement" to out of "for loop".

@K-Shinotsuka, Could you provide more details about what `if` are you talking about? You may refer to original OpenCV code and show the lines.

**Comment by K-Shinotsuka** [comment]
>Could you provide more details about what if are you talking about? You may refer to original OpenCV code and show the lines.

I move "switch( type )  case ~" in " for( i = 0; i < roi.height; i++ )" at thresh_8u() to out of " for( i = 0; i < roi.height; i++ )".
I move "if( useSIMD )" in "for( i = 0; i < roi.height; i++, src += src_step, dst += dst_step )" at thresh_16s() to out of "for( i = 0; i < roi.height; i++, src += src_step, dst += dst_step )"
I move "if( useSIMD )" in "for( i = 0; i < roi.height; i++, src += src_step, dst += dst_step )" at thresh_32f() to out of "for( i = 0; i < roi.height; i++, src += src_step, dst += dst_step )"
I move "switch( type ) case ~" at thresh_xxx() to "ThresholdRunner::operator ()".

>If you are talking about optimization, could you provide performance numbers before and after your changes? 

#I improved to thresh functions.
I measured the clocks.
Please observe the following.

<table border=1>
 <tr><th>Conditions</th><th>Average Clocks (original code)</th><th>Average Clocks (new code)</th><th>Faster Rate (compared with original code)</th></tr>
 <tr><td>16x16,uchar,THRESH_BINARY</td><td>602.8</td><td>444.4</td><td>1.36</td></tr>
 <tr><td>16x16,uchar,THRESH_BINARY_INV</td><td>633.2</td><td>442.4</td><td>1.43</td></tr>
 <tr><td>16x16,uchar,THRESH_TRUNC</td><td>624.0</td><td>439.0</td><td>1.42</td></tr>
 <tr><td>16x16,uchar,THRESH_TOZERO</td><td>667.2</td><td>623.2</td><td>1.07</td></tr>
 <tr><td>16x16,uchar,THRESH_TOZERO_INV</td><td>582.4</td><td>456.4</td><td>1.28</td></tr>
 <tr><td>16x16,short,THRESH_BINARY</td><td>659.4</td><td>456.2</td><td>1.45</td></tr>
 <tr><td>16x16,short,THRESH_BINARY_INV</td><td>651.4</td><td>492.0</td><td>1.32</td></tr>
 <tr><td>16x16,short,THRESH_TRUNC</td><td>605.4</td><td>498.2</td><td>1.22</td></tr>
 <tr><td>16x16,short,THRESH_TOZERO</td><td>700.4</td><td>473.6</td><td>1.48</td></tr>
 <tr><td>16x16,short,THRESH_TOZERO_INV</td><td>689.2</td><td>500.8</td><td>1.38</td></tr>
 <tr><td>16x16,float,THRESH_BINARY</td><td>999.4</td><td>841.6</td><td>1.19</td></tr>
 <tr><td>16x16,float,THRESH_BINARY_INV</td><td>974.8</td><td>795.2</td><td>1.26</td></tr>
 <tr><td>16x16,float,THRESH_TRUNC</td><td>892.4</td><td>746.6</td><td>1.20</td></tr>
 <tr><td>16x16,float,THRESH_TOZERO</td><td>973.6</td><td>830.0</td><td>1.17</td></tr>
 <tr><td>16x16,float,THRESH_TOZERO_INV</td><td>998.4</td><td>825.2</td><td>1.21</td></tr>
</table>

Measurement Conditions
OS : Ubuntu 16.04
Compiler : g++ (Ubuntu 5.3.1-13ubuntu3) 5.3.1 20160330
CPU : Intel(R) Core(TM)2 Duo CPU E8500 @ 3.16GHz
Compiler Option : -msse2 -O3
Measurement Function: rdtsc()

**Comment by vpisarev** [comment]
shall we merge it in?

**Comment by ilya-lavrenov** [comment]
not sure. I dislike the fact that the implementation has been refactored significantly. @K-Shinotsuka, can we achieve the same performance without completely implementation rewriting?

**Comment by K-Shinotsuka** [comment]
@vpisarev 
@ilya-lavrenov 

>not sure. I dislike the fact that the implementation has been refactored significantly. @K-Shinotsuka, 
>can we achieve the same performance without completely implementation rewriting?

I understand it. I will close this pull request.
I will commit the code refactored in small step.

**Comment by vpisarev** [comment]
@K-Shinotsuka, @ilya-lavrenov, yes, this makes sense. Smaller modifications are usually better than the big ones. Especially for such a relatively simple function as threshold, I agree with Ilya that there can be a simpler way to achieve the same results. Let me close this PR than.

**Pull request closed without merging**
