### PR TITLE
Stitching Detailed Tutorial Improvements

### PR DESCRIPTION
**Pull request by lukasalexanderweber**
There are two issues with the code in the tutorial:

1. Vertical wave correction isn't supported but proposed as parameter to the user
2. Changing the confidence threshold isn't supported but proposed as parameter to the user

Both are because of static implementations instead of using the user defined parameters.
Please see the commit descriptions for details.
This Pull request solves both Issues.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by lukasalexanderweber** [comment]
do I have to do change something because of the failed checks?

**Comment by alalek** [comment]
You can ignore "OpenCV CN *" builders results (these failures are not related to this PR).

**Comment by lukasalexanderweber** [comment]
ok thanks!

**Comment by DumDereDum** [comment]
👍

**Review by DumDereDum — APPROVED** [review]
👍

**Pull request merged**
