### PR TITLE
bindings(python): fix handling of 'isalgorithm'

### PR DESCRIPTION
**Pull request by alalek**

### CODE REVIEW

**Comment by vpisarev** [comment]
can you please put here (or put a link to) the problem description that the patch solves?

**Comment by alalek** [comment]
Problem is incorrect implementation. It doesn't properly handle multiple inheritance levels.

For example, `cv::ml::Boost` currently has invalid `isalgorithm = False`, however it is derived from cv::Algorithm:
```
class CV_EXPORTS_W Boost : public DTrees
class CV_EXPORTS_W DTrees : public StatModel
class CV_EXPORTS_W StatModel : public Algorithm
```

**Comment by mshabunin** [comment]
BTW, we have a test for that: https://github.com/opencv/opencv/blob/master/modules/python/test/test_misc.py

**Comment by vpisarev** [comment]
ok, thanks! :+1:

**Pull request merged**
