### PR TITLE
Fix cpu features detection on android

### PR DESCRIPTION
**Pull request by RyuheiMori**
/proc/self/auxv will fail from regular application processes on some Android platform versions.

use cpufeatures library provided by ndk instead.

### CODE REVIEW

**Comment by alalek** [comment]
What Android NDK do you use to extract `cpufeatures` sources?

**Comment by RyuheiMori** [comment]
r15 Beta 2

**Comment by RyuheiMori** [comment]
This issue happens when running 32bit binary on 64 bit platform. I have confirmed the issue with sony z5 (android 7.0)/ samsung s6 /s7 (android 6.0).

https://android.googlesource.com/platform/ndk/+/882ac8f3392858991a0e1af33b4b7387ec856bd2

https://github.com/opencv/opencv/blob/master/modules/core/src/system.cpp#L490
During initialization, opencv will check whether baseline features exist or not.
If not, it abort immediately.

**Comment by alalek** [comment]
@RyuheiMori Hi! I'm sorry for huge delay.

Unfortunately, `cpufeatures` detection uses `dlopen` call.
Currently OpenCV features detection code is processed at library initialization stage (under other `dlopen` call). This pattern is not supported well: recursive dlopen calls hangs on some devices (It hangs on Android 2.2.3, but Android 4.4.3 is fine).

Could you try to remove dlopen call and try again on your device:
```.diff
-void* libc_handle = dlopen("libc.so", RTLD_NOW);
+void* libc_handle = 0;
```

Does other fallback detections work for you?

**Comment by alalek** [comment]
@RyuheiMori Thank you for your effort.

In general, I prefer "cpufeatures" way instead of self-written code.
I have updated library integration code and added hang workaround to cpufeatures.
Could you check this code: https://github.com/opencv/opencv/compare/master...alalek:pr8753 ?
You can fetch my updates via these commands:
```
git fetch https://github.com/alalek/opencv pr8753:alalek_pr8753
git checkout alalek_pr8753
```

**Comment by RyuheiMori** [comment]
OK, it works on my devices

**Comment by alalek** [comment]
@RyuheiMori Thanks for check!

I have updated this patch.
Your last changes are saved here: https://github.com/alalek/opencv/commits/pr8753_origin

**Pull request merged**
