### PR TITLE
replace lena.png in (test,perf)_intelligent_scissors.cpp

### PR DESCRIPTION
**Pull request by cpoerschke**
similar to #25635 issue

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [X] The PR is proposed to the proper branch
- [X] There is a reference to the original bug report and related work
- [X] There is accuracy test, performance test and test data in opencv_extra repository: https://github.com/opencv/opencv_extra/pull/1192
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by cpoerschke** [comment]
Tests pass for me locally but the https://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/106295/steps/test_imgproc/logs/tests%20summary CI finding includes this:

```
Total tests: 1551
Tests failed: 3
Tests passed: 1548
Disabled: 23

List failed tests (first 10):
Imgproc_IntelligentScissorsMB.check_features_grayscale_1_0_0_zerro_crossing_with_limit :
C:\build\precommit_windows64\4.x\opencv\modules\imgproc\test\test_intelligent_scissors.cpp(208): error: Expected: (contoursAreaPixelsMismatch(pts, reference_pts)) <= (allowed_mismatch), actual: 17973 vs 11
Imgproc_IntelligentScissorsMB.check_features_grayscale_1_0_0_canny :
C:\build\precommit_windows64\4.x\opencv\modules\imgproc\test\test_intelligent_scissors.cpp(208): error: Expected: (contoursAreaPixelsMismatch(pts, reference_pts)) <= (allowed_mismatch), actual: 18 vs 6
Imgproc_IntelligentScissorsMB.check_features_grayscale_0_1_0 :
C:\build\precommit_windows64\4.x\opencv\modules\imgproc\test\test_intelligent_scissors.cpp(208): error: Expected: (contoursAreaPixelsMismatch(pts, reference_pts)) <= (allowed_mismatch), actual: 533 vs 4

List passed tests (first 10):
...
```

**Comment by cpoerschke** [comment]
Hmm, again tests pass for me locally but the https://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/106315/steps/test_imgproc/logs/tests%20summary CI finding includes this:

```
Total tests: 1551
Tests failed: 5
Tests passed: 1546
Disabled: 23

List failed tests (first 10):
Imgproc_IntelligentScissorsMB.check_features_grayscale_1_0_0_zerro_crossing_with_limit :
C:\build\precommit_windows64\4.x\opencv\modules\imgproc\test\test_intelligent_scissors.cpp(208): error: Expected: (contoursAreaPixelsMismatch(pts, reference_pts)) <= (allowed_mismatch), actual: 2947 vs 11
Imgproc_IntelligentScissorsMB.check_features_grayscale_1_0_0_canny :
C:\build\precommit_windows64\4.x\opencv\modules\imgproc\test\test_intelligent_scissors.cpp(208): error: Expected: (contoursAreaPixelsMismatch(pts, reference_pts)) <= (allowed_mismatch), actual: 8 vs 6
Imgproc_IntelligentScissorsMB.check_features_grayscale_0_1_0 :
C:\build\precommit_windows64\4.x\opencv\modules\imgproc\test\test_intelligent_scissors.cpp(208): error: Expected: (contoursAreaPixelsMismatch(pts, reference_pts)) <= (allowed_mismatch), actual: 94 vs 4
Imgproc_IntelligentScissorsMB.color_custom_features_all :
C:\build\precommit_windows64\4.x\opencv\modules\imgproc\test\test_intelligent_scissors.cpp(208): error: Expected: (contoursAreaPixelsMismatch(pts, reference_pts)) <= (allowed_mismatch), actual: 15 vs 9
Imgproc_IntelligentScissorsMB.color_custom_features_edge_magnitude :
C:\build\precommit_windows64\4.x\opencv\modules\imgproc\test\test_intelligent_scissors.cpp(208): error: Expected: (contoursAreaPixelsMismatch(pts, reference_pts)) <= (allowed_mismatch), actual: 15 vs 9
```

**Comment by s-trinh** [comment]
> "HappyFish.jpg"

Maybe the issue comes from using jpeg format? I think it does not give bit-exact decoding?

**Comment by asmorkalov** [comment]
Hello @cpoerschke . OpenCV core team discussed the issue with Lena image and decided to not touch existing code for now, but update test data and images together with the code update. It's decided to make performance numbers comparable across releases and reduce opencv_extra changes. See https://github.com/opencv/opencv/wiki/FAQ#social.

**Pull request closed without merging**
