### PR TITLE
add feature to convert FP32(float) to FP16(half) using HW instructions

### PR DESCRIPTION
**Pull request by vpisarev**
### What does this PR change?
Allow user to pack 32 bit float data in to 16bit float data (half)
  * check compiler support
  * check HW support before executing
  * add test doing round trip conversion from / to FP32
  * treat array correctly if size is not multiple of 4
  * add declaration to prevent warning

### CODE REVIEW

**Comment by vpisarev** [comment]
@tomoaki0705, thanks! let's put it in! :+1:

**Comment by alalek** [comment]
There are build failures:
http://pullrequest.opencv.org/buildbot/builders/precommit_pack_android/builds/107/steps/build%20sdk/logs/stdio
```
/Volumes/build-storage/build-2/precommit_pack_android/opencv/modules/core/src/convert.cpp: In function 'void cv::cvtScaleHalf_(const T*, size_t, DT*, size_t, cv::Size) [with T = float; DT = short int; size_t = unsigned int; cv::Size = cv::Size_<int>]':
/Volumes/build-storage/build-2/precommit_pack_android/opencv/modules/core/src/convert.cpp:4591:21: error: 'float16x4_t' was not declared in this scope
                     float16x4_t v_dst = vcvt_f16_f32(v_src);
                     ^
/Volumes/build-storage/build-2/precommit_pack_android/opencv/modules/core/src/convert.cpp:4591:33: error: expected ';' before 'v_dst'
                     float16x4_t v_dst = vcvt_f16_f32(v_src);
                                 ^
/Volumes/build-storage/build-2/precommit_pack_android/opencv/modules/core/src/convert.cpp:4593:35: error: expected primary-expression before ')' token
                     *(float16x4_t*)(dst + x) = v_dst;
                                   ^
/Volumes/build-storage/build-2/precommit_pack_android/opencv/modules/core/src/convert.cpp:4593:48: error: 'v_dst' was not declared in this scope
                     *(float16x4_t*)(dst + x) = v_dst;
                                                ^
/Volumes/build-storage/build-2/precommit_pack_android/opencv/modules/core/src/convert.cpp:4589:33: warning: unused variable 'v_src' [-Wunused-variable]
                     float32x4_t v_src = *(float32x4_t*)(src + x);
                                 ^
/Volumes/build-storage/build-2/precommit_pack_android/opencv/modules/core/src/convert.cpp: In function 'void cv::cvtScaleHalf_(const T*, size_t, DT*, size_t, cv::Size) [with T = short int; DT = float; size_t = unsigned int; cv::Size = cv::Size_<int>]':
/Volumes/build-storage/build-2/precommit_pack_android/opencv/modules/core/src/convert.cpp:4641:21: error: 'float16x4_t' was not declared in this scope
                     float16x4_t v_src = *(float16x4_t*)(src + x);
                     ^
/Volumes/build-storage/build-2/precommit_pack_android/opencv/modules/core/src/convert.cpp:4641:33: error: expected ';' before 'v_src'
                     float16x4_t v_src = *(float16x4_t*)(src + x);
                                 ^
/Volumes/build-storage/build-2/precommit_pack_android/opencv/modules/core/src/convert.cpp:4643:54: error: 'v_src' was not declared in this scope
                     float32x4_t v_dst = vcvt_f32_f16(v_src);
                                                      ^
/Volumes/build-storage/build-2/precommit_pack_android/opencv/modules/core/src/convert.cpp:4643:59: error: 'vcvt_f32_f16' was not declared in this scope
                     float32x4_t v_dst = vcvt_f32_f16(v_src);
```

**Comment by tomoaki0705** [comment]
@vpisarev , thank you for the review.

@alalek , for this build issue, I opened a new PR for this.
Unfortunately, I don't have the Android build environment, but I'm quite confident that that PR will fix it.

**Comment by tomoaki0705** [comment]
I can't believe but as far as I checked, every test of video module is failing since this PR is merged.
May be it's better to revert this PR modification first, or otherwise every single PR to master branch will fail.

I don't understand at all, but the every situation points that this PR caused an issue.

**Pull request merged**
