### PR TITLE
js setup docker build warning and docs instructions

### PR DESCRIPTION
**Pull request by cancerberoSgx**
* js
 * documentation only 
 * adds a warning on building with docker section related to https://github.com/opencv/opencv/issues/14691
 * adds instructions to build the docs with docker

### CODE REVIEW

**Comment by alalek** [comment]
Please change target of this PR onto 3.4 branch + rebase

**Comment by cancerberoSgx** [comment]
I'm creating a new PR from 3.4 branch and closing this one . Thanks

**Comment by alalek** [comment]
Instruction is below:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

**Comment by cancerberoSgx** [comment]
@alalek thanks for the instructions! I think it's done.

**Pull request merged**
