### PR TITLE
Fix bug 6641.

### PR DESCRIPTION
**Pull request by kevin-coder**
resolves 6641

### What does this PR change?
Fix bug 6641 that an endless loop will happen for reading an specific jpg file.

Root cause: In function "getExif", if both of the values for appMarker[0] and appMarker[1] are '\0', this cannot match any of the termination condition. So endless loop will happen

Signed-off-by: Zhenqing, Hu <huzq85@gmail.com>

### CODE REVIEW

**Comment by alalek** [comment]
I believe that real problem is here:
```
default: //No other markers are expected according to standard. May be a signal of error
    break;
```

`break` statement is related to `switch` statement and doesn't break `while` loop, which cause hang.

My suggestion is to:
1) introduce some new flag for `while` statement:
```
bool searchExit = true;
while (... && searchExit)
{
    ...
    switch (...)
    {
    ...
    default:
        searchExit = false; // unexpected input, stop
    }
}

fclose(f);
...
```
2) or replace `default` break with `goto` statement to `fclose` call
3) or replace all `break` statements from `case` blocks to `continue`, remove `default:` block and place while's `break` after switch:
```
while (...)
{
    ...
    switch (...)
    {
    case ...:
         ...
         continue;
    ... other non-default cases ....
    }
    break; // unkown marker, stop while loop
}
...
```

**Comment by kevin-coder** [comment]
hi, @alalek , thank you for your feedback about this PR, and I have following comments about your feedback:
I agree that the issue caused by the "break" statement just impact switch-case, not impact while loop, so that it cannot break the loop. However, do we need to search the entire whole file to find the valid markers? For example, in the following patterns:
=======================
invalidMakers, validMarkers
=======================
seems that based on your comments, when it meet the first invalidMarks, it will break and do not try to find the following validMarkers, then return empty m_exif, but actually in this pattern there is a valid markers.
If it doesn't matter about this (which I have concern about it), I think I accept your comments and will update the PR soon, otherwise, I will try to find another solution and submit PR.

Thanks!

**Comment by eklinger** [comment]
Hello, any idea when this will be merged into master?

**Comment by vpisarev** [comment]
this PR will be reopened because of CI issues

**Pull request closed without merging**
