### PR TITLE
imwrite multipage TIFF files

### LINKED ISSUE #8729: Create write version of of cv::imreadmulti, cv:imwritemulti
Currently we have [cv::imreadmulti](https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/loadsave.cpp#L585) which allows for multi-image Tiff files to be read. I very much like this. Probably the most common use case is to read in a bunch of related images for processing.

It is also useful to write out a vector of images to a single Tiff file. 

My feature request is simple. Signature of proposed addition to [loadsave.cpp](https://github.com/opencv/opencv/blob/master/modules/imgcodecs/src/loadsave.cpp):

`bool imwritemulti(const String& filename, std::vector<Mat>& mats, const std::vector<int>& params)`

`mats` would be written out as a multi-image file. Currently the only multi-image format supported by OpenCV is TIff.

### PR DESCRIPTION
**Pull request by savuor**
resolves #8729

### This pullrequest changes
The old PR #8913 re-created, merge conflicts are fixed

### CODE REVIEW

**Comment by alalek** [comment]
I believe OpenCV should handle most universal cases and "multipage" images case is not one of this. Also it is TIFF only (and perhaps animated GIFs). Image by definition is not multipage (see wiki).
For sequence of images we have VideoCapture/VideoWriter interface, so it is better to deprecate existed imreadmulti API and move multipage TIFF stuff there.

/cc @vpisarev 
see #8511

**Comment by vpisarev** [comment]
actually, I like how it's handled. Without introducing extra function we added extra functionality. Of course, it needs to be properly documented. But the same technique can be used even for animated gifs

**Comment by vpisarev** [comment]
:+1:

**Comment by rounakskm** [comment]
Hi all,
I am fairly new to opencv and am having trouble finding this function.
Could anyone please tell me how to write  a `vector<cv::Mat> `-- where each Mat is a Tiff image -- to one stacked Tiff file?
An example would be much appreciated.

**Comment by savuor** [comment]
@rounakskm Although this place is not for questions and answers (please use answers.opencv.org) I can help you as an exception. You can find an example of usage [here](https://github.com/opencv/opencv/blob/master/modules/imgcodecs/test/test_tiff.cpp#L265)

**Pull request merged**
