### PR TITLE
instrumentation: minor refactoring, wrap common OpenCL calls

### PR DESCRIPTION
**Pull request by alalek**
- calculate ticksTotal instead of ticksMean
- local / global width is based on ticksTotal value
- added instrumentation for OpenCL program compilation
- added instrumentation for OpenCL kernel execution
- fixed builds on Linux with GCC

Output example:
```
[ RUN      ] OCL_BufferPoolFixture_BufferPool_UMatCanny10.BufferPool_UMatCanny10/0
[ PERFSTAT ]    (samples = 38, mean = 62.60, median = 62.25, stddev = 1.71 (2.7%))
[ VALUE    ]    false
[ TRACE    ]
ROOT
\---cv::Canny - C:380 T:7.8229ms
    |---Compile: ab77f867162d4614 options: -D WI...<W_OCL> - C:1 T:170.2362ms L:6% G:6%
    |---stage1_with_sobel<F_OCL> - C:380 T:3.3217ms L:42% G:42%
    |---Compile: ab77f867162d4614 options: -D ST...<W_OCL> - C:1 T:217.2061ms L:7% G:7%
    |---stage2_hysteresis<F_OCL> - C:380 T:1.2031ms L:15% G:15%
    |---Compile: ab77f867162d4614 options: -D GE...<W_OCL> - C:1 T:185.5047ms L:6% G:6%
    \---getEdges<F_OCL> - C:380 T:1.4261ms L:18% G:18%

IPP weight: 0.0%
OPENCL weight: 76.1%
[/TRACE    ]
[       OK ] OCL_BufferPoolFixture_BufferPool_UMatCanny10.BufferPool_UMatCanny10/0 (3035 ms)
[ RUN      ] OCL_BufferPoolFixture_BufferPool_UMatCanny10.BufferPool_UMatCanny10/1
[ PERFSTAT ]    (samples = 13, mean = 63.04, median = 62.74, stddev = 1.42 (2.2%))
[ VALUE    ]    true
[ TRACE    ]
ROOT
\---cv::Canny - C:130 T:6.2848ms
    |---stage1_with_sobel<F_OCL> - C:130 T:3.2723ms L:52% G:52%
    |---stage2_hysteresis<F_OCL> - C:130 T:1.2294ms L:20% G:20%
    \---getEdges<F_OCL> - C:130 T:1.4207ms L:23% G:23%

IPP weight: 0.0%
OPENCL weight: 94.2%
[/TRACE    ]
[       OK ] OCL_BufferPoolFixture_BufferPool_UMatCanny10.BufferPool_UMatCanny10/1 (840 ms)
```

### CODE REVIEW

**Comment by alalek** [comment]
@lupustr3 Pavel, Could you please take a look on this? Output example can be found [here](http://pullrequest.opencv.org/buildbot/builders/precommit_opencl/builds/6805/steps/perf_core-ippicv-opencl/logs/stdio).

**Comment by alalek** [comment]
:+1:

**Comment by lupustr3** [comment]
@alalek Sorry, I didn't see the notification. I will check it as soon as I can. But I suppose instrumentation code lives its own life from now on :)

**Comment by lupustr3** [comment]
@alalek Why did you replaced mean time counter with total time counter? Now it calculates weights for parallel regions incorrectly.

**Comment by alalek** [comment]
@lupustr3 There were problem with incorrect weights calculation for OpenCL branches (kernel compilation is one-time task, as I remember it causes result percents more than 100% for these entries). I will take a look on parallel regions.

**Comment by alalek** [comment]
There some results for `OCL_CannyFixture_Canny.Canny/15` perf test:
- with reverted commit from this patch:
```
ROOT
\---Canny - C:100 T:42.5589ms
    \---parallel_for_ - C:200 T:21.2376ms L:50% G:50%
```
- with this patch (current master):
```
ROOT
\---Canny - C:100 T:40.9775ms
    \---parallel_for_ - C:200 T:20.4462ms L:100% G:100%
```

Do you expect this output or something other?

BTW, I found partially implemented `CV_INSTRUMENT_REGION_MT`. What is purpose of this macro?

**Comment by alalek** [comment]
There is bug in pthreads `parallel_for` backend (instrumentation uses "proxy", but pthreads branch ignores it), so `parallel_for_` tree is truncated in logs above.

Updated logs:
- with reverted commit from this patch:
```
ROOT
\---Canny - C:100 T:42.9849ms
    \---parallel_for_ - C:200 T:21.4472ms L:50% G:50%
        \---Sobel - C:800 T:7.4511ms L:35% G:17%
            |---ipp_sobel<W_IPP> - C:800 T:0.0190ms L:0% G:0%
            |   \---IPPDerivSobel<W_IPP> - C:800 T:0.0009ms L:5% G:0%
            |   
            |---convertTo - C:1600 T:0.0029ms L:0% G:0%
            |   \---ippicviConvert_32s32f_C1R<F_IPP> - C:1600 T:0.0006ms L:21% G:0%
            |   
            \---sepFilter2D - C:800 T:7.4071ms L:99% G:17%
                |---convertTo - C:3200 T:0.0063ms L:0% G:0%
                |   \---ippicviConvert_32f32s_C1RSfs<F_IPP> - C:1600 T:0.0122ms L:195% G:0%
                |   
                \---apply - C:800 T:7.3633ms L:99% G:17%
                    \---borderInterpolate - C:878800 T:0.0001ms L:0% G:0%
```
- with this patch:
```
ROOT
\---Canny - C:100 T:40.6791ms
    \---parallel_for_ - C:200 T:20.2970ms L:100% G:100%
        \---Sobel - C:800 T:7.1323ms L:141% G:140%
            |---ipp_sobel<W_IPP> - C:800 T:0.0018ms L:0% G:0%
            |   \---IPPDerivSobel<W_IPP> - C:800 T:0.0010ms L:53% G:0%
            |   
            |---convertTo - C:1600 T:0.0049ms L:0% G:0%
            |   \---ippicviConvert_32s32f_C1R<F_IPP> - C:1600 T:0.0009ms L:17% G:0%
            |   
            \---sepFilter2D - C:800 T:7.1048ms L:100% G:140%
                |---convertTo - C:3200 T:0.0030ms L:0% G:0%
                |   \---ippicviConvert_32f32s_C1RSfs<F_IPP> - C:1600 T:0.0047ms L:78% G:0%
                |   
                \---apply - C:800 T:7.0781ms L:100% G:139%
                    \---borderInterpolate - C:878800 T:0.0001ms L:1% G:2%
```

Unfortunately, both cases has weight percents above 100%

**Comment by alalek** [comment]
I [added](https://github.com/opencv/opencv/compare/master...alalek:instr_parallel) dummy `parallel_for_body` region and receive this log:
```
ROOT
\---Canny - C:100 T:43.8002ms
    |---parallel_for_ - C:100 T:42.1026ms L:96% G:96%
    |   \---parallel_for_body - C:400 T:34.9895ms L:332% G:320%
    |       \---Sobel - C:800 T:7.4419ms L:43% G:136%
    |           |---ipp_sobel<W_IPP> - C:800 T:0.0128ms L:0% G:0%
    |           |   \---IPPDerivSobel<W_IPP> - C:800 T:0.0009ms L:7% G:0%
    |           |   
    |           |---convertTo - C:1600 T:0.0020ms L:0% G:0%
    |           |   \---ippicviConvert_32s32f_C1R<F_IPP> - C:1600 T:0.0010ms L:47% G:0%
    |           |   
    |           \---sepFilter2D - C:800 T:7.3898ms L:99% G:135%
    |               |---convertTo - C:3200 T:0.0010ms L:0% G:0%
    |               |   \---ippicviConvert_32f32s_C1RSfs<F_IPP> - C:1600 T:0.0008ms L:36% G:0%
    |               |   
    |               \---apply - C:800 T:7.3606ms L:100% G:134%
    |                   \---borderInterpolate - C:878800 T:0.0001ms L:1% G:1%
    |   
    \---finalPass - C:100 T:1.6154ms L:4% G:4%
        \---parallel_for_ - C:100 T:1.6118ms L:100% G:4%
            \---parallel_for_body - C:3200 T:0.1395ms L:277% G:10%
```

This region contains meaningful weight >= 100% (like CPU utilization factor).

Other local weight looks fine (<= 100%).
But global weight is still above 100%. Probably these values should be adjusted by weight of this dummy `parallel_body` region.
Any thoughts?

**Comment by lupustr3** [comment]
parallel_for region requires some special handling for such cases. Its name can be modified to make it unique for each operator:
void cv::parallel_for_(const cv::Range& range, const cv::ParallelLoopBody& body, double nstripes)
{
#ifdef ENABLE_INSTRUMENTATION
    String regionName = __FUNCTION__;
    {
        char buffer[20];
        char *name = _ui64toa((uint64)&body, buffer, 10);
        regionName += name;
    }
    CV_INSTRUMENT_REGION_META(regionName.c_str(), cv::instr::TYPE_GENERAL, cv::instr::IMPL_PLAIN)
#endif

--->
[ TRACE    ]
ROOT
\---cv::Canny - C:100 T:1.5824ms
    |---cv::parallel_for_727398084280 - C:100 T:1.0440ms L:66% G:66%
    |   \---cv::parallelCanny::operator () - C:400 T:0.7422ms L:71% G:47%
    |       \---cv::Sobel - C:800 T:0.0252ms L:3% G:2%
    |           \---cv::ipp_Deriv<W_IPP> - C:800 T:0.0202ms L:80% G:1%
    |               \---::ipp::iwiFilterSobel<F_IPP> - C:800 T:0.0144ms L:71% G:1%
    |
    \---cv::parallel_for_727398084408 - C:100 T:0.3152ms L:20% G:20%
        \---cv::finalPass::operator () - C:500 T:0.1466ms L:47% G:9%

IPP weight: 0.9%
OPENCL weight: 0.0%
[/TRACE    ]

> This region contains meaningful weight >= 100% (like CPU utilization factor).

I think it is better to add another value for such metric. Weights should provide actual information about time for the region relative to first node execution time. Messing it with parallel timings makes it unreadable.

parallel_for can have special region mark and thread operator could compare its timing with total parallel region timing printing some sort of thread scaling multiplier.

Also to avoid 8000% values for weights they need to be calculated from mean time, not total time. I am preparing a patch for them.

> BTW, I found partially implemented CV_INSTRUMENT_REGION_MT. What is purpose of this macro?

Remains of different timing collection for multi-threaded functions. Should be removed.

**Comment by alalek** [comment]
> parallel_for region requires some special handling for such cases.

I believe, **all** functions require similar "unique" identification. For example, Sobel(dx) and Sobel(dy) may have different timings, but current approach mess their performance under one "Sobel" label.

`&body` address can't guarantee this due this thoughts:
- there is high probability of duplicates in case of stack-based allocations
- there is high probability of misses in case of heap-based allocations

I believe we need to store/use information about a place from where function is called.
What is about `return address`?
- MSVS [__ReturnAddress()](http://msdn.microsoft.com/en-us/library/64ez38eh%28vs.71%29.aspx)
- GCC: `__builtin_extract_return_addr(__builtin_return_address(0))`

BTW, Canny trace tree has 6 Sobel [sub-trees](https://github.com/opencv/opencv/blob/6c12533160bc5e6de1f09847d9cd6dd548667a55/modules/imgproc/src/canny.cpp#L348-L379) in this case...
[Dump](https://gist.github.com/alalek/377b93ecdf3cacbfd60e8e1fb54cc2d4).
[Branch](https://github.com/opencv/opencv/compare/master...alalek:instr_parallel_20161101).

**Comment by lupustr3** [comment]
This is a nice idea!

I have two notes:
- It can backfire in case of unrolling or other loops related compiler optimizations. E.g. if some vector based instrumented function is called for image in loop by rows.
- Full tree is very big, some switch to select collapsed/expanded mode would be appropriate.

**Comment by lupustr3** [comment]
@alalek I made some adjustments to timing calculation, including ticks normalization to provide accurate mean values for repeating and threaded functions. Can you take a look?

[https://github.com/opencv/opencv/compare/master...lupustr3:pvlasov/intrument_update](https://github.com/opencv/opencv/compare/master...lupustr3:pvlasov/intrument_update)

```
[ TRACE    ]
ROOT
\---cv::Canny - C:100 T:9.8180ms
    |---cv::parallel_for_ - C:100 T:7.3324ms L:75% G:75%
    |   \---cv::parallelCanny::operator () - C:400 T:6.7453ms L:92% G:69%
    |       |---cv::Sobel - C:800 T:1.7876ms L:27% G:18%
    |       |   |---cv::Mat::convertTo - C:1600 T:0.0217ms L:1% G:0%
    |       |   |   \---ippiConvert_32s32f_C1R<F_IPP> - C:1600 T:0.0047ms L:22% G:0%
    |       |   |
    |       |   \---cv::sepFilter2D - C:800 T:1.6234ms L:91% G:17%
    |       |       |---cv::Mat::convertTo - C:4000 T:0.0610ms L:4% G:1%
    |       |       |   |---ippiConvert_32f32s_C1RSfs<F_IPP> - C:1600 T:0.0056ms L:9% G:0%
    |       |       |   \---ippiConvert_32s32f_C1R<F_IPP> - C:800 T:0.0021ms L:3% G:0%
    |       |       |
    |       |       \---cv::FilterEngine::apply - C:800 T:1.4214ms L:88% G:14%
    |       |           \---cv::borderInterpolate - C:151200 T:0.2935ms L:21% G:3%
    |       |
    |       \---cv::parallelCanny::operator ()_gradient - C:400 T:4.7236ms L:70% G:48%
    |
    \---cv::parallel_for_ - C:100 T:0.8399ms L:9% G:9%
        \---cv::finalPass::operator () - C:500 T:0.4105ms L:49% G:4%

IPP weight: 0.1%
OPENCL weight: 0.0%
[/TRACE    ]
```

**Comment by alalek** [comment]
Looks like normalization is performed by "m_counter". I believe it should be done by number of threads.

Result for `nstripes` (current code == 4 == numOfThreads):
```
    |---parallel_for_ - C:100 T:121.7356ms L:94% G:94%
    |   \---operator() - C:400 T:115.6307ms L:95% G:89%
    |       \---Sobel - C:800 T:53.0033ms L:46% G:41%
```
Result for `nstripes * 8`:
```
    |---parallel_for_ - C:100 T:126.3679ms L:93% G:93%
    |   \---operator() - C:3200 T:29.0202ms L:23% G:21%
    |       \---Sobel - C:6400 T:13.8344ms L:48% G:10%
```

I believe "L/G" values should be stable.

> cv::parallelCanny::operator ()_gradient
What is "gradient" mean here? (I can't find code for it)

I believe we should [automatically](https://github.com/opencv/opencv/commit/4147ffe88c32ab90e7d9646977cf3767cae9391f) "wrap" most part of `parallel_for_` operators, because they are very specific. But need to think how to preserve meaningful name (for example, we can use names from RTTI)

**Comment by lupustr3** [comment]
> I believe it should be done by number of threads.

Counters are always actual. Number of stripes can be saturated by range. But otherwise they should provide same results because each stripe increases counters just once.

> What is "gradient" mean here? (I can't find code for it)

This is a manual mark for the code after the Sobel calculation. I didn't include it into the branch.

**Comment by lupustr3** [comment]
Yes, you right. Well, I don't see any other way to detect actual threading but to return TLS timings from one of mine initial implementations, need to make with less overhead though.

**Comment by lupustr3** [comment]
Another approach that doesn't require normalization: [https://github.com/opencv/opencv/commit/1b11c75f4ea78525f9417bd041587baf8f31ab37](https://github.com/opencv/opencv/commit/1b11c75f4ea78525f9417bd041587baf8f31ab37)

TC - threads counter. Maximum number of different threads which accessed the node region.
- Ticks for each node are the max ticks from every thread which accessed the node. So sum of ticks can be a little higher than ticks of parent node.
- Also in case of conditional calls (such as Sobel here for tails) sum of ticks from independent paths can be much higher than parent ticks, as they are processed independently. TC indicates threads weight of these nodes.

**Comment by lupustr3** [comment]
```
ROOT
\---cv::Canny - TC:1 C:10 T:2614.49ms
    |---cv::parallel_for_ - TC:1 C:10 T:2413.56ms L:92% G:92%
    |   \---`anonymous-namespace'::ParallelLoopBodyW... - TC:4 C:40 T:2405.46ms L:100% G:92%
    |       |---cv::Sobel - TC:4 C:80 T:1365.25ms L:57% G:52%
    |       |   |---cv::Mat::convertTo - TC:4 C:160 T:0.94ms L:0% G:0%
    |       |   |   \---ippiConvert_32s32f_C1R<F_IPP> - TC:4 C:160 T:0.33ms L:35% G:0%
    |       |   |
    |       |   \---cv::sepFilter2D - TC:4 C:80 T:1317.75ms L:97% G:50%
    |       |       |---cv::Mat::convertTo - TC:4 C:320 T:1.40ms L:0% G:0%
    |       |       |   \---ippiConvert_32f32s_C1RSfs<F_IPP> - TC:4 C:160 T:0.38ms L:27% G:0%
    |       |       |
    |       |       \---cv::FilterEngine::apply - TC:4 C:80 T:1314.78ms L:100% G:50%
    |       |           \---cv::borderInterpolate - TC:4 C:87880 T:108.29ms L:8% G:4%
    |       |
    |       \---gradient - TC:4 C:40 T:1012.80ms L:42% G:39%
    |
    \---cv::parallel_for_ - TC:1 C:10 T:141.50ms L:5% G:5%
        \---`anonymous-namespace'::ParallelLoopBodyW... - TC:5 C:1270 T:139.66ms L:99% G:5%

IPP weight: 0.0%
OPENCL weight: 0.0%
[/TRACE    ]
```

**Comment by alalek** [comment]
Looks good to me (except big Canny indentation changes).

**Comment by lupustr3** [comment]
This is an example of how to use custom regions. They are quite helpful there

**Pull request merged**
