### PR TITLE
cv::normalize negative values bug fix

### PR DESCRIPTION
**Pull request by Aravind-Suresh**
Fixes https://github.com/Itseez/opencv/issues/6125

### CODE REVIEW

**Comment by Aravind-Suresh** [comment]
Some test cases are failing because the diff between expected and calculated exceeds eps. Please tell me whether I am going in the right direction or not.

**Comment by Aravind-Suresh** [comment]
I changed the worktype from float to double and the function seems to work fine. But some test cases are failing because the difference between expected and calculated mats exceed eps. Please tell me whether I am going in the right direction or not.

**Comment by Aravind-Suresh** [comment]
Please tell me whether I am right or not. If not tell me how to go about and solve it?

**Comment by vpisarev** [comment]
This PR will be recreated because of CI issues

**Pull request closed without merging**
