### PR TITLE
Linux window_QT mouse wheel support

### PR DESCRIPTION
**Pull request by theg4sh**
This changes are fix wrong code in window_QT.cpp, which merged from PR #6787.
Verified with QT 5.6.1.

### CODE REVIEW

**Comment by vpisarev** [comment]
:+1:

**Comment by philboske** [comment]
Attempting to compile using a Git clone from 12-hours ago:

`3207:    scaleView(delta / 240.0, pt);`

This is an invalid call from within the OpenGlViewPort class as scaleView is a private method of the DefaultViewPort class. Will leave for someone else to request the change as duplicating methods within different classes feels dirty to me.

`3208:    viewport()->update();`

This also produces an '...undeclared...' error.

**Comment by theg4sh** [comment]
@philboske got it. Going to fix it today.
It looks dirty, I agree. I'll try to do something with it...

**Comment by theg4sh** [comment]
@philboske Thanks for response. PR #6976 will fix it.
Please, take a look to PR #6977, to my mind this looks a bit clearer than it was.

**Pull request merged**
