### PR TITLE
dnn: fix build error on Visual Studio 2012

### LINKED ISSUE #10289: dnn: build fails on VS2012 with 'round' identifier not found
##### System information (version)

- OpenCV => master ( after 17dcf0e82dc5f86081f1ae67a5b1ec0412e9d5cc #10255)
- Operating System / Platform => Windows 10 Pro 64bit
- Compiler => Visual Studio 2012

##### Detailed description
 - When building recent OpenCV master on Visual Studio 2012, following error appears.
````
  C:\opencv\modules\dnn\src\layers\pooling_layer.cpp(299): error C3861: 'round': identifier not found [C:\opencv\build\modules\dnn\opencv_dnn.vcxproj]
  C:\opencv\modules\dnn\src\layers\pooling_layer.cpp(300): error C3861: 'round': identifier not found [C:\opencv\build\modules\dnn\opencv_dnn.vcxproj]
  C:\opencv\modules\dnn\src\layers\pooling_layer.cpp(307): error C3861: 'round': identifier not found [C:\opencv\build\modules\dnn\opencv_dnn.vcxproj]
  C:\opencv\modules\dnn\src\layers\pooling_layer.cpp(308): error C3861: 'round': identifier not found [C:\opencv\build\modules\dnn\opencv_dnn.vcxproj]
````
 - The actual place of the error is [here](https://github.com/opencv/opencv/blob/17dcf0e82dc5f86081f1ae67a5b1ec0412e9d5cc/modules/dnn/src/layers/pooling_layer.cpp#L299-L308).
 - The root of the cause is that ```ronud``` function doesn't exists on Visual Studio 2012 ( and probably earlier )
 - I'll throw a PR to fix this issue, later.

##### Steps to reproduce
 - Build OpenCV revision 17dcf0e82dc5f86081f1ae67a5b1ec0412e9d5cc or later on Visual Studio 2012

### PR DESCRIPTION
**Pull request by tomoaki0705**
### This pullrequest changes
  * round doesn't exists in standard library of Visual Studio 2012
  * close #10289

### CODE REVIEW

**Comment by alalek** [comment]
Thank you!
Could you please just replace `round()` -> `cvRound()` ?

**Comment by tomoaki0705** [comment]
Sure !
Sounds simpler.

**Comment by tomoaki0705** [comment]
Let's hope 5c29f2a works (I'm now away from my build machine)

**Comment by alalek** [comment]
@dkurt Looks like we need updated testdata.

**Comment by dkurt** [comment]
I have `cvRound(0.5) = cvRound(-0.5) = cvRound(0.5f) = cvRound(-0.5f) = 0`. Is it correct?

**Comment by alalek** [comment]
OpenCV's `cvRound()` makes rounding to nearest even.

**Comment by dkurt** [comment]
So let's replace it to
```cpp
int ystartROI = roisData[2] * spatialScale + (roisData[2] >= 0 ? 0.5f : -0.5f);
int yendROI = roisData[4] * spatialScale + (roisData[4] >= 0 ? 0.5f : -0.5f);

xstartROI = roisData[1] * spatialScale + (roisData[1] >= 0 ? 0.5f : -0.5f);
int xendROI = roisData[3] * spatialScale + (roisData[3] >= 0 ? 0.5f : -0.5f);
```
It computes only for Fast- Faster- RCNN based models.

**Comment by dkurt** [comment]
:+1: looks good

@tomoaki0705, many thanks!

**Comment by tomoaki0705** [comment]
Thanks from me, too @dkurt !

**Pull request merged**
