### PR TITLE
Add onRuntimeInitialized for opencv.js (WASM)

### PR DESCRIPTION
**Pull request by dkurt**
### This pullrequest changes

resolves https://github.com/opencv/opencv/issues/14020

Added changes from
https://github.com/opencv/opencv/pull/12361
https://github.com/opencv/opencv/pull/12601
https://github.com/opencv/opencv/pull/12622

```
allow_multiple_commits=1
docker_image:Docs=docs-js
docker_image:Custom=javascript
buildworker:Custom=linux-4
```

### CODE REVIEW

**Comment by alalek** [comment]
Nightly JS builds: http://pullrequest.opencv.org/buildbot/builders/3_4_javascript-emscripten-lin64

**Comment by dkurt** [comment]
@alalek, It looks like previous versions of OpenCV.js were compiled with no WASM support (at least according to their sizes):

releases:
13M https://docs.opencv.org/3.4.5/opencv.js
14M https://docs.opencv.org/4.0.1/opencv.js
13M https://docs.opencv.org/4.0.0/opencv.js

dev branches:
7,7M https://docs.opencv.org/3.4/opencv.js
8,3M https://docs.opencv.org/master/opencv.js

**Comment by dkurt** [comment]
related https://github.com/opencv/opencv/issues/12436

**Comment by dkurt** [comment]
@alalek, I tested this patch with `1.38.28` release of emscripten. All tests are passed.
For now `master` branch has `1.38.21` (OK) and `3.4` has `1.37.21` (buggy).

**Comment by alalek** [comment]
@dkurt Need to stick buildworker for javascript: linux1, linux-2 or linux-4.

**Pull request merged**
