### PR TITLE
G-API: Aligned include syntax for public includes

### PR DESCRIPTION
**Pull request by rgarnov**
Changed quotes to branches when including public headers

```
build_gapi_standalone:Linux x64=ade-0.1.1d
build_gapi_standalone:Win64=ade-0.1.1d
build_gapi_standalone:Mac=ade-0.1.1d
build_gapi_standalone:Linux x64 Debug=ade-0.1.1d
```

### CODE REVIEW

**Comment by dmatveev** [comment]
@alalek so what is the right thing, `""` or `<>`?

**Comment by alalek** [comment]
In general, exact behavior implementation is compiler implementation-defined (not covered by standard).
GCC with `"..."` [additionally looks](https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html) into directory of current processed file (.cpp or other header), so relative paths works in that case.


I'm trying to follow these rules:
- `<...>` is used with "external" headers (like C++ runtime or external library). Also used in samples/tests (because library is kind of external entity). Should not be used with "relative" paths.
- `"..."` is used with headers from the same project/module/directory or relative paths (like OpenCV's `precomp.hpp`).

(probably got from [here](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html))

---

More info:
- https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename

**Comment by dmatveev** [comment]
@alalek so in other words we should use `""` instead of `<>` for own/OpenCV header includes?

**Comment by alalek** [comment]
There is no strong policy from my side. In general, both variants should work fine.

**Comment by dmatveev** [comment]
ok, thanks, what about standalone mode? :)
https://github.com/opencv/opencv/wiki/Graph-API

**Comment by dmatveev** [comment]
:+1:

**Comment by dmatveev** [comment]
Wrong button, sorry!

**Pull request merged**
