### PR TITLE
ARM: video: disable NEON optimization in lkpyramid

### PR DESCRIPTION
**Pull request by alalek**
Test log with failed test (with additional dump of values) on Terga TK1 is available here: http://pullrequest.opencv.org/buildbot/builders/precommit_armv7/builds/55/steps/distributed%20test/logs/log_1.txt

### CODE REVIEW

**Comment by tomoaki0705** [comment]
Looks OK to deactivate.
I'd like to use some time to figure out why this happens and whether this only happens only on TK1 or on other chips, too.
Thanks for investigation.

**Comment by K-Shinotsuka** [comment]
Would it be possible to build under the following conditions for isolating the problem?
CV_SIMD128: OFF
CV_NEON: ON

**Comment by tomoaki0705** [comment]
@alalek , could you have a look through #7494 please ?
I think we can fix the problem without workaround.

**Comment by K-Shinotsuka** [comment]
@tomoaki0705 
I am sorry to cause you inconvenience and thank you for fixing the bug.
Code of CV_SIMD128 is tested properly.
So I guess there is the bug in my code and I want to isolate the problem.
But you fix the bug immediately. Once again, thank you.

By the way, I want to get instruction set for neon.
I refer the following page when I write the sse code.
URL:  https://software.intel.com/sites/landingpage/IntrinsicsGuide/
Please teach me the intrinsic guide for neon.

**Comment by tomoaki0705** [comment]
@k-shinotsuka, 
I usually check [here](http://infocenter.arm.com/help/topic/com.arm.doc.ihi0073a/IHI0073A_arm_neon_intrinsics_ref.pdf) for instruction set, but more than this, I look inside of ```arm_neon.h``` on ARM+Linux platform.
I recommend you to purchase RPi3 or ODROID-C2, they are just around 40$ and you'll have an actual ARM platform.

**Comment by K-Shinotsuka** [comment]
@tomoaki0705 
Thanks for your advice.
I'll see the manual and header file.
And I'll purchase the tablet.
では、また。

**Pull request closed without merging**
