### PR TITLE
Update interactive-calibration app

### PR DESCRIPTION
**Pull request by sovrasov**
### This pullrequest changes
Delete direct lapack calls, minor fixes in UI

### CODE REVIEW

**Comment by vpisarev** [comment]
@sovrasov, since support for MKL has been added to OpenCV itself, can we remove direct calls to MKL from the camera calibration app?

**Comment by sovrasov** [comment]
@vpisarev it's possible but in this case solving of linear systems using QR decomposition will be disabled.

**Comment by vpisarev** [comment]
@sovrasov, let's do it this way:
1. change the code in lapack.cpp:

<pre>
if( method == DECOMP_QR )
    method = DECOMP_SVD;
</pre>

with some real processing using MKL/OpenBLAS (when we have it)

<pre>
if( method == DECOMP_QR )
#ifdef USE_LAPACK
    ...
#else
    method = DECOMP_SVD;
#endif
</pre>

2. use cv::solve(, DECOMP_QR) from the calibration app

**Comment by sovrasov** [comment]
@vpisarev please, look at the last changes.

**Comment by vpisarev** [comment]
excellent! :+1:

**Pull request merged**
