### PR TITLE
G-API: Fix Journal usage in Fluid backend

### PR DESCRIPTION
**Pull request by andrey-golubev**
### This pullrequest changes

- Fixes usage model of `Journal` in Fluid backend: clear existing `Journal` entries on graph reshape
- Adds (experimental) test to verify that memory usage stays the same

### CODE REVIEW

**Comment by andrey-golubev** [comment]
@dmatveev @rgarnov @alalek please review

**Comment by jsxyhelu** [comment]
what is G-API?

**Comment by andrey-golubev** [comment]
@jsxyhelu G-API is the new OpenCV module (since OpenCV 4) targeted to improve image processing pipelines by applying additional layer of optimizations + providing capabilities for heterogeneous execution at the same time

You can learn more about it here: https://docs.opencv.org/4.1.1/d0/d1e/gapi.html

**Comment by andrey-golubev** [comment]
@dmatveev please review this PR as well

**Comment by dmatveev** [comment]
> sorry,what is G-API?

In addition to Andrey's link, here's some slides https://github.com/opencv/opencv/wiki/files/2018-12-24-GAPI_Overview.pdf

**Comment by andrey-golubev** [comment]
@alalek please merge

**Comment by andrey-golubev** [comment]
Thanks!

**Pull request merged**
