### PR TITLE
implemented same bracket style

### PR DESCRIPTION
**Pull request by Aniket965**
### This pullrequest changes

changed few bracket style to the style used overall

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
I seriously wonder why people even do stuff like this :rofl: instead of focusing on actual issues... is there a course in your school that asks you to provide a random fix to OpenCV?

**Comment by StevenPuttemans** [comment]
@Aniket965 It might not sound like that, but I am actually and honoustly wondering why you did this ... so it was an actualiteit question. Your suggestion might still be a good one!

**Comment by Aniket965** [comment]
i was wondering what code style big organisation uses for making their code clean , i liked the way it is done on opencv except some places which I changed sorry if it that was bad thing , i just did that making code same everywhere neat and clean

**Comment by StevenPuttemans** [comment]
Oh well, then why not keep your suggestion open so that the change gets integrated once a core dev has a look.

**Comment by Aniket965** [comment]
I deleted that repo as well may be some other day :)

**Comment by StevenPuttemans** [comment]
:+1:

**Pull request closed without merging**
