### PR TITLE
Move from https to ssh for Windows in Github Actions

### PR DESCRIPTION
**Pull request by asenyaev**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Review by asmorkalov — APPROVED** [review]
:+1:

**Comment by fengyuentau** [comment]
May I ask why use SSH protocol instead of HTTPS?

**Comment by asenyaev** [comment]
> May I ask why use SSH protocol instead of HTTPS?

In case of the command `git ls-remote --heads ...` asks for a username and a password any time with HTTPS and Windows builds can stuck on this simple check ([for example](https://github.com/opencv/opencv/runs/6410201506?check_suite_focus=true)), but SSH doesn't ask for credentials.

By the way, I would replace this implementation with something similar as it is in buildbot. In addition, we had used `curl` to check a branch in other repo in Jenkins.

**Comment by fengyuentau** [comment]
Thank you for the explanation👍

**Review by fengyuentau — APPROVED** [review]

**Pull request merged**
