### PR TITLE
feat: Ran `futurize` over all python code.

### PR DESCRIPTION
**Pull request by ckaran**
[futurize](https://www.python-future.org/futurize.html) is a tool to rewrite python code so that it is compatible with both python 2 and python 3.  I have run the tool over all python code, and believe that the code is correct, **but I have no way of testing the output!** For reasons I still don't understand, I cannot get OpenCV to compile correctly on my machine as it cannot find the C++ standard libraries (my own code compiles fine, its something in  OpenCV).  Please perform any testing you can before merging this request in.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch -**UNKNOWN - If this should be against a different branch, please let me know.**
- [ ] There is reference to original bug report and related work - **There is no original bug report, I just created this**
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name. **Not applicable**
- [ ] The feature is well documented and sample code can be built with the project CMake **UNKNOWN - I can't get OpenCV to compile on my machine, so I don't know if this commit has broken anything.**

### CODE REVIEW

**Comment by berak** [comment]
> I cannot get OpenCV to compile correctly on my machine

maybe you can present your problem on https://answers.opencv.org, we could try to help you from there (as building & running tests locally is essential for a task like this)

then, applying [stage 2](https://www.python-future.org/futurize.html#stage-2-py3-style-code-with-wrappers-for-py2) adds dependancies to the `future` and `past` modules, which are not present in a plain vanilla python install (breaking the build in a lot of places). 

maybe restrict it to stage 1 for now (so it at least builds), and discuss with the devs, how to proceed further ?

**Comment by ckaran** [comment]
> maybe you can present your problem on https://answers.opencv.org, we could try to help you from there (as building & running tests locally is essential for a task like this)

@berak Thank you, I'll present my issues on there, I'd really like to figure out why I can't compile it!

> then, applying stage 2 adds dependancies to the future and past modules, which are not present in a plain vanilla python install (breaking the build in a lot of places).

> maybe restrict it to stage 1 for now (so it at least builds), and discuss with the devs, how to proceed further?

Sure, I can do that.  Where would be the best place to discuss this?  I want to make certain that the breakage is minimal (ideally 0), but still allows all of OpenCV to run under python 3.

In the meantime, I'm going to close this PR, as it isn't well enough tested or clean enough.  Once I know better what I'm doing, I'll make a new PR for the stage 1 changes.  Also, should I create an issue before I make a PR, or can I just make a PR directly?

**Comment by dkurt** [comment]
Can you please describe why just using `print(...)` everywhere is not simpler than `print_function`?

Moreover OpenCV source code is checked by static analyzer https://github.com/opencv/opencv/pull/11504.

**Comment by ckaran** [comment]
@dkurt please forgive me, but I'm confused by your comment; what precisely are you asking?  The output of futurize should always convert print statements to print functions, which are what python 3 uses.  The import statements are so that python 2 understands that you're using the function and not the statement form.

**Comment by dkurt** [comment]
> futurize is a tool to rewrite python code so that it is compatible with both python 2 and python 3

Are OpenCV samples compatible with Python 2.x / 3.x?

**Comment by ckaran** [comment]
> Are OpenCV samples compatible with Python 2.x / 3.x?

@dkurt They should be.  The idea behind futurize is to make code that can run under both python 2 and python 3 (it doesn't forcefully upgrade the code to python 3 only).  So if the necessary support libraries are installed, all tests should transparently pass.

**Pull request closed without merging**
