### PR TITLE
use INTER_LINEAR instead of INTER_LINEAR_EXACT for resize in HOG to actually use OpenCL

### PR DESCRIPTION
**Pull request by kallaballa**
Pertaining Issue: https://github.com/opencv/opencv/issues/22772

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by catree** [comment]
Would it be possible to use an option (via an environment variable or via a method call) for this?
To have the best of both worlds.

**Comment by kallaballa** [comment]
I think that would work-around T-API in its essence? Wouldn't it?

**Comment by asmorkalov** [comment]
Just `INTER_LINEAR` resize may produce slightly different results from device to device. As soon as HOG is used as descriptor it may break existing code. `EXACT` version of resize guaranties predictable behavior everywhere. So, the best solution is to implement EXACT version with OpenCL rather than introduce inobvious regressions to existing code.

**Comment by kallaballa** [comment]
I understand. thx!
I'll have a look at the OpenCL code.

**Comment by kallaballa** [comment]
> Just `INTER_LINEAR` resize may produce slightly different results from device to device. As soon as HOG is used as descriptor it may break existing code. `EXACT` version of resize guaranties predictable behavior everywhere. So, the best solution is to implement EXACT version with OpenCL rather than introduce inobvious regressions to existing code.

I had a look and I am bit confused. do you propose that I implement the resize operation inside objdetect_hog.cl? What exactly does "EXACT version" mean?

I think we may have a misunderstanding because i think all that has to change is some kind of new option that makes HOG use 

```c++
            resize(_img, image_scale, effect_size, 0, 0, INTER_LINEAR);
```

instead of: 

https://github.com/opencv/opencv/blob/2aad039b4f64d8e4a6136388c48d1368c120feec/modules/objdetect/src/hog.cpp#L1868

**Comment by kallaballa** [comment]
Thanks for you help! But i still don't understand how it helps the issue to change OpenCL code in that case. How did you get to the conclusion?

**Comment by catree** [comment]
> But i still don't understand how it helps the issue to change OpenCL code in that case. How did you get to the conclusion?

`INTER_LINEAR_EXACT` is not implemented for OpenCL code path. So from my understanding, the goal is to add OpenCL implementation of `INTER_LINEAR_EXACT` method.

**Comment by kallaballa** [comment]
I get it now. :)
thx!

**Pull request closed without merging**
