### PR TITLE
(5.x) Merge 4.x

### PR DESCRIPTION
**Pull request by asmorkalov**
OpenCV Contrib: https://github.com/opencv/opencv_contrib/pull/3587
Opencv Extra: https://github.com/opencv/opencv_extra/pull/1119

#21066 from andrewerf:21052-openvino-native-onnx
#23879 from asmorkalov/release_3.4.20
#23894 from kallaballa:blobFromImagesWithParams
#23929 from CNClareChen:4.x
#24092 from Aser-Abdelfatah:GSoC_Support_GatherElements_ONNX
#24168 from autoantwort:missing-include-3
#24322 from Abdurrahheem:ash/dev_einsum_ellips
#24434 from Kumataro:fixWarningForGCC13
#24363 from cudawarped:videoio_ffmpeg_add_stream_encapsulation
#24367 from alexlyulkov:al/fixed-cumsum-inplace-flag
#24371 from hanliutong:clean-up
#24372 from Kumataro:fix24369
#24382 from sisakat:cuda-compile-multicore
#24405 from kochanczyk:4.x
#24409 from fengyuentau:norm_kernel
#24412 from vrabaud:inter_area1
#24417 from asmorkalov:as/resize_interarea_perf
#24420 from vpisarev:fp16bf16_arithm
#24422 from mshabunin:update-ade-012d
#24425 from fengyuentau:fix_timvx_test
#24427 from fengyuentau:gather_elements_fp16
#24429 from vrabaud:inter_area1
#24438 from vrabaud:avif_check
#24440 from COOLIRON2311:4.x
#24441 from vrabaud:avif_check
#24451 from eplankin:3.4
#24454 from komakai:refactorObjcRange
#24461 from fengyuentau:tracker_vit_backend_target
#24468 from asmorkalov:as/python_ctor_docs
#24478 from CCInc:mingw_fix

Previous "Merge 4.x": #24416

### CODE REVIEW

**Comment by asmorkalov** [comment]
@opencv-alalek the PR is ready for review.

**Review by opencv-alalek — COMMENTED** [review]
There are test failures in CUDA and OpenCL DNN tests.
(Looks like CPU implementation result is changed)

**Comment by asmorkalov** [comment]
@opencv-alalek I added extra branch to FastNeuralStyle_eccv16 test for CUDA. 4.x and 5.x use different networks and thresholds are not compatible. I suspect the same issue as in https://github.com/opencv/opencv/pull/24359

**Review by opencv-alalek — APPROVED** [review]
LGTM :+1:

OpenCL test failure is not a regression of this patch - there is failed nightly build with the same: https://pullrequest.opencv.org/buildbot/builders/5_x-lin64/builds/100293

**Pull request merged**
