### PR TITLE
added  template matching object detection java sample

### PR DESCRIPTION
**Pull request by mesutpiskin**
### This pullrequest changes

Template Matching Method for Object Detection

### CODE REVIEW

**Comment by alalek** [comment]
1) Images and other data for samples should be stored under [samples/data](https://github.com/opencv/opencv/tree/master/samples/data) sub-directory.
2) What is licence for used image?
3) Proxy link via 'camo' looks very dangerous. Original image can be changed/lost anytime. Could you use more reliable image storage? (also in case of proper license)
4) There is 'Template matching' [tutorial](http://docs.opencv.org/master/d4/dc6/tutorial_py_template_matching.html), you can try to use images from there.

**Comment by mshabunin** [comment]
>There is 'Template matching' tutorial, you can try to use images from there

I think we should wait until #7041 is merged - it should add support for multi-language tutorials. Then it will be possible to add Java code to existing tutorial.

**Comment by Cartucho** [comment]
@mshabunin I have that tutorial in Java.
You can have a look at the sample [here](http://cartucho.github.io/tutorial_template_matching.html).

As soon as the #7041 gets merged I will start the PR with the multi-language tutorials.

**Comment by mshabunin** [comment]
Multi-language tutorials are supported now, so the original [cpp tutorial](http://docs.opencv.org/master/de/da9/tutorial_template_matching.html) should be extended.

**Comment by mshabunin** [comment]
Similar tutorial has been integrated in #8043

**Pull request closed without merging**
