### PR TITLE
Optimize RowVec_32f and SymmColumnVec_32f with AVX2

### PR DESCRIPTION
**Pull request by woodychow**
Just translated the instructions from SSE to AVX2

### CODE REVIEW

**Comment by vpisarev** [comment]
@woodychow, thank you very much for the contribution! We've just integrated patch by @alalek to support runtime dispatching of AVX code; see https://github.com/alalek/opencv/wiki/CPU-optimizations-build-options. Can you please refactor your patch to support it? Basically, you need to move AVX-optimized code into a separate file with special suffix (_avx2.cpp) and call it from filter.cpp. This way your AVX2-optimized code will be available by default and backward compatibility with old hardware will be retained.

**Comment by alalek** [comment]
Moving to new dispatcher on this PR is not easy and straightforward task. These algorithms include a lot of shared data, with additional usage of classes.

Also there is no "real" sample how to deal with it. Probably some changes need to be added into mentioned patch.

So my suggestion is to start from other more lightweight PR, like #8398. Or to merge this "as is" and to migrate code by whole "files" instead of single function optimization (I believe it is more easy way).

**Comment by woodychow** [comment]
I agree with @alalek. There is currently no *_opt_*.cpp in the project. If there is sample code for me to follow, I can definitely refactor my patches and maybe help with transitioning.

**Comment by vpisarev** [comment]
@woodychow, @alalek, ok, I'm fine with it too. Somehow we need to stabilize the solution. I suggest to postpone integration of the patch. Finalize the simpler ones and then refactor this one. Right now the proposed optimization will likely be used by less than 1% of OpenCV users, after making AVX support dynamic it will grow to 20-30% (basically, all the people who run OpenCV on reasonably modern Intel/AMD CPUs)

**Comment by vpisarev** [comment]
:+1:

**Comment by woodychow** [comment]
Thanks!

**Pull request merged**
