### PR TITLE
Resolved issue number #22177

### PR DESCRIPTION
**Pull request by AryanNanda17**
Resolved issue no https://github.com/opencv/opencv/issues/22177

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by AryanNanda17** [comment]
Resolved issue no #22177

**Review by asmorkalov — COMMENTED** [review]
The constants are used not only by remap, but many other functions like warpAfine, warpPerspective, blur, etc. The behaviour should be checked everywhere.

**Comment by AryanNanda17** [comment]
I checked the behavior and it is not causing any trouble. What should I do next @asmorkalov.

**Review by vpisarev — APPROVED** [review]

**Comment by vpisarev** [comment]
that's little but nice clarification of how border mode affects behaviour of functions. It can be merged

**Comment by AryanNanda17** [comment]
Hi @vpisarev, thanks for looking into my pull request!
Could you please help me in figuring this out:-
- In my open-source contributions, I frequently face building failures or skips when my pull requests are reviewed. Can you explain the reasons behind this occurrence, and what specific elements should I investigate to identify the issues?
-  Why did some build for this pull request get skipped?

Thanks

**Pull request merged**
