### PR TITLE
core(libva): use dynamic loader

### PR DESCRIPTION
**Pull request by alalek**
<cut/>

```
force_builders=Custom
Xbuild_image:Custom=centos:7
build_image:Custom=ubuntu:20.04
buildworker:Custom=linux-1,linux-4,linux-6
allow_multiple_commits=1
```

### CODE REVIEW

**Comment by mshabunin** [comment]
Checked with this MediaStack: https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-20.5.1

##### Env setup
```
export LD_LIBRARY_PATH=/opt/intel/mediasdk-20.5.1/lib64/
export LIBVA_DRIVER_NAME=iHD
export LIBVA_DRIVERS_PATH=/opt/intel/mediasdk-20.5.1/lib64/
export PATH=/opt/intel/mediasdk-20.5.1/bin/:$PATH
```
##### Running the sample
```
$ ./bin/example_va_intel_va_intel_interop ../opencv/samples/data/rubberwhale1.p
ng A B
libva info: VA-API version 1.10.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk-20.5.1/lib64//iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
VA display opened successfully
Interop ON : processing time, msec: 1.08985

$ ./bin/example_va_intel_va_intel_interop ../opencv/samples/data/rubberwhale1.png A B -f
libva info: VA-API version 1.10.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk-20.5.1/lib64//iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
VA display opened successfully
Interop OFF: processing time, msec: 39.3298
```
##### No dependency on libva
```
$ objdump -p lib/libopencv_core.so | grep NEEDED
  NEEDED               libdl.so.2
  NEEDED               libpthread.so.0
  NEEDED               librt.so.1
  NEEDED               libz.so.1
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.6
```

**Comment by mikhail-nikolskiy** [comment]
VADisplay (VAAPI context) contains v-table of all VAAPI functions. VAAPI experts confirm that v-table guarantees backward compatibility.
So all functions, except vaInitilize which creates VADisplay, could be called via v-table if include public header <va/va_backend.h>.
Here is [example](https://github.com/mikhail-nikolskiy/opencv/blob/videoio-hw/modules/videoio/src/cap_ffmpeg_hw.hpp#L110).

**Comment by mshabunin** [comment]
@mikhail-nikolskiy , I think the method with vtable requires runtime libva version checks. Otherwise there can be situation when the library built with fresh libva would expect some new method exists and slightly older libva loaded in runtime would not have this field in vtable. This situation is partially handled by `dlopen` (older version won't load), but not with vtable. So this approach requires slightly more developer's conciousness and double version checks (in general case, not at current integration level):
```.cpp
#if VERSION > XX  // new_function added in XX
if (ctx->version > XX)
    ctx->new_function()
else
#endif
    cerr << "Not implemented" << endl;
```
We have somewhat similar code for example in OSX AVFoundation integration: https://github.com/opencv/opencv/blob/504ff978c580e9c4bb78d5d5ad9170aec9519e1b/modules/videoio/src/cap_avfoundation_mac.mm#L330-L332


Currently `dlopen` seems more appropriate since it is compatible with both libva 1.x and 2.x with other things more or less equal.

**Comment by alalek** [comment]
@mikhail-nikolskiy Thank you for the information!

Unfortunately we still need to support configurations/platforms with old libva versions:
- CentOS 7: 0.40.0 (by va_version.h)
- Ubuntu 16.04: 0.39.0

**Review by mshabunin — APPROVED** [review]

**Pull request merged**
