### PR TITLE
BUG: Reverting hardcoded TCP hack for RTSP streaming via ffmpeg

### LINKED ISSUE #9290: ffmpeg capture forced to TCP, even if UDP is desired
##### System information (version)
- OpenCV => latest(master)
- Operating System / Platform => Windows 10 Creators 64 Bit
- Compiler => Visual Studio 2015 64

##### Detailed description

I have an rtsp server which crashes after prolonged TCP connection. I have no way of avoiding this device, and I don't have control to fix the crash. UDP is needed. However, after bug "fix" [http://code.opencv.org/issues/2235#note-18](http://code.opencv.org/issues/2235#note-18) ffmpeg capture is hardcoded to TCP.

##### Steps to reproduce
Normal opening of RTSP stream using cv::VideoCapture

```.cpp
this->Capture = std::make_shared<cv::VideoCapture>(this->VideoURL, this->RequestedCaptureAPI);
this->Capture->read(*this->Frame)
```

### PR DESCRIPTION
**Pull request by adamrankin**
Now configurable via setProperty functionality of capture interface

resolves #9290 

### This pullrequest changes

cap_ffmpeg_impl.hpp now supports configuring the transport layer by storing a requested [RTSPLowerTransport](https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/rtsp.h#L37) (default to TCP as per previous desired behaviour).

Desired transport layer can be changed via 
```cv::VideoCapture::set(CV_FFMPEG_CAP_PROP_TRANSPORT, <value>)```
where \<value\> is a 
```static_cast<double>(RTSPLowerTransport)```

### CODE REVIEW

**Comment by adamrankin** [comment]
Will fix compile issues as they come in. Unfortunately I am working on Windows and don't have the Windows ffmpeg build setup.

**Comment by adamrankin** [comment]
Ah, of course, ffmpeg is much more than RTSP. Will investigate ffmpeg code to identify format independent method.

**Comment by ebachard** [comment]
Why was this issue closed ? I'm currently trying to make RTSP work on Linux ( OpenCV 3.4.0) and I can't make it work.  ... and the issues about capture rtsp or whatver IP cam using openCV seems to be a bit messy ... 

Is there a better (and working) solution ?  Thanks in advance

**Comment by adamrankin** [comment]
This PR was the wrong approach, I implemented a solution in https://github.com/opencv/opencv/pull/9292

Perhaps something has changed, but it worked for me and capturing an RTSP stream was as easy as
```
cv::VideoCapture cap(rtspUrlString);
if(!cap.isOpened())
    return -1;
```

If you are experiencing problems, I recommend you open an issue and describe the symptoms and error messages you get.

**Comment by ebachard** [comment]
@adamrankin : thanks a lot for your detailed answer. 

My issue is currenty not solved, but you provided me very good tracks, and I start to see what is -probably- missing to make it work as expected.

**Pull request closed without merging**
