### PR TITLE
fix the bug in pyrUp

### PR DESCRIPTION
**Pull request by heavyrain-lzy**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by heavyrain-lzy** [comment]
fix the bug in pyrUp:
when deal with the right boder in multi-channels image, the code forget to multiply the "cn" to calculate the "index".

**Review by alalek — COMMENTED** [review]
Thank you for contribution!

We don't have [coverage](http://pullrequest.opencv.org/buildbot/export/opencv_releases/master_coverage-lin64-debug/20220610-175221_100000/coverage_html/opencv/modules/imgproc/src/pyramids.cpp.gcov.html) of tests for the mentioned line.

Please prepare simple regression test which covers this case (to avoid regression in the future).
You could use test scheme similar to `TEST(Imgproc_Filter2D, dftFilter2d_regression_13179)` with some small image data (e.g., 8x8 pixels).
Test should fail without the patch and pass with this patch.

---

As a bug fix this patch should go into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first.
We will merge changes from 3.4 into 4.x regularly (weekly/bi-weekly).

Please:
- change "base" branch of this PR: 4.x => 3.4 (use "Edit" button near PR title)
- rebase your commits from 4.x onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/4.x`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

**Comment by heavyrain-lzy** [comment]
>Thanks for the suggestions. I have complete the code change according to the commends.

**Review by alalek — APPROVED** [review]
Well done! Thank you for contribution :+1:

**Pull request merged**
