### PR TITLE
core(TLS): implement releasing of ThreadData with thread termination

### LINKED ISSUE #9745: Memory leak in every thread
- OpenCV => 3.3.0
- Operating System / Platform => Arch Linux (4.12.13-1-ARCH SMP PREEMPT x86_64 GNU/Linux)
- Compiler => gcc 7.2.0 and clang 5.0.0

##### Detailed description

It seems that a significant piece of memory is leaked in every thread.
The following code snippet consumes cca 100MB/s.

##### Steps to reproduce

```.cpp
#include <opencv2/opencv.hpp>
#include <future>
int main()
{
    while(true) {
        std::async(std::launch::async, []() { cv::Mat::zeros(1, 1, CV_32FC3); }).wait();
    }
}
```

### PR DESCRIPTION
**Pull request by alalek**
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/2316

resolves #9745

- move TLS & instrumentation code out of core/utility.hpp
- TLSData lost .gather() method (to dispose thread data on thread termination)
- use TLSDataAggregator for reliable collecting of thread data
- prefer using of .detachData() instead of .gather() method

<cut/>

TODO:
- [x] propose API for reliable gathering of thread data
- [x] fix trace.cpp
- [x] additional tests
- [ ] ? backward compatibility mode

### CODE REVIEW

**Comment by CodArs-van** [comment]
Hi @alalek, I'm having OpenCV memory leak issues reported by heaptrack on Linux, I saw your pr is merging into version 3.4, I'm wondering if 4.x also has the same problem? Will you merge this into 4.x as well?

**Comment by CodArs-van** [comment]
@alalek any plan to merge this into 4.x?

**Comment by mshabunin** [comment]
@CodArs-van , it have been merged to _master_.

**Comment by XF920418** [comment]
Hi @alalek ．First of all, I am very grateful for the repair of the opencv async memory leak. This has also been verified after the update of the opencv version(such as 4.2), but now another problem encountered is somewhat similar. The same version(opencv 4.2) is also frequently used async (or std::thread)to open threads, in the child thread Calling opencv interfaces such as canny(or remap), there is a problem of continuous memory growth, do you know why? 
This is my test code.
```
for (size_t i = 0; i < 1000000; i++) {
        std::async(std::launch::async, []() {
            cv::Mat binary_image_;
            std::cout << cv::utils::getThreadID() << std::endl;
            cv::Mat mImageGray = cv::imread("1.png", 1);
            cv::Canny(mImageGray, binary_image_, 12, 60);
        }).wait();
    }
```

**Pull request merged**
