### PR TITLE
add a wrapper for getAvailableTargets

### PR DESCRIPTION
**Pull request by JulienMaille**
as requested by @dkurt here: https://github.com/opencv/opencv/pull/16184#issuecomment-569006520

<cut/>

```
force_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2019r3.0:16.04
build_image:Custom Win=openvino-2019r3.0
build_image:Custom Mac=openvino-2019r3.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

### CODE REVIEW

**Comment by dkurt** [comment]
Thanks!
Please change target branch to 3.4. We will port to master branch

**Comment by neFAST** [comment]
done

**Comment by alalek** [comment]
Could you please add simple bindings tests?

- Python: https://github.com/opencv/opencv/blob/4.2.0/modules/dnn/misc/python/test/test_dnn.py
- Java: https://github.com/opencv/opencv/tree/4.2.0/modules/dnn/misc/java/test

Check should be simple enough (`DNN_BACKEND_OPENCV`+`DNN_TARGET_CPU` is always available).

Thank you!

**Comment by JulienMaille** [comment]
@alalek something like this?
```
def test_getAvailableTargets(self):
    targets = cv.dnn.getAvailableTargets(cv.dnn.DNN_BACKEND_OPENCV)
    test.assertIn(cv.dnn.DNN_TARGET_CPU, targets)
```

**Comment by alalek** [comment]
@JulienMaille Yes

**Comment by JulienMaille** [comment]
I tried my best, but I'm gonna need help with the java test

**Comment by JulienMaille** [comment]
@alalek Python test is ok but this is the error I get for the java one:
```
    [javac] /build/precommit_linux64/build/java_test/src/org/opencv/test/dnn/DnnTensorFlowTest.java:146: error: cannot find symbol
    [javac]         List<Integer> targets = Dnn.getAvailableTargets(Dnn.DNN_BACKEND_OPENCV);
    [javac]                                    ^
    [javac]   symbol:   method getAvailableTargets(int)
    [javac]   location: class Dnn
```

**Comment by JulienMaille** [comment]
@dkurt can the issue with java be solved without changing the signature to take an int instead of an enum?

**Comment by dkurt** [comment]
@JulienMaille, I will try to check it.

**Comment by dkurt** [comment]
@JulienMaille, may I ask you to try the following changes?

```patch
diff --git a/modules/dnn/include/opencv2/dnn/dnn.hpp b/modules/dnn/include/opencv2/dnn/dnn.hpp
index a2030ad..4699dac 100644
--- a/modules/dnn/include/opencv2/dnn/dnn.hpp
+++ b/modules/dnn/include/opencv2/dnn/dnn.hpp
@@ -97,7 +97,7 @@ CV__DNN_INLINE_NS_BEGIN
     };
 
     CV_EXPORTS std::vector< std::pair<Backend, Target> > getAvailableBackends();
-    CV_EXPORTS_W std::vector<Target> getAvailableTargets(Backend be);
+    CV_EXPORTS_W std::vector<Target> getAvailableTargets(dnn::Backend be);
 
     /** @brief This class provides all data needed to initialize layer.
      *
diff --git a/modules/dnn/misc/java/gen_dict.json b/modules/dnn/misc/java/gen_dict.json
index c0e0a1b..5a397ea 100644
--- a/modules/dnn/misc/java/gen_dict.json
+++ b/modules/dnn/misc/java/gen_dict.json
@@ -36,6 +36,14 @@
             "v_type": "vector_Layer",
             "j_import": "org.opencv.dnn.Layer"
         },
+        "vector_Target": {
+            "j_type": "List<Integer>",
+            "jn_type": "List<Integer>",
+            "jni_type": "jobject",
+            "jni_var": "std::vector< cv::dnn::Target > %(n)s",
+            "suffix": "Ljava_util_List",
+            "v_type": "vector_Target"
+        },
         "LayerId": {
             "j_type": "DictValue",
             "jn_type": "long",
diff --git a/modules/dnn/misc/java/src/cpp/dnn_converters.cpp b/modules/dnn/misc/java/src/cpp/dnn_converters.cpp
index 1d259ae..95184c0 100644
--- a/modules/dnn/misc/java/src/cpp/dnn_converters.cpp
+++ b/modules/dnn/misc/java/src/cpp/dnn_converters.cpp
@@ -60,6 +60,25 @@ jobject vector_Ptr_Layer_to_List(JNIEnv* env, std::vector<cv::Ptr<cv::dnn::Layer
     return result;
 }
 
+jobject vector_Target_to_List(JNIEnv* env, std::vector<cv::dnn::Target>& vs)
+{
+    static jclass juArrayList   = ARRAYLIST(env);
+    static jmethodID m_create   = CONSTRUCTOR(env, juArrayList);
+    jmethodID m_add       = LIST_ADD(env, juArrayList);
+
+    static jclass jInteger = env->FindClass("java/lang/Integer");
+    static jmethodID m_create_Integer = env->GetMethodID(jInteger, "<init>", "(I)V");
+
+    jobject result = env->NewObject(juArrayList, m_create, vs.size());
+    for (size_t i = 0; i < vs.size(); ++i)
+    {
+        jobject element = env->NewObject(jInteger, m_create_Integer, vs[i]);
+        env->CallBooleanMethod(result, m_add, element);
+        env->DeleteLocalRef(element);
+    }
+    return result;
+}
+
 std::vector<cv::Ptr<cv::dnn::Layer> > List_to_vector_Ptr_Layer(JNIEnv* env, jobject list)
 {
     static jclass juArrayList       = ARRAYLIST(env);
diff --git a/modules/dnn/misc/java/src/cpp/dnn_converters.hpp b/modules/dnn/misc/java/src/cpp/dnn_converters.hpp
index 6a72701..e1f63e0 100644
--- a/modules/dnn/misc/java/src/cpp/dnn_converters.hpp
+++ b/modules/dnn/misc/java/src/cpp/dnn_converters.hpp
@@ -28,5 +28,6 @@ jobject vector_Ptr_Layer_to_List(JNIEnv* env, std::vector<cv::Ptr<cv::dnn::Layer
 
 std::vector<cv::Ptr<cv::dnn::Layer> > List_to_vector_Ptr_Layer(JNIEnv* env, jobject list);
 
+jobject vector_Target_to_List(JNIEnv* env, std::vector<cv::dnn::Target>& vs);
 
 #endif /* DNN_CONVERTERS_HPP */
```

**Comment by JulienMaille** [comment]
@dkurt done

**Pull request merged**
