### PR TITLE
Fix issue #11242 (universal intrinsics v_rotate, v_extract type restriction and SSSE3 optimization)

### LINKED ISSUE #11242: Remove integer-only restriction from universal intrinsic ```v_extract``` SSE2 only
### System information (version)

- OpenCV => master
  - Built with ```CV_CPU_HAS_SUPPORT_SSE2```
  - Built with ```CV_TRY_SSE3, CV_TRY_SSSE3, CV_TRY_SSE4_1, CV_TRY_SSE4_2, CV_TRY_AVX, CV_TRY_AVX2```
- Operating System / Platform => 
  - Universal intrinsics 128-bit SSE2 
  - Tested on Windows 10
  - Kaby Lake
  - 64-bit OS, CPU
- Compiler => Visual Studio 2017 Community (MSVC 15.6.3)

### Detailed description

OpenCV universal intrinsic ```v_extract``` for SSE2 (see source lines below) imposes an "integer only" restriction. This restriction does not exist for non-SSE2, such as scalar, NEON, VSX. A pull-request will be submitted to remove this restriction, by using templates and casts.

#### Code where such restriction exists for SSE2

 * https://github.com/opencv/opencv/blob/f93c1b942ab7781ba54da48831ca1fb31e3cc1eb/modules/core/include/opencv2/core/hal/intrin_sse.hpp#L1362-L1371

#### Doxygen documentation comment describing the SSE2-only restriction (should be removed after bug fix)

 * https://github.com/opencv/opencv/blob/f93c1b942ab7781ba54da48831ca1fb31e3cc1eb/modules/core/include/opencv2/core/hal/intrin_cpp.hpp#L1479

### Steps to reproduce

These test code need to be test-compiled inside the OpenCV library, because universal intrinsics are internal implementation detail to OpenCV.

#### Problem exists for floating-point types on SSE2

```.cpp
v_float32x4 first, second;
v_float32x4 third = v_extract(first, second);
```

*(compiler output)*

```.txt
1>c:\users\git\opencv\modules\core\include\opencv2\core\hal\intrin_sse.hpp(1369): error C2664: '__m128i _mm_slli_si128(__m128i,int)': cannot convert argument 1 from 'const __m128' to '__m128i'
1>c:\users\git\opencv\modules\core\include\opencv2\core\hal\intrin_sse.hpp(1369): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>c:\users\git\opencv\modules\core\include\opencv2\core\hal\intrin_sse.hpp(1370): error C2440: '<function-style-cast>': cannot convert from '__m128i' to 'cv::hal_baseline::v_float32x4'
1>c:\users\git\opencv\modules\core\include\opencv2\core\hal\intrin_sse.hpp(1370): note: No constructor could take the source type, or constructor overload resolution was ambiguous
```

#### Problem doesn't exists for integer types on SSE2

```.cpp
v_uint32x4 first, second;
v_uint32x4 third = v_extract(first, second);
```

*(compiles successfully, no diagnostics)*

#### Problem doesn't exists for any types on NEON, VSX, C++ scalar, etc.

*(code omitted)*

### PR DESCRIPTION
**Pull request by kinchungwong**
WIP resolve #11242 

Please review. 
Requires C++11.
PR to (master == 4.0). Do not merge to 3.4
Please run buildbot (master == 4.0), if resource permits.

***This PR.***
 - [x] v_rotate_left, right (reg a), (reg a, reg b)
 - [x] v_extract (reg a, reg b)

***Not done, open to discussion.***
 - [ ] design uniformity in CPP, NEON, AVX, VSX
 - [ ] Before/after performance comparison, with and without SSSE3
   - core "matmul", (note: it uses ```v_rotate_left, right```)
   - calib3d "stereo sgbm", 
   - contrib optflow "dis_flow", 
   - contrib optflow "variational_refinement") 
 - [ ] Uncertainty about latency impacts on using PALIGNR ("integer-centric instructions") or PUNPCKH(L)DQ in between floating-point intensive algorithms. Such latency may come from CPU execution units. ***Suggestions welcome.***

***Not in this issue, not in this PR.***
 - [ ] v_insert (out reg a, out reg b, in const ref c)
 - [ ] v_rotate_left, right (array of regs) 
 - [ ] v_extract (array of regs)

### This pullrequest changes

 * ```typedef``` ```v_int32x4::vector_type``` etc
 * ```namespace hal_sse_internal``` ```v_sse_reinterpret_as``` such as ```__m128i```
 * ```namespace hal_sse_internal``` ```v_sse_palignr_u8```
 * ```v_rotate_left```, ```v_rotate_right```, ```v_extract``` enhancement
   * Remove type restriction, should work for 8, 16, 32, 64 integers and 32, 64 floats
   * Enhancement using PALIGNR when preprocessor (```CV_SSSE3```) equals 1
 * Updated test case in ```test_intrin.cpp```
 * Updated doxygen docs in ```intrin_cpp.hpp```

#### Test and performance outputs

My machine isn't set up for performance testing (it has thermal throttling, so execution time can vary a lot depending on random reasons.) Would appreciate any help from anybody.

[opencv_perf_optflow.after_modify.txt](https://github.com/opencv/opencv/files/1897804/opencv_perf_optflow.after_modify.txt)
[opencv_test_calib3d.after_modify.txt](https://github.com/opencv/opencv/files/1897805/opencv_test_calib3d.after_modify.txt)
[opencv_test_core.after_modify.txt](https://github.com/opencv/opencv/files/1897806/opencv_test_core.after_modify.txt)
[opencv_test_optflow.after_modify.txt](https://github.com/opencv/opencv/files/1897807/opencv_test_optflow.after_modify.txt)
[opencv_perf_calib3d.after_modify.txt](https://github.com/opencv/opencv/files/1897808/opencv_perf_calib3d.after_modify.txt)
[opencv_perf_core.after_modify.txt](https://github.com/opencv/opencv/files/1897809/opencv_perf_core.after_modify.txt)

```
buildworker:Linux x64=linux-1
buildworker:Win64 OpenCL=windows-2
force_builders=Custom
docker_image:Custom=powerpc64le
```

### CODE REVIEW

**Comment by vpisarev** [comment]
@kinchungwong, how heavy is the dependency from C++ 11 features? If it's just static_assert(), there is CV_StaticAssert()

**Comment by kinchungwong** [comment]
@vpisarev The commit (5dd9a7f) uses: enum class, constexpr, constexpr used in class template default argument, explicitly deleted function (non-special function). I don't have a compiler which I can turn off C++11 for verifying compliance. I'll update my PR to use ```CV_StaticAssert()``` instead of ```static_assert```.

**Comment by kinchungwong** [comment]
***(Background info / motivation.)***

This [code sample (gist)](https://gist.github.com/kinchungwong/94a090ace1bdd67c02cf932c4a4b8a2a) explains why I'm eager to improve ```v_extract``` (and ```v_insert``` at a later time) but not eager to get it into branch 3.4.

I'm trying to create a convolution function wrapper (transformer) using nothing but C++11.

My other (future) code contributions will consist of universal intrinsics which, upon widening, returns the widened result in a ```std::array<vec_type, 2>```. For example, widening from ```v_uint8x16``` to ```s32``` will return a ```std::array<v_int32x4, 4>```, as opposed to four separate output arguments which must be specified as out ref arguments in the function call. Because their return types are different, these new overloads will be added to a nested namespace, only available to users who explicitly want to use it.

**Comment by kinchungwong** [comment]
Replaced by #11304 which does not contain C++11.

**Pull request closed without merging**
