### PR TITLE
A new feature matching algorithm is added

### PR DESCRIPTION
**Pull request by JiawangBian**
I add a feature matching algorithm "GMS: Grid-based Motion Statistics for Fast, Ultra-robust Feature Correspondence IEEE, CVPR 2017"  to the feature2d module.

The project page of the paper is: [ProjectPage](http://jwbian.net/gms )
The source code is on the [Github](https://github.com/JiawangBian/GMS-Feature-Matcher)

### CODE REVIEW

**Comment by alalek** [comment]
Hi,
Thank you for contribution!

1) Please provide tests. There are some tests for feature matchers, but required API is different.
2) In general, completely new algorithms should go into opencv_contrib if they are not highly integrated into existed code.
3) OpenCV uses BSD license for code. What is the license of this code?

**Comment by JiawangBian** [comment]
Just now added a BSD license for the code. 
Will put the code into opencv_contrib and provide tests. thanks@alalek

**Comment by alalek** [comment]
There are [entry-points](https://github.com/opencv/opencv/blob/3.2.0/modules/features2d/test/test_matchers_algorithmic.cpp#L532-L544) for existed feature matching tests.
Similar code (need to check consistency) is existed in `xfeatures2d` tests of opencv_contrib.
But we need to wrap this algorithm into `DescriptorMatcher` class to use them.

**Comment by JiawangBian** [comment]
Those codes may be used to check the nearest neighbor matching. This algorithm regards nearest neighbor matches as input and labels them as inlier or outlier, so we may write another test code. Should I make a new module called "featurematching" to put it?

**Comment by alalek** [comment]
> This algorithm regards nearest neighbor matches as input and labels them as inlier or outlier

> `matches_all` Input neighborhood matches.

OK, this is not classical feature matcher algorithm.
So existed tests for matchers are no applicable here, we need some other tests to check code.

> make a new module

New module is not needed. I believe we can put this into "xfeatures2d" module or `ccalib3d` (if it is similar to `findHomography` function).

**Comment by JiawangBian** [comment]
I think this is a good position: "https://github.com/opencv/opencv/blob/master/modules/stitching/src/matchers.cpp"
Because I find ratio-test(BestOf2NearestMatcher) here and the new algorithm is an alternative to ratio-test.

Can I put the code here?

**Comment by catree** [comment]
@JiawangBian If you are ok, I would like to port this pull request into the [xfeatures2d module](https://github.com/opencv/opencv_contrib/tree/master/modules/xfeatures2d). 
This way, the algorithm will be integrated in OpenCV contrib to be usable and later can be moved or refactored if needed.

**Comment by JiawangBian** [comment]
OK，thanks very much。and i will keep updating if needed.

**Comment by catree** [comment]
@JiawangBian For your information, I have created the corresponding pull request in opencv/opencv_contrib#1532.

**Pull request closed without merging**
