### PR TITLE
(5.x) Merge 4.x

### PR DESCRIPTION
**Pull request by asmorkalov**
Extra: https://github.com/opencv/opencv_extra/pull/1074
Contrib: https://github.com/opencv/opencv_contrib/pull/3527

#21797 from anna-khakimova:ak/merge3_extend_supported_types
#21959 from cpoerschke:4.x-intelligent-scissors-optimisation
#22947 from chacha21:hasNonZero
#23264 from AleksandrPanov:add_detect_qr_with_aruco
#23595 from TolyaTalamanov:at/implement-openvino-backend
#23596 from vrabaud:libavif
#23666 from mshabunin:barcode-move
#23668 from TolyaTalamanov:at/fix-resize-applying-logic-ie-backend
#23688 from cpoerschke:4.x-pr-21959-prep
#23721 from asmorkalov:as/openjpeg_2.5_warning_fix
#23722 from asmorkalov:as/python_classifiers_update
#23725 from asmorkalov:as/aruco_js_refresh
#23732 from vekkuli:vekkuli-patch-create-featherblender
#23740 from Peekabooc:4.x
#23746 from Abdurrahheem:ash/graph_simplifier
#23748 from AleksandrPanov:fix_cornerRefinementMethod_binding
#23750 from mshabunin:fix-bgr2hls-access
#23758 from AleksandrPanov:add_GenericGraphicalCode_interface
#23761 from LaurentBerger:typeblobfromimages
#23762 from TolyaTalamanov:at/gapi-ov-backend-hotfix
#23763 from zihaomu:add_runtime_check
#23766 from TolyaTalamanov:at/segmentation-demo-desync
#23769 from asmorkalov:as/qrcode_js_fix
#23775 from kai-waang:fixing-typo
#23783 from zihaomu/remove_unsupported_character
#23785 from damianofalcioni:4.x
#23786 from TolyaTalamanov:at/expose-preprocessing-to-ie-backend
#23788 from dkurt:py_scalar_assign
#23789 from asmorkalov:as/python_aruco_qr
#23790 from asmorkalov:as/qrcode_aruco_js
#23795 from dkurt:tf_half_pixel_for_nn
#23797 from asmorkalov:as/barcode_js_bindings
#23798 from VadimLevin:dev/vlevin/runtime-typing-module
#23800 from kai-waang:4.x
#23807 from mshabunin:barcode-test
#23721 from asmorkalov:as/openjpeg_2.5_warning_fix 

Previous "Merge 4.x": #23718

```
force_builders=Linux AVX2,Custom
build_image:Docs=docs-js:18.04
build_image:Custom=javascript
buildworker:Custom=linux-1,linux-4,linux-f1
```

### CODE REVIEW

**Review by opencv-alalek — COMMENTED** [review]
Non-ported changes must be mentioned in the description, like #23078 #23806 and may be others.

Regular merge process assumes that ALL(!) PRs are propagated by default. Non-ported PRs (excluding dedicated "backport" PRs) should be considered as a strong exceptions.
Otherwise it just increase technical debt and complicates future merges as base of patches is not here.
Also special labels must be applied to postpones PRs for proper tracking: see [`port to 5.x is needed`](https://github.com/opencv/opencv/issues?q=label%3A%22port+to+5.x+is+needed%22)

**Comment by asmorkalov** [comment]
I want to synchronize 4.x and 5.x in 3 steps:
1. Everything before USAC update.
2. USAC update and related refactoring as "port" PR. USAC implementation diverged in 4.x and 5.x and I asked the original author to work on it.
3. Everything after USAC update.
This PR is step 1. Nothing is skipped or added.

**Comment by opencv-alalek** [comment]
Got it.
Please update tests tolerance and we could merge PR: https://pullrequest.opencv.org/buildbot/builders/precommit_linux64-avx2/builds/100167

**Comment by asmorkalov** [comment]
@opencv-alalek I tuned threshold in 3d module. JS failures are not related to the merge and will be fixed with another PR.

**Pull request merged**
