### PR TITLE
cv::videostab::calcBlurriness moved to imgproc

### PR DESCRIPTION
**Pull request by mshabunin**
just a proposal if it is possible.
if it is acceptable let me improve documentation of the function.

Restored #5816

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
do we really need such simple function in the library's public interface?

**Comment by vpisarev** [comment]
this breaks binary compatibility; is calcBlurriness used somewhere else?

**Comment by alalek** [comment]
> this breaks binary compatibility

Actually, it doesn't.
- cv::videostab::calcBlurriness (from video and it is not removed)
- cv::calcBlurriness (from imgproc)

**Comment by vpisarev** [comment]
ok, let's close the PR then. Calculating blurriness can be done in many different ways, it's application-dependent, so we'd rather let users to copy this function to their application and adjust it as needed.

**Pull request closed without merging**
