### PR TITLE
WIP: [GSoC] Bit-exact SIFT detector

### PR DESCRIPTION
**Pull request by Yosshi999**
This work is related to #18167 and #18053 .  These two PRs and this will make SIFT detector to be bit-exact in the future.

<cut/>

## Future works
- [ ] Complete bit-exact SIFT detector’s implementation
- [ ] Add test for checking bit-exactness
- [ ] Report the result of perftests.

### CODE REVIEW

**Review by crypt096 — APPROVED** [review]

**Comment by alalek** [comment]
@Yosshi999 Please rebase patch on latest 3.4 branch

**Comment by Yosshi999** [comment]
This bitexact version seems to make perftest much slower.
I will write reports later.

**Comment by Yosshi999** [comment]
environment:
```
Parallel framework: pthreads (nthreads=4)
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?
Intel(R) IPP version: ippIP AVX2 (l9) 2020.0.0 Gold (-) Oct 19 2019
OpenCL is disabled
```

testcase:
```
feature2d_detect.
  detect/57  # GetParam() = (SIFT_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")
  detect/58  # GetParam() = (SIFT_DEFAULT, "stitching/a3.png")
  detect/59  # GetParam() = (SIFT_DEFAULT, "stitching/s2.jpg")
```

Performace test | Reference time | PR time | Speedup
--|--|--|--
detect/57 | 109.93 | 390.80 | 0.281
detect/58 | 99.85 | 380.50 | 0.262
detect/59 | 221.52 | 859.21 | 0.257

Bit exact version is about 4x slower than original.

**Comment by Yosshi999** [comment]
profiling results of:
```OPENCV_TRACE_DEPTH_OPENCV=0 OPENCV_TRACE_MAX_CHILDREN=10 python IntelSEAPI/runtool/sea_runtool.py -o ocv_trace_nonBE -f gt ! ~/opencv/build/bin/opencv_perf_features2d --gtest_filter=feature2d_detect.detect/57```

original
image

bit-exact (this PR)
image

It seems I should improve the bit-exact Gaussian blur for 16bit unsigned int.

**Comment by Yosshi999** [comment]
Performace   test | Reference time | PR time | Speedup
-- | -- | -- | --
detect/57 | 109.93 | 178.81 | 0.615
detect/58 | 99.85 | 202.31 | 0.494
detect/59 | 221.52 | 486.11 | 0.456

Now bit exact version is about 2x slower than original.

**Comment by asmorkalov** [comment]
@Yosshi999 Do you have any progress with the solution. The PR looks like abandoned.

**Comment by Yosshi999** [comment]
@asmorkalov Sorry I will give up this task and I'll reopen a PR with [only this diff](https://github.com/opencv/opencv/pull/18217/commits/2d1c04a4e311874fe60f0a02a3ba20328b3a7e66), because it is an improvement of #18167 and can be separated from this.

**Pull request closed without merging**
