### PR TITLE
Added LSTM and GRU tests for various batch and input length sizes

### PR DESCRIPTION
**Pull request by Abdurrahheem**
Added tests with various sequence length and batch sizes

Test data: https://github.com/opencv/opencv_extra/pull/1057

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@Abdurrahheem You need to rebase the PR to OpenCV Extra on top of 4.x. There is merge conflict there.

**Comment by asmorkalov** [comment]
```
[ RUN      ] Test_ONNX_layers.LSTM_cell_batchsize_1_seqlen_50/0, where GetParam() = CUDA/CUDA
/home/ci/opencv/modules/dnn/test/test_common.impl.hpp:75: Failure
Expected: (normL1) <= (l1), actual: 0.0991663 vs 1e-05
  |ref| = 0.62599176168441772
/home/ci/opencv/modules/dnn/test/test_common.impl.hpp:78: Failure
Expected: (normInf) <= (lInf), actual: 0.474885 vs 0.0001
  |ref| = 0.62599176168441772
[  FAILED  ] Test_ONNX_layers.LSTM_cell_batchsize_1_seqlen_50/0, where GetParam() = CUDA/CUDA (5 ms)
[ RUN      ] Test_ONNX_layers.LSTM_cell_batchsize_1_seqlen_50/1, where GetParam() = CUDA/CUDA_FP16
[       OK ] Test_ONNX_layers.LSTM_cell_batchsize_1_seqlen_50/1 (7 ms)
[ RUN      ] Test_ONNX_layers.LSTM_cell_batchsize_1_seqlen_50/2, where GetParam() = OCV/CPU
[       OK ] Test_ONNX_layers.LSTM_cell_batchsize_1_seqlen_50/2 (1 ms)
[ RUN      ] Test_ONNX_layers.LSTM_cell_batchsize_5_seqlen_5/0, where GetParam() = CUDA/CUDA
/home/ci/opencv/modules/dnn/test/test_common.impl.hpp:75: Failure
Expected: (normL1) <= (l1), actual: 0.15313 vs 1e-05
  |ref| = 0.98481488227844238
/home/ci/opencv/modules/dnn/test/test_common.impl.hpp:78: Failure
Expected: (normInf) <= (lInf), actual: 0.846282 vs 0.0001
  |ref| = 0.98481488227844238
[  FAILED  ] Test_ONNX_layers.LSTM_cell_batchsize_5_seqlen_5/0, where GetParam() = CUDA/CUDA (5 ms)
```
It looks like CUDA branch of LSTM is not complete. Please skip CuDNN backend in test like here: https://github.com/opencv/opencv/blob/4.x/modules/dnn/test/test_layers.cpp#L231, create ticket about LSTM CUDA issue and add reference to it to test code.

**Review by asmorkalov — APPROVED** [review]

**Comment by asmorkalov** [comment]
@dkurt @fengyuentau Could you take a look too.

**Review by fengyuentau — APPROVED** [review]
LGTM 👍

**Pull request merged**
