### PR TITLE
Add samples code for tutorials (Load, Modify, and Save an Image)

### PR DESCRIPTION
**Pull request by sunwoo2**
I found that there is no source code link and repository in OpenCV Tutorials/Introduction to OpenCV/ Load, Modify, and Save an Image. So i've added it.

https://docs.opencv.org/3.4.0/db/d64/tutorial_load_save_image.html

```
force_builders_only=linux,docs
```

### CODE REVIEW

**Comment by dkurt** [comment]
Am I right that you wanted to replace it to code snippets from file?

That means you need to modify https://github.com/opencv/opencv/blob/3.4/doc/tutorials/introduction/load_save_image/load_save_image.markdown as well

**Comment by sunwoo2** [comment]
I couldn't see 'doc' folder well enough because I concentrate 'samples' folder and docs homepage.
thank you for your feedback. I think the github address you linked can maintain current state.
 
-----Original Message-----

**Comment by asmorkalov** [comment]
@sunwoo2 Do you have progress on the patch?

**Comment by sunwoo2** [comment]
@asmorkalov No.

**Pull request closed without merging**
