### PR TITLE
Bug fix for sample/dnn/text_detection.py

### PR DESCRIPTION
**Pull request by zihaomu**
### Pull Request Readiness Checklist

The implementation of text recognition decode has a bug.

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@zihaomu Could you share full issue reproducer for the patch: python version, command line, link to models?

**Comment by zihaomu** [comment]
> @zihaomu Could you share full issue reproducer for the patch: python version, command line, link to models?

Thank you for your reply.

The text recognition models that I have trained can be found at https://drive.google.com/drive/folders/1cTbQ3nuZG-EKWak6emD_s8_hHXWz7lAr?usp=sharing. They can work well in sample/dnn/text_dection.cpp but not sample/dnn/text_detection.py.

And I found a bug during text decoding. 
The recognition model output is ```scores```, which dimension is (24 x 37).  During the decoding process, we need to return the position of the maximum value in each row of the vector. 

So we should use code ``` np.argmax(scores[i])```, instead of ``` np.argmax(scores[i][0])```. 

```np.argmax(scores[i][0])``` only return ```0```. And it will cause all recognition models failing to work.

**Comment by asmorkalov** [comment]
@zihaomu I made experiments with the original sample and the models and everything is good. `decodeText` function is applied to recognition network output. It looks like your model output and original model output has different shape. I propose to accommodate to original model shape and not change the sample to run the sample with both models.

**Comment by zihaomu** [comment]
> @zihaomu I made experiments with the original sample and the models and everything is good. `decodeText` function is applied to recognition network output. It looks like your model output and original model output has different shape. I propose to accommodate to original model shape and not change the sample to run the sample with both models.

@asmorkalov Thank you for your reply. You're right, my models have different output shape. I have changed the structure of my model so that the output has the same shape.

I will close this PR.

**Pull request closed without merging**
