### PR TITLE
Updated modules white list for JS after calib3d reorg

### PR DESCRIPTION
**Pull request by asmorkalov**
Fixes https://github.com/opencv/opencv/issues/19017
relates #18940

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders_only=docs,Custom
build_image:Docs=docs-js
build_image:Custom=javascript
buildworker:Custom=linux-4
```

### CODE REVIEW

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv/pull/18948 need to be merged to next to fix error reported by flake8.

**Comment by alalek** [comment]
Feel free to cherry-pick commit `77b986c7a16721146edc51153502c38428d98a6f` (without squash)

**Comment by asmorkalov** [comment]
@alalek Done. I triggered remaining builds.

**Review by alalek — APPROVED** [review]
Thank you :+1:

**Pull request merged**
