### PR TITLE
WIP : qrcode

### PR DESCRIPTION
**Pull request by ZhengQiushi**

### CODE REVIEW

**Comment by APrigarina** [comment]
@ZhengQiushi, what is the reason of creating of new pull request?

**Comment by ZhengQiushi** [comment]
> @ZhengQiushi, what is the reason of creating of new pull request?
I can't get into the building process after I have updated and pushed my code again. So I closed the old PR and created a new one . Sorry for inconveniencing you .

**Comment by rayonnant14** [comment]
@ZhengQiushi if you create your branch new22 from master, base branch should also be master. Now PR contains not only your commits due to change of base branch to 3.4. Please fix it by change base branch to master.

**Comment by APrigarina** [comment]
@ZhengQiushi please discuss with us (@APrigarina and @rayonnant14) before you decide to do something

**Comment by rayonnant14** [comment]
@ZhengQiushi we still don't understand the reason of creating a new PR. Do you mean that some builders didn't work in buildbot for your last pull request? The reason of this is that scope of builders was limited, as it is said in the last PR description

**Pull request closed without merging**
