### PR TITLE
GAPI (fluid): RGB/BGR to gray: optimization

### PR DESCRIPTION
**Pull request by elatkin**
```
force_builders=Linux AVX2
```

### CODE REVIEW

**Comment by elatkin** [comment]
CV_SIMD dynamic dispatching to AVX2 looks quite efficient  
(although perform about 5% slower than static dispatching)

Overall testing results on my desktop, Sky Lake i5-6600  

|            | OpenCV  | GAPI/AVX  | GAPI/SSE  | GAPI/orig |
|----------|-------------|---------------|---------------|--------------|
| 1080p | 1.72 ms   | 0.556 ms   | 1.18   ms   | 9.57 ms    |
|   720p | 0.749 ms | 0.245 ms   | 0.527 ms   | 4.28 ms    |
|   480p | 0.262 ms | 0.1 ms       | 0.333 ms   | 3.88 ms    |

GAPI appears 2.5-3x faster than OpenCV's kernel on AVX,  
and 1.5x faster on SSE if large image (20% slower if small)  

Overall speed-up by this optimization is 15x for large images,
and almost 40x for small images

**Comment by alalek** [comment]
Dispatching decisions should be performed on graph compilation time, not during execution.

**Comment by savuor** [comment]
Need to add an assert for conversion coeffs: `(rc + gc + bc) == (1 << 16)`

**Comment by elatkin** [comment]
force_builders=Linux AVX2

**Comment by alalek** [comment]
OpenCV CI doesn't track comments

**Comment by elatkin** [comment]
@dmatveev  
Could you please review?

**Comment by dmatveev** [comment]
Looks ok, We have "compound kernels" to do dispatching (as well) in compile time, so I think we could consider this for further improvement. Current results are promising already, though

**Comment by elatkin** [comment]
@alalek  
Could you please merge this PR?

**Comment by dmatveev** [comment]
Cool, thanks!

**Pull request merged**
