### PR TITLE
(3.4) android: backport build_sdk.py

### PR DESCRIPTION
**Pull request by alalek**
backport #13939

```
force_builders=Android pack
```

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by hurzl** [comment]
Can't find cmake
```
Executing: ['~/Android/Sdk/cmake/3.10.2.4988404/bin/cmake', '--version']
Failed: can't concat str to bytes
Traceback (most recent call last):
  File "~/android/opencv/opencv-3.4.9/platforms/android/build_sdk.py", line 440, in <module>
    builder = Builder(args.work_dir, args.opencv_dir, args)
  File "~/android/opencv/opencv-3.4.9/platforms/android/build_sdk.py", line 155, in __init__
    self.cmake_path = self.get_cmake()
  File "~/android/opencv/opencv-3.4.9/platforms/android/build_sdk.py", line 171, in get_cmake
    raise Fail("Can't find cmake")
__main__.Fail: Can't find cmake
# ~/Android/Sdk/cmake/3.10.2.4988404/bin/cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
#
```
cmake installed from Android Studio

**Comment by alalek** [comment]
> Failed: can't concat str to bytes

Python version? OS?

> ~/

Some shells can't handle that properly. Try to use full path.

**Comment by hurzl** [comment]
> Python version? OS?

Python 3.8.1
linux 4.19.102-1-MANJARO

> Some shells can't handle that properly. Try to use full path.

I removed that only here

**Pull request merged**
