### PR TITLE
Another sample cpp

### PR DESCRIPTION
**Pull request by cabelo**
### This pullrequest changes

<cut/>

opecv

Invisibility example with OpenCV (using morphologyEx, bitwise_not, absdiff and another funcions)

@alalek , @dkurt this effect sample. I used in this work: https://www.youtube.com/watch?v=h5savmDl5G0

Source: https://github.com/cabelo/my-opencv-examples

*** Sorry for the confusion in the last request.

```
**WIP**
force_builders=linux,windows,docs
test_modules=none
```

### CODE REVIEW

**Comment by alalek** [comment]
Please stop re-creating of Pull requests. Almost anything can be "fixed" without re-creation of PR.

**Comment by cabelo** [comment]
> ### This pullrequest changes
> 
> opecv
> 
> Invisibility example with OpenCV (using morphologyEx, bitwise_not, absdiff and another funcions)
> 
> @alalek , @dkurt this effect sample. I used in this work: https://www.youtube.com/watch?v=h5savmDl5G0
> 
> Source: https://github.com/cabelo/my-opencv-examples
> 
> *** Sorry for the confusion in the last request.
> 
> ```
> **WIP**
> force_builders=linux,windows,docs
> test_modules=none
> ```

**Comment by cabelo** [comment]
> Please stop re-creating of Pull requests. Almost anything can be "fixed" without re-creation of PR.

Sorry

**Comment by cabelo** [comment]
> > Please stop re-creating of Pull requests. Almost anything can be "fixed" without re-creation of PR.
> 
> Sorry

@alalek  this example (Invisibility)  was rejected, or can I submit it?
Please. Sorry for the confusion.

**Comment by alalek** [comment]
> this example (Invisibility) was rejected

Nobody rejects this PR.
Please have to learn GitHub first. 5 PRs in a row - no idea what you are doing.

**Comment by cabelo** [comment]
> > this example (Invisibility) was rejected
> 
> Nobody rejects this PR.
> Please have to learn GitHub first. 5 PRs in a row - no idea what you are doing.

@alalek  THANK YOU!!! I found the problem.

**Pull request closed without merging**
