### PR TITLE
cascade bug fixed

### PR DESCRIPTION
**Pull request by mohitgupta07**
The bug caused me alot ..made me cry for a while but i am fine now :') 'still crying'....

### CODE REVIEW

**Comment by mohitgupta07** [comment]
I have fixed the issue that occurs in opencv 3.2 versions.... and please merge it now so that other won't cry ..

**Comment by alalek** [comment]
This is definitely not a fix.
Please post output of `adb logcat` during startup of application.

**Comment by mohitgupta07** [comment]
Well perhaps it is. I will provide you the logcat too .

**Comment by StevenPuttemans** [comment]
line 86 is doing exactly what line 84 is doing during initialization, so this is not a solution. Like said, provide us your actual issue and we might be able to point what is wrong.

**Comment by mohitgupta07** [comment]
Hi let me point out the issue first. Suppose you don't want to use c++ libraries in your opencv codeand then you try to implement the same code commenting all those detection_tracker code then what will happen is if you don't include the load function in your code then cascade classifier won't get initialize and will return null! You need to first create a new object then use load function to load the xml data in classifier. I don't know the reason behind it but certainly know that adding those lines will do the trick. 
P.s. It did cost me bunch of hours to figure out the bug I am talking about. Take this tutorial for eg https://www.mirkosertic.de/blog/2013/07/realtime-face-detection-on-android-using-opencv/ I bet you everything will seem fine to you but the code will not work until you add the lines I did added in patch. Also I am new to opencv but can figure out the issue. Thanks and let me know if its just a myth or a serious bug I did face.

**Comment by mohitgupta07** [comment]
Anyone looking through my issue??

**Comment by alalek** [comment]
Fix will not be accepted in this form.
Unfortunately we can't resolve this because we can't reproduce it. You may provide more information (`adb logcat` at least) to help investigation of this issue here: #7223

**Pull request closed without merging**
