### PR TITLE
doc: fix typo in py_tutorials

### PR DESCRIPTION
**Pull request by pranitbauva1997**
This fixes the issue #9721 . I understand it's not a big issue, but I have just compiled the repo locally and trying out to fix some easy issues.

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
I am not sure why the build on `Win64 OpenCL` is failing. I haven't made any changes to the source yet either. Unfortunately, I don't have the system so can please anyone tell me where the problem is?

**Comment by berak** [comment]
@pranitbauva1997 ; no fear. it's an internal buildbot problem, not related to your commit at all.

just wait it out, the bot will restart soon (hopefully in a much happier state :)

**Comment by sovrasov** [comment]
Similar error should be fixed in [py_matcher.markdown](https://github.com/opencv/opencv/blob/da0188acc0f7f14507a2db029e60779b324124f1/doc/py_tutorials/py_feature2d/py_matcher/py_matcher.markdown) too.

**Comment by pranitbauva1997** [comment]
@sovrasov Thanks! I have fixed it.

**Comment by sovrasov** [comment]
:+1:

**Pull request merged**
