### PR TITLE
DNN : fix bug in extracting prior-box variances in detection output layer

### PR DESCRIPTION
**Pull request by SamFC10**
GetPriorBBoxes() assumes the input blob has shape (1, 2, num_priors * 4, 1) with the second channel being prior-box variances. But when `_varianceEncodedInTarget` is true, the input has shape (1, 1, num_prioirs * 4, 1), as checked by the following assertion

https://github.com/opencv/opencv/blob/424eaba4c5db94524e416c95dba38c8d09071afe/modules/dnn/src/layers/detection_output_layer.cpp#L239

Another reference in the [reshape](https://github.com/opencv/opencv_extra/blob/3c7cf7a13255a0917a13aeb801b322ff9d3d898f/testdata/dnn/faster_rcnn_vgg16.prototxt#L486) for the input of Detection output layer in faster-rcnn-vgg16.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
@SamFC10 Thank you for contribution!
Is it possible to add accuracy test for this case?

**Comment by SamFC10** [comment]
> Is it possible to add accuracy test for this case?

There were some faster rcnn tests which crashed sporadically in my int8 PR (#20228) on Windows CI builders and local windows machine with the message - `unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.` Tracing back, it was the illegal memory access in prior-box variances which caused these crashes. I don't know how to reproduce these sporadic crashes in a test. Will need some help.

**Comment by alalek** [comment]
> Tracing back, it was the illegal memory access in prior-box variances which caused these crashes.

This usually happens when memory is accessed without checking arrays layouts (through CV_Check* or CV_Assert macros). It makes sense to add these checks there.

**Comment by SamFC10** [comment]
> add these checks there

There is one already 

https://github.com/opencv/opencv/blob/424eaba4c5db94524e416c95dba38c8d09071afe/modules/dnn/src/layers/detection_output_layer.cpp#L239

It was added in #11255 but the function GetPriorBBoxes() wasn't modified along with the added assertion.

**Review by vpisarev — APPROVED** [review]

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
