### PR TITLE
Fixed a typo in android toolchain documentation.

### PR DESCRIPTION
**Pull request by vladkraievskiy**
### This pullrequest changes

Fixed a typo in android toolchain documentation.

### CODE REVIEW

**Comment by alalek** [comment]
This patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into 3.4 branch. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

**Comment by vladkraievskiy** [comment]
Thank you for help. Changed base branch to 3.4 and fixed my "master" branch to contain only 1 commit that must be merged.

**Comment by alalek** [comment]
Well done! Thank you :+1:

> my "master" branch

There is common recommendation to make proper branch names for patches (like "fix_typo_android_toolchain") instead of generic "master".

**Comment by vladkraievskiy** [comment]
Ok. Sorry for that branch name. Thought that it's unimportant for fork pull-request.

**Pull request merged**
