### PR TITLE
Set swapRB to false in Caffe tests and examples

### LINKED ISSUE #9625: Caffe models are trained in BGR image format, not RGB
Some of samples with Caffe models wrongly swap red and blue channels (by keeping swapRB argument of `blobFromImage` with default `true` value). However models are trained in BGR input format, see https://github.com/BVLC/caffe/wiki/Image-Format:-BGR-not-RGB.

source: http://answers.opencv.org/question/174139/is-the-swaprb-value-in-the-example-googlenet-dnn-code-wrong/

GoogLeNet image classification using DNN:

Image | RGB input (class id / confidence) | BGR input 
----------|--------------|------------
space shuttle <br>  | 812 0.999828 | 812 0.999935
red wine <br>  | 966 0.869604 | 966 **0.995303**
jeans <br>  | 608 0.83024 | 608 **0.998637**

We need to find the all Caffe networks are used in our samples / tutorials and check the correctness.

### PR DESCRIPTION
**Pull request by jrobble**
Resolves #9625 

**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/1375
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/382

Set swapRB to false in Caffe tests and examples.

### CODE REVIEW

**Comment by dkurt** [comment]
@jrobble, thanks for your contribution! Can you squash the changes to a single commit? At the all PRs.

**Comment by jrobble** [comment]
@dkurt, should I create new PRs for that or is there another way?

**Comment by dkurt** [comment]
@jrobble, no. Just `checkout` to `fix_caffe_swaprb` branch and call `git rebase -i HEAD~3` where 3 is a number of commits you want to squash into the single one.
If you use git from console you'll see an editor with list of selected commits:
```
pick ce109b0 Set swapRB to false in Caffe tests and examples.
pick 4ef1334 Set swapRB to false in some Android and Python code.
pick 1b523cd Reproducibility_FCN test now uses caffe_fcn8s_prob.png instead of caffe_fcn8s_prob.npy.
```
Replace `pick` to `squash` like:
```
pick ce109b0 Set swapRB to false in Caffe tests and examples.
squash 4ef1334 Set swapRB to false in some Android and Python code.
squash 1b523cd Reproducibility_FCN test now uses caffe_fcn8s_prob.png instead of caffe_fcn8s_pro
```
Exit editor(`Ctrl+X` was for me). Then, optionally, modify a commit message in the next editor or out of it by `git commit --amend -m "Set swapRB to false in Caffe tests and examples."`.

**Comment by jrobble** [comment]
@dkurt, thanks for the explanation. I wasn't aware that GitHub could handle a forced push after a squash. I had to do:

```
git push --force my-fork fix_caffe_swaprb
```

**Comment by dkurt** [comment]
👍

**Pull request merged**
