### PR TITLE
core: fix `Core_GEMM.accuracy` failure on recent macOS

### PR DESCRIPTION
**Pull request by fengyuentau**
Resolves https://github.com/opencv/opencv/issues/25302

Reproducer: https://github.com/opencv/ci-gha-workflow/actions/runs/8747714722/job/24006610667?pr=171#step:12:1041

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by fengyuentau** [comment]
It is even weirder that if I set unrolling by factor of 2 instead of 4, it passes. Could it be something related to the compiler?

```cpp
                 #if CV_ENABLE_UNROLLED
                for(; j <= m - 2; j += 2 )
                {
                    WT t0 = d_buf[j] + WT(b_data[j])*al;
                    WT t1 = d_buf[j+1] + WT(b_data[j+1])*al;
                    d_buf[j] = t0;
                    d_buf[j+1] = t1;
                    // t0 = d_buf[j+2] + WT(b_data[j+2])*al;
                    // t1 = d_buf[j+3] + WT(b_data[j+3])*al;
                    // d_buf[j+2] = t0;
                    // d_buf[j+3] = t1;
                }
                #endif
```

**Comment by opencv-alalek** [comment]
Are there some aliased pointers on the same memory for reading and writing? (inplace processing)

**Comment by fengyuentau** [comment]
> Are there some aliased pointers on the same memory for reading and writing? (inplace processing)

Probably no.

- `d_buf` is an AutoBuffer allocated in the domain of outside of the loop. It is set to zero for each element just before entering the problematic loop.
- The source of `b_data` is a bit complecated. It is a parameter for the function and for test case #14, it is a piece of buffer copied from the original source B mat.

https://github.com/opencv/opencv/blob/5da17a4b03b9b9cac92ccadd5fda249523dfdd79/modules/core/src/matmul.simd.hpp#L1246-L1257

**Comment by fengyuentau** [comment]
Test is now green with this patch merged https://github.com/opencv/ci-gha-workflow/actions/runs/8750864630/job/24015266117?pr=171

**Pull request merged**
