### PR TITLE
doc: update to doxygen-awesome-css v2.3.4

### PR DESCRIPTION
**Pull request by Kumataro**
Close https://github.com/opencv/opencv/issues/26411

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [X] The PR is proposed to the proper branch
- [X] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
The CSS changes style for code snippets and layout of some pieces. Looks good to me in general. @mshabunin @vpisarev what do you think?

**Comment by Kumataro** [comment]
Thank you for your comment.
`custom.css` changes `white-space` attribute, it is reason to break style.
It is from https://github.com/opencv/opencv/pull/25339

I removed this change and tried with Firefox 129.0.2(in ubuntu 24.04) , chromium 128.0.6613.84(in ubuntu 24.04) and chrome 130.0.6723.92(in windows). 
It works well for both formula in `NormTypes enum` description and code snippets.

https://pullrequest.opencv.org/buildbot/export/pr/26414/docs/d2/de8/group__core__array.html#gad12cefbcb5291cf958a85b4b67b6149f

https://pullrequest.opencv.org/buildbot/export/pr/26414/docs/d8/d01/tutorial_discrete_fourier_transform.html

**Review by mshabunin — APPROVED** [review]
Looks good to me. Dark mode is now working :fireworks: 

I noticed that content width has changed (1000->1050) which migh not work well on small laptops (1024px) and some strange font for python function names, but that could be issue with dark mode or buildbot serving. Let's merge it and check nightly documentation afterwards.

**Comment by Kumataro** [comment]
Thank you for your reply!
Maybe missing space has 2 reasons, CloudFlare site optimization and `custom.css`.

My "local" test requires to update custom.css for fixing indent.
And at [26412 preview](https://pullrequest.opencv.org/buildbot/export/pr/26412/docs/db/da5/tutorial_how_to_scan_images.html), if disable this part of `custom.css` in development mode, code indent is fined.

Based on the above results, I would like to apply the latest code at this time.

**Comment by mshabunin** [comment]
I disabled CloudFlare cache for buildbot docs preview pages (hopefully) and restarted docs build, let's see if something changes.

**Comment by Kumataro** [comment]
I can confirm `custom.css` is updated and code indent works well.
Thank you very much for quick response !!!

**Pull request merged**
