### PR TITLE
Updated protobuf version to 3.5.1

### LINKED ISSUE #10510: protobuf: build issue
Problem is fixed in protobuf upstream (3.2.0+).

With Android NDK 16.1 (gcc):

> FAILED: 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/type_info.cc.o 
<ndk-bundle>/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-g++ --sysroot=<ndk-bundle>/sysroot  -DHAVE_PTHREAD=1 -D__OPENCV_BUILD=1 -I3rdparty/protobuf/src -I3rdparty/ippicv/ippicv_lnx/include -I3rdparty/ippicv/ippiw_lnx/include -I. -isystem <ndk-bundle>/sources/cxx-stl/llvm-libc++/include -isystem <ndk-bundle>/sources/android/support/include -isystem <ndk-bundle>/sources/cxx-stl/llvm-libc++abi/include -isystem <ndk-bundle>/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -fno-strict-aliasing    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security   -Winit-self -Wpointer-arith   -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -march=i686 -fomit-frame-pointer  -msse -msse2 -mfpmath=sse -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated -Wno-missing-declarations -Wno-shadow -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-sign-compare -Wno-sign-promo -Wno-undef -Wno-ignored-qualifiers -Wno-extra -Wno-unused-function -O2 -DNDEBUG   -DNDEBUG -fPIC -MD -MT 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/type_info.cc.o -MF 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/type_info.cc.o.d -o 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/util/internal/type_info.cc.o -c 3rdparty/protobuf/src/google/protobuf/util/internal/type_info.cc

```
3rdparty/protobuf/src/google/protobuf/util/internal/type_info.cc:126:33: error: reference to 'map' is ambiguous
   static void DeleteCachedTypes(map<StringPiece, T>* cached_types) {
                                 ^
```

### PR DESCRIPTION
**Pull request by oqtvs**
resolves #10510

### This pullrequest changes
 This pull request changes the version of dnn's protobuf from 3.1.0 to 3.5.1

```
allow_multiple_commits=1
```

### CODE REVIEW

**Comment by oqtvs** [comment]
Will just solve this conflicts maybe with a rebase

**Comment by oqtvs** [comment]
Just updating here
Windows builds and docs aren't building for now, the error is:
```
Creating library C:/build/precommit_opencl/build/lib/Release/opencv_dnn340.lib and object C:/build/precommit_opencl/build/lib/Release/opencv_dnn340.exp
   319>libprotobuf.lib(zero_copy_stream_impl.obj) : error LNK2019: unresolved external symbol "int __cdecl google::protobuf::internal::win32::close(int)" (?close@win32@internal@protobuf@google@@YAHH@Z) referenced in function "public: bool __cdecl google::protobuf::io::FileInputStream::CopyingFileInputStream::Close(void)" (?Close@CopyingFileInputStream@FileInputStream@io@protobuf@google@@QEAA_NXZ) [C:\build\precommit_opencl\build\modules\dnn\opencv_dnn.vcxproj]
   319>libprotobuf.lib(zero_copy_stream_impl.obj) : error LNK2019: unresolved external symbol "int __cdecl google::protobuf::internal::win32::read(int,void *,unsigned __int64)" (?read@win32@internal@protobuf@google@@YAHHPEAX_K@Z) referenced in function "public: virtual int __cdecl google::protobuf::io::FileInputStream::CopyingFileInputStream::Read(void *,int)" (?Read@CopyingFileInputStream@FileInputStream@io@protobuf@google@@UEAAHPEAXH@Z) [C:\build\precommit_opencl\build\modules\dnn\opencv_dnn.vcxproj]
   319>libprotobuf.lib(zero_copy_stream_impl.obj) : error LNK2019: unresolved external symbol "int __cdecl google::protobuf::internal::win32::write(int,void const *,unsigned __int64)" (?write@win32@internal@protobuf@google@@YAHHPEBX_K@Z) referenced in function "public: virtual bool __cdecl google::protobuf::io::FileOutputStream::CopyingFileOutputStream::Write(void const *,int)" (?Write@CopyingFileOutputStream@FileOutputStream@io@protobuf@google@@UEAA_NPEBXH@Z) [C:\build\precommit_opencl\build\modules\dnn\opencv_dnn.vcxproj]
   319>C:\build\precommit_opencl\build\bin\Release\opencv_dnn340.dll : fatal error LNK1120: 3 unresolved externals [C:\build\precommit_opencl\build\modules\dnn\opencv_dnn.vcxproj]
   319>Done Building Project "C:\build\precommit_opencl\build\modules\dnn\opencv_dnn.vcxproj" (default targets) -- FAILED.
     1>Project "C:\build\precommit_opencl\build\ALL_BUILD.vcxproj" (1) is building "C:\build\precommit_opencl\build\modules\core\opencv_test_core.vcxproj" (351) on node 3 (default targets).
```

**Comment by alalek** [comment]
@oqtvs Thank you! I will take a look on these issues.

**Comment by oqtvs** [comment]
@alalek I have looked into it and it was a io_win32.cpp file that was missing on cmakefile, now mainly problem with trailing whitespace and warnings.

**Comment by oqtvs** [comment]
Fixed white-space problems, now mainly warnings,
One of them i found a solution on protobuf's repo:
-Wno-invalid-offsetof was used as solution for invalid offset warning on protobuf #3450 ( Wrote a note on protobuf build cmakefile )
But i think it is better to look with caution into them and see what effects they have.

**Comment by alalek** [comment]
I pushed an update, please take a look.
- split the first commit: update protobuf + update generated code
- regenerated .proto files with latest version (#10550)
- removed unused "test" files from protobuf

**Comment by oqtvs** [comment]
@alalek it looks good to me(builded locally and it is working)! The only question that remained to me was if the solution of suppressing the warnings: `/wd4701 /wd4703 -Winvalid-offsetof` was right (meaning that it isn't a bug on libprotobuf?) I haven't had the time to look into it. But besides my doubt everything is ok.

**Comment by alalek** [comment]
@oqtvs These warnings doesn't point on serious bug in protobuf.

**Comment by oqtvs** [comment]
Ok perfect! Thanks @alalek =)

**Pull request merged**
