### PR TITLE
Canny with own gradient

### PR DESCRIPTION
**Pull request by LaurentBerger**
### What does this PR change?
Please add your changes here.

With this PR it is possible to use canny non maxima suppression and d…ouble thresholding with a gradient image (not sobel only as previously)

### CODE REVIEW

**Comment by vpisarev** [comment]
the PR will be reopened because of CI issues

**Comment by alalek** [comment]
(comment is copied from #6804)
@LaurentBerger I add #6878 with reduced amount of changed code and added tests. The current PR should not closed because example is not ported yet.

**Comment by LaurentBerger** [comment]
OK

**Comment by LaurentBerger** [comment]
I have update my git repo with new Canny function and keep only example

**Comment by alalek** [comment]
I believe it is better to slightly extend existed canny example: samples/cpp/edge.cpp

**Comment by alalek** [comment]
Well done! Thanks you!
:+1:

**Pull request merged**
