### PR TITLE
gapi(test): avoid using of unstable random floating-point input

### LINKED ISSUE #14961: G-API: failed tests in SSE4.2 builds
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/master_opt-sse42_noICV-skl-lin64/builds/276):

```
[==========] 30123 tests from 308 test cases ran. (156235 ms total)
[  PASSED  ] 30104 tests.
[  FAILED  ] 19 tests, listed below:
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/434, where GetParam() = (5, 1280x720, 0, false, 0x564071396b30, compare_f, 2.5, -128)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/441, where GetParam() = (5, 1280x720, 2, false, 0x564071396b30, compare_f, 2.5, 250)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/443, where GetParam() = (5, 1280x720, 2, false, 0x564071396b30, compare_f, 2.5, -128)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/450, where GetParam() = (5, 1280x720, 3, false, 0x564071396b30, compare_f, 2.5, 250)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/452, where GetParam() = (5, 1280x720, 3, false, 0x564071396b30, compare_f, 2.5, -128)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/459, where GetParam() = (5, 1280x720, 5, false, 0x564071396b30, compare_f, 2.5, 250)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/461, where GetParam() = (5, 1280x720, 5, false, 0x564071396b30, compare_f, 2.5, -128)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/470, where GetParam() = (5, 640x480, 0, false, 0x564071396b30, compare_f, 2.5, -128)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/477, where GetParam() = (5, 640x480, 2, false, 0x564071396b30, compare_f, 2.5, 250)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/479, where GetParam() = (5, 640x480, 2, false, 0x564071396b30, compare_f, 2.5, -128)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/486, where GetParam() = (5, 640x480, 3, false, 0x564071396b30, compare_f, 2.5, 250)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/488, where GetParam() = (5, 640x480, 3, false, 0x564071396b30, compare_f, 2.5, -128)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/495, where GetParam() = (5, 640x480, 5, false, 0x564071396b30, compare_f, 2.5, 250)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/497, where GetParam() = (5, 640x480, 5, false, 0x564071396b30, compare_f, 2.5, -128)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/506, where GetParam() = (5, 128x128, 0, false, 0x564071396b30, compare_f, 2.5, -128)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/515, where GetParam() = (5, 128x128, 2, false, 0x564071396b30, compare_f, 2.5, -128)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/524, where GetParam() = (5, 128x128, 3, false, 0x564071396b30, compare_f, 2.5, -128)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/531, where GetParam() = (5, 128x128, 5, false, 0x564071396b30, compare_f, 2.5, 250)
[  FAILED  ] ConvertToGPU/ConvertToTest.AccuracyTest/533, where GetParam() = (5, 128x128, 5, false, 0x564071396b30, compare_f, 2.5, -128)
```

/cc @dmatveev

### PR DESCRIPTION
**Pull request by alalek**
resolves #14961

<cut/>

```
force_builders=Custom
buildworker:Custom=linux-5
build_image:Custom=ubuntu:18.04
CPU_BASELINE:Custom=SSE4_2
CPU_DISPATCH:Custom=
```

### CODE REVIEW

**Comment by dmatveev** [comment]
This is nice, but probably some other test suite methods may need to be updated. @TolyaTalamanov @AsyaPronina  can you please have a look on this?

**Comment by AsyaPronina** [comment]
Hi @dmatveev, @alalek! I don't think that these changes affect other methods logic, but we may be need the same logic for initScalarRandU, initMatsRandU, initMatrixRandN?

**Comment by alalek** [comment]
> ThresholdTestGPU/ThresholdTest.AccuracyTestBinary

Tests are failed due bug in OpenCV/IPP code: #16085

**Comment by alalek** [comment]
> BitwiseNotTestCPU/NotTest.AccuracyTest/13, where GetParam() = (32FC1, 640x480, SAME_TYPE, 0x9c489c)

Excluded 32F test cases: #16086 (due NaN results)

**Comment by alalek** [comment]
> initScalarRandU

The current implementation is buggy - it produces integers only.
Floating-point approach breaks several new tests. Postponed.

> initMatsRandU

Broken tests:
```
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] MathOperatorTestFluid/MathOperatorMatMatTest.OperatorAccuracyTest/164, where GetParam() = (32FC1, 1280x720, SAME_TYPE, 0x67d2a0, AbsExact(), operator/)
[  FAILED  ] MathOperatorTestFluid/MathOperatorMatMatTest.OperatorAccuracyTest/173, where GetParam() = (32FC1, 1280x720, 8UC1, 0x67d2a0, AbsExact(), operator/)
[  FAILED  ] MathOperatorTestFluid/MathOperatorMatMatTest.OperatorAccuracyTest/182, where GetParam() = (32FC1, 1280x720, 32FC1, 0x67d2a0, AbsExact(), operator/)
[  FAILED  ] MathOperatorTestFluid/MathOperatorMatMatTest.OperatorAccuracyTest/191, where GetParam() = (32FC1, 640x480, SAME_TYPE, 0x67d2a0, AbsExact(), operator/)
[  FAILED  ] MathOperatorTestFluid/MathOperatorMatMatTest.OperatorAccuracyTest/200, where GetParam() = (32FC1, 640x480, 8UC1, 0x67d2a0, AbsExact(), operator/)
[  FAILED  ] MathOperatorTestFluid/MathOperatorMatMatTest.OperatorAccuracyTest/209, where GetParam() = (32FC1, 640x480, 32FC1, 0x67d2a0, AbsExact(), operator/)
```

with not useful [test report](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/24091):
```
AbsExact error: G-API output and reference output matrixes are not bitexact equal.
/build/precommit_linux64/opencv/modules/gapi/test/common/gapi_operators_tests_inl.hpp:56: Failure
Value of: cmpF(out_mat_gapi, out_mat_ocv)
  Actual: false
Expected: true
```

Feel free to investigate this on your side.


> initMatrixRandN

Proposed transformation doesn't follow normal distribution rules. Differed.


-----

[Validated](http://pullrequest.opencv.org/buildbot/builders/master_opt-sse42_noICV-skl-lin64/builds/445) :+1:

**Pull request merged**
