### PR TITLE
Add clip to deploy.prototxt

### PR DESCRIPTION
**Pull request by LaurentBerger**
try to solve issue #14841 
@dkurt

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/650

```
force_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2019r1:16.04
build_image:Custom Win=openvino-2019r2.0
build_image:Custom Mac=openvino-2019r2.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
test_opencl:Custom=ON
test_bigdata:Custom=1
test_filter:Custom=*

allow_multiple_commits=1
```

### CODE REVIEW

**Comment by dkurt** [comment]
Please estimate an accuracy on FDDB and WIDER datasets using https://github.com/opencv/opencv/blob/master/modules/dnn/misc/face_detector_accuracy.py. We need to check if there is no regression.

**Comment by dkurt** [comment]
> Please estimate an accuracy on FDDB and WIDER datasets using https://github.com/opencv/opencv/blob/master/modules/dnn/misc/face_detector_accuracy.py. We need to check if there is no regression.

Theoretically, numerical accuracy should be improved due cropping of implicit edges to image because labels are also in the image space so IoU will be higher.

@LaurentBerger, do you mind to keep accuracy threshold unchanged? Anyway now an entire output blob is returned from `Net::forward`

**Comment by LaurentBerger** [comment]
@dkurt sorry for the delay. I must finish opencv python book before august. I think that I will work on this PR in august

**Comment by dkurt** [comment]
@LaurentBerger, sounds great! Feel free to ask us any question.

I can evaluate it by myself

**Comment by dkurt** [comment]
@LaurentBerger, please apply this commit to your branch: https://github.com/dkurt/opencv/commit/35c69f2dbe19f09f8320f7bcbf7a74224dad133d.

**Comment by LaurentBerger** [comment]
I have never done that : 

```
cd temp
git clone -b face_clip https://github.com/dkurt/opencv.git
cd opencv
git format-patch -1 f16c7ee
cd myopencv
git am < /f/lib/temp/opencv/0001-Fixes-for-OpenCV-face-detection-network.patch

```

is it good?

**Comment by dkurt** [comment]
@LaurentBerger, maybe try this:

```
git checkout face_clip

git remote add dkurt https://github.com/dkurt/opencv
git fetch dkurt face_clip
git cherry-pick f16c7ee848f9fbc2a104e6f9a4c242ceee080844
```

**Comment by LaurentBerger** [comment]
I hope that's good!

**Comment by dkurt** [comment]
@LaurentBerger, that's perfect! Thank you!

**Comment by LaurentBerger** [comment]
Yes now there is no problem in my used video. with clip 1 and #15118

**Pull request merged**
