### PR TITLE
Extracted matches_confindece_thresh as stitching matcher parameter.

### PR DESCRIPTION
**Pull request by asmorkalov**
Replacement for https://github.com/opencv/opencv/pull/19955/
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
Which parameter's value should be used to enable behavior from referenced PR?

**Comment by asmorkalov** [comment]
`matches_confindece_thresh = DOUBLE_MAX`.

**Comment by asmorkalov** [comment]
@alalek Could you take a look on
```
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library [C:\build\precommit_windows64\build\modules\imgcodecs\opencv_imgcodecs.vcxproj]
```

it's not related to the patch IMHO.

**Comment by alalek** [comment]
It is broken 1-2 weeks ago (spng or other PR to imgcodecs).

See nightly builds here: https://pullrequest.opencv.org/buildbot/builders/master-win64-vc14

**Comment by asmorkalov** [comment]
@alalek  The fix for runtime library warning was merged. I rebased this PR, it's ready.

**Review by alalek — APPROVED** [review]

**Pull request merged**
