### PR TITLE
Fix issues in opencv_test_dnn from conv48 kernels without bias

### PR DESCRIPTION
**Pull request by scottchou007**
Original PR: #22419

Descriptions:
The issue was found in several networks in original Opencv case "opencv_test_dnn" on NXP iMX8 ARM64 platform with Vulkan backend. It happens randomly from the networks that uses parallel convolution kernel "conv48".

Affected test: "opencv_test_dnn" with Vulkan backed (VKCOM).

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
> into `opencv:master`

Patch should go to 4.x branch: https://github.com/opencv/opencv/wiki/Branches

**Comment by alalek** [comment]
Please take a look on whitespace issues: http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/101015

Wiki page: https://github.com/opencv/opencv/wiki/How_to_contribute#q3-i-was-asked-to-remove-whitespace-issues-how-can-i-do-that

**Comment by rogday** [comment]
I don't see any regressions, but I also can't download all models with `download_models.py` (404 and stuff), so someone else should test this also since our CI doesn't test all the backends at the moment.

**Review by rogday — APPROVED** [review]
NVM, I found missing nets, looks good.

**Comment by asmorkalov** [comment]
@scottchou007 please squash the commits to have clean repo history.

**Comment by scottchou007** [comment]
Commits merged.

**Pull request merged**
