### PR TITLE
Update table of content for imgproc module tutorials to reflect languages used

### PR DESCRIPTION
**Pull request by dmallia17**
This adds the Languages field for the "Random generator and text with OpenCV" tutorial and updates the Languages field for the "Anisotropic image segmentation by a gradient structure tensor" tutorial.

On a related note: I have not been able to locate an equivalent for the C++ RNG class in Python, but I believe this functionality can be achieved with NumPy (among other options). If I have missed the equivalent or if NumPy is an acceptable alternative, I would very much like to try expanding the "Random generator and text with OpenCV" tutorial to include Python. Thank you!

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@dmallia17 Functions like `theRNG` that returns default OpenCV random generator are not wrapped into Python bindings and you need to use alternatives. Numpy `np.random` is good choice. Some OpenCV algorithms are stochastic by design and use OpenCV RNG implementation internally. You still can manage their parameters in Python with calls like `setRNGSeed`.

**Comment by asmorkalov** [comment]
@dmallia17 Could you squash the commits to have clean library history?

**Comment by dmallia17** [comment]
@asmorkalov I believe that should do it - please correct me if I'm wrong. (First time having to squash commits for a PR!)

Also thank you very much for the explanation! I did spot `setRNGSeed` but wasn't sure of its usage. I am hopeful that I will be able to tackle expanding that tutorial very soon.

**Comment by dmallia17** [comment]
@asmorkalov Thank you! After looking around a bit further, I have found a couple of other tutorial modules where the table of contents should be updated. Would it be best to make a pull request for each table of contents or update all of the ones I spot at once?

**Comment by alalek** [comment]
@dmallia17 Thank you for contribution! Feel free to create single Pull Request with similar changes.

**Comment by dmallia17** [comment]
@alalek  Thank you very much - will do!

**Pull request merged**
