### PR TITLE
Pev  handle dna vectors

### PR DESCRIPTION
**Pull request by pemmanuelviel**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by mshabunin** [comment]
I'm wondering why do we add specialized DNA-processing functionality to the library?

**Comment by pemmanuelviel** [comment]
Why not as all the infrastructure is there? Back to May, thinking what I
could do at my level in this Covid period, I’ve realised the clustering of
binary vectors I worked on in FLANN several years ago could also be
employed for DNA. Idea is to bring such feature so anyone can play and
cluster sequences for stats or other purposes (for instance there were 326
variants of the Covid-19 at the time I did that). Who knows, this might
create vocations...


Le vendredi 28 août 2020, Maksim Shabunin <notifications@github.com> a
écrit :

**Review by alalek — APPROVED** [review]
Lets put it in (we have already merged DNA enumerations).

Anyway it is better to keep computer vision and related tasks as primary OpenCV functionality.

**Comment by pemmanuelviel** [comment]
Thanks Alexander.
The other way round, if some are downloading OpenCV for these FLANN
features, they might end up practicing Computer Vision ;-)

**Pull request merged**
