### PR TITLE
some improvements on tutorials

### PR DESCRIPTION
**Pull request by sturkmen72**
### This pullrequest changes

1. enriching documentation ( adding more example to documentation )
2. giving default values to needed parameters ( mostly a default image )
3. removing unnecessary lines

### CODE REVIEW

**Comment by sturkmen72** [comment]
hi @alalek what is your opinion on this kind of improvements on tutorials?

i am afraid if i will stole developers time to review

**Comment by alalek** [comment]
Look good to me. It is always useful to run and improve samples periodically. Thank you!

**Comment by sturkmen72** [comment]
let me know if i am on the right path. i will continue to make smilar modifications.

**Comment by alalek** [comment]
:+1:

**Pull request merged**
