### PR TITLE
Added type deduced v_setall intrinsic

### PR DESCRIPTION
**Pull request by terfendail**
### This pullrequest changes
Added type deduced v_setall intrinsic

<cut/>

```
force_builders=Custom
buildworker:Custom=linux-1,linux-2,linux-4
docker_image:Custom=ubuntu-clang:18.04
```

### CODE REVIEW

**Comment by terfendail** [comment]
v_setall_##<short_type_id>(type val) intrinsics are declared the way it is possible to deduce short_type_id from the input value type. So it could be convenient to use uniform named version.

**Comment by alalek** [comment]
What is about a variant via template? (would help with proper forcing of used types)

**Comment by terfendail** [comment]
Corresponding low-level intrinsics have different names for different types(at least for x86 SIMD) so it looks like it would be necessary to specialize the template for every type. Existing implementation will  IMO also force correctness of input type because it will define the output vector type that can't be implicitly casted to another vector type if there is a mismatch. The change make impossible(or essentially harder) to add implicit vector type casting, but I doubt whether we need such casting.

**Comment by alalek** [comment]
Please add corresponding intrinsic test

**Comment by alalek** [comment]
@terfendail Could you take a look on this patch: #15839 ?

**Comment by asmorkalov** [comment]
@terfendail, @alalek  Do you have aby progress on the patch?

**Comment by terfendail** [comment]
Replaced by #15839

**Pull request closed without merging**
