### PR TITLE
Adding threading in calibrate.py

### PR DESCRIPTION
**Pull request by art049**
### This pullrequest changes

This pull request add threading in the calibration.py sample script. The old script can take a lot of time to be executed on large images.

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for your effort!
But lets keep samples as simple as possible.

**Comment by art049** [comment]
Do you think adding this multi-threading could be useful in interactive calibration ?
I've been using it and it's quite annoying to wait a long time when images are large

**Comment by alalek** [comment]
I believe, effective interactive calibration application should cache results of chess-board detection for previous frames. In this case parallel processing of images is not necessary (can't be applied, because we have one new image only).

BTW, Did you have a chance to take a look on this application (C++): https://github.com/opencv/opencv/tree/master/apps/interactive-calibration ?

**Comment by art049** [comment]
Yes, I had a look. I understand your point when processing a video. But
when the input is a sequence of images It could be a lot faster just with
threading. I'm just asking because I did the modifications for myself and I
was interested in sharing these.

**Comment by alalek** [comment]
I have pushed update with changes:
- replace magic THREADS number with command-line argument
- drop manual locks
- use Python thread [Pool](https://docs.python.org/2/library/multiprocessing.html#module-multiprocessing.dummy)
- other fixes (allow to disable debug mode, incorrect image pattern, etc)

**Pull request merged**
