### PR TITLE
Some mist. typo fixes

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -i 3 -w --skip="./3rdparty" -I ../opencv-whitelist.txt`

### CODE REVIEW

**Comment by vpisarev** [comment]
thanks! :+1:

**Comment by luzpaz** [comment]
@vpisarev quick question in the ./platforms/linux directory there are the following:
```
./platforms/linux/ppcat.toolchain.cmake:62: INTERAL  ==> INTERNAL, INTEGRAL
./platforms/linux/ppcat.toolchain.cmake:63: INTERAL  ==> INTERNAL, INTEGRAL
./platforms/linux/ppcat.toolchain.cmake:64: INTERAL  ==> INTERNAL, INTEGRAL
./platforms/linux/ppcat.toolchain.cmake:65: INTERAL  ==> INTERNAL, INTEGRAL
./platforms/linux/ppcat.toolchain.cmake:66: INTERAL  ==> INTERNAL, INTEGRAL
./platforms/linux/arm.toolchain.cmake:52: INTERAL  ==> INTERNAL, INTEGRAL
./platforms/linux/arm.toolchain.cmake:53: INTERAL  ==> INTERNAL, INTEGRAL
./platforms/linux/arm.toolchain.cmake:54: INTERAL  ==> INTERNAL, INTEGRAL
./platforms/linux/arm.toolchain.cmake:55: INTERAL  ==> INTERNAL, INTEGRAL
./platforms/linux/arm.toolchain.cmake:56: INTERAL  ==> INTERNAL, INTEGRAL
```
should I s/INTERAL/INTERNAL/ ?

**Comment by alalek** [comment]
`INTERNAL`

**Comment by luzpaz** [comment]
@alalek A-OK, will submit this fix in a follow-up PR. 😉

**Comment by luzpaz** [comment]
@alalek submitted fix as part of #10814

**Pull request merged**
