### PR TITLE
core: remove raw SSE2/NEON implementation from convert.cpp

### PR DESCRIPTION
**Pull request by tomoaki0705**
### This pullrequest changes
  * remove raw implementation from ```Cvt_SIMD```
  * remove raw implementation from ```cvtScale_SIMD```
  * remove duplicated implementation ```cvt_<float, short>```
  * remove duplicated implementation ```cvtScale_<short, short, float>```
  * add "from double" version of ```Cvt_SIMD```

### CODE REVIEW

**Comment by vpisarev** [comment]
@tomoaki0705, wow, that's a big patch! thank you! Did you measure the performance before and after your patch?

**Comment by alalek** [comment]
Consider disabling IPP (env: `OPENCV_IPP=disabled`)  to debug observed issue.

**Comment by vpisarev** [comment]
@alalek, thanks, it really helped to reproduce the problem!

**Comment by tomoaki0705** [comment]
@vpisarev , I forgot to thank you for brushing up my PR.
I didn't imagine this big amount of modify was needed to finish this.
I really appreciate your help, thank you !

**Pull request merged**
