### PR TITLE
fix conflicting Pointer and SmartPointer

### LINKED ISSUE #5894: Algorithm::save (and other Algorithm methods) broken for Java bindings
I ran into an issue with the Java bindings in OpenCV 3.1

When attempting to save a Boost model I received a core dump.  

The error appears to be in the generated Java<->CPP linkage which is:

```
JNIEXPORT void JNICALL Java_org_opencv_core_Algorithm_save_10
  (JNIEnv* env, jclass , jlong self, jstring filename)
{
    static const char method_name[] = "core::save_10()";
    try {
        LOGD("%s", method_name);
        cv::Algorithm* me = (cv::Algorithm*) self; //TODO: check for NULL                                                                                                                                            
        const char* utf_filename = env->GetStringUTFChars(filename, 0); String n_filename(utf_filename ? utf_filename : "" ); env->ReleaseStringUTFChars(filename, utf_filename);
        me->save( n_filename );
        return;
    } catch(const std::exception &e) {
        throwJavaException(env, &e, method_name);
    } catch (...) {
        throwJavaException(env, 0, method_name);
    }
    return;
}
```

Debugging the generated core file with gdb it appears that me is not a valid pointer to `cv::Algorithm*` (although it is not NULL).  The line `me->save` is where the segmentation fault occurs and looking at the stack trace it does not appear that it is getting to the save method.  

Calling empty() on StatModel (another class in the heirarchy) does work and I notice the linkage code constructs the pointer as:

```
    Ptr<cv::ml::StatModel>* me = (Ptr<cv::ml::StatModel>*) self; //TODO: check for NULL                                                                                                                          
    bool _retval_ = (*me)->empty(  );
```

If I move the save implementation into the `StatModel` class then it works fine.  I tried all other `Algorithm` implemented methods and got the same results.

### PR DESCRIPTION
**Pull request by utibenkei**
### This pullrequest changes

Since normal pointers and smart pointers were mixed, many problems were occurring.
This pull request changes all classes to handle with smart pointers.
This fix solves many crashes.
resolves #5894

### CODE REVIEW

**Comment by vpisarev** [comment]
@mshabunin, could you please review it?

**Comment by alalek** [comment]
BTW, `cv::Mat` has "smart pointer" design actually (with some tricks like assignment, `.create()`, `.clone()` methods and so on).
I have no chance to take a look on this patch yet, but I believe we should not wrap `cv::Mat` into `cv::Ptr` without a strong reason.

**Comment by utibenkei** [comment]
The file that is changed by this pull request is only the class automatically generated by **gen_java.py**. Mat classes will not be changed.

**old code**
An segmentation fault happens when "self" is Ptr<>.
Please see this issue.#5894 Such problems are occurring in many classes.
```
JNIEXPORT void JNICALL Java_org_opencv_core_Algorithm_save_10 (JNIEnv*, jclass, jlong, jstring);

JNIEXPORT void JNICALL Java_org_opencv_core_Algorithm_save_10
  (JNIEnv* env, jclass , jlong self, jstring filename)
{
    static const char method_name[] = "core::save_10()";
    try {
        LOGD("%s", method_name);
        cv::Algorithm* me = (cv::Algorithm*) self; //TODO: check for NULL
        const char* utf_filename = env->GetStringUTFChars(filename, 0); String n_filename( utf_filename ? utf_filename : "" ); env->ReleaseStringUTFChars(filename, utf_filename);
        me->save( n_filename );  //An segmentation fault happens at this line when "self" is Ptr<>.
        return;
    } catch(const std::exception &e) {
        throwJavaException(env, &e, method_name);
    } catch (...) {
        throwJavaException(env, 0, method_name);
    }
    return;
}
```


**new code**
```
JNIEXPORT void JNICALL Java_org_opencv_core_Algorithm_save_10 (JNIEnv*, jclass, Ptr<cv::Algorithm>*, jstring);
 
JNIEXPORT void JNICALL Java_org_opencv_core_Algorithm_save_10
  (JNIEnv* env, jclass , Ptr<cv::Algorithm>* self, jstring filename)
{
    static const char method_name[] = "core::save_10()";
    try {
        LOGD("%s", method_name);
        Ptr<cv::Algorithm>* me = (Ptr<cv::Algorithm>*) self; //TODO: check for NULL
        const char* utf_filename = env->GetStringUTFChars(filename, 0); String n_filename( utf_filename ? utf_filename : "" ); env->ReleaseStringUTFChars(filename, utf_filename);
        (*me)->save( n_filename );
        return;
    } catch(const std::exception &e) {
        throwJavaException(env, &e, method_name);
    } catch (...) {
        throwJavaException(env, 0, method_name);
    }
    return;
}
```

**Comment by mshabunin** [comment]
@utibenkei , does JNI support passing arbitrary pointers via function parameters? I thought it supports only several primitive types: https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/types.html
What will happen if we switch native library to 32 bit?

Please, check whether the fix from #8524 works for you.

**Comment by utibenkei** [comment]
@mshabunin As you said, passing arbitrary pointers via function parameters does not seem appropriate.

#8524 is a simple and perfect solution. The problem has been fixed.
Thank you.

**Pull request closed without merging**
