### PR TITLE
Fix error backend

### PR DESCRIPTION
**Pull request by Danile71**
### Pull Request Readiness Checklist
image

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
Please add description about the problem.

**Comment by Danile71** [comment]
> Please add description about the problem.

image
I tried load [models](https://download.01.org/opencv/2021/openvinotoolkit/2021.2/open_model_zoo/models_bin/3/face-detection-retail-0005/FP16/)

**Comment by dkurt** [comment]
Seems like OpenCV was build without nGraph. Let's check CMake summary first. Model https://download.01.org/opencv/2021/openvinotoolkit/2021.2/open_model_zoo/models_bin/3/face-detection-retail-0005/FP16/ is IRv10 that means there should not be such error.

**Comment by Danile71** [comment]
> Seems like OpenCV was build without nGraph. Let's check CMake summary first. Model https://download.01.org/opencv/2021/openvinotoolkit/2021.2/open_model_zoo/models_bin/3/face-detection-retail-0005/FP16/ is IRv10 that means there should not be such error.

model
cmake
error

**Comment by alalek** [comment]
It is ridiculous to post text information through screenshots. At least searching for similar issues doesn't work.

Build configuration is invalid:
- `/usr/local/lib/libngraph.so`

This path must be from openvino location. Use `ngraph_DIR` for proper configuration (it is a part of OpenVINO's `setupvars.sh`).
Perhaps you didn't drop CMake cache after applying `setupvars.sh` in the middle. Always drop CMake cache (or clean build directory) if external dependencies (or build environment) are changed and you want to run CMake again.

Patch is not correct. At least it doesn't fix anything (except exception message removal).
Use issues for reporting problems instead if you have enough evidences. Try to download and play with pre-build packages first (they are validated at least), before trying to build something yourself.

Closing.

**Comment by Danile71** [comment]
> It is ridiculous to post text information through screenshots. At least searching for similar issues doesn't work.
> 
> Build configuration is invalid:
> 
> * `/usr/local/lib/libngraph.so`
> 
> This path must be from openvino location. Use `ngraph_DIR` for proper configuration (it is a part of OpenVINO's `setupvars.sh`).
> Perhaps you didn't drop CMake cache after applying `setupvars.sh` in the middle. Always drop CMake cache (or clean build directory) if external dependencies (or build environment) are changed and you want to run CMake again.
> 
> Patch is not correct. At least it doesn't fix anything (except exception message removal).
> Use issues for reporting problems instead if you have enough evidences. Try to download and play with pre-build packages first (they are validated at least), before trying to build something yourself.
> 
> Closing.

/usr/local/lib/libngraph.so - path after make install ie. (I tested -D ngraph_DIR=/openvino/build/ngraph, same erorr)

I make docker build with cuda+openvino support (prev versions ie+opencv works perfect, about 1 year, but 4.5.1 update broke code)

**Pull request closed without merging**
