### PR TITLE
Added information to OpenCV documentation [MacOS]

### LINKED ISSUE #17340: Add and Edit specific information to the "Installation in MacOS" OpenCV documentation
In the current OpenCV "[Installation in MacOS](https://docs.opencv.org/master/d0/db2/tutorial_macos_install.html)" documentation, some things need to be edited in order to make it more simple for the user.

- In the **Installing CMake** section, the writer tells us to go to "Tools –> Install For Command Line Use". Unfortunately, "Install For Command Line Use" is not an option. The instructions should tell us to go to "Tools -> How to Install for Command Line Use" and then follow the instructions from the pop-up there.

- Another thing, the writer accidentally labeled the wrong folder name in Step #1 under the **Building OpenCV from Source Using CMake** section. This can make it difficult for the user to follow along, since a completely different folder name was used later on.

- In Step #2 under the **Building OpenCV from Source Using CMake** section, there are two bullet points that say "set full path to ___". I think users will benefit more if the documentation was a bit more specific. In this case, it should say "Set OpenCV source code path to ___" and "Set binary build path to ____".

These changes seem fairly simple, I will be making a pull request accounting for these changes soon!

### PR DESCRIPTION
**Pull request by wongjessica**
Closes #17340

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ✓ ] I agree to contribute to the project under OpenCV (BSD) License.
- [ ✓ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ✓ ] The PR is proposed to proper branch
- [ ✓ ] There is reference to original bug report and related work
- [ ✓ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ✓ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for contribution!

This patch should go into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first.
We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

**Comment by asmorkalov** [comment]
@wongjessica Please pay attention on PR commits history. The branch is still based on master.

**Comment by asmorkalov** [comment]
@wongjessica Friendly reminder.

**Comment by asmorkalov** [comment]
@wongjessica Do you have a chance to rebase the PR properly?

**Comment by wongjessica** [comment]
Hello @asmorkalov With the help of my friend, it should be fixed!

**Pull request merged**
