### PR TITLE
Creation of Maven POM project and documentation.

### PR DESCRIPTION
**Pull request by vpisarev**
### Former  #6492

by @jtkb:

#### This pull request introduces an Apache Maven build to OpenCV, it makes no modification to any existing source files.

The Maven build is simply a wrapper around the existing CMake one with some additional features.

The motivation for introducing Maven is to provide a robust build process for creating OpenCV native and Java libraries as well as create an additional OSGi-compatible bundle. Aimed at Debian Linux distributions the Maven build can therefore function on x86 and ARM architectures e.g. Ubuntu or Raspbian. Prior to building the libraries the Maven build carries out checks for required native libraries and environment failing if these are not as required.

One extra directory has been included to contain scripts used in the build and an additional Markdown document is provides guidance on how to use the Maven build.

### CODE REVIEW

**Comment by mshabunin** [comment]
Ping @jtkb

**Comment by jtkb** [comment]
Hi mshabunin. I saw the notifications, just not had chance to resolve yet

**Comment by jtkb** [comment]
OK squashed.

**Comment by alalek** [comment]
@jtkb Thank you! :+1:

**Pull request merged**
