### PR TITLE
dnn (cuda): support broadcasting if a.rank() != b.rank()

### PR DESCRIPTION
**Pull request by fengyuentau**
Inspired by https://github.com/opencv/opencv/pull/24786. This PR keeps the fusion of `NaryEltwise` and `Concat` while addressed the data missing problem via supporting broadcasting if a.rank() != b.rank().

Resolves https://github.com/opencv/opencv/issues/23977
Resolves https://github.com/opencv/opencv/issues/24606
Resolves https://github.com/opencv/opencv/issues/24635
Resolves https://github.com/opencv/opencv/issues/24721 

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by fengyuentau** [comment]
Tried to add yolov8n to test on different backends, but turns out we may have more problems, especially in CUDA_FP16 target:

```
[ RUN      ] DNNTestNetwork.YOLOv8n/0, where GetParam() = CUDA/CUDA
/workspace/cuda_naryeltwise_broadcast/opencv/modules/dnn/test/test_common.impl.hpp:79: Failure
Expected: (normInf) <= (lInf), actual: 0.0010376 vs 0.0001
First run  |ref| = 638.03076171875
/workspace/cuda_naryeltwise_broadcast/opencv/modules/dnn/test/test_common.impl.hpp:79: Failure
Expected: (normInf) <= (lInf), actual: 0.00109863 vs 0.0001
Second run  |ref| = 638.5064697265625
[  FAILED  ] DNNTestNetwork.YOLOv8n/0, where GetParam() = CUDA/CUDA (288 ms)
[ RUN      ] DNNTestNetwork.YOLOv8n/1, where GetParam() = CUDA/CUDA_FP16
/workspace/cuda_naryeltwise_broadcast/opencv/modules/dnn/test/test_common.impl.hpp:76: Failure
Expected: (normL1) <= (l1), actual: 0.0118579 vs 0.004
First run  |ref| = 638.03076171875
/workspace/cuda_naryeltwise_broadcast/opencv/modules/dnn/test/test_common.impl.hpp:79: Failure
Expected: (normInf) <= (lInf), actual: 6.54901 vs 0.02
First run  |ref| = 638.03076171875
/workspace/cuda_naryeltwise_broadcast/opencv/modules/dnn/test/test_common.impl.hpp:76: Failure
Expected: (normL1) <= (l1), actual: 0.0119177 vs 0.004
Second run  |ref| = 638.5064697265625
/workspace/cuda_naryeltwise_broadcast/opencv/modules/dnn/test/test_common.impl.hpp:79: Failure
Expected: (normInf) <= (lInf), actual: 8.83636 vs 0.02
Second run  |ref| = 638.5064697265625
[  FAILED  ] DNNTestNetwork.YOLOv8n/1, where GetParam() = CUDA/CUDA_FP16 (601 ms)
[ RUN      ] DNNTestNetwork.YOLOv8n/2, where GetParam() = OCV/OCL
[ WARN:0@1.061] global ocl4dnn_conv_spatial.cpp:1931 loadTunedConfig OpenCV(ocl4dnn): consider to specify kernel configuration cache directory through OPENCV_OCL4DNN_CONFIG_PATH parameter.
OpenCL program build log: dnn/dummy
Status -11: CL_BUILD_PROGRAM_FAILURE
-cl-no-subgroup-ifp
Error in processing command line: Don't understand command line argument "-cl-no-subgroup-ifp"!
/workspace/cuda_naryeltwise_broadcast/opencv/modules/dnn/test/test_common.impl.hpp:79: Failure
Expected: (normInf) <= (lInf), actual: 0.00161743 vs 0.0001
First run  |ref| = 638.03076171875
/workspace/cuda_naryeltwise_broadcast/opencv/modules/dnn/test/test_common.impl.hpp:79: Failure
Expected: (normInf) <= (lInf), actual: 0.00117493 vs 0.0001
Second run  |ref| = 638.5064697265625
[  FAILED  ] DNNTestNetwork.YOLOv8n/2, where GetParam() = OCV/OCL (3184 ms)
[ RUN      ] DNNTestNetwork.YOLOv8n/3, where GetParam() = OCV/OCL_FP16
[       OK ] DNNTestNetwork.YOLOv8n/3 (545 ms)
[----------] 4 tests from DNNTestNetwork (4618 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (4618 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] DNNTestNetwork.YOLOv8n/0, where GetParam() = CUDA/CUDA
[  FAILED  ] DNNTestNetwork.YOLOv8n/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] DNNTestNetwork.YOLOv8n/2, where GetParam() = OCV/OCL
```

**Comment by Abdurrahheem** [comment]
@fengyuentau once this PR is complete (currently yolov8 is not supported on CUDA here, AFAK) does it mean that PR #24786 is going be obsolete?

**Comment by fengyuentau** [comment]
> does it mean that PR https://github.com/opencv/opencv/pull/24786 is going be obsolete?

Yes.

> currently yolov8 is not supported on CUDA here

It's not true. There are some minor differences in the results between CPU and CUDA/CUDA, which is OK I think, but the differences are much bigger when it comes to the CUDA_FP16 target. I guess we lose some accuracy in `Sigmoid` and such. Need an in-depth investigation.

**Comment by asmorkalov** [comment]
Locally I observe several test failures like this:
```
[----------] 1 test from Layer_Test_Eltwise_bcast
[ RUN      ] Layer_Test_Eltwise_bcast.brute_force/10, where GetParam() = ("sum", 3, CUDA/CUDA)
Exception message: OpenCV(4.9.0-dev) /mnt/projects/Projects/OpenCV/opencv-master/modules/dnn/src/cuda/../cuda4dnn/csl/tensor.hpp:1047: error: (-215:Assertion failed) rank() >= 2 in function 'squeeze'

/mnt/projects/Projects/OpenCV/opencv-master/modules/dnn/test/test_layers.cpp:2053: Failure
Expected: re = net.forward() doesn't throw an exception.
  Actual: it throws.
Exception message: OpenCV(4.9.0-dev) /mnt/projects/Projects/OpenCV/opencv-master/modules/dnn/src/cuda/../cuda4dnn/csl/tensor.hpp:1047: error: (-215:Assertion failed) rank() >= 2 in function 'squeeze'

/mnt/projects/Projects/OpenCV/opencv-master/modules/dnn/test/test_layers.cpp:2053: Failure
Expected: re = net.forward() doesn't throw an exception.
  Actual: it throws.
Exception message: OpenCV(4.9.0-dev) /mnt/projects/Projects/OpenCV/opencv-master/modules/dnn/src/cuda/../cuda4dnn/csl/tensor.hpp:1047: error: (-215:Assertion failed) rank() >= 2 in function 'squeeze'

/mnt/projects/Projects/OpenCV/opencv-master/modules/dnn/test/test_layers.cpp:2053: Failure
Expected: re = net.forward() doesn't throw an exception.
  Actual: it throws.
Exception message: OpenCV(4.9.0-dev) /mnt/projects/Projects/OpenCV/opencv-master/modules/dnn/src/cuda/../cuda4dnn/csl/tensor.hpp:1047: error: (-215:Assertion failed) rank() >= 2 in function 'squeeze'

/mnt/projects/Projects/OpenCV/opencv-master/modules/dnn/test/test_layers.cpp:2053: Failure
Expected: re = net.forward() doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] Layer_Test_Eltwise_bcast.brute_force/10, where GetParam() = ("sum", 3, CUDA/CUDA) (1536 ms)
```

Full list:
```
[  FAILED  ] Layer_Test_Eltwise_bcast.brute_force/10, where GetParam() = ("sum", 3, CUDA/CUDA)
[  FAILED  ] Layer_Test_Eltwise_bcast.brute_force/11, where GetParam() = ("sum", 3, CUDA/CUDA_FP16)
[  FAILED  ] Layer_Test_Eltwise_bcast.brute_force/15, where GetParam() = ("sum", 4, CUDA/CUDA)
[  FAILED  ] Layer_Test_Eltwise_bcast.brute_force/16, where GetParam() = ("sum", 4, CUDA/CUDA_FP16)
[  FAILED  ] Layer_Test_Eltwise_bcast.brute_force/20, where GetParam() = ("sum", 5, CUDA/CUDA)
[  FAILED  ] Layer_Test_Eltwise_bcast.brute_force/21, where GetParam() = ("sum", 5, CUDA/CUDA_FP16)
```

**Comment by fengyuentau** [comment]
It was due to there are inputs of shape [1] (1d mat) in these failed tests. In cuda backend, there are asserts checking `rank>=2`. So it is not feasible to run these tests with CUDA backend without bypassing the assert checks.

It works previously because it was not actually testing the CUDA backend; If two inputs have different dimensions, it falls back to CPU implementation. So it tests nothing related to the CUDA backend in these case. See below for the fall back (Line 804-805):

https://github.com/opencv/opencv/blob/5c9ad9d2c974613b610dcf108a58a1f3e35d9b37/modules/dnn/src/layers/nary_eltwise_layers.cpp#L800-L811

---

With that being said, I propose to turn off these tests specifically for CUDA backend. @asmorkalov What do you think?

@WanliZhong Please join this talk as well.

**Comment by fengyuentau** [comment]
> It was due to there are inputs of shape [1] (1d mat) in these failed tests. In cuda backend, there are asserts checking `rank>=2`. So it is not feasible to run these tests with CUDA backend without bypassing the assert checks.
> 
> It works previously because it was not actually testing the CUDA backend; If two inputs have different dimensions, it falls back to CPU implementation. So it tests nothing related to the CUDA backend in these case. See below for the fall back (Line 804-805):
> 
> https://github.com/opencv/opencv/blob/5c9ad9d2c974613b610dcf108a58a1f3e35d9b37/modules/dnn/src/layers/nary_eltwise_layers.cpp#L800-L811
> 
> With that being said, I propose to turn off these tests specifically for CUDA backend. @asmorkalov What do you think?
> 
> @WanliZhong Please join this talk as well.

Or we still fall back to CPU when dimension is 1.

**Comment by WanliZhong** [comment]
I propose fallback when dim is 1 to make sure cuda run correctly rather than throw an error

**Comment by fengyuentau** [comment]
> > It was due to there are inputs of shape [1] (1d mat) in these failed tests. In cuda backend, there are asserts checking `rank>=2`. So it is not feasible to run these tests with CUDA backend without bypassing the assert checks.
> > It works previously because it was not actually testing the CUDA backend; If two inputs have different dimensions, it falls back to CPU implementation. So it tests nothing related to the CUDA backend in these case. See below for the fall back (Line 804-805):
> > https://github.com/opencv/opencv/blob/5c9ad9d2c974613b610dcf108a58a1f3e35d9b37/modules/dnn/src/layers/nary_eltwise_layers.cpp#L800-L811
> > 
> > With that being said, I propose to turn off these tests specifically for CUDA backend. @asmorkalov What do you think?
> > @WanliZhong Please join this talk as well.
> 
> Or we still fall back to CPU when dimension is 1.

It does not work due to the 1d mat is actually produced during the broadcasting implementation in the CUDA backend. Let me find another solution to this.

**Comment by fengyuentau** [comment]
New commits should resolve this problem.

**Comment by fengyuentau** [comment]
Sporadic crash in `PR:4.x / macOS-ARM64-Vulkan / BuildAndTest (pull_request)`. This patch makes no changes on Caffe and Vulkan.

**Review by Abdurrahheem — APPROVED** [review]

**Review by dkurt — APPROVED** [review]

**Pull request merged**
