### PR TITLE
Fix #13577

### LINKED ISSUE #13577: cv::resize, UMat refcount Error when setting UseOpenCL to false
##### System information (version)
- OpenCV => 4.0.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

`unknown file: error: C++ exception with description "OpenCV(4.0.0) d:\opencv\opencv-4.0.0\modules\core\src\matrix.cpp:169: error: (-215:Assertion failed) u->refcount == 0 in function 'cv::StdMatAllocator::deallocate'
" thrown in the test body.`

##### Steps to reproduce

    cv::ocl::setUseOpenCL(false);
    UMat foo( 10, 10, CV_32FC1 );
    cv::resize(foo, foo, cv::Size(), .5, .5 );  // <-- happens here

Only happens when `src`==`dst` for `cv::resize`
See similar:  https://github.com/opencv/opencv/issues/8693

### PR DESCRIPTION
**Pull request by clunietp**
### This pullrequest changes
resolves #13577

### CODE REVIEW

**Comment by clunietp** [comment]
I expected this change to trigger the test builds, but it wasn't picked up by the buildbot.  What can I do to trigger this manually?

**Comment by asmorkalov** [comment]
@terfendail @dkurt Any comments on patch?

**Comment by dkurt** [comment]
@clunietp, Please change target branch to 3.4. Despite the [previous comment](https://github.com/opencv/opencv/pull/13594#issuecomment-453918389) it will require a new PR. Then we will port the patch to master branch.

**Comment by asmorkalov** [comment]
@dkurt Should I close the PR for now?

**Comment by dkurt** [comment]
Probably we should wait for another PR. Otherwise we can just miss it.

Another option is to open it by ourselves adding @clunietp as an author.

**Comment by clunietp** [comment]
Sorry, I've been busy.  I'll try to get a PR in today; the change is pretty simple

**Pull request closed without merging**
