### PR TITLE
G-API(test): avoid anonymous namespace types as template parameters

### LINKED ISSUE #18865: G-API: Build warnings with GCC 7.5 (Ubuntu 18.04)
[Nigthly build](http://pullrequest.opencv.org/buildbot/builders/master_opt-avx2_noICV-skl-lin64/builds/776):

```
[1186/1744] Building CXX object modules/gapi/CMakeFiles/opencv_test_gapi.dir/test/cpu/gapi_ocv_stateful_kernel_tests.cpp.o
In file included from /build/master_opt-avx2_noICV-skl-lin64/opencv/modules/gapi/include/opencv2/gapi/gcommon.hpp:17:0,
                 from /build/master_opt-avx2_noICV-skl-lin64/opencv/modules/gapi/include/opencv2/gapi/gmat.hpp:15,
                 from /build/master_opt-avx2_noICV-skl-lin64/opencv/modules/gapi/include/opencv2/gapi.hpp:25,
                 from /build/master_opt-avx2_noICV-skl-lin64/opencv/modules/gapi/test/cpu/../test_precomp.hpp:18,
                 from /build/master_opt-avx2_noICV-skl-lin64/opencv/modules/gapi/test/cpu/gapi_ocv_stateful_kernel_test_utils.hpp:10,
                 from /build/master_opt-avx2_noICV-skl-lin64/opencv/modules/gapi/test/cpu/gapi_ocv_stateful_kernel_tests.cpp:7:
/build/master_opt-avx2_noICV-skl-lin64/opencv/modules/gapi/include/opencv2/gapi/util/any.hpp:70:21: warning: 'cv::util::any::holder_ptr cv::util::any::holder_impl<value_t>::clone() [with value_t = opencv_test::{anonymous}::UserStruct]' declared 'static' but never defined [-Wunused-function]
          holder_ptr clone() override { return holder_ptr(new holder_impl (v));}
                     ^~~~~
```

---

[GCC 8 is affected too](http://pullrequest.opencv.org/buildbot/builders/master_etc-fedora-tbb-lin64/builds/779).

### PR DESCRIPTION
**Pull request by alalek**
resolves #18865

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by anton-potapov** [comment]
@alalek  thank you very much ! 

It very unobvious to get understand what `static` means in this  compiler warnings

**Review by anton-potapov — COMMENTED** [review]
LGTM

**Comment by dmatveev** [comment]
Thanks!

**Pull request merged**
