### PR TITLE
A new p3p solver

### PR DESCRIPTION
**Pull request by tonyke1993**

### CODE REVIEW

**Comment by alalek** [comment]
- This code is not used anywhere in OpenCV.
- Tests are required.
- There are existed P3P functionality. What is the difference? (article/measured performance)

**Comment by tonyke1993** [comment]
- This code is not used anywhere in OpenCV.
  Can P3P be an independent module, or it should be included in other modules like PnP?

- Tests are required.
  Sure. I can add tests.

- There are existed P3P functionality. What is the difference? (article/measured performance)
  The performance is better than the existed P3P. I have some tests for comparing their performance, how should I show them?

**Comment by alalek** [comment]
It will be great to have some details about performance/accuracy on real test cases (for example, it may be a part of some article or technical report). Also it will be great to compare with existed P3P OpenCV functionality.

BTW, In general, new modules/functionality which is not highly integrated into the main OpenCV code should go into [opencv_contrib repository](https://github.com/opencv/opencv_contrib).

**Comment by tonyke1993** [comment]
May I ask if this report can stay confidential?

**Pull request closed without merging**
