### PR TITLE
Utilize CV_UNUSED macro

### PR DESCRIPTION
**Pull request by cv3d**
Preferably merge with opencv/opencv_contrib#1756

Minor change for coding style unification

### This pullrequest changes
- Utilized `CV_UNUSED(x);` instead of `(void)x;`

### CODE REVIEW

**Comment by alalek** [comment]
Do not rebase this patch onto 3.4 (there are some conflicts).
I will prepare separate back-porting patch into 3.4 patch.

**Comment by cv3d** [comment]
I already rebased 😖 , but I guess there is no harm.

**Comment by alalek** [comment]
> modules/dnn/misc/caffe/opencv-caffe.pb.cc

Please revert changes in these files (`.pb.cc`). They are auto-generated by propobuf compiler. Extra diffs are not needed here.

**Comment by cv3d** [comment]
@alalek Done!

**Comment by cv3d** [comment]
@alalek I guess the milestone should be 3.4 instead

**Pull request merged**
