### PR TITLE
Allow a GMainLoop when capturing using GStreamer

### PR DESCRIPTION
**Pull request by michaelgruner**
A running GMainLoop processes many events on the GLib/GStreamer world. While some things may work without it, many others won't. Examples of these are signals, timers and many other source events. The problem becomes more concerning by the fact that some GStreamer elements rely on signals to work. This PR allows the user to specify an OpenCV option to start a main loop, if needed. Since the loop blocks, this is done in a separate thread.

I've documented the example that motivated to push this [in this wiki](https://developer.ridgerun.com/wiki/index.php?title=RidgeRun_OpenCV_Fork#GStreamer_Main_Loop).

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by michaelgruner** [comment]
Do you guys see value on absorbing this?

**Comment by alalek** [comment]
Please share some simple reproducer for this problem.

---

Opens:
- singleton for thread?
- `gst_bus_add_watch()`?
- also please take a look on `handleMessage(GstElement * pipeline)` implementation and its calls.

**Comment by AsyaPronina** [comment]
Hi @michaelgruner, could you please  point which category of GStreamer elements can't work without GMainLoop?

**Comment by asmorkalov** [comment]
@michaelgruner Friendly reminder.

**Review by alalek — APPROVED** [review]
Looks good to me. Thank you :+1:

**Pull request merged**
