### PR TITLE
Reformat USAC tutorial

### LINKED ISSUE #23404: extra `\` in usac.markdown
### Descripe the doc issue

There appears to be extra slashes (`\`) in [usac.markdown](https://github.com/opencv/opencv/blob/4.x/doc/tutorials/calib3d/usac.markdown?plain=1#LL200-LL201) as we can see in the [documentation](https://docs.opencv.org/4.x/d0/d74/md__build_4_x-contrib_docs-lin64_opencv_doc_tutorials_calib3d_usac.html) (search for `\ \`).

### Fix suggestion

It seems like those slashes should be removed.

Also, older versions of that [tutorial](https://docs.opencv.org/4.x/d0/d74/md__build_4_x-contrib_docs-lin64_opencv_doc_tutorials_calib3d_usac.html) seem to be broken; i.e., I cannot change the version in the dropdown at the top of the page, e.g., to 4.6.0

Finally, should this tutorial be listed in the [Table of Contents](https://github.com/opencv/opencv/blob/4.x/doc/tutorials/calib3d/table_of_content_calib3d.markdown)?

### PR DESCRIPTION
**Pull request by ivashmak**
Fixes #23404

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

```
force_builders_only=docs
```

### CODE REVIEW

**Comment by asmorkalov** [comment]
General recommendations:
- Please merge bib file to doc/opencv.bib and update references. They will be links.
- Please replace "`NEIGH_FLANN_KNN`" with just  "NEIGH_FLANN_KNN". Doxygen recognizes function names, class names  and constants and adds corss-references automatically.

**Review by asmorkalov — APPROVED** [review]
:+1:

**Comment by asmorkalov** [comment]
@opencv-alalek Could you help to resove documentation build warning. I cannot reproduce the issue locally.

**Comment by opencv-alalek** [comment]
Problem is visible in GHA environment too: https://github.com/opencv/opencv/actions/runs/6763833637/job/18430285450?pr=24465#step:18:365

We could see the raised problem in GHA more clearly if builder doesn't eat errors (many GHA builders have that problem)

**Pull request merged**
