### PR TITLE
Fix some C++ compiler warnings

### PR DESCRIPTION
**Pull request by eecsninja**
### This pullrequest changes

- Replace {!"string"} with {false && "string"}
- Replace case statement fallthroughs with break statements

### CODE REVIEW

**Comment by alalek** [comment]
1.
What are compiler / version / flags used to catch these warnings?

2.
This patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into 3.4 branch. So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).

We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

**Comment by eecsninja** [comment]
> What are compiler / version / flags used to catch these warnings?

gcc 7.3.0 with flag -Wimplicit-fallthrough

**Comment by eecsninja** [comment]
The build failed because of a CMake version check:

> CMake Error at CMakeLists.txt:29 (cmake_minimum_required):
>  CMake 3.5.1 or higher is required.  You are running version 2.8.12.2

http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/15542/steps/cmake/logs/stdio

**Comment by alalek** [comment]
This is because you need to rebase your commits into proper branch - see my first comment for details.

**Comment by eecsninja** [comment]
I will create a new pull request then.

**Pull request closed without merging**
