### PR TITLE
CUDA9 build fixed, added detection

### PR DESCRIPTION
**Pull request by borisfom**
### This pullrequest changes
CUDA cmake build setup extended to handle CUDA9
fp16 code changed to accommodate CUDA9 API-breaking changes

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for contribution! Looks good to me :+1:

**Comment by zwolenik** [comment]
Hi guys, 
I try to compile sources with latest version from git using CUDA9. My process of build stops on error bellow:

[94/1185] cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_dll --intdir=modules\cudev\CMakeFiles\opencv_cudev.dir --manifests  -- C:\PROGRA~2\MICROS~3\2017\ENTERP~1\VC\Tools\MSVC\1411~1.255\bin\HostX86\x64\link.exe /nologo modules\cudev\CMakeFiles\opencv_cudev.dir\src\stub.cpp.obj modules\cudev\CMakeFiles\opencv_cudev.dir\vs_version.rc.res  /out:bin\opencv_cudev330d.dll /implib:lib\opencv_cudev330d.lib /pdb:bin\opencv_cudev330d.pdb /dll /version:3.3 /machine:x64 /debug /INCREMENTAL /NODEFAULTLIB:libc /DEBUG -LIBPATH:C:\PROGRA~1\NVIDIA~2\CUDA\v9.0\lib\x64 3rdparty\lib\ippiwd.lib 3rdparty\ippicv\ippicv_win\lib\intel64\ippicvmt.lib cudart.lib nppc.lib nppial.lib nppicc.lib nppicom.lib nppidei.lib nppif.lib nppig.lib nppim.lib nppist.lib nppisu.lib nppitc.lib npps.lib cufft.lib -LIBPATH:"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64" cudart.lib nppc.lib nppial.lib nppicc.lib nppicom.lib nppidei.lib nppif.lib nppig.lib nppim.lib nppist.lib nppisu.lib nppitc.lib npps.lib cufft.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
     Creating library lib\opencv_cudev330d.lib and object lib\opencv_cudev330d.exp
  
  [95/1185] cmd.exe /C "cd /D C:\Users\zwolenik\CMakeBuilds\0a3f2040-a587-0f3e-af48-065e0c313449\build\x64-Debug\modules\core\CMakeFiles\cuda_compile.dir\src\cuda && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe" -E make_directory C:/Users/zwolenik/CMakeBuilds/0a3f2040-a587-0f3e-af48-065e0c313449/build/x64-Debug/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/. && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe" -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=C:/Users/zwolenik/CMakeBuilds/0a3f2040-a587-0f3e-af48-065e0c313449/build/x64-Debug/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.obj -D generated_cubin_file:STRING=C:/Users/zwolenik/CMakeBuilds/0a3f2040-a587-0f3e-af48-065e0c313449/build/x64-Debug/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.obj.cubin.txt -P C:/Users/zwolenik/CMakeBuilds/0a3f2040-a587-0f3e-af48-065e0c313449/build/x64-Debug/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.obj.cmake"
  FAILED: modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.obj 
  cmd.exe /C "cd /D C:\Users\zwolenik\CMakeBuilds\0a3f2040-a587-0f3e-af48-065e0c313449\build\x64-Debug\modules\core\CMakeFiles\cuda_compile.dir\src\cuda && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe" -E make_directory C:/Users/zwolenik/CMakeBuilds/0a3f2040-a587-0f3e-af48-065e0c313449/build/x64-Debug/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/. && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe" -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=C:/Users/zwolenik/CMakeBuilds/0a3f2040-a587-0f3e-af48-065e0c313449/build/x64-Debug/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.obj -D generated_cubin_file:STRING=C:/Users/zwolenik/CMakeBuilds/0a3f2040-a587-0f3e-af48-065e0c313449/build/x64-Debug/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.obj.cubin.txt -P C:/Users/zwolenik/CMakeBuilds/0a3f2040-a587-0f3e-af48-065e0c313449/build/x64-Debug/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.obj.cmake"
  nvcc fatal   : Unsupported gpu architecture 'compute_20'
  
  CMake Error at cuda_compile_generated_gpu_mat.cu.obj.cmake:206 (message):
    Error generating
    C:/Users/zwolenik/CMakeBuilds/0a3f2040-a587-0f3e-af48-065e0c313449/build/x64-Debug/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.obj

Maybe you can help me what I'm doing wrong. Or maybe provide more information. I started to  be familiar with environement - sorry for question but I stuck on this steps and I dont know how to diagnose or push this forward.

Slawek

**Comment by alalek** [comment]
> nvcc fatal : Unsupported gpu architecture 'compute_20'

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by borisfom** [comment]
Actually, this is about OpenCV detecting correct flags for CUDA - @zwolenik are yuo sure you pull the lasted and do a clean build? After my changes, compute_20 should not be included.

**Comment by zwolenik** [comment]
Thanks for you answer,
Yes, I'm pretty sure that I pull clear OpenCV code. Once I did fetch later
changes including your ... second pull latest clean repository. Few times
doing clean build trying to get more detail and understand what is exactly
reasons.
No success:(

Slawek

28.08.2017 22:25 "Boris Fomitchev" <notifications@github.com> napisał(a):

**Comment by alalek** [comment]
Could you try this fix: #9465 ?

**Comment by borisfom** [comment]
Oh I think I know what it is  - auto detection - is your GPU arch CUDA 2.0 ?

**Comment by zwolenik** [comment]
After spending some time I cannot get to this kind of details level. How to manage this and get info? This can be autodetection bug or I need to turn off something on building process?

**Comment by borisfom** [comment]
@zwolenik : I mean, if you have GPU card that is Kepler (2.x CUDA arch) - its not supported  by CUDA9. You can still build on that machine if you override flags, but you can't build 2.x code with CUDA9.

**Comment by pstieber** [comment]
@borisfom It looks like the inclusion of `opencv2/core/private.cuda.hpp` in `saturate_cast.hpp` may be a mistake, because the later file is installed and should not refer to a private include.

**Pull request merged**
