### PR TITLE
Add support for ONNX "ReduceMean" Layer

### PR DESCRIPTION
**Pull request by Aeroxander**
resolves https://github.com/opencv/opencv/issues/14768

### This pull request changes

Support for the ONNX ReduceMean Layer.

### CODE REVIEW

**Comment by dkurt** [comment]
@Aeroxander, Can you please add some test for it? You may check https://github.com/opencv/opencv/pull/14697 with https://github.com/opencv/opencv_extra/pull/615/files for reference.

Please also replace base branch to 3.4

**Comment by alalek** [comment]
> Merge branch 'master' of https://github.com/opencv/opencv

Please avoid "merge" commits from the patch. Use git rebasing on the top of target branch instead.
Merge commits over-complicates patch, make review complex and may break GitHub reviewing tool.

They may break rebasing onto a current [maintenance branch - "3.4"](https://github.com/opencv/opencv/wiki/Branches).

**Comment by Aeroxander** [comment]
Got it, will solve both issues as soon as I can, it might take a while cause I'm in a hurry of also adding other missing layers.

**Comment by dkurt** [comment]
We merged this PR as a part of https://github.com/opencv/opencv/pull/15032. Thanks!

**Pull request closed without merging**
