### PR TITLE
Decrease min box size in icvGetQuadrangleHypotheses

### PR DESCRIPTION
**Pull request by MaximSmolskiy**
### Pull Request Readiness Checklist

In chessboard (corners) finding algorithm we have variable `min_area = 25` (https://github.com/MaximSmolskiy/opencv/blob/4.x/modules/calib3d/src/calibinit.cpp#L1734), which corresponds to `min_size = 5`.  But in fast check similar variable have greater value.

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
```
../shared/baboon.png: chessboard 0:
Error: chessboard was detected in the image ../shared/baboon.png
```
The patch adds false-positive detection.

**Comment by MaximSmolskiy** [comment]
> ```
> ../shared/baboon.png: chessboard 0:
> Error: chessboard was detected in the image ../shared/baboon.png
> ```
> 
> The patch adds false-positive detection.

@asmorkalov But current fast check isn't able to detect chessboards with quite small cell sizes, but following main detection algorithm is able.

I tested these changes with benchmark:
changed line https://github.com/opencv/opencv_benchmarks/blob/develop/python_benchmarks/objdetect_benchmark/objdetect_benchmark.py#L648 from
```
ret, corners = cv.findChessboardCorners(gray, synthetic_chessboard.pattern_size, criteria)
```
to
```
ret, corners = cv.findChessboardCorners(gray, synthetic_chessboard.pattern_size, criteria, cv.CALIB_CB_ADAPTIVE_THRESH + cv.CALIB_CB_NORMALIZE_IMAGE + cv.CALIB_CB_FAST_CHECK)
```
ran
```
python3 objdetect_benchmark.py --configuration=generate_run --board_x=7 --path=res_chessboard --synthetic_object=chessboard --cell_img_size 10
```
and got following results:
these changes drastically improve chessboards detection with quite small cell sizes with enabled fast check

before
```
                                 category  detected chessboard  total detected chessboard  total chessboard  average detected error chessboard
                          _none_none_blur             0.000000                          0               360                                NaN
                    _none_none_gaussNoise             0.000000                          0               360                                NaN
                          _none_none_none             0.000000                          0               360                                NaN
                    _none_none_strongBlur             0.000000                          0               360                                NaN
                   _none_undistorted_blur             0.000000                          0               360                                NaN
             _none_undistorted_gaussNoise             0.497222                        179               360                           5.059457
                   _none_undistorted_none             0.000000                          0               360                                NaN
             _none_undistorted_strongBlur             0.000000                          0               360                                NaN
                   _perspective_none_blur             0.000000                          0              1080                                NaN
             _perspective_none_gaussNoise             0.000000                          0              1080                                NaN
                   _perspective_none_none             0.000000                          0              1080                                NaN
             _perspective_none_strongBlur             0.000000                          0              1080                                NaN
            _perspective_undistorted_blur             0.000000                          0              1080                                NaN
      _perspective_undistorted_gaussNoise             0.000000                          0              1080                                NaN
            _perspective_undistorted_none             0.000000                          0              1080                                NaN
      _perspective_undistorted_strongBlur             0.000000                          0              1080                                NaN
             _strongPerspective_none_blur             0.000000                          0               360                                NaN
       _strongPerspective_none_gaussNoise             0.000000                          0               360                                NaN
             _strongPerspective_none_none             0.000000                          0               360                                NaN
       _strongPerspective_none_strongBlur             0.000000                          0               360                                NaN
      _strongPerspective_undistorted_blur             0.000000                          0               360                                NaN
_strongPerspective_undistorted_gaussNoise             0.000000                          0               360                                NaN
      _strongPerspective_undistorted_none             0.000000                          0               360                                NaN
_strongPerspective_undistorted_strongBlur             0.000000                          0               360                                NaN
                                      all             0.012431                        179             14400                           5.059457
Total detected time:  0.8411489999999998 sec
Total benchmark time: 14.532698631286621 sec
```

after
```
                                 category  detected chessboard  total detected chessboard  total chessboard  average detected error chessboard
                          _none_none_blur             0.991667                        357               360                           4.905091
                    _none_none_gaussNoise             0.750000                        270               360                           5.215633
                          _none_none_none             1.000000                        360               360                           4.943304
                    _none_none_strongBlur             0.916667                        330               360                           3.806217
                   _none_undistorted_blur             0.994444                        358               360                           5.220915
             _none_undistorted_gaussNoise             0.997222                        359               360                           4.542443
                   _none_undistorted_none             0.997222                        359               360                           4.340208
             _none_undistorted_strongBlur             0.161111                         58               360                           5.024331
                   _perspective_none_blur             0.629630                        680              1080                           4.825401
             _perspective_none_gaussNoise             0.966667                       1044              1080                           3.895425
                   _perspective_none_none             0.971296                       1049              1080                           3.920378
             _perspective_none_strongBlur             0.000000                          0              1080                                NaN
            _perspective_undistorted_blur             0.555556                        600              1080                           4.650435
      _perspective_undistorted_gaussNoise             0.999074                       1079              1080                           3.553195
            _perspective_undistorted_none             0.750000                        810              1080                           3.604110
      _perspective_undistorted_strongBlur             0.000000                          0              1080                                NaN
             _strongPerspective_none_blur             0.000000                          0               360                                NaN
       _strongPerspective_none_gaussNoise             0.000000                          0               360                                NaN
             _strongPerspective_none_none             0.000000                          0               360                                NaN
       _strongPerspective_none_strongBlur             0.000000                          0               360                                NaN
      _strongPerspective_undistorted_blur             0.000000                          0               360                                NaN
_strongPerspective_undistorted_gaussNoise             0.000000                          0               360                                NaN
      _strongPerspective_undistorted_none             0.000000                          0               360                                NaN
_strongPerspective_undistorted_strongBlur             0.000000                          0               360                                NaN
                                      all             0.535625                       7713             14400                           4.219942
Total detected time:  2.2138009999999992 sec
Total benchmark time: 17.869497299194336 sec
```

**Comment by asmorkalov** [comment]
@MaximSmolskiy Is the patch still relevant?

**Comment by MaximSmolskiy** [comment]
@asmorkalov Yes. I got following results on some private dataset:
1) with enabled fast check and before (without these changes): `160` detected chessboards
2) with enabled fast check and after (with these changes): `240` detected chessboards
3) with disabled fast check: `280` detected chessboards

So, these changes significantly improve detection of chessboards with quite small cell sizes.

**Comment by MaximSmolskiy** [comment]
> @asmorkalov Yes. I got following results on some private dataset:
> 
> 1. with enabled fast check and before (without these changes): `160` detected chessboards
> 2. with enabled fast check and after (with these changes): `240` detected chessboards
> 3. with disabled fast check: `280` detected chessboards
> 
> So, these changes significantly improve detection of chessboards with quite small cell sizes.

@asmorkalov gentle ping

**Comment by asmorkalov** [comment]
There are test failures on CI.

**Pull request closed without merging**
