### PR TITLE
fixing bug in  py_calibration.markdown

### PR DESCRIPTION
**Pull request by phunsukwangdu**
Resolves  cv2.cornerSubPix() and assign it to a variable and use this variable in other function call

### What does this PR change?
In the camera calibration code { cv2.cornerSubPix() } will be of no use.In the updated code it is assigned to the (corners2) variable 
which is passed down to { cv2.drawChessboardCorners() }

### CODE REVIEW

**Comment by vpisarev** [comment]
this PR will be reopened because of CI issues

**Comment by phunsukwangdu** [comment]
Hi Vadim Pisarevsky!

I am interested in contributing  to Opencv.
I sent some Pr but were closed.I have written couple of code in opencv.

I have realised that opencv 3.1 does not have python opencv tutorials.
Opencv 3.0.0 does have python opencv tutorials but most of its code is not
compatible in opencv 3.1.
I would be happy to make it compatible and add extra to it.I have already
pioneered machine learning  and written a neural network library of my own
in python.

thx for anticipation.

**Comment by alalek** [comment]
@phunsukwangdu Hi! Don't worry, your patch is merged into master branch via cloned PR #6816 (there were some issues with PRs).

**Comment by phunsukwangdu** [comment]
Hi Alexander

I am very interested to write and update python tutorials for Opencv 3.1.

**Pull request closed without merging**
