### PR TITLE
support four channels in cv::findChessboardCorners

### PR DESCRIPTION
**Pull request by csukuangfj**
### This pullrequest changes
The original implementation missed the 4-channel case. This pullrequest fixes it.

### CODE REVIEW

**Comment by alalek** [comment]
Do you have a test for this?

`COLOR_BGR2GRAY` has a trick to use `COLOR_BGRA2GRAY in case of 4 ch input (added for these cases).

**Comment by vpisarev** [comment]
thanks you! indeed, looks like this patch is unecessary; cvtColor is smart enough to process 4-channel images as well in COLOR_BGR2GRAY mode

**Comment by alalek** [comment]
@csukuangfj Almost right! But need to update this statement (line 581) with `.clone()` removal:
```
equalizeHist(img, img);
```

**Comment by alalek** [comment]
BTW, GitHub doesn't allow to reopen this PR (because source branch has been changed during PR is closed).
Please open a new PR.

**Comment by csukuangfj** [comment]
@alalek 
do you mean to add `img = img.clone()` just before this statement?

**Comment by alalek** [comment]
> img = img.clone();
> img.clone();

I miss that :+1:

`img = img.clone()` just before `equalizeHist()` should work fine.

**Comment by csukuangfj** [comment]
Underflow for `unsigned`
https://github.com/opencv/opencv/blob/5e31c82b5b71efdd4e9e119e73765d4a2b50457b/modules/core/include/opencv2/core/types.hpp#L1947-L1948

https://github.com/opencv/opencv/blob/5e31c82b5b71efdd4e9e119e73765d4a2b50457b/modules/core/include/opencv2/core/types.hpp#L1951

I think it is a bug.

**Pull request closed without merging**
