### PR TITLE
python: bindings loader package

### PR DESCRIPTION
**Pull request by alalek**
Configures and loads OpenCV bindings extension including 3rdparty dependencies

Based on running Python specify:
- configure PYTHONPATH (via "sys.path")
- configure PATH / LD_LIBRARY_PATH (changes doesn't work in the same process)

TODO:
- [ ] RPATH support from standalone Python builds (via CMAKE_INSTALL_RPATH ?)

```
test_modules=python2,python3
```

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by hmaarrfk** [comment]
@alalek it seems that this is a new file that changes how we are supposed to import and/or install opencv for use with python. 

Do you have some docs that explain the new install flags/macros?

xref: https://github.com/conda-forge/opencv-feedstock/pull/132

**Comment by alalek** [comment]
@hmaarrfk Yes, default behavior has been changed.

Old behavior can restored via these CMake variables:
- `OPENCV_SKIP_PYTHON_LOADER=ON`
- `OPENCV_PYTHON3_INSTALL_PATH=...site/dist-packages location...`

**Comment by hmaarrfk** [comment]
Thanks that did the trick!

**Pull request merged**
