### PR TITLE
Fixed support of mean/scale preprocessing in OV backend for non-real types

### PR DESCRIPTION
**Pull request by AsyaPronina**
### Merge with extra: https://github.com/opencv/opencv_extra/pull/1139

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [X] The PR is proposed to the proper branch
- [X] There is a reference to the original bug report and related work
- [X] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [X] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@dmatveev @TolyaTalamanov please take a look.

**Review by dmatveev — COMMENTED** [review]
Looks ok for me but is there a way to test it somehow?

Also, final approver is @TolyaTalamanov as the code owner of this backend

**Comment by AsyaPronina** [comment]
> Looks ok for me but is there a way to test it somehow?
> 
> Also, final approver is @TolyaTalamanov as the code owner of this backend

Hello Dear Dmitry! Test was added!

**Comment by dmatveev** [comment]
@AsyaPronina can you please check if this test is executed in the OpenCV CI?

**Comment by AsyaPronina** [comment]
> @AsyaPronina can you please check if this test is executed in the OpenCV CI?

Hello Dear Dmitry (@dmatveev), unfortunately, I can't find these tests in build logs. It seems that they are not executed.

**Review by TolyaTalamanov — APPROVED** [review]

**Comment by asmorkalov** [comment]
@dmatveev Could you take a look?

**Review by dmatveev — APPROVED** [review]
👍

**Pull request merged**
