### PR TITLE
Improve MultibandBlender cuda

### PR DESCRIPTION
**Pull request by hewj03**
### This pullrequest changes

Improve MultibandBlender by moving more work to cuda and reducing the number of upload/download. An accuracy test is added.

### CODE REVIEW

**Comment by vpisarev** [comment]
unfortunately, we are not able to check it, so let's merge it as-is

**Comment by vpisarev** [comment]
:+1:

**Comment by mshabunin** [comment]
@hewj03 , there is an issue with the new code (reported in opencv/opencv_contrib#1012): 
```
Building CXX object modules/cudalegacy/CMakeFiles/opencv_test_cudalegacy.dir/test/TestDrawRects.cpp.o
/home/spu/Documents/github/opencv_dev/modules/stitching/src/cuda/multiband_blend.cu(93): error: Within a __device__/__global__ function, only __shared__ variables may be marked "static"

1 error detected in the compilation of "/tmp/tmpxft_00004d79_00000000-7_multiband_blend.cpp1.ii".
```
Could you please take a look?

**Comment by hewj03** [comment]
@mshabunin i will check

**Pull request merged**
