### PR TITLE
fixing models to resolve XML violation issue

### LINKED ISSUE #8894: Some XML cascade file have comments which violate XML syntax
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => n/a
- Compiler => n/a

##### Detailed description
Several of the cascade.xml files (e.g. data/haarcascades/haarcascade_frontalcatface.xml)
contain improper XML comments in the header:

&lt;!--------------------------------
...
----------------------------------&gt;

This does not cause problems when reading the data using OpenCV, but other readers (e.g. Python ElementTree) will not read these files. This is easily fixed by changing the lines to &lt;!-- and --&gt;.

XML comments start with &lt;!-- and end with --&gt;
The text in between must be at least one character, may not end in a hyphen, and may not contain two consecutive hyphens.

See https://www.w3.org/TR/REC-xml/#sec-comments

[ Some informal references miss this detail -- e.g. https://www.tutorialspoint.com/xml/xml_comments.htm ; not only fails to mention this, actually gives examples which violate it. ]

### PR DESCRIPTION
**Pull request by StevenPuttemans**
resolves #8894
As suggested in issue #8894, this solves issues with XML style violation.

### CODE REVIEW

**Comment by alalek** [comment]
> - A 3rdparty/ippicv/downloads/linux-808b791a6eac9ed78d32a7666804320e/ippicv_linux_20151201.tgz (0)

Please remove this file from PR

**Comment by StevenPuttemans** [comment]
@alalek done! seems I accidently included it. The 3rdparty folder should be in the gitignore file :)

**Comment by alalek** [comment]
These files are moved into `.cache` folder in current master.
`3rdparty/ippicv/downloads/` was used in previous releases.

Current workaround is to create `.gitignore` file with "*" content in `3rdparty/ippicv/downloads/` directory.

**Comment by alalek** [comment]
Thanks! :+1:

**Pull request merged**
