### PR TITLE
fix API cv::dnn::net::getLayerInputs

### PR DESCRIPTION
**Pull request by Dimitri1**

### CODE REVIEW

**Comment by dkurt** [comment]
Hi! Thanks for the path.

Can you please provide incorrect case? In example, using [dumpToFile](https://docs.opencv.org/master/db/d30/classcv_1_1dnn_1_1Net.html#a4f7d0d1e650571e11d988d07f7ed5a7d).

**Comment by Dimitri1** [comment]
[mobilenetv2-1.0.onnx.openCV.dumpToFile.txt](https://github.com/opencv/opencv/files/3400671/mobilenetv2-1.0.onnx.openCV.dumpToFile.txt)

**Comment by dkurt** [comment]
@Dimitri1, Which layer is a problematic one?

**Comment by Dimitri1** [comment]
Hi, the issue is that getLayerInputs method returns 0 size vector (no input) on opencv master.
Maybe I missed a step of initialization or something, but my patch fix directly the issue.

**Here is my test sequence:**

// build net from .onnx
datas_->net_ = cv::dnn::readNetFromONNX(datas_->modelFilename_);
std::vector<cv::String> layerNames = datas_->net_.getLayerNames();
for (int il = 0; il < layerNames.size(); il++) {
		cv::String layerName = layerNames[il];
 		int        layerId   = datas_->net_.getLayerId(layerName);
		std::vector<cv::Ptr<cv::dnn::Layer>> layerInputs = datas_->net_.getLayerInputs(layerId);
}
Here **layerInputs** is empty with opencv master getLayerInputs !

**Comment by dkurt** [comment]
@Dimitri1, Please check the changes in this PR. can we review again initial version?

You may reopen it with new branch with different name from `master`.

**Comment by asmorkalov** [comment]
@Dimitri1 A loot of fixes has been merged to DNN module and merge conflict appears. Please re-base you branch and fix it.

**Comment by Dimitri1** [comment]
ignore this pull request

**Pull request closed without merging**
