### PR TITLE
Update createsamples app

### LINKED ISSUE #10267: createsamples: reproducible results
Currently there is no way to reproduce results of createsamples tool. Launching with the same parameters doesn't return the same results.

- This tool uses `srand((unsigned int)time(0));`. Need to add command-line option to specify seed with some fixed default (like 12345).
- This tool uses `rand()`. It is not a thread-safe call. Need to replace these calls on `cv::RNG` API.

### PR DESCRIPTION
**Pull request by sturkmen72**
resolves #10267

### This pullrequest changes
adds command-line option -rngseed
replaces rand() -> theRNG()

*WIP*

```
docker_image:Custom=ubuntu:17.10
```

### CODE REVIEW

**Comment by sturkmen72** [comment]
@alalek could you take a look at the code. i will test it later but let me know if i am on the right path.

**Comment by alalek** [comment]
@sturkmen72 It seems good! Thank you!

**Comment by sturkmen72** [comment]
@alalek please review it later. i am still working on it.

**Comment by sturkmen72** [comment]
@terfendail do you have time to check #10264 there is a problem when calling the program like below ( it runs good when the commit reverted )

`opencv_createsamples -img face.jpg -num 200 -vec positives.vec -w 88 -h 48`

 it generates vec file width and height swapped

`opencv_createsamples -img face.jpg -num 200 -vec positives.vec -w 148 -h 48`

raises error

`OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in cv::Mat::Mat, file E:\git\opencv\modules\core\src\matrix.cpp, line 538`

**Pull request merged**
