### PR TITLE
RISC-V: allow building scalable RVV support with GCC, LLVM 16 support

### PR DESCRIPTION
**Pull request by mshabunin**
Related issue #22608

* GCC does not support "overloaded RVV intrinsics", but we can add some of them in our code
* LLVM since version 16 uses `__riscv_<name>` naming scheme (see related ticket), so we need to add compatibility headers to rename our 0.10 intinsics to the new scheme (also for some "overloaded intrinsics")

TODO:
- [x] ~check and fix compilation with GCC~ still does not work due to toolchain issue or limitation
- [x] extract overloaded intsinsics implementation to separate header
- [x] ~macros for overloaded intrinsics looks too broad, maybe convert them to function macros / inline functions / undef?~ used headers from RISC-V collab as is
- [x] clean-up the code - reduce modifications

Note: scalable RVV compilation using GCC still does not work (T-Head 2.6.1 and RISC-V Collab Toolchain@_rvv_next_) due to compiler issues or limitations. More analysis needed.

<cut/>

```
force_builders=Custom
build_image:Custom=riscv-clang-rvv
Xbuild_image:Custom=riscv-clang-rvv-128
Xbuild_image:Custom=riscv-gcc-rvv-07
test_modules:Custom=core,imgproc,dnn
buildworker:Custom=linux-4
test_timeout:Custom=600
build_contrib:Custom=OFF
```

### CODE REVIEW

**Review by opencv-alalek — APPROVED** [review]
LGTM :+1:

**Comment by zhongjuzhe** [comment]
Can you use upstream GCC (GCC 13.0) test? We don't maintain rvv-next any more. All update upstream GCC directely.
https://github.com/gcc-mirror/gcc

**Comment by opencv-alalek** [comment]
@zhongjuzhe Thank you for the information!
Is there some example how to build RISC-V GCC toolchain from upstream source code? (similar to https://github.com/riscv-collab/riscv-gnu-toolchain instructions)
CI logs? Or Dockerfile?

**Comment by zhongjuzhe** [comment]
> 

It seems that RISC-V toolchain doesn't bump to latest upstream GCC. I think you can file an issue to @kito-cheng and ask him to update the toolchain.

Here is an simple example to verify that both GCC and LLVM are consisten each other with the same API doc:
https://godbolt.org/z/dz83ozbeb

compiler explorer has showed that both GCC and LLVM are recognizing same API RVV.

**Comment by mshabunin** [comment]
I've been able to build riscv-collab toolchain with the latest GCC by updating _gcc_ submodule to _master_ manually. It can build OpenCV with scalable RVV support, but failed to build non-scalable (`intrin_rvv.hpp`) variant. I'm going to take a closer look. @zhongjuzhe , thank you for guidance!

**Comment by zhongjuzhe** [comment]
Thank you for trying.
Feel free file a bug here: 
https://gcc.gnu.org/bugzilla/ 
if you see any compiler bug.

Thanks.


***@***.***
 
From: Maksim Shabunin
Date: 2023-04-17 18:21
To: opencv/opencv
CC: Ju-Zhe Zhong; Mention
Subject: Re: [opencv/opencv] RISC-V: allow building scalable RVV support with GCC, LLVM 16 support (PR #23383)
I've been able to build riscv-collab toolchain with the latest GCC by updating gcc submodule to master manually. It can build OpenCV with scalable RVV support, but failed to build non-scalable (intrin_rvv.hpp) variant. I'm going to take a closer look. @zhongjuzhe , thank you for guidance!

**Pull request merged**
