### PR TITLE
Object_Detection_API(NanoDet&YoloX)

### PR DESCRIPTION
**Pull request by Sidd1609**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

**PR: API for Light-weight object Detection using Nanodet and YoloX**
Tasks To be Done:

- [x] Image data pre-processing 
- [x] Model Inference modules 
- [ ] Inference post-processing module 
- [ ] Integration of modules 
- [ ] Test results with sample input images

### CODE REVIEW

**Comment by asmorkalov** [comment]
objdetect as other OpenCV modules is a library, `main` is not allowed there.

**Comment by fengyuentau** [comment]
@asmorkalov The contributor contributed object detection models to opencv_zoo and I invited him to contribute C++ APIs for the models in the objdetect module. He is a first-time contributor to C++ library and still learning new things.

**Comment by fengyuentau** [comment]
Hello @Sidd1609 , any updates on this pull request?

**Comment by Sidd1609** [comment]
Yes, planning on pushing some updates in this weekend.

**Comment by Sidd1609** [comment]
@fengyuentau for executing the .cpp file of objectdetect like facedetect could we build only the dependencies of the dnn module. I am facing issues in building opencv with CMake.

**Comment by fengyuentau** [comment]
```
git clone https://github.com/Sidd1609/opencv_GSOC-22

# you need to fork opencv_extra as well.
# any test data should go to opencv_extra/testdata/dnn.
# some big models need to be downloaded using opencv_extra/testdata/dnn/download_models.py
git clone https://github.com/Sidd1609/opencv_extra

cd opencv_GSOC-22
git checkout ObjDetectionAPI

# I suggest installing the latest CMake
cmake -B build .
# following command builds the test program and its dependency only
cmake --build build --target opencv_test_objdetect -j 4

# set environment for the program to find test data
export OPENCV_TEST_DATA_PATH=/path/to/your/opencv_extra/testdata
export OPENCV_DNN_TEST_DATA_PATH=/path/to/your/opencv_extra/testdata

# run tests
./build/bin/opencv_test_objdetect
# run tests with filter
./build/bin/opencv_test_objdetect --gtest_filter="Objdetect_face_detection.regression"
```

**Comment by fengyuentau** [comment]
By the way, opencv_contrib is not needed in this pull request. Leave comments in this pull request for discussion.

**Comment by Sidd1609** [comment]
So, while building opencv with cmake the opencv_extra folder path needs to
be mentioned here?
[image: image.png]

**Comment by fengyuentau** [comment]
@Sidd1609 Do you plan to continue this pull request? I got some other students who are interested in this and they want to continue your work.

**Comment by Sidd1609** [comment]
Yes yuantao, I plan on contributing to it, but if I could work with someone
it would be great.

**Comment by Sidd1609** [comment]
Need an extra hand.

**Comment by fengyuentau** [comment]
I mean it will be another pull request created by some other students. Based on your recent activity on this pull request, I do not think you have time on working with someone on this pull request.

**Comment by Sidd1609** [comment]
Hi yuantao, I have pushed the code for object_detect.cpp based on previous interaction, will need to test the script by building cv on my system for cpp will get this done ASAP.

**Pull request closed without merging**
