### PR TITLE
Improved chessboard detection

### PR DESCRIPTION
**Pull request by HHI-VIT-IMC**
Modified and improved the method for chessboard detection. It is now faster and detects chessboards under difficult lighting condition as well as when the chessboard has strong out of plane rotations

### CODE REVIEW

**Comment by vpisarev** [comment]
@HHI-VIT-IMC, thank you for the contribution!

We can not accept it as-is though. As I see, the modified version first runs your algorithm and in the case of failure it runs the original one. It means that:
1) when the board is there, it can be overall gain in performance or loss, depending on the percentage of the boards that your algorithm detects.
2) when the board is not there, the new algorithm will definitely be slower. And actually surprisingly many people use chessboard patterns not for calibration, but for augmented reality or pose recovery in general (e.g. WG used it to detect robot's arm pose).

So,
1) in any case some performance analysis is needed.
2) it should probably be an option to findChessboardCorners (disabled by default) that activates your branch.
3) what actually happens if we retain just your branch? will your algorithm detect all the boards from OpenCV test datasets?

**Comment by HHI-VIT-IMC** [comment]
Dear Vadim Pisarevsky,

thank you very much for the review of our submission. We fully agree that a performance analysis is necessary to have convincing reasons for acception of this contribution.
We performed an evaluation on the OpenCV test data set, which in our mind is not a very challenging set of images. Our approach successfully detect the chessboards in these images. Beyond this, we performed the evaluation on another set of test images (154 samples) with much more difficult lighting conditions. The performance evaluation has been run using the original algorithm and our new approach on both test sets. We analysed successfull detection and run time on a standard PC (Windows 7, 3.5GHz, 12 core CPU). 
The new approach performs significantly better also in bad illumination conditions and it is on average 10 times faster than the original approach. 

On the following link
https://datacloud.hhi.fraunhofer.de/owncloud/public.php?service=files&t=60469dc859451bddaf37b3a97bea1c20
you can download the challenging set of test images as well as an excel sheet with the performance figures.

Regarding point 2) we introduced another parameter which allows to enable the histogram based analysis. We fully agree with your suggestion.

Regarding point 3), there will be some rare cases where the histogram based analysis fails. This mainly happens if there is a grey scale among the white background of the pattern. Sometimes the original approach can still find a working threshold, but this is a very rare case. Therefore, we suggest to keep the original method as well as a kind of fall back solution. In the case of successfull detection with our approach, the original method is not used.

In the latest commit on github, we added the additional parameter and some more detailed references to the originators of the algorithm. 

We are very much interested on your feedback. 

Best regards,
    Oliver Schreer & Stefano Masneri

**Comment by vpisarev** [comment]
Oliver, Stefano,

thank you! this is very comprehensive study!
and, btw, my congratulations, your "standard PC" characteristics (12 cores, 3.5GHz) sound pretty neat :)

As far as I can see from the table, in some cases (when the current OpenCV algorithm detects the board successfully) your algorithm is ~3x slower, but still reasonably fast. In other cases OpenCV spends several hundred milliseconds and then fails to detect the board. Your algorithm spends 10x less time and finds the board successfully.

So, when the board is there, your approach is clearly superior!

Now, let's consider the negative case more carefully. Do you have any numbers of how much your algorithm spends in this case? If it at least not much slower than the current one, I'd suggest a different route:

your proposal:
<pre>
found = false;
if( cvCheckChessboardBinary(image, board_size) )
{
     found = cvFindChessboardCorners(image, ...);
}
</pre>
in this scenario we may save some time when the board is not there, but in the positive case cvCheckChessboardBinary() time will be added to cvFindChessboardCorners(). If I understand correctly, it practically means that the processing time will be doubled.

my proposal:
#define CV_CALIB_CB_USE_HIST 32 /* or some other descriptive name */

1)
// use your algorithm (not in addition, but instead of OpenCV). If your algorithm does not find a board, return immediately, do not fallback to the previous algorithm.
found = cvFindChessboardCorners(image, ...., flags | CV_CALIB_CB_USE_HIST);

2) // for critical applications when we do not care about the processing time much (e.g. offline calibration)
found = cvFindChessboardCorners(image, ...., flags | CV_CALIB_CB_USE_HIST)
if( !found )
{
    // fallback to previous algorithm manually.
     found = cvFindChessboardCorners(image, ...., flags);
}

what do you think?

**Comment by HHI-VIT-IMC** [comment]
Dear Vadim,

Many thanks again for the detailed feedback. First of all in our latest commit last week, we already introduced a flag for the new histogram based analysis.

We are not sure if it is the right approach to let the user decide about the algorithm. The point is that your arguments hold perhaps for the few openVC test images. However, the old version fails in many other cases even in extreme and unpleasant lighting conditions. Hence, perhaps the old version will be faster in very few cases but it will miss many chessboards.

Therefore we suggested to combine both approaches.

1.      Run the fast histogram based analysis.
If a chessboard is detected then it is fast anyhow and faster than the old approach.

2.      If the chessboard is not detected, then try the simple approach to calculate the threshold.

As mentioned in my last email, especially in cases with a grey scale along the white part of the pattern, our new method might fail. Hence the old version is still a backup solution to make the detection more robust also against these cases.
Overall, the chessboard detection will be anyhow faster on average in our opinion.

Best regards,
               Oliver

**Comment by vpisarev** [comment]
@HHI-VIT-IMC,

Dear Oliver,
somehow, I did not post my reply. In 2.4 branch, which is now in maintenance mode, I would prefer to play safe and retain the original algorithm as the default option and, if you like, use your algorithm when user explicitly specifies the flag. In the master branch I would be happy to implement your proposal.

Regards,
Vadim

**Comment by HHI-VIT-IMC** [comment]
Dear Vadim,

Thanks again for the feedback.
We are more than happy with your proposal (and honestly said, very much satisfied that our new approach ends up in the next OpenCV master branch).
Please go ahead as you suggested.

Best regards,
               Oliver

**Comment by mshabunin** [comment]
Transferred to new PR

**Comment by javierBarandiaran** [comment]
Hi,
At this line of cvFindChessboardCorners,
`dilate( thresh_img_new, thresh_img_new, Mat(), Point(-1, -1), 1 );`
in the second iteration, the input image is the resultant image of findContours used in icvGenerateQuads. Is this intended? Should not it be the previously dilated image? I am not sure if the result is the same.
If it is intended, may be the previous comment could be clarified
`//USE BINARY IMAGE COMPUTED USING icvBinarizationHistogramBased METHOD`
Regards,
Javier

**Comment by mshabunin** [comment]
@javierBarandiaran , it can be a problem. Can you provide an  image which fails check due to this behavior?

**Comment by javierBarandiaran** [comment]
I didn't found any. I have tested some complicated images and always obtained the same result. I suppose that the code correct.

**Pull request closed without merging**
