### PR TITLE
dnn: cleanup of tengine backend

### PR DESCRIPTION
**Pull request by fengyuentau**
🚀 Cleanup for OpenCV 5.0. Tengine backend is added for convolution layer speedup on ARM CPUs, but it is not maintained and the convolution layer on our default backend has reached similar performance to that of Tengine.

Tengine backend related PRs:
- https://github.com/opencv/opencv/pull/16724
- https://github.com/opencv/opencv/pull/18323

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by dkurt** [comment]
Can you please add a motivation into the PR description why Tengine going to be removed (not maintained or there are more efficient alternatives)?

**Comment by fengyuentau** [comment]
The decision (and also the cleanup of Halide backend) was made in the internal meeting. We have already reached similar performance of convolution layers against Tengine.

**Comment by dkurt** [comment]
@fengyuentau, I don't see any obstacles, this is just for commit history which includes complete message from PR description only.

**Comment by fengyuentau** [comment]
> this is just for commit history which includes complete message from PR description only.

Ok

**Review by dkurt — APPROVED** [review]

**Review by asmorkalov — APPROVED** [review]
:+1:

**Pull request merged**
