### PR TITLE
Fixed load error

### LINKED ISSUE #7223: samples/android/face-detection "Failed to load cascade classifier"
- OpenCV => 3.1
- Operating System / Platform => OpenCV-3.1.0-android-sdk
##### Detailed description

When running the samples/android/face-detection sample from the OpenCV-3.1.0-android-sdk, the Java based face recognition code doesn't detect any faces, but switching to native mode detects faces as expected.

After some investigation and trial and error, I found that adding just a single line to the sample makes it work.
##### Steps to reproduce
1. Run the OpenCV-android-sdk/samples/face-detection
2. Logcat will display the message "Failed to load cascade classifier"
3. Faces will not be detected
4. In FdActivity Add after `mJavaDetector = new CascadeClassifier(mCascadeFile.getAbsolutePath());`: `mJavaDetector.load(mCascadeFile.getAbsolutePath())`
5. Running the sample again will detect faces correctly
   
   ``` .java
                       mJavaDetector = new CascadeClassifier(mCascadeFile.getAbsolutePath());
                       mJavaDetector.load(mCascadeFile.getAbsolutePath());
                       if (mJavaDetector.empty()) {
   ```

### PR DESCRIPTION
**Pull request by souch55**
resolves #7223

### CODE REVIEW

**Comment by alalek** [comment]
There is problem in Java bindings implementation. I believe, introducing workarounds via samples is a not a good idea.

**Comment by souch55** [comment]
Hi  alalek we need to improve java bindings implementation,i agree but this if any work around corrects the existing issues even in samples and example level we can adapt it.

**Comment by vpisarev** [comment]
let's put it in for now and fix java bindings later :+1:

**Comment by alalek** [comment]
I can't confirm original issue, both Java and Native code paths works fine in 3.2 without additional patches.
Double initialization of cascade classifier doesn't look like normal processing too.

**Pull request closed without merging**
