### PR TITLE
imgproc: use universal intrinsic in threshold

### PR DESCRIPTION
**Pull request by tomoaki0705**
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/315

### This pullrequest changes
  * use universal intrinsic in threshold function
  * add performance test for 32F and 64F threshold

I'll add performance test result later

### CODE REVIEW

**Comment by tomoaki0705** [comment]
### PINE 64 Ubuntu 16.04 64bit  GCC 5.4 (ARM Cortex A53 1.2GHz)

test case | Before | After
--------- | ------ | -----
(640x480, 8UC1, THRESH_BINARY)| 0.17 | 0.18
(640x480, 8UC1, THRESH_BINARY_INV)| 0.18 | 0.20
(640x480, 8UC1, THRESH_TRUNC)| 0.18 | 0.21
(640x480, 8UC1, THRESH_TOZERO)| 0.18 | 0.20
(640x480, 8UC1, THRESH_TOZERO_INV)| 0.20 | 0.18
(640x480, 16SC1, THRESH_BINARY)| 0.57 | 0.57
(640x480, 16SC1, THRESH_BINARY_INV)| 0.57 | 0.57
(640x480, 16SC1, THRESH_TRUNC)| 0.57 | 0.60
(640x480, 16SC1, THRESH_TOZERO)| 0.57 | 0.56
(640x480, 16SC1, THRESH_TOZERO_INV)| 0.57 | 0.59
(640x480, 32FC1, THRESH_BINARY)| 1.36 | 1.37
(640x480, 32FC1, THRESH_BINARY_INV)| 1.36 | 1.34
(640x480, 32FC1, THRESH_TRUNC)| 1.35 | 1.36
(640x480, 32FC1, THRESH_TOZERO)| 1.37 | 1.37
(640x480, 32FC1, THRESH_TOZERO_INV)| 1.36 | 1.38
(640x480, 64FC1, THRESH_BINARY)| 2.61 | 2.57
(640x480, 64FC1, THRESH_BINARY_INV)| 2.62 | 2.57
(640x480, 64FC1, THRESH_TRUNC)| 2.60 | 2.57
(640x480, 64FC1, THRESH_TOZERO)| 2.64 | 2.58
(640x480, 64FC1, THRESH_TOZERO_INV)| 2.59 | 2.57
(1280x720, 8UC1, THRESH_BINARY)| 0.99 | 1.00
(1280x720, 8UC1, THRESH_BINARY_INV)| 1.07 | 0.97
(1280x720, 8UC1, THRESH_TRUNC)| 1.04 | 0.91
(1280x720, 8UC1, THRESH_TOZERO)| 0.99 | 1.01
(1280x720, 8UC1, THRESH_TOZERO_INV)| 1.00 | 0.97
(1280x720, 16SC1, THRESH_BINARY)| 1.95 | 1.92
(1280x720, 16SC1, THRESH_BINARY_INV)| 1.92 | 1.85
(1280x720, 16SC1, THRESH_TRUNC)| 1.89 | 1.76
(1280x720, 16SC1, THRESH_TOZERO)| 1.89 | 1.83
(1280x720, 16SC1, THRESH_TOZERO_INV)| 1.94 | 1.82
(1280x720, 32FC1, THRESH_BINARY)| 3.67 | 3.69
(1280x720, 32FC1, THRESH_BINARY_INV)| 3.66 | 3.72
(1280x720, 32FC1, THRESH_TRUNC)| 3.73 | 3.67
(1280x720, 32FC1, THRESH_TOZERO)| 3.76 | 3.56
(1280x720, 32FC1, THRESH_TOZERO_INV)| 3.66 | 3.65
(1280x720, 64FC1, THRESH_BINARY)| 7.12 | 7.12
(1280x720, 64FC1, THRESH_BINARY_INV)| 7.20 | 6.51
(1280x720, 64FC1, THRESH_TRUNC)| 7.12 | 7.13
(1280x720, 64FC1, THRESH_TOZERO)| 7.16 | 6.99
(1280x720, 64FC1, THRESH_TOZERO_INV)| 7.12 | 7.00
(1920x1080, 8UC1, THRESH_BINARY)| 2.16 | 2.24
(1920x1080, 8UC1, THRESH_BINARY_INV)| 2.21 | 2.18
(1920x1080, 8UC1, THRESH_TRUNC)| 2.21 | 2.14
(1920x1080, 8UC1, THRESH_TOZERO)| 2.20 | 2.18
(1920x1080, 8UC1, THRESH_TOZERO_INV)| 2.18 | 2.10
(1920x1080, 16SC1, THRESH_BINARY)| 4.16 | 4.15
(1920x1080, 16SC1, THRESH_BINARY_INV)| 4.17 | 3.71
(1920x1080, 16SC1, THRESH_TRUNC)| 4.12 | 4.15
(1920x1080, 16SC1, THRESH_TOZERO)| 4.17 | 4.24
(1920x1080, 16SC1, THRESH_TOZERO_INV)| 4.57 | 4.12
(1920x1080, 32FC1, THRESH_BINARY)| 8.10 | 7.90
(1920x1080, 32FC1, THRESH_BINARY_INV)| 7.95 | 8.00
(1920x1080, 32FC1, THRESH_TRUNC)| 8.17 | 8.04
(1920x1080, 32FC1, THRESH_TOZERO)| 8.18 | 8.00
(1920x1080, 32FC1, THRESH_TOZERO_INV)| 8.12 | 8.01
(1920x1080, 64FC1, THRESH_BINARY)| 15.86 | 16.04
(1920x1080, 64FC1, THRESH_BINARY_INV)| 15.66 | 15.68
(1920x1080, 64FC1, THRESH_TRUNC)| 15.93 | 15.39
(1920x1080, 64FC1, THRESH_TOZERO)| 15.50 | 15.66
(1920x1080, 64FC1, THRESH_TOZERO_INV)| 15.87 | 15.44
(127x61, 8UC1, THRESH_BINARY)| 0.00 | 0.00
(127x61, 8UC1, THRESH_BINARY_INV)| 0.00 | 0.00
(127x61, 8UC1, THRESH_TRUNC)| 0.00 | 0.01
(127x61, 8UC1, THRESH_TOZERO)| 0.00 | 0.00
(127x61, 8UC1, THRESH_TOZERO_INV)| 0.00 | 0.00
(127x61, 16SC1, THRESH_BINARY)| 0.01 | 0.01
(127x61, 16SC1, THRESH_BINARY_INV)| 0.01 | 0.01
(127x61, 16SC1, THRESH_TRUNC)| 0.01 | 0.01
(127x61, 16SC1, THRESH_TOZERO)| 0.01 | 0.01
(127x61, 16SC1, THRESH_TOZERO_INV)| 0.01 | 0.01
(127x61, 32FC1, THRESH_BINARY)| 0.01 | 0.01
(127x61, 32FC1, THRESH_BINARY_INV)| 0.01 | 0.01
(127x61, 32FC1, THRESH_TRUNC)| 0.02 | 0.01
(127x61, 32FC1, THRESH_TOZERO)| 0.01 | 0.01
(127x61, 32FC1, THRESH_TOZERO_INV)| 0.01 | 0.01
(127x61, 64FC1, THRESH_BINARY)| 0.02 | 0.02
(127x61, 64FC1, THRESH_BINARY_INV)| 0.02 | 0.02
(127x61, 64FC1, THRESH_TRUNC)| 0.02 | 0.02
(127x61, 64FC1, THRESH_TOZERO)| 0.02 | 0.02
(127x61, 64FC1, THRESH_TOZERO_INV)| 0.02 | 0.02


### Jetson TK1 Ubuntu 14.04 32bit GCC 4.8 (ARM Cortex-A15 2.3GHz)
test case | Before | After
--------- | ------ | -----
(640x480, 8UC1, THRESH_BINARY)| 0.10 | 0.10 
(640x480, 8UC1, THRESH_BINARY_INV)| 0.12 | 0.07 
(640x480, 8UC1, THRESH_TRUNC)| 0.11 | 0.07 
(640x480, 8UC1, THRESH_TOZERO)| 0.11 | 0.12 
(640x480, 8UC1, THRESH_TOZERO_INV)| 0.12 | 0.11 
(640x480, 16SC1, THRESH_BINARY)| 0.10 | 0.13 
(640x480, 16SC1, THRESH_BINARY_INV)| 0.10 | 0.14 
(640x480, 16SC1, THRESH_TRUNC)| 0.10 | 0.13 
(640x480, 16SC1, THRESH_TOZERO)| 0.11 | 0.10 
(640x480, 16SC1, THRESH_TOZERO_INV)| 0.11 | 0.10 
(640x480, 32FC1, THRESH_BINARY)| 0.19 | 0.21 
(640x480, 32FC1, THRESH_BINARY_INV)| 0.23 | 0.25 
(640x480, 32FC1, THRESH_TRUNC)| 0.23 | 0.23 
(640x480, 32FC1, THRESH_TOZERO)| 0.24 | 0.25 
(640x480, 32FC1, THRESH_TOZERO_INV)| 0.25 | 0.26 
(640x480, 64FC1, THRESH_BINARY)| 0.91 | 0.88 
(640x480, 64FC1, THRESH_BINARY_INV)| 0.81 | 0.72 
(640x480, 64FC1, THRESH_TRUNC)| 0.76 | 0.81 
(640x480, 64FC1, THRESH_TOZERO)| 0.89 | 0.78 
(640x480, 64FC1, THRESH_TOZERO_INV)| 0.87 | 0.64 
(1280x720, 8UC1, THRESH_BINARY)| 0.18 | 0.17 
(1280x720, 8UC1, THRESH_BINARY_INV)| 0.20 | 0.26 
(1280x720, 8UC1, THRESH_TRUNC)| 0.20 | 0.22 
(1280x720, 8UC1, THRESH_TOZERO)| 0.18 | 0.18 
(1280x720, 8UC1, THRESH_TOZERO_INV)| 0.22 | 0.19 
(1280x720, 16SC1, THRESH_BINARY)| 0.69 | 0.32 
(1280x720, 16SC1, THRESH_BINARY_INV)| 0.30 | 0.33 
(1280x720, 16SC1, THRESH_TRUNC)| 0.30 | 0.30 
(1280x720, 16SC1, THRESH_TOZERO)| 0.31 | 0.28 
(1280x720, 16SC1, THRESH_TOZERO_INV)| 0.30 | 0.32 
(1280x720, 32FC1, THRESH_BINARY)| 1.01 | 1.10 
(1280x720, 32FC1, THRESH_BINARY_INV)| 1.03 | 1.11 
(1280x720, 32FC1, THRESH_TRUNC)| 1.05 | 1.33 
(1280x720, 32FC1, THRESH_TOZERO)| 1.03 | 1.36 
(1280x720, 32FC1, THRESH_TOZERO_INV)| 1.03 | 1.40 
(1280x720, 64FC1, THRESH_BINARY)| 2.46 | 2.70 
(1280x720, 64FC1, THRESH_BINARY_INV)| 2.49 | 2.55 
(1280x720, 64FC1, THRESH_TRUNC)| 2.40 | 2.49 
(1280x720, 64FC1, THRESH_TOZERO)| 2.42 | 2.42 
(1280x720, 64FC1, THRESH_TOZERO_INV)| 2.42 | 2.41 
(1920x1080, 8UC1, THRESH_BINARY)| 0.38 | 0.38 
(1920x1080, 8UC1, THRESH_BINARY_INV)| 0.39 | 0.42 
(1920x1080, 8UC1, THRESH_TRUNC)| 0.37 | 0.38 
(1920x1080, 8UC1, THRESH_TOZERO)| 0.38 | 0.37 
(1920x1080, 8UC1, THRESH_TOZERO_INV)| 0.37 | 0.36 
(1920x1080, 16SC1, THRESH_BINARY)| 1.18 | 1.23 
(1920x1080, 16SC1, THRESH_BINARY_INV)| 1.18 | 1.24 
(1920x1080, 16SC1, THRESH_TRUNC)| 1.18 | 1.21 
(1920x1080, 16SC1, THRESH_TOZERO)| 1.18 | 1.26 
(1920x1080, 16SC1, THRESH_TOZERO_INV)| 1.16 | 1.27 
(1920x1080, 32FC1, THRESH_BINARY)| 2.55 | 2.72 
(1920x1080, 32FC1, THRESH_BINARY_INV)| 2.56 | 2.64 
(1920x1080, 32FC1, THRESH_TRUNC)| 2.53 | 2.67 
(1920x1080, 32FC1, THRESH_TOZERO)| 2.64 | 2.71 
(1920x1080, 32FC1, THRESH_TOZERO_INV)| 2.55 | 2.71 
(1920x1080, 64FC1, THRESH_BINARY)| 5.37 | 5.40 
(1920x1080, 64FC1, THRESH_BINARY_INV)| 5.39 | 5.38 
(1920x1080, 64FC1, THRESH_TRUNC)| 5.35 | 5.38 
(1920x1080, 64FC1, THRESH_TOZERO)| 5.35 | 5.35 
(1920x1080, 64FC1, THRESH_TOZERO_INV)| 5.37 | 5.34 
(127x61, 8UC1, THRESH_BINARY)| 0.00 | 0.00 
(127x61, 8UC1, THRESH_BINARY_INV)| 0.00 | 0.00 
(127x61, 8UC1, THRESH_TRUNC)| 0.00 | 0.00 
(127x61, 8UC1, THRESH_TOZERO)| 0.00 | 0.00 
(127x61, 8UC1, THRESH_TOZERO_INV)| 0.00 | 0.00 
(127x61, 16SC1, THRESH_BINARY)| 0.00 | 0.00 
(127x61, 16SC1, THRESH_BINARY_INV)| 0.00 | 0.00 
(127x61, 16SC1, THRESH_TRUNC)| 0.00 | 0.00 
(127x61, 16SC1, THRESH_TOZERO)| 0.00 | 0.00 
(127x61, 16SC1, THRESH_TOZERO_INV)| 0.00 | 0.00 
(127x61, 32FC1, THRESH_BINARY)| 0.01 | 0.01 
(127x61, 32FC1, THRESH_BINARY_INV)| 0.01 | 0.01 
(127x61, 32FC1, THRESH_TRUNC)| 0.01 | 0.00 
(127x61, 32FC1, THRESH_TOZERO)| 0.01 | 0.01 
(127x61, 32FC1, THRESH_TOZERO_INV)| 0.01 | 0.01 
(127x61, 64FC1, THRESH_BINARY)| 0.03 | 0.02 
(127x61, 64FC1, THRESH_BINARY_INV)| 0.03 | 0.02 
(127x61, 64FC1, THRESH_TRUNC)| 0.04 | 0.02 
(127x61, 64FC1, THRESH_TOZERO)| 0.03 | 0.02 
(127x61, 64FC1, THRESH_TOZERO_INV)| 0.03 | 0.02 




### Windows 7 64bit (VS2012 64bit Corei7 3.4GHz)

test case | Before | After
--------- | ------ | -----
(640x480, 8UC1, THRESH_BINARY)| 0.02 | 0.02
(640x480, 8UC1, THRESH_BINARY_INV)| 0.02 | 0.02
(640x480, 8UC1, THRESH_TRUNC)| 0.02 | 0.02
(640x480, 8UC1, THRESH_TOZERO)| 0.02 | 0.02
(640x480, 8UC1, THRESH_TOZERO_INV)| 0.02 | 0.02
(640x480, 16SC1, THRESH_BINARY)| 0.03 | 0.03
(640x480, 16SC1, THRESH_BINARY_INV)| 0.03 | 0.03
(640x480, 16SC1, THRESH_TRUNC)| 0.03 | 0.03
(640x480, 16SC1, THRESH_TOZERO)| 0.03 | 0.03
(640x480, 16SC1, THRESH_TOZERO_INV)| 0.03 | 0.04
(640x480, 32FC1, THRESH_BINARY)| 0.06 | 0.06
(640x480, 32FC1, THRESH_BINARY_INV)| 0.06 | 0.06
(640x480, 32FC1, THRESH_TRUNC)| 0.06 | 0.06
(640x480, 32FC1, THRESH_TOZERO)| 0.06 | 0.06
(640x480, 32FC1, THRESH_TOZERO_INV)| 0.06 | 0.06
(640x480, 64FC1, THRESH_BINARY)| 0.13 | 0.13
(640x480, 64FC1, THRESH_BINARY_INV)| 0.12 | 0.12
(640x480, 64FC1, THRESH_TRUNC)| 0.12 | 0.12
(640x480, 64FC1, THRESH_TOZERO)| 0.13 | 0.13
(640x480, 64FC1, THRESH_TOZERO_INV)| 0.13 | 0.12
(1280x720, 8UC1, THRESH_BINARY)| 0.04 | 0.04
(1280x720, 8UC1, THRESH_BINARY_INV)| 0.04 | 0.04
(1280x720, 8UC1, THRESH_TRUNC)| 0.05 | 0.04
(1280x720, 8UC1, THRESH_TOZERO)| 0.04 | 0.04
(1280x720, 8UC1, THRESH_TOZERO_INV)| 0.04 | 0.05
(1280x720, 16SC1, THRESH_BINARY)| 0.07 | 0.06
(1280x720, 16SC1, THRESH_BINARY_INV)| 0.06 | 0.08
(1280x720, 16SC1, THRESH_TRUNC)| 0.13 | 0.10
(1280x720, 16SC1, THRESH_TOZERO)| 0.10 | 0.09
(1280x720, 16SC1, THRESH_TOZERO_INV)| 0.06 | 0.08
(1280x720, 32FC1, THRESH_BINARY)| 0.15 | 0.16
(1280x720, 32FC1, THRESH_BINARY_INV)| 0.17 | 0.16
(1280x720, 32FC1, THRESH_TRUNC)| 0.17 | 0.24
(1280x720, 32FC1, THRESH_TOZERO)| 0.17 | 0.20
(1280x720, 32FC1, THRESH_TOZERO_INV)| 0.18 | 0.17
(1280x720, 64FC1, THRESH_BINARY)| 1.31 | 1.13
(1280x720, 64FC1, THRESH_BINARY_INV)| 1.32 | 1.11
(1280x720, 64FC1, THRESH_TRUNC)| 1.34 | 1.10
(1280x720, 64FC1, THRESH_TOZERO)| 1.49 | 1.09
(1280x720, 64FC1, THRESH_TOZERO_INV)| 1.15 | 1.22
(1920x1080, 8UC1, THRESH_BINARY)| 0.07 | 0.08
(1920x1080, 8UC1, THRESH_BINARY_INV)| 0.08 | 0.09
(1920x1080, 8UC1, THRESH_TRUNC)| 0.08 | 0.09
(1920x1080, 8UC1, THRESH_TOZERO)| 0.09 | 0.08
(1920x1080, 8UC1, THRESH_TOZERO_INV)| 0.09 | 0.09
(1920x1080, 16SC1, THRESH_BINARY)| 0.21 | 0.23
(1920x1080, 16SC1, THRESH_BINARY_INV)| 0.24 | 0.24
(1920x1080, 16SC1, THRESH_TRUNC)| 0.22 | 0.20
(1920x1080, 16SC1, THRESH_TOZERO)| 0.22 | 0.22
(1920x1080, 16SC1, THRESH_TOZERO_INV)| 0.20 | 0.23
(1920x1080, 32FC1, THRESH_BINARY)| 1.36 | 1.49
(1920x1080, 32FC1, THRESH_BINARY_INV)| 1.28 | 1.53
(1920x1080, 32FC1, THRESH_TRUNC)| 1.31 | 1.60
(1920x1080, 32FC1, THRESH_TOZERO)| 1.29 | 1.33
(1920x1080, 32FC1, THRESH_TOZERO_INV)| 1.32 | 1.37
(1920x1080, 64FC1, THRESH_BINARY)| 3.23 | 3.18
(1920x1080, 64FC1, THRESH_BINARY_INV)| 3.08 | 3.21
(1920x1080, 64FC1, THRESH_TRUNC)| 3.12 | 3.02
(1920x1080, 64FC1, THRESH_TOZERO)| 3.28 | 3.08
(1920x1080, 64FC1, THRESH_TOZERO_INV)| 3.15 | 3.13
(127x61, 8UC1, THRESH_BINARY)| 0.00 | 0.00
(127x61, 8UC1, THRESH_BINARY_INV)| 0.00 | 0.00
(127x61, 8UC1, THRESH_TRUNC)| 0.00 | 0.00
(127x61, 8UC1, THRESH_TOZERO)| 0.00 | 0.00
(127x61, 8UC1, THRESH_TOZERO_INV)| 0.00 | 0.00
(127x61, 16SC1, THRESH_BINARY)| 0.00 | 0.00
(127x61, 16SC1, THRESH_BINARY_INV)| 0.00 | 0.00
(127x61, 16SC1, THRESH_TRUNC)| 0.00 | 0.00
(127x61, 16SC1, THRESH_TOZERO)| 0.00 | 0.00
(127x61, 16SC1, THRESH_TOZERO_INV)| 0.00 | 0.00
(127x61, 32FC1, THRESH_BINARY)| 0.00 | 0.00
(127x61, 32FC1, THRESH_BINARY_INV)| 0.00 | 0.00
(127x61, 32FC1, THRESH_TRUNC)| 0.00 | 0.00
(127x61, 32FC1, THRESH_TOZERO)| 0.00 | 0.00
(127x61, 32FC1, THRESH_TOZERO_INV)| 0.00 | 0.00
(127x61, 64FC1, THRESH_BINARY)| 0.01 | 0.01
(127x61, 64FC1, THRESH_BINARY_INV)| 0.01 | 0.01
(127x61, 64FC1, THRESH_TRUNC)| 0.01 | 0.01
(127x61, 64FC1, THRESH_TOZERO)| 0.01 | 0.01
(127x61, 64FC1, THRESH_TOZERO_INV)| 0.01 | 0.01

**Comment by vpisarev** [comment]
@tomoaki0705, thank you for the PR. As you can see, some test failed because you've modified added some more configurations to the performance tests. Can you make a pull request to opencv_extra to the branch with the same name (featureUniversalThreshold)?

**Comment by tomoaki0705** [comment]
@vpisarev , Thank you for your suggestion.
Yeah, I'm working on opencv_extra, too.  I will make a branch with same name, later.
Please give me sore time to push the branch to opencv_extra.

Best.

**Comment by alalek** [comment]
:+1:

**Pull request merged**
