### PR TITLE
G-API: Object tracking

### PR DESCRIPTION
**Pull request by TolyaTalamanov**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under OpenCV (BSD) License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by TolyaTalamanov** [comment]
@dmatveev @smirnov-alexey

**Comment by dmatveev** [comment]
Please rebase to a proper branch to clear out the `GOpaque<>`-related changes

**Comment by asmorkalov** [comment]
@TolyaTalamanov friendly reminder.

**Comment by asmorkalov** [comment]
@TolyaTalamanov @dmatveev  Do you have progress with the patch? There are merge conflicts.

**Comment by dmatveev** [comment]
@asmorkalov the design is still not closed yet as we are actively discussing it. I'd mark it as WIP to avoid confusion

**Comment by asmorkalov** [comment]
@dmatveev Friendly reminder about the patch.

**Pull request closed without merging**
