### PR TITLE
fix Win32 build (2)

### PR DESCRIPTION
**Pull request by alalek**
**WIP**

### CODE REVIEW

**Comment by K-Shinotsuka** [comment]
@alalek 
Thank you for fixing the compile error.
I want to know why this error was occurred.
And I want to know why you conceive this change.
Please teach me.

**Comment by alalek** [comment]
This problem is detected by Win32 builder. It is not included into list of required pre-commit builds, so this problem is not detected during PR review process.
This problem is raised during regular nightly Win32 builds: http://pullrequest.opencv.org/buildbot/grid?tag=scheduled-master

The reason of problem is related to MSVC compiler, which can't work with `__m128` parameters passed by value.
Description of compiler error message: https://msdn.microsoft.com/en-us/library/373ak2y1.aspx
Take a look on this StackOverflow [comment](http://stackoverflow.com/questions/28488986/c-opengl-formal-parameter-with-declspecalign16-wont-be-aligned#comment45301490_28489172) about a similar problem.

**Comment by K-Shinotsuka** [comment]
@alalek 
That’s very helpful.
I can learn a lot from you.

**Comment by mshabunin** [comment]
:+1:

**Pull request merged**
