### PR TITLE
update libpng to 1.6.36

### PR DESCRIPTION
**Pull request by tailsu**
Sources copied from https://github.com/glennrp/libpng/archive/v1.6.36.tar.gz

### CODE REVIEW

**Comment by alalek** [comment]
Previous libpng update: #12991

Please add temporary testing commit "! test" to force building of these source on all available platforms (from mentioned PR: [commit](https://github.com/opencv/opencv/commit/a39d14b33642be8753bdaea7a6ee8209136a2fe2)). It will be removed before actual merge.

**Comment by alalek** [comment]
Build warnings should be [suppressed via CMake scripts](https://github.com/opencv/opencv/blob/3.4.5/3rdparty/libpng/CMakeLists.txt#L66).

**Comment by tailsu** [comment]
added `! test` commit.

Also, I noticed that NEON acceleration was completely disabled for arm64. I fixed the cmake file.

**Comment by tailsu** [comment]
```
Manual validation is requied.  Variable is not defined: HAVE_LIBPNG_PNG_H
```
I don't understand where this warning comes from. Any help?

**Comment by alalek** [comment]
It is internal configuration validation (some kind of regressions in CMake scripts). Warning is expected ("! test" commit).

Looks like other parts of builds are fine.
Please remove "! test" commit and squash commits into one (for example, via `git rebase -i HEAD~5`)

**Comment by alalek** [comment]
Thank you!

Please add [missing updates](https://github.com/alalek/opencv/commit/pr13807_r) for `REAME` and `pnglibconf.h` files (squash commits into one).

**Comment by tailsu** [comment]
Done.

My pleasure!

**Pull request merged**
