### PR TITLE
[ts][summary.py] Extend `-o` to support tabs separated output.

### PR DESCRIPTION
**Pull request by fpetrogalli**
This PR is related to issue #19267 .

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [X] The PR is proposed to proper branch
- [X] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by fpetrogalli** [comment]
In the last commit I fixed the code, so that now it does not produce `TAB` at the beginning of the row and at the end of it.

**Comment by fpetrogalli** [comment]
@alalek  - gentle ping.

I am planning to set up pipelines that could use this. It would be good if I could skip the cherry pick step.

Cheers,

Francesco

**Review by alalek — APPROVED** [review]
@fpetrogalli Sorry for delay.
Well done! Thank you for contribution :+1:

**Comment by fpetrogalli** [comment]
Thank you!

**Pull request merged**
