### PR TITLE
cmake: fix pkg-config generation for MacOSX

### LINKED ISSUE #10046: Opencv pkg-config config file is unusable, Opencv 3.3.1 Homebrew OSX
File `/usr/local/lib/pkgconfig/opencv.pc` has all the linker flags wrong, and it makes pkg-config unusable for opencv.

example:

it is:
`-llibopencv_stitching.3.3.1.dylib`

it should be:
`-lopencv_stitching`

etc.

Fresh install OSX 10.13 High Sierra.

`$ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ade735b9e95352f1731445bad505d920c9521969
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13-x86_64
Xcode: 9.1
CLT: 9.0.1.0.1.1506734476
X11: 2.7.11 => /opt/X11`

`$ brew info opencv
opencv: stable 3.3.1 (bottled)
Open source computer vision library
https://opencv.org/
/usr/local/Cellar/opencv/3.3.1_1 (519 files, 95.8MB) *
  Built from source on 2017-11-08 at 11:53:09
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/opencv.rb
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: eigen ✔, ffmpeg ✔, jpeg ✔, libpng ✔, libtiff ✔, openexr ✔, numpy ✔, tbb ✔
==> Requirements
Required: python ✔, python3 ✔`

Also reported in Homebrew bug tracker: https://github.com/Homebrew/homebrew-core/issues/20406

### PR DESCRIPTION
**Pull request by alalek**
resolves #10046

### CODE REVIEW

**Comment by ilovezfs** [comment]
This produces
```
iMac-TMP:3.3.1_1 joe$ cat lib/pkgconfig/opencv.pc 
# Package Information for pkg-config

prefix=/usr/local/Cellar/opencv/3.3.1_1
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir_old=${prefix}/include/opencv
includedir_new=${prefix}/include

Name: OpenCV
Description: Open Source Computer Vision Library
Version: 3.3.1
Libs: -L${exec_prefix}/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_photo -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dpm -lopencv_face -lopencv_fuzzy -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core
Libs.private: -L/usr/local/lib -ltbb
Cflags: -I${includedir_old} -I${includedir_new}
iMac-TMP:3.3.1_1 joe$ 
```
which looks good except that the frameworks appear to be missing from the Libs.private section when compared to 3.3.0. Is that expected or another regression?

**Comment by alalek** [comment]
Thanks!
This OpenCV build produces shared libraries (`.dylib` files). `Libs.private` is used with static linking only (`pkg-config --static --libs`), so this should not break current applications builds.

**Comment by ilovezfs** [comment]
We distribute both the .dylib's and .a's in Homebrew …

**Comment by alalek** [comment]
Hmm, there is no single opencv.pc file for both configurations.

Result with `BUILD_SHARED_LIBS=ON` (default):

> Package Information for pkg-config
>
> prefix=/usr/local
> exec_prefix=${prefix}
> libdir=${exec_prefix}/lib
> includedir_old=${prefix}/include/opencv
> includedir_new=${prefix}/include
> 
> Name: OpenCV
> Description: Open Source Computer Vision Library
> Version: 3.3.1
> Libs: -L${exec_prefix}/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -> lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dpm -lopencv_face -lopencv_photo -lopencv_fuzzy -lopencv_hdf -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_viz -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core
> Libs.private: 
Cflags: -I${includedir_old} -I${includedir_new}


Result with `BUILD_SHARED_LIBS=OFF`:
> Package Information for pkg-config
> 
> prefix=/usr/local
> exec_prefix=${prefix}
> libdir=${exec_prefix}/lib
> includedir_old=${prefix}/include/opencv
> includedir_new=${prefix}/include
> 
> Name: OpenCV
> Description: Open Source Computer Vision Library
> Version: 3.3.1
> Libs: -L${exec_prefix}/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -> lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dpm -lopencv_face -lopencv_photo -> lopencv_fuzzy -lopencv_hdf -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core
> Libs.private: -L${exec_prefix}/share/OpenCV/3rdparty/lib -littnotify -llibprotobuf -llibjpeg -llibwebp -llibpng -llibtiff -llibjasper -lIlmImf -lzlib -lippiw -lippicv -framework OpenCL -lavcodec -lavformat -lavutil -lswscale -lavresample -framework VideoDecodeAcceleration -lbz2 -framework Cocoa -framework Accelerate -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreVideo -framework QuartzCore -L/usr/local/Cellar/hdf5/1.10.1_2/lib -llibhdf5.dylib -L/usr/local/opt/szip/lib -lsz -L/usr/lib -llibz.dylib -ldl -llibm.dylib -lstdc++
> Cflags: -I${includedir_old} -I${includedir_new}

**Comment by alalek** [comment]
:+1:

**Comment by amroamroamro** [comment]
The resulting `opencv.pc` is also unusable in MinGW, it produces something like:
```
...
Libs: -L${exec_prefix}/x86/mingw/lib -llibopencv_stitching331.dll -llibopencv_superres331.dll ...
...
```

This should fix it:
``` diff
$ git diff
diff --git a/cmake/OpenCVUtils.cmake b/cmake/OpenCVUtils.cmake
index 160424b2c..841a83ea6 100644
--- a/cmake/OpenCVUtils.cmake
+++ b/cmake/OpenCVUtils.cmake
@@ -1002,7 +1002,7 @@ endfunction()
 macro(ocv_get_libname var_name)
   get_filename_component(__libname "${ARGN}" NAME)
   # libopencv_core.so.3.3 -> opencv_core
-  string(REGEX REPLACE "^lib(.+)\\.(a|so)(\\.[.0-9]+)?$" "\\1" __libname "${__libname}")
+  string(REGEX REPLACE "^lib(.+)\\.(a|so|dll)(\\.[.0-9]+)?$" "\\1" __libname "${__libname}")
   # MacOSX: libopencv_core.3.3.1.dylib -> opencv_core
   string(REGEX REPLACE "^lib(.+[^.0-9])\\.([.0-9]+\\.)?dylib$" "\\1" __libname "${__libname}")
   set(${var_name} "${__libname}")
```

Even better, it can be simplified by directly using [`NAME_WE`](https://cmake.org/cmake/help/latest/command/get_filename_component.html):
``` diff
$ git diff
diff --git a/cmake/OpenCVUtils.cmake b/cmake/OpenCVUtils.cmake
index 160424b2c..0197ba129 100644
--- a/cmake/OpenCVUtils.cmake
+++ b/cmake/OpenCVUtils.cmake
@@ -1000,11 +1000,8 @@ endfunction()


 macro(ocv_get_libname var_name)
-  get_filename_component(__libname "${ARGN}" NAME)
-  # libopencv_core.so.3.3 -> opencv_core
-  string(REGEX REPLACE "^lib(.+)\\.(a|so)(\\.[.0-9]+)?$" "\\1" __libname "${__libname}")
-  # MacOSX: libopencv_core.3.3.1.dylib -> opencv_core
-  string(REGEX REPLACE "^lib(.+[^.0-9])\\.([.0-9]+\\.)?dylib$" "\\1" __libname "${__libname}")
+  get_filename_component(__libname "${ARGN}" NAME_WE)
+  string(REGEX REPLACE "^lib" "" __libname "${__libname}")
   set(${var_name} "${__libname}")
 endmacro()
```

**Comment by alalek** [comment]
> This should fix it

Feel free to prepare pull request.

> NAME_WE

We used this before and this doesn't work well on Linux: #8970

**Comment by amroamroamro** [comment]
I see, I'll submit a PR with the first fix.

**Pull request merged**
