### PR TITLE
`solvePnP`and 'projectPoints' for calib3d and face module

### PR DESCRIPTION
**Pull request by kavikode**
reproducer for #15299

```
opencv_contrib=master
force_builders_only=Custom
buildworker:Custom=linux-1,linux-2,linux-4
docker_image:Custom=javascript
```

### CODE REVIEW

**Comment by kavikode** [comment]
any suggestions please ?

**Comment by asmorkalov** [comment]
@kavikode Could you look at my comments and also rebase the patch to current master to fix merge conflicts.

**Comment by alalek** [comment]
This PR is just a reproducer for linked issue.

Need to fix bindings generator first (support nested namespaces - see issue's comments)

**Comment by kavikode** [comment]
Yes, how do we fix it?

**Comment by asmorkalov** [comment]
@alalek thanks, I missed the link in PR description.

**Comment by kavikode** [comment]
how do we fix the issue so that the face module works? I want to use it purely from OpenCV.js.

**Comment by asenyaev** [comment]
jenkins cn please retry a build

**Pull request closed without merging**
