### PR TITLE
Add minDiversity check in grayscale MSER

### PR DESCRIPTION
**Pull request by danielenricocahall**
Addresses issue described here https://github.com/opencv/opencv/issues/5630. In MSER, `min_diversity` was used for color images but not for grayscale. There was a check to verify variance was positive, which I replaced with checking to verify the variance is greater than `minDiversity`. I also expose setter/getter for `minDiversity`.
 
Note:
- Had to explicitly set `minDiversity` to 0 (to replicate the original logic) in `history_update_regression`, `cases`, and `test_mser.py` unit tests, as `min_diversity` defaults to 0.2.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by danielenricocahall** [comment]
@alalek do you have any thoughts around the introduction of the virtual methods for `minDiversity` and the v-table change https://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/31657/steps/Compare%20ABI%20dumps/logs/report-html? It currently causes a failure

**Comment by vpisarev** [comment]
@danielenricocahall, thank you for the contribution!

Regarding the ABI compatibility check. Use the following trick:

1. redefine `setMinDiversity/getMinDiversity` as non-virtual method.
2. inside the methods' implementation do the following:

```
MSER_Impl* impl = dynamic_cast<MSER_Impl*>(this);
if (impl) { 
    impl->params.minDiversity = minDiversity; // in the case of setMinDiversity()
} else {
    CV_Error(Error::StsBadArg, "Ptr<MSER_Impl> is expected");
}
```

**Comment by danielenricocahall** [comment]
> @danielenricocahall, thank you for the contribution!
> 
> Regarding the ABI compatibility check. Use the following trick:
> 
> 1. redefine `setMinDiversity/getMinDiversity` as non-virtual method.
> 2. inside the methods' implementation do the following:
> 
> ```
> MSER_Impl* impl = dynamic_cast<MSER_Impl*>(this);
> if (impl) { 
>     impl->params.minDiversity = minDiversity; // in the case of setMinDiversity()
> } else {
>     CV_Error(Error::StsBadArg, "Ptr<MSER_Impl> is expected");
> }
> ```

@vpisarev thank you for the feedback! Good to know - is there any alternative though? What are the consequences to the v-table changing? I was trying to follow the pattern laid out for the other setters/getters in MSER

**Comment by vpisarev** [comment]
In OpenCV 3.x we stated that ABI is preserved. Changes in v-table mean violation of this statement. It is a simple as this. In the master branch the rule is relaxed a bit, but the ABI check is still performed for the core, imgproc and few other modules, if I'm not mistaken.

If it works for you, you can resubmit the patch to the "next" branch (the upcoming OpenCV 5.0), there we can add virtual methods easily.
Otherwise, I do not see any other alternatives, unfortunately.

**Pull request closed without merging**
