### PR TITLE
Move vector_size_t and vector_vector_Mat

### LINKED ISSUE #9719: error with python module on compile
On fedora 26 I have this error when compiling openCV with the modules:

```
[ 84%] Building CXX object modules/optflow/CMakeFiles/opencv_perf_optflow.dir/perf/perf_main.cpp.o
[ 84%] Building CXX object modules/optflow/CMakeFiles/opencv_perf_optflow.dir/perf/perf_variational_refinement.cpp.o
In file included from /home/malcolm/external_sources/opencv/modules/python/src2/cv2.cpp:1496:0:
/home/malcolm/external_sources/opencv/build/modules/python2/pyopencv_generated_types.h: In function ‘PyObject* pyopencv_cv_structured_light_structured_light_StructuredLightPattern_decode(PyObject*, PyObject*, PyObject*)’:
/home/malcolm/external_sources/opencv/build/modules/python2/pyopencv_generated_types.h:45897:5: error: ‘vector_vector_Mat’ was not declared in this scope
     vector_vector_Mat patternImages;
     ^~~~~~~~~~~~~~~~~
/home/malcolm/external_sources/opencv/build/modules/python2/pyopencv_generated_types.h:45897:5: note: suggested alternative: ‘vector_vector_DMatch’
     vector_vector_Mat patternImages;
     ^~~~~~~~~~~~~~~~~
     vector_vector_DMatch
/home/malcolm/external_sources/opencv/build/modules/python2/pyopencv_generated_types.h:45909:42: error: ‘patternImages’ was not declared in this scope
         pyopencv_to(pyobj_patternImages, patternImages, ArgInfo("patternImages", 0)) &&
                                          ^~~~~~~~~~~~~
/home/malcolm/external_sources/opencv/build/modules/python2/pyopencv_generated_types.h:45909:42: note: suggested alternative: ‘whiteImages’
         pyopencv_to(pyobj_patternImages, patternImages, ArgInfo("patternImages", 0)) &&
                                          ^~~~~~~~~~~~~
                                          whiteImages
/home/malcolm/external_sources/opencv/build/modules/python2/pyopencv_generated_types.h:45922:5: error: ‘vector_vector_Mat’ was not declared in this scope
     vector_vector_Mat patternImages;
     ^~~~~~~~~~~~~~~~~
/home/malcolm/external_sources/opencv/build/modules/python2/pyopencv_generated_types.h:45922:5: note: suggested alternative: ‘vector_vector_DMatch’
     vector_vector_Mat patternImages;
     ^~~~~~~~~~~~~~~~~
     vector_vector_DMatch
/home/malcolm/external_sources/opencv/build/modules/python2/pyopencv_generated_types.h:45934:42: error: ‘patternImages’ was not declared in this scope
         pyopencv_to(pyobj_patternImages, patternImages, ArgInfo("patternImages", 0)) &&
                                          ^~~~~~~~~~~~~
/home/malcolm/external_sources/opencv/build/modules/python2/pyopencv_generated_types.h:45934:42: note: suggested alternative: ‘whiteImages’
         pyopencv_to(pyobj_patternImages, patternImages, ArgInfo("patternImages", 0)) &&
                                          ^~~~~~~~~~~~~
                                          whiteImages
In file included from /home/malcolm/external_sources/opencv/modules/python/src2/cv2.cpp:1496:0:
/home/malcolm/external_sources/opencv/build/modules/python3/pyopencv_generated_types.h: In function ‘PyObject* pyopencv_cv_structured_light_structured_light_StructuredLightPattern_decode(PyObject*, PyObject*, PyObject*)’:
/home/malcolm/external_sources/opencv/build/modules/python3/pyopencv_generated_types.h:45676:5: error: ‘vector_vector_Mat’ was not declared in this scope
     vector_vector_Mat patternImages;
     ^~~~~~~~~~~~~~~~~
/home/malcolm/external_sources/opencv/build/modules/python3/pyopencv_generated_types.h:45676:5: note: suggested alternative: ‘vector_vector_DMatch’
     vector_vector_Mat patternImages;
     ^~~~~~~~~~~~~~~~~
     vector_vector_DMatch
/home/malcolm/external_sources/opencv/build/modules/python3/pyopencv_generated_types.h:45688:42: error: ‘patternImages’ was not declared in this scope
         pyopencv_to(pyobj_patternImages, patternImages, ArgInfo("patternImages", 0)) &&
                                          ^~~~~~~~~~~~~
/home/malcolm/external_sources/opencv/build/modules/python3/pyopencv_generated_types.h:45688:42: note: suggested alternative: ‘whiteImages’
         pyopencv_to(pyobj_patternImages, patternImages, ArgInfo("patternImages", 0)) &&
                                          ^~~~~~~~~~~~~
                                          whiteImages
/home/malcolm/external_sources/opencv/build/modules/python3/pyopencv_generated_types.h:45701:5: error: ‘vector_vector_Mat’ was not declared in this scope
     vector_vector_Mat patternImages;
     ^~~~~~~~~~~~~~~~~
/home/malcolm/external_sources/opencv/build/modules/python3/pyopencv_generated_types.h:45701:5: note: suggested alternative: ‘vector_vector_DMatch’
     vector_vector_Mat patternImages;
     ^~~~~~~~~~~~~~~~~
     vector_vector_DMatch
/home/malcolm/external_sources/opencv/build/modules/python3/pyopencv_generated_types.h:45713:42: error: ‘patternImages’ was not declared in this scope
         pyopencv_to(pyobj_patternImages, patternImages, ArgInfo("patternImages", 0)) &&
                                          ^~~~~~~~~~~~~
/home/malcolm/external_sources/opencv/build/modules/python3/pyopencv_generated_types.h:45713:42: note: suggested alternative: ‘whiteImages’
         pyopencv_to(pyobj_patternImages, patternImages, ArgInfo("patternImages", 0)) &&
                                          ^~~~~~~~~~~~~
                                          whiteImages
[ 84%] Building CXX object modules/stitching/CMakeFiles/opencv_perf_stitching.dir/perf/perf_stich.cpp.o
[ 84%] Linking CXX executable ../../bin/opencv_perf_optflow
[ 84%] Built target opencv_perf_optflow
Scanning dependencies of target tutorial_hull_demo
[ 84%] Building CXX object samples/cpp/CMakeFiles/tutorial_hull_demo.dir/tutorial_code/ShapeDescriptors/hull_demo.cpp.o
[ 84%] Linking CXX executable ../../bin/cpp-tutorial-hull_demo
[ 84%] Built target tutorial_hull_demo
Scanning dependencies of target tutorial_EqualizeHist_Demo
[ 84%] Building CXX object samples/cpp/CMakeFiles/tutorial_EqualizeHist_Demo.dir/tutorial_code/Histograms_Matching/EqualizeHist_Demo.cpp.o
make[2]: *** [modules/python2/CMakeFiles/opencv_python2.dir/build.make:324: modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:21101: modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 84%] Linking CXX executable ../../bin/opencv_perf_stitching
[ 84%] Linking CXX executable ../../bin/cpp-tutorial-EqualizeHist_Demo
[ 84%] Built target opencv_perf_stitching
[ 84%] Built target tutorial_EqualizeHist_Demo
make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/build.make:324: modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:21232: modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

```

My Cmake config is as follow 
```
General configuration for OpenCV 3.3.0-dev =====================================
--   Version control:               3.3.0-370-g7475d23fe
-- 
--   Extra modules:
--     Location (extra):            /home/malcolm/external_sources/opencv_contrib/modules
--     Version control (extra):     3.3.0-58-g4bc49c05
-- 
--   Platform:
--     Timestamp:                   2017-09-26T18:52:28Z
--     Host:                        Linux 4.12.9-300.fc26.x86_64 x86_64
--     CMake:                       3.9.1
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/gmake
--     Configuration:               Release
-- 
--   CPU/HW features:
--     Baseline:                    SSE SSE2 SSE3
--       requested:                 SSE3
--     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
--       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2
--       SSE4_1 (3 files):          + SSSE3 SSE4_1
--       SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
--       FP16 (2 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
--       AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
--       AVX2 (7 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
-- 
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++11:                       YES
--     C++ Compiler:                /usr/bin/c++  (ver 7.1.1)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -O2 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /usr/bin/cc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -O2 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections  -msse -msse2 -msse3 -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):
--     Linker flags (Debug):
--     ccache:                      NO
--     Precompiled headers:         YES
--     Extra dependencies:          dl m pthread rt
--     3rdparty dependencies:
-- 
--   OpenCV modules:
--     To be built:                 core flann imgproc ml objdetect phase_unwrapping photo plot reg surface_matching video viz xphoto bgsegm face freetype fuzzy img_hash imgcodecs shape videoio xobjdetect highgui superres ts bioinspired dpm features2d line_descriptor saliency text calib3d ccalib cvv datasets rgbd stereo structured_light tracking videostab xfeatures2d ximgproc aruco optflow stitching python2 python3
--     Disabled:                    js world contrib_world dnn_modern
--     Disabled by dependency:      -
--     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev java cnn_3dobj hdf matlab sfm
-- 
--   GUI: 
--     QT 5.x:                      YES (ver 5.7.1)
--     QT OpenGL support:           NO
--     OpenGL support:              NO
--     VTK support:                 YES (ver 8.1.0)
-- 
--   Media I/O: 
--     ZLib:                        /lib64/libz.so (ver 1.2.11)
--     JPEG:                        /lib64/libjpeg.so (ver )
--     WEBP:                        build (ver encoder: 0x020e)
--     PNG:                         /lib64/libpng.so (ver 1.6.28)
--     TIFF:                        /lib64/libtiff.so (ver 42 - 4.0.8)
--     JPEG 2000:                   build (ver 1.900.1)
--     OpenEXR:                     build (ver 1.7.1)
--     GDAL:                        NO
--     GDCM:                        NO
-- 
--   Video I/O:
--     DC1394 1.x:                  NO
--     DC1394 2.x:                  NO
--     FFMPEG:                      NO
--       avcodec:                   NO
--       avformat:                  NO
--       avutil:                    NO
--       swscale:                   NO
--       avresample:                NO
--     GStreamer:                   NO
--     OpenNI:                      NO
--     OpenNI PrimeSensor Modules:  NO
--     OpenNI2:                     NO
--     PvAPI:                       NO
--     GigEVisionSDK:               NO
--     Aravis SDK:                  NO
--     UniCap:                      NO
--     UniCap ucil:                 NO
--     V4L/V4L2:                    NO/YES
--     XIMEA:                       NO
--     Xine:                        NO
--     Intel Media SDK:             NO
--     gPhoto2:                     NO
-- 
--   Parallel framework:            pthreads
-- 
--   Trace:                         YES (with Intel ITT)
-- 
--   Other third-party libraries:
--     Use Intel IPP:               2017.0.3 [2017.0.3]
--                at:               /home/malcolm/external_sources/opencv/build/3rdparty/ippicv/ippicv_lnx
--     Use Intel IPP IW:            NO
--     Use VA:                      NO
--     Use Intel VA-API/OpenCL:     NO
--     Use Lapack:                  NO
--     Use Eigen:                   YES (ver 3.3.4)
--     Use Cuda:                    NO
--     Use OpenCL:                  YES
--     Use OpenVX:                  NO
--     Use custom HAL:              NO
-- 
--   OpenCL:                        <Dynamic loading of OpenCL library>
--     Include path:                /home/malcolm/external_sources/opencv/3rdparty/include/opencl/1.2
--     Use AMDFFT:                  NO
--     Use AMDBLAS:                 NO
-- 
--   Python 2:
--     Interpreter:                 /usr/bin/python2.7 (ver 2.7.13)
--     Libraries:                   /lib64/libpython2.7.so (ver 2.7.13)
--     numpy:                       /usr/lib64/python2.7/site-packages/numpy/core/include (ver 1.12.1)
--     packages path:               lib/python2.7/site-packages
-- 
--   Python 3:
--     Interpreter:                 /usr/bin/python3 (ver 3.6.2)
--     Libraries:                   /lib64/libpython3.6m.so (ver 3.6.2)
--     numpy:                       /usr/lib64/python3.6/site-packages/numpy/core/include (ver 1.12.1)
--     packages path:               lib/python3.6/site-packages
-- 
--   Python (for build):            /usr/bin/python2.7
-- 
--   Java:
--     ant:                         NO
--     JNI:                         NO
--     Java wrappers:               NO
--     Java tests:                  NO
-- 
--   Matlab:                        Matlab not found or implicitly disabled
-- 
--   Documentation:
--     Doxygen:                     NO
-- 
--   Tests and samples:
--     Tests:                       YES
--     Performance tests:           YES
--     C/C++ Examples:              YES
-- 
--   Install path:                  /usr/local
-- 
--   cvconfig.h is in:              /home/malcolm/external_sources/opencv/build
-- -----------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/malcolm/external_sources/opencv/build
```

I used to work until I set BUILD_opencv_dnn and BUILD_opencv_dnn_modernto false. I'm not sure what I'm missing here

### PR DESCRIPTION
**Pull request by IgWod**
### This pullrequest changes

Following typedefs were moved from the dnn to the core module.:

```
typedef std::vector<size_t> vector_size_t;
typedef std::vector<std::vector<Mat> > vector_vector_Mat;
```

They are used by different module(s) and when dnn is not built they aren't defined and it causes errors.

I am not sure about two things:
* Is types.hpp the right file to move typedefs to? It seems right as they are types definitions.
* Should this fix be applied to 2.4 as well? I'm not sure about it as types definitions are moved between header files and this may have some API compatibility implications (I'm not sure tho)

resolves #9719

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for contribution!

This is python-related types, so `types.hpp` doesn't look no a right place. I believe they should by moved into python module (cv2.cpp?) or into core/misc/python (it currently missing).

> Should this fix be applied to 2.4 as well

No. Codebases are different for bindings handling.

**Comment by IgWod** [comment]
I moved definitions to the python module - cv2.cpp. There are vector definitions already there, so I think it's a right place now.

**Comment by IgWod** [comment]
@alalek It looks like a build failed. Does it have anything to do with my change? I can't see how my change would cause this error - any errors with typedefs should happen on the compile time. In this case the crash is related to the stack.

**Comment by sturkmen72** [comment]
@IgWod the failure is not related with your code.

**Comment by alalek** [comment]
Thank you! Looks good to me :+1:

**Pull request merged**
