### PR TITLE
added Apache 2 license and a separate Copyright file for major contributors

### PR DESCRIPTION
**Pull request by vpisarev**
Text of the license is a verbatim copy of http://www.apache.org/licenses/LICENSE-2.0.txt.

Copyrights are extracted from the current BSD license. 3rd-party copyright clause is separated by empty line to leave some space for more major contributors and yet to keep this 3rd-party copyright clause noticeable.

Apache 2 license should be the default license for all new contributions (and eventually for the whole OpenCV).

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [-] There is reference to original bug report and related work
- [-] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [-] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
Two concurrent license files in a repository doesn't look as good idea. It is too confusing, because there is no plan to provide dual license.

**Comment by asmorkalov** [comment]
@vpisarev @alalek We decided to add notes to Readme document to make license status and process obvious for users and contributors.

**Comment by vpisarev** [comment]
@alalek, in any case, there will be some transition period, even if it lasts for 1 week. But I expect it to be a bit longer. As @asmorkalov said, at first we need to change the template for OpenCV pull requests, so that all new contributions are supplied under Apache 2 license. Next, we publish at opencv.org announcement that we are migrating to Apache 2 license. The next step will be removal of LICENSE and renaming LICENSE.APACHE2 to LICENSE. Because Apache 2 license does not have convenient place to insert copyrights, and because we will unlikely change the license itself often, I've added a separate copyright file.

**Comment by vpisarev** [comment]
following our discussion, I'll resubmit the PR later

**Pull request closed without merging**
