### PR TITLE
Fix `cv::imread` with `OutputArray dst`

### PR DESCRIPTION
**Pull request by cocoa-xu**
This PR is related to https://github.com/opencv/opencv/issues/25694.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by cocoa-xu** [comment]
Hi @sturkmen72, thanks for the reply. I think this should be a bug (or has inconsistent semantic meaning comp)and should for the following reasons:

1. Inconsistent semantic meaning
    
    `OutputArray` in other functions like `cv::blur` suppports empty `cv::Mat` without any pre-allocations.

    ```cpp
    void cv::blur(InputArray src,
        OutputArray dst,
        Size ksize,
        Point anchor = Point(-1,-1),
        int borderType = BORDER_DEFAULT 
    )
    ```

    https://docs.opencv.org/4.x/d4/d86/group__imgproc__filter.html#ga8c45db9afe636703801b0b2e440fce37

    The proposed changes should make it align with other existing functions that accepts an `OutputArray` for storing the result.

2. It should work with empty `cv::Mat`

    In the implementation of `cv::imread`, i.e., `imread_`, empty `cv::Mat` can be corrected handled and initialised there:

    https://github.com/opencv/opencv/blob/337c183b9db4cfd5358b09ec8a610f449e3b8e00/modules/imgcodecs/src/loadsave.cpp#L460-L463

    This makes the current version to silently load, decode an image and discard the results. It would not only waste CPU time but also cause confusions and inconsistencies.

3. Unclear requirements
    
    In the inline docs, it mentions that the *img parameter **can be** pre-allocated*, which IMHO suggests that it can also work with empty `cv::Mat`.

4. Fail with no indications

    Furthermore, even if we really don't want it to work with any empty `cv::Mat`, and say that the pre-allocation is a **must**, then I'm expected to see an exception or assertion in the code instead of silently failing.

    ```cpp
    void imread( const String& filename, OutputArray dst, int flags )
    {
        CV_TRACE_FUNCTION();

        Mat img = dst.getMat();
        CV_Assert( !img.empty() );

        /// load the data
        imread_(filename, flags, img);
    }
    ```

**Comment by sturkmen72** [comment]
@cocoa-xu   i completely agree with you. in addition the function should return an int value ( zero for All is OK or a failure code ). this is a new addition maybe still it is not too late to change API. anyway #24415 is the original addition PR.

**Comment by cocoa-xu** [comment]
> in addition the function should return an int value ( zero for All is OK or a failure code ). this is a new addition maybe still it is not too late to change API. 

OK it's done now. It will now forward the result boolean value from `imread_` to the caller. I chose bool because that's all the information we can get from `imread_`. 

And as there's no other calls can potentially fail inside this function, I think it should be okay. But please don't hesitate to let me know if we should use int instead. :)

**Comment by sturkmen72** [comment]
core developers decide. My suggestion is good in that it is open to development in the future.

**Comment by sturkmen72** [comment]
i am just a contributor. take it in account.

**Comment by mshabunin** [comment]
The root cause of this problem is wrong handling of `OutputArray`. 
```.cpp
void foo(OutputArray res)
{
    Mat m = res.getMat(); // either Mat object wrapped by "res" or temporary Mat object
    m.create(...); // does not affect "res" or original object
}
```
To resolve this issue we should call `OutputArray::create` and then `getMat` instead of `getMat` and `Mat::create`.

**Comment by mshabunin** [comment]
@cocoa-xu , please check whether #25703 resolves your issue.

**Pull request closed without merging**
