### PR TITLE
Loadknearest

### PR DESCRIPTION
**Pull request by LaurentBerger**
Add Ptr<KNearest> KNearest::load and python binding

### CODE REVIEW

**Comment by LaurentBerger** [comment]
@alalek about test do you mean only insert[ at line](https://github.com/opencv/opencv/blob/master/modules/ml/test/test_save_load.cpp#L191) 
```
        if (modelName == CV_KNEAREST)
            model = Algorithm::load<KNearest>(filename);

```
and there is no test for [LR ](https://docs.opencv.org/master/d6/df9/classcv_1_1ml_1_1LogisticRegression.html#af3a20a4bc0f92ca2c5c1a2e46713b2f0)and [EM ](https://docs.opencv.org/master/d1/dfb/classcv_1_1ml_1_1EM.html#a90eec814e087b4d8c3ff9e92f8069f6a) but functions exist.

did I understand correctly?

**Comment by alalek** [comment]
I mean python test at first.
Please rebase on the latest 3.4 branch (including #14078) and add test into [modules/ml/misc/python/test](https://github.com/opencv/opencv/tree/3.4/modules/ml/misc/python/test).

**Comment by alalek** [comment]
@LaurentBerger I rebased commit onto 3.4 branch. Please fetch changes from your 'opencv' fork.

**Comment by LaurentBerger** [comment]
Oops I made something wrong PR was merged automatically and closed. I used same branch but a new PR was created

**Pull request closed without merging**
