### PR TITLE
32bit rgb bmp file should not copy data as rgba

### PR DESCRIPTION
**Pull request by Harvey-Huang**
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/927

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
> wants to merge 2,475 commits

needs to **force** push to the branch `32bit_rgb`

**Comment by Harvey-Huang** [comment]
I need use png image to convert, but I check in my PC, this is the smallest image.

**Comment by Harvey-Huang** [comment]
oh, sorry! I mixed up.

**Comment by Harvey-Huang** [comment]
done!

**Pull request merged**
