### PR TITLE
Delete lena.jpg and any use of it from the JS tutorials

### PR DESCRIPTION
**Pull request by arobase-che**
### Pull Request Readiness Checklist

From the discussion of #25635.
Other references: #17461 #17713  #17714 

For now, it only removes the Lena image from the JS tutorial.
Why only there ? Because it's easy and have more impact of the public image of OpenCV.

Every image I added came from the Kodak images set (often  named Kodim) which is widely used in research papers.
I resized every image to be 400x400.
The dataset is available here: https://r0k.us/graphics/kodak/

The credit doesn't explicitly express the images are released for  for unrestricted use but there are widely used already, even in the OpenCV extra repository. 

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [-] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [-] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by opencv-alalek** [comment]
Please add detail into PR's description about the source and the license of added images.

**Review by dkurt — CHANGES_REQUESTED** [review]
There are already existing images across OpenCV folders. Please choose between existing instead of adding new ones.

**Comment by arobase-che** [comment]
I'm sorry, I'm a little busy at the moment. Will add more information and use OpenCV images as soon as I can.

**Comment by arobase-che** [comment]
Ok, I edited the PR and the images metadata to add the source of the images.

To make it easier to review, here is a comparison side by side of the differences.

adaptive_threshold_diff
affine_transform_diff
bilateral_filter_diff
convert_color_diff
convex_hull_diff
equalize_histogram_diff
face_detection_diff
gaussian_blur_diff
get_affine_transform_diff
image_approxPolyDP_diff
image_area_diff
image_bitwise_diff
image_blur_diff
image_canny_diff
image_CLAHE_diff
image_contours_diff
image_DFT_diff
image_filter_diff
image_GrabCut_diff
image_histogram_diff
image_InRange_diff
image_laplacian_diff
image_moments_diff
image_padding_diff
image_perimeter_diff
image_PyrDown_diff
image_PyrUp_diff
image_read_and_show_diff
image_resize_diff
image_ROI_diff
image_sobel_diff
image_threshold_diff
image_transpose_diff
intelligent_scissors_diff
median_blur_diff

This one is a little tricky. It didn't work with Lena on the first model.
object_detection_diff
perspectiv_transform_diff
rotate_transform_diff
style_transfer_diff
template_match_diff

About using already used images. I'm looking for images so. I can't find ones in the `doc` directory that fit the need, especially the face recognition example.
Otherwise, `apple.jpg` and `orange.jpg` are OK but not really good.
In the directory `samples` I found:
 - [leuvenA.jpg](https://github.com/opencv/opencv/blob/1fa96b161ff2525f446d829db06b6eb59850cdc4/samples/data/leuvenA.jpg)
 - [starry_night.jpg](https://github.com/opencv/opencv/blob/1fa96b161ff2525f446d829db06b6eb59850cdc4/samples/data/starry_night.jpg)
 - [board.jpg](https://github.com/opencv/opencv/blob/1fa96b161ff2525f446d829db06b6eb59850cdc4/samples/data/board.jpg)
 - [messi5.jpg](https://github.com/opencv/opencv/blob/1fa96b161ff2525f446d829db06b6eb59850cdc4/samples/data/messi5.jpg)
 - [butterfly.jpg](https://github.com/opencv/opencv/blob/1fa96b161ff2525f446d829db06b6eb59850cdc4/samples/data/butterfly.jpg)
 
 But none is good for the face detection example. Even [group1](https://github.com/opencv/opencv/blob/1fa96b161ff2525f446d829db06b6eb59850cdc4/samples/winrt/FaceDetection/FaceDetection/Assets/group1.jpg) and [group3](https://github.com/opencv/opencv/blob/1fa96b161ff2525f446d829db06b6eb59850cdc4/samples/winrt/FaceDetection/FaceDetection/Assets/group3.jpg) (which I guess use something butter to detect faces).
 
 
 From the opencv_extra repository.
 I found those images that are interesting:
  - [02.png](https://github.com/opencv/opencv_extra/blob/4.x/testdata/cv/ximgproc/sources/02.png)
  - [aloeR.png](https://github.com/opencv/opencv_extra/blob/4.x/testdata/gpu/perf/aloeR.png)
  - [reference.png](https://github.com/opencv/opencv_extra/blob/4.x/testdata/cv/cloning/color_change/reference.png)
  - [memorial4.png](https://github.com/opencv/opencv_extra/blob/4.x/testdata/cv/hdr/exposures/memorial04.png)
  - [statue.png](https://github.com/opencv/opencv_extra/blob/4.x/testdata/cv/edgefilter/statue.png)
  - [test2.png](https://github.com/opencv/opencv_extra/blob/4.x/testdata/cv/npr/test2.png)
  - [test3.png](https://github.com/opencv/opencv_extra/blob/4.x/testdata/cv/npr/test3.png)
  - [4_barcodes.jpg](https://github.com/opencv/opencv_extra/blob/4.x/testdata/cv/barcode/multiple/4_barcodes.jpg)
  - [baboon.png](https://github.com/opencv/opencv_extra/blob/4.x/testdata/cv/shared/baboon.png)
  - [kodim23.png](https://github.com/opencv/opencv_extra/blob/4.x/testdata/cv/edgefilter/kodim23.png)
  
Note that there is 2 images from the Kodim (statue.png and kodim23.png).
Also, statue.png works for face detection but only one eye is visible (and detected), I didn' know if it's a problem or not.
  
Please help me to choose images if the ones I have chosen are not good. If I have to take only one image, I think we can choose statue.png.

**Comment by arobase-che** [comment]
Hello, can I have an update on the review here please?
Can I help in any way?

If the problem is to chose the images, if I take:
 - statue.png
 - baboon.png
 - kodim23.png
 
 Is it ok? The goal of adding images was to keep the same dimension as the original Lena 400x400 cropped version.
 Should I crop them too? I need to crop at least one image for the "Template match example". :)

**Comment by dkurt** [comment]
Problem in adding new images with unknown license - reuse existing images. There are a lot of them in OpenCV source tree.

**Comment by sturkmen72** [comment]
imho you will remove one image and add several images. why not find one proper image to replace lena.jpg

**Comment by asmorkalov** [comment]
Hello @arobase-che . OpenCV core team discussed the issue with Lena image and decided to not touch existing code for now, but update test data and images together with the code update. It's decided to make performance numbers comparable across releases and reduce binary file changes. See https://github.com/opencv/opencv/wiki/FAQ#social.

**Pull request closed without merging**
