### PR TITLE
Update libpng to 1.6.24

### PR DESCRIPTION
**Pull request by kurenai**
### This pullrequest changes

Update libpng to 1.6.24
Enable SSE optimization

### CODE REVIEW

**Comment by PhilLab** [comment]
Thanks. There are a lot of whitespace-only changes making the diff unnecessarily hard to read. What is the reason behind this?

**Comment by kurenai** [comment]
@PhilLab 
The [source](http://download.sourceforge.net/libpng/libpng-1.6.24.tar.gz) is copied directly from official libpng website.

**Comment by PhilLab** [comment]
@kurenai seems legit :smile:

**Comment by alalek** [comment]
Looks good to me!
Builds with forced 3rdparty libpng are fine: [Linux](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/7276), [Windows](http://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/6835), [Mac](http://pullrequest.opencv.org/buildbot/builders/precommit_macosx/builds/6596).
:+1:

**Pull request merged**
