### PR TITLE
DNN: fuse conv+naryEletwise on CUDA backend.

### PR DESCRIPTION
**Pull request by zihaomu**
Related issue: https://github.com/opencv/opencv/issues/23234.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by zihaomu** [comment]
Hi @WanliZhong, please take a look.

**Review by WanliZhong — APPROVED** [review]
👍Currently, the inference time of palm detection improved from `60ms` to `55.03ms`.

**Comment by Abdurrahheem** [comment]
@zihaomu  #24721 issue is related this this PR. Particularly to this [line](https://github.com/opencv/opencv/blob/283407e1ff6076a508302a68d350704299b46e6b/modules/dnn/src/net_impl_fuse.cpp#L740C78-L740C78). It causes yolov8 CUDA backend to predict wrong outputs. Where are relevant issues https://github.com/opencv/opencv/issues/24606 https://github.com/opencv/opencv/issues/23977 https://github.com/opencv/opencv/issues/24635.

**Comment by fengyuentau** [comment]
@Abdurrahheem I was also looking at this problem. Have you came up with a solution yet? If yes, I will re-open https://github.com/opencv/opencv/issues/24606 and assigned to you.

**Pull request merged**
