### PR TITLE
Fix for missing check of result from Hough circles and lines

### LINKED ISSUE #6621: Python examples for Hough lines and circles break when no segments found
I've noticed that in the C++ examples there is a check for the result that the Hough lines and Hough circles functions return whether there are actually any segments (lines or circles) found. In Python this check is missing which leads to a crash of `houghlines.py` and `houghcircles.py` when no lines/circles are found.

### PR DESCRIPTION
**Pull request by aleksandaratanasov**
resolves #6621

### What does this PR change?
Added simple check which compares the result from both Hough functions (for circles and lines) to `None` and if it is unequal then the iteration over the list with circles/lines takes place and these are added to the image.

### CODE REVIEW

**Comment by savuor** [comment]
@aleksandaratanasov please remove trailing spaces at `samples/python/houghcircles.py:32` so that your PR will pass docs check and we can merge it

**Comment by aleksandaratanasov** [comment]
Hi savuor. Quick question - do I have to create a new pull request with the changes? Sorry for the late reply.

**Comment by aleksandaratanasov** [comment]
Nvm it can be also done with the online editor.

**Comment by aleksandaratanasov** [comment]
Fixed incorrect call for `imshow()` in case no lines/circles have been found.

**Comment by alalek** [comment]
Looks good to me.
Please squash all commits into one (and remove useless merge commit).

**Comment by vpisarev** [comment]
this PR will be reopened because of CI issues

**Pull request closed without merging**
