### PR TITLE
named enum's added for videoio  resolves #6746

### LINKED ISSUE #6746: Naming all enumerations in videoio.hpp
- **OpenCV version**: 3.x
- **Which part**: [videoio.hpp](https://github.com/Itseez/opencv/blob/master/modules/videoio/include/opencv2/videoio.hpp)
- **Actual behaviour**: All enumerations in videoio.hpp are unnamed

### Expected behaviour
Starting from @mshabunin suggestion:

> Naming all enumerations in videoio.hpp to make it possible to refer them from corresponding function documentation. See documentation for cv::imread for example.

### Additional description

Because once a name is assigned it will be hard/impossible to change later, please find here some request for comment:

2. Which naming convention should be used ?
3. Are there enumerations that might/should be merged ? 
4. May be some enumerations should live in their own module like OPENNI_, PVAPI_, XI_, and so on
5. May be enumerations should have better organization or stronger type like `MEDIA_API`, `MEDIA_PROPERTIES` (class and inheritance ?, C++11 typed enumeration ?,...)
6. Should functions that use enumerations be declared with enumeration name as arg type instead of simple int  e.g. `VideoCapture::get(MEDIA_PROPERTIES propId)` or `VideoCapture::open( String filename, MEDIA_API apiPreference )` ?
7. Meaning of enumerator value is mixed. It could be an ID, a flag, a mask of bits. Last cases, changing the enumerator value will break the code. Some kind of warning should exist here: e.g `CAP_api` is used with %10 to select the api, or OpenNI shortcuts or `CAP_PVAPI_DECIMATION_2OUTOF8`,...
8. Shall we forget all about and try to derive enumeration name from common part of enumerators e.g. `enum CAP_PROP {CAP_PROP_POS_MSEC=0, CAP_PROP_POS_FRAMES=1,...}`

### PR DESCRIPTION
**Pull request by souch55**

### CODE REVIEW

**Comment by PkLab** [comment]
@souch55 Just some tips
1. In your PR description use the hashtag \#the_issue_num to get a link between them
2. You have "Unsuccessful builds" from buildbot. If any builder are failed sure your PR can't be merged. Check details... mainly you have "Warnings make doxygen" because of  `copydoc cv::CvaptureProperties::...`

**Comment by vpisarev** [comment]
@mshabunin, looks like we have 2 similar PRs, this one and https://github.com/opencv/opencv/pull/6995. Could you please check them out?

**Comment by souch55** [comment]
Hi vpisarev/mshabunin requesting you to merge my changes for named enums after review, i have followed  the CamelCase  format and also added the names to the enums as references by documentation,i have avoided c++11 enum classes type format,instead have used plural forms for consistency.

**Comment by mshabunin** [comment]
@souch55 , thank you for effort, but I tend to accept PR #6995 with similar change, it is one step closer to the merge stage than this PR.

**Pull request closed without merging**
