### PR TITLE
Support for super-fisheye lenses (i.e., opening angles above 180 degr…

### PR DESCRIPTION
**Pull request by vpisarev**
This PR adds support for super-fisheye lenses (i.e., lenses with opening angles above 180 degrees).

Essentially, the idea is to compute `theta` as `atan2(sqrt(x*x+y*y),z)` (where `[x,y,z]` is the point relative to the camera, with z pointing forward).

It is downward-compatible for points in front of the camera. Points behind the camera (i.e., negative z coordinates) gave bogus results previously and now only fail if they are exactly behind the camera.
The computation of the Jacobians should be slightly faster and more accurate, especially for z close to zero.

Other functions in the fisheye module would need to be ported as well and the documentation would also need to be updated. But before I proceed, are there any opinions on this?

### CODE REVIEW

**Comment by chhtz** [comment]
I made some changes to `cv::internal::InitExtrinsics` which apparently make `test_calib3d` fail now. This is because there is a comparison against a pre-computed calibration result with very little tolerance (and I somehow suspect that the previous result was just what was computed by the calibration routine itself).
I'm not claiming that the "new calibration" is more accurate, but I'd say that testing against hard-coded values is probably not the best unit-test for this.
Furthermore, I'm more than happy to make my recent changes optional (I do need this for super-fisheyes, however).

Other than that, I'd actually like to have some methods exposed to the public API, e.g. `calibrateExtrinsics` (or `initExtrinsics` as well).
And I think, the actual calibration routine should not interleave calibrating the intrinsics and extrinsics, but optimize them simultaneously (which is what Levenberg-Marquardt is made for).

**Comment by chhtz** [comment]
I made some "work in progress" changes. I'll clean this up, if I get any feedback

**Comment by chhtz** [comment]
Hi, any updates on this?
Would this PR generally be acceptable (after making the unit test pass again and cleaning up ...)?

**Comment by paroj** [comment]
as the change improves functionality while retaining backwards compatibility, I see no reason why it should not be acceptable.

Perhaps you could add a reference [on this][1] to further justify the changes.

[1]: https://users.aalto.fi/~kannalj1/publications/tpami2006.pdf

**Comment by sovrasov** [comment]
@chhtz we will discuss your PR soon.

**Comment by sovrasov** [comment]
@chhtz PR can be accepted, but more strong backward-compatibility checks are needed.
Also test for new functionality should be added.

**Comment by chhtz** [comment]
Thanks for the responses. I'll be busy for the rest of this week, but I'll try to work on this again next week.

**Comment by mounikakv1** [comment]
how to run that file

**Comment by asmorkalov** [comment]
The PR is closed as diverged from upstream branch and required extra development. Super-fisheye cameras support is tracked by https://github.com/opencv/opencv/issues/15923

**Pull request closed without merging**
