### PR TITLE
(5.x) Merge 4.x

### PR DESCRIPTION
**Pull request by asmorkalov**
Extra: https://github.com/opencv/opencv_extra/pull/1079
Conrib: https://github.com/opencv/opencv_contrib/pull/3538

#18498 from firebladed:patch-1
#22798 from lamm45:distransform-large
#23540 from cudawarped:add_CAP_PROP_CODEC_FOURCC
#23647 from AleksandrPanov:fix_charuco_board_detect
#23664 from asmorkalov:as/solveLP_infeasible
#23692 from asmorkalov:as/ffmpeg_fps_3.4
#23702 from dkurt:py_rotated_rect
#23724 from dkurt:java_without_ant
#23729 from asmorkalov:as/create_samples_overflow
#23754 from dkurt:remap_linear_transparent
#23768 from opencv-pushbot:gitee/alalek/issue_23156
#23796 from TolyaTalamanov:at/align-ie-backend-with-latest-openvino
#23799 from TolyaTalamanov:at/ov20-backend-implement-missing-kernels
#23801 from VadimLevin:dev/vlevin/python-stubs-api-refinement
#23809 from VadimLevin:dev/vlevin/re-export-stubs-submodules
#23812 from dizcza:tbb
#23813 from VadimLevin:dev/vlevin/runtime-typing-module
#23815 from LaurentBerger:CAP_IMAGES
#23816 from VadimLevin:dev/vlevin/export-all-caps-enum-constants
#23819 from asmorkalov:as/objdetect_no_dnn
#23821 from asmorkalov:as/python_types_extra_imports
#23825 from ulvido:4.x
#23829 from fengyuentau:fixes4orbbec
#23831 from asmorkalov:update_version_3.4.20-pre
#23832 from asmorkalov:as/reshape_docs
#23833 from asmorkalov:update_version_4.8.0-pre
#23835 from VadimLevin:dev/vlevin/fix-ast-nodes-required-usage-imports
#23838 from VadimLevin:dev/vlevin/numpy-array-typing
#23841 from asmorkalov:as/ffmpeg_update_3.4
#23842 from opencv-pushbot:gitee/alalek/fix_static_build_with_gapi_openvino
#23843 from TolyaTalamanov:at/fix-missing-opaque-kind-for-kernel
#23846 from asmorkalov:as/ffmpeg_update_4.x
#23848 from AleksandrPanov:fix_detectDiamonds_api
#23853 from fengyuentau:disable_fp16_warning
#23855 from thekpaul:3.4_patched
#23859 from TolyaTalamanov:at/ov-backend-core-wa
#23860 from fengyuentau:fix_overflow_sigmoid_v3.4
#23863 from asmorkalov:as/calibrate_py_rework
#23881 from asmorkalov:as/fast_math_nan
#23884 from TolyaTalamanov:at/fix-async-infer-ov-backend
#23885 from hanliutong:UniversalIntrinsicRewriter
#23892 from vrabaud:compile_fix
#23896 from mshabunin:test-cap-images
#23900 from kai-waang:fixing-typo
#23901 from kai-waang:remove-duplicated
#23909 from asmorkalov:as/exclude_3.4
#23914 from AleksandrPanov:update_aruco_byteList_docs
#23918 from kallaballa:custom_package_name
#23920 from loongson-zn:4.x
#23922 from vrabaud:imgwarp
#23924 from ocpalo:patch-2
#23927 from Avasam:partially-unknown-mat
#23928 from Avasam:Add-missing-properties-to-error-class
#23931 from asmorkalov:as/drawing_overflow
#23936 from SaltFish-T:4.x
#23938 from mshabunin/fix-warnings-gcc
#23940 from mshabunin:fix-cap-images
#23943 from vrabaud:avif_tsan
#23944 from mshabunin:test-v4l2
#23952 from zihaomu:fix_depth_conv_5x5
#23954 from VadimLevin:dev/vlevin/matrix-type-constants-stubs
#23955 from VadimLevin:dev/vlevin/overload-presence-check-fix
#23956 from VadimLevin:dev/vlevin/recursive-re-export-submodules
#23958 from VadimLevin:dev/vlevin/friendly-wrong-npy-type-message
#23963 from opencv-pushbot:gitee/alalek/fixup_23842
#23966 from hanliutong:popcount
#23967 from YusukeKameda:4.x
#23968 from mshabunin:doc-env
#23969 from asmorkalov:as/python2_test_fix
#23970 from mshabunin:fix-v4l-test
#23972 from Avasam:partially-unknown-mat
#23973 from mshabunin:riscv-unaligned-access
#23986 from headshog:fix-numtrunc
#23991 from buyuer:4.x
#23999 from asmorkalov:as/opencv_logging
#24001 from legrosbuffle:legrosbuffle-cvround-intrinsic
#24003 from cudawarped:cuda_fix_skip_test_exception
#24004 from dkurt:tflite_new_layers
#24008 from iarspider:patch-1
#24022 from VadimLevin:dev/vlevin/python-typing-cuda
#24023 from VadimLevin:dev/vlevin/python-typing-magic-constants
#24024 from TolyaTalamanov:at/add-onnx-openvino-execution-provider
#24026 from VadimLevin:dev/vlevin/python-numpy-writeable-flag-check
#24028 from VadimLevin:dev/vlevin/fix-flann-python-bindings
#24029 from VadimLevin:dev/vlevin/python-add-cuda-stream-to-simple-types
#24032 from vrabaud:ubsan
#24040 from asmorkalov:as/cuda_dnn_eps_fix
#24042 from vrabaud:circle
#24043 from zixianweei:use-vaddq_f32-on-arm64
#24045 from TolyaTalamanov:at/add-onnx-directml-execution-provider
#24046 from VadimLevin:dev/vlevin/add-cuda-gpu-mat-to-big-types
#24054 from mwangistan:4.x
#24055 from asmorkalov:as/msvc_cxx20_warning_disable
#24056 from dkurt:eltwise_prelu
#24061 from VadimLevin:dev/vlevin/python-typing-highgui-refinement
#24062 from VadimLevin:dev/vlevin/python-typing-redirect-error
#24066 from VadimLevin:dev/vlevin/python-typing-register-dnn-layer

~~#23971 from asmorkalov:as/ci-ubuntu-2204~~

Previous "Merge 4.x": #23979

### CODE REVIEW

**Review by opencv-alalek — COMMENTED** [review]
PR 22371 is not propagated here to 5.x, so it should be properly noted in the description with PRs list like:
~~#23971 from asmorkalov:as/ci-ubuntu-2204~~
and added label `"port to 5.x is needed"` for such PR.

`satysfying` typo is not ported from #23900

To avoid such mistakes 3 steps strategy "merge partially", "force manual merge", "merge to accept manual changes" should be done in a short period of time (to avoid intermediate PRs). Current pipeline has 6 weeks timeline gap.

**Comment by asmorkalov** [comment]
Following changes in CI: https://github.com/opencv/ci-gha-workflow/pull/110

**Comment by asmorkalov** [comment]
@opencv-alalek I fixed missing typos. Ubuntu 22.04 pipelines are ready. I'll add them to Actions, when the PR is merged.

**Comment by mshabunin** [comment]
:face_exhaling: Look like I'm late with the MSVC warning fix: #24087 :slightly_smiling_face:

**Pull request merged**
