### PR TITLE
Add getMatInblob function

### PR DESCRIPTION
**Pull request by LaurentBerger**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work https://github.com/opencv/opencv/issues/24158
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@LaurentBerger Thanks for the contribution! Could you provide some use-case for the new function?

**Comment by asmorkalov** [comment]
@LaurentBerger Thanks  for the patch. The PR was discussed on OpenCV core team meeting and the team decided to reject the patch. Reasons:
- The No strong definition of API. There is no use-case for the function.
- The same may be done without extra function.

**Comment by LaurentBerger** [comment]
> * There is no use-case for the function.

there is this https://github.com/opencv/opencv/issues/24158
Where is use case of [imagesfromblob](https://github.com/search?q=repo%3Aopencv%2Fopencv%20imagesFromBlob&type=code)?

**Comment by opencv-alalek** [comment]
@LaurentBerger At first, thank you for all your contributions to this project!

> imagesfromblob

This is just an another example of bad designed function:
- bad name - according to implementation it should be `extractImagesFromNCWHBlob()`.
- function is still not used (so it is not needed at all, no use-case)
- there is no way to provide generic `well specified/defined/clear` API for that (too many options are here as "blob" is anything like ND-tensor)
- Now, OpenCV API has `cv::transposeND()` to perform similar operations. With help of `.reshape()` + ROI you could get the same result. It is better to provide "basic" operations to keep code clean (and have clean OpenCV API).

So, we need to avoid of repeating of such experience.

Adding function which returns "reference" (not a copy) on the data is a problem with bindings. E.g. in Python code use numpy directly instead.

**Pull request closed without merging**
