### PR TITLE
Improvement of sequential connected components Wu's algorithm and pro…

### LINKED ISSUE #7270: Multithreaded connected component labeling implementation
This is an RFC for the implementation of a multithreaded version of the connected component labeling algorithm. 

Such algorithms have appeared in research papers since a few years ago. A common theme in these approaches is to divide the image into blocks (tiles or strips), and then:

1. Perform labeling within each block, in parallel; 
1. Let the main (caller) thread process the equivalence labeling of "seams" between blocks;
1. Update the labeling in each block to the final labeling, in parallel.    

The second step is single-threaded. As a result there is a synchronization barrier before and after the second step.

I ask this question here instead of OpenCV Answers because it is not a beginner question, and I believe this is a feature that will eventually be implemented in (contributed to) OpenCV. A second reason I ask this is because I have implemented a proprietary version of it for my employer. I have secured the permissions to make a separate implementation for OpenCV provided that the implementation details in the contributed version can be fully traced to research work that has already been published.

I am aware of the existing connected component labeling implementation in OpenCV and has studied the algorithm. However, it is too early for me to say whether I will be able to keep the best of both implementations.

I haven't started working on this second implementation yet; so I would like to solicit some feedback about the desirability of this feature before I start. Please feel free to ask questions.

I understand that performance benchmarks will help make an informed decision. Please feel free to suggest performance benchmark scenarios that I should test for.

### LINKED ISSUE #7607: LabelingGrana: Incorrect upper bound for the number of components
##### System information (version)

- OpenCV => master
- Operating System / Platform => OSX 10.12.1
- Compiler => Apple LLVM version 8.0.0 (clang-800.0.42.1)

##### Detailed description

New implemented algorithm LablelingGrana has incorrect upper bound for the number of components. And now it's default algorithm for this common case of usage:

   ```.cpp
cv::connectedComponents(image, labels);
   ```

This cause an BAD_ACCESS issue.

##### Steps to reproduce

Here is an example code that may reproduce an issue.
Here number of components is ROWS * COLS / 3,
But in [implementation](https://github.com/sokian/opencv/blob/master/modules/imgproc/src/connectedcomponents.cpp#L351-L353) it's ROWS * COLS / 4.

   ```.cpp
#include <iostream>
#include <opencv2/imgproc.hpp>

const int ROWS = 1;
const int COLS = 500;
int sum = 0;

void testConnectedComponents() {
    cv::Mat img(cv::Size(COLS, ROWS), CV_8U);
    for (int i = 0; i < COLS * ROWS; i += 3) {
        img.data[i] = 1;
    }
    cv::Mat lab;
    sum += cv::connectedComponents(img, lab);
}

int main() {
    int t = 1000000;
    for (int i = 0; i < t; ++i) {
        testConnectedComponents();
    }
    std::cerr << "Sum: " << sum << std::endl;
    return 0;
}

   ```

##### Solution

And, of course, it can be replaced by upper bound from LabelingWu algorithm
[link to commit](https://github.com/sokian/opencv/commit/b2a54ea614916becefdb02ae555401a842eb0df5)

### PR DESCRIPTION
**Pull request by MicheleCancilla**
### This pullrequest changes

With this Pull Request we provide the following improvements on “cv::connectedComponents” and on “cv::connectedComponentsWithStats” functions: 
<ul>
<li>We improve the speed of Wu’s algorithm (sequential version) providing a better implementation, both for 4 and 8-way connectivity.</li>
<li>We provide a parallel CPU implementation of both Wu and Grana’s algorithms that are the ones currently included in the OpenCV library. These parallel versions are automatically chose by the functions when the TBB variable is defined. The performance are shown in the charts below where acronyms are used to distinguish the different implementation/version of the algorithms. An explanation of the datasets used and how the tests were performed can be found <a href="https://github.com/prittt/YACCLAB/blob/master/README.md">here</a>. </li>
</ul>
To conclude, this pull request reply to RFC #7270 and take into account the issue #7607 providing the same solution proposed by @sokian with pull request #7608 that is open yet. 
<br/><br/>
<b>SAUF_OLD:</b> is the old implementation of the sequential version of the Wu’s algorithm;
<br/>
<b>SAUF_NEW:</b> is the implementation of the sequential version of the Wu’s algorithm proposed with this pull request;
<br/>
<b>SAUF_PAR:</b> is the parallel version of the Wu’s algorithm introduced by this pull request; 
<br/>
<b>BBDT_SEQ:</b> is the current sequential version of the Grana’s algorithm (currently included in the OpenCV);
<br/>
<b>BBDT_PAR:</b> is the parallel version of the Grana’s algorithm introduced by this pull request;
<br/>
<br/>
<table border="0">
<tr><p align="center">Comparison of  Wu’s algorithms with 8-way connectivity (without computing statistics)</p></tr>
<tr>
 <td>3DPeSfigure1</td>
 <td>Medicalfigure2</td>
 <td>Tobacco800figure3</td>
</tr>
</table><br/>
<table border="0">
<tr><p align="center">Comparison of  Wu’s algorithms with 4-way connectivity (without computing statistics)</p></tr>
<tr>
 <td>3DPeSfigure1</td>
 <td>Medicalfigure2</td>
 <td>Tobacco800figure3</td>
</tr>
</table><br/>
<table border="0">
<tr><p align="center">Comparison of  Grana’s algorithms without computing statistics</p></tr>
<tr>
 <td>3DPeSfigure1</td>
 <td>Medicalfigure2</td>
 <td>Tobacco800figure3</td>
</tr>
</table><br/>
<table border="0">
<tr><p align="center">Comparison of  Grana’s algorithms with statistics computation</p></tr>
<tr>
 <td>3DPeSfigure1</td>
 <td>Medicalfigure2</td>
 <td>Tobacco800figure3</td>
</tr>
</table>

### Contributors:
Michele Cancilla @MicheleCancilla (cancilla.michele[at]gmail.com)
Federico Bolelli @prittt (federico.bolelli[at]unimore.it)
Costantino Grana @CostantinoGrana (costantino.grana[at]unimore.it)

### CODE REVIEW

**Comment by mshabunin** [comment]
Please, restore text indentation on lines 54-3957: it was 4 spaces, but you've changed it to 8 spaces.

**Comment by mshabunin** [comment]
Is it possible to change TBB to `cv::parallel_for_`? It has different backends (including TBB) and will work on more platforms.

**Comment by prittt** [comment]
Hi @mshabunin, 

"Please, restore text indentation on lines 54-3957: it was 4 spaces, but you've changed it to 8 spaces."
Sure!!

"Is it possible to change TBB to cv::parallel_for_? It has different backends (including TBB) and will work on more platforms."
We are trying to do that and we are making some other performance tests to see the differences.

**Comment by MicheleCancilla** [comment]
Hi @mshabunin. You were right: we reverted the parallel code to `cv::parallel_for_` and now it is obviously more flexible (tests revealed that also parallel frameworks different from TBB improve performances pretty well). We fixed the indentation issue and wrote down some notes in the documentation.

**Comment by alalek** [comment]
```
'_P' => 'P_'
```

To avoid conflicts with reserved variable names (started with underscore).

**Comment by mschoeneck** [comment]
I tested your last commit a bit. I noticed, that when I use CV_16U label type, connectedComponents returns only the labels from first thread and the label image is broken. This seems to occure for both, GRANA and WU as well as for 4 and 8 connected.
With CV_32S it seems to be OK.
When I set number of threads to 1 the CV_16U output also returns correct number of found labels and label image looks correct.

**Comment by MicheleCancilla** [comment]
Hello @mschoeneck, 
you are right. We try to explain the problem in the easiest possible way.

The CV_16U label type can be used only when the number of labels in the image can be fit a 16bit data type (i.e 65536). The problem with the parallel version of the algorithms (which divide the image to label in stripes and compute labeling on each stripe in parallel) is that each thread must start labeling from the maximum possible value reachable by the previous thread. This is necessary in order to avoid collision accesses to equivalence label array. 

For example (considering an image with 8 rows and 2 thread): the first thread works with rows from 0 to 3 [0;3] and starts from label 1 (background is 0). The second one works with rows from 4 to 7 [4;7] and starts from maximum label reachable (at least in theory) by thread one incremented by one. So if the maximum label reachable from thread one is 5 thread two starts labeling from label 6. 

Then, if you run connectedComponents function with CV_16U label type on an image that actually have only two labels, but the maximum number of different labels that image could contain is greater than 65536, parallel labeling will fail because of its nature.

For this reason we decided to call the parallel connectedComponents only with CV_32S label type.

@mshabunin @alalek The latest push failed under linux with strange errors (error closing /tmp/ccXGh37G.s: No space left on device), it's my fault or was there a problem with the buildbot?

**Comment by alalek** [comment]
> there a problem with the buildbot

These builds are restarted.

**Comment by MicheleCancilla** [comment]
hello, do you have any updates? :smile:

**Comment by MicheleCancilla** [comment]
The last commit includes the following changes/improvements:
1)	Improvement of array of equivalences’ upper bound. The current upper bound in release 3.2.0 is undersized (wrong in some cases) but in the current pull request (as in the pull request REF) we have proposed a new upper bound that is correct but oversized in some cases (i.e. on images with even number of rows and/or cols). With the last commit, we definitely solve the problem (see following figure);
2)	Specialized the first assigned label of each thread for parallel algorithms in 8-way-connectivity;
3)	Fix some wrong comments (authors’ name) in other modules;
immagine

**Comment by vpisarev** [comment]
trying to fix doc builder complains, see #8789

**Pull request closed without merging**
