### PR TITLE
Support of OpenVINO interface libraries

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
<cut/>

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2021.4.0:20.04
build_image:Custom Win=openvino-2021.4.0
build_image:Custom Mac=openvino-2021.4.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

### CODE REVIEW

**Comment by alalek** [comment]
Could you please add link on related OpenVINO PR?

**Comment by ilya-lavrenov** [comment]
> Could you please add link on related OpenVINO PR?

https://github.com/openvinotoolkit/openvino/pull/7419

Here `IE::inference_engine` can be an interface library

**Comment by alalek** [comment]
Moved helper function from root CMakeLists.txt, use `ocv_` prefix, output is 1st argument.

@ilya-lavrenov Please take a look.

**Comment by ilya-lavrenov** [comment]
@alalek I'm OK with the change.

**Review by alalek — APPROVED** [review]

**Pull request merged**
