### PR TITLE
Fixed cv::cuda::orb async calls

### PR DESCRIPTION
**Pull request by mshabunin**
Restored #5777

### CODE REVIEW

**Comment by jet47** [comment]
There are merge conflicts. Please rebase your branch on top of latest master.

**Comment by mshabunin** [comment]
@dtmoodie , please fix merge conflicts.

**Comment by paroj** [comment]
these changes were already merged. see last comment in #5777

**Comment by mshabunin** [comment]
@paroj , thank you!

Merged in PR #6290

**Pull request closed without merging**
