### PR TITLE
StridedSlice from TensorFlow

### PR DESCRIPTION
**Pull request by dkurt**
### This pullrequest changes

resolves https://github.com/opencv/opencv/issues/13720

Add support of [faster_rcnn_nas_coco_2018_01_28](http://download.tensorflow.org/models/object_detection/faster_rcnn_nas_coco_2018_01_28.tar.gz) from TensorFlow.

Known problems:
* Object detection classes are shifted for Faster R-CNN networks (need to fix a sample or list of classes?)
* Faster R-CNN from TensorFlow don't work on random input (need to test on images with no detections). Reason - the first DetectionOutput may have less detections than allocated memory. Possible solution - fill the rest of output blob by zeros. (fixed by https://github.com/opencv/opencv/pull/14552)

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/604

out

```
force_builders=Custom,Custom Win,Custom Mac
buildworker:Custom=linux-1,linux-2,linux-4
docker_image:Custom=ubuntu-openvino-2019r1:16.04
docker_image:Custom Win=openvino-2019r1
docker_image:Custom Mac=openvino-2019r1
```

### CODE REVIEW

**Comment by advanpix** [comment]
Thank you for the great work! When we can see this in "master" branch :)?

**Comment by dkurt** [comment]
@advanpix, I guess this week. Thanks!

**Comment by advanpix** [comment]
I have tested the changes - everything works fine. Thank you very much!

Btw, every time I run my program, I see following diagnostic message:
[ INFO:0] global ...\opencv-master\modules\core\src\ocl.cpp (888) cv::ocl::haveOpenCL Initialize OpenCL runtime...

Any chance this can kind of info-messages can be disabled?

**Comment by dkurt** [comment]
@advanpix, Please take a look at [setLogLevel](https://docs.opencv.org/master/da/db0/namespacecv_1_1utils_1_1logging.html#aa022dd6c6e2d72539cc1e5100bcb378b).

**Comment by advanpix** [comment]
What is default setting for setLogLevel? 
With previous versions of OpenCV (including master) these kind of message were never shown.

**Comment by alalek** [comment]
Default log level is "INFO" for Debug builds. "WARNING" for Release builds.

**Comment by advanpix** [comment]
I use "Release" builds, and this message is still shown. 
Now I use setLogLevel to suppress it, but [INFO] messages were never shown before in "Release". Something is going on with this message.

**Comment by alalek** [comment]
Could you try to set environment variable: `OPENCV_LOG_LEVEL=WARN`?

**Pull request merged**
