### PR TITLE
Update 3rdparty zlib to 1.3

### PR DESCRIPTION
**Pull request by FantasqueX**
The opencv zlib patch is still not merged. So I applied it to zlib-1.3. Since zlib-1.3 didn't modify CMakeLists.txt, opencv's zlib CMakeLists.txt doesn't need to be modified.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch

### CODE REVIEW

**Review by asmorkalov — CHANGES_REQUESTED** [review]
I compared your branch with official zlib 1.3 sources and see some difference in inflate.c.

**Comment by FantasqueX** [comment]
@asmorkalov Hi, thanks for your review. I checked it again. The only difference between my branch and the official zlib-1.3 is 
```patch
@@ -207,7 +207,6 @@
     state->strm = strm;
     state->window = Z_NULL;
     state->mode = HEAD;     /* to pass state test in inflateReset2() */
-    state->check = 1L;      /* 1L is the result of adler32() zero length data */
     ret = inflateReset2(strm, windowBits);
     if (ret != Z_OK) {
         ZFREE(strm, state);
```
As I mentioned above, "The opencv zlib patch is still not merged. So, I applied it to zlib-1.3.". you can check at https://github.com/opencv/opencv/blob/4.x/3rdparty/zlib/patches/20190330-ununitialized-use-state-check.diff

**Comment by asmorkalov** [comment]
Ok, I got your point about the patch. It's not obvious from the PR description.

**Comment by asmorkalov** [comment]
For reference: issue and patch information:
```
    3rdparty(zlib): prevent uninitialized use of state->check
    
    ozz-fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13317
    PR: https://github.com/opencv/opencv/pull/14193
    zlib upstream bug: madler/zlib#245
    Ported fix: https://chromium.googlesource.com/chromium/src/+/ee376c65abdd5afe787bfb63af9f2e82fdc35c2e
```

**Review by asmorkalov — APPROVED** [review]
:+1:

**Pull request merged**
