### PR TITLE
Fix python bindings for setCharucoParameters

### PR DESCRIPTION
**Pull request by siilats**
setcharucoparameters fails in python

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

This hack works meanwhile:
image

### CODE REVIEW

**Comment by dkurt** [comment]
https://github.com/opencv/opencv/blob/12db19c1299cefdea37514bf66d5c24a1c92497c/modules/objdetect/src/aruco/charuco_detector.cpp#L273 should be changed too

**Comment by mostafarohani** [comment]
@dkurt thank you for the reference, and thank you @siilats for the workaround, however I think there is still a bug.

When I do a charuco find markers without using the intrinsics and distortions (i.e. a factory CharucoParamaters) the calibration/poses derived are reasonable but not great.

However when i feed in the ground truth intrinsics/distortions using CharucoParameters, the result is terrible/very wrong.

I have only noticed this because we have upgraded our repo from opencv 4.1 to 4.7; in the old code everything worked completely fine.

**Comment by dkurt** [comment]
@mostafarohani, I've added a test in Python, can you please take a look and if your example is different, please provide a reproducer.

**Review by AleksandrPanov — APPROVED** [review]
It is possible to add more clear names instead of `test_charuco_no_segfault_1`, `test_charuco_no_segfault_2`. The tests are small and there are comments, so it's ok for me.

**Comment by dkurt** [comment]
@AleksandrPanov, sure, done!

**Pull request merged**
