### PR TITLE
Update to initInverseRectificationMap()

### PR DESCRIPTION
**Pull request by IanMaquignaz**
Updates to initInverseRectificationMap(). Includes update to documentation and fixes to issues identified in #20165

### Pull Request Readiness Checklist
- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for update!
Please take a look on whitespace issues (from default/"Docs" builder).

Also you may want to install git pre-commit hook to catch them early: https://github.com/opencv/opencv/wiki/How_to_contribute#q3-i-was-asked-to-remove-whitespace-issues-how-can-i-do-that

**Review by alalek — APPROVED** [review]
Thank you :+1:

**Comment by IanMaquignaz** [comment]
@alalek I haven't added the new unit test... that's why this was still a work in progress....

Guess I need a new PR to add that?

**Comment by alalek** [comment]
This PR is merged to reduce testing infrastructure pressure (tests are disabled by this patch).

Yes, please create new PR with updated tests.

**Pull request merged**
