### PR TITLE
added CascadeClassifier tutorial copy - java translated

### PR DESCRIPTION
**Pull request by siddharthTyagi**
### This pullrequest changes

Added the java version of CascadeClassifier (cpp) tutorial.

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
Some remarks

1. Buildbot is crashing due to the fact that there are all tab identations in the file. Replace them by 4 spaces to delete those issues.
2. @mshabunin I remember a pull request enabling multiple language buttons in a single tutorial. Wouldn't this be the ideal case to implement this with? Just not able to retrieve/locate it anywhere.

**Comment by siddharthTyagi** [comment]
@StevenPuttemans, I have converted tabs to space. Funny as it has been adopted almost everywhere - the default eclipse format ignores it.
About the multiple languages - Are you referring to human language or programming language?

**Comment by StevenPuttemans** [comment]
I mean programming language. There is this option for a single tutorial to include c++, java, c, python tabs at each code position. Just not sure if it is already live or not.

**Comment by mshabunin** [comment]
Please take a look at the PR #8043 for an example of multi-lang tutorial.

**Comment by vpisarev** [comment]
ok, let's close it for now

**Pull request closed without merging**
