### PR TITLE
fix a 3rd party blur3x3 function(the 7th value in tcurr should be set to the 5th value in old tcurr, which will be be overwritten by the 3rd value in old tcurr)

### PR DESCRIPTION
**Pull request by driftee**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@driftee Could you provide small test/reproducer that shows the bug?

**Comment by asmorkalov** [comment]
@driftee I propose to extend test "Imgproc_Blur.borderTypes" to highlight the issue and ensure the same behavior on all supported platforms. See https://github.com/opencv/opencv/blob/7e845a3b87e9e729e6f10b049b2845331f966a6a/modules/imgproc/test/test_filter.cpp#L1971

**Comment by asmorkalov** [comment]
@driftee friendly reminder.

**Comment by asmorkalov** [comment]
The function is not called in OpenCV and cannot be tested with public API.

**Review by asmorkalov — APPROVED** [review]

**Comment by alalek** [comment]
@asmorkalov are you able to reproduce the problem?
Changing order of "independent" lines looks strange - if we have problem, then it could be worse.

**Comment by asmorkalov** [comment]
It looks like the function blur is some rudiment. It's not called from OpenCV, but Filter2d is used as universal solution. Also looks like it's not the only bug. This 2 lines are very suspicious:
https://github.com/opencv/opencv/blob/4.x/3rdparty/carotene/src/blur.cpp#L376

**Pull request merged**
