### PR TITLE
Add workflows for macOS ARM64 and macOS x86_64 for branch 3.4

### PR DESCRIPTION
**Pull request by fengyuentau**
4.x: #22104
5.x: #22105

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asenyaev** [comment]
macOS jobs failed for 3.4 branch in case of [this line](https://github.com/opencv/ci-gha-workflow/blob/08573e7d60d609e25070b4aca549a5874c3c1801/.github/workflows/OCV-PR-3.4-macOS-ARM64.yaml#L303), there is an extra space.

https://github.com/opencv/ci-gha-workflow/pull/18 is going to fix it.

**Comment by asenyaev** [comment]
@fengyuentau, please, do re-commit. GitHub Actions work this way - if your commit was before latest changes in a repository where workflow files are located, then it will never update a new info til you update the commit.

**Comment by fengyuentau** [comment]
Sure, I have done re-commit.

**Comment by asenyaev** [comment]
Currently, anything is fine, but not Windows:

```
Run OPENCV_CONTRIB_FORK=$(git ls-remote --heads "git@github.com:fengyuentau/opencv_contrib" "macOS_workflows_for_3.4") || true
  
Merge opencv_contrib with macOS_workflows_for_3.4 branch
From github.com:fengyuentau/opencv_contrib
 * branch                macOS_workflows_for_3.4 -> FETCH_HEAD
fatal: refusing to merge unrelated histories
Error: Process completed with exit code 128.
```
@fengyuentau, could you remove this branch in your opencv_contrib fork? As I see, workflows for opencv_contrib repository have been merged.

**Review by asenyaev — APPROVED** [review]
Thank you! :+1:

**Review by alalek — APPROVED** [review]

**Pull request merged**
