### PR TITLE
Expose CGImage <-> Mat conversion for iOS platforms

### PR DESCRIPTION
**Pull request by colejd**
#18547 introduces `CGImage`<->`Mat` conversion for MacOS platforms. This PR enables the same capabilities for iOS platforms. C++ users can now use `MatToCGImage` and `CGImageToMat` in `ios.h`, and Objc users can now do the equivalent conversions in `Mat+Converters.h`.

I also took the liberty of adding `CF_RETURNS_RETAINED` annotations to methods that return `CGImageRef`, so that the Swift compiler knows to `CFRelease()` when the reference count goes to 0. This is technically a breaking change, as the prior implementation required users to explicitly use `takeRetainedValue()` to properly reference count; however, I think the expectation is that such objects are reference counted by default, so I would categorize the prior behavior as a bug and my changes as a bugfix.

<cut/>

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders_only=Custom Mac
build_image:Custom Mac=osx_framework-test
buildworker:Custom Mac=macosx-2
build_contrib:Custom Mac=OFF
```

### CODE REVIEW

**Comment by mtfrctl** [comment]
Thank you @colejd !
Originally, there is no CGImage <-> Mat conversion method for iOS (https://github.com/opencv/opencv/pull/18547/files#diff-c3966397c21ebeff71a44f0344019837cd32fdd566133506b5ed8d9a91bf8a3e), and it is not hidden because it was added for macOS, but thank you for adding it for iOS as well.

Also, regarding the CF_RETURNS_RETAINED annotation, I was not confident in this process, so thank you for adding it.

**Comment by colejd** [comment]
@mtfrctl Thanks! Sorry, I didn't mean to imply any wrongdoing on your part. I should have paid more attention to the file history. Kind of flying by the seat of my pants here.

**Comment by alalek** [comment]
:+1:

**Pull request merged**
