### PR TITLE
parallelize FAST

### PR DESCRIPTION
**Pull request by WeiChungChang**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### Purpose
This PR tries to implement parallelism flow of FAST.
### Design details.

- this PR implements an invoker which inherits from ParallelLoopBody.

- in the constructor of invoker, it divides input image into slices.

- in operator() if invoker, execute FAST algorithm in parallel.

- to completely comply with original flow, slices need to overlap with their neighbors. in order to:

1. provide corner check reference. 
2. provide NMS reference.

- each slice is represented as ROI.

- currently TYPE_9_16 has been verified and should provide the same result as original flow.

- we need to add slice offset to keypoints' y axis. 

### Performance measure
environment: 12 threads (6+6) of Intel core i7 9th Gen.

[cpuinfo.txt](https://github.com/opencv/opencv/files/5179545/cpuinfo.txt)

**case 1:** no NMS, only  to detect keypoints and threshold = 10.
nonms

nonms

Speedup up to ~x5 is observed; notice that if slices are divided uniformly it can be even faster (as explained in criterion to select # of slices)

**case 2:** with NMS, only  to detect keypoints and threshold = 10.
nms
nms
Speedup up to ~x6 is observed; notice that if slices are divided uniformly it can be even faster (as explained in criterion to select # of slices)

**criterion to select # of slices:** .
For some images, the key points distribute non-evenly.
As description in (TODO), if we ensure the # of slices >= # of available threads, we can do better. 
Experiment result is given below(TODO)

### TODO:

### CODE REVIEW

**Comment by asmorkalov** [comment]
CI bot reports compilation warnings: https://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/28833

**Comment by vpisarev** [comment]
@WeiChungChang, thank you for the contribution! Can the testing be somehow improved? In theory, if we have a set of images with increasing resolution and approximately the same density of feature points, the execution time should grow monotonously. If your benchmarks the execution time jumps like crazy. Besides, it's good to see that at 4K resolution the acceleration factor is 6x. But on, say, FullHD it's 2.57x, which is quite low for 6+6-core machine.

In other words, in order to merge your patch we need to better understand what's the real behaviour of this algorithm. Perhaps, the threshold of 640 rows is too low for this algorithm. Maybe, the parallel version should be enabled starting from FullHD images. And the threshold rule should be changed to check the number of pixels instead of the number of rows, because in principle images can have a different aspect ratio. What about `(size_t)img.rows*img.cols >= 2000000`?

**Comment by asmorkalov** [comment]
@WeiChungChang Friendly reminder.

**Comment by asmorkalov** [comment]
@WeiChungChang Friendly reminder.

**Comment by asmorkalov** [comment]
@WeiChungChang Friendly reminder.

**Comment by alalek** [comment]
OpenCV CI can't validate this PR due to removed the source branch.

**Pull request closed without merging**
