### PR TITLE
Convert demosaic functions to HAL (2.6x faster for VSX)

### PR DESCRIPTION
**Pull request by ChipKerchner**
Convert demosaic functions to HAL (2.6x faster for VSX).

Added bayerRGBA to vectorized functions (missing from x86) - plus added alpha to parameter list.

Leaving NEON code in since it has much better instructions for interleaving data - plus added HAL bayerRGB_EA for NEON.

```
force_builders=linux,docs,Custom,Linux AVX2,ARMv7
buildworker:Custom=linux-1
build_image:Custom=mips64el
```

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for working on this!
Could you please take a look on compilation issues?

**Comment by ChipKerchner** [comment]
> Could you please take a look on compilation issues?

I'm not sure why this compilation is taking and timing out after almost 2 hrs.  I've compiled it on gcc for x86, Power, and ARM without problem.

Any suggestions?

**Comment by alalek** [comment]
@ChipKerchner Sorry, It is CI failure.

**Comment by ChipKerchner** [comment]
> By the way, did you compare that NEON code performance vs universal intrinsics performance on the same platform?
> Although NEON intrinsics code is more compact and intuitive, the less code to support we have the better.

I have no way on comparing NEON code performance - only correctness.  If someone else can see if the NEON or the HAL code is faster on an ARM, please do so.  If HAL is faster, I'll eliminate the NEON code.

**Comment by savuor** [comment]
👍

**Comment by ChipKerchner** [comment]
Great!  I'll probably have a 2nd PR for the other sections of demosiacing at a later time.

**Pull request merged**
