### PR TITLE
cmake: set _WIN32_WINNT for Windows 7 API

### LINKED ISSUE #15886: core(TLS): failed test in static Windows builds
[Nightly build](http://pullrequest.opencv.org/buildbot/builders/3_4-win64-vc14-static/builds/546)

Message:

```
[ RUN      ] Core_TLS.HandleThreadTermination
c:\build\3_4-win64-vc14-static\opencv\modules\core\test\test_utils_tls.impl.hpp(69): error: Expected equality of these values:
  init_allocated + 0
    Which is: 0
  TLSReporter::g_allocated
    Which is: 4
[  FAILED  ] Core_TLS.HandleThreadTermination (463 ms)
```

### PR DESCRIPTION
**Pull request by alalek**
resolves #15886

```
build_shared:Custom Win=OFF
build_examples:Custom Win=OFF
```

### CODE REVIEW

**Comment by asmorkalov** [comment]
@alalek How does Windows version definition solve the issue?

**Comment by alalek** [comment]
This macro activates code from this patch: #15812 (there is patch note: "In order to use Fls-functions need to define _WIN32_WINNT to 0x0600 or above.")

This macro is not added by CMake as default.
Windows SDK defines to 0x400 by default (checked with MSVS 2017).

**Comment by asmorkalov** [comment]
Thanks for clarification.

**Comment by alalek** [comment]
:+1:

**Pull request merged**
