### PR TITLE
Fix two race conditions in LazyInit and Matrix default allocator

### PR DESCRIPTION
**Pull request by grundman**

### CODE REVIEW

**Comment by alalek** [comment]
1) Use CV_SINGLETON_LAZY_INIT macro, without creation of global objects (you can't guarantee initialization order of them - so `Mutex g_matAllocatorMutex;` doesn't work because it may not be initialized when you want to use them). See "static initialization order fiasco" for more info.
2) Don't change CV_SINGLETON_LAZY_INIT macro. It is well known pattern: https://en.wikipedia.org/wiki/Double-checked_locking

**Comment by vpisarev** [comment]
@alalek, let me assign it to you

**Comment by alalek** [comment]
@grundman Patch is rebased and updated (race condition in `Mat::getDefaultAllocator()` is resolved, other changes were removed).

**Comment by alalek** [comment]
:+1:

**Pull request merged**
