### PR TITLE
Fix some C++ compiler warnings (case fallthrough, negation of string)

### PR DESCRIPTION
**Pull request by eecsninja**
### This pullrequest changes

Replace {!"string"} with {false && "string"}
Replace case statement fallthroughs with break statements

The warnings appear in gcc 7.3.0 with -Wimplicit-fallthrough

### CODE REVIEW

**Comment by alalek** [comment]
No need to re-open PRs. Just push your changes into the same branch (perhaps with "force" flag).

**Comment by alalek** [comment]
I have rebased this patch on the top of #11352 (the first commit is dropped).
Could you check that warnings are gone in your build configuration?

**Comment by eecsninja** [comment]
> I have rebased this patch on the top of #11352 (the first commit is dropped).
> Could you check that warnings are gone in your build configuration?

How do I pull in new changes from opencv/opencv to eecsninja/opencv?

**Comment by alalek** [comment]
These changes are already pushed to the source branch of this PR into your fork. Just fetch and checkout 3.4 branch from your fork. Something like this:
```
git checkout -B backup_3.4 3.4  # backup, optional step
git fetch origin 3.4
git checkout -B 3.4 origin/3.4
```

**Pull request merged**
