### PR TITLE
Added descriptions of randu and randn

### PR DESCRIPTION
**Pull request by pauljurczak**

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for contribution!

Please take a look on this guide how to resolve failed checks:
https://github.com/opencv/opencv/wiki/How_to_contribute#q3-i-was-asked-to-remove-whitespace-issues-how-can-i-do-that

**Comment by pauljurczak** [comment]
I was editing this file in my browser, using github edit feature. I have no idea how to fix whitespace issue through github website.

**Comment by pauljurczak** [comment]
What should I do differently the next time? I looked at https://github.com/opencv/opencv/wiki/Coding_Style_Guide and https://github.com/opencv/opencv/wiki/How_to_contribute and I don't see anything related to whitespace rules in source files.

**Comment by alalek** [comment]
Avoid trailing spaces in the end of lines. Builds use [`git diff --check`](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---check) to check rules.
Unfortunately I have no suggestions how to check that in "GitHub Editor".

**Pull request merged**
