### PR TITLE
(5.x) Merge 4.x

### PR DESCRIPTION
**Pull request by asmorkalov**
OpenCV Contrib: https://github.com/opencv/opencv_contrib/pull/3769
OpenCV Extra: https://github.com/opencv/opencv_extra/pull/1193

#22836 from kallaballa:opengl_cmake_warning_linux
#24941 from WanliZhong:v_exp
#25147 from fengyuentau:dnn/elementwise_layers/speedup
#25607 from Fest1veNapkin:imgproc_approx_bounding_poly
#25781 from WanliZhong:v_log
#25792 from asmorkalov:as/HAL_fast_GaussianBlur
#25794 from Abdurrahheem:ash/yolov10-support
#25799 from asmorkalov:as/HAL_GaussianBlurBinomial_Carotene
#25800 from xndcn:patch-2
#25808 from DmitryYurov:bug-25806-checkerboard-marker-black-tile
#25809 from zihaomu:imread_rgb_flag
#25810 from fengyuentau:python/fix_parsing_3d_mat_in_dnn
#25817 from lamiayous:ly/extend_onnxrt_gapi_backend_handle_i32_i64_type
#25822 from mqcmd196:gtk3-gl-support
#25824 from j3knk:calib3d/fix_projectpoints
#25841 from asmorkalov:as/cudnn9_version_check
#25842 from mshabunin:cpp-imgproc-test-4.x
#25844 from dietmar:dont_rely_on_nb_frames
#25845 from kaingwade:orbbecsdk_mac_off
#25856 from alexlyulkov:al/android-optional-kotlin
#25857 from asmorkalov:as/yolov9_harrowing_conversion
#25858 from asmorkalov:as/kleidicv_on
#25861 from Abdurrahheem:ash/torch-attention-export-fix-4x
#25864 from vrabaud:legacy
#25865 from asmorkalov:as/gtk_2_opengl_fix
#25872 from fengyuentau:core/v_erf
#25877 from Kumataro:fix25875
#25880 from Jamim:fix/cuda-no-fp16
#25885 from Sourav6971:4.x
#25888 from sturkmen72:haveImageReader
#25893 from fengyuentau:core/fix_v_erf
#25894 from mshabunin:fix-test-templ-match
#25897 from richard28039:4.x
#25899 from vrabaud:move_no_except
#25903 from Kumataro:fixC3767
#25911 from asmorkalov:as/HAL_fast_GaussianBlur
#25912 from asmorkalov:as/round_pair_f64_restore
#25913 from asmorkalov:as/chessboard_debug_logs

~~#25630 from fengyuentau:nary-multi-thread~~ Covered with dedicated PR #25900

Previous "Merge 4.x": #25840

### CODE REVIEW

**Comment by fengyuentau** [comment]
Two ocl tests in `windows10-x64` did not pass:

```
2024-07-16T11:02:43.4122013Z [ RUN      ] Test_ONNX_layers.PyTorchAttentionSingleHead/0, where GetParam() = OCV/OCL
2024-07-16T11:02:43.4513917Z unknown file: error: C++ exception with description "OpenCV(5.0.0-pre) C:\GHA-OCV-1\_work\opencv\opencv\opencv\modules\core\src\umatrix.cpp:1065: error: (-215:Assertion failed) _cn >= 0 && _newndims > 0 && _newndims <= CV_MAX_DIM && _newsz in function 'cv::UMat::reshape'
2024-07-16T11:02:43.4519296Z " thrown in the test body.
2024-07-16T11:02:43.4521450Z [  FAILED  ] Test_ONNX_layers.PyTorchAttentionSingleHead/0, where GetParam() = OCV/OCL (39 ms)
2024-07-16T11:02:43.4525077Z [ RUN      ] Test_ONNX_layers.PyTorchAttentionSingleHead/1, where GetParam() = OCV/OCL_FP16
2024-07-16T11:02:43.4580148Z unknown file: error: C++ exception with description "OpenCV(5.0.0-pre) C:\GHA-OCV-1\_work\opencv\opencv\opencv\modules\core\src\umatrix.cpp:1065: error: (-215:Assertion failed) _cn >= 0 && _newndims > 0 && _newndims <= CV_MAX_DIM && _newsz in function 'cv::UMat::reshape'
2024-07-16T11:02:43.4585490Z " thrown in the test body.
```

**Comment by asmorkalov** [comment]
I tried the initial patch from Abduragim (closed https://github.com/opencv/opencv/pull/25851) and it has the same issue:
```
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from Test_ONNX_layers
[ RUN      ] Test_ONNX_layers.TorchAttentionSingleHead/0, where GetParam() = OCV/OCL
unknown file: Failure
C++ exception with description "OpenCV(5.0.0-pre) /home/alexander/Projects/OpenCV/opencv-next/modules/core/src/umatrix.cpp:1065: error: (-215:Assertion failed) _cn >= 0 && _newndims > 0 && _newndims <= CV_MAX_DIM && _newsz in function 'reshape'
" thrown in the test body.
[  FAILED  ] Test_ONNX_layers.TorchAttentionSingleHead/0, where GetParam() = OCV/OCL (2 ms)
[ RUN      ] Test_ONNX_layers.TorchAttentionSingleHead/1, where GetParam() = OCV/OCL_FP16
unknown file: Failure
C++ exception with description "OpenCV(5.0.0-pre) /home/alexander/Projects/OpenCV/opencv-next/modules/core/src/umatrix.cpp:1065: error: (-215:Assertion failed) _cn >= 0 && _newndims > 0 && _newndims <= CV_MAX_DIM && _newsz in function 'reshape'
" thrown in the test body.
[  FAILED  ] Test_ONNX_layers.TorchAttentionSingleHead/1, where GetParam() = OCV/OCL_FP16 (2 ms)
[ RUN      ] Test_ONNX_layers.TorchAttentionSingleHead/2, where GetParam() = OCV/CPU
[       OK ] Test_ONNX_layers.TorchAttentionSingleHead/2 (2 ms)
[----------] 3 tests from Test_ONNX_layers (6 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (6 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] Test_ONNX_layers.TorchAttentionSingleHead/0, where GetParam() = OCV/OCL
[  FAILED  ] Test_ONNX_layers.TorchAttentionSingleHead/1, where GetParam() = OCV/OCL_FP16
```
So the issue is not related to the merge. Will disable a test and file a bug.

**Review by fengyuentau — APPROVED** [review]
dnn part looks good 👍

**Comment by asmorkalov** [comment]
Disabled tests and added reference to issue.

**Review by mshabunin — APPROVED** [review]

**Review by opencv-alalek — APPROVED** [review]

**Pull request merged**
