### PR TITLE
Add documentation and example program for intersectConvexConvex

### PR DESCRIPTION
**Pull request by SSteve**
### This pullrequest changes

I expanded the documentation for `intersectConvexConvex` and added a sample program illustrating its use.

```
force_builders_only=Linux x64,Docs
```

### CODE REVIEW

**Comment by asmorkalov** [comment]
@SSteve The patch introduces build warnings. Please take a look on CI logs: https://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/23294/steps/compile%20release/logs/warnings%20%286%29

**Comment by SSteve** [comment]
Warnings have been eliminated.

**Comment by asmorkalov** [comment]
:+1:

**Comment by alalek** [comment]
This patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

**Comment by SSteve** [comment]
Ok, I think that was successful.

**Comment by SSteve** [comment]
Oh, look, new warnings! I'll get to work on them.

**Comment by SSteve** [comment]
Oh, I see why all the new errors. OpenCV 4 uses c++11 but OpenCV 3.4 doesn't. Ok, I'll take out all the c++11 code.

**Comment by SSteve** [comment]
Looks like I've got a 3.4-compatible version!

**Pull request merged**
