### PR TITLE
fix a bug about vittrack post-process

### PR DESCRIPTION
**Pull request by lpylpy0514**
Fix a bug about vittrack post-process.

### CODE REVIEW

**Comment by fengyuentau** [comment]
Context: https://github.com/opencv/opencv_zoo/pull/245#issuecomment-2017255789

**Review by fengyuentau — COMMENTED** [review]
Could you post the reference to the change?

**Comment by lpylpy0514** [comment]
The two line I changed is based on 32 and 89 line in [ostrack](https://github.com/botaoye/OSTrack/blob/main/lib/test/tracker/ostrack.py).

**Comment by fengyuentau** [comment]
> The two line I changed is based on 32 and 89 line in [ostrack](https://github.com/botaoye/OSTrack/blob/main/lib/test/tracker/ostrack.py).

Thank you for the fix 👍

**Pull request merged**
