### PR TITLE
sobel and scharr ocl kernel optimization

### PR DESCRIPTION
**Pull request by pengli**
It improves 108%~230% performance in the perf test
with image format "CV_8UC1" and kernel size 3.

Signed-off-by: Li Peng <peng.li@intel.com>

### CODE REVIEW

**Comment by alalek** [comment]
Please use `sepFilter3x3` names instead of `filter2D3x3` (2D suffix is not needed in this case, because it is already 3x3)

**Comment by alalek** [comment]
There are failed tests in Intel iGPU device:
http://pullrequest.opencv.org/buildbot/builders/precommit_opencl-intel/builds/59

**Comment by pengli** [comment]
@alalek , have fixed the test failure in the new update by adding ddepth check.  please re-run the intel opencl test.

**Comment by alalek** [comment]
Thank you! :+1:

**Pull request merged**
