### PR TITLE
Adding some MSA specific optimizations for imgproc/video/vidoeio/dnn …

### PR DESCRIPTION
**Pull request by mipsopen-fwu**
…modules.

Signed-off-by: Fei Wu <fwu@wavecomp.com>
Added some MSA specific optimizations for the code in modules imgproc/video/vidoeio/dnn.

<cut/>

The changes files are:
modules/dnn/src/layers/convolution_layer.cpp 
modules/imgproc/src/demosaicing.cpp
modules/imgproc/src/moments.cpp
modules/imgproc/src/resize.cpp
modules/video/src/lkpyramid.cpp
modules/videoio/src/cap_mjpeg_encoder.cpp
All the changed code are embraced with macro CV_MSA.

relates #15422 

```
force_builders=linux,docs,Custom
buildworker:Custom=linux-1
build_image:Custom=mips64el
```

### CODE REVIEW

**Comment by mipsopen-fwu** [comment]
@alalek 
This PR has been kept in the current state for several days. How to make the merging process move on?
Thanks.

**Comment by mipsopen-fwu** [comment]
@alalek 
Could you please make this PR merged? Thanks a lot.

**Comment by alalek** [comment]
@mipsopen-fwu Hi!
This part of patch still has original problem - [using of original native intrinsic](https://github.com/opencv/opencv/pull/15422#discussion_r319469068). We prefer to avoid that until this is highly required (for performance reasons).

Unfortunately we can't review this fast:
- there is no OpenCV SIMD-based code path for these parts yet.
- there is lack of performance tests on these cases (no MJPEG encoder perf test at least).

We need to resolve these items first. Unfortunately, we are busy with release activities.

**Comment by mipsopen-fwu** [comment]
> @mipsopen-fwu Hi!
> This part of patch still has original problem - using of original native intrinsic. We prefer to avoid that until this is highly required (for performance reasons).
> Unfortunately we can't review this fast:
> 
> there is no OpenCV SIMD-based code path for these parts yet.
> there is lack of performance tests on these cases (no MJPEG encoder perf test at least).
> 
> We need to resolve these items first. Unfortunately, we are busy with release activities.

@alalek 
In places where MSA optimizations are applied in this part,  ARM neon also uses original native intrinsics.  If neon has proved the performance promotion, better performance can also be expected by using MSA instructions on MIPS platforms.

**Comment by mipsopen-fwu** [comment]
> @mipsopen-fwu Hi!
> This part of patch still has original problem - using of original native intrinsic. We prefer to avoid that until this is highly required (for performance reasons).
> Unfortunately we can't review this fast:
> there is no OpenCV SIMD-based code path for these parts yet.
> there is lack of performance tests on these cases (no MJPEG encoder perf test at least).
> We need to resolve these items first. Unfortunately, we are busy with release activities.
> 
> @alalek
> In places where MSA optimizations are applied in this part,  ARM neon also uses original native intrinsics.  If neon has proved the performance promotion, better performance can also be expected by using MSA instructions on MIPS platforms.

I can removed MJPEG encoder changes from this PR since the specific test case is not available. But for other changes in dnn/improc/video, the current perf-test suites have covered these optimizations  and we have seen the performance improvement from the testing on MIPS HW.  Could you please make these parts merged first? Thanks.

**Comment by ChipKerchner** [comment]
> * there is no OpenCV SIMD-based code path for these parts yet.

I'm working on a HAL conversion of

modules/imgproc/src/demosaicing.cpp

Eventually I'll get around to 

modules/imgproc/src/moments.cpp

**Comment by asmorkalov** [comment]
@ChipKerchner There is some issue with custom pre-commit job. Could you look at it:https://pullrequest.opencv.org/buildbot/builders/precommit_custom_linux/builds/2740/steps/compile%20release/logs/stdio

**Comment by alalek** [comment]
Issue is known: #15705

**Comment by ChipKerchner** [comment]
Added PR for conversion to HAL for demosaicing functions - [15764](https://github.com/opencv/opencv/pull/15764)

**Comment by alalek** [comment]
PR #15764 has been merged. It adds OpenCV SIMD code path for demosaicing color conversion. Thank you @ChipKerchner !

@mipsopen-fwu Could you please rebase this patch and compare performance between direct MIPS native intrinsics and through OpenCV SIMD on MIPS H/W? If performance is similar (for example, not worse more than 20%) then we prefer to keep code path with OpenCV SIMD universal intrinsics only.

**Comment by mipsopen-fwu** [comment]
@alalek I will evaluate the performance with the new implementations. Thanks.

**Comment by ChipKerchner** [comment]
Added PR for conversion to HAL for moments functions - [15828](https://github.com/opencv/opencv/pull/15828)

**Comment by ChipKerchner** [comment]
Added PR for Demosiacing with Variable Number of Gradients [15917](https://github.com/opencv/opencv/pull/15917)

**Comment by vpisarev** [comment]
Let's close it for now; all the information is stored in #19008

**Pull request closed without merging**
