### PR TITLE
Fix LogSoftmax for ONNX

### PR DESCRIPTION
**Pull request by dianlujitao**
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/608

Fix wrong indentation as well while at it

```
allow_multiple_commits=1
opencv_extra=onnx-log-softmax
force_builders=Linux x64,docs
```

### CODE REVIEW

**Comment by dianlujitao** [comment]
Test data: https://github.com/opencv/opencv_extra/pull/607

**Comment by dkurt** [comment]
Please replace the base branch from master to 3.4 (perhaps, you'll need to reopen PR). The best practice is to create new branches for patches with different names comparing to origin ones (so neigher `master` nor `3.4`).

**Comment by dianlujitao** [comment]
@dkurt Do I need to move the _extra PR to 3.4 branch as well?

**Comment by alalek** [comment]
Yes, please rebase opencv_extra PR too.

---

This patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

**Comment by dianlujitao** [comment]
Done on both side. opencv/opencv_extra#607 was messed up so I opened opencv/opencv_extra#608 instead.

**Pull request merged**
