### PR TITLE
Replace FLANNException by CV_Error.

### PR DESCRIPTION
**Pull request by vrabaud**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by vrabaud** [comment]
This is to not throw error when setBreakOnError has been called.

**Comment by vrabaud** [comment]
I will wait for master to become OpenCV 5.

**Comment by alalek** [comment]
@vrabaud It is fine to reopen PR and restore `FLANNException` class under `#if CV_VERSION_MAJOR == 4` guard to make ABI checker happy.

**Comment by vrabaud** [comment]
@alalek , I have re-opened the branch and set it to the 3.4 branch but the builds have not triggered for 3 days, what should I do ? Thx

**Comment by alalek** [comment]
> from vrabaud:master
> but the builds have not triggered for 3 days, what should I do 

Need to use proper [descriptive branch names](https://github.com/opencv/opencv/wiki/How_to_contribute) for source branch. `master` / `3.4` / etc source branches can't be automatically tested (especially in multi-repository cases with_opencv_extra/contrib).
Builds for such PRs are scheduled manually by reviewers/maintainers.

**Review by alalek — APPROVED** [review]
LGTM :+1:

**Pull request merged**
