### PR TITLE
js: Fix C preprocessor stringification

### PR DESCRIPTION
**Pull request by vrabaud**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
What issue do you try to fix. IMHO, the original code is correct.

**Comment by vrabaud** [comment]
This is the kind of code I get in typescript:
```ts
export type Range = {
  start: number,
  end: number
};

export type #type = {
  width: number,
  height: number
};

export type #type = {
  x: number,
  y: number
};
```
Which triggers the error
```
opencv_wasm_types.d.ts:1304:1 - error TS1128: Declaration or statement expected.

1304 export type #type = {
     ~~~~~~
opencv_wasm_types.d.ts:1304:13 - error TS2457: Type alias name cannot be '#type'.

1304 export type #type = {
```

**Comment by vrabaud** [comment]
We want the macro to behave like `emscripten::value_object<type>("Point")`

**Comment by vrabaud** [comment]
It should be obvious here: https://godbolt.org/z/hE956cEGM

**Pull request merged**
