### PR TITLE
Update Connected component labelling bug

### PR DESCRIPTION
**Pull request by yash112-lang**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### Overview
This PR fixes issue #21783

### CODE REVIEW

**Comment by MicheleCancilla** [comment]
You have modified the wrong line...
Faulty code: https://github.com/opencv/opencv/blob/56f21c4fd5653962d8fbd6ff268cfe5a875d590b/modules/imgproc/src/connectedcomponents.cpp#L4343

**Comment by yash112-lang** [comment]
I had updated it @MicheleCancilla, sorry for the previous commit. Can you take a look at it?

**Comment by prittt** [comment]
@yash112-lang  You reverted the wrong change, but the original buggy line is still there. Moreover, instead of having 3 commits to fix one line of code is better to have just one (e.g. forcepushing on your repo).

**Comment by MicheleCancilla** [comment]
It's wrong again!
Original (wrong) line:
`#define condition_e c+2<w && r-1>=0 && img_row_prev[c-1]>0` 
shoud become:
`#define condition_e c+2<w && r-1>=0 && img_row_prev_prev[c+2]>0`

You wrote:
`#define condition_e c+2<w && r-2>=0 && img_row_prev_prev[c+2]>0`

**Comment by yash112-lang** [comment]
> @yash112-lang You correctly reverted the wrong change, but the original buggy line is still there. Moreover, instead of having 3 commits to fix one line of code is better to have just one (e.g. forcepushing on your repo).

I think @prittt, the code was fine after the previous commit - [](https://github.com/yash112-lang)@yash112-lang
[Update connectedcomponents.cpp](https://github.com/opencv/opencv/pull/21794/commits/4debb1d35a096de5e6044bb9adf9deed76044d3b).

**Comment by prittt** [comment]
> > @yash112-lang You correctly reverted the wrong change, but the original buggy line is still there. Moreover, instead of having 3 commits to fix one line of code is better to have just one (e.g. forcepushing on your repo).
> 
> I think @prittt, the code was fine after the previous commit - @yash112-lang [Update connectedcomponents.cpp](https://github.com/opencv/opencv/pull/21794/commits/4debb1d35a096de5e6044bb9adf9deed76044d3b).

@yash112-lang Yes, after your last commit it is. 

To keep the history of the OpenCV repo as clean as possible, I suggest you to compress all changes (one line of code) in one single commit instead of five.

**Comment by yash112-lang** [comment]
@prittt, When trying to **squash** all commits into one it shows me an error like this - _"`Unable to reorder. Reordering replays all commits up to the last one required for the reordering. A merge commit cannot exist among those commits`."_ I searched on Internet also but have not found a relevant answer can you please help me.

**Comment by alalek** [comment]
Rebased to keep 1 commit only in PR.

**Review by alalek — APPROVED** [review]
Thank you for contribution :+1:

@MicheleCancilla Thank you for the review!

**Pull request merged**
