### PR TITLE
Add instructions for how to use findEssentialMat() when camera matrices are different

### LINKED ISSUE #17329: How can I find the essential matrix between two different cameras?
This is a question about the API, not really a bug report.

The documentation on [`findEssentialMat()`](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga13f7e34de8fa516a686a56af1196247f) states
> Note that this function assumes that points1 and points2 are feature points from cameras with the same camera matrix. 

But this is a very strong restriction. Is there a way to solve this problem between two distinct cameras?
Or would it be possible to `undistortPoints()` the points to normalized image coordinates with identity camera matrices for both cameras?

### PR DESCRIPTION
**Pull request by themightyoarfish**
Fixes #17329.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable

### CODE REVIEW

**Comment by themightyoarfish** [comment]
I mistakenly edited on top of old master. Pushing new commits to this PR branch does not seem to work, what seems to be the problem?

**Comment by asmorkalov** [comment]
Thanks a lot for contribution. This patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no need to re-open PR, apply changes "inplace".

**Comment by vpisarev** [comment]
@themightyoarfish, thank you, this is a good workaround! :+1:

**Comment by asmorkalov** [comment]
@alalek I rebased the patch and fixed conflicts. It's ready to merge.

**Pull request merged**
