### PR TITLE
Typos: cheirality vs chirality

### PR DESCRIPTION
**Pull request by mohawk2**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
> cheirality -> chirality

Looks like this part may be incorrect.
It is a valid term about cameras and computer vision: https://users.cecs.anu.edu.au/~hartley/Papers/cheiral/revision/cheiral.pdf or https://cmsc426.github.io/sfm/
The second one is probably related to chemistry.

BTW, I'm not a native English speaker, so I could be wrong.

**Comment by mohawk2** [comment]
Mr Hartley's paper (which you link to) gives the etymology of "cheirality" as the Ancient Greek "χείρ" ("hand"); the dictionary entry for "chiral" gives the same. They both refer to the "handedness" of a structure (in both chemistry and computer vision, whether they are identical with their reflection). "Cheirality" has <6,000 hits on Google; "chirality" has 134,000,000.

https://users.cecs.anu.edu.au/~hartley/publications-ajax/publications.htm shows Mr Hartley publishing papers with "cheirality" in 1979, 1980, 1993. Then with "chirality" in 1998, with the same abstract as you linked to, but titled "Chirality" (its DOI URL: http://dx.doi.org/10.1023/A:1007984508483).

My conclusion: "cheirality" is a mis-spelling, as evidenced by the authoritative version of the paper you linked to spelling it "chirality".

**Comment by mohawk2** [comment]
@alalek Any feedback on my thought above? :-)

**Comment by alalek** [comment]
There is link about computer vision: https://www.cambridge.org/core/books/abs/multiple-view-geometry-in-computer-vision/cheirality/2269D936A5BB233CBB0E9567C000F9C6
(we would fix typo iff Cambridge University Press do that)

IMHO, there may be an issue between UK / USA English - I have no idea, because I'm not English native speaker.

**Comment by mohawk2** [comment]
@alalek This is not a US vs UK issue. Professor Hartley's own publications page at ANU only lists one spelling of the word (the correct one, "chirality"): https://users.cecs.anu.edu.au/~hartley/publications-ajax/publications.htm

Google has 4e3 hits for "cheirality", and 6.6e7 hits for "chirality" (over 10,000 times as many). Once again, I am a native English speaker. If you're not interested in changing the spelling to be correct, please just close this pull request.

(@asmorkalov Thanks for much better PR title)

**Review by asmorkalov — APPROVED** [review]
:+1:

**Pull request merged**
