### PR TITLE
Added reference to Python example (stitching.py) in the High-Level St…

### PR DESCRIPTION
**Pull request by Suyog-16**
## What this Pull Request (PR) does
Added reference to Python example (stitching.py) in the High-Level Stitching API Tutorial for 4.x.

## Related issues
This PR addresses the issue where the tutorial only referenced the C++ example and did not include the Python example.

### Pull Request Readiness Checklist

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
```
Run cd /home/ci/opencv
doc/tutorials/others/stitcher.markdown:30: trailing whitespace.
+A similar script is available for Python 
Error: Process completed with exit code 2.
```

**Comment by asmorkalov** [comment]
I reviewed the tutorial and just link addition is not enough. The tutorial describes parts of code and it does not work for python as is. You need to rewrite some text pieces and use switch for python/c++ like in https://docs.opencv.org/4.x/d3/d96/tutorial_basic_geometric_drawing.html

**Comment by Suyog-16** [comment]
Well i took this issue thinking it would be an easy fix, but i am unknown with changing the code snippets and rewriting them . I think someone with experience could take this issue and help here .Thank you for your understanding

**Comment by ericmariasis** [comment]
Let me try to tackle the switch as part of PR 25962.

**Comment by ericmariasis** [comment]
I added the toggle, but note that the explanations below are still C++ only. From what it sounds like, a Python specific explanation is out of scope for this issue.

**Pull request closed without merging**
