### PR TITLE
Added AKAZE features in the stitcher pipeline (issue #6474)

### LINKED ISSUE #6474: Feature request to add Akaze feature detector in stitcher class
Stitcher class in <opencv2/stitching.hpp> has currently two feature detectors: 1. surf    2. orb.
Surf gives good results compared to orb but Surf is patented. Whereas Akaze feature detector is free to use commercially and it has been added in opencv which outperforms Surf in certain cases but it has not been added to Stitcher class. Therefore I request to add detail::AkazeFeatureFinder() also as well as detail::SurfFeatureFinder() and detail::OrbFeatureFinder(). I tried to integrate Akaze externally but I could not suceed.
Thank you.
### Please state the information for your system
- OpenCV version: 3.x
- Host OS: Linux (Ubuntu 15.10)  

### In which part of the OpenCV library you got the issue?
- stitching

### Code example to reproduce the issue / Steps to reproduce the issue
Please try to give a full example which will compile as is.
```
#include <iostream>
#include <fstream>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/stitching.hpp>

using namespace std;
using namespace cv;

bool try_use_gpu = false;
vector<Mat> imgs;
string result_name = "result.jpg";

void printUsage();
int parseCmdArgs(int argc, char** argv);

int main(int argc, char* argv[])
{
    int retval = parseCmdArgs(argc, argv);
    if (retval) return -1;

    Mat pano;
    Stitcher stitcher = Stitcher::createDefault(try_use_gpu);
    stitcher.setFeaturesFinder(new detail::OrbFeaturesFinder());
    stitcher.setFeaturesFinder(new detail::SurfFeaturesFinder());        
    Stitcher::Status status = stitcher.stitch(imgs, pano);
    std::cout<<"orb Status: "<<status<<std::endl;
    if (status != Stitcher::OK)
    {
        cout << "Can't stitch images, error code = " << int(status) << endl;
        return -1;
    }
    imwrite("orb_"+result_name, pano);

    stitcher.setFeaturesFinder(new detail::SurfFeaturesFinder());
    status = stitcher.stitch(imgs, pano);
    std::cout<<"surf Status: "<<status<<std::endl;
    if (status != Stitcher::OK)
    {
        cout << "Can't stitch images, error code = " << int(status) << endl;
        return -1;
    }
    imwrite("surf_"+result_name, pano);

    return 0;
}


void printUsage()
{
    cout <<
        "Rotation model images stitcher.\n\n"
        "stitching img1 img2 [...imgN]\n\n"
        "Flags:\n"
        "  --try_use_gpu (yes|no)\n"
        "      Try to use GPU. The default value is 'no'. All default values\n"
        "      are for CPU mode.\n"
        "  --output <result_img>\n"
        "      The default is 'result.jpg'.\n";
}


int parseCmdArgs(int argc, char** argv)
{
    if (argc == 1)
    {
        printUsage();
        return -1;
    }
    for (int i = 1; i < argc; ++i)
    {
        if (string(argv[i]) == "--help" || string(argv[i]) == "/?")
        {
            printUsage();
            return -1;
        }
        else if (string(argv[i]) == "--try_use_gpu")
        {
            if (string(argv[i + 1]) == "no")
                try_use_gpu = false;
            else if (string(argv[i + 1]) == "yes")
                try_use_gpu = true;
            else
            {
                cout << "Bad --try_use_gpu flag value\n";
                return -1;
            }
            i++;
        }
        else if (string(argv[i]) == "--output")
        {
            result_name = argv[i + 1];
            i++;
        }
        else
        {
            Mat img = imread(argv[i]);
            if (img.empty())
            {
                cout << "Can't read image '" << argv[i] << "'\n";
                return -1;
            }
            imgs.push_back(img);
        }
    }
    return 0;
}
```

### PR DESCRIPTION
**Pull request by Tytan**
### Resolve  #6474

Adds AKAZE features to the stiching pipeline. 

Had to use Mat instead of UMat for the descriptors in the detectAndCompute function since AKAZE implementation doesn't seem to support UMat for descriptors.

### CODE REVIEW

**Comment by sovrasov** [comment]
:+1:

**Comment by sovrasov** [comment]
@Tytan Exposure compensator is a new feature and it doesn't related to #6474, so  it's better to create a new PR with the last commit.

**Comment by alalek** [comment]
Just do not use 'master' branch as source. Please recreate PR with proper branch name.

**Comment by Tytan** [comment]
Yeah just realised that. My bad, new PR on a proper branch incoming

**Pull request closed without merging**
