### PR TITLE
Added detection of MSVC1911

### PR DESCRIPTION
**Pull request by patrikhuber**
MSVC1911 is VS2017 Preview (which is an "early preview" of the next changes). The PR makes sure the version is detected properly and the INSTALL target then correctly installs to x64/vc15 (the same as for MSVC1910).

Same changes as done in #7797 for MSVC1910.

### CODE REVIEW

**Comment by patrikhuber** [comment]
This could be back-ported to 2.4.x I guess if anyone can be bothered. I'm not using 2.4.x anymore ;-)

**Comment by alalek** [comment]
Thanks! Do you have any information about binary compatibility between MSVS2015 (1900) and MSVS2017 (1910/1911)?

**Comment by patrikhuber** [comment]
Hi @alalek, Yep, I linked this in #7797 already at the end, as per your request. Was the information there not sufficient?
(TLDR: Yes they're binary compatible).

**Comment by alalek** [comment]
I found [this link](https://blogs.msdn.microsoft.com/vcblog/2017/03/07/binary-compatibility-and-pain-free-upgrade-why-moving-to-visual-studio-2017-is-almost-too-easy/):
> VC Runtime in MSVC 2017 is binary compatible with 2015

:+1:

**Comment by patrikhuber** [comment]
@alalek Yep this link is even newer - I guess since December last year MS wrote a couple of blog posts with a bit more official information about it! :-)

**Pull request merged**
