### PR TITLE
Fix memory leak in Python custom dnn layers

### PR DESCRIPTION
**Pull request by dkurt**
resolves https://github.com/opencv/opencv/issues/16811

### CODE REVIEW

**Comment by ndvbd** [comment]
Was this problem fixed in opencv 4? If so in what version?

**Comment by dkurt** [comment]
@ndvbd, with OpenCV 4.3.0: https://github.com/opencv/opencv/releases/tag/4.3.0 Released after several weeks after fix has been merged.

**Comment by ndvbd** [comment]
Thanks @dkurt ! Do you know if the memory leak was only in the python wrapper, or also when using the DNN forward from C++?

**Comment by dkurt** [comment]
@ndvbd, the issue connected to only Python bindings and corresponding solution solves it in the code related to Python API. So, it was only Python problem if you use custom layers. If there is no custom layers - there were no leaks.

**Pull request merged**
