### PR TITLE
CUDA implementation of the BackgroundSubtractorKNN() algorithm

### PR DESCRIPTION
**Pull request by bramton**
This pullrequest contains the CUDA implementation of the BackgroundSubtractorKNN() algorithm. The performance increase is roughly 20x with shadow detection enabled and 30x without shadow detection enabled. The current CUDA code will only work with CV_8UC3 input frames.

### CODE REVIEW

**Comment by alalek** [comment]
Please add a test for this functionality.

**Comment by bramton** [comment]
I have been struggling to create a test for this functionality. But it seems there is currently something wrong with the CUDA testing macros #7993.

**Comment by alalek** [comment]
Could you please rebase your changes and check CUDA tests again?

**Comment by vpisarev** [comment]
it looks like the PR is abandoned

**Pull request closed without merging**
