### PR TITLE
Const and class to json

### PR DESCRIPTION
**Pull request by Cartucho**
### This pullrequest changes

Adding python constants and classes to the `pyopencv_signatures.json` file.

### CODE REVIEW

**Comment by Cartucho** [comment]
@alalek what do you think of this approach?

**Comment by alalek** [comment]
Looks good!

I believe we should provide more accurate names:
```
    "cv::dnn::DNN_BACKEND_DEFAULT": [
        {
            "name": "DNN_BACKEND_DEFAULT",
            "ret": 0
        }
    ]
```
but there is lost additional "sub-module":
```
>>> cv2.DNN_BACKEND_HALIDE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'DNN_BACKEND_HALIDE'
>>> cv2.dnn.DNN_BACKEND_HALIDE
1
```

Actually the same problem with functions too (existed before this patch):
```
>>> cv2.readNetFromTensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'readNetFromTensorflow'
>>> cv2.dnn.readNetFromTensorflow
<built-in function readNetFromTensorflow>

    "cv::dnn::readNetFromTensorflow": [
        {
            "arg": "model",
            "name": "readNetFromTensorflow",
            "ret": "retval"
        }
    ]
```

Need to find how sub-modules are handled (or ignore this for future changes with filing issue).


Also It is quite unclear to me how "expanded" values of enums could help OpenCV Users. I believe proper "Python" names is enough.

**Comment by Cartucho** [comment]
@alalek Sorry for the delay! I've been busy in the University.
If we use the namespace we can do a quick fix to add the sub-module info.

Let me know what you think, I can do the same for the functions.

**Comment by alalek** [comment]
Looks good to me!
Please add namespace for the functions and for the classes.

**Comment by Cartucho** [comment]
@alalek I added the namespace to the functions and classes.

I noticed that in some of the classes a `_create(params...)` should be added
I.e:  `cv2.ml.ParamGrid` should be: `cv2.ml.ParamGrid_create()`

**Comment by alalek** [comment]
Perhaps we should avoid adding namespaces to methods. Example:
```
{"cv::dnn::Layer::forward": [{"name": "cv2.dnn.forward" ...
```

`_create` had special processing. They can wrap "static" method "create()":
```
{"cv::ml::ParamGrid::create": [{"name": "cv2.ml.ParamGrid_create"
```
or wrap class constructor (it is buggy sometimes yet):
```
{"cv::KeyPoint::cv::KeyPoint::KeyPoint": [{"name": "cv2.KeyPoint" ...
```


There is attempt to eliminate `_create` functions (use ctor directly): #8934
So I believe we don't need "_create" suffix.

**Comment by Cartucho** [comment]
@alalek is this correct? `cv2.dnn.forward`
Or do we need to create the net first and only then do the forward? I couldn't find any docs on this.

But it makes sense to have the namespace in the methods for example:
`cv::dnn::blobFromImage` -> `cv2.dnn.blobFromImage`


How do you want to proceed? We can either:

a) ignore for now the specific modules (dnn, ...) and then add them one by one checking if everything is alright.

b) try to figure out a way to cover all the specific modules corner cases

**Comment by alalek** [comment]
> cv2.dnn.forward

No, `forward` is a [method name](https://docs.opencv.org/master/d3/d6c/classcv_1_1dnn_1_1Layer.html#a73b2805c23c1ed07dea8e6a99d96feaf) of `Layer`. So it is probably to keep it without any namespace (can't be used without class object: usage is `mylayer.forward(...)`).

`blobFromImage` is function, so namespace is applicable here.

**Comment by Cartucho** [comment]
@alalek I understand now! I will remove the namespace from methods!

**Comment by Cartucho** [comment]
@alalek I removed the namespace from methods. But, for example, the method `fourcc` (now in the .json file) should be `cv2.VideoWriter_fourcc()`.

**Comment by alalek** [comment]
I believe because `fourcc()` is "static" method, right?

**Comment by Cartucho** [comment]
@alalek from the brief:

VideoWriter_fourcc(c1, c2, c3, c4) -> retval

This static method constructs the fourcc code of the codec to be used in the constructor VideoWriter::VideoWriter or VideoWriter::open

**Comment by alalek** [comment]
For static methods it is make sense to provide information in this format:
```
<namespace>.<class_name>_<method_name> = cv2.VideoWriter_fourcc
```

**Comment by Cartucho** [comment]
@alalek How do you suggest me to check if it's static?
When I print the proto from line 624 they all appear to be static:

image

**Comment by Cartucho** [comment]
@alalek I checked and I believe all the methods are static, i.e:

HOGDescriptor_getDaimlerPeopleDetector()
HOGDescriptor_getDefaultPeopleDetector()
VideoWriter_fourcc(c1, c2, c3, c4)
CascadeClassifier_convert(...)
SparsePyrLKOpticalFlow_create(winSize=None, ...)
...

**Comment by alalek** [comment]
We need to check for "/S" attribute:
https://github.com/opencv/opencv/blob/3.3.0/modules/python/src2/hdr_parser.py#L360-L361

**Comment by Cartucho** [comment]
@alalek actually there is a parameter to see if it's static (isclassmethod):

https://github.com/opencv/opencv/blob/3.3.0/modules/python/src2/gen2.py#L846-L848

For users to better understand that their dealing with a class object I added a my<Class> before, what do you think?

image

**Comment by alalek** [comment]
> I added a my before

I don't understand. These static methods are already a part of Python bindings interface. No need to rename this.

```
>>> cv2.ml.TrainData_create
<built-in function TrainData_create>
```

**Comment by Cartucho** [comment]
@alalek 
I gave you the wrong example.

I meant I wanted to add the my before the non static methods.
For example: `mylayer.forward(...)` instead of writing just `forward`.

According to these lines all the methods are static:
https://github.com/opencv/opencv/blob/3.3.0/modules/python/src2/gen2.py#L846-L848

**Comment by Cartucho** [comment]
@alalek I commited the most recent version.

I don't know why some "regular methods" from sub-modules. For example the `objLayer.forward` are not showing up

**Comment by alalek** [comment]
I have pushed changes:
- proper handling for constructors, classmethods (static methods), regular methods
- fix methods C++ names (`cv::ml::TrainData::cv::ml::TrainData`)
- removed magic values: bindings generator doesn't know: 'ml', 'flann' and even 'cv2'
- removed magic translations for constant names (reuse existed variables instead)
- removed evaluation of constants (it is useless thing: it is better to know that `ACCESS_RW` is `ACCESS_READ | ACCESS_WRITE` than some number)

**Comment by Cartucho** [comment]
@alalek 
Just one thing, now it is generating for example 4 functions with the same name (`obj.load`), so if we could add the class as well (`obj<Classname>.load`) would be better for distinguishing. Do you agree?

**Comment by alalek** [comment]
> now it is generating for example 4 functions with the same name (obj.load)

This is Python part, it is not required to be unique. We should map C++ entities => Python entities. I don't expect reverse mapping at this moment. So probably there is no serious problem.
Also there is no direct access to class methods without pre-created object instances.

Did you have a chance to take a look on opencv.tag file from doxygen?

**Comment by Cartucho** [comment]
@alalek Sorry, I've been really busy! I will get back to this this weekend, what's left to do?

**Comment by alalek** [comment]
I believe we can merge this patch and use current results in #9260 (check for more details).

**Pull request merged**
