### PR TITLE
Added TanH activation function to darknet

### PR DESCRIPTION
**Pull request by aryanshomray**
### Pull Request Readiness Checklist

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
1. from `aryanshomray:master`
According to contribution guidelines `master` source branch should not be used.
2. Patch with testdata is missing to opencv_extra repository.
3. Build and run tests locally first.

You need to use source branch with descriptive name and re-create new PR.

**Comment by aryanshomray** [comment]
Yes, sure. I will do the things as described.

**Comment by cpraschl** [comment]
Anything new on this PR?

**Comment by aryanshomray** [comment]
I am currently working on this, it might take some time this is my 1st OpenCV contribution(however i use opencv a lot).

**Pull request closed without merging**
