### PR TITLE
Rephrase parts of the templates and use comments

### PR DESCRIPTION
**Pull request by Dikay900**
### What does this PR change?
This PR changes the templates a bit so the comments are actual comments and won't be posted if not erased.

- [x] smaller headings
- [x] hidden instructions on top of each section
- [x] Guidelines for how to contribute
 - [x] link [How To Contribute](https://github.com/Itseez/opencv/wiki/How_to_contribute)
- [x] leave a mark that this is the bug report section and should not be used for general questions
 - [x] link http://answers.opencv.org
- [x] use placeholder for real values
 - [x] give example of real values in How To Contribute or comment
- [x] detailed description
 - [x] code template as hidden comment

### CODE REVIEW

**Comment by mshabunin** [comment]
Very good suggestion, thank you! Especially for replacing questions in section headers. I thought about something like this too, following are some of my ideas:
- we could use smaller heading level like 5 or 6 (`#####` or `######`)
- all hidden instructions `<!-- ... -->` should be placed either at the beginning of each section, either at the beginning of the template
- probably we need some detailed PR/issue writing guide with concrete examples in wiki (related page: [How to contribute](https://github.com/Itseez/opencv/wiki/How_to_contribute)).
- sometimes people do not fill issue description (for example #6529), and it would be better if the issue will look unfilled from the first sight (see the second appendix):
    - in system description we could show some placeholder instead of actual values: 
    <br/> `OpenCV version: ???`
    <br/> `Platform: ???`
    <br/> `Compiler: ???`
    - instead of several description sections we could use single _Detailed description_ section with subsections: _Steps ..._, _Actual ..._, _Expected ..._.
    - probably we don't need the _Expected ..._ and even _Actual ..._ sections at all. Often these sections contain just several words: `work`/`do not work` or `no assert`/`assert`.
    - the code example can be replaced with the instruction referring to markdown code snippet command (see the first appendix)

The main thought is to give people guidelines and useful information but not to force them to detailed format implicitly.

---
_Appendix 1: code sample replacement:_
```
<!-- to add code example fence it with triple backticks and optional file extension 
    ```.cpp
    // C++ code example
    ```
 or attach as .txt or .zip file -->
```
---
_Appendix 2: this is how I would prefer to see an unfilled issue:_

##### System information
<!-- put some actual information here -->
- _OpenCV_ => :grey_question:
- _Platform_ => :grey_question: 
- _Compiler_ => :grey_question:

##### Detailed description
<!-- describe the problem in general -->

###### Steps to reproduce
<!-- provide detailed reproducing steps -->

**Comment by Dikay900** [comment]
Thanks for your additions i set up a list and will work on this soon.

**Comment by Dikay900** [comment]
I added an example for version description in the template and changed the pr template as well again.
Sorry for the long delay.

**Comment by mshabunin** [comment]
Thank you! Looks good to me :+1:
@alalek , what do you think?

**Comment by alalek** [comment]
:+1:

**Comment by vpisarev** [comment]
this PR will be reopened because of CI issues

**Pull request closed without merging**
