### PR TITLE
BackgroundSubtractorCNT

### PR DESCRIPTION
**Pull request by lhelontra**
New background subtraction solution, very fast compared with mog2 or Knn. Good solution for low spec hardware.

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for contribution!
Could you add more information about implemented algorithm? (link to article)
For newer functionality tests should be provided (accuracy at least).

**Comment by lhelontra** [comment]
Sure, this link: https://www.theimpossiblecode.com/blog/fastest-background-subtraction-opencv/

**Comment by vpisarev** [comment]
I think, this algorithm should be put to opencv_contrib, not opencv.

**Comment by vpisarev** [comment]
ok, thanks! so, I'm closing this PR.

**Pull request closed without merging**
