### PR TITLE
GAPI (fluid): RGB to Lab optimization

### PR DESCRIPTION
**Pull request by elatkin**

### CODE REVIEW

**Comment by elatkin** [comment]
Performance: nearly same as cv::cvtColor, minus 5% for GAPI overhead

**Comment by alalek** [comment]
Need to rebase this PR after merging of #13174

**Comment by elatkin** [comment]
> Need to rebase this PR after merging of #13174

Done: merged fresh master (and resolved conflicts)

**Comment by alalek** [comment]
`git rebase -i master` with removal of "duplicate" commits are much easier.
And no conflicts at all.

**Pull request merged**
