### PR TITLE
Add Grana's connected components algorithm for 8-way connectivity.

### PR DESCRIPTION
**Pull request by vpisarev**
### What does this PR change?
<p align="justify">This PR introduces a faster algorithm for Connected Components Labeling with 8-way connectivity. The algorithm has been originally proposed in:
</br></br>
Grana, Costantino, Daniele Borghesani, and Rita Cucchiara. "Optimized block-based connected components labeling with decision trees." Image Processing, IEEE Transactions on 19.6 (2010): 1596-1609.
</br></br>
A series of performance comparisons has been made to assess the execution times of this algorithm, and to compare its performance with respect to the the algorithm currently implemented in OpenCV. Results of these evaluations, along with their source code, can be found in the <a href="https://github.com/prittt/YACCLAB">YACCLAB</a> project on Github.
The algorithm this PR introduces is named as BBDT in that project, while the current CCL algorithm implemented in Opencv is called SAUF.</p>

### Notes on *distanceTransformWithLabels* function
<p align="justify"><i>distanceTransformWithLabels</i> is a variant of the <i>distanceTransform</i> function included in Opencv. This variant does not only compute the minimum distance for each pixel (x,y), like <i>distanceTransform</i> does, but also identifies the nearest connected components consisting of zero pixels calling the <i>connectedComponents</i> function (which is the object of this PR). We change <i>connectedComponents</i> calls from <i>distanceTransform</i> function to forces SAUF algorithm execution for the following reasons: </p>
- *distanceTransform* algorithm requires a *labels*'s matrix with row major ordering of labels;
- SAUF algorithm forces that order of labels while BBDT does not.

<p align="justify">It is important to underline that different algorithms can produce the same connected components with different labels, this has not be considered as an error. For example, given the following binary image<p>

0 1 0 0 0 0 1
0 1 1 1 0 0 0
0 0 0 0 0 1 1
1 1 1 1 1 1 1

two different algorithms may label connected components in the following different ways:

0 1 0 0 0 0 2
0 1 1 1 0 0 0
0 0 0 0 0 3 3
3 3 3 3 3 3 3

0 2 0 0 0 0 3
0 2 2 2 0 0 0
0 0 0 0 0 1 1
1 1 1 1 1 1 1

This won't impact on any further analysis or on the statistics computed by the algorithms.

### Contributors
Federico Bolelli,
Costantino Grana,
Lorenzo Baraldi,
Roberto Vezzani.

### CODE REVIEW

**Comment by vpisarev** [comment]
Hello @prittt! Thank you for the contribution and sorry for delay! Could you please provide some tests to make sure that the function works well?

**Comment by prittt** [comment]
Hi @vpisarev, thank you for the reply! You mean tests for the automatic OpenCV's buildbot?

**Comment by vpisarev** [comment]
@prittt, sorry for delay, we've been changing our hardware. Yes, I mean the regular OpenCV regression tests

**Comment by prittt** [comment]
Ok, sure! I plan to do that this week.

**Comment by prittt** [comment]
Hi @vpisarev! I rewrote the test_connectedcomponents.cpp file and now opencv tests check the output correctness of both old and new algorithms of connectedComponents function. Let me know if you want something more.

**Comment by vpisarev** [comment]
@prittt, thanks! I think, the test is a bit weak, for example, for each painted pixel its neighbours must either belong to the same connected component or background - the test does not check it. But for a smoke test it may be fine :+1:

**Pull request merged**
