### PR TITLE
cv::TickMeter class addition

### LINKED ISSUE #6582: Feature Request cv::TickMeter
i think adding cv::TickMeter class in the library will be fine.

there is open questions at answers.opencv.org
http://answers.opencv.org/question/67009/why-tickmeter-class-only-used-in-the-gpu-samples/
http://answers.opencv.org/question/69035/tickmeter-class-removal-and-how-to-replace-it/

PS: if some core developer confirm and suggest the proper module ( i think it can be merged in core module). i will try to supply Pull Request.

### PR DESCRIPTION
**Pull request by vpisarev**
### Former #6584

resolves #6582

### What does this PR change?
moves cv::TickMeter class in the core library

initial commit

### CODE REVIEW

**Comment by apavlenko** [comment]
Summarizing the discussion inside #6584 the `TickMeter` class should use the `std::steady_clock` if C++11 is available and fall-back to the current implementation otherwise.
@sturkmen72 , do you plan to add the C++11 branch?

**Comment by alalek** [comment]
> cv::TickMeter class should use the std::steady_clock

I believe `cv::getTickCount` should think about "steady_clock" or other implementations. `TickMeter` is just a wrapper over `getTickCount` and should be simple as much as possible.

**Comment by apavlenko** [comment]
@alalek , sounds reasonable!
@sturkmen72 ?

**Comment by apavlenko** [comment]
OK, if so - let's merge this one and wait for a fix for the feature request #6902.
:+1:

**Pull request merged**
