### PR TITLE
IPP: minmaxidx with mask

### PR DESCRIPTION
**Pull request by alalek**
related #9207
resolves https://github.com/opencv/opencv_contrib/issues/1281

### CODE REVIEW

**Comment by lupustr3** [comment]
There are outdated checks for zero-mask. Here is a fix.

Replace this:
```
        status = ippMinMaxFun(src.ptr(), (int)src.step, size, dataType, pMinVal, pMaxVal, pMinIdx, pMaxIdx, (Ipp8u*)mask.ptr(), (int)mask.step);
        if(status < 0 || status == ippStsNoOperation)
            return false;
        if(_minVal)
            *_minVal = minVal;
        if(_maxVal)
            *_maxVal = maxVal;
        if(_minIdx)
        {
            if(!mask.empty() && !minIdx.y && !minIdx.x)
            {
                _minIdx[0] = -1;
                _minIdx[1] = -1;
            }
            else
            {
                _minIdx[0] = minIdx.y;
                _minIdx[1] = minIdx.x;
            }
        }
        if(_maxIdx)
        {
            if(!mask.empty() && !maxIdx.y && !maxIdx.x)
            {
                _maxIdx[0] = -1;
                _maxIdx[1] = -1;
            }
            else
            {
                _maxIdx[0] = maxIdx.y;
                _maxIdx[1] = maxIdx.x;
            }
        }
```

With this:
```
        status = ippMinMaxFun(src.ptr(), (int)src.step, size, dataType, pMinVal, pMaxVal, pMinIdx, pMaxIdx, (Ipp8u*)mask.ptr(), (int)mask.step);
        if(status < 0)
            return false;
        if(_minVal)
            *_minVal = minVal;
        if(_maxVal)
            *_maxVal = maxVal;
        if(_minIdx)
        {
            if(status == ippStsNoOperation)
            {
                _minIdx[0] = -1;
                _minIdx[1] = -1;
            }
            else
            {
                _minIdx[0] = minIdx.y;
                _minIdx[1] = minIdx.x;
            }
        }
        if(_maxIdx)
        {
            if(status == ippStsNoOperation)
            {
                _maxIdx[0] = -1;
                _maxIdx[1] = -1;
            }
            else
            {
                _maxIdx[0] = maxIdx.y;
                _maxIdx[1] = maxIdx.x;
            }
        }
```

**Comment by alalek** [comment]
Fix helps [partially](http://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/11678/steps/test_core/logs/stdio) (PR #8901). Also it works with `OPENCV_IPP=sse42` environment parameter, looks like there is an issue with AVX optimization.

**Comment by lupustr3** [comment]
Just updated checks. Function returns NoOperation falsely some times, so I added checks for index values. In combination this should be correct.

I also stuck with AVX. I will check on newer IPP version and will post conditions for disabling.

**Comment by lupustr3** [comment]
Please, add this at the top of ipp_minMaxIdx:

```
    // cv::minMaxIdx problem with index positions on AVX
#if IPP_VERSION_X100 < 201810
    if(!mask.empty() && _maxIdx && ipp::getIppFeatures()&ippCPUID_AVX)
        return false;
#endif
```

**Comment by alalek** [comment]
@lupustr3 Pavel, thank you!

:+1:

**Pull request merged**
