### PR TITLE
Add an illustration to the homography exercise

### PR DESCRIPTION
**Pull request by catree**
See https://github.com/opencv/opencv/pull/22130

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [X] The PR is proposed to the proper branch
- [X] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
As soon as it's illustration, I propose to make the animation several times slower.

**Comment by catree** [comment]
Ideally, I would prefer to add a link to a YouTube video url (see https://github.com/opencv/opencv/pull/22130#issuecomment-1195932710).

A slower gif would take much more disk space.

**Review by vpisarev — CHANGES_REQUESTED** [review]
replace gif with static image (jpeg)

**Comment by catree** [comment]
@vpisarev Done.

@asmorkalov If needed, I can also "backport" these changes to the 4.x branch.

**Comment by asmorkalov** [comment]
"backport" to 4.x is not required. I'm working on 3.4 -> 4.x merge right now.

**Review by vpisarev — APPROVED** [review]

**Pull request merged**
