### PR TITLE
Created opencv_stitching_tool App (based on Python API)

### PR DESCRIPTION
**Pull request by lukasalexanderweber**
relates #20744 #20723
tutorial needs data from https://github.com/opencv/opencv_extra/pull/915

## Introduction

The advanced stitching example [stitching_detailed.py](https://github.com/opencv/opencv/blob/master/samples/python/stitching_detailed.py) is a big script with awesome functionality. It is, however, very long and a bit unstructured to grasp what's going on. It's by far the most complex script in the [python samples folder](https://github.com/opencv/opencv/tree/master/samples/python):

samples_line_distribution

There is, however, a very clear [pipeline description](https://github.com/opencv/opencv/blob/master/modules/stitching/doc/StitchingPipeline.jpg?raw=true).

## Refactoring

I [changed the stitching_detailed.py](https://github.com/lukasalexanderweber/opencv/blob/master/samples/python/stitching_detailed.py) so that it only contains the argument parser. At the end, the functionality of the [stitcher](https://github.com/lukasalexanderweber/opencv/blob/master/samples/python/stitching_detailed/stitcher.py) class is called. The stitcher class follows precisely the stitching pipeline of the image. Unlike in the original program, the intermediate results can be obtained and analysed easily. 

I didn't changed much of the functionality, the most work was done in structuring the functionality.

I added the possibility to specify the number of features (default 500) in the Feature Detection step, since 500 features are not enough for my REALY big plans (see [this issue/question](https://github.com/opencv/opencv/issues/17508)).

The final results (from blender or timelapser) are returned in 8-bit numpy arrays so they can be saved on disk and viewed using cv.imshow(). The conversion is done using [cv::convertScaleAbs](https://docs.opencv.org/4.5.3/d2/de8/group__core__array.html#ga3460e9c9f37b563ab9dd550c4d8c4e7d)

Problems during the stitching pipeline raise a `StitchingError`

Additionally, I added functionality to subset the matches and cameras, which was not done in the original file. If there are noise images at the beginning, this leads to significant artefacts:

`python stitching_detailed.py s1.jpg s2.jpg boat5.jpg boat2.jpg boat3.jpg boat4.jpg boat1.jpg boat6.jpg --compose_megapix 3 --output boat_default_with_noise_original.jpg --save_graph boat_default_with_noise_original.txt`

boat_default_with_noise_original

With the proposed changes, this is not an issue anymore. The performance speed is the same as before the restructuring, the RAM needed reduced for the boat example from 130MB to 95MB. See [test_performance.py](https://github.com/lukasalexanderweber/opencv/blob/master/samples/python/stitching_detailed/test/test_performance.py). The tests can be found [here](https://github.com/lukasalexanderweber/opencv/blob/master/samples/python/stitching_detailed/test). With a view to the [tutorial](https://docs.opencv.org/4.5.1/d8/d19/tutorial_stitcher.html), I tested different settings for the boat example as well as the affine example of the budapest map within [test_stitcher.py](https://github.com/lukasalexanderweber/opencv/blob/master/samples/python/stitching_detailed/test/test_stitcher.py)

## Drawing Functionality

For intermediate results I added some drawing functionality, e.g. the match inliers or the seam masks upon the final panorama:

index
index3

## Tutorial

For the refactored functioality and the new drawing functionality I created a [Jupyter Notebook Tutorial](https://github.com/lukasalexanderweber/opencv/blob/master/samples/python/stitching_detailed/tutorial/Stitching%20Tutorial.ipynb).

## Background 

I need to stitch >10000 plans of waterway-infrastructure buildings. During digitalization, the scanner was too small for the whole plan. There are overlaps that allow the use of the stitching algorithm and I'm thankful that OpenCV contains the stitcher module. For documentation purposes for my work I wanted to structure the code and now hope to discuss if the changes might could merged into the opencv master branch.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

```
opencv_extra=
force_builders=docs
```

### CODE REVIEW

**Comment by catree** [comment]
> I need to stitch >10000 plans of waterway-infrastructure buildings.

Wondering if [Microsoft ICE](https://www.microsoft.com/en-us/research/product/computational-photography-applications/image-composite-editor/) software would be able to stitch these many images?
I believe for regular photo use cases, the ICE software will produce better results. But I am wondering if it would be able to handle lots of images?

If you want to give it a try, you can download it [here](https://web.archive.org/web/20180708164707/https://download.microsoft.com/download/7/3/9/73918E0B-C146-40FA-B18C-EADF03FEC4BA/ICE-2.0.3-for-64-bit-Windows.msi).

**Comment by lukasalexanderweber** [comment]
@catree thanks for the tip! I am very happy with the performance of the opencv algorithm. My work is part of a research project and I am happy to have complete control over the stitching process. Also, my institute focuses on working with and improving open source software. I just want to share the (for me it seems like) improvements I did :)

**Comment by catree** [comment]
:+1:  Any effort to improve OpenCV is really great.

---

I am using ICE to stitch my personal photos since it is really easy to use and provide good results for me. I was just wondering if ICE would be able to deal with 10000 images, independently of the performance of OpenCV.

**Comment by lukasalexanderweber** [comment]
I can't test it since I have some noise elements which were put on the plans during scanning (e.g. Barcodes). I resize the scans to medium resolution through the OpenCV Stitcher API, then remove noise elements using object detection, and then match the images (since the Barcodes disturb a correct matching). So I'm quite sure ICE wouldn't work as I desire.

**Comment by alalek** [comment]
@lukasalexanderweber Thank you for contribution!

Currently OpenCV samples are small enough applications that demonstrate OpenCV API.
Proposed application doesn't fit in this conception well. It looks like a heavy standalone app / tool based on OpenCV - it may confuse users who just start learning of OpenCV.

OpenCV Dev team need to discuss how to properly place this contribution and promote to users. I hope we will back with proposal in 2 weeks.

/cc @LaurentBerger

**Comment by LaurentBerger** [comment]
Nice contribution. 
About stitching_detailed.py I translate C++ code stitching_detailed.cpp in python to check all python binding of stitching module. 
If something change in C++ api  python binding can be check in stitching_detailed.py. I prefer that stitching_detailed.py stay as it is written and you change you source code name.

About App in opencv it's easy to include in opencv but how to maintain?

**Comment by lukasalexanderweber** [comment]
@LaurentBerger Thanks! Nice to know that it's a process of translating [cpp](https://github.com/opencv/opencv/blob/master/samples/cpp/stitching_detailed.cpp) directly in [py](https://github.com/opencv/opencv/blob/master/samples/python/stitching_detailed.py). 

On the long run it might be desirable to bring the cpp example to a similar structure as the here proposed (If I would know how to programm in C++ I would have done it directly..). I know that having background code on a single sample structured in modules/package is not exactly brilliant. However I think a clear structure (instead of 900 lines in one file) can rather help a new user than 

> it may confuse users who just start learning of OpenCV >

If this would happen, the [proposed Tutorial](https://github.com/lukasalexanderweber/opencv/blob/master/samples/python/stitching_detailed/tutorial/Stitching%20Tutorial.ipynb) could be converted into an official opencv tutorial as [SVMs](https://docs.opencv.org/master/d1/d73/tutorial_introduction_to_svm.html) where the user can switch between the programming languages. It would as well solve the maintainace problem. 

I'm open for any short-term suggestions where to put the code, if at all.

**Comment by lukasalexanderweber** [comment]
@alalek @asmorkalov I restored the work into the app folder

Please note https://github.com/opencv/opencv_extra/pull/915

**Comment by lukasalexanderweber** [comment]
@alalek I changed the tutoral image sizes from https://github.com/opencv/opencv_extra/pull/915 to https://github.com/opencv/opencv_extra/pull/919

**Comment by alalek** [comment]
@lukasalexanderweber You are right! Please open a new PR for this fix.

**Comment by lukasalexanderweber** [comment]
@alalek can you say if and when the App will be merged? I have a new Feature and would like to present it in a new Pull Request

**Comment by alalek** [comment]
Thank you for update!


Should we re-open opencv_extra PR: https://github.com/opencv/opencv_extra/pull/915 ?

BTW, opencv_extra usually contains test data for tests.

---

> apps/opencv_stitching_tool/opencv_stitching_tutorial/Stitching Tutorial.ipynb

This file is large >10Mb.
Need to discuss how to handle these files ("opencv" repo is large and growing fast, so we prefer to put here the code without large binary bundles).
I believe we could put a link to your dedicated repository with the tutorial code and related data (.ipynb + data from extra PR), something like https://github.com/lukasalexanderweber/opencv_stitching_tutorial (e.g., put link with minimal description into apps/opencv_stitching_tool/README.md).

**Comment by lukasalexanderweber** [comment]
> Should we re-open opencv_extra PR: opencv/opencv_extra#915 ?

I submitted a new PR with reduced image sizes: https://github.com/opencv/opencv_extra/pull/919

>  I believe we could put a link to your dedicated repository with the tutorial code and related data (.ipynb + data from extra PR), something like https://github.com/lukasalexanderweber/opencv_stitching_tutorial (e.g., put link with minimal description into apps/opencv_stitching_tool/README.md).

I moved the Tutorial into [opencv_stitching_tutorial](https://github.com/lukasalexanderweber/opencv_stitching_tutorial) and created a small [Readme](https://github.com/lukasalexanderweber/opencv/tree/master/apps/opencv_stitching_tool) with a link

**Comment by alalek** [comment]
Looks good!

Could you please move images from opencv_extra's PR to this tutorial repository? (probably in original non-compressed size)
As we don't use these images for tests here, we can place them near tutorial (and close opencv_extra's PR).

Please take a look on whitespace issues [here](http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/32755).
It would we nice if you could squash commits into one for this PR. It would allow to pass "patch size" check (git stores history of all used commits including removed files).

**Comment by lukasalexanderweber** [comment]
Please see https://github.com/opencv/opencv/pull/21020

**Pull request closed without merging**
