### PR TITLE
resolves #4958 cv::ml::StatModel::calcError not working for responses of type CV_32S

### LINKED ISSUE #4958: cv::ml::StatModel::calcError not working for responses of type CV_32S
Transferred from http://code.opencv.org/issues/4258

```
|| Jochen Goertler on 2015-03-30 15:14
|| Priority: Normal
|| Affected: branch 'master' (3.0-dev)
|| Category: ml
|| Tracker: Bug
|| Difficulty: 
|| PR: 
|| Platform: Any / Any
```
## cv::ml::StatModel::calcError not working for responses of type CV_32S

```
I have posted this on the Q&A Forum:
http://answers.opencv.org/question/57171/cvmlstatmodelcalcerror-not-working-for-responses-of-type-cv_32s/
But did not receive answers.

I have a feature vector consisting of several ordered variables. My responses on the other hand are categorical and of type @CV_32S@. I now want to create a RTrees for this problem. The documentation of @TrainData::create()@ states that it is possible to have train data of type @CV_32S@:

??
responses – matrix of responses. If the responses are scalar, they should be stored as a single row or as a single column. The matrix should have type CV_32F or CV_32S (in the former case the responses are considered as ordered by default; in the latter case - as categorical)
??

In the documentation of @RTrees@ I can't find a reason for this to be illegal.

However if I train my @RTrees@ as described in the following gist:
https://gist.github.com/grtlr/b6195466421c9606b8f9

In *Case 1* and *Case 2* the output is something like the following:

<pre>
calc error: 46
pred error: 0.17
</pre> 

Only for *Case 3* the error is computed correctly:

<pre>
calc error: 24
pred error: 0.24
</pre>

Is this behavior desired? If so, maybe this should be clarified in the documentation of @StatModel@, @RTrees@ or @TrainData@?

The problem seems to be in this part of the @StatModel::calcError()@ method:

<pre>
...
float val = predict(sample);
float val0 = responses.at<float>(si);

if( isclassifier )
    err += fabs(val - val0) > FLT_EPSILON;
...
</pre>


If responses is of type int this would lead to a different val0 then expected?

I think this could be fixed by checking the type of responses and switching between @at<float>@ and @at<int>@?

I was quite confused, that @calcError@ returns a result between @0 <= x <= 100@, although the return type is float. In my opinion a return value between @0 <= x <= 1@ would be more appropriate. What do you think?
```
##### Jochen Goertler on 2015-03-30 15:15

```
If there are changes to be made, I could try to provide a pull request with the necessary fixes.
```
##### Maksim Shabunin on 2015-04-29 09:34

```
-   Target version set to 3.0
```

### PR DESCRIPTION
**Pull request by logic1988**
resolves #4958 
Update inner_functions.cpp
cv::ml::StatModel::calcError not working for responses of type CV_32S

### CODE REVIEW

**Comment by alalek** [comment]
This code is not efficient (type check in "for loop" should be moved out).
Or you may use something like `responses.convertTo(responses, CV_32F)`.

BTW, It will be great to have reproducer code for this problem (complete use case).

**Comment by vpisarev** [comment]
@logic1988, @alalek, I think, the code can be made sufficiently efficient if you put save `responses.type()` before running the loop:

<pre>
int rtype = responses.type();
for( i = 0; i < n; i++ )
{
  ...
  float val0 = rtype== CV_32S ? (float)responses.at<int>(si) : responses.at<float>(si);
}
</pre>

**Comment by alalek** [comment]
@vpisarev @logic1988 Patch is updated.

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
