### PR TITLE
Mat pretty printer: fix submatrix indexation

### PR DESCRIPTION
**Pull request by rogday**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [X] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by victor1234** [comment]
Add some comments for changes, pls

**Review by AleksandrPanov — APPROVED** [review]
LGTM, but there is still a problem with multi-channel `Mat`. I think that this problem should be fixed in another PR.

**Review by AleksandrPanov — APPROVED** [review]
multi-channel works now :+1:  :+1: :+1:

**Pull request merged**
