### PR TITLE
Update demosaicing.cpp

### LINKED ISSUE #18558: A typo in source code of Edge-aware demosaicing.
https://github.com/opencv/opencv/blob/1b443219ed181124978ed8627fb2da8db42765ab/modules/imgproc/src/demosaicing.cpp#L1587
The code
`D[2] = (S[-sstep-1] + S[-sstep+1] + S[sstep-1] + S[sstep+1]) >> 2;`
should be modifed to
`D[2] = (S[-sstep-1] + S[-sstep+1] + S[sstep-1] + S[sstep+1] + 2) >> 2;`

### PR DESCRIPTION
**Pull request by krush11**
fixes #18558

<cut/>

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by krush11** [comment]
fixes #18558

**Comment by alalek** [comment]
> from `unknown repository`

This PR can't be tested on CI (so it can't be merged).
You should not remove repository until merge.

**Review by NEMSIS14061 — COMMENTED** [review]
I

**Comment by krush11** [comment]
Sorry i am new to this so was just testing things. I have forked it the repo again. Will it be possible to do CI checks again or should i file a new PR?

**Comment by alalek** [comment]
State of this PR is not changed, so create new PR:

> from `unknown repository`

**Pull request closed without merging**
