### PR TITLE
features2d cleanup: Move several feature detectors and descriptors to opencv_contrib

### PR DESCRIPTION
**Pull request by kaingwade**
features2d cleanup: #24999

The PR moves KAZE, AKAZE, AgastFeatureDetector, BRISK and BOW to opencv_contrib/xfeatures2d.

Related PR: opencv/opencv_contrib#3709

```
force_builders=Custom
Xbuild_image:Docs=docs-js
build_image:Custom=javascript
build_image:Docs=docs-js:22.04-3.1.64
#build_image:Custom=javascript:3.1.64
buildworker:Custom=linux-4
buildworker:Docs=linux-4
```

### CODE REVIEW

**Comment by asmorkalov** [comment]
```
2024-03-29T08:23:41.6399573Z Discovering python tests from: /home/ci/opencv/modules/videoio/misc/python/test
2024-03-29T08:23:41.6400802Z Traceback (most recent call last):
2024-03-29T08:23:41.6402052Z   File "/home/ci/opencv/modules/python/test/test_algorithm_rw.py", line 15, in test_algorithm_rw
2024-03-29T08:23:41.6403874Z     gold = cv.xfeatures2d.AKAZE_create(descriptor_size=1, descriptor_channels=2, nOctaves=3, threshold=4.0)
2024-03-29T08:23:41.6405540Z AttributeError: module 'cv2' has no attribute 'xfeatures2d'
```

**Comment by asmorkalov** [comment]
I propose to migrate corresponding tutorials, python and java tests to contrib too.

**Comment by asmorkalov** [comment]
```
2024-03-29T08:22:31.7150331Z [ RUN      ] OCL_stitch_a123.a123/1, where GetParam() = "akaze"
2024-03-29T08:22:31.9278749Z Segmentation fault (core dumped)
2024-03-29T08:22:31.9801728Z ##[error]Process completed with exit code 139.
2024-03-29T08:22:32.0383796Z ##[group]Run cd $HOME/build && xvfb-run -a bin/opencv_perf_video --perf_impl=plain --perf_min_samples=1 --perf_force_samples=1 --perf_verify_sanity --skip_unstable=1 --perf_threads=16
2024-03-29T08:22:32.0386765Z [36;1mcd $HOME/build && xvfb-run -a bin/opencv_perf_video --perf_impl=plain --perf_min_samples=1 --perf_force_samples=1 --perf_verify_sanity --skip_unstable=1 --perf_threads=16[0m
2024-03-29T08:22:32.0388739Z shell: bash --noprofile --norc -e -o pipefail {0}
```

**Comment by asmorkalov** [comment]
Please pay attention on merge conflicts.

**Comment by kaingwade** [comment]
> I propose to migrate corresponding tutorials, python and java tests to contrib too.

Some of these tutorials are more about doing matching and tracking using the features which are to be migrated to contrib rather than the features alone, for example akaze_matching.markdown, akaze_tracking.markdown etc. Would replacing the features with one of those which are still in the main repo and keeping the tutorials be better than completely migrating them to contrib?

And quite a few examples in the documentation use the SURF feature which is in contrib, for example https://docs.opencv.org/4.x/d7/dff/tutorial_feature_homography.html. Should we replace SURF with another feature as well?
That's to say to keep as less as possible contrib related descriptions in the documention.

For tests, in many of them AKAZE is used as 'gold'. In this case will replace it with ORB or another feature which are in the main repo.

**Comment by asmorkalov** [comment]
@kaingwade there is conflict with documentation changes. Please rebase and fix the conflict.

**Review by asmorkalov — APPROVED** [review]
:+1:

**Pull request merged**
