### PR TITLE
Drawing performance

### PR DESCRIPTION
**Pull request by chacha21**
ICV_HLINE performance : call a single memset if the color is a several times the same byte

### CODE REVIEW

**Comment by vpisarev** [comment]
Did you measure the results of this optimization? To me it seems that the new version should be slower, not faster

**Comment by chacha21** [comment]
Yes, I did not write a Unit test, but a simple program drawing thousands of random rectangles shew a significand improvement (x2 for me).

**Comment by vpisarev** [comment]
well, acceleration is only possible if a drawn rectangle is black, white or gray, right? can you share your simple program?

**Comment by alalek** [comment]
If we really need acceleration, we probably should use C++ templates to "enable" compiler optimizations (at least for "channels/pix_size") - but this will increase binary size.

**Comment by chacha21** [comment]
Yes, the acceleration is possible if the rectangle has a the same color on all channels. Which is particularly useful when the image itself has only one channel.
Moreover, it is not limited to rectangles but to every polygon filling that use ICV_HLINE.
I will post my test program, but it is just a batch draw of random rectangles.

**Comment by chacha21** [comment]
So here is the sample code (compile in Release 64b under W7)

//just a helper function to get the next random number
size_t nextR(size_t& R, const std::vector<int>& cache, size_t mod)
{
  size_t result = cache[R]%mod;
  R = (R+1)%cache.size();
  return result;
}


int _tmain(int argc, _TCHAR* argv[])
{
  AllocConsole();

  //rpecompute a random cache so that the cost of rand() does not introduce a bias
  srand(1);
  std::vector<int> randomCache;
  randomCache.reserve(1U*1024*1024);
  for(size_t i = 0 ; i<randomCache.capacity() ; ++i)
    randomCache.push_back(rand());
  size_t R = 0;

  cv::Size imgSize(2048, 2048);
  //first, draw random rectangle in a 3-channels image
  {
    cv::Mat img(imgSize, CV_8UC3);
    R = 0;

    __int64 e1 = cv::getTickCount();
    for(size_t i = 0 ; i<10000U ; ++i)
    {
      cv::Rect r(nextR(R, randomCache, imgSize.width), nextR(R, randomCache, imgSize.height), nextR(R, randomCache, imgSize.width), nextR(R, randomCache, imgSize.height));
      cv::rectangle(img, r, cv::Scalar(nextR(R, randomCache, 256), nextR(R, randomCache, 256), nextR(R, randomCache, 256)), CV_FILLED);
    }
    __int64 e2 = cv::getTickCount();
    printf("optimization OFF : ticks for non uniform color = %.2fms\n", (e2-e1)/(cv::getTickFrequency()/1000));
  }

  //second, draw the exact same random rectangle in a 1-channel image
  {
    cv::Mat img(imgSize, CV_8UC1);
    R = 0;

    __int64 e1 = cv::getTickCount();
    for(size_t i = 0 ; i<10000U ; ++i)
    {
      cv::Rect r(nextR(R, randomCache, imgSize.width), nextR(R, randomCache, imgSize.height), nextR(R, randomCache, imgSize.width), nextR(R, randomCache, imgSize.height));
      cv::rectangle(img, r, cv::Scalar(nextR(R, randomCache, 256), nextR(R, randomCache, 256), nextR(R, randomCache, 256)), CV_FILLED);
    }
    __int64 e2 = cv::getTickCount();
    printf("optimization OFF : ticks for uniform color = %.2fms\n", (e2-e1)/(cv::getTickFrequency()/1000));
  }

  return 0;
}

**Comment by chacha21** [comment]
And my result timings when using opencv compiled without or with the new ICV_HLINE

optimization OFF : ticks for non uniform color = 12821.89ms
optimization OFF : ticks for uniform color = 6926.90ms

optimization ON : ticks for non uniform color = 12793.86ms
optimization ON : ticks for uniform color = 397.08ms

**Comment by vpisarev** [comment]
I'm afraid that this optimization will degrade performance significantly when you draw thin (but not 1 pixel-thin) lines or other such objects, because 1) the check whether pixel color is uniform or not is done each single time, 2) most often people draw things in color images and the drawn objects are not grayscale (so the check will likely fail, but you will spend time on it anyway).

I found that the following macro works well for both grayscale and color images:

<pre>
#define ICV_HLINE( ptr, xl, xr, color, pix_size )            \
if((pix_size) == 1)                                          \
{                                                            \
    uchar* hline_ptr = (uchar*)(ptr) + (xl);                 \
    uchar* hline_max_ptr = (uchar*)(ptr) + (xr);             \
    uchar hline_c = *(const uchar*)(color);                  \
                                                             \
    memset(hline_ptr, hline_c, (hline_max_ptr - hline_ptr) + 1);  \
}                                                            \
else if((pix_size) == 3)                                     \
{                                                            \
    uchar* hline_ptr = (uchar*)(ptr) + (xl)*3;               \
    uchar* hline_max_ptr = (uchar*)(ptr) + (xr)*3;           \
                                                             \
    for( ; hline_ptr <= hline_max_ptr; hline_ptr += 3)       \
    {                                                        \
        hline_ptr[0] = ((uchar*)(color))[0];                 \
        hline_ptr[1] = ((uchar*)(color))[1];                 \
        hline_ptr[2] = ((uchar*)(color))[2];                 \
    }                                                        \
}                                                            \
else                                                         \
{                                                            \
    uchar* hline_ptr = (uchar*)(ptr) + (xl)*(pix_size);      \
    uchar* hline_max_ptr = (uchar*)(ptr) + (xr)*(pix_size);  \
                                                             \
    for( ; hline_ptr <= hline_max_ptr; hline_ptr += (pix_size))\
    {                                                        \
        int hline_j;                                         \
        for( hline_j = 0; hline_j < (pix_size); hline_j++ )  \
        {                                                    \
            hline_ptr[hline_j] = ((uchar*)color)[hline_j];   \
        }                                                    \
    }                                                        \
}
</pre>

**Comment by chacha21** [comment]
I agree that it's hard to tell whether the small performance degradation to test for uniform color worth the try. 
But I vote for improving at least the case pix_size==1

**Comment by vpisarev** [comment]
special case pix_size == 3 (which, in my opinion, is much more common than pix_size == 1) also gave quite noticeable speedup, ~3x.

**Comment by chacha21** [comment]
You can also make a special case for (pix_size == 4) when the pixel address is 4-aligned. I notice a x10 improvement. But is this a common case ?

#define is_aligned(POINTER, BYTE_COUNT) \
    (((uintptr_t)(const void *)(POINTER)) % (BYTE_COUNT) == 0)

...
else if(((pix_size) == 4) && is_aligned(((uchar*)(ptr) + (xl)*4), 0x4)) \
{                                                            \
    uint32_t c;                                      \
    memcpy(&c, (uchar*)(color), sizeof(c));                  \
    uint32_t* hline_ptr = (uint32_t*)(ptr) + xl;    \
    uint32_t* hline_max_ptr = (uint32_t*)(ptr) + xr;\
                                                             \
    for( ; hline_ptr <= hline_max_ptr; ++hline_ptr   )       \
        *hline_ptr = c;                                      \
}    
...

**Comment by chacha21** [comment]
For the case pix_size == 3, we could also optimize the part of the line that starts at a 0x4 multiple and has a length divisible by 12 bytes ; thus, three int32 would match 4 3-channel colors. yet again, there would be a good speed improvement. 
But how do we decide that it worth the cost of the test and the increment in code size ?

**Comment by chacha21** [comment]
Currently, this would give the following code :
````
#define is_aligned(POINTER, BYTE_COUNT) (((uintptr_t)(const void *)(POINTER)) % (BYTE_COUNT) == 0)

#define ICV_HLINE( ptr, xl, xr, color, pix_size )                 \
if((pix_size) == 1)                                               \
{                                                                 \
    uchar* hline_ptr = (uchar*)(ptr) + (xl);                      \
    uchar* hline_max_ptr = (uchar*)(ptr) + (xr);                  \
    uchar hline_c = *(const uchar*)(color);                       \
                                                                  \
    memset(hline_ptr, hline_c, (hline_max_ptr - hline_ptr) + 1);  \
}                                                                 \
else if((pix_size) == 3)                                          \
{                                                                 \
    uchar* hline_ptr = (uchar*)(ptr) + (xl)*3;                    \
    uchar* hline_end   = (uchar*)(ptr) + (xr+1)*3;                \
    uchar* hbody12_start = std::min(hline_end, (uchar*)(4*(((uint64)(hline_ptr)+3)/4)));  \
    uchar* hbody12_end = std::min(hline_end, (uchar*)(12*(((uint64)(hline_end)+11)/12))); \
    if ((hbody12_start < hbody12_end))                       \
    {                                                        \
      uint32_t c4[3];                                        \
      uchar* ptrC4 = reinterpret_cast<uchar*>(&c4);          \
      ptrC4[0]  = ((uchar*)(color))[0];                      \
      ptrC4[1]  = ((uchar*)(color))[1];                      \
      ptrC4[2]  = ((uchar*)(color))[2];                      \
      ptrC4[3]  = ((uchar*)(color))[0];                      \
      ptrC4[4]  = ((uchar*)(color))[1];                      \
      ptrC4[5]  = ((uchar*)(color))[2];                      \
      ptrC4[6]  = ((uchar*)(color))[0];                      \
      ptrC4[7]  = ((uchar*)(color))[1];                      \
      ptrC4[8]  = ((uchar*)(color))[2];                      \
      ptrC4[9]  = ((uchar*)(color))[0];                      \
      ptrC4[10] = ((uchar*)(color))[1];                      \
      ptrC4[11] = ((uchar*)(color))[2];                      \
      for( ; hline_ptr < hbody12_start; hline_ptr)           \
      {                                                      \
         *hline_ptr++ = ((uchar*)(color))[0];                \
         *hline_ptr++ = ((uchar*)(color))[1];                \
         *hline_ptr++ = ((uchar*)(color))[2];                \
      }                                                      \
      for(uint32_t* ptr32 = reinterpret_cast<uint32_t*>(hbody12_start), *ptr32End = reinterpret_cast<uint32_t*>(hbody12_end) ; ptr32<ptr32End ; ) \
      {                                                       \
          *ptr32++ = c4[0];                                   \
          *ptr32++ = c4[1];                                   \
          *ptr32++ = c4[2];                                   \
      }                                                       \
      for(hline_ptr = hbody12_end ; hline_ptr < hline_end ; ) \
      {                                                       \
          *hline_ptr++ = ((uchar*)(color))[0];                \
          *hline_ptr++ = ((uchar*)(color))[1];                \
          *hline_ptr++ = ((uchar*)(color))[2];                \
      }                                                       \
    }                                                         \
    else                                                      \
    {                                                         \
      for( ; hline_ptr < hline_end ; )                        \
      {                                                       \
          *hline_ptr++ = ((uchar*)(color))[0];                \
          *hline_ptr++ = ((uchar*)(color))[1];                \
          *hline_ptr++ = ((uchar*)(color))[2];                \
      }                                                       \
    }                                                         \
}                                                             \
else if(((pix_size) == 4) && is_aligned(((uchar*)(ptr) + (xl)*4), 0x4)) \
{                                                              \
    uint32_t c;                                                \
    memcpy(&c, (uchar*)(color), sizeof(c));                    \
    uint32_t* hline_ptr = (uint32_t*)(ptr) + xl;               \
    uint32_t* hline_max_ptr = (uint32_t*)(ptr) + xr;           \
                                                               \
    for( ; hline_ptr <= hline_max_ptr; ++hline_ptr   )         \
        *hline_ptr = c;                                        \
}                                                              \
else                                                           \
{                                                              \
    uchar* hline_ptr = (uchar*)(ptr) + (xl)*(pix_size);        \
    uchar* hline_max_ptr = (uchar*)(ptr) + (xr)*(pix_size);    \
                                                               \
    for( ; hline_ptr <= hline_max_ptr; hline_ptr += (pix_size))\
    {                                                          \
        int hline_j;                                           \
        for( hline_j = 0; hline_j < (pix_size); hline_j++ )    \
        {                                                      \
            hline_ptr[hline_j] = ((uchar*)color)[hline_j];     \
        }                                                      \
    }                                                          \
}
````

**Comment by vpisarev** [comment]
sorry for the delay. The code for 4-channel data relies on a particular order of bytes within 32-bit integer (little-endian vs big-endian). I suggest not to include 4-channel code for now. Maybe a bit later. Please, submit a fresh PR with the patch included; this PR contains some irrelevant commits from other PRs.

**Comment by chacha21** [comment]
I really think that the optimization for 3 and 4 channels worht the work
I have submitted #8182 with additional code for endianness

**Pull request closed without merging**
