### PR TITLE
Transforms now use a grid stride loop to enable execution on larger d…

### PR DESCRIPTION
**Pull request by dtmoodie**
### This pullrequest changes

Previously transformSimple used a traditional indexing method, this method fails when a single dimension of the input data is such that the calculated grid dimension exceeds the limitations set by CUDA.  This pull request changes transformSimple to using a grid stride loop. 
https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-write-flexible-kernels-grid-stride-loops/

I still have some performance testing to do, and I need to validate it on a larger dataset, but this change passes both relevant CUDA performance and accuracy tests.

### CODE REVIEW

**Comment by alalek** [comment]
@dtmoodie Please remove trailing whitespaces.

**Comment by dtmoodie** [comment]
Hello,  I've made the corrections and pushed them back onto my branch.

**Comment by jet47** [comment]
This approach leads to performance degradation, especially for `CV_64F` case, which uses `transformSimple` branch (up to 10x slowdown).

```
                                  Name of Test                                       old       new       new    
                                                                                                          vs    
                                                                                                         old    
                                                                                                      (x-factor)
AbsDiffScalar::Sz_Depth::(1280x720, CV_8U)                                        0.035 ms  0.058 ms     0.60   
AbsDiffScalar::Sz_Depth::(1280x720, CV_16U)                                       0.036 ms  0.061 ms     0.59   
AbsDiffScalar::Sz_Depth::(1280x720, CV_32F)                                       0.059 ms  0.061 ms     0.97   
AbsDiffScalar::Sz_Depth::(1280x720, CV_64F)                                       0.117 ms  1.363 ms     0.09   
AbsDiffScalar::Sz_Depth::(1280x1024, CV_8U)                                       0.044 ms  0.075 ms     0.59   
AbsDiffScalar::Sz_Depth::(1280x1024, CV_16U)                                      0.077 ms  0.110 ms     0.70   
AbsDiffScalar::Sz_Depth::(1280x1024, CV_32F)                                      0.084 ms  0.081 ms     1.04   
AbsDiffScalar::Sz_Depth::(1280x1024, CV_64F)                                      0.145 ms  1.473 ms     0.10   
AbsDiffScalar::Sz_Depth::(1920x1080, CV_8U)                                       0.062 ms  0.111 ms     0.56   
AbsDiffScalar::Sz_Depth::(1920x1080, CV_16U)                                      0.068 ms  0.119 ms     0.57   
AbsDiffScalar::Sz_Depth::(1920x1080, CV_32F)                                      0.119 ms  0.158 ms     0.76   
AbsDiffScalar::Sz_Depth::(1920x1080, CV_64F)                                      0.228 ms  1.552 ms     0.15   
```

I tried to use smaller grid for `transformSimple` - `(32, 32)` instead of `(32*16, 32*16)`. It improves performance, but still slower than current approach.

Maybe it will be better to leave both approaches - simple indexing and grid stride and choose it based on image dimensions?

**Comment by dtmoodie** [comment]
Thanks for looking into that, I'll implement a selection based on image dimension.

**Comment by jet47** [comment]
BTW, you can compare performance by running:

```
$ ./opencv_perf_cudaarithm --gtest_output=xml:report.xml
```

and compare two reports via:

```
$ python opencv/modules/ts/misc/summary.py report1.xml report2.xml
```

**Comment by vpisarev** [comment]
let's close this PR for now

**Pull request closed without merging**
