### PR TITLE
cvtColor: fix inplace processing

### LINKED ISSUE #6653: cvtColor and UMat error.
Win7 x64, MSVC 2013, cmake 3.3.2, branch 3.1.0-165-gba1d3ef.

Error if as argument for cvtColor used the same UMat and opencl support disabled by ocl::setUseOpenCL(false);

UMat frame;
cvtColor(frame, frame, CV_BGR2GRAY);

### PR DESCRIPTION
**Pull request by alalek**
resolves #6653

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by mshabunin** [comment]
PR is merged, but GitHub does not show correct status.

**Comment by zchrissirhcz** [comment]
@alalek  Hi, I'm late here, but observed that this PR makes "inplace rgb2bgr" operation slow for cv::Mat. 

Specifically, for a `h=4032, w=3024` rgb image, on android arm64 phone (QCOM855) with OpenCV4.5 (neon enabled, carotine lib used), this code:
```c++
cv::Mat image = cv::read("rgb.png");
cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
```
costs 15 ms, while my own naive implentation only costs 5 ms
```c++
void rgb2bgr_inplace_naive(unsigned char* buf, size_t height, size_t width)
{
    unsigned char tmp = 0;
    size_t len = height * width *3;
    for (size_t i=0; i<len; i+=3) {
        tmp = buf[i];
        buf[i] = buf[i+2];
        buf[i+2] = tmp;
    }
}
```
and I figured out the "magic" is the change in this commit, i.e.:
```c++
        if (_src.getObj() == _dst.getObj()) // inplace processing (#6653)
            _src.copyTo(src);  // !! this copy makes more time cost
        else
            src = _src.getMat();
```

Is there any better solution, that keeps arm neon performance for inplace rgb2bgr, and also resolve #6653 ?

**Comment by zchrissirhcz** [comment]
Tested with the following code, which is more faster (3ms on my android arm64):
```c++
cv::Mat image = cv::read("rgb.png");
cv::Mat image_copy = image;
cv::cvtColor(image_copy, image, cv::COLOR_BGR2RGB);
```

Is the usage OK? In this usage, `_src.getObj() == _dst.getObj()` is false, but `image.data == image_copy.data` is true.

**Pull request closed without merging**
