### PR TITLE
Installation tutorials rework

### PR DESCRIPTION
**Pull request by mshabunin**
Changes:
* Created "Installation overview" and "Configuration reference" tutorials.
* Updated "Linux installation" tutorial.
* Added scripts for automatic checks of installation for Ubuntu 18
* General tutorials: moved "Author" and "Version" information from listing into tutorials, marked some tutorials "Obsolete"
* Minor CSS doxygen changes

[Demo](http://pullrequest.opencv.org/buildbot/export/pr/18195/docs/df/d65/tutorial_table_of_content_introduction.html)

<cut/>

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch ❔ 
- [ ] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
BTW, There is something wrong with new logo.
This style can fix that:
```
#projectlogo
{
	text-align: center;
	vertical-align: center;
	border-collapse: separate;
	padding-left: 0.5em;
}
```

**Comment by mshabunin** [comment]
@alalek , @asmorkalov , I think the PR can be considered ready for review. There are still some unfinished things in "Config reference", but I believe the focus of the PR should be on "Installation overview" and "Installation in Linux'. We can restructure and update config reference later with Windows/OSX/ARM/Android installation tutorials updates.

**Comment by mshabunin** [comment]
Looks like Javadoc build is broken due to some reasons.

**Review by alalek — APPROVED** [review]
Well done! Thank you :+1:

**Pull request merged**
