### PR TITLE
Add maximum, minimum layers ( target_cuda, target_cpu)

### PR DESCRIPTION
**Pull request by Crayon-new**
Signed-off-by: Crayon-new <1349159541@qq.com>

**Merge with extra:** https://github.com/opencv/opencv_extra/pull/950
op link:  https://devdocs.io/tensorflow~1.15/math/maximum

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
buildworker:Custom=linux-4,linux-6
Xbuild_image:Custom=ubuntu-cuda:18.04
build_image:Custom=ubuntu-cuda-cc52:18.04
test_modules:Custom=dnn
```

### CODE REVIEW

**Comment by rogday** [comment]
Hi, @Crayon-new. We have `EltwiseLayer`, which is implemented for OpenCL, CUDA and CPU and supports min, max, sum, prod and div operations on its inputs. If my understanding is correct, `Minimum` and `Maximum` layers can be implemented using `EltwiseLayer`(e.g. if hasConstBlob is true, we can add proxy `Const` layer for this blob and connect it to the node). If you tried implementing it this way, can you share benefits(performance or otherwise) of your solution?

**Comment by Crayon-new** [comment]
> Hi, @Crayon-new. We have `EltwiseLayer`, which is implemented for OpenCL, CUDA and CPU and supports min, max, sum, prod and div operations on its inputs. If my understanding is correct, `Minimum` and `Maximum` layers can be implemented using `EltwiseLayer`(e.g. if hasConstBlob is true, we can add proxy `Const` layer for this blob and connect it to the node). If you tried implementing it this way, can you share benefits(performance or otherwise) o

**Comment by Crayon-new** [comment]
@rogday  Thanks for your reply, I have noticed `eltwise_layer`, and I used it for the "two inputs" case. I used element_wise layer to implement the "one_input" case because i saw this in eltwise_layer.
QQ图片20220110154034
So is there a way to take const as input? I may use it.

**Comment by rogday** [comment]
> @rogday Thanks for your reply, I have noticed `eltwise_layer`, and I used it for the "two inputs" case. I used element_wise layer to implement the "one_input" case because i saw this in eltwise_layer. QQ图片20220110154034 So is there a way to take const as input? I may use it.

Yes, you may want to look at `parseConcat` for reference.

**Comment by Crayon-new** [comment]
@rogday Thank you! I may convert this pr to draft first.

**Comment by Crayon-new** [comment]
@rogday Excuse me, I have another question, dose `eltwise` surpport broadcasting? such as taking vector or scalar as the second input.

**Comment by rogday** [comment]
> @rogday Excuse me, I have another question, dose `eltwise` surpport broadcasting? such as taking vector or scalar as the second input.

It seems that the number of channels can differ, but as for everything else - one needs to look closely at `getMemoryShapes()` and its assertions. If you encounter problems with current implementation, it may be better to enhance it than to add another layer - it may benefit other layers implemented using `ElementwiseLayer`(like @zihaomu noted, broadcasting for `Mut` op is implemented through `Scale` right now). By enhancement I mean something non-allocating, since there are works for the fallback scenario: https://github.com/opencv/opencv/pull/21415.

**Comment by asmorkalov** [comment]
@Crayon-new Thanks for the contribution! Do you have any progress with the patch?

**Comment by Crayon-new** [comment]
> @Crayon-new Thanks for the contribution! Do you have any progress with the patch?

Sorry for taking so long. According to discussions with rogday and the details in `eltwise layer`, broadcasting cannot be supported for now, so some test cases cannot pass. But I noticed this pr: #21449, and I may create another pr when rogday finished that work.

**Pull request closed without merging**
