### PR TITLE
Bugfix 3186 second

### PR DESCRIPTION
**Pull request by StevenPuttemans**
As mentioned in bugfix 3186 (http://code.opencv.org/issues/3186)

Tried to incorporate remarks made in last pull request, which got merged but then reverted back due to breaking stuff down. (https://github.com/Itseez/opencv/pull/1376)

### CODE REVIEW

**Comment by lopsided98** [comment]
I would like to be able to fix this bug. I'll check it out myself, but does anyone know what part of the PR actually broke the build?

**Comment by StevenPuttemans** [comment]
Not really sure what you are going to fix? This is a PR from 2013 which has since then been solved as far as I know...

**Comment by lopsided98** [comment]
This bug was never fixed. The PR was reverted, and the problem still occurs. I was able to update the patch to fix it, though, and will submit a new PR when I have time.

**Comment by alalek** [comment]
@lopsided98 Thanks! Looks like this fix is available in master branch (see #6313). Could you try it?

**Pull request merged**
