### PR TITLE
Update to add window position and size retrieval to HighGUI

### PR DESCRIPTION
**Pull request by GregoryMorse**
Add read only property retrieval (window width, height, position x and y) for enhanced rendering capabilities and more sophisticated research tools

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for contribution!
Could you add some test for this functionality in highgui module?

BTW, Do we need to process/flush UI messages queue (in terms of Win32) to put window on its final position?

**Comment by GregoryMorse** [comment]
As for Windows, since this must be called from the UI thread (at least in the spirit of the rest of the current code, as only GTK appears to generalize this to arbitrary thread), then GetWindowRect will cause a SendMessage with a WM_RECT, which would cause the message queue to clear/flush while it blocked to process so there is no issue.  I am setting up for the test of the code now.  But I realize a problem with this design.  It is not useful without the trackbar height.  The idea of drawing an image to the exact window size to avoid the scaling requires precise knowledge of the image size, not just the effective window size.  And the trackbar height is the only missing link here if one is present.  I added code for Carbon and Cocoa, and WinRT would be relatively easy to add, though several other calls and features for WinRT were also not added so its questionable how useful this would be without them.

**Comment by alalek** [comment]
> GetWindowRect

Perhaps GetClientRect may help:
https://stackoverflow.com/questions/7561049/what-is-the-difference-between-getclientrect-and-getwindowrect-in-winapi

I believe, for the first version it is fine to support windows without additional controls only. And return -1 in cases of custom controls.

**Comment by GregoryMorse** [comment]
Yes you are absolutely right - further the StretchBlt call which gives the computation of the image size is using this.  In fact the toolbar should be irrelevant in all contexts if this is done properly.  The screen coordinates of the upper left of the image display location is largely a novelty to include but is possible.  The dimensions are very useful.

**Comment by GregoryMorse** [comment]
Next attempt at working and careful solution for cross platform proper computation of the image screen position and size on the window.

**Comment by GregoryMorse** [comment]
By changing the test code to call the new code, the automatic build checks are failing, but it seems to have nothing to do with the changes (Android and iOS only):
POST git-upload-pack (947 bytes)
error: RPC failed; result=56, HTTP code = 0
fatal: The remote end hung up unexpectedly

**Comment by alalek** [comment]
@GregoryMorse Does this patch ready for final review?

**Comment by GregoryMorse** [comment]
Yes it appears ready though I must admit not fetching the width and height atomically is largely already a disadvantage for the very precautious app developer.  But the change has even been hand verified in the debugger on Windows.  Also the X and Y positions of the upperleft screen position of the image are hard to reason or test about their exact correctness and their usefulness is questionable.  But the change compiles, and only is used for those who query such info, with proper error checking at any rate.  So final review is okay.

**Comment by alalek** [comment]
> width and height atomically

I believe it is natural to have `bool cv::getWindowRect(const cv::String& window_name, CV_OUT cv::Rect& rect)` function instead of read-only properties.

BTW, C++  way is to use `cv::Rect cv::getWindowRect(const cv::String& window_name)` with exception in case of error/not supported (like trackbar) - exception with clear message is more useful than "bool" result.

getWindowRect (whole image area with title) or getWindowImageRect (client area only for image painting)?

P.S. What is about multi-monitor configurations? (need to check implementation of `cv::moveWindow()` if it is supported)

**Comment by vpisarev** [comment]
@GregoryMorse, thanks for the contribution! looks useful!

**Comment by GregoryMorse** [comment]
It is final now with the change made, returning errors as cv::Rect(-1, -1, -1, -1) for now in consistency with the other code.  A width and height of 0 means the window is minimized at least on Windows and should probably be documented as such.

**Comment by GregoryMorse** [comment]
I updated my initial comment, as GetWindowRect/GetClientRect very well do not at least in a documented way use SendMessage and may very well use the data structure as specified in CreateWindow arguments for retrieving the window rectangle (client rect almost certainly just uses the window rect and origins to 0, 0 and adjusts width and height appropriately as right-left+1, bottom-right+1).  I am not sure if it flushes the queue or not.  But its likely thread safe in general regardless.  As to desiring a flush of the queue, since generally the context is for resizing live video with overlays, the issue works itself out over a frame as the old frame would be scaled (undesirably) for a very short period.

Multiple monitor support is partially working in HighGUI.  If the window gets too wide (more than a monitor), I cannot shrink it again without manually editing the registry values where the width is persisted.  Otherwise it works fully, even showing negative top or left values when the origin screen is aligned as such.  GetClientRect has already abstracted this away so for this change its not important.

**Comment by GregoryMorse** [comment]
It is final now with the change made, returning errors as cv::Rect(-1, -1, -1, -1) for now in consistency with the other code. A width and height of 0 means the window is minimized at least on Windows and should probably be documented as such.

**Pull request merged**
