### PR TITLE
Fix clipping bug in SQDIFF_NORMED template matching

### PR DESCRIPTION
**Pull request by danielenricocahall**
Addresses https://github.com/opencv/opencv/issues/15215 regarding `CV_TM_SQDIFF_NORMED`  clipping at 1.0, despite the range being > 1. The test case is the example presented in the ticket.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by danielenricocahall** [comment]
Hi @vpisarev! I'm having some trouble addressing the last few failing tests for the CL builds + Mac build. They all seem to be the same, and I can't replicate locally. It looks like the norm is still being clipped at 1 when the difference is computed - do you have any thoughts/suggestions?

**Comment by asmorkalov** [comment]
There is OpenCL implementation of `MatchTemplate` that follows the original function logic: https://github.com/opencv/opencv/blob/3.4/modules/imgproc/src/opencl/match_template.cl

**Comment by danielenricocahall** [comment]
> There is OpenCL implementation of `MatchTemplate` that follows the original function logic: https://github.com/opencv/opencv/blob/3.4/modules/imgproc/src/opencl/match_template.cl

@asmorkalov yes I saw that - I made changes to the function in that file to match the new logic, but it doesn't appear to be addressing the issue. With SQDIFF Normed, we should just be taking the numerator and the denominator with no conditionals.

**Comment by asmorkalov** [comment]
@alalek I created PR https://github.com/opencv/opencv_extra/pull/916 for sanity check update. Please take a look.

**Comment by alalek** [comment]
@asmorkalov Public CI is not able to collect patches from different users (not implemented because it is unusual case)

**Comment by asmorkalov** [comment]
Replacement: https://github.com/opencv/opencv/pull/20770

**Pull request closed without merging**
