### PR TITLE
Grammar fixes for python core operations docs

### PR DESCRIPTION
**Pull request by collinbrake**
### This pullrequest improves the grammar in the following sections:
- Basic Operations on Images
- Arithmetic Operations on Images
- Performance Measurement and Improvement Techniques

### CODE REVIEW

**Comment by alalek** [comment]
Please fix whitespace issues:
```
doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.markdown:73: trailing whitespace.
+Image properties include number of rows, columns, and channels; type of image data; number of pixels; 
```

**Comment by collinbrake** [comment]
@alalek Does my commit above fix the issue, or are there more cases of trailing whitespace? Should I squash the two commits above or keep as is?

**Comment by collinbrake** [comment]
@asmorkalov I am going to revert these changes on a different branch -- closing pull request.

**Comment by alalek** [comment]
No need to re-create new PRs.
Just push changes into source branch of your fork.

**Comment by asmorkalov** [comment]
@collinbrake The grammar fixes look good to me :+1:. Please squash your commits.

**Comment by collinbrake** [comment]
@asmorkalov Thanks for your help with this! I was planning to squash the commits, so I probably should have labeled this PR as a work in progress until I got that finished.

**Pull request merged**
