### PR TITLE
make NEON more similar to SSE2

### PR DESCRIPTION
**Pull request by vpisarev**
### What does this PR change?
 - Add inline functions which let NEON available to work like SSE2
 - unpack and pack instructions

### Former #6718

### CODE REVIEW

**Comment by vpisarev** [comment]
@cuda-geek, could you please review it?

**Comment by cuda-geek** [comment]
@tomoaki0705, I'm a bit confused by this contribution. You introduced a set of functions, but don't use any of them. What we have for now is 100% untested and unused code.

Could you please find and introduce to us an application for this functions before contributing them into OpenCV?

**Comment by ilya-lavrenov** [comment]
@cuda-geek, I believe we can close this request since the provided intrinsics are quite simple and it's better and easy to write the code using NEON directly.

**Comment by mshabunin** [comment]
@tomoaki0705 , please take a look at the [Universal Intrinsics](http://docs.opencv.org/master/df/d91/group__core__hal__intrin.html#gsc.tab=0), they allow you to write one code for NEON and SSE.

**Pull request closed without merging**
