### PR TITLE
Added CV_PROP_RW macro to keypoints

### PR DESCRIPTION
**Pull request by tezz-io**
As outlined in the feature request in the issue https://github.com/opencv/opencv/issues/21171 : the keypoints field has been made parsable by the bindings.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for contribution!

Please add simple Python test to ensure that this code works as expected:
https://github.com/opencv/opencv/blob/4.x/modules/stitching/misc/python/test/test_stitching.py

Prefer to test binding itself, not an accuracy of C++ code.

**Comment by tezz-io** [comment]
@alalek Please check if the added test is correct and I am happy to follow up.

**Comment by alalek** [comment]
Thank you for update!

There is a whitespace issue in this PR: http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/33206 (line of spaces)

But commits for this PR broke GitHub review page and we don't see malicious changes here.

> `Merge branch 'opencv:4.x' into 4.x`

We don't need this commit at all.
Please remove this commit from PR. E.g, you can use `git reset --hard HEAD~1` and then `git push --force ...`
Do NOT update "4.x" branch of your fork with unrelated changes of your fork until PR merge. See below.

> `from tezz-io:4.x`
> `4.x`

It is better to avoid using source branches with the names from upstream for creation of PRs.
You may want to update your fork but also this pushing unwanted updates to PRs, which we should avoid.

**Comment by tezz-io** [comment]
I have rolled back the merge and removed the whitespace new line. Please check if it works now. Thank you.

**Review by alalek — APPROVED** [review]
Thank you :+1:

**Pull request merged**
