### PR TITLE
cmake: fix CUDA world build

### LINKED ISSUE #14205: CUDA : OpenCV requires enabled 'cudev' module from 'opencv_contrib'
i am building opencv c++ on windows using the script here : https://docs.opencv.org/3.4.3/d3/d52/.... I enabled cuda, tests, perf_tests, docs and samples as i wanted to build eveything. but i get this compilation cmake error. I have installed CUDA toolkit 10.1 on my machine. CMake Error at modules/core/CMakeLists.txt:39 (message): CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib' repository: https://github.com/opencv/opencv_contrib Call Stack (most recent call first): modules/world/CMakeLists.txt:13 (include) modules/world/CMakeLists.txt:32 (include_one_module)

I believe the script sets opencv_contrib path which has cudev module. Unable to figure out what's going wrong here.
Prior i was able to build it and This started happening since 2 days.

### PR DESCRIPTION
**Pull request by alalek**
resolves #14205

```
force_builders=Custom
buildworker:Custom=linux-2
build_world:Custom=ON
docker_image:Custom=ubuntu-cuda:16.04
build_contrib:Custom=ON
```

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by PascalYIN** [comment]
Hello there, I am trying to build the latest released version (4.1.2) on ubuntu18.04 with cuda10.1, and I also get this error "OpenCV requires enabled 'cudev' module from 'opencv_contrib", I found the same issue here but I don't quite understand the solution, is that something that I need to do on my side ? How should I do exactly ?

**Comment by btbulxb** [comment]
@PascalYIN Did you solve this problem?  I found the same issue here but I don't quite understand the solution

**Comment by PascalYIN** [comment]
@btbulxb Sorry for not seeing your message, yes I solved this problem finally. You simply need to build opencv with "[opencv-contrib](https://github.com/opencv/opencv_contrib)", a repo provided by opencv. By following its instruction you can build opencv with CUDA, it's not very complicated.

**Comment by DeeKudlay** [comment]
That's not helpful at all. I have the contrib and reference it via -DOPENCV_EXTRA_MODULES_PATH. Does not solve the issue. he problem is that the flag HAVE_opencv_cudev is not enabled. There is no instructions for what enables it.

**Comment by nowhere-girl** [comment]
@DeeKudlay Me too, did you end up solve it ? I tried to put path to extra module as well to build with cuda, end up with more error instead. What is this cudev setting ? Not everyone understand how to put patch (like me, a student for example). Literally 2-3 people asking already how to do it.

**Comment by Totemi1324** [comment]
@alalek @PascalYIN When there's one thing I hate on programmer's forums is that one simply assumes everybody got the same skill level as they do and offending you when you don't understand something. Not everybody has that much experience and knowledge as you do, so _please_ can you explain **IN DETAIL** how to apply the above patch?
I have the flag -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules set and it still gives me this error:
CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'
  repository: https://github.com/opencv/opencv_contrib
And I don't recognize the above lines as any programming language or syntax, so can you _please_ tell us where exactly they should be inserted? Thank you!

**Comment by PascalYIN** [comment]
@Totemi1324 alalek is a contributor of the OpenCV repo and considering the number of new issues to which he should pay attention I suppose that he won't answer to your demand. I'm willing to respond you because I can feel the anger and disappointment that you felt and I totally understand that. I have had gone through the same things and I believe that I will still come across the same situation in the future. I am not a very skilled programmer so I don't have the right to judge you, which is neither the purpose of this message.

The thing is, when we are talking about similar errors, we don't necessarily have the same causes. What I have written above was exactly what I have gone through, no more supplementary operations, and it just worked. And that happened 6 months ago on a computer that I no longer use. So it is very difficult to recall any additional detail of the building stage.

I still remember the first time I tried to compile OpenCV with MinGW on Windows, I knew NOTHING about CMake and I didn't know what "make -j4" was and I was simply using only one thread to compile OpenCV. Each compilation took 3 hours and always failed at 70%-80%. I searched on the Internet for a solution but I couldn't find a single case which matched my problem. It took me three days to finish a successful compilation, because I had to try again and again the compilation with different settings.

If you are using CMake GUI, you will see that there are hundreds of flags or items to be set. An exceptionally checked flag can result in multiple errors during the compilation. Saying that one have followed the instruction and it didn't work is not helping since the reader is not able to know if you have omitted any conventional operations that is usually not noticed or not mentioned in the instructions. 

So if you still need help, please at least upload a snapshot of your settings.

**Comment by Totemi1324** [comment]
Hello @PascalYIN ,
Thank you for your help and understanding. I was just tired of running into the same errors again and again, I try to compile working Caffe with OpenCV for half a year now.
But this is some general behaviour that I could notice on almost any programming forums. I understand that you not always have the time, but there are many people just posting some code with neither a context nor an explanation, and this kind of posts just leaves me back frustrated.
Just because I'm wondering, how can you See wether somebody is a contributor or not? Because alalek's profile just appears as anybody else's. Or I just missed something, I don't know.
(Btw, with some struggle I finally succeeded on resolving my issues, the only thing I'm saying is that this could have been achieved much faster if there was a proper explanation.)

**Comment by PascalYIN** [comment]
@Totemi1324 you can check the insight tab of this repo and then on the left you will see "contributors"

**Comment by emanuel248** [comment]
If you have the latest version and still get this error it could be beacuse the path you've set in -D OPENCV_EXTRA_MODULES_PATH=....   does not point to the right directory containing opencv_contrib. If it is, the HAVE_opencv_cudev flag should be automatically set by cmake

**Comment by 4everZard** [comment]
> If you have the latest version and still get this error it could be beacuse the path you've set in -D OPENCV_EXTRA_MODULES_PATH=.... does not point to the right directory containing opencv_contrib. If it is, the HAVE_opencv_cudev flag should be automatically set by cmake

Thank you! This solves my problem.

**Comment by Matesanz** [comment]
> If you have the latest version and still get this error it could be beacuse the path you've set in -D OPENCV_EXTRA_MODULES_PATH=.... does not point to the right directory containing opencv_contrib. If it is, the HAVE_opencv_cudev flag should be automatically set by cmake

As @emanuel248  pointed the solution is checking that the flag **OPENCV_EXTRA_MODULES_PATH points to the correct folder.** Thanks.

**Comment by jc508** [comment]
and the 'correct' folder is the modules one.
If you are doing this with cmake on windows you have to use forward slashes /  in the path not the windows back slashes \.
So you cann't just paste it in from windows explorer!  - that cost me several hours!

**Comment by Wlamit39** [comment]
@nowhere-girl did you fix this issue? I'm also troubling with the same.

**Comment by ashBabu** [comment]
I noticed something that when I try to do 

```cmake -D CMAKE_BUILD_TYPE=Release -D WITH_CUDA=ON -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_GENERATE_PKGCONFIG=YES OPENCV_EXTRA_MODULES_PATH=/home/repo/opencv_contrib/modules BUILD_EXAMPLES=true  ..```,

 it gives me the error 

`CMake Error at modules/core/CMakeLists.txt:53 (message):
  CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'
  repository: https://github.com/opencv/opencv_contrib`

 but when I did 

`cmake -D WITH_CUDA=ON -D OPENCV_EXTRA_MODULES_PATH=/home/repo/opencv_contrib/modules  ..`,

 it worked. May be of some help to someone

**Comment by buzzkillionair** [comment]
OS: Ubuntu 20.04
OpenCV version: 4.5.5
OpenCV_Contrib version: 4.5.5

I am currently running into this error and have tried the suggestions but have had no luck. I am using Opencv 4.5.5 and opencv_contrib_4.5.5.  I have 
`-DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules`
Before I get the the error of
`CMake Error at modules/core/CMakeLists.txt:53 (message):
  CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'
  repository: https://github.com/opencv/opencv_contrib`

I also get this CMake error:
`CMake Error at cmake/OpenCVModule.cmake:274 (message):
  No modules has been found:
  ../opencv_contrib
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:356 (_glob_locations)
  cmake/OpenCVModule.cmake:385 (ocv_glob_modules)
  CMakeLists.txt:927 (ocv_register_modules)`
I am using ".." to replace my path because I am not really able to chare the full path information, but in my code the entire path is there.

**Comment by buzzkillionair** [comment]
> but when I did
> 
> `cmake -D WITH_CUDA=ON -D OPENCV_EXTRA_MODULES_PATH=/home/repo/opencv_contrib/modules ..`,
> 
> it worked. Clear the build folder first. May be of some help to someone.

OS: Ubuntu 20.04
OpenCV version: 4.5.5
OpenCV_Contrib version: 4.5.5

I am currently running into this error and have tried the suggestions but have had no luck. I am using Opencv 4.5.5 and opencv_contrib_4.5.5.  I have 
`-DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules`
Before I get the the error of
`CMake Error at modules/core/CMakeLists.txt:53 (message):
  CUDA: OpenCV requires enabled 'cudev' module from 'opencv_contrib'
  repository: https://github.com/opencv/opencv_contrib`

I also get this CMake error prior to the cudev issue:
`CMake Error at cmake/OpenCVModule.cmake:274 (message):
  No modules has been found:
  ../opencv_contrib
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:356 (_glob_locations)
  cmake/OpenCVModule.cmake:385 (ocv_glob_modules)
  CMakeLists.txt:927 (ocv_register_modules)`
I am using ".." to replace my path because I am not really able to chare the full path information, but in my code the entire path is there.

**Pull request merged**
