### PR TITLE
ffmpeg: try to load ffmpeg wrapper dll from the current module directory

### LINKED ISSUE #6720: Python module can not find ffmpeg dll
### Please state the information for your system
- OpenCV version: 3.1.0
- Host OS: Windows Vista

### In which part of the OpenCV library you got the issue?
videocapture

### Additional description
When opencv3 is installed into virtualenv on Windows using opencv_python-3.1.0-cp27-cp27m-win32.whl from http://www.lfd.uci.edu/~gohlke/pythonlibs/ it is unable to use its .dlls unless those copied into the dir with script.

### PR DESCRIPTION
**Pull request by alalek**
resolves #6720

### CODE REVIEW

**Comment by apavlenko** [comment]
:+1: 
verified on Win 8.1 x64 and Python 2.7 x64

**Comment by techtonik** [comment]
Awesome. Is there a way how to test this without compiling everything myself? Nightly builds or something?

**Comment by alalek** [comment]
@techtonik Currently there are no public artifacts of nightly builds. Also we don't prepare Python .whl packages similar to [this](http://www.lfd.uci.edu/~gohlke/pythonlibs/#opencv)

**Comment by techtonik** [comment]
@alalek I found this - https://github.com/skvark/opencv-python - which is able to produce build artifacts - https://ci.appveyor.com/project/skvark/opencv-python/build/artifacts - is it worthy to propose this for merging?

**Comment by alalek** [comment]
There artifacts don't include ffmpeg wrapper. But you can built it yourself using command from build scripts.

**Comment by techtonik** [comment]
Right. But I see it is being copied, so I rebuilt opencv from current HEAD (https://ci.appveyor.com/project/techtonik/opencv-python/build/artifacts), placed `opencv_ffmpeg310.dll` next to it and it worked! =)

**Pull request merged**
