### PR TITLE
Fixed removing is_parameter, is_constant, is_output

### PR DESCRIPTION
**Pull request by ilyachur**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by ilyachur** [comment]
@dkurt Please take a look!

!!! This PR should be merged at the same moment with https://github.com/openvinotoolkit/openvino/pull/1324

**Comment by alalek** [comment]
@ilyachur @ilya-lavrenov 

> the same moment

In general, this doesn't work in that way.

Right process of public API change is below:
- add new API. But don't remove old one (provide compatibility shims for old API), mark old API deprecated. Merge that patch.
- next, some timeframe for updating all* dependent code (like OpenCV), which should migrate on new API only.
- finally, remove old API.

**Comment by ilyachur** [comment]
> In general, this doesn't work in that way.

@alalek Does it means that I should split my PR on OpenVINO side on two parts, add new methods after that merge this PR to OpenCV and only after that remove these methods in the OpenVINO?

**Comment by alalek** [comment]
Yes.

OV product config is for testing/validation only. It can't help with merge.

**Comment by ilyachur** [comment]
Ok, I will revert removed methods in order to merge this PR.

**!!! This pr can be merged only after this PR: https://github.com/openvinotoolkit/openvino/pull/1324**

**Comment by dkurt** [comment]
Tested with IE master branch (https://github.com/openvinotoolkit/openvino/commit/f7d6711137d24aba7d84846b2b60718a950bf05f) - works

**Pull request merged**
