### PR TITLE
highgui: Make GThread mandatory with GTK

### PR DESCRIPTION
**Pull request by tintou**
The GThread API is available since more than 11 years with GLib, it is now safe to assume that it is always available.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
Even in Ubuntu 12.04 GThread is part of  libglib package. So the cleanup makes sense. Could you push empty commit to re-trigger CI?

**Comment by asmorkalov** [comment]
@tintou Please rebase and fix conflicts. I merged older PR for OpenGL support with GTK3. Sorry for often pushes.

**Comment by tintou** [comment]
@asmorkalov done, no worries :slightly_smiling_face:

**Review by asmorkalov — APPROVED** [review]

**Comment by asmorkalov** [comment]
@opencv-alalek Please update hooks:
```
CMake Warning at /build/precommit_linux64/ci/cmake_checks/cmake_checks.cmake:105 (message):
  Manual validation is requied.  Variable is not defined: HAVE_GTHREAD
Call Stack (most recent call first):
  /build/precommit_linux64/ci/cmake_checks/precommit_linux64/POST_FINALIZE.cmake:94 (build_validate_enabled_flag)
  cmake/OpenCVUtils.cmake:65 (include)
  CMakeLists.txt:2007 (ocv_cmake_hook)
```

**Comment by opencv-alalek** [comment]
Relaxed CI validation checks.

**Pull request merged**
