### PR TITLE
Enhance GigE support: Add BayerGR8 support for aravis

### PR DESCRIPTION
**Pull request by Neio**
Issue:
(no issue number)
Currently Aravis GigE only support mono color. We are not able to get RGB color space image.

Resolution:
Adding raw Bayer GR 8 Format support for Aravis (GigE) plugin. In this we we can convert raw Bayer GR 8 Format to RGB color space.

### CODE REVIEW

**Comment by alalek** [comment]
@ArkadiuszRaj Please take look on this patch.

**Comment by ArkadiuszRaj** [comment]
This patch adds only passing new format code to Aravis library. The received image is not "debayerized' hence in my humble opinion for clarity it shall use code BYR1 and not BGR8.

From the other hand, BGR8 suggest layout of the filter array used - why not to use COLOR_BayerBG2BGR mode of cvtColor(), and enhance CvCaptureCAM_Aravis::retrieveFrame(int) to return RGB image?

**Comment by Neio** [comment]
@ArkadiuszRaj I see.  I have updated the code to output RGB directly.

BTW, could you explain the meaning of code "BYR1"?

**Comment by ArkadiuszRaj** [comment]
According to fourcc BYR1 andBYR2 means Bayer RAW 8 and 16 bits respectively. 

The code you provided seems to be OK. Hope you have verified conversion to RGB by your own. 

One comment. Your second commit adds plenty of unnecessary files to this pull request. @alalek what do you think on this?

**Comment by alalek** [comment]
I think, it is better to "squash" commits into one (probably with "rebase" on upstream master branch) to remove unnecessary intermediate changes from git history.

**Comment by Neio** [comment]
@ArkadiuszRaj Thanks for clarify. Yes, I have verified with my GigE camera (MindVision MV-GE130C-T).

@alalek I never tried. It seems like I don't need to anything but GitHub already provided an option to "squash" commits? ( https://github.com/blog/2141-squash-your-commits)

**Comment by ArkadiuszRaj** [comment]
@alalek, this PR was closed by submitter but it is not merged.

**Pull request closed without merging**
