### PR TITLE
Add QR decomposition to HAL

### PR DESCRIPTION
**Pull request by sovrasov**
### This pullrequest changes
Add QR decomposition to HAL

### CODE REVIEW

**Comment by vpisarev** [comment]
looks great! I have 2 comments:

1. it's preferable to use std::vector<> instead of manual memory allocation
2. we should avoid conditional compilation outside of OpenCV modules as much as possible; we need to call SVD if QR is not available and then remove `#if HAVE_LAPACK` clause in the tests

**Comment by sovrasov** [comment]
Unfortunately method `std::vector<>::data()` appears since C++11. Should I use hacks like `&myVector.front()` ?

**Comment by sovrasov** [comment]
@vpisarev please, look at last changes.

**Comment by vpisarev** [comment]
very useful addition! Sometimes it's useful to have some liner system solver that is more robust than LU/Cholesky and yet is significantly faster than SVD. If I understand correctly, the implementation does not choose the pivot element, so it's possible something that can be improved; but for now it's fine :+1:

**Pull request merged**
