### PR TITLE
Add support for 3D point cloud segmentation, using the USAC framework.

### PR DESCRIPTION
**Pull request by Ryyyc**
According to the previous plan(https://github.com/opencv/opencv_contrib/issues/2968), we want to merge the 3D point cloud plane segmentation algorithm into OpenCV. After analyzing the `usac` part of OpenCV's 3D module, we decided to slightly adapt and extend it to support segmentation of 3D point cloud basic geometric models (plane, sphere, cylinder, etc.).

Now the segmentation of the plane and the sphere has been tentatively completed.

---

To summarize the main work of this PR.
1. Moved class *Ransac* from `3d/src/usac/ransac_solvers.cpp` to `3d/src/usac.hpp` (and renamed it to *UniversalRANSAC*) so that it can be used elsewhere. And the first argument of the constructor of this class was modified(Replaced by a new interface `UsacConfig`), the reason for the modification was that the original interface was strongly coupled with the Homography part.
2. Added `PlaneModelError`, `SphereModelError`, interfaces defined in `3d/src/usac.hpp` and implemented in `3d/src/usac/estimator.cpp`. Their role is to estimate the error of the plane and sphere models respectively, and they will be used in the class *UniversalRANSAC*.
3. Added `PlaneModelMinimalSolver`, `PlaneModelNonMinimalSolver`, `SphereModelMinimalSolver`, `SphereModelNonMinimalSolver`, interfaces are defined in `3d/src/ usac.hpp`, implemented in `3d/src/usac/plane_solver.cpp.cpp`, `3d/src/usac/sphere_solver.cpp`. Their role is to estimate the minimum sampling model and the non-minimum sampling model for the plane and the sphere, respectively.
4. Added `PointCloudModelEstimator`, the interface is defined in `3d/src/usac.hpp` and implemented in `3d/src/usac/estimator.cpp`. Its role is to estimate point cloud models based on sampled points and decide whether to use them based on user-defined constraints.
5. New class *PointCloudWrapper*, which is defined in `3d/src/ptcloud/ptcloud_wrapper.hpp`, its role is a simple encapsulation of the access pointer to 3D point cloud data, avoiding the repetition of redundant construction code, It is used by Solver, Error.
6. New class *SACSegmentation*, which is defined in `3d/include/opencv2/3d/ptcloud.hpp` and implemented in `3d/src/ptcloud/sac_segmentation.cpp`, its role is to use the SAmple Consensus algorithm for 3D point clouds for basic geometric model segmentation, currently supporting the segmentation of planes and spheres using the RANSAC algorithm. The user will make use of the class *SACSegmentation*.

---

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders=linux,docs,win32,Win64 OpenCL
```

### CODE REVIEW

**Comment by Ryyyc** [comment]
relates #17683.
Thank you @ivashmak  for your work and help!

**Comment by Ryyyc** [comment]
I think the infrastructure work for segmenting the basic geometric model of 3D point clouds based on the USAC framework is basically complete, and the user-oriented interface is in the class `SACSegmentation`. More RNASAC-based algorithms and extensions to the geometric model will not affect the user-oriented interface.

**Comment by Zoom1111** [comment]
- This is a simple visualization of the basic objects (planes and spheres)  segmentation, where blue, red and yellow are marked as planes, and purple, green and light blue are marked as spheres. Point cloud data from test generation.

PR效果图

- This is the segmentation of the road and wall in the actual radar scan map, where blue is marked as the road, red and yellow are marked as the walls. Point cloud data from [IQmulus & TerraMobilita Contest](http://data.ign.fr/benchmarks/UrbanAnalysis/).

image

**Comment by Ryyyc** [comment]
Hi, @alalek, @savuor, excuse me, the build test of OpenCV code in `Linux x64`, `Docs` has been successful, it seems that the build test in `Win64`, `Mac` and other platforms will not be run automatically, can you give me a little help?

**Comment by alalek** [comment]
> from `No-Plane-Cannot-Be-Detected:5.x`
> 5.x

https://github.com/opencv/opencv/wiki/Branches

> Your development branch name must differ from the names of branches in the upstream OpenCV repository, i.e. your branch must NOT be named 2.4, 3.4, 4.x, 5.x, or master/next (it's a technical requirement specific to our continuous integration system to properly test multi-repository patches with opencv_extra/opencv_contrib)

---

Due to this builds are not triggered automatically.

**Comment by Ryyyc** [comment]
> > from `No-Plane-Cannot-Be-Detected:5.x`
> > 5.x
> 
> https://github.com/opencv/opencv/wiki/Branches
> 
> > Your development branch name must differ from the names of branches in the upstream OpenCV repository, i.e. your branch must NOT be named 2.4, 3.4, 4.x, 5.x, or master/next (it's a technical requirement specific to our continuous integration system to properly test multi-repository patches with opencv_extra/opencv_contrib)
> 
> Due to this builds are not triggered automatically.

Thanks for your patience in answering. But it seems I just renamed the branch causing this pr to be closed, I will reopen a new one.

**Pull request closed without merging**
