### PR TITLE
Updated version of libwebp to 0.6.0. Removed iOS from build exceptions for libwebp

### PR DESCRIPTION
**Pull request by ilijapuaca**
### This pullrequest changes

For needs of my app I needed to use libwebp in combination with OpenCV. Since version that is in the repo is ancient, and the fact it does not get built for iOS I made some minor modifications to get it to work.

### Potential improvements

In my app, I had to make use of libwebp directly in order to adjust the compression parameters by importing libwebp header files. The improvement I plan on making is exposing parameters other than quality so that they can be used with functions such as imencode, just like jpeg.

As I was not familiar with either OpenCV build process or libwebp, there may be things I have overlooked. The idea itself is pretty simple, hopefully there are no major issues with what I've done.

### CODE REVIEW

**Comment by ilijapuaca** [comment]
Just saw the warning pop up and took a look at libwebp code.

It seems to be a spelling error in `rescaler_sse2.c` - `#if (WEBP_RESCALER_FIX < 32)`. The macro they actually use is called `WEBP_RESCALER_RFIX`.

Not sure how relevant it is though...

**Comment by alalek** [comment]
WEBP_RESCALER_RFIX is [defined](https://github.com/webmproject/libwebp/blob/master/src/utils/rescaler_utils.h#L23) to 32. So in both cases "else" branch is processed.

I looked for upstream patches/issues, but there were nothing found about this.

**Comment by ilijapuaca** [comment]
My point was that the macro they used on the line that generates the warning is a typo. It should be WEBP_RESCALER_**R**FIX (missing the R).

As you noted though, it will evaluate to 0.

Either way, it is an issue with current libwebp release, and should not be a big deal (hopefully?) as it is a single operation optimization.

**Comment by alalek** [comment]
Both branches are equivalent with WEBP_RESCALER_RFIX=32. So mentioned typo fix should work.
Could you eliminate build warnings please?

**Comment by ilijapuaca** [comment]
I wanted to submit the fix to libwebp repo, but that means this pull request would have to wait for their next release.

Pushed the fix and squashed the commits.

**Comment by alalek** [comment]
BTW, CMakeLists.txt contains this line:
```
file(GLOB lib_srcs dec/*.c dsp/*.c enc/*.c mux/*.c utils/*.c webp/*.c)
```
Probably there is missing new "demux" sub-directory.

There is this warning in OpenCV code (probably, add forced cast to int: "(int)wfile_size"):
```
opencv/modules/imgcodecs/src/grfmt_webp.cpp:119:24: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
        data.create(1, wfile_size, CV_8U);
```

**Comment by ilijapuaca** [comment]
Good catch, changed both and pushed.

**Comment by ilijapuaca** [comment]
All of the checks seems to have passed.

Just curious though, I forgot to ask, why was iOS an exception when including libwebp during the build? Was the support lacking for some reason at the time?

**Comment by ilijapuaca** [comment]
Any updates? :guardsman:

**Comment by alalek** [comment]
Looks good to me! :+1:

**Pull request merged**
