### PR TITLE
build: avoid MSVC ICE

### PR DESCRIPTION
**Pull request by alalek**
<cut/>

```
buildworker:Mac OpenCL=macosx-1
build_image:Mac OpenCL=openvino-2019r1
test_modules=dnn

buildworker:Custom=linux-2
docker_image:Custom=ubuntu-openvino-2019r1:16.04
test_opencl:Custom=ON
test_bigdata:Custom=1
test_filter:Custom=*
test_modules:Custom=dnn

ci_branch:Linux AVX2=no-checks
docker_image:Linux AVX2=ubuntu-openvino-2019r1:16.04
test_opencl:Linux AVX2=OFF
buildworker:Linux AVX2=linux-1
build_parallel_tests:Linux AVX2=1
test_bigdata:Linux AVX2=1
test_module:Linux AVX2=dnn,python2,python3,java
tests_filter:Linux AVX2=*
```

### CODE REVIEW

**Comment by dkurt** [comment]
@alalek, It looks like the `{ }` were critical there. Without it I can face segfault in the application (despite tests are passed). Let me provide a reproducer.

**Comment by alalek** [comment]
Lets move code of this lambda into a separate static method.
DLIE API accepts just function pointer (not `std::function<>` or other template).

**Comment by dkurt** [comment]
@alalek, Thanks! Actually, for now I'm not sure that this is a root of my problem. My python application has a separate thread which grabs frames from a camera and a main thread which visualize it. Without `imshow` it's ok. I'll try to minimize it.

**Comment by dkurt** [comment]
@alalek, I just opened https://github.com/opencv/opencv/issues/14483. Please take a look if you'll have time. Thanks!

**Pull request merged**
