### PR TITLE
Static ffmpeg link

### PR DESCRIPTION
**Pull request by zhanggyb**
### This pullrequest changes

Fix link error which complains 'ffmpeg library not found' when building static OpenCV libraries on macOS.

To reproduce the issue on macOS EI Capitan:

- install `ffmpeg` with Homebrew
```shell
$ brew install ffmpeg
```
- configure cmake to build static libraries
```shell
$ cd <opencv source dir>
$ mkdir build && cd build
$ cmake -D BUILD_SHARED_LIBS=OFF ../
$ make
```

There will be error message such as `ld: library not found for -lavcodec`.

### CODE REVIEW

**Comment by alalek** [comment]
Looks like this patch duplicates some functionality from [here](https://github.com/opencv/opencv/blob/44bda8fbb7bb66b4d9d36f48344eaafd5d61115f/modules/videoio/CMakeLists.txt#L207-L216)

**Comment by zhanggyb** [comment]
Hi @alalek , those lines you highlighted only impact the `videoio` module and other modules linked to `videio`, I think.

If you use the default option and `-D BUILD_SHARED_LIBS=OFF`, it will fail when linking `/bin/opencv_perf_core` in `core` module, on macOS.

Btw, I tried to build the `master` in Ubuntu and everything is OK.

**Comment by vpisarev** [comment]
@alalek, let me assign it to you

**Comment by alalek** [comment]
CMake doesn't work well with libraries passed by name which are located in non-system directories.

Most of brew libraries add symlinks into /usr/local/lib and it is default to linker:
```
$ man ld
...
   Search paths
     ld maintains a list of directories to search for a library or framework to use.
     The default library search path is /usr/lib then /usr/local/lib.
```

Please add output of this command:
```
$ ls -al /usr/local/lib/libav*
```

Are there some lines similar to (for extended "ls -al /usr/local/lib/" command):
```
lrwxr-xr-x    1 admin  admin        36 Aug 10 14:28 libpng.a -> ../Cellar/libpng/1.6.23/lib/libpng.a
lrwxr-xr-x    1 admin  admin        40 Aug 10 14:28 libpng.dylib -> ../Cellar/libpng/1.6.23/lib/libpng.dylib
```
?

What output of pkg-config command?
```
$ pkg-config --libs libavcodec
-L/usr/local/lib -lavcodec -lm -framework CoreFoundation -framework VideoDecodeAcceleration -framework QuartzCore -lbz2 -lz -lavutil -lm

$ pkg-config --libs libpng
-L/usr/local/Cellar/libpng/1.6.23/lib -lpng16
```

**Comment by zhanggyb** [comment]
Hi, output of `ls -al /usr/local/lib/libav*` on my Mac:

```shell
lrwxr-xr-x  1 zhanggyb  admin  39  8 11 19:47 /usr/local/lib/libavcodec.a -> ../Cellar/ffmpeg/3.1.2/lib/libavcodec.a
lrwxr-xr-x  1 zhanggyb  admin  40  8 11 19:47 /usr/local/lib/libavdevice.a -> ../Cellar/ffmpeg/3.1.2/lib/libavdevice.a
# too many lines, no need to list all of them
```

`pkg-config` command output:

```shell
$ pkg-config --libs libavcodec
-L/usr/local/Cellar/ffmpeg/3.1.2/lib -lavcodec
```

I don't know why it's different from yours.

**Comment by alalek** [comment]
Looks good, links are available from /usr/local/lib , so linker ("ld") should handle it without any additional `-L<path>` parameters.
But I have no idea why your OpenCV build fails.

Could you run this experiment in your environment?

```
$ cc -v
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ cc -x c -lavcodec - <<< "extern void ff_big_add(void); int main() { return (int)ff_big_add; }"
$ otool -L a.out
a.out:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
$ nm -g a.out
0000000100000000 T __mh_execute_header
0000000100000610 T _ff_big_add
0000000100000680 T _ff_big_div
0000000100000780 T _ff_big_mul
0000000100000810 T _ff_xface_generate_face
0000000100000b40 S _ff_xface_probranges_2x2
0000000100000ae0 S _ff_xface_probranges_per_level
0000000100000ac0 T _main
                 U dyld_stub_binder
```

Are there any differences?

P.S. Our ffmpeg on build machine is not installed via homebrew.

**Comment by zhanggyb** [comment]
There're differences, I have to add `-L /usr/local/lib` to make it compile.
I have tow Macs and have the same output as below.

Anyway, I suggest closing this rp issue as 'not bug' until other Mac user verifies it. It's not critical and maybe caused by my mistake, just don't want to waste your time. :)

```shell
~ $ cc -v
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
~ $ cc -x c -lavcodec - <<< "extern void ff_big_add(void); int main() { return (int)ff_big_add; }"
ld: library not found for -lavcodec
clang: error: linker command failed with exit code 1 (use -v to see invocation)
~ $ cc -x c -L/usr/local/lib -lavcodec - <<< "extern void ff_big_add(void); int main() { return (int)ff_big_add; }"
~ $ otool -L a.out
a.out:
	/usr/local/opt/ffmpeg/lib/libavcodec.57.dylib (compatibility version 57.0.0, current version 57.48.101)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
~ $ nm -g a.out
0000000100000000 T __mh_execute_header
                 U _ff_big_add
0000000100000fa0 T _main
                 U dyld_stub_binder
```

**Comment by alalek** [comment]
It is very strange, especially in case of same compiler version.

Do you have same result in "Library search paths" section?
```
$ cc -Xlinker -v
@(#)PROGRAM:ld  PROJECT:ld64-264.3.101
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
Library search paths:
        /usr/lib
        /usr/local/lib
Framework search paths:
        /Library/Frameworks/
        /System/Library/Frameworks/
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by zhanggyb** [comment]
My output:

```shell
$ cc -Xlinker -v
@(#)PROGRAM:ld  PROJECT:ld64-264.3.101
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
Library search paths:
       	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/lib
Framework search paths:
       	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And before running the command I double-checked my dotfiles such as `.profile` and I'm sure there's no custom configuration of library/framework paths.

**Comment by alalek** [comment]
Could you check these commands (LDFLAGS environment variable is added to CMake command):
```
$ cd <opencv source dir>
$ mkdir build && cd build
$ LDFLAGS="-L/usr/local/lib" cmake -D BUILD_SHARED_LIBS=OFF ../
$ make
```

**Comment by zhanggyb** [comment]
It works if set `LDFLAGS="-L/usr/local/lib"`

**Comment by alalek** [comment]
@zhanggyb Thank you for checks! I have added general solution here: #7125

**Pull request closed without merging**
