### PR TITLE
Support for custom V4L stream & Matrix depth

### PR DESCRIPTION
**Pull request by shawndfernandes**
This pullrequest  adds support for custom stream & depth for opencv capture, reverts to default opencv values if not set.
Set via VideoWriter::set method
 CV_CAP_PROP_STREAM, CV_CAP_PROP_DEPTH
matrix_depth =   8,16 //* for 8U and 16 for 16U depth

stream_format  = 1,2,3,4,5…12;  //choose the raw camera stream via V4L

 "BGR24"   1:
 "YVU420"  2:
"YUV411P"  3:
"MJPEG"    4:
"JPEG"     5:
"YUYV"     6:
"UYVY"     7:
"SN9C10X"  8:
"SBGGR8"   9:
"SGBRG8"   10:
"RGB24"    11:
"Y16"      12:
Shawn Fernandes, shawndfernandes@yahoo.com

### CODE REVIEW

**Comment by alalek** [comment]
New introduced `CAP_PROP_STREAM` duplicates functionality of CAP_PROP_FOURCC. The similar problem with `CV_CAP_PROP_DEPTH`: there is already `CAP_PROP_FORMAT` for this.

BTW, Good patch should avoid touching of file code style.

**Comment by shawndfernandes** [comment]
Closing as build master is not queuing builds

**Comment by alalek** [comment]
It is not queued, because source branch name is "master".

**Comment by vpisarev** [comment]
@shawndfernandes, thanks for the contribution! I agree with @alalek; indeed, now cap_v4l.cpp diff can not be seen - too much unnecessary changes in formatting.

**Comment by shawndfernandes** [comment]
Dear Alalek, Vpisarev,

Any tips on how to ensure that coding style is being followed?
I have not git cloned openCV, but merged my build output file on github portal.

Please let me know if I can follow other options.

**Comment by vpisarev** [comment]
@shawndfernandes, terribly sorry for delay. it looks like you are using a text editor that automatically does some reformatting. You need to disable such features and modify/add just the lines you wanted  to, while trying to preserve indentation and curly brace style that is used in the original file

**Comment by terfendail** [comment]
`CAP_PROP_STREAM` property duplicates functionality of `CAP_PROP_FOURCC`
Information provided by `CV_CAP_PROP_DEPTH` reading could be retrieved from `CAP_PROP_FORMAT` Also changing of `CV_CAP_PROP_DEPTH` is not actually possible since V4L will set image data depth in accordance with `CAP_PROP_FOURCC` regardless of `CV_CAP_PROP_DEPTH` value therefore configuring output image header to other image depth could lead to corrupted data.

**Pull request closed without merging**
