### PR TITLE
Added FaceDetectorYN to OpenCV JS API

### PR DESCRIPTION
**Pull request by asmorkalov**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
build_image:Docs=docs-js
build_image:Custom=javascript
buildworker:Custom=linux-1,linux-4,linux-f1
```

### CODE REVIEW

**Comment by asmorkalov** [comment]
@opencv-alalek ONNX file is not stored in the repo. Do we need a test with always downloadable ONNX file? I suppose, no.

**Comment by WanliZhong** [comment]
@asmorkalov I tried to build `opencv.js`, but I can't make it be imported successfully. Could you paste the `opencv.js` with FaceDetectorYN?

**Comment by asmorkalov** [comment]
@WanliZhong I relay on BuildBot in this case. I'll try to reproduce it locally and send instruction.

**Comment by opencv-alalek** [comment]
@WanliZhong you could download it from docs preview: https://pullrequest.opencv.org/buildbot/export/pr/25430/docs/<space>opencv.js

**Comment by WanliZhong** [comment]
@opencv-alalek I met the same problem as the package I built. The `onRuntimeInitialized` callback function will not be called in this opencv.js or which I built manually. But it works in release opencv.js version https://docs.opencv.org/master/opencv.js
https://github.com/opencv/opencv/blob/a1e4444fb5ce9ee3d4afa80073e49dcc7ed6c6dd/samples/dnn/js_face_recognition.html#L193-L203

**Comment by opencv-alalek** [comment]
Does JS tutorial sample work for you? http://pullrequest.opencv.org/buildbot/export/pr/25430/docs/db/d64/tutorial_js_colorspaces.html

**Comment by WanliZhong** [comment]
> Does JS tutorial sample work for you? http://pullrequest.opencv.org/buildbot/export/pr/25430/docs/db/d64/tutorial_js_colorspaces.html

Yes, it works. I shouldn't use Safari. This problem seems browser kernel related. It works in Edge browser😂

**Review by opencv-alalek — APPROVED** [review]
Tutorial page would help with testing.

**Pull request merged**
