### PR TITLE
dnn:perf add missing definition __OPENCV_TEST to fix pch

### LINKED ISSUE #14195: dnn: build failure on gcc, invalid-pch
##### System information (version)

- OpenCV => 3.4, master. after #13932
- Operating System / Platform => all
- Compiler => tested on gcc >= 4.9 on ppc64le, also on x86

##### Detailed description

```bash
cc1plus: warning: /worker/buildbot/Power9_Linux_gcc-6__opencv/build/modules/dnn/test_precomp.hpp.gch/opencv_test_dnn_Release.gch: not used because `__OPENCV_TESTS' not defined [-Winvalid-pch]
[ 50%] Building CXX object modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/test/test_imgproc_umat.cpp.o
In file included from <command-line>:0:0:
/worker/buildbot/Power9_Linux_gcc-6__opencv/build/modules/dnn/test_precomp.hpp:50:27: fatal error: test_common.hpp: No such file or directory
 #include "test_common.hpp"
                           ^
compilation terminated.
make[2]: *** [modules/dnn/CMakeFiles/opencv_perf_dnn.dir/build.make:63: modules/dnn/CMakeFiles/opencv_perf_dnn.dir/test/test_common.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6697: modules/dnn/CMakeFiles/opencv_perf_dnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
buildbot URI:
nightly builds: [Linux-debug](http://pullrequest.opencv.org/buildbot/builders/3_4_noOCL_noICV_noSSE-lin64-debug/builds/342/steps/compile%20debug/logs/stdio) (other tests uses ccache on Linux)
gcc4.9 : https://ocv-power.imavr.com/#/builders/5/builds/46
gcc5: https://ocv-power.imavr.com/#/builders/16/builds/291
gcc6 : https://ocv-power.imavr.com/#/builders/14/builds/18
gcc7: https://ocv-power.imavr.com/#/builders/12/builds/8

##### Steps to reproduce

build dnn module with tests enabled

### PR DESCRIPTION
**Pull request by seiko2plus**
resolves #14195 
````
pw_compilers=clang-4, clang-5, clang-6, gcc-4.9, power9_gcc-5, power9_gcc-6, power9_gcc-7
````

### CODE REVIEW

**Comment by gogogo2018** [comment]
Thank you!

**Comment by AlexanderProschek** [comment]
I'm having the same issue. Can someone explain what this fix means?

**Comment by alalek** [comment]
Workaround without fixes: `cmake -DENABLE_PRECOMPILED_HEADERS=OFF ...`

**Comment by seiko2plus** [comment]
> I'm having the same issue. Can someone explain what this fix means?

@AlexanderProschek, #13932 shared utility functions(print, asserts, etc) in accuracy test with performance test of dnn module by including source code test_common.cpp to performance test's build target, which break [pch (precompiled header) ](https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html) that generated during build accuracy test due missing of definition `__OPENCV_TEST` that only defined by accuracy test's build target.
I fixed this issue by add missing definition `__OPENCV_TEST` to performance test target but later @alalek rework this fix in #14198 by moving content of "test_common.cpp" into a shareable header file instead.

>Can someone please explain how do I apply this solution? Do I input it as a line in the script or preinstall dependencies? Thank you.

@dux-sclavorum, instead of patch or fetch last changes you can workaround this issue by just disable `pch` using cmake option `-DENABLE_PRECOMPILED_HEADERS=OFF` just like @alalek mentioned in his previous comment and I apologize I had to mention disable `pch`  as quick fix, however I gonna edit that comment.

**Comment by dux-sclavorum** [comment]
`cmake   -D CMAKE_BUILD_TYPE=RELEASE \
            -D CMAKE_INSTALL_PREFIX=$cwd/installation/OpenCV-"$cvVersion" \
            -D INSTALL_C_EXAMPLES=ON \
            -D INSTALL_PYTHON_EXAMPLES=ON \
            -D WITH_TBB=ON \
            -D WITH_V4L=ON \
            -D OPENCV_PYTHON3_INSTALL_PATH=$cwd/OpenCV-$cvVersion-py3/lib/python3.6/site-packages \
        -D WITH_QT=ON \
        -D WITH_OPENGL=ON \
        -D ENABLE_PRECOMPILED_HEADERS=OFF
	-D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
        -D BUILD_EXAMPLES=ON ..`


When I insert the line in the cmake block, I get this error in the terminal. Thank you for your help thus far. I'm tottaly lost at this point forth.

`CMake Error: The source directory "/home/domagoj/opencv/build/ENABLE_PRECOMPILED_HEADERS=OFF" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
./installOpenCV-4-on-Ubuntu-18-04.sh: line 99: -D: command not found
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
`

**Comment by alalek** [comment]
Something is wrong with your command line.
Try to remove space after `-D` (no idea, because we can't reproduce that)

Anyway, It is enough to update to the latest code for now.

**Comment by dux-sclavorum** [comment]
This is the script that works for complete installation. The space removal works! Thank you very much!
(change is needed from txt to sh)

[installOpenCV-4-on-Ubuntu-18-04.txt](https://github.com/opencv/opencv/files/3035653/installOpenCV-4-on-Ubuntu-18-04.txt)

**Comment by alalek** [comment]
This script has several strange and dangerous parts.

<details>

1. How many aliases do you have at this moment in your profile configuration file?
```
echo "# Virtual Environment Wrapper" >> ~/.bashrc
echo "alias workoncv-$cvVersion=\"source $cwd/OpenCV-$cvVersion-py3/bin/activate\"" >> ~/.bashrc
```

2. Why? CMake Python detection needs this.
Because of that, the parameter `OPENCV_PYTHON3_INSTALL_PATH=$cwd/OpenCV-$cvVersion-py3/lib/python3.6/site-packages` is not needed really.
```
# quit virtual environment
deactivate
```

3. `sudo -H pip3 install -U pip numpy` before "create virtual environment". You can update your pip in virtualenv only. Main purpose of virtualenv - separate custom python configuration and leave system untouched. This sudo command looks useless.

4. `sudo apt -y install libprotobuf-dev protobuf-compiler` - not used (not enabled via OpenCV CMake flags).

5. `sudo apt -y install x264` not used by openCV directly. Probably installed with ffmpeg (avcodec) runtime libraries automatically

6. No idea why we need this (not used by OpenCV):
```
sudo apt -y install libfaac-dev libmp3lame-dev libtheora-dev
sudo apt -y install libvorbis-dev libxvidcore-dev
sudo apt -y install libopencore-amrnb-dev libopencore-amrwb-dev
```

7. Magic? OpenCV don't need this. V4L2 works great.
```
cd /usr/include/linux
sudo ln -s -f ../libv4l1-videodev.h videodev.h
```

8. gfortran, yasm - not used

9. checkinstall - useful, but not used by this script actually

10. `sudo apt -y remove x264 libx264-dev`. Removing packages to install something is the primary strange thing really.

11. `rm -rf opencv_contrib/build` - where is this directory created?

12. `libjasper1` - probably this command failed due missing package in Ubuntu 18.04. Errors are not handled by script at all.

13. `libxine2-dev` package is installed, but corresponding flag is not enabled for OpenCV CMake (`-DWITH_XINE=ON`)

14. `-D CMAKE_BUILD_TYPE=RELEASE` selected automatically.

15. Provided script may not work because there is "TAB" on the line with `ENABLE_PRECOMPILED_HEADERS` flag.

</details>

**Comment by zpymyyn** [comment]
> > I'm having the same issue. Can someone explain what this fix means?
> 
> @AlexanderProschek, #13932 shared utility functions(print, asserts, etc) in accuracy test with performance test of dnn module by including source code test_common.cpp to performance test's build target, which break [pch (precompiled header) ](https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html) that generated during build accuracy test due missing of definition `__OPENCV_TEST` that only defined by accuracy test's build target.
> I fixed this issue by add missing definition `__OPENCV_TEST` to performance test target but later @alalek rework this fix in #14198 by moving content of "test_common.cpp" into a shareable header file instead.
> 
> > Can someone please explain how do I apply this solution? Do I input it as a line in the script or preinstall dependencies? Thank you.
> 
> @dux-sclavorum, instead of patch or fetch last changes you can workaround this issue by just disable `pch` using cmake option `-DENABLE_PRECOMPILED_HEADERS=OFF` just like @alalek mentioned in his previous comment and I apologize I had to mention disable `pch` as quick fix, however I gonna edit that comment.

Hi, thank you all for the help.
The "disable" walkaround does work, however slows down the process a lot.
Does the patch also slow down compiling?

**Pull request merged**
