### PR TITLE
Fixed small inefficiency in seamless clone init

### LINKED ISSUE #16186: There seems to be a bug in modules/calib3d/src/stereobm.cpp at line 685.
##### System information (version)

- OpenCV => 4.1.2
- Operating System / Platform => ubuntu 16.04 64 bit
- Compiler => gcc 5.4.0

##### Detailed description

There may be a bug in modules/calib3d/src/stereobm.cpp at line 685.

At line 1161 `cost` is defined as
```
cost.create( left0.size(), CV_16S );
```
while at line 685 :
```
int* costptr = cost.data ? cost.ptr<int>() + lofs + x : &costbuf;
``` 
Shoud not it be `short* costptr`?

### PR DESCRIPTION
**Pull request by stringtheory1234**
Resolves #16186

### CODE REVIEW

**Comment by asmorkalov** [comment]
@stringtheory1234 Please organize the PR according to contribution guide: https://github.com/opencv/opencv/wiki/How_to_contribute

**Comment by asmorkalov** [comment]
Duplicates https://github.com/opencv/opencv/pull/16199. Closed in favor of original solution.

**Comment by asmorkalov** [comment]
Alternative solution uses cvtColor instead of copy. GRAY2BGR conversion not just copy values to 3 channels, but multiply it with coefficient, so the alternative patch is not equivalent.

**Comment by asmorkalov** [comment]
:+1:

**Comment by alalek** [comment]
> GRAY2BGR conversion not just copy values to 3 channels, but multiply it with coefficient

This is NOT true.
I hope you can find related code (search for `Gray2RGB` implementation).

P.S. Use`~~` to mark ~~statements~~ incorrect.

**Comment by asmorkalov** [comment]
@alalek My fault, I screwed up and looked inside another piece of code (another window). Yes, cvtColor is more efficient for this.

**Pull request closed without merging**
