### PR TITLE
dnn: prevent unloading of InferenceEngine plugins

### PR DESCRIPTION
**Pull request by alalek**
<cut/>

```
force_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2019r3.0:16.04
build_image:Custom Win=openvino-2019r3.0
build_image:Custom Mac=openvino-2019r3.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

### CODE REVIEW

**Comment by JulienMaille** [comment]
I have weird random crashes with my NCS2, is this PR supposed to fix some issues or is it just some code tidying?

**Comment by dkurt** [comment]
@JulienMaille, do you have a reproducer?

**Comment by JulienMaille** [comment]
@dkurt I don't want to hijack this thread but I'm not ready to create an issue yet.
It seems that my problem is much less frequent when I use a batchsize>1
But when doing forward one by one, the stick often disconnects with these traces
<details>
  <summary>Click to expand</summary>

```
Setting name for watchdog thread failed: No error
WF: [global] [         0] [EventRead00Thr] dispatcherEventReceive:362   inUsb_WritePipe: System err 995
Duplicate id detected.

WinUsb_WritePipe failed with error:=995

E: [global] [         0] [Scheduler00Thr] dispatcherEventSend:1004      WWrite failed (header) (err -2) | event XLINK_WRITE_RESP
i
nE: [xLink] [         0] [Scheduler00Thr] eventSchedulerRun:626 UEvent sending faileds
b_ReadPipe: System err 22
E: [global] [         0] [EventRead00Thr] handleIncomingEvent:275       handleIncomingEvent() Read failed -2

E: [global] [         0] [EventRead00Thr] handleIncomingEvent:277       ..\thirdparty\movidius\XLink\shared\XLink.c:277
         Assertion Failed: 0
W: [global] [         0] [EventRead00Thr] dispatcherEventReceive:367    Failed to handle incoming event
WinUsb_ReadPipe: System err 22
E: [xLink] [         0] [EventRead00Thr] eventReader:218        eventReader thread stopped (err -2)
E: [xLink] [         0] [] dispatcherWaitEventComplete:774      waiting is timeout, sending reset remote event
E: [global] [         0] [] XLinkReadDataWithTimeOut:1494       Event data is invalid
E: [watchdog] [         0] [] sendPingMessage:121       Failed send ping message: X_LINK_TIMEOUT
E: [ncAPI] [         0] [] ncFifoReadElem:3510  Packet reading is failed.
E: [global] [         0] [] writeData:1390      ..\thirdparty\movidius\XLink\shared\XLink.c:1390
         Assertion Failed: link != NULL
E: [watchdog] [         0] [] sendPingMessage:121       Failed send ping message: X_LINK_ERROR
E: [watchdog] [         0] [] watchdog_routine:315      [0000020B25841E30] device, not respond, removing from watchdog
```

</details>

**Comment by dkurt** [comment]
@JulienMaille, hard to say without reproducer. Please open a ticket because it's the best way to track the problem.

**Pull request merged**
