### PR TITLE
CV_DbgAssert that the result of area() fits in the return value

### LINKED ISSUE #8093: Rect::area() and Size::area() may overflow too easily
Just spent some 10 hours debugging a critical issue in an application I wrote. There was no crash or anything – only wrong behavior, sometimes.

Had in the code something like this:

```.cpp
cv::Rect rect = ...
if (rect.area() > 0) {
    ...
}
```

Turns out that the reason for the wrong behavior was that the product of `width` and `height` [here](https://github.com/opencv/opencv/blob/0e4dde1781d6439eb5377e22208a0eb6f6cd404e/modules/core/include/opencv2/core/types.hpp#L1734) overflowed the 32-bit result integer. So both the width and the height were strictly positive, yet the return value was negative and therefore my code didn't enter the block of code it was expected to enter, causing further down the road another problem that took a long time to trace back to here.

I think at a bare minimum, there could be a `CV_Assert` (or something) that would be triggered if the product doesn't fit in the return value. Would have saved me hours of time.

A better solution I guess would be to change the output type. But given the way the class is currently templated, I am not sure what to suggest – at least not right after my long debugging session today. Maybe, if no-one proposes a fix, I'll create some PR at some point.

In addition to [Rect_<_Tp>::area()](https://github.com/opencv/opencv/blob/0e4dde1781d6439eb5377e22208a0eb6f6cd404e/modules/core/include/opencv2/core/types.hpp#L1732), a similar fix, if any, is probably needed for [Size_<_Tp>::area()](https://github.com/opencv/opencv/blob/0e4dde1781d6439eb5377e22208a0eb6f6cd404e/modules/core/include/opencv2/core/types.hpp#L1593) also.

**Workaround**

I changed my code to look like this:

```.cpp
cv::Rect rect = ...
if (rect.width > 0 && rect.height > 0) {
    ...
}
```

### PR DESCRIPTION
**Pull request by reunanen**
resolves #8093

This pull request fixes (at least partially) the problem described in #8093: the result of `Rect::area()` and `Size::area()` may rather easily be too large to fit in the return value type, causing bugs that can be difficult to find (because depending on the situation, they may surface in a completely different part of an application).

Personally I might be inclined towards changing the return value type to `intmax_t` or so, but I do understand that this approach may not be great for everyone.

### CODE REVIEW

**Comment by reunanen** [comment]
Accidentally included multiple commits in the PR, but [fd5370](https://github.com/opencv/opencv/pull/8102/commits/fd53706d349acecbc49f2878c27edd97eb2a104c) is the only relevant one.

**Comment by reunanen** [comment]
Accidentally included multiple commits in the PR; when reviewing, please just look at the diff.

**Comment by vpisarev** [comment]
probably, a fresh PR should be created. Otherwise, I'm fine with the patch

**Comment by reunanen** [comment]
@vpisarev : created #8107 as a fresh PR.

**Pull request closed without merging**
