### PR TITLE
build: workaround for missing _mm256_setr_m128 in GCC

### LINKED ISSUE #8079: Compile error in corner.cpp: ‘_mm256_setr_m128’ was not declared in this scope
##### System information (version)
- OpenCV => git master (currently at 3.2.0.r103.g74defefd6)
- Operating System / Platform => Arch Linux 64-bit
- Compiler => gcc 6.3.1

##### Detailed description
I'm getting the following compile error when trying to build OpenCV version git master:
```
/home/user/abs/opencv-noffmpeg-git/src/opencv-noffmpeg-git/modules/imgproc/src/corner.cpp: In function ‘void cv::store_interleave(float*, const __m256&, const __m256&, const __m256&)’:
/home/user/abs/opencv-noffmpeg-git/src/opencv-noffmpeg-git/modules/imgproc/src/corner.cpp:116:86: error: ‘_mm256_setr_m128’ was not declared in this scope
     _mm256_storeu_ps(ptr, _mm256_setr_m128(_mm_castsi128_ps(a0), _mm_castsi128_ps(b0)));
                                                                                      ^
```

This issue seems to be caused by the recent git commit aa5caf83f6443a4581b1d52d23d581e7fee6f919.

##### Steps to reproduce
Attached.
Complete output also provided.

[opencv-steps.txt](https://github.com/opencv/opencv/files/732465/opencv-steps.txt)
[opencv-output.txt](https://github.com/opencv/opencv/files/732466/opencv-output.txt)

### PR DESCRIPTION
**Pull request by alalek**
resolves #8079

### CODE REVIEW

**Comment by tomoaki0705** [comment]
Thank you and sorry for bothering by my mistake.
the ```_mm256_setr_m128``` was a macro in VS, so probably it's better to use GCC version without using ```ifdef```

**Comment by alalek** [comment]
It is not only in VS:

- Intel compiler (2017 update 1):
```
alalek ~$ grep -R _mm256_setr_m128 /opt/intel/include/
/opt/intel/include/icc/immintrin.h:#define _mm256_setr_m128(lo, hi)    _mm256_set_m128((hi), (lo))
/opt/intel/include/icc/immintrin.h:#define _mm256_setr_m128d(lo, hi)   _mm256_set_m128d((hi), (lo))
/opt/intel/include/icc/immintrin.h:#define _mm256_setr_m128i(lo, hi)   _mm256_set_m128i((hi), (lo))
```

- [Clang](https://clang.llvm.org/doxygen/avxintrin_8h_source.html#l04873):
```
static __inline __m256 __DEFAULT_FN_ATTRS
_mm256_setr_m128 (__m128 __lo, __m128 __hi)
{
  return _mm256_set_m128(__hi, __lo);
}
```

**Comment by bermond** [comment]
This pull request perfectly solves issue #8079.
Thank you!

**Comment by alalek** [comment]
:+1:

**Pull request merged**
