### PR TITLE
Minimum change to address issue #18837

### LINKED ISSUE #18837: Incorrect parameter options for findFundamentalMat(...) in OpenCV Docs
Listed parameters for method are: 
CV_FM_7POINT for a 7-point algorithm. N=7
CV_FM_8POINT for an 8-point algorithm. N≥8
CV_FM_RANSAC for the RANSAC algorithm. N≥8
CV_FM_LMEDS for the LMedS algorithm. N≥8

but parameters should be: 
FM_7POINT for a 7-point algorithm. N=7
FM_8POINT for an 8-point algorithm. N≥8
FM_RANSAC for the RANSAC algorithm. N≥8
FM_LMEDS for the LMedS algorithm. N≥8

##### System information (version)
- OpenCV => 4.5.0-dev

##### Detailed description

Docs could be further described as un-descriptive. If anyone has links or description for the different methods I could include them in the fix.

##### Steps to reproduce
See [OpenCV Docs](https://docs.opencv.org/master/d9/d0c/group__calib3d.html#ga59b0d57f46f8677fb5904294a23d404a)

### PR DESCRIPTION
**Pull request by IanMaquignaz**
Fixes #18837

[Demo page](http://pullrequest.opencv.org/buildbot/export/pr/18849/docs/d9/d0c/group__calib3d.html#ga59b0d57f46f8677fb5904294a23d404a) for this patch.

<cut/>

### Pull Request Readiness Checklist
- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
[Demo page](http://pullrequest.opencv.org/buildbot/export/pr/18849/docs/d9/d0c/group__calib3d.html#ga59b0d57f46f8677fb5904294a23d404a) for this patch.

**Comment by asmorkalov** [comment]
@IanMaquignaz Please use `@ref` as it was recommended in the ticket. With `@ref` doxygen checks symbols in code and reports error, if code changes.

**Comment by IanMaquignaz** [comment]
@asmorkalov `@ref` has been applied. Let me know if I did it correctly. 

If yes, I believe this change could be applied to Rodriges(), findEssentialMat(), estimateAffine3D(), findHomography(), solvePnp() and possible more. Want me to apply this change here?

**Review by asmorkalov — APPROVED** [review]
:+1:

**Comment by IanMaquignaz** [comment]
> 
> 
> 👍

Does that mean "yes, the use of @ref is correct" or "yes change is correct and go ahead and add those other changes changes to this pull request"?

**Comment by asmorkalov** [comment]
@IanMaquignaz `@ref` works. You can see that doxygen adds link to enum description. There are another places in the header files, where enum keys are mentioned without reference. You can fix them all.

**Comment by IanMaquignaz** [comment]
@asmorkalov see #18872

**Pull request merged**
