### PR TITLE
Add Min layer to CPU, OpenCL, Halide, Inference Engine, NGraph and CUDA

### PR DESCRIPTION
**Pull request by rogday**
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/908

Related: https://github.com/opencv/opencv/issues/20438

<cut/>

```
opencv_extra=min

force_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2021.4.0:20.04
build_image:Custom Win=openvino-2021.4.0
build_image:Custom Mac=openvino-2021.4.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
test_opencl:Custom=ON
test_bigdata:Custom=1
test_filter:Custom=*
```

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [X] The PR is proposed to proper branch
- [X] There is reference to original bug report and related work
- [X] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Review by alalek — APPROVED** [review]
Looks good to me :+1:

**Comment by rogday** [comment]
@alalek, I'm going to make a new PR to master, since it's a feature, with CUDA implementation.

**Comment by alalek** [comment]
It make sense to create another PR to master branch as this PR to 3.4 is ready.

**Comment by YashasSamaga** [comment]
I was wondering if these fusions tests should be enabled for min:

https://github.com/opencv/opencv/blob/c3ac834526c66840835737f03ed1b4d8f711534e/modules/dnn/test/test_layers.cpp#L2340-L2344

They might help identify accidental fusions.

**Review by sergei-sl — APPROVED** [review]
Looks good to me :+1:

**Review by sl-sergei — APPROVED** [review]
Approve from the correct account

**Pull request merged**
