### PR TITLE
CMakeLists.txt: fix a typo in a message

### PR DESCRIPTION
**Pull request by lpea**
### This pullrequest changes

This PR fixes a typo in an error message in the main CMakeLists.txt file.

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by lpea** [comment]
@alalek, should I also submit this patch on the 2.4 branch? Is that what the "backport is needed" label suggests?

**Comment by alalek** [comment]
This is not necessary.
I will check these labels before next 2.4 maintenance release and will port these changes via single patch (in a batch).

**Comment by lpea** [comment]
Alright, as you prefer. If you change your mind just let me know!

Thanks

**Pull request merged**
