### PR TITLE
Updated the OpenCV logo

### PR DESCRIPTION
**Pull request by AnnaPetrovicheva**
Adding the updated OpenCV logo. Please see all versions here: https://opencv.org/resources/media-kit/.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by dkurt** [comment]
Should it be really stored in the docs? I mean is that used somewhere?

**Comment by mshabunin** [comment]
For reference:
```
../opencv/samples/winrt/ImageManipulations/Package.appxmanifest:      <m2:VisualElements DisplayName="OCV Image Manipulations" Description="OpenCV Image Manipulations sample" BackgroundColor="#00b2f0" ForegroundText="light" Square150x150Logo="Assets\opencv-logo-150.png" Square30x30Logo="Assets\opencv-logo-30.png">
../opencv/samples/winrt/ImageManipulations/MediaCapture.vcxproj:    <Image Include="assets\opencv-logo-150.png" />
../opencv/samples/winrt/ImageManipulations/MediaCapture.vcxproj:    <Image Include="assets\opencv-logo-30.png" />
../opencv/samples/winrt/ImageManipulations/MediaCapture.vcxproj.filters:    <Image Include="assets\opencv-logo-30.png">
../opencv/samples/winrt/ImageManipulations/MediaCapture.vcxproj.filters:    <Image Include="assets\opencv-logo-150.png">
../opencv/doc/tutorials/introduction/windows_visual_studio_opencv/windows_visual_studio_opencv.markdown:OpenCV logo](https://github.com/opencv/opencv/tree/master/samples/data/opencv-logo.png). Before starting up the application,
../opencv/doc/py_tutorials/py_core/py_basic_ops/py_basic_ops.markdown:img1 = cv.imread('opencv-logo.png')
../opencv/doc/py_tutorials/py_core/py_image_arithmetics/py_image_arithmetics.markdown:img2 = cv.imread('opencv-logo.png')
../opencv/doc/py_tutorials/py_core/py_image_arithmetics/py_image_arithmetics.markdown:img2 = cv.imread('opencv-logo-white.png')
../opencv/doc/py_tutorials/py_imgproc/py_houghcircles/py_houghcircles.markdown:img = cv.imread('opencv-logo-white.png',0)
../opencv/doc/py_tutorials/py_imgproc/py_filtering/py_filtering.markdown:img = cv.imread('opencv-logo-white.png')
../opencv/doc/Doxyfile.in:PROJECT_LOGO           = @CMAKE_CURRENT_SOURCE_DIR@/opencv-logo-small.png
```
```
../opencv/doc/header.html:<link href="$relpath^opencv.ico" rel="shortcut icon" type="image/x-icon" />
../opencv/doc/CMakeLists.txt:  list(APPEND CMAKE_DOXYGEN_HTML_FILES "${CMAKE_CURRENT_SOURCE_DIR}/opencv.ico")
../opencv/platforms/ios/build_framework.py:            shutil.copyfile(os.path.join(self.opencv, "doc", "opencv.ico"), os.path.join(outdir, "docs", "favicon.ico"))
```
Files opencv-logo-30 and opencv-logo-150 are not replaced by this PR.

**Comment by vpisarev** [comment]
@AnnaPetrovicheva, thank you very much! the new logo looks great and modern :+1:

**Comment by asmorkalov** [comment]
@mshabunin Could you look on the patch again?

**Pull request merged**
