### PR TITLE
Update py_mouse_handling.markdown

### PR DESCRIPTION
**Pull request by Satyam-kumar-yadav**
Updated docs

### CODE REVIEW

**Comment by alalek** [comment]
Please describe what is wrong with original code?

**Comment by Satyam-kumar-yadav** [comment]
while using it in jupyter i was not able to close it  or if i tried to close it end up getting another such window.

**Comment by alalek** [comment]
Does `Esc` key work?

**Comment by Satyam-kumar-yadav** [comment]
I have been searching for how to close the window but wasn't able to get any document, so I think it was quite possible for any such person like me to get in the problem so , for that reason I  updated the docs .

**Comment by Satyam-kumar-yadav** [comment]
and thanks  Esc key does work

**Comment by asmorkalov** [comment]
@alalek I propose to close PR without merge. What do you think?

**Pull request closed without merging**
