### PR TITLE
G-API: Graph compile arguments must be unique.

### PR DESCRIPTION
**Pull request by TolyaTalamanov**
### This pullrequest changes
* Add unique check to cv::compile_args()

### CODE REVIEW

**Comment by TolyaTalamanov** [comment]
@dmatveev Pls, check it, maybe it's good idea.

**Comment by TolyaTalamanov** [comment]
@dmatveev @rgarnov

**Comment by dmatveev** [comment]
Let's discuss live, tomorrow.

**Comment by asmorkalov** [comment]
@dmatveev Do you have any news on the patch? Are you ready to merge it?

**Comment by asmorkalov** [comment]
@TolyaTalamanov please re-base and resolve merge conflict.

**Pull request closed without merging**
