### PR TITLE
added CV_MAT_DEPTH_IS_FLOAT() and CV_MAT_DEPTH_IS_SIGNED()

### PR DESCRIPTION
**Pull request by chacha21**
Proposal of utility functions about mat depth.

### CODE REVIEW

**Comment by chacha21** [comment]
Use case for me :
I plan to add REDUCE_SUMABS and REDUCE_MAXABS to cv::reduce().
For unsigned depths, it will just be interpreted as REDUCE_SUM and REDUCE_MAX.

**Comment by asmorkalov** [comment]
@alalek Please take a look.

**Comment by VadimLevin** [comment]
@alalek Have a look, please.

**Comment by asmorkalov** [comment]
The functions are not used in OpenCV right now and maintainers do not see significant value in the patch. @alalek, @vpisarev, @VadimLevin @vladimir-dudnik decided to close the PR on OpenCV core team meeting. @chacha21 Feel free to propose the same functions as part of another PR together with useful functionality that use it.

**Pull request closed without merging**
