### PR TITLE
MediaSDK initial support

### PR DESCRIPTION
**Pull request by mshabunin**
### This pullrequest changes

Adds support to read and write video stream using MediaSDK.

### CODE REVIEW

**Comment by mshabunin** [comment]
@mletavin , please take a look.

**Comment by vpisarev** [comment]
:+1:

**Comment by UnaNancyOwen** [comment]
@mshabunin Thank you for implementing good features.
Do you have a plan to support Windows?

**Comment by mshabunin** [comment]
@UnaNancyOwen , yes, but later. First I want to enable containers and properties support.

**Comment by UnaNancyOwen** [comment]
@mshabunin Thanks!

**Comment by mshabunin** [comment]
@vpisarev , I've rebased my changes on current master and added one commit with minor modifications.

**Comment by vpisarev** [comment]
looks great! :+1:

**Comment by alalek** [comment]
@mshabunin Please add license header to source files. You can use this:
```
// This file is part of OpenCV project.
// It is subject to the license terms in the LICENSE file found in the top-level directory
// of this distribution and at http://opencv.org/license.html
```

If some code is highly based on Media SDK samples, then add this too:
```
//
// This file is based on Media SDK package samples issued under the "MIT License"
// available: https://github.com/Intel-Media-SDK/MediaSDK/blob/master/LICENSE
```

**Comment by mshabunin** [comment]
@alalek , thank you, I've added the license.

**Comment by alalek** [comment]
:+1:

**Pull request merged**
