### PR TITLE
Fix mfx videowriter bitrate calculation

### PR DESCRIPTION
**Pull request by ccdsad**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake
Fix bug from this issue:
https://github.com/opencv/opencv/issues/13306

### CODE REVIEW

**Comment by mshabunin** [comment]
@ccdsad , please check this PR: #17228, it adds ability to control encoding bitrate using environment variables.

**Comment by ccdsad** [comment]
@mshabunin , Ok, but the incorrectness of the formula makes the choice of this coefficient intuitively incomprehensible. For example with 1920x1080 25fps:
```
params.mfx.TargetKbps = (mfxU16)cvRound(frameSize.area() * fps / BITRATE_DIVISOR);
```
Gives us
BITRATE_DIVISOR= 300: TargetKbps= 41728
BITRATE_DIVISOR= 400: TargetKbps= 64064
BITRATE_DIVISOR= 500: TargetKbps= 38144
BITRATE_DIVISOR= 800: TargetKbps= 64800
```
params.mfx.TargetKbps = (mfxU16)cvRound((frameSize.area() * fps * 24) / (BITRATE_DIVISOR * 1024));
```
Gives us
BITRATE_DIVISOR= 300: TargetKbps= 4050
BITRATE_DIVISOR= 400: TargetKbps= 3037
BITRATE_DIVISOR= 500: TargetKbps= 2430
BITRATE_DIVISOR= 800: TargetKbps= 1518

Сorrect me if I'm wrong

**Comment by mshabunin** [comment]
In my opinion this divisor does not have meaning in any way, it is just some empirically derived constant. Actual image quality will depend on codec, its parameters and contents of the video. We can try and set default value to `500 * 1024 / 24 = 21333` if you think it is better, but our tests might fail.

**Comment by ccdsad** [comment]
Unfortunately target kbs affects not only the quality of compressed video, but also the size of the video file. It's not that hard to check. This simple python code sample:
```
import cv2
import os


inp = cv2.VideoCapture('input.mp4', cv2.CAP_FFMPEG)
w = int(inp.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(inp.get(cv2.CAP_PROP_FRAME_HEIGHT))
reso = (w, h)
fps = inp.get(cv2.CAP_PROP_FPS)
fourcc = cv2.VideoWriter_fourcc(*'X264')
frame_count = int(inp.get(cv2.CAP_PROP_FRAME_COUNT))

out = cv2.VideoWriter(
        'output.mp4',
        cv2.CAP_INTEL_MFX,
        fourcc,
        fps,
        reso,
        isColor=True,
)
for _ in range(frame_count):
    ret, frame = inp.read()
    out.write(frame)

inp.release()
out.release()
print(f'resolution= {reso}, fps= {round(fps, 2)}, frame_count= {frame_count}')
print(f'input.mp4 size= {round(os.stat("input.mp4").st_size / (1024 * 1024), 2)}M')
print(f'output.mp4 size= {round(os.stat("output.mp4").st_size / (1024 * 1024), 2)}M')
```
Tells us that from 42M input video we get 266M video file:
```
$ python3 mfx_test.py                                          
libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /opt/intel/mediasdk/lib64/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
resolution= (1920, 1080), fps= 59.9, frame_count= 3000
input.mp4 size= 42.08M
output.mp4 size= 266.58M
```
If we just change cv2.CAP_INTEL_MFX to cv2.CAP_FFMPEG we get diametrically opposite result:
```
python3 mfx_test.py
OpenCV: FFMPEG: tag 0x34363258/'X264' is not supported with codec id 28 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
resolution= (1920, 1080), fps= 59.9, frame_count= 3000
input.mp4 size= 42.08M
output.mp4 size= 24.47M
```
When i faced this problem a few months ago at first I did not understand what I was doing wrong. But thanks to this issue https://github.com/opencv/opencv/issues/13306 I find this line of code:
```
params.mfx.TargetKbps = (mfxU16)cvRound(frameSize.area() * fps / 500);
```
If we take a close look at this expression, we will understand that it does not count bits per second, but divides the number of pixels per second and further by the compression coefficient. The worst part is that the values ​​obtained with the "normal" resolution and азы are obtained more than (2 ** 16 - 1) and after converting the value to uint16 we get random values ​​of the "Targetkbs". For example:
```
1920x1080 60fps -> 1920 * 1080 * 60 (Pixels/s) / 500 -> 248832 -> Targetkbs= 52227 (in uint16)
1920x1080 30fps -> 1920 * 1080 * 30 (Pixels/s) / 500 -> 124416 -> Targetkbs= 58881 (in uint16)
4096x3072 30fps -> 4096 * 3072 * 30 (Pixels/s) / 500 -> 754974 -> Targetkbs= 34089 (in uint16)
1080x720 30fps -> 1280 * 720 * 30 (Pixels/s) / 500 -> 55296 -> Targetkbs= 55296 (in uint16)
```
As you can see, an unpredictable video bitrate is generated, and accordingly the compression quality and the size of the video file will also be random.
Now if we look at this expression:
```
params.mfx.TargetKbps = (mfxU16)cvRound((frameSize.area() * fps * 24) / (500 * 1024));
frameSize.area() * fps   pixels/s
24   pixel size in bits
1024   bps -> kbps
500   divisor
```
Now this expression makes more sense. With 1920x1080 30fps divisor= 1 we get bitrate of raw data, which is equal to 1458000kbs (or 1.39Gbs) and now BITRATE_DIVISOR really makes sense. If divisor= 500 we get TargetKbs= 2916  kbps.
Unfortunately, I could not rebuild the opencv for python with the correct expression. So I had to choose gstreamer+vaapi.
If you leave the default value 500. Then I will be have to change the environment variable to 21333 so as not to receive video with random quality and file size.
But I think that the correct way to fix this problem is to correctly calculate the bitrate of the output video, where compression ratio really is.

**Comment by mshabunin** [comment]
@ccdsad , I've updated my PR according to your suggestions:
* DIVISOR is multiplied by 1024 and divided by 24
* added saturate_cast to avoid overflow

**Comment by ccdsad** [comment]
Thank you, now it can be closed

**Pull request closed without merging**
