### PR TITLE
Avoid extra memset

### PR DESCRIPTION
**Pull request by dkurt**
### Pull Request Readiness Checklist

Just an experiment to avoid extra usage of `memset`.

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by fengyuentau** [comment]
Do we have tests for fp16 convolution? cc @zihaomu

**Comment by zihaomu** [comment]
Yes, we have the FP16 accuracy test, which has the flag of `DNN_TARGET_CPU_FP16`. https://github.com/opencv/opencv/blob/52f3f5a3f617e8b1fa708bdfc37a6bc58a13ebb7/modules/dnn/test/test_onnx_importer.cpp#L2352

**Comment by fengyuentau** [comment]
> Yes, we have the FP16 accuracy test, which has the flag of `DNN_TARGET_CPU_FP16`.
> 
> https://github.com/opencv/opencv/blob/52f3f5a3f617e8b1fa708bdfc37a6bc58a13ebb7/modules/dnn/test/test_onnx_importer.cpp#L2352

It is turned off by default: https://github.com/opencv/opencv/actions/runs/8200307720/job/22436426876?pr=25184#step:17:12821. Tests for a single convolution layer on fp16?

**Comment by zihaomu** [comment]
https://github.com/opencv/opencv/actions/runs/8200307720/job/22436426876?pr=25184#step:17:12955, the default is ON, and we turned it off since the accuracy issue introduced by FP16.

**Comment by dkurt** [comment]
@fengyuentau, @zihaomu, does it make sense to verify that this PR will pass on 5.x branch too?

**Comment by asmorkalov** [comment]
@dkurt You may create yet another PR to 5.x with the same change. I'll merge it independently.

**Review by fengyuentau — APPROVED** [review]

**Review by zihaomu — APPROVED** [review]

**Pull request merged**
