### PR TITLE
JavaScript: add TrackerMIL

### PR DESCRIPTION
**Pull request by alalek**
To verify that Tracker wrapper works.

Blocked by #21045

```
force_builders_only=docs,Custom
buildworker:Docs=linux-4,linux-6
build_image:Docs=docs-js:18.04
build_image:Custom=javascript
buildworker:Custom=linux-4,linux-6
```

### CODE REVIEW

**Comment by Karma-is-a-Bitch** [comment]
opencv/opencv <
***@***.***>

opencv/opencv ***@***.***>

Subscribed ***@***.***>

On Tue, Nov 9, 2021 at 9:34 PM Alexander Alekhin ***@***.***>
wrote:

> To verify that Tracker wrapper works.
>
> force_builders=Custom
> buildworker:Docs=linux-4,linux-6
> build_image:Docs=docs-js:18.04
> build_image:Custom=javascript
> buildworker:Custom=linux-4,linux-6
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/opencv/opencv/pull/21032
> Commit Summary
>
>    - js: add TrackerMIL
>
> File Changes
>
> (3 files)
>
>    - *M* modules/js/src/core_bindings.cpp (4)
>    - *M* modules/js/test/test_video.js (25)
>    - *M* platforms/js/opencv_js.config.py (19)
>
> Patch Links:
>
>    - https://github.com/opencv/opencv/pull/21032.patch
>    - https://github.com/opencv/opencv/pull/21032.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
>
-- 
Julia

**Comment by alalek** [comment]
@murata- Thank you for looking on this!

There is another problem with handling of output Rect arguments.
Currently this feature is blocked by #21045

**Comment by murata-** [comment]
@alalek Thank you for your reply.
I pulled a change for # 21045, but tracking didn't work.
TestRectOutput The test failed.

**Comment by alalek** [comment]
There is no fix yet. #21045 is just a reproducer.

**Comment by alalek** [comment]
@murata- Added workaround for the output rect problem, please take a look (API is updated, see test code).

**Comment by murata-** [comment]
@alalek 
Thank you very much.
It worked :'-)  :’‐D

After building, change bin/opencv.js (line 34)
 < return cv.ready
 > return cv

**Comment by alalek** [comment]
:+1:

**Pull request merged**
