### PR TITLE
core: improve AVX512 infrastructure by adding more CPU features groups

### PR DESCRIPTION
**Pull request by seiko2plus**
related to #13891

```
force_builders=Custom,Linux AVX2
build_image:Custom=ubuntu:18.04
buildworker:Custom=linux-5
test_opencl:Custom=ON
```

### CODE REVIEW

**Comment by alalek** [comment]
Thank you!

I will take a look on this after completion of ongoing OpenCV release activities (probably on next week).

**Comment by seiko2plus** [comment]
@alalek , no problem, just take your time, thank you!.

**Comment by alalek** [comment]
@seiko2plus Hi! I rebased and updated patch (primary CMake's part of changes)

**Comment by seiko2plus** [comment]
@alalek, Hello !, thank you for updating the patch "well done!"

**Pull request merged**
