### PR TITLE
G-API: Align imgproc tests to new model

### PR DESCRIPTION
**Pull request by andrey-golubev**
### This pullrequest

updates imgproc accuracy tests according to new test model

### CODE REVIEW

**Comment by andrey-golubev** [comment]
@dmatveev @rgarnov please review

**Comment by dmatveev** [comment]
I am ok with this. :+1: 

Let's remove that "bool()" parameter (initialize output matrix) as a next step!

**Comment by andrey-golubev** [comment]
@alalek please merge

**Comment by andrgolubev** [comment]
Thanks!

**Pull request merged**
