### PR TITLE
Intel Inference Engine: cpu_extension_avx2.dll

### PR DESCRIPTION
**Pull request by peters**
### This pullrequest changes

If you download the latest version of `Intel OpenVINO` then `cpu_extension.dll` does not exist but `cpu_extension_avx2.dll` is available (Build number `10478`). I'm not that familiar with Intel Inference Engine, just wanted to create a few benchmarks comparing it to the GPU backend. 

/cc @alalek

### CODE REVIEW

**Comment by dkurt** [comment]
Please try to build `cpu_extension.dll` from source using this guide: https://github.com/opencv/opencv/wiki/Intel's-Deep-Learning-Inference-Engine-backend.
or just rename a new `cpu_extension_avx2.dll` to `cpu_extension.dll`. It looks like just a manually renamed library but not a generated name. At least there is no `avx2` suffix at corresponding CMakeList.

**Comment by dkurt** [comment]
Linux distribution of OpenVINO R1.2 has `libcpu_extension_avx2.so` and `libcpu_extension_sse4.so`

**Comment by peters** [comment]
@dkurt Aha! Compiling `cpu_extension` project inside samples folder did the trick. Though it should be mentioned that this was not entirely straight forward on Windows. 

Visual Studio 2017 Enterprise 15.7.3 (x64 build).
 
## `samples\cmake\cmake_cpuid.cmake`

Cmake errors out complaining about not finding cpuid.txt. This was resolved by manually compiling the cpp file inside `cmake/cpuid.cmake` and run `cpuid.exe` then copy `cpuid.txt` to the cmake build directory. 

## `samples\extension\CMakeLists.txt`

1. Remove omp macro
2. Replace with the following

```cmake
find_package(OpenMP)
if (OPENMP_FOUND)
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif()
```

For some strange reason i was unable to compile without changing from c++ 11 til c++ 17.

**Comment by peters** [comment]
Btw, thanks for the help @dkurt :)

**Comment by dkurt** [comment]
@peters, thank you for pointing that issue! Unfortunately we couldn't reopen your PR because commit has been created in GitHub's editor. Please see https://github.com/opencv/opencv/pull/11700 for added changes.

**Pull request closed without merging**
