### PR TITLE
A solution of #6644

### LINKED ISSUE #6644: How can use the runAt function in cascade detect in opencv 3.1?
This is a template helping you to create an issue which can be processes as quickly as possible. Feel free to add additional information or remove not relevant points if you do not need them.

If you have a question rather than reporting a bug please go to http://answers.opencv.org where you get much faster responses.

### Please state the information for your system
- OpenCV version:  3.10
- Host OS: Mac OS X 10.11.3
-Compiler & CMake: GCC 5.3 & CMake 3.5

### In which part of the OpenCV library you got the issue?
Examples:
- objdetect
- face recognition

### Expected behaviour

The continues behaviour as opencv2.4.
Opencv 2.4 support run a cascade detection in a specified point, which enable cascade object to do classifier's job. 

### Actual behaviour

In opencv 3.1, the runAt function has been moved to CascadeClassifierImpl, 
which is not accessable .

How can I use the runAt function?
### Code example to reproduce the issue / Steps to reproduce the issue
Please try to give a full example which will compile as is.
```

### PR DESCRIPTION
**Pull request by huangynn**
resolves #6644

### This pullrequest changes
Add classify function to CascadeClassifier to classify a specific image is an object or not

### CODE REVIEW

**Comment by StevenPuttemans** [comment]
wow wait o_O why would we need a new function to perform a classification on a given window using a cascade classifier? Thats already perfectly possible.

**Comment by huangynn** [comment]
Actually, it is used to get the cascade classification confidence of a specific image. I don't know which function provide this.

**Comment by StevenPuttemans** [comment]
But that is what I do not get, a cascade classification is done on each sample through a sliding window approach. If you supply it with an image equalling model size, then detectMultiScale with weights parameters, just give you the same output. This is nothing new ...

**Comment by StevenPuttemans** [comment]
@huangynn since it seems you are not trying to update this, let me show how I think you can get the same output with the current functionality.

```
// Make sure your img is a fixed known window you want to evaluate.
// If this is not the case, supply the correct ROI.
Mat img; 
vector<double> weights;
vector<int> levels;
vector<Rect> detections;
CascadeClassifier model("/path/to/your/model.xml");
model.detectMultiScale(img, detections, levels, weights, 1.1, 3, 0, Size(), Size(), true);
cerr << "Detection " << detections[0] << " with weight " << weights[0] << endl;
```

**Comment by sam-n-johnston** [comment]
I'm having a problem trying to implement this functionality. I created a minimal [repo](https://github.com/sam-n-johnston/cascade-weight-test/tree/master) to test this out. There are six face, from a good relatively fontal face to a decentered face. The output I get is strange: 
```
Detection ./cropped_face1.png [109 x 109 from (2, 14)] with weight 108.512 and level: 22 and size: 1
Detection ./cropped_face2.png [111 x 111 from (9, 9)] with weight 108.411 and level: 22 and size: 1
Detection ./cropped_face3.png [109 x 109 from (2, 14)] with weight 108.512 and level: 22 and size: 1
```
The last 3 faces do not even get a single output, even if face#4 is reasonably nice:
cropped_face4

The level always seems to be 22 (on my very little sample, sorry). Stage 22 seems to be the final stage of the classifier. I am also unclear on to what the weights actually represent with such strange number. I didn't find anything in the documentation to help me. I started going through the source code, but I didn't find anything to help me yet. 

I do not quite understand why face#3 gets to the final stage of the classifier, with ~108 of weight, and the face#4 has no output. 

Am I doing something wrong? Is something wrong with the function? Can there be an explanation of the usage and the variables?

**Comment by acgtyrant** [comment]
@StevenPuttemans Your example is very useful to me, thank you! However, the description of this function is too incomplete in the documentation.

**Comment by StevenPuttemans** [comment]
@acgtyrant I will add a pull request adding a code sample to the docs, making it more clear for future users.

**Pull request closed without merging**
