### PR TITLE
Remove obsolete FFMPEG versions support

### PR DESCRIPTION
**Pull request by VadimLevin**
In order to move further with extending existed functionality and reduce support costs about 3-4 months ago on the OpenCV core team meetings it was decided to limit FFMPEG versions to the versions that are available in the Ubuntu 14.04 LTS release:
```
- avcodec:       YES (54.35.1)
- avformat:      YES (54.20.4)
- avutil:        YES (52.3.0)
- swscale:       YES (2.1.1)
- avresample:    YES (1.0.1)
```
I tested using the following Docker container:
```Docker
# Base image
FROM ubuntu:14.04

# General packages
RUN \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        software-properties-common \
        pkg-config \
        curl git man make mc vim wget htop

# GCC configuration
# Configure repository
RUN \
    add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
    apt-get update
# Install required version
RUN \
    apt-get install -y --no-install-recommends gcc-6 g++-6
# Substitute default version
RUN \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

# Verify compilers version
RUN \
    g++ --version && \
    gcc --version

# Actual CMake
# Install dependency
RUN \
    apt-get install -y --no-install-recommends \
        libssl-dev
# Download
RUN \
    wget https://github.com/Kitware/CMake/releases/download/v3.16.5/cmake-3.16.5.tar.gz && \
    tar -xvf cmake-3.16.5.tar.gz
# Configure
RUN \
    cd cmake-3.16.5 && \
    ./bootstrap 
# Build and install
RUN cd cmake-3.16.5 && \
    make -j 4 && \
    make install
# Verify CMake installation
RUN \
    cmake --version

# Install FFMPEG libraries
RUN \
    apt-get install -y --no-install-recommends \
        libavformat-dev libavformat-extra-54 libswscale-dev libavcodec-dev libavresample-dev

# Define entry-point of the container
CMD [ "/bin/bash" ]
```
The only difference from the default Ubuntu 14.04 setup is newer versions of GCC (6.5) and CMake (3.16).

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@mshabunin could you take a look?

**Comment by mshabunin** [comment]
Is this patch applicable to _3.4_ or we will keep that branch frozen?

Why GCC 6? Is there a problem with 4.8?

**Comment by VadimLevin** [comment]
> Is this patch applicable to _3.4_ or we will keep that branch frozen?
> 
> Why GCC 6? Is there a problem with 4.8?

I think it is better to keep 3.4 in the state as it is, applying bug fixes and without radical (like version increments) changes.

GCC 4.8 does not fully C++11 complaint (some features are missing and not fully library support). OpenCV 4.x uses C++11 as default, so I take GCC 6, but it is possible to use GCC 5.1 (full C++11 support)

**Comment by mshabunin** [comment]
I've checked several FFmpeg versions built from sources on Ubuntu 20 and found one issue:
```
In file included from /opencv/modules/videoio/src/cap_ffmpeg.cpp:50:
/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp: In member function 'bool CvCapture_FFMPEG::open(const char*)':
/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:940:35: error: 'AVDISCARD_NONINTRA' was not declared in this scope; did you mean 'AVDISCARD_NONKEY'?
  940 |                 enc->skip_frame = AVDISCARD_NONINTRA;
      |                                   ^~~~~~~~~~~~~~~~~~
      |                                   AVDISCARD_NONKEY
```
It is reproduced only with several [older FFmpeg versions](https://ffmpeg.org/olddownload.html): 1.1.16 - 2.2.16 ; which is strange because this line should not be compiled. Though this issue exists on _master_ branch too, so I it is not a problem of this PR.

**Comment by mshabunin** [comment]
I tested with default Ubuntu 20 compiler: GCC 9.3.0. See https://github.com/mshabunin/videoio-ffmpeg-check

More cases covered:
* Same problem with libav-12.3 and libav-11.12 (AVDISCARD_NONINTRA)
* No problems with libav-9.21
* Different problem with libav-0.8.21, but I guess we won't support it.
* And another problem with older ffmpeg-2.7.7
  ```
  In file included from /opencv/modules/videoio/src/cap_ffmpeg.cpp:50:
  /opencv/modules/videoio/src/cap_ffmpeg_impl.hpp: In function 'AVStream* icv_add_video_stream_FFMPEG(AVFormatContext*, AVCodecID, int, int, int, double, int)':
  /opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:1804:21: error: 'AV_CODEC_FLAG_GLOBAL_HEADER' was not declared in this scope; did you mean 'CODEC_FLAG_GLOBAL_HEADER'?
   1804 |         c->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;
        |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
        |                     CODEC_FLAG_GLOBAL_HEADER
  ```

**Review by mshabunin — APPROVED** [review]

**Comment by alalek** [comment]
Please add some note/comment about minimal handled FFmpeg / libav versions (and their release dates/years)

**Comment by alalek** [comment]
@tomoaki0705 Could you check if this PR works on your devices? (there is conflict with changes from #18119 )

**Comment by VadimLevin** [comment]
> @tomoaki0705 Could you check that this PR works on your devices? (there is conflict with changes from #18119 )

It won't work, because I would like to raise minimal libavcodec version up to 54.35.100 (tested) and versions checks to the `detect_ffmpeg.cmake` . The problem, that #18119 solves, occurs for libavcodec version < 54.25.0 (FFMPEG 0.11.5 release). Should do we need to continue 0.11.5 release support?

**Comment by tomoaki0705** [comment]
@VadimLevin is correct.
Here's my build log.
https://gist.github.com/tomoaki0705/e45f8494280607f16370f352fdab2275

It did fail building, but it didn't come up at cmake stage

```
--   Video I/O:
--     DC1394:                      NO
--     FFMPEG:                      YES
--       avcodec:                   YES (53.7.0)
--       avformat:                  YES (53.4.0)
--       avutil:                    YES (51.9.1)
--       swscale:                   YES (2.0.0)
--       avresample:                NO
--     GStreamer:                   NO
--     v4l/v4l2:                    YES (linux/videodev2.h)
 :
-- Generating done
-- Build files have been written to: /home/odroid/opencv-fork/build
 :
In file included from /home/odroid/opencv-fork/modules/videoio/src/cap_ffmpeg.cpp:50:
/home/odroid/opencv-fork/modules/videoio/src/cap_ffmpeg_impl.hpp: In function 'const char* _opencv_avcodec_get_name(CodecID)':
/home/odroid/opencv-fork/modules/videoio/src/cap_ffmpeg_impl.hpp:352:11: error: 'AVCodecDescriptor' does not name a type
  352 |     const AVCodecDescriptor *cd;
      |           ^~~~~~~~~~~~~~~~~
/home/odroid/opencv-fork/modules/videoio/src/cap_ffmpeg_impl.hpp:359:5: error: 'cd' was not declared in this scope; did you mean 'id'?
  359 |     cd = avcodec_descriptor_get(id);
      |     ^~
      |     id
```

Is this expected ? (your message insists that error should appear in cmake stage)

I don't think we need to support the issue about #18119
The right answer for solving #18119 is to install newer `ffmpeg` via `apt`

I vote +1 for raise minimal `libavcodec` version to something later.

**Comment by VadimLevin** [comment]
Not this message, the user should receive a message about what version is detected and what is the minimal version on CMake configuration step, not on build as for now. I'm working on it and it will be ready today.

**Comment by VadimLevin** [comment]
I resolved problems with missing `#if` version guards and @mshabunin script output gives expected output for all versions FFMPEG versions >= 1.1.16 and libav >= 9.20. This versions are checked during CMake configuration step, if one of the library has lower version FFMPEG is disabled.
I will back-port (`AV_CODEC_FLAG_GLOBAL_HEADER` and `AVDISCARD_NONINTRA`) guards  for 3.4 branch too in other PR.

**Review by alalek — APPROVED** [review]
Looks good to me! Thank you :+1:

**Pull request merged**
