### PR TITLE
Implement Soft NMS

### PR DESCRIPTION
**Pull request by WeiChungChang**
Implement Paper "Soft-NMS -- Improving Object Detection With One Line of Code"
https://arxiv.org/abs/1704.04503

It is the implementation part; will create sample program to RCNN models at the next step.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
@WeiChungChang Thank you for contribution!

Could you please to add in this PR:
- public API in headers
- documentation
- simple tests for new functionality

**Comment by asenyaev** [comment]
jenkins cn please retry a build

**Comment by asenyaev** [comment]
jenkins cn please retry a build

**Comment by asenyaev** [comment]
jenkins cn please retry a build

**Comment by asmorkalov** [comment]
@WeiChungChang friendly reminder.

**Comment by asmorkalov** [comment]
@WeiChungChang friendly reminder about tests.

**Comment by asmorkalov** [comment]
@WeiChungChang friendly reminder.

**Comment by rogday** [comment]
Replaced by https://github.com/opencv/opencv/pull/20813

**Pull request closed without merging**
