### PR TITLE
add noexcept to default constructor for: Mat, UMat, Mat_, MatSize, MatStep

### PR DESCRIPTION
**Pull request by diablodale**
Resolves issue https://github.com/opencv/opencv/issues/19682

### Pull Request Readiness Checklist

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [X] The PR is proposed to proper branch
- [X] There is reference to original bug report and related work
- [X] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by diablodale** [comment]
I'm seeing a lot of timeouts in Jenkins. Are there Jenkins problems occurring right now?

**Comment by asmorkalov** [comment]
jenkins cn please retry a build

**Comment by diablodale** [comment]
Thanks. Now I see only two failed tests within the "OpenCV CN Windows 10 x64". 
```
videoio/videocapture_acceleration.read/61
videoio/videocapture_acceleration.read/63
```

These two tests are failing in others PRs like https://github.com/opencv/opencv/pull/19685.
I suspect these two test failures are not related to this PR and are instead an unrelated external error introduced.

**Comment by alalek** [comment]
Thank you for contribution! This is one more step in migration to proper usage of C++11.

---

This patch should go into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first.
We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

Please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".


---

Ignore OpenCV CN checks. They are optional for now.

**Comment by diablodale** [comment]
Ah, I wrote in the issue but not here...
> As this is a new feature, not a bug fix, and requires C++11, this is for the 4.x branch of OpenCV.

**Comment by alalek** [comment]
OpenCV 3.4 is required to compile with C++98
There is no deny to compile/use OpenCV 3.4 with C++11/14/17

OpenCV 4.x just raises minimal supported compiler version (required version) from C++98 to C++11.

**Comment by diablodale** [comment]
Got it. I'm focused on OpenCV 4.x and adding new features there. This is due to

* The official statement from the OpenCV team when OpenCV 4.0 launched that the 3.x is in bugfix maintenance mode. https://opencv.org/opencv-4-0/
* My own priorities. This PR is a new feature, not a bug fix. I architect, develop, and test new features for the OpenCV 4.x branch. Anyone that wants a new feature that I develop in open-source projects is welcome to take my code and re-write/backport it for something old. I am not part of that because I don't architect, develop, or test it for these old branches. New features....I only develop for current branches; not branches that are in bugfix maintenance mode.
* I've been consistent with this in my contributions to OpenCV. I don't see this changing with new features.

Bugfixes are different. I might provide a bugfix that is for both 3.x and 4.x. I think I've only done that once for OpenCV -- it is rare. And that is the right approach as only important critical bugfixes should go to branches in bugfix maintenance mode.

**Review by alalek — APPROVED** [review]

**Pull request merged**
