### PR TITLE
cmake: add DllMain() into each OpenCV DLL

### LINKED ISSUE #12750: imgproc: program crashes after test of imgproc "OCL_ImgProc/CvtColor8u32f"
##### System information (version)

- OpenCV => 3.4 branch ( 0101fa789cde6c03bc58288a56e1d6ce7175cd48 )
- Operating System / Platform => Windows 10 64bit
- Compiler => Visual Studio 2015
- CUDA => 10.0

##### Summarized description
 - The ```opencv_test_imgproc``` passes, but when I ran it from target ```RUN_TESTS```, it says ```Segfault```

```
    Start 9: opencv_test_imgproc
1/1 Test #9: opencv_test_imgproc ..............***Exception: SegFault137.81 sec
```

- I ran ```opencv_test_imgproc``` separately, but all the test passes (!)
- To reproduce what gtest was seeing, I need to ran it in Debug mode
- When running ```opencv_test_imgproc``` with "Start debug" on Visual Studio 2015, the test passed but at the end, it did cause an ```Segfault``` at [ocl.cpp](https://github.com/opencv/opencv/blob/0101fa789cde6c03bc58288a56e1d6ce7175cd48/modules/core/src/ocl.cpp#L4328)
https://github.com/opencv/opencv/blob/0101fa789cde6c03bc58288a56e1d6ce7175cd48/modules/core/src/ocl.cpp#L4322-L4329

##### Detailed description
- I narrowed down the test case, and the test case was from ```OCL_ImgProc/CvtColor8u32f```
- Furthermore, it was related to test of either HSV/Lab/Luv conversion.
- Also, although I put a break point at where it causes ```Segfault```, it doesn't reproduce the situation.
- I have to exit from the [main routine call](https://github.com/opencv/opencv/blob/0101fa789cde6c03bc58288a56e1d6ce7175cd48/modules/imgproc/test/test_main.cpp) and it was happening after that exit call.  Mysterious...

- After watching the source code, I realized that some of the static ```UMat``` was used in a wrong scope, such like [here ](https://github.com/opencv/opencv/blob/0101fa789cde6c03bc58288a56e1d6ce7175cd48/modules/imgproc/src/color_hsv.cpp#L1483-L1486)
https://github.com/opencv/opencv/blob/0101fa789cde6c03bc58288a56e1d6ce7175cd48/modules/imgproc/src/color_hsv.cpp#L1483-L1486
- These ```UMat``` were passed as a [parameter of the OpenCL kernel](https://github.com/opencv/opencv/blob/0101fa789cde6c03bc58288a56e1d6ce7175cd48/modules/imgproc/src/color_hsv.cpp#L1516-L1521) but the scope [was closed before](https://github.com/opencv/opencv/blob/0101fa789cde6c03bc58288a56e1d6ce7175cd48/modules/imgproc/src/color_hsv.cpp#L1519) it was [actually used](https://github.com/opencv/opencv/blob/0101fa789cde6c03bc58288a56e1d6ce7175cd48/modules/imgproc/src/color_hsv.cpp#L1521)
https://github.com/opencv/opencv/blob/0101fa789cde6c03bc58288a56e1d6ce7175cd48/modules/imgproc/src/color_hsv.cpp#L1516-L1521
- Looking back the history, it seems that color convert was splitted in [early 2018](https://github.com/opencv/opencv/commit/0b900b54e54e8cbd19a65cfe69d20838f142e6b3), and before the split, the scope was aligned with the actual use.
- I moved the ```UMat``` declarations and also, I removed the ```static```
- Now the test passed without ```Segfault```

##### Steps to reproduce
- Build under environment explained above.
- Run with CUDA 10.0 and run the OpenCL kernel on dGPU 
- ```OPENCV_OPENCL_DEVICE=:dgpu opencv_test_imgproc --gtest_filter=OCL_ImgProc/CvtColor8u32f*``` 

- Also, there I'm not sure why this doesn't happen on ```CPU``` and ```igpu``` on my laptop.
- Still, the scope difference seems bad, so I think it has meaning to fix the scope.

### PR DESCRIPTION
**Pull request by alalek**
to detect process termination after ExitProcess() call

resolves #12750
relates #1972 #1490

```
allow_multiple_commits=1
```

### CODE REVIEW

**Comment by tomoaki0705** [comment]
OK, I tried your branch (3fbd7e2b1) and it still caused crash.

I looked in and tried to gather information as much as possible

#### command
```
opencv_test_imgproc --gtest_filter=*CvtColor*HSV*
```

#### Raw Log
```
CTEST_FULL_OUTPUT
OpenCV version: 3.4.3-dev
OpenCV VCS version: 3.4.3-306-g3fbd7e2b1
Build type: N/A
WARNING: build value differs from runtime: Debug
Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe  (ver 19.0.24215.1)
Parallel framework: ms-concurrency
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2
Intel(R) IPP version: ippIP AVX2 (l9) 2017.0.3 (-) Jul 31 2017
[ INFO:0] Initialize OpenCL runtime...
OpenCL Platforms:
    NVIDIA CUDA
        dGPU: GeForce GTX 1060 (OpenCL 1.2 CUDA)
    Intel(R) OpenCL
        iGPU: Intel(R) UHD Graphics 620 (OpenCL 2.1 )
        CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (OpenCL 2.1 (Build 10))
Current OpenCL device:
    Type = dGPU
    Name = GeForce GTX 1060
    Version = OpenCL 1.2 CUDA
    Driver version = 411.63
    Address bits = 64
    Compute units = 10
    Max work group size = 1024
    Local memory size = 48 KB
    Max memory allocation size = 1 GB 512 MB
    Double support = Yes
    Host unified memory = No
    Device extensions:
        cl_khr_global_int32_base_atomics
        cl_khr_global_int32_extended_atomics
        cl_khr_local_int32_base_atomics
        cl_khr_local_int32_extended_atomics
        cl_khr_fp64
        cl_khr_byte_addressable_store
        cl_khr_icd
        cl_khr_gl_sharing
        cl_nv_compiler_options
        cl_nv_device_attribute_query
        cl_nv_pragma_unroll
        cl_nv_d3d10_sharing
        cl_khr_d3d10_sharing
        cl_nv_d3d11_sharing
        cl_nv_copy_opts
        cl_nv_create_buffer
    Has AMD Blas = No
    Has AMD Fft = No
    Preferred vector width char = 1
    Preferred vector width short = 1
    Preferred vector width int = 1
    Preferred vector width long = 1
    Preferred vector width float = 1
    Preferred vector width double = 1
Note: Google Test filter = *CvtColor*HSV*
[==========] Running 64 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 64 tests from OCL_ImgProc/CvtColor8u32f
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGB2HSV/0, where GetParam() = (CV_8U, false)
[ INFO:0] Successfully initialized OpenCL cache directory: C:\Users\tomoaki\AppData\Local\Temp\opencv\3.4.x-dev\opencl_cache\
[ INFO:0] Preparing OpenCL cache configuration for context: NVIDIA_Corporation--GeForce_GTX_1060--411_63
[       OK ] OCL_ImgProc/CvtColor8u32f.RGB2HSV/0 (97 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGB2HSV/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGB2HSV/1 (10 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGB2HSV/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGB2HSV/2 (8 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGB2HSV/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGB2HSV/3 (6 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGR2HSV/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGR2HSV/0 (8 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGR2HSV/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGR2HSV/1 (7 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGR2HSV/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGR2HSV/2 (7 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGR2HSV/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGR2HSV/3 (7 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV/0 (8 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV/1 (7 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV/2 (7 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV/3 (12 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV/0 (11 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV/1 (11 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV/2 (9 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV/3 (10 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGB2HSV_FULL/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGB2HSV_FULL/0 (11 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGB2HSV_FULL/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGB2HSV_FULL/1 (9 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGB2HSV_FULL/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGB2HSV_FULL/2 (4 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGB2HSV_FULL/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGB2HSV_FULL/3 (10 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGR2HSV_FULL/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGR2HSV_FULL/0 (8 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGR2HSV_FULL/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGR2HSV_FULL/1 (8 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGR2HSV_FULL/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGR2HSV_FULL/2 (4 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGR2HSV_FULL/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGR2HSV_FULL/3 (9 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV_FULL/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV_FULL/0 (8 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV_FULL/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV_FULL/1 (13 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV_FULL/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV_FULL/2 (5 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV_FULL/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.RGBA2HSV_FULL/3 (13 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV_FULL/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV_FULL/0 (12 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV_FULL/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV_FULL/1 (10 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV_FULL/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV_FULL/2 (6 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV_FULL/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.BGRA2HSV_FULL/3 (10 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGB/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGB/0 (10 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGB/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGB/1 (10 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGB/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGB/2 (8 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGB/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGB/3 (9 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGR/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGR/0 (9 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGR/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGR/1 (10 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGR/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGR/2 (10 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGR/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGR/3 (16 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA/0 (11 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA/1 (14 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA/2 (10 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA/3 (14 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA/0 (11 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA/1 (11 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA/2 (9 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA/3 (13 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGB_FULL/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGB_FULL/0 (10 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGB_FULL/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGB_FULL/1 (10 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGB_FULL/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGB_FULL/2 (8 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGB_FULL/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGB_FULL/3 (12 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGR_FULL/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGR_FULL/0 (13 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGR_FULL/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGR_FULL/1 (12 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGR_FULL/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGR_FULL/2 (9 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGR_FULL/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGR_FULL/3 (13 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA_FULL/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA_FULL/0 (11 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA_FULL/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA_FULL/1 (8 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA_FULL/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA_FULL/2 (4 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA_FULL/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2RGBA_FULL/3 (8 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA_FULL/0, where GetParam() = (CV_8U, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA_FULL/0 (3 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA_FULL/1, where GetParam() = (CV_8U, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA_FULL/1 (3 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA_FULL/2, where GetParam() = (CV_32F, false)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA_FULL/2 (3 ms)
[ RUN      ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA_FULL/3, where GetParam() = (CV_32F, true)
[       OK ] OCL_ImgProc/CvtColor8u32f.HSV2BGRA_FULL/3 (4 ms)
[----------] 64 tests from OCL_ImgProc/CvtColor8u32f (1070 ms total)

[----------] Global test environment tear-down
[==========] 64 tests from 1 test case ran. (1092 ms total)
[  PASSED  ] 64 tests.
OpenCV: terminating: opencv_highgui
OpenCV: terminating: opencv_videoio
OpenCV: terminating: opencv_imgcodecs
OpenCV: terminating: opencv_imgproc
```
To emphasize, ```OpenCV: terminating: opencv_imgproc``` was the last message on the console

#### dialog message
```
Exception thrown at 0x00007FF8C53C024E (ntdll.dll) in opencv_test_imgprocd.exe: 0xC0000005: Access violation reading location 0x0000000000000010.

If there is a handler for this exception, the program may be safely continued.
```


#### call stack
```
 	ntdll.dll!00007ff8c53c024e()	Unknown
 	nvopencl.dll!00007ff8723d4c60()	Unknown
 	nvopencl.dll!00007ff8721aaee1()	Unknown
 	nvopencl.dll!00007ff871fac36a()	Unknown
 	nvopencl.dll!00007ff871f9d6b5()	Unknown
 	nvopencl.dll!00007ff871f9db65()	Unknown
 	nvopencl.dll!00007ff871fb0808()	Unknown
>	opencv_core343d.dll!OPENCL_FN_clReleaseMemObject_switch_fn(_cl_mem * p1) Line 526	C++
 	opencv_core343d.dll!cv::ocl::OpenCLBufferPoolImpl::_releaseBufferEntry(const cv::ocl::CLBufferEntry & entry) Line 4328	C++
 	opencv_core343d.dll!cv::ocl::OpenCLBufferPoolBaseImpl<cv::ocl::OpenCLBufferPoolImpl,cv::ocl::CLBufferEntry,_cl_mem * __ptr64>::release(_cl_mem * buffer) Line 4237	C++
 	opencv_core343d.dll!cv::ocl::OpenCLAllocator::deallocate_(cv::UMatData * u) Line 4905	C++
 	opencv_core343d.dll!cv::ocl::OpenCLAllocator::deallocate(cv::UMatData * u) Line 4778	C++
 	opencv_core343d.dll!cv::UMat::deallocate() Line 491	C++
 	opencv_core343d.dll!cv::UMat::release() Line 3828	C++
 	opencv_core343d.dll!cv::UMat::~UMat() Line 481	C++
 	[External Code]	
```

#### crashed location
[here](https://github.com/alalek/opencv/blob/3fbd7e2b12f61501a36fe09f9b45636096eaa7d3/modules/core/src/opencl/runtime/autogenerated/opencl_core_impl.hpp#L526)

https://github.com/alalek/opencv/blob/3fbd7e2b12f61501a36fe09f9b45636096eaa7d3/modules/core/src/opencl/runtime/autogenerated/opencl_core_impl.hpp#L526

#### ```cv::__termination```
```
cv::__termination	false	bool
```

#### just before the crash
Since I could set a breakpoint at [the printf](https://github.com/alalek/opencv/blob/3fbd7e2b12f61501a36fe09f9b45636096eaa7d3/cmake/templates/dllmain.cpp.in#L33), I could trace a little bit in side Visual Studio runtime.
There is ```C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\vcruntime\utility.cpp```and the last call was to ```_execute_onexit_table```

````
extern "C" void __cdecl __scrt_dllmain_uninitialize_c()
{
    if (__scrt_is_ucrt_dll_in_use())
    {
        _execute_onexit_table(&module_local_atexit_table); // here
    }
    else
    {
        if (!_is_c_termination_complete())
        {
            _cexit();
        }
    }
}
````

**Comment by tomoaki0705** [comment]
@alalek Thank you !

Now, commit of 11e2a216c513e302e6bc1c475c40b7717fbb8ed0 passed the test without any crashes.
Thank you again !

**Comment by alalek** [comment]
:+1:

**Pull request merged**
