### PR TITLE
docs: hotfix: call isOpened() in python bg sub tutorial

### PR DESCRIPTION
**Pull request by alkasm**
https://github.com/opencv/opencv/issues/19299

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Review by asmorkalov — APPROVED** [review]
:+1:

**Comment by asmorkalov** [comment]
@alkasm Thanks for the patch. The same issue exists in branch 3.4. Please re-base your patch on top of 3.4 and re-target the PR to 3.4. OpenCV team merges 3.4 to master weekly or biweekly and the fix will be applied everywhere.

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no need to re-open PR, apply changes "inplace".

**Comment by alkasm** [comment]
No problem, rebased on top of 3.4.

**Review by asmorkalov — APPROVED** [review]
:+1:

**Pull request merged**
