### PR TITLE
update libjpeg-turbo version to 2.1.3

### PR DESCRIPTION
**Pull request by ocpalo**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by ocpalo** [comment]
After this PR merged, i will open another PR for SIMD/NASM support for libjpeg-turbo.

**Comment by ocpalo** [comment]
I did include assembly files in this pull request. Should I remove them and include it with SIMD/NASM support for libjpeg-turbo? I rather to keep in this pull request because they are part of the library. Let me know what you think.

**Review by vpisarev — APPROVED** [review]

**Comment by vpisarev** [comment]
assembly files in this PR are appropriate, I think. It's atomic pull request that brings everything what is needed from libjpeg-turbo side. Next PR should update build scripts to include those assembly files into the build

**Comment by ocpalo** [comment]
Next PR is ready. When this PR merged, i will rebase it and open it immediately.

**Comment by alalek** [comment]
BTW, libjpeg-turbo 2.1.4 has been released: https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.1.4

**Comment by ocpalo** [comment]
I have limited time left in order to successfully complete GSoC and I am little behind. Lets merge SIMD pr if appropiate, after GSoC, if noone does, i will update the libjpeg-turbo version.

**Comment by vpisarev** [comment]
@ocpalo, please, submit the subsequent PR with enabling NASM in libjpeg-turbo

**Pull request merged**
