### PR TITLE
changed OpenCV license from BSD to Apache 2 license

### PR DESCRIPTION
**Pull request by vpisarev**
Many files still contain old-style copyrights though

See See https://github.com/opencv/opencv/wiki/OE-32.--Change-OpenCV-License-to-Apache-2.

Should be merged together with https://github.com/opencv/opencv_contrib/pull/2628

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (~~BSD~~ Apache 2.0) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [N/A] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by vpisarev** [comment]
@alalek, many source files in OpenCV modules contain the old BSD license in verbatim style instead of simple reference to opencv/LICENSE. I suggest to change those files as well, but do it in subsequent multiple PRs, 1 or a few modules per pull request.

**Comment by berak** [comment]
> Many files still contain old-style copyrights though

what should be the replacement ? like this ? (would it be enough ?)

```
// This file is part of the OpenCV project.
// It is subject to the license terms in the LICENSE file found in the top-level directory
// of this distribution and at http://opencv.org/license.html.
```
(took the liberty to make it *the* OpenCV project..)

**Comment by vpisarev** [comment]
@berak, I agree, "the" should probably be removed :)

**Comment by vpisarev** [comment]
@alalek, @berak, I've modified filterengine.hpp and phasecorr.cpp; they represent the proposed way of handling the transition to APL2

**Comment by alalek** [comment]
I don't agree with license header update on [Wiki](https://github.com/opencv/opencv/wiki/Coding_Style_Guide/_compare/7741191a5d6a1ef1b553e4d188b07d9916d44aad):

```.diff
-// This file is part of OpenCV project.
-// It is subject to the license terms in the LICENSE file found in the top-level directory
-// of this distribution and at http://opencv.org/license.html.	
+// This file is a part of OpenCV project.
+// See opencv/LICENSE and http://opencv.org/license.html for the actual licensing terms.
```

1. "a part" is not necessary. We are not native speakers, so lets just check other projects:

```
$ grep -R "This file is part" /usr/include/ | wc -l
5596
$ grep -R "This file is a part" /usr/include/ | wc -l
14
```

(GLIBC / GNU ISO C++, Eigen, FFmpeg, HDF5, Qt are without the "a" article)

2. "opencv/LICENSE" doesn't look right for "opencv_contrib" repository.

3. Current(previous) short license header doesn't conflict with BSD-3 => Apache 2 migration. This change is not necessary.

**Comment by vpisarev** [comment]
@alalek, I reverted the change in wiki. I can submit the follow-up pull request to change it in filterengine.hpp, or you can do it if/when some massive patches are submitted with the license changes.

**Pull request merged**
