### PR TITLE
Updated PR #7159 (OSX AVFoundation support)

### PR DESCRIPTION
**Pull request by alalek**
Related #7159

### CODE REVIEW

**Comment by varunkworld** [comment]
@alalek I am new here. Can you tell me what am I supposed to do now about the "QTKit problem" ?

**Comment by alalek** [comment]
@varunkworld After these steps:
```
$ git clone https://github.com/Itseez/opencv.git
$ cd opencv
```
Apply this patch:
```
$ git fetch https://github.com/opencv/opencv.git +pull/7266/head:pr7266
$ git checkout pr7266 # instread of 3.0.0 or 3.1.0
```
And continue with "Step 8"

BTW, "opencv_contrib" repo should be synchronized with "opencv" repo, so checkout "master" branch also.

**Comment by varunkworld** [comment]
@alalek Thanks ! Now I can do my opencv projects.

**Comment by vpisarev** [comment]
:+1:

**Comment by pr0methaz1ne** [comment]
@alalek Wait so what do you type to install the contrib?

**Comment by toaditoad** [comment]
@pr0methaz1ne I think you just have to add ```--with-contrib```

Thanks guys, finally my installation worked with:
```brew install opencv3 --with-java --with-contrib --with-python --HEAD```

**Comment by ChristopheEcabert** [comment]
Thanks for the fix but apparently there is an issue with the ```getProperty(int)``` method. At the moment only base class method is called therefore always returning 0.
Shouldn't ```virtual double CvCaptureCAM::getProperty(int property_id) const;``` and ```virtual double CvCaptureFile::getProperty(int property_id) const;``` be declared as non-const to respect ```CvCapture``` interface ?

**Comment by alalek** [comment]
@ChristopheEcabert Nice catch! Thanks! Could you check #7383?

**Comment by aaronbatchelder** [comment]
@alalek thanks for being on top of this! The below suggestions worked great on Sierra with Xcode 8.

```
$ git clone https://github.com/Itseez/opencv.git
$ cd opencv

Apply this patch:

$ git fetch https://github.com/opencv/opencv.git +pull/7266/head:pr7266
$ git checkout pr7266 # instread of 3.0.0 or 3.1.0
```

**Pull request merged**
