### PR TITLE
Solve Issue 7063

### LINKED ISSUE #7063: Cholesky function in opencv without HAL
- OpenCV => 3.1
- Operating System / Platform => Windows 10 64 Bit
- Compiler => Visual Studio 2013

Hi,

I want to have cholesky decomposition of a matrix. In opencv doc is [here ](http://docs.opencv.org/3.1.0/db/de0/group__core__utils.html#gac8d860b8a49bf2ed304b1c82acb916e5)and I think this [doc ](http://docs.opencv.org/master/d8/d0e/group__core__hal__interface__decomp__cholesky.html#gsc.tab=0)is still good. In following program I try to have cholesky decomposition of matrix A 

```
    #include <opencv2/opencv.hpp>
    #include <iostream>
    
    using namespace cv;
    using namespace std;
    
    
    int main (int argc,char **argv)
    {
    
        Mat m1=(Mat_<double>(3,3) << 4,12,-16,12,37,-43,-16,-43,98);
        
        cout<<m1<<endl;
        Cholesky ((double*)m1.ptr(),m1.cols*8, 3,NULL, 0, 0);
        m1.at<double>(0,1)=0;m1.at<double>(0,2)=0;m1.at<double>(1,2)=0;
        cout<<"L = "<<m1<<endl;
        cout<<"L' = "<<m1.t()<<endl;
        cout << "LL'="<<m1*m1.t()<<endl;
    }

```

LL' should be m (m1 is an axample in [wikipedia](https://en.wikipedia.org/wiki/Cholesky_decomposition#cite_note-4)). Something is strange.  In this [post ](http://answers.opencv.org/question/99704/cholesky-function-in-opencv/) Eduardo give a link to a static cholesky function in opencv which gives a good result

I think two lines are missing in [source code](https://github.com/opencv/opencv/blob/master/modules/core/src/matrix_decomp.cpp#L155) 
```
for( i = 0; i < m; i++ )
    L[i*astep + i]=1/L[i*astep + i];

```

### PR DESCRIPTION
**Pull request by LaurentBerger**
resolves #7063

This pullrequest changes

Cholesky decompostion is now good. Change are agree with @sovrasov comments.  There is no change in code for linear solver.

### CODE REVIEW

**Comment by mshabunin** [comment]
Probably we could also replace similar [function](https://github.com/opencv/opencv/blob/master/modules/ml/src/inner_functions.cpp#L115) in _ml_ module and update [wrapper](https://github.com/opencv/opencv/blob/master/modules/stitching/src/autocalib.cpp#L50) in _stitching_.

**Comment by LaurentBerger** [comment]
Yes you are right For wrapper I proposed to delete https://github.com/opencv/opencv/blob/master/modules/stitching/src/autocalib.cpp#L55-L56.
For wrapper something like this
```
    CV_Assert(A.type() == CV_32F);

    S = A.clone();
    Cholesky ((float*)S.ptr(),S.step, 3,NULL, 0, 0);
    S = S.t();
    for (int i=1;i<S.rows;i++)
        for (int j=0;j<i;j++)
            S.at<float>(i,j)=0;

```

**Comment by vpisarev** [comment]
@sovrasov, could you please review it?

**Comment by sovrasov** [comment]
@LaurentBerger patch is OK but it's necessary to squash commits into one before merge.

Also will be useful to add an accuracy test like this:
```
    const int n = 5;
	Mat A(n, n, CV_64F), refA;
	Mat mean(1, 1, CV_64F);
	*mean.ptr<double>() = 10.0;
	Mat dev(1, 1, CV_64F);
	*dev.ptr<double>() = 10.0;
	RNG rng(10);
	rng.fill(A, RNG::NORMAL, mean, dev);
	A = A*A.t();
	A.copyTo(refA);
	Cholesky(A.ptr<double>(), A.step, n, NULL, 0, 0);

  for (int i = 0; i < A.rows; i++)
    for (int j = i + 1; j < A.cols; j++)
      A.at<double>(i, j) = 0.0;

  assert(norm(refA - A*A.t()) < 10e-5);
```

I can create a new PR with the test or @LaurentBerger can you add test please?

**Comment by LaurentBerger** [comment]
@sovrasov I'm not familiar with test. But I can try. Does it mean that I must add test in [test_operations](https://github.com/opencv/opencv/blob/master/modules/core/test/test_operations.cpp) like method [test_svd](https://github.com/opencv/opencv/blob/master/modules/core/test/test_operations.cpp#L1062) with your code?

**Comment by alalek** [comment]
@LaurentBerger Take a look on [this](https://github.com/opencv/opencv/blob/f210602d1e7f18182b38b528fb9046b2357c2e53/modules/core/test/test_utils.cpp#L223-L233).

**Comment by sovrasov** [comment]
@LaurentBerger no, just put test code into 
`TEST(Core_Array, CholeskyDecomp) { <testcase code> }`
and insert it at the end of test_operations.cpp
Use EXPECT_TRUE() instead of assert()

**Comment by sovrasov** [comment]
@LaurentBerger thanks for patch and test!
And the last needed thing before merge is to squash commits into one.

**Comment by LaurentBerger** [comment]
Thanks I learnt how to write a test

**Comment by sovrasov** [comment]
:+1:

**Pull request merged**
