### PR TITLE
Faster-RCNN object detection models from TensorFlow

### PR DESCRIPTION
**Pull request by dkurt**
### This pullrequest changes

Script to create a config file for Faster-RCNN networks from TensorFlow.

resolves https://github.com/opencv/opencv/issues/10393
related:
http://answers.opencv.org/question/187943/opencv-python-34-error-in-loading-tensorflow-object-detection-model/
http://answers.opencv.org/question/188747/how-to-use-readnetfromtensorflow-with-resnet50-network/

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/455

### CODE REVIEW

**Comment by teaglin** [comment]
Hi, I tried out this build and it works with the coco model in the TensorFlow model zoo. But it does not work with a custom trained model. I get this error. Any ideas?

Error: Unspecified error (Const input blob for weights not found) in getConstBlob, file /Volumes/HD3/opencv/modules/dnn/src/tensorflow/tf_importer.cpp, line 464

**Comment by dkurt** [comment]
@teaglin, please specify what [config file] did you use https://github.com/tensorflow/models/tree/master/research/object_detection/samples/configs and what changes in it did you made? If you can share the model we can solve it faster. Thanks!

**Comment by teaglin** [comment]
@dkurt I used faster_rcnn_inception_v2_pets.config as a starting point. The only change I made was to the class count. I only have 1 class. The model can be downloaded here. Let me know if you need anything else.

https://www.dropbox.com/s/d5oh7lp8iutjdtd/frozen_inference_graph.pb?dl=0

**Comment by dkurt** [comment]
@teaglin, Thank you! Could you pleas specify what kind of object is detected to test an accuracy?

**Comment by teaglin** [comment]
@dkurt The model is used for detecting sports balls.

**Comment by dkurt** [comment]
@teaglin, Please regenerate a `.pbtxt` file using an updated script from this PR. I've added extra graph transformations to remove `Identity` nodes. Then you can use [object_detection.py](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.py):
```
python object_detection.py --input footballer.jpg --model frozen_inference_graph.pb --config graph.pbtxt --mean 127.5 127.5 127.5 --scale 0.00784 --rgb
```
res

**Comment by teaglin** [comment]
@dkurt Awesome, I really appreciate the help. I will try this out. 

On a side note do any of the other configs of rcnn work? I tried the coco resnet50 and resnet101 from tensor flow model zoo. They loaded, but I got really low confidence values. Are there different mean and scale values that have to be used?

**Comment by dkurt** [comment]
@teaglin, Thank you!

> On a side note do any of the other configs of rcnn work? I tried the coco resnet50 and resnet101 from tensor flow model zoo. They loaded, but I got really low confidence values. Are there different mean and scale values that have to be used?

Definitely yes, you may check it at README (see PR's files). All the ResNet-based Faster-RCNN networks work with input images with subtracted mean values `103.939 116.779 123.68` (blue, green, red channels correspondingly) and scale = 1.0 (no scale).

**Comment by vpisarev** [comment]
:+1:

**Comment by UserLiubov** [comment]
Hi, I created graph.pbtxt with tf_text_graph_faster_rcnn.py from frozen_inference_graph.pb, ran `cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'graph.pbtxt')` and I got next error:
```
CropAndResize:CropAndResize(FirstStageFeatureExtractor/InceptionV2/InceptionV2/Mixed_4e/concat)(CropAndResize/crop_size)(detection_out)
method:[ ]
extrapolation_value:[ ]
OpenCV(3.4.1) Error: Unspecified error (Unknown layer type CropAndResize in op CropAndResize) in cv::dnn::experimental_dnn_v4::`anonymous-namespace'::TFImporter::populateNet, file C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp, line 1582
Traceback (most recent call last):
  File "E:/Диплом/tensorflow network/test.py", line 3, in <module>
    cvNet = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'graph.pbtxt')
cv2.error: OpenCV(3.4.1) C:\projects\opencv-python\opencv\modules\dnn\src\tensorflow\tf_importer.cpp:1582: error: (-2) Unknown layer type CropAndResize in op CropAndResize in function cv::dnn::experimental_dnn_v4::`anonymous-namespace'::TFImporter::populateNet
```
I thought that I need to manually update the file `opencv/samples/dnn/tf_text_graph_faster_rcnn.py` and others but I can't find the file on my disk (there is no directory C:\projects\).
I have this error on both Windows 10 and Ubuntu 16.4.
I installed opencv-python via pip on Windows and vaa conda-forge on Ubuntu.
Please, can you give me any advices?

**Comment by dkurt** [comment]
@UserLiubov, this patch has been merged a week ago. I don't think that opencv installed from pip is up to date. Try to build it from source https://github.com/opencv/opencv/tree/3.4.
Duplicate of https://github.com/opencv/opencv/issues/11691.

**Comment by Luca3424** [comment]
Hi, I'm trying to load a custom trained TensorFlow faster_rcnn_inception_v2 model with faster_rcnn_inception_v2_pets.config as a starting point.
I'm using OpenCV 3.4.2 and I updated the graph.pbtxt file with the tf_text_graph_faster_rcnn.py script.
While using a ssd_inception_v2 custom model everything works fine, but as soon as I'm trying the F-RCNN it crashes with the following error:

> \opencv\modules\dnn\src\tensorflow\tf_importer.cpp:532: error: (-2:Unspecified error) Const kernel input not found in function 'cv::dnn::experimental_dnn_v5::`anonymous-namespace'::TFImporter::getConstBlob'

It seems like it's crashing while loading the model and config in the readNetFromTensorflow function.

Does anyone of you guys know this problem?
Thanks!

**Pull request merged**
