### PR TITLE
Faster-RCNN object detection model

### PR DESCRIPTION
**Pull request by dkurt**
### This pullrequest changes

origin: https://github.com/rbgirshick/py-faster-rcnn

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/419

VGG16 model:
frame_screenshot_14 12 2017

ZF model:
frame_screenshot_zf_14 12 2017

### CODE REVIEW

**Comment by vpisarev** [comment]
@dkurt, wow, very cool!

**Comment by vpisarev** [comment]
:+1:

**Comment by hrnr** [comment]
Hi, 

do you still have the model files for Faster-RCNN? In the linked repository https://github.com/rbgirshick/py-faster-rcnn I was only able to find a link to `coco_vgg16_faster_rcnn_final.caffemodel`, which was trained on coco dataset, but the prototxt we have in opencv_extra are for pascal_voc dataset.

Maybe it would be nice to add the models to the `download_models.py` script.

Cheers,
Jiri

**Comment by dkurt** [comment]
@hrnr, that is good idea! Feel free to propose a PR. Also tests may be added.

**Comment by dkurt** [comment]
@hrnr, We did it. See https://github.com/opencv/opencv_extra/pull/435.

**Comment by hrnr** [comment]
Thanks a lot. `download_models.py` is starting to look like a small model zoo for OpenCV.

**Pull request merged**
