### PR TITLE
Parse TensorFlow models with help of text graphs

### PR DESCRIPTION
**Pull request by dkurt**
### This pullrequest changes

resolves https://github.com/opencv/opencv/issues/9751
resolves https://github.com/opencv/opencv/issues/9660

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/387

* A way to manage TensorFlow graphs in Caffe like style: use `.caffemodel` as a weights storage and `.prototxt` as a network configuration.
* Script for FP32->FP16 frozen graphs conversion. In case of MobileNet-SSD it gives 15.7MB (origin graph takes 29MB).
* Accuracy metrics achieved by COCO evalutation tools, http://cocodataset.org/#detections-eval on the validation dataset (2017).

Using TensorFlow (FP32, FP16):
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.258
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.421
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.272
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.034
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.217
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.547
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.237
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.339
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.358
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.069
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.357
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.685
```
Using OpenCV (FP32, FP16):
```
Average Precision @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.257 (-0.001)
Average Precision @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.420 (-0.001)
Average Precision @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.272         
Average Precision @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.034         
Average Precision @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.215 (-0.002)
Average Precision @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.546 (-0.001)
Average Recall    @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.237         
Average Recall    @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.340 (+0.001)
Average Recall    @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.357 (-0.001)
Average Recall    @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.070 (+0.001)
Average Recall    @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.356 (-0.001)
Average Recall    @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.683 (-0.002)
```
best time: 21ms (Intel&reg; Core&trade; i7-6700K CPU @ 4.00GHz x 8)
out

### CODE REVIEW

**Comment by hansg60** [comment]
@dkurt That's really good.  Thank you.

**Comment by stereomatchingkiss** [comment]
@dkurt May you show us how to parse tensorflow model with text graph?Anything need to change when saving the model of tensorflow or loading the model from opencv dnn? Would this pull request able to solve #9660? Thanks

**Comment by hansg60** [comment]
@dkurt Hi Dmitry,
I merged your changes locally and built opencv and got a different error.  

1. Built opencv with the changes in your branch.
2. I downloaded ssd_mobilenet_v1_coco from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md
3. I didn't find a ssd_mobilenet_v1_coco.pbtxt in this archive, but there is a graph.pbtxt file.  Is this the same thing???
4. I executed python mobilenet_ssd_python.py --weights ./frozen_inference_graph.pb --prototxt ./graph.pbtxt --num_classes 90

5. Got this error:
[libprotobuf ERROR /Users/hans/opencv_git/3rdparty/protobuf/src/google/protobuf/text_format.cc:298] Error parsing text-format tensorflow.GraphDef: 113344:5: Unknown enumeration value of "DT_RESOURCE" for field "type".
OpenCV Error: Unspecified error (FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: ./graph.pbtxt) in ReadTFNetParamsFromTextFileOrDie, file /Users/hans/opencv_git/modules/dnn/src/tensorflow/tf_io.cpp, line 72
Traceback (most recent call last):
  File "mobilenet_ssd_python.py", line 57, in <module>
    net = cv.dnn.readNetFromTensorflow(args.weights, args.prototxt)
cv2.error: /Users/hans/opencv_git/modules/dnn/src/tensorflow/tf_io.cpp:72: error: (-2) FAILED: ReadProtoFromTextFileTF(param_file, param). Failed to parse GraphDef file: ./graph.pbtxt in function ReadTFNetParamsFromTextFileOrDie

**Comment by dkurt** [comment]
@hansg60, according to script's arguments help `prototxt` is a path to ssd_mobilenet_v1_coco.pbtxt from opencv_extra, https://github.com/opencv/opencv_extra/pull/387

**Comment by vpisarev** [comment]
@dkurt, you are the monster! thank you! :+1:

**Comment by vpisarev** [comment]
oops, looks like there are merge conflicts. @dkurt, could you please resolve them?

**Comment by dkurt** [comment]
@vpisarev, thank you! Sure, done!

**Comment by bowler77** [comment]
@dkurt, thank you for your great job, I can now use Tensorflow released ssd_mobilenet_v1_coco model in dnn module.
About the swapRB flag, I think it should be set to true in blobFromImage() for tensorflow model (convert opencv BGR to tensorflow RGB order).
And set confidence_threshold in ssd_mobilenet_v1_coco.pbtxt from 0.2 to 0.01 to calculate AP (Average Precision) more accurate.
Then the result is very close to tensorflow.
How can I generate .pbtxt file for other tensorflow released object detection model, e.g., ssd_inception_v2_coco or rfcn_resnet101_coco, faster_rcnn_resnet101_coco...?
Thank you.

**Comment by dkurt** [comment]
@bowler77, thank you for a feedback! You're right, we need to pass RGB images, I fixed it. Both RGB images and confidence threshold 0.01 gives better metrics.
I think we'll prepare a wiki page with an example.

@vpisarev, please don't merge until the changes proposed by @bowler77 would be pushed. Thanks!

**Comment by vpisarev** [comment]
thank you! :+1:

**Comment by barbecacov** [comment]
@bowler77 Have you generated the .pbtxt for the ssd_inception_v2_coco model?I seriously need it now,pls

**Comment by dkurt** [comment]
@barbecacov, please let's make a conversation at https://github.com/opencv/opencv/issues/9977. Don't ping closed issues / PRs.

**Comment by RomRoc** [comment]
Hello, I executed sample code mobilenet_ssd_python.py for object detection with suggested Tensorflow model, it works perfectly.
Now I would like to try other models from Tensorflow detection model zoo.
I started from the simplest, downloading the [ssd_mobilenet_v1_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2017_11_17.tar.gz) I substituted the frozen_inference_graph.pb file in input parameter, and I used the same ssd_mobilenet_v1_coco.pbtxt but it doesn't work. I get this error:
cv2.error: /home/user/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:567: error: (-2) Const input blob for weights not found in function getConstBlob

Can you tell me where I'm wrong please?
Thanks

**Comment by kr0920** [comment]
@dkurt Hi, i am new to tensorflow. Now i want to convert my onnx model to tensorflow. But when i load my converted model using Opencv(C++), there occurs error:

my_variable:VariableV2
dtype:0
container:[ ]
shape:[ ]
shared_name:[ ]
OpenCV(3.4.1) Error: Unspecified error (Unknown layer type VariableV2 in op my_variable) in populateNet, file/opencv-3.4.1/modules/dnn/src/tensorflow/tf_importer.cpp, line 1582
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.1) /opencv-3.4.1/modules/dnn/src/tensorflow/tf_importer.cpp:1582: error: (-2) Unknown layer type VariableV2 in op my_variable in function populateNet

I guess the reason is what you have mentioned that the newer version graph text has obfuscated Const nodes names(i.e. FeatureExtractor/MobilenetV1/Conv2d_0/weights to FeatureExtractor/MobilenetV1/Conv2d_0/weights/read/_104__cf__107). I want to know how can i generate my own models' correct graph text?

**Comment by dkurt** [comment]
@kr0920, Have you tried https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API? Please do not closed issues/pull requests to ask questions because they are hard to track. Use a forum instead: http://answers.opencv.org.

**Pull request merged**
