### PR TITLE
DNN: multiple outputs for asynchronous inference

### PR DESCRIPTION
**Pull request by dkurt**
### This pullrequest changes

- [x] NNBuilder API
- [ ] nGraph API

resolves https://github.com/opencv/opencv/issues/15023

Let's merge it after https://github.com/opencv/opencv/pull/15537

```
force_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2020.1.0:16.04
build_image:Custom Win=openvino-2020.1.0
build_image:Custom Mac=openvino-2020.1.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

### CODE REVIEW

**Comment by asmorkalov** [comment]
@dkurt @alalek The related PR has been merged. Could you rebase and fix conflicts to go ahead with the patch?

**Comment by asmorkalov** [comment]
@dkurt Friendly reminder.

**Comment by asmorkalov** [comment]
@dkurt  Is the patch is still relevant after https://github.com/opencv/opencv/pull/16906/ ?

**Comment by dkurt** [comment]
@asmorkalov, yes. Maybe let's mark this PR as draft for now.

**Comment by asmorkalov** [comment]
@dkurt Is there chance you finish the PR?

**Comment by dkurt** [comment]
I think that it's better to finish it after old NNBuilder approach is removed. Let's close for now

**Pull request closed without merging**
