### PR TITLE
Remove asymmetric padding in Conv layer since it is supported in CPU backend

### PR DESCRIPTION
**Pull request by fengyuentau**
In https://github.com/opencv/opencv/pull/21910, fast convolution is introduced with support for asymmetric padding in calculation. So there is no need to keep a separate padding layer for asymmetric padding in convolution layer.

## Regression test for convolution layer with asymmetric padding:

https://github.com/opencv/opencv/blob/d09cc0f30c708ca06ad1a05f5b39f6368d986fad/modules/dnn/test/test_onnx_importer.cpp#L118-L122

OpenVINO, Default CPU (CPU, OCL, Tengine), Vulkan, CUDA, WebNN are registered for this test.

## Checks on different backends
- [x] OpenCV CPU
- [x] OpenCL
- [x] OpenVINO (should be good since it builds its padding from pads_begin & pads_end, see code [here](https://github.com/opencv/opencv/blob/a1d5565e65548bfbb9cafccf3016eca7994cfd85/modules/dnn/src/layers/convolution_layer.cpp#L838-L839) and [here](https://github.com/opencv/opencv/blob/a1d5565e65548bfbb9cafccf3016eca7994cfd85/modules/dnn/src/layers/convolution_layer.cpp#L846-L847))
- [x] CUDA
- [ ] ~Vulkan~ I am getting segmentation fault regardless my changes
- [ ] WebNN (should be good since it builds its padding from pads_begin & pads_end, see code [here](https://github.com/opencv/opencv/blob/a1d5565e65548bfbb9cafccf3016eca7994cfd85/modules/dnn/src/layers/convolution_layer.cpp#L936-L939))
- [x] Tengine (failed at `Test_ONNX_layers.Convolution_variable_weight_bias/0` but should not be related to this patch)

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
I tried the branch with TEngine enabled on my Jetson TK1 (armv7 with neon, Ubuntu 14.04) and minimal dnn test suite has a failure:
```
[ SKIPSTAT ] 947 tests skipped
[ SKIPSTAT ] TAG='mem_2gb' skip 21 tests
[ SKIPSTAT ] TAG='verylong' skip 1 tests
[ SKIPSTAT ] TAG='dnn_skip_opencv_backend' skip 57 tests
[ SKIPSTAT ] TAG='dnn_skip_onnx_conformance' skip 0 tests (616 times in extra skip list)
[ SKIPSTAT ] TAG='dnn_skip_parser' skip 559 tests
[ SKIPSTAT ] TAG='skip_other' skip 309 tests
[==========] 2619 tests from 80 test cases ran. (4368 ms total)
[  PASSED  ] 2618 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Test_ONNX_layers.Convolution_variable_weight_bias/0, where GetParam() = OCV/CPU
```
I'll check, if it relates somehow to the patch and let you know.

**Comment by asmorkalov** [comment]
The same issue in 4.x with TEngine:
```
[----------] Global test environment tear-down
[ SKIPSTAT ] 947 tests skipped
[ SKIPSTAT ] TAG='mem_2gb' skip 21 tests
[ SKIPSTAT ] TAG='verylong' skip 1 tests
[ SKIPSTAT ] TAG='dnn_skip_opencv_backend' skip 57 tests
[ SKIPSTAT ] TAG='dnn_skip_onnx_conformance' skip 0 tests (616 times in extra skip list)
[ SKIPSTAT ] TAG='dnn_skip_parser' skip 559 tests
[ SKIPSTAT ] TAG='skip_other' skip 309 tests
[==========] 2619 tests from 80 test cases ran. (4250 ms total)
[  PASSED  ] 2618 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Test_ONNX_layers.Convolution_variable_weight_bias/0, where GetParam() = OCV/CPU

```

**Comment by asmorkalov** [comment]
The issue is TEngine specific and is not reproducible without it:
```
[----------] Global test environment tear-down
[ SKIPSTAT ] 947 tests skipped
[ SKIPSTAT ] TAG='mem_2gb' skip 21 tests
[ SKIPSTAT ] TAG='verylong' skip 1 tests
[ SKIPSTAT ] TAG='dnn_skip_opencv_backend' skip 57 tests
[ SKIPSTAT ] TAG='dnn_skip_onnx_conformance' skip 0 tests (616 times in extra skip list)
[ SKIPSTAT ] TAG='dnn_skip_parser' skip 559 tests
[ SKIPSTAT ] TAG='skip_other' skip 309 tests
[==========] 2619 tests from 80 test cases ran. (3999 ms total)
[  PASSED  ] 2619 tests.
```

**Comment by fengyuentau** [comment]
@asmorkalov Thank you for the test! I will take a look at the problem. But let me clarify, do you mean Tengine by TEngine?

https://github.com/opencv/opencv/blob/3651831e7e2a055a08445245bec5a0fe780712f0/CMakeLists.txt#L453-L455

**Comment by asmorkalov** [comment]
Yes, I mean WITH_TENGINE option:
```
cmake -DWITH_TENGINE=ON -DCPU_BASELINE_REQUIRE=NEON -DBUILD_opencv_gapi=OFF ../opencv
```

**Comment by fengyuentau** [comment]
@asmorkalov Convolution with asymmetric padding in Tengine is now supported. However, I did not find the root problem in  `Test_ONNX_layers.Convolution_variable_weight_bias/0`. The model in this unit test has no padding, and I can confirm the weight & bias are all correct before they are converted to Tengine tensors.

**Comment by asmorkalov** [comment]
Previous work and tests for asymmetric padding support: https://github.com/opencv/opencv/issues/20964

**Review by rogday — APPROVED** [review]
:+1:

**Comment by asmorkalov** [comment]
Tested with the last 2 releases of OpenVINO. No new regressions in comparison to 4.x.

**Pull request merged**
