### PR TITLE
Tutorial - Make required input args positional.

### PR DESCRIPTION
**Pull request by float13**
I think it would help to change all 3 of the the input file arguments to be "positional" for consistency with the other tutorials. This also simplifies the command line input to run this tutorial by reducing typing, and helpfully prints the "usage" info if any of the 3 required inputs are missing.

I'm new to OpenCV and working through the tutorials. I kept getting runtime errors with this one until I realized that the arguments weren't positional, and I was missing the "--input1", "--input2, "--input3" flags preceding the filenames. All of the previous tutorials had required filenames as positional arguments and didn't require this.

The original code would require each input to be specified like this:
```./compareHist_Demo --input1 filename1 --input2 filename2 --input3 filename3```

But with this change, the above command is simplified to:
```./compareHist_Demo  filename1 filename2 filename3```

This avoids a confusing runtime error to make things simpler for newcomers like me :)

### This pullrequest changes

samples/cpp/tutorial_code/Histograms_Matching/compareHist_Demo.cpp

### CODE REVIEW

**Comment by alalek** [comment]
Thank you for contribution!

This patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

**Comment by float13** [comment]
Hi,

I made this edit on the online Github editor, without downloading/cloning the source. I changed the branch to 3.4 but I can’t do the rebase command online.

It now says that I want to merge 944 commits - is this normal? 
float13 <https://github.com/float13> wants to merge 944 commits into opencv:3.4 <https://github.com/opencv/opencv/tree/3.4> from float13:patch-1 <https://github.com/float13/opencv/tree/patch-1>

There are also branch conflicts now.

Should I clone the source and then try to do the rebase? Or is it simpler to just open a new pull request directly to 3.4?

Thanks

**Comment by alalek** [comment]
I pushed rebased patch.

P.S. I don't have instructions for GitHub editor about rebasing process.

**Comment by float13** [comment]
Thanks! Now I know for next time.

Anything else to do?

**Pull request merged**
