### PR TITLE
ffmpeg/5.x: update FFmpeg wrapper 2024.11

### LINKED ISSUE #26465: 5.x: Update FFmpeg Windows wrapper for OpenCV 5.0
Tasks:
- [ ] new branch (ffmpeg/5.x) in opencv_3rdparty
- [ ] bump ffmpeg version (5.x - 7.x)
- [ ] bump ffmpeg wrapper dependencies
- [ ] update wrapper version and force 5.x plugin version instead of 4.x

### PR DESCRIPTION
**Pull request by opencv-alalek**
**Merge with 3rdparty**: https://github.com/opencv/opencv_3rdparty/pull/89

- FFmpeg n7.1
- OpenH264 2.5.0
- libvpx 1.15.0
- aom 3.11.0

resolves #26465

<cut/>

<details><summary>FFmpeg config:</summary>

```
+ PKG_CONFIG_PATH=/build/openh264/install_x86_64/lib/pkgconfig:/build/libvpx_x64/install/lib/pkgconfig:/build/aom_x64/install/lib/pkgconfig
+ ./configure --enable-cross-compile --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --enable-static --enable-w32threads --enable-libopenh264 --enable-libvpx --disable-filters --disable-bsfs --disable-programs --disable-debug --disable-cuda --disable-cuvid --disable-nvenc --enable-libaom --prefix=/build/ffmpeg_x86_64/install
install prefix            /build/ffmpeg_x86_64/install
source path               .
C compiler                x86_64-w64-mingw32-gcc
C library                 mingw64
host C compiler           gcc
host C library            glibc
ARCH                      x86 (generic)
big-endian                no
runtime cpu detection     yes
standalone assembly       yes
x86 assembler             nasm
MMX enabled               yes
MMXEXT enabled            yes
3DNow! enabled            yes
3DNow! extended enabled   yes
SSE enabled               yes
SSSE3 enabled             yes
AESNI enabled             yes
AVX enabled               yes
AVX2 enabled              yes
AVX-512 enabled           yes
AVX-512ICL enabled        yes
XOP enabled               yes
FMA3 enabled              yes
FMA4 enabled              yes
i686 features enabled     yes
CMOV is fast              yes
EBX available             yes
EBP available             yes
debug symbols             no
strip symbols             yes
optimize for size         no
optimizations             yes
static                    yes
shared                    no
postprocessing support    no
network support           yes
threading support         w32threads
safe bitstream reader     yes
texi2html enabled         no
perl enabled              yes
pod2man enabled           yes
makeinfo enabled          yes
makeinfo supports HTML    yes
xmllint enabled           no

External libraries:
libaom                  libopenh264             libvpx                  mediafoundation         schannel

External libraries providing hardware acceleration:
d3d11va                 dxva2

Libraries:
avcodec                 avfilter                avutil                  swscale
avdevice                avformat                swresample

Programs:

Enabled decoders:
aac                     atrac3                  ffwavesynth             mp1                     pfm                     tiff
aac_fixed               atrac3al                fic                     mp1float                pgm                     tmv
aac_latm                atrac3p                 fits                    mp2                     pgmyuv                  truehd
aasc                    atrac3pal               flac                    mp2float                pgssub                  truemotion1
ac3                     atrac9                  flic                    mp3                     pgx                     truemotion2
ac3_fixed               aura                    flv                     mp3adu                  phm                     truemotion2rt
acelp_kelvin            aura2                   fmvc                    mp3adufloat             photocd                 truespeech
adpcm_4xm               av1                     fourxm                  mp3float                pictor                  tscc2
adpcm_adx               avrn                    fraps                   mp3on4                  pixlet                  tta
adpcm_afc               avrp                    frwu                    mp3on4float             pjs                     twinvq
adpcm_agm               avs                     ftr                     mpc7                    ppm                     txd
adpcm_aica              avui                    g723_1                  mpc8                    prores                  ulti
adpcm_argo              bethsoftvid             g729                    mpeg1video              prosumer                utvideo
adpcm_ct                bfi                     gdv                     mpeg2video              psd                     v210
adpcm_dtk               bink                    gem                     mpeg4                   ptx                     v210x
adpcm_ea                binkaudio_dct           gif                     mpegvideo               qcelp                   v308
adpcm_ea_maxis_xa       binkaudio_rdft          gremlin_dpcm            mpl2                    qdm2                    v408
adpcm_ea_r1             bintext                 gsm                     msa1                    qdmc                    v410
adpcm_ea_r2             bitpacked               gsm_ms                  msmpeg4v1               qdraw                   vb
adpcm_ea_r3             bmp                     h261                    msmpeg4v2               qoa                     vble
adpcm_ea_xas            bmv_audio               h263                    msmpeg4v3               qoi                     vbn
adpcm_g722              bmv_video               h263i                   msnsiren                qpeg                    vc1
adpcm_g726              bonk                    h263p                   msp2                    qtrle                   vc1image
adpcm_g726le            brender_pix             h264                    msrle                   r10k                    vcr1
adpcm_ima_acorn         c93                     hap                     mss1                    r210                    vmdaudio
adpcm_ima_alp           cavs                    hca                     mss2                    ra_144                  vmdvideo
adpcm_ima_amv           cbd2_dpcm               hcom                    msvideo1                ra_288                  vmix
adpcm_ima_apc           ccaption                hdr                     mszh                    ralf                    vmnc
adpcm_ima_apm           cdgraphics              hevc                    mts2                    rawvideo                vnull
adpcm_ima_cunning       cdtoons                 hnm4_video              mv30                    realtext                vorbis
adpcm_ima_dat4          cdxl                    hq_hqa                  mvc1                    rka                     vp3
adpcm_ima_dk3           cfhd                    hqx                     mvc2                    rl2                     vp4
adpcm_ima_dk4           cinepak                 huffyuv                 mvdv                    roq                     vp5
adpcm_ima_ea_eacs       clearvideo              hymt                    mxpeg                   roq_dpcm                vp6
adpcm_ima_ea_sead       cljr                    iac                     nellymoser              rpza                    vp6a
adpcm_ima_iss           cllc                    idcin                   notchlc                 rtv1                    vp6f
adpcm_ima_moflex        comfortnoise            idf                     nuv                     rv10                    vp7
adpcm_ima_mtf           cook                    iff_ilbm                on2avc                  rv20                    vp8
adpcm_ima_oki           cpia                    ilbc                    opus                    rv30                    vp9
adpcm_ima_qt            cri                     imc                     osq                     rv40                    vplayer
adpcm_ima_rad           cscd                    imm4                    paf_audio               s302m                   vqa
adpcm_ima_smjpeg        cyuv                    imm5                    paf_video               sami                    vqc
adpcm_ima_ssi           dca                     indeo2                  pam                     sanm                    vvc
adpcm_ima_wav           dds                     indeo3                  pbm                     sbc                     wady_dpcm
adpcm_ima_ws            derf_dpcm               indeo4                  pcm_alaw                scpr                    wavarc
adpcm_ms                dfa                     indeo5                  pcm_bluray              sdx2_dpcm               wavpack
adpcm_mtaf              dfpwm                   interplay_acm           pcm_dvd                 sga                     wbmp
adpcm_psx               dirac                   interplay_dpcm          pcm_f16le               sgi                     webp
adpcm_sbpro_2           dnxhd                   interplay_video         pcm_f24le               sgirle                  webvtt
adpcm_sbpro_3           dolby_e                 ipu                     pcm_f32be               sheervideo              wmalossless
adpcm_sbpro_4           dpx                     jacosub                 pcm_f32le               shorten                 wmapro
adpcm_swf               dsd_lsbf                jpeg2000                pcm_f64be               simbiosis_imx           wmav1
adpcm_thp               dsd_lsbf_planar         jpegls                  pcm_f64le               sipr                    wmav2
adpcm_thp_le            dsd_msbf                jv                      pcm_lxf                 siren                   wmavoice
adpcm_vima              dsd_msbf_planar         kgv1                    pcm_mulaw               smackaud                wmv1
adpcm_xa                dsicinaudio             kmvc                    pcm_s16be               smacker                 wmv2
adpcm_xmd               dsicinvideo             lagarith                pcm_s16be_planar        smc                     wmv3
adpcm_yamaha            dss_sp                  lead                    pcm_s16le               smvjpeg                 wmv3image
adpcm_zork              dst                     libaom_av1              pcm_s16le_planar        snow                    wnv1
agm                     dvaudio                 libopenh264             pcm_s24be               sol_dpcm                wrapped_avframe
aic                     dvbsub                  libvpx_vp8              pcm_s24daud             sonic                   ws_snd1
alac                    dvdsub                  libvpx_vp9              pcm_s24le               sp5x                    xan_dpcm
alias_pix               dvvideo                 loco                    pcm_s24le_planar        speedhq                 xan_wc3
als                     dxtory                  m101                    pcm_s32be               speex                   xan_wc4
amrnb                   dxv                     mace3                   pcm_s32le               srt                     xbin
amrwb                   eac3                    mace6                   pcm_s32le_planar        ssa                     xbm
amv                     eacmv                   magicyuv                pcm_s64be               stl                     xface
anm                     eamad                   mdec                    pcm_s64le               subrip                  xl
ansi                    eatgq                   media100                pcm_s8                  subviewer               xma1
anull                   eatgv                   metasound               pcm_s8_planar           subviewer1              xma2
apac                    eatqi                   microdvd                pcm_sga                 sunrast                 xpm
ape                     eightbps                mimic                   pcm_u16be               svq1                    xsub
aptx                    eightsvx_exp            misc4                   pcm_u16le               svq3                    xwd
aptx_hd                 eightsvx_fib            mjpeg                   pcm_u24be               tak                     y41p
arbc                    escape124               mjpegb                  pcm_u24le               targa                   ylc
argo                    escape130               mlp                     pcm_u32be               targa_y216              yop
ass                     evrc                    mmvideo                 pcm_u32le               text                    yuv4
asv1                    fastaudio               mobiclip                pcm_u8                  theora                  zero12v
asv2                    ffv1                    motionpixels            pcm_vidc                thp
atrac1                  ffvhuff                 movtext                 pcx                     tiertexseqvideo

Enabled encoders:
a64multi                asv2                    hevc_mf                 pcm_f32be               pgm                     svq1
a64multi5               avrp                    huffyuv                 pcm_f32le               pgmyuv                  targa
aac                     avui                    jpeg2000                pcm_f64be               phm                     text
aac_mf                  bitpacked               jpegls                  pcm_f64le               ppm                     tiff
ac3                     bmp                     libaom_av1              pcm_mulaw               prores                  truehd
ac3_fixed               cfhd                    libopenh264             pcm_s16be               prores_aw               tta
ac3_mf                  cinepak                 libvpx_vp8              pcm_s16be_planar        prores_ks               ttml
adpcm_adx               cljr                    libvpx_vp9              pcm_s16le               qoi                     utvideo
adpcm_argo              comfortnoise            ljpeg                   pcm_s16le_planar        qtrle                   v210
adpcm_g722              dca                     magicyuv                pcm_s24be               r10k                    v308
adpcm_g726              dfpwm                   mjpeg                   pcm_s24daud             r210                    v408
adpcm_g726le            dnxhd                   mlp                     pcm_s24le               ra_144                  v410
adpcm_ima_alp           dpx                     movtext                 pcm_s24le_planar        rawvideo                vbn
adpcm_ima_amv           dvbsub                  mp2                     pcm_s32be               roq                     vc2
adpcm_ima_apm           dvdsub                  mp2fixed                pcm_s32le               roq_dpcm                vnull
adpcm_ima_qt            dvvideo                 mp3_mf                  pcm_s32le_planar        rpza                    vorbis
adpcm_ima_ssi           dxv                     mpeg1video              pcm_s64be               rv10                    wavpack
adpcm_ima_wav           eac3                    mpeg2video              pcm_s64le               rv20                    wbmp
adpcm_ima_ws            ffv1                    mpeg4                   pcm_s8                  s302m                   webvtt
adpcm_ms                ffvhuff                 msmpeg4v2               pcm_s8_planar           sbc                     wmav1
adpcm_swf               fits                    msmpeg4v3               pcm_u16be               sgi                     wmav2
adpcm_yamaha            flac                    msrle                   pcm_u16le               smc                     wmv1
alac                    flv                     msvideo1                pcm_u24be               snow                    wmv2
alias_pix               g723_1                  nellymoser              pcm_u24le               sonic                   wrapped_avframe
amv                     gif                     opus                    pcm_u32be               sonic_ls                xbm
anull                   h261                    pam                     pcm_u32le               speedhq                 xface
aptx                    h263                    pbm                     pcm_u8                  srt                     xsub
aptx_hd                 h263p                   pcm_alaw                pcm_vidc                ssa                     xwd
ass                     h264_mf                 pcm_bluray              pcx                     subrip                  y41p
asv1                    hdr                     pcm_dvd                 pfm                     sunrast                 yuv4

Enabled hwaccels:
av1_d3d11va             h264_d3d11va2           hevc_dxva2              vc1_d3d11va             vp9_d3d11va2            wmv3_dxva2
av1_d3d11va2            h264_dxva2              mpeg2_d3d11va           vc1_d3d11va2            vp9_dxva2
av1_dxva2               hevc_d3d11va            mpeg2_d3d11va2          vc1_dxva2               wmv3_d3d11va
h264_d3d11va            hevc_d3d11va2           mpeg2_dxva2             vp9_d3d11va             wmv3_d3d11va2

Enabled parsers:
aac                     cook                    dvdsub                  h264                    mpegaudio               vc1
aac_latm                cri                     evc                     hdr                     mpegvideo               vorbis
ac3                     dca                     flac                    hevc                    opus                    vp3
adx                     dirac                   ftr                     ipu                     png                     vp8
amr                     dnxhd                   g723_1                  jpeg2000                pnm                     vp9
av1                     dolby_e                 g729                    jpegxl                  qoi                     vvc
avs2                    dpx                     gif                     misc4                   rv34                    webp
avs3                    dvaudio                 gsm                     mjpeg                   sbc                     xbm
bmp                     dvbsub                  h261                    mlp                     sipr                    xma
cavsvideo               dvd_nav                 h263                    mpeg4video              tak                     xwd

Enabled demuxers:
aa                      cdxl                    idf                     live_flv                pcm_s16be               sol
aac                     cine                    iff                     lmlm4                   pcm_s16le               sox
aax                     codec2                  ifv                     loas                    pcm_s24be               spdif
ac3                     codec2raw               ilbc                    lrc                     pcm_s24le               srt
ac4                     concat                  image2                  luodat                  pcm_s32be               stl
ace                     data                    image2_alias_pix        lvf                     pcm_s32le               str
acm                     daud                    image2_brender_pix      lxf                     pcm_s8                  subviewer
act                     dcstr                   image2pipe              m4v                     pcm_u16be               subviewer1
adf                     derf                    image_bmp_pipe          matroska                pcm_u16le               sup
adp                     dfa                     image_cri_pipe          mca                     pcm_u24be               svag
ads                     dfpwm                   image_dds_pipe          mcc                     pcm_u24le               svs
adx                     dhav                    image_dpx_pipe          mgsts                   pcm_u32be               swf
aea                     dirac                   image_exr_pipe          microdvd                pcm_u32le               tak
afc                     dnxhd                   image_gem_pipe          mjpeg                   pcm_u8                  tedcaptions
aiff                    dsf                     image_gif_pipe          mjpeg_2000              pcm_vidc                thp
aix                     dsicin                  image_hdr_pipe          mlp                     pdv                     threedostr
alp                     dss                     image_j2k_pipe          mlv                     pjs                     tiertexseq
amr                     dts                     image_jpeg_pipe         mm                      pmp                     tmv
amrnb                   dtshd                   image_jpegls_pipe       mmf                     pp_bnk                  truehd
amrwb                   dv                      image_jpegxl_pipe       mods                    pva                     tta
anm                     dvbsub                  image_pam_pipe          moflex                  pvf                     tty
apac                    dvbtxt                  image_pbm_pipe          mov                     qcp                     txd
apc                     dxa                     image_pcx_pipe          mp3                     qoa                     ty
ape                     ea                      image_pfm_pipe          mpc                     r3d                     usm
apm                     ea_cdata                image_pgm_pipe          mpc8                    rawvideo                v210
apng                    eac3                    image_pgmyuv_pipe       mpegps                  rcwt                    v210x
aptx                    epaf                    image_pgx_pipe          mpegts                  realtext                vag
aptx_hd                 evc                     image_phm_pipe          mpegtsraw               redspark                vc1
aqtitle                 ffmetadata              image_photocd_pipe      mpegvideo               rka                     vc1t
argo_asf                filmstrip               image_pictor_pipe       mpjpeg                  rl2                     vividas
argo_brp                fits                    image_png_pipe          mpl2                    rm                      vivo
argo_cvg                flac                    image_ppm_pipe          mpsub                   roq                     vmd
asf                     flic                    image_psd_pipe          msf                     rpl                     vobsub
asf_o                   flv                     image_qdraw_pipe        msnwc_tcp               rsd                     voc
ass                     fourxm                  image_qoi_pipe          msp                     rso                     vpk
ast                     frm                     image_sgi_pipe          mtaf                    rtp                     vplayer
au                      fsb                     image_sunrast_pipe      mtv                     rtsp                    vqf
av1                     fwse                    image_svg_pipe          musx                    s337m                   vvc
avi                     g722                    image_tiff_pipe         mv                      sami                    w64
avr                     g723_1                  image_vbn_pipe          mvi                     sap                     wady
avs                     g726                    image_webp_pipe         mxf                     sbc                     wav
avs2                    g726le                  image_xbm_pipe          mxg                     sbg                     wavarc
avs3                    g729                    image_xpm_pipe          nc                      scc                     wc3
bethsoftvid             gdv                     image_xwd_pipe          nistsphere              scd                     webm_dash_manifest
bfi                     genh                    ingenient               nsp                     sdns                    webvtt
bfstm                   gif                     ipmovie                 nsv                     sdp                     wsaud
bink                    gsm                     ipu                     nut                     sdr2                    wsd
binka                   gxf                     ircam                   nuv                     sds                     wsvqa
bintext                 h261                    iss                     obu                     sdx                     wtv
bit                     h263                    iv8                     ogg                     segafilm                wv
bitpacked               h264                    ivf                     oma                     ser                     wve
bmv                     hca                     ivr                     osq                     sga                     xa
boa                     hcom                    jacosub                 paf                     shorten                 xbin
bonk                    hevc                    jpegxl_anim             pcm_alaw                siff                    xmd
brstm                   hls                     jv                      pcm_f32be               simbiosis_imx           xmv
c93                     hnm                     kux                     pcm_f32le               sln                     xvag
caf                     iamf                    kvag                    pcm_f64be               smacker                 xwma
cavsvideo               ico                     laf                     pcm_f64le               smjpeg                  yop
cdg                     idcin                   lc3                     pcm_mulaw               smush                   yuv4mpegpipe

Enabled muxers:
a64                     codec2raw               h263                    mp2                     pcm_s16le               sox
ac3                     crc                     h264                    mp3                     pcm_s24be               spdif
ac4                     dash                    hash                    mp4                     pcm_s24le               spx
adts                    data                    hds                     mpeg1system             pcm_s32be               srt
adx                     daud                    hevc                    mpeg1vcd                pcm_s32le               stream_segment
aea                     dfpwm                   hls                     mpeg1video              pcm_s8                  streamhash
aiff                    dirac                   iamf                    mpeg2dvd                pcm_u16be               sup
alp                     dnxhd                   ico                     mpeg2svcd               pcm_u16le               swf
amr                     dts                     ilbc                    mpeg2video              pcm_u24be               tee
amv                     dv                      image2                  mpeg2vob                pcm_u24le               tg2
apm                     eac3                    image2pipe              mpegts                  pcm_u32be               tgp
apng                    evc                     ipod                    mpjpeg                  pcm_u32le               truehd
aptx                    f4v                     ircam                   mxf                     pcm_u8                  tta
aptx_hd                 ffmetadata              ismv                    mxf_d10                 pcm_vidc                ttml
argo_asf                fifo                    ivf                     mxf_opatom              psp                     uncodedframecrc
argo_cvg                filmstrip               jacosub                 null                    rawvideo                vc1
asf                     fits                    kvag                    nut                     rcwt                    vc1t
asf_stream              flac                    latm                    obu                     rm                      voc
ass                     flv                     lc3                     oga                     roq                     vvc
ast                     framecrc                lrc                     ogg                     rso                     w64
au                      framehash               m4v                     ogv                     rtp                     wav
avi                     framemd5                matroska                oma                     rtp_mpegts              webm
avif                    g722                    matroska_audio          opus                    rtsp                    webm_chunk
avm2                    g723_1                  md5                     pcm_alaw                sap                     webm_dash_manifest
avs2                    g726                    microdvd                pcm_f32be               sbc                     webp
avs3                    g726le                  mjpeg                   pcm_f32le               scc                     webvtt
bit                     gif                     mkvtimestamp_v2         pcm_f64be               segafilm                wsaud
caf                     gsm                     mlp                     pcm_f64le               segment                 wtv
cavsvideo               gxf                     mmf                     pcm_mulaw               smjpeg                  wv
codec2                  h261                    mov                     pcm_s16be               smoothstreaming         yuv4mpegpipe

Enabled protocols:
async                   fd                      hls                     ipns_gateway            rtmp                    subfile
cache                   ffrtmphttp              http                    md5                     rtmps                   tcp
concat                  file                    httpproxy               mmsh                    rtmpt                   tee
concatf                 ftp                     https                   mmst                    rtmpts                  tls
crypto                  gopher                  icecast                 pipe                    rtp                     udp
data                    gophers                 ipfs_gateway            prompeg                 srtp                    udplite

Enabled filters:

Enabled bsfs:
aac_adtstoasc           evc_frame_merge         hevc_mp4toannexb        pgs_frame_merge         vvc_mp4toannexb
av1_frame_merge         extract_extradata       media100_to_mjpegb      vp9_superframe
av1_metadata            h264_mp4toannexb        pcm_rechunk             vp9_superframe_split

Enabled indevs:
dshow                   gdigrab                 lavfi                   vfwcap

Enabled outdevs:

License: LGPL version 2.1 or later
```

</details>

Before (uses 4.10):

```
[ INFO:0@0.154] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\build\precommit_windows64\build\bin\Release\opencv_videoio_ffmpeg500_64.dll => OK
[ INFO:0@0.154] global backend_plugin.cpp:50 cv::impl::PluginBackend::initCaptureAPI Found entry: 'opencv_videoio_capture_plugin_init_v1'
[ INFO:0@0.154] global backend_plugin.cpp:173 cv::impl::PluginBackend::checkCompatibility Video I/O: initialized 'FFmpeg OpenCV Video I/O Capture plugin': built with OpenCV 4.10 (ABI/API = 1/1), current OpenCV version is '5.0.0-pre' (ABI/API = 1/1)
[ INFO:0@0.154] global backend_plugin.cpp:69 cv::impl::PluginBackend::initCaptureAPI Video I/O: plugin is ready to use 'FFmpeg OpenCV Video I/O Capture plugin'
[ INFO:0@0.154] global backend_plugin.cpp:84 cv::impl::PluginBackend::initWriterAPI Found entry: 'opencv_videoio_writer_plugin_init_v1'
[ INFO:0@0.154] global backend_plugin.cpp:173 cv::impl::PluginBackend::checkCompatibility Video I/O: initialized 'FFmpeg OpenCV Video I/O Writer plugin': built with OpenCV 4.10 (ABI/API = 1/1), current OpenCV version is '5.0.0-pre' (ABI/API = 1/1)
[ INFO:0@0.155] global backend_plugin.cpp:103 cv::impl::PluginBackend::initWriterAPI Video I/O: plugin is ready to use 'FFmpeg OpenCV Video I/O Writer plugin'
```

Patch:

```
[ INFO:0@0.212] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\build\precommit_windows64\build\bin\Release\opencv_videoio_ffmpeg500_64.dll => OK
[ INFO:0@0.212] global backend_plugin.cpp:50 cv::impl::PluginBackend::initCaptureAPI Found entry: 'opencv_videoio_capture_plugin_init_v1'
[ INFO:0@0.212] global backend_plugin.cpp:169 cv::impl::PluginBackend::checkCompatibility Video I/O: initialized 'FFmpeg OpenCV Video I/O Capture plugin': built with OpenCV 5.0 (ABI/API = 1/1), current OpenCV version is '5.0.0-pre' (ABI/API = 1/1)
[ INFO:0@0.212] global backend_plugin.cpp:69 cv::impl::PluginBackend::initCaptureAPI Video I/O: plugin is ready to use 'FFmpeg OpenCV Video I/O Capture plugin'
[ INFO:0@0.212] global backend_plugin.cpp:84 cv::impl::PluginBackend::initWriterAPI Found entry: 'opencv_videoio_writer_plugin_init_v1'
[ INFO:0@0.212] global backend_plugin.cpp:169 cv::impl::PluginBackend::checkCompatibility Video I/O: initialized 'FFmpeg OpenCV Video I/O Writer plugin': built with OpenCV 5.0 (ABI/API = 1/1), current OpenCV version is '5.0.0-pre' (ABI/API = 1/1)
[ INFO:0@0.212] global backend_plugin.cpp:103 cv::impl::PluginBackend::initWriterAPI Video I/O: plugin is ready to use 'FFmpeg OpenCV Video I/O Writer plugin'
```

```
allow_multiple_commits=1
```

### CODE REVIEW

**Comment by opencv-alalek** [comment]
Depends on #21386

**Comment by asmorkalov** [comment]
I propose to enable tests that waits for FFmpeg update:
```
test_ffmpeg.cpp:299:#if defined(WIN32)  // remove when FFmpeg wrapper includes PR25874
test_ffmpeg.cpp:300:#define WIN32_WAIT_FOR_FFMPEG_WRAPPER_UPDATE
test_ffmpeg.cpp:334:#if !defined(WIN32_WAIT_FOR_FFMPEG_WRAPPER_UPDATE)
test_ffmpeg.cpp:349:#if !defined(WIN32_WAIT_FOR_FFMPEG_WRAPPER_UPDATE)
test_ffmpeg.cpp:384:#if !defined(WIN32_WAIT_FOR_FFMPEG_WRAPPER_UPDATE)
```

**Review by asmorkalov — APPROVED** [review]

**Comment by asmorkalov** [comment]
Looks like `videoio_encapsulate.write` tests require FFmpeg update for some containers. Let's disable them for now back and merge as is. The test pass on Linux, so we can return to it later.

**Comment by opencv-alalek** [comment]
There is just nothing to fail in the setter itself:

https://github.com/opencv/opencv/blob/d0820dac382943cb35b7ca4a0d51458164010803/modules/videoio/src/cap_ffmpeg_impl.hpp#L2656-L2661


Problem is in the plugin support part which is not implemented at all:

https://github.com/opencv/opencv/blob/d0820dac382943cb35b7ca4a0d51458164010803/modules/videoio/src/cap_ffmpeg.cpp#L517-L521

**Pull request merged**
