### PR TITLE
fix issue 9359

### LINKED ISSUE #9359: Documentation bug
Documentation bug in the 2.4.x docs -> OpenCV Tutorials -> Highgui -> Video Input with OpenCV and similarity measurement -> Image similarity - PSNR and SSIM

Mentioned : Here the MAX_I^2 is the maximum valid value for a pixel

Wikpedia says that MAX_I is the max value, and MAX_I^2 is its square. 
Link : https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio

### PR DESCRIPTION
**Pull request by StevenPuttemans**
resolves #9359: add fix from the issue report

### CODE REVIEW

**Comment by sovrasov** [comment]
:+1:

**Comment by StevenPuttemans** [comment]
Do we still provide backports to 2.4? Isn't it time to abandon it and leave it frozen as is? :dagger:

**Comment by mshabunin** [comment]
@StevenPuttemans , OpenCV 2.4 is still used by some people, so we try not to break it and to fix some issues if possible.

**Comment by StevenPuttemans** [comment]
Fine for me, just in my opinion a huge overkill

**Pull request merged**
