### PR TITLE
[GSOC] Speeding-up AKAZE, part #3

### PR DESCRIPTION
**Pull request by hrnr**
cc: @bmagyar 

This is currently based on #8951. I will rebase on master, once it gets in.

Currently this contains reworked version of finding scale space extremas. Speed up for images with lots of keypoints is ~3.6x.

```

Geometric mean

                                                   Name of Test                                                        perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf      perf      perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf   
                                                                                                                    8200996b1  b12facf48  aa5a72b46  8cc0b286c  1d3f7fe9e  c13351891  76151e566  ea089a8ab  f9c2951fa  ba071d1ad  09c7288de  d71718dea  61a35d7a6  1d42c1fa8  70b66d1b6 1a4c8989d b12facf48  aa5a72b46  8cc0b286c  1d3f7fe9e  c13351891  76151e566  ea089a8ab  f9c2951fa  ba071d1ad  09c7288de  d71718dea  61a35d7a6  1d42c1fa8  70b66d1b6  1a4c8989d 
                                                                                                                                                                                                                                                                                                      vs         vs         vs         vs         vs         vs         vs         vs         vs         vs         vs         vs         vs         vs         vs    
                                                                                                                                                                                                                                                                                                     perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf       perf   
                                                                                                                                                                                                                                                                                                  8200996b1  8200996b1  8200996b1  8200996b1  8200996b1  8200996b1  8200996b1  8200996b1  8200996b1  8200996b1  8200996b1  8200996b1  8200996b1  8200996b1  8200996b1 
                                                                                                                                                                                                                                                                                                  (x-factor) (x-factor) (x-factor) (x-factor) (x-factor) (x-factor) (x-factor) (x-factor) (x-factor) (x-factor) (x-factor) (x-factor) (x-factor) (x-factor) (x-factor)
detectAndExtract::feature2d::(AKAZE_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png") 73.555 ms  65.326 ms  45.166 ms  45.018 ms  42.333 ms  39.708 ms  39.556 ms  38.896 ms  43.073 ms  39.038 ms  37.845 ms  37.977 ms  38.303 ms  31.364 ms  33.183 ms 33.253 ms    1.13       1.63       1.63       1.74       1.85       1.86       1.89       1.71       1.88       1.94       1.94       1.92       2.35       2.22       2.21   
detectAndExtract::feature2d::(AKAZE_DEFAULT, "stitching/a3.png")                                                    58.468 ms  52.088 ms  35.045 ms  34.284 ms  32.775 ms  30.440 ms  29.703 ms  30.023 ms  31.295 ms  30.154 ms  28.886 ms  29.472 ms  28.711 ms  23.899 ms  26.021 ms 26.826 ms    1.12       1.67       1.71       1.78       1.92       1.97       1.95       1.87       1.94       2.02       1.98       2.04       2.45       2.25       2.18   
detectAndExtract::feature2d::(AKAZE_DEFAULT, "stitching/s2.jpg")                                                    276.495 ms 250.674 ms 173.192 ms 165.687 ms 162.380 ms 148.727 ms 151.201 ms 156.154 ms 169.405 ms 159.459 ms 149.227 ms 157.420 ms 151.767 ms 119.365 ms 76.862 ms 77.646 ms    1.10       1.60       1.67       1.70       1.86       1.83       1.77       1.63       1.73       1.85       1.76       1.82       2.32       3.60       3.56   
```

### CODE REVIEW

**Comment by hrnr** [comment]
Notice that 1a4c8989d2b953b1edaaa4dbc446a2ae81d0b8ed actually slows things down. I can't relly explain that.

**Comment by vpisarev** [comment]
@hrnr, thank you, cool results! Are you going to do any more commits or it can be reviewed and integrated?

**Comment by hrnr** [comment]
Yes, I'm planning to optimize further at least non-linear diffusion and Scharr kernels with nonstandard sigmas.

#8951 is ready for merge, it improves CPU perf by ~2.0x and implements basic OCL support.

**Comment by vpisarev** [comment]
ok, thanks! as we are preparing 3.3 now, perhaps, it makes sense to merge something now

**Comment by vpisarev** [comment]
:+1:

**Comment by hrnr** [comment]
Ok, this can go in too, but it should be rebased on #8951. When #8951 gets in I will rebase it, and it is good to go.

**Comment by alalek** [comment]
@hrnr #8951 is merged. Please rebase this patch.

**Comment by hrnr** [comment]
rebased and remowed the fixup commit.

**Comment by hrnr** [comment]
build failed on win32, which seems to have a slightly lower accuracy. I have lowered the treshold a bit. 

BTW Do you have idea why buildbot scheduled a win32 build? These builders has not been scheduled ever before for this PR.

**Comment by alalek** [comment]
Some builders are optional on precommit checks.

We observed that:
- there is no testdata for kaze/akaze tests, so these tests don't check results, just write them.
- [valgrind](http://pullrequest.opencv.org/buildbot/builders/master_valgrind-lin64-debug/builds/10040) builder detects unitialized values in akaze algorithm results

**Comment by hrnr** [comment]
Testdata are an omission, but now I'm not sure if it is wise to have tests like these at all. For descriptors test the exact number of keypoints must be the same, which might be problematic as everything in AKAZE is done in floats. Detector test seems to be quite fine though.

What is the approach to these magic values controlling tests? Shouldn't we drop them (at least for AKAZE) and rely only on invarience tests, which don't control any magic values?

I'll check the problem with valgrind.

**Comment by alalek** [comment]
Agree, current tests look strange and currently they are broken. I will take a look on them.

**Comment by alalek** [comment]
@hrnr Valgrind issue: there are untouched last two bits of descriptor: 61 bytes is 488 bits, but MLDB [changes] 486 bits only.

**Comment by alalek** [comment]
Lets put it in and fix remaining issues.
:+1:

**Pull request merged**
