### PR TITLE
Gets rid of unnecessary NSData object in MatToUIImage function

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by terfendail** [comment]
As far as I could understand the original code created UIImage as a copy of provided Mat data so after the call it's safe to change the Mat without affecting created UIImage. For me it looks like updated code creates UIImage that depends on the original memory so the function behavior is changed.

**Comment by valeriyvan** [comment]
Current implementation creates NSData object with +[NSData dataWithBytes:length:] which makes a copy of buffer. Documentation:
+ dataWithBytes:length:
Creates and returns a data object containing a given number of bytes copied from a given buffer.

Then CGDataProviderCreateWithCFData creates CGDataProvider object which is used in CGImageCreate to create CGImage object.

Proposed change eliminates unnecessary intermediate NSData object and data copying.

Don't worry. CGImageCreate creates new CGImage object, a bitmap image from data supplied by a data provider.

**Comment by terfendail** [comment]
As stated in `CGImageCreate` [description](https://developer.apple.com/reference/coregraphics/1455149-cgimagecreate) it retain passed `CGDataProvider` so it still could reference the original memory(I've found no direct mention that it copy or convert provided data to own memory). I've also unsure that data will be copied during [UIImage imageWithCGImage:imageRef].

**Comment by valeriyvan** [comment]
It seems you're right. I've made test project to check proposed fix https://github.com/valeriyvan/OpenCV_TestFix_MatToUIImage. It's interesting to write unit test for this bug. Now I am closing this pull request.

**Pull request closed without merging**
