### PR TITLE
Add JSON support for FileStorage

### PR DESCRIPTION
**Pull request by wiryls**
[GSoC 2016] FileStorage.

Add JSON support and also some tests and docs.

### This pullrequest changes

1. add a JSON emitter and a parser.
1. add tests and some basic docs.

### CODE REVIEW

**Comment by PhilLab** [comment]
Awesome! Linking #6871

**Comment by wiryls** [comment]
@PhilLab Thanks!

**Comment by vpisarev** [comment]
@wiryls, I like it! :+1:

**Comment by wiryls** [comment]
@vpisarev Thanks for your affirmation!

And here are current known differences or unsupported features:
 - Value `null` is not supported.
 - Value `true` and `false` will be treated as integer 1 and 0.
 - Character `\uXXXX` is not supported.
 - The float number may not meet the requirements of standard JSON. (e.g. `0.` is not an invalid number in JSON).
 - Support `/* */` and `//` as comments.

**Comment by vpisarev** [comment]
@wiryls, all the differences you mentioned make perfect sense in our case!

**Comment by mattmyne** [comment]
I am planning on using the JSON output to share data with other JSON-compatible applications; the non-standard float output is an issue. Would a change to the behaviour (add a trailing zero if no fractional part) be likely, or perhaps an additional FileStorage flag if both variants are needed?

**Comment by wiryls** [comment]
@mattmyne , I'm sorry I didn't take account of these that.

I just used the default OpenCV functions to output float and double. See:

 - `static char* icvDoubleToString( char* buf, double value )` and
 - `static char* icvFloatToString( char* buf, float value )` in `persistence.cpp`.

Those functions look a little bit complex and I didn't know why the author designed them like this. Finally, I didn't modify them.

Recently I am preparing for an exam, and will be free a month later. If you're not in a hurry, maybe I could have a try at that time.

**Comment by mattmyne** [comment]
@wiryls it's only minor and you'd already highlighted the potential issue in your original comment. Many thanks for doing the much harder work of getting JSON support in the first place!
I've added a PR that hopefully fixes this.

**Pull request merged**
