### PR TITLE
G-API: unique_ptr for Priv in fluid

### PR DESCRIPTION
**Pull request by rgarnov**
* Changed shared_ptr to unique_ptr for pimpl implementation in fluid::Buffer and fluid::View

```
build_gapi_standalone:Linux x64=ade-0.1.1f
build_gapi_standalone:Win64=ade-0.1.1f
Xbuild_gapi_standalone:Mac=ade-0.1.1f
build_gapi_standalone:Linux x64 Debug=ade-0.1.1f

build_image:Custom=centos:7
buildworker:Custom=linux-1

allow_multiple_commits=1
```

### CODE REVIEW

**Comment by dmatveev** [comment]
@rgarnov what's the reason to do that?

**Comment by dmatveev** [comment]
@rgarnov please update this PR

**Comment by asmorkalov** [comment]
@dmatveev @rgarnov Do you have any progress on the patch?

**Comment by rgarnov** [comment]
Updated, @anton-potapov please take a look

**Comment by dmatveev** [comment]
> @rgarnov what's the reason to do that?

Please clarify

**Comment by rgarnov** [comment]
> > @rgarnov what's the reason to do that?
> 
> Please clarify

Generally it's much better to utilize unique_ptr for Pimpl, one object - one priv, there is nothing to share via shared_ptr. And there were some copies in the backend so different copies of the View with possibly different states were sharing the same Priv. It worked, but can lead to issues in future. My change just removes some not obvious dependencies between Views, Buffers and Agents in the backend

**Comment by asmorkalov** [comment]
@dmatveev @rgarnov do you have progress on the PR?

**Comment by dmatveev** [comment]
@asmorkalov I am trying to progress with my understanding of this problem

@rgarnov can you please put a detailed problem description in the MR text? I still hardly understand what problem it actually solves (but am welcome to merge this is as soon as I get this)

**Comment by asmorkalov** [comment]
@rgarnov @dmatveev Friendly reminder.

**Comment by asmorkalov** [comment]
@dmatveev @anton-potapov Friendly reminder again :)

**Comment by asmorkalov** [comment]
@dmatveev Could we merge the PR?

**Pull request merged**
