### PR TITLE
dnn(test): update tests for OpenVINO 2021.1

### PR DESCRIPTION
**Pull request by alalek**
<cut/>

```
force_builders=Custom,Custom Win,Custom Mac
Xbuild_image:Custom=ubuntu-openvino-2020.4.0:16.04
build_image:Custom=ubuntu-openvino-2021.1.0:20.04
Xbuild_image:Custom Win=openvino-2020.4.0
build_image:Custom Win=openvino-2021.1.0
Xbuild_image:Custom Mac=openvino-2020.4.0
build_image:Custom Mac=openvino-2021.1.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

### CODE REVIEW

**Comment by JulienMaille** [comment]
@alalek Sorry I'm not sure where to ask this, but what is the CMake flag we should use in order to disable openvino legacy mode (ie. not ngraph)
Thanks

**Comment by alalek** [comment]
Look for `OPENCV_DNN_IE_NN_BUILDER_2019` CMake variable (should be missing or has OFF value in `CMakeCache.txt`).
NN Builder API is already removed from OpenVINO 2020.4+

**Comment by JulienMaille** [comment]
> OPENCV_DNN_IE

I have this
```
//Build with Inference Engine NN Builder API support
OPENCV_DNN_IE_NN_BUILDER_2019:BOOL=OFF
```
However I still need to distribute `inference_engine_legacy.dll`

**Comment by alalek** [comment]
Some IE plugins may still use legacy stuff internally.

**Comment by alalek** [comment]
:+1:

**Pull request merged**
