### PR TITLE
cuda4dnn(conv): autotuning for convolution

### PR DESCRIPTION
**Pull request by YashasSamaga**
**Statistics as of May 14th 2020:**

Devices:

- GTX 1050 Mobile
- GTX 1080 Ti
- RTX 2080 Ti

[benchmarks without this PR](https://gist.github.com/YashasSamaga/4640594be2580d85b80f5c662339ff4b)

[benchmarks with this PR](https://gist.github.com/YashasSamaga/be44243671b4796977b475d02f41ef80)

[autotuning algorithm selections](https://gist.github.com/YashasSamaga/963d628a10711c8b5bfd6d8da2a5fee0)

[convolution configurations](https://gist.github.com/YashasSamaga/b048ee7084e52d9c9a3dd41f15663e09)

---

**NOTE:** Not up-to-date.

**Device:** GTX 1050

Model                                       | without this patch | with this patch
---------------------------------------- | ----------------------- | ---------------------
MobileNet SSD Coco v1          | 55ms                    |  **7ms**
MobileNet SSD Coco v2          | 84ms                    | **11ms**
OpenPose pose MPI                | 156ms                 | **111ms**
EfficientNet B0 YOLOv3          | 121ms                  | **15ms**
FastNeuralStyle Stary Night    | 26ms                    | **22ms**
Inception v2 Mask RCNN        | 180ms                  | **152ms**

Every model which uses depthwise convolutions has got an improvement.

Most of Mask RCNN improvement comes from a single convolution layer where the algorithm chosen by heuristics took 40ms whereas the best algorithm took just 20ms. 

---

**Pending:**
- insanely big initialization times

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
buildworker:Custom=linux-4
build_image:Custom=ubuntu-cuda:18.04
```

### CODE REVIEW

**Comment by tompollok** [comment]
Great Job @YashasSamaga

**Comment by YashasSamaga** [comment]
The CUDA backend now performs autotuning on its own which appears have resolved the performance degradation problems. Moreover, it also includes fused convolutions while autotuning. This has improved the performance further.

### Problem:
The initialization time has gone up significantly. It's in several seconds for many models and few of them take two digit seconds. Mask RCNN takes 26s for initialization!

There are eight algorithms available for convolution. These are the combinations which are tried while autotuning:

1. **cuDNN default math fused:**
    - all eight algorithms are tried
    - cuDNN does convolution, bias addition and activation together
2. **cuDNN default math unfused:**
    - all eight algorithms are tried
    - cuDNN does the convolution
    - bias addition and activation are carried out by cuda4dnn kernels (bias and activation are fused together)
3. **cuDNN tensor core fused:**
    - two algorithms are tried
    - cuDNN does convolution, bias addition and activation together
4. **cuDNN tensor core unfused**
    - two algorithms are tried
    - cuDNN does the convolution
    - bias addition and activation are carried out by cuda4dnn kernels (bias and activation are fused together)

In the worst case, 20 combinations will be tried for every convolution layer. There are few algorithms, particularly FFT based algorithms, which request insane amounts of workspace. For example, the FFT tiling algorithm requests a workspace of 8GB for convolving on a 200KB image. These memory allocations take seconds!

The FFT algorithms are feebly used (only once in my testbed consisting of 26 models) as they are too slow for small filters and small batches.

**Why try unfused cuDNN combinations when fused cuDNN combinations are available?**
Because fused cuDNN can sometimes be slower than unfused cuDNN convolution with separate bias_activation step. For example, if fused cuDNN operations are forced whenever they are available, MobileNet to take 37ms instead of just 7ms!

**Comment by tompollok** [comment]
Would it make sense to add a file next to the model file that persists the tuned configuration in case the same hardware is used to save expensive autotuning when just processing a single image on request, because sometimes several models have to be applied to a single image for some tasks.

**Comment by YashasSamaga** [comment]
That would require discussions on the storage format, API and a lot of other things (and quite a bit of work).

An easier temporary solution might be to make autotuning optional (opt-in feature, i.e. disabled by default). This again will require new API (or we can use a layer param of the conv layer).

**Comment by alalek** [comment]
Some similar approach exists in OpenCL (ocl4dnn) backend. It includes:
- rules to define convolution [configuration](https://github.com/opencv/opencv/blob/4.2.0/modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp#L631-L643).
- [default "pre-tuned" values](https://github.com/opencv/opencv/blob/4.2.0/modules/dnn/src/ocl4dnn/include/default_kernel_config.hpp) for some cases (target H/W is selected through number of execution units (EU) - autotuning is available for Intel iGPUs).
- multi-level storage of tuned configurations: ["default"](https://github.com/opencv/opencv/blob/4.2.0/modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp#L1973-L1974), ["in-memory"](https://github.com/opencv/opencv/blob/4.2.0/modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp#L1976), ["on disk"](https://github.com/opencv/opencv/blob/4.2.0/modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp#L2045).
- tuning configuration [flags](https://github.com/opencv/opencv/blob/4.2.0/modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp#L204-L233). Auto-tuning is disabled by default, but can be enabled by request or loaded from the disk.
- some [magic](https://github.com/opencv/opencv/blob/4.2.0/modules/dnn/src/ocl4dnn/src/ocl4dnn_conv_spatial.cpp#L1665-L1695) how candidates are generated for tuning process.

**Comment by YashasSamaga** [comment]
What about having an API for loading, saving and optimizing model cofigurations that is exposed through `cv::dnn::Net`? This seems more user-friendly than using environment variables. It also allows having unoptimized and optimized models to be used simultaneously (without having to modify the environment variables at runtime). It's also easier to extend in the future.

Both OpenCL and CUDA could use the same API instead of having individual backend-specific APIs.

I think only three functions are required (and maybe user-friendly overloads):
```
void Net::loadOptimizedConfiguration(const std::string& config);
void Net::saveOptimizedConfiguration(std::string& config);
void Net::runOptimizer();
```

The configuration could be stored in protobuf format. The format can be kept as an internal format.

**Comment by tompollok** [comment]
The API proposal sounds reasonable to me as it makes the use of optimized vs non optimized versions dynamically selectable at runtime and transparent to the users. I would also vote against the use environment variables.

**Comment by YashasSamaga** [comment]
cuDNN 8 has a brand new API which offers better autotuning capabilities. I will make a PR supporting cuDNN 8's new backend API and then a PR for autotuning.

**Comment by lorenzolightsgdwarf** [comment]
@YashasSamaga thanks for the work! On my net (a custom version of SSD MobileNet v2) I haven't seen any improvement. I'm using Cuda 10.2 and Cudnn 7.6.2. Is there any flag/environment variable that enables the autotuning? Or is there something that disables it? Bests!

**Comment by YashasSamaga** [comment]
> @YashasSamaga thanks for the work! On my net (a custom version of SSD MobileNet v2) I haven't seen any improvement. I'm using Cuda 10.2 and Cudnn 7.6.2. Is there any flag/environment variable that enables the autotuning? Or is there something that disables it? Bests!

It's always enabled in this PR. This PR hasn't been merged into master. Therefore, you need to build this PR to use the autotuning facility.

Related: https://github.com/opencv/opencv/issues/20966

**Pull request closed without merging**
