### PR TITLE
Add layer model blending

### PR DESCRIPTION
**Pull request by jsxyhelu**
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/766

from #17347
let us add a test to "addLayerModelBlending" and make it better.

<cut/>

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
opencv_extra=add_layer_model_blend
force_builders_only=linux,docs
```

### CODE REVIEW

**Comment by jsxyhelu** [comment]
This is the current state, buildbot reports this error 

> "Photo_LayerModelBlend_DARKEN.regression :
> /build/precommit_linux64/3.4/opencv/modules/photo/test/test_layermodelblend.cpp:27: Failure
> Value of: target.empty()
>   Actual: true
> Expected: false
> Could not load target image samples/cpp/lena.jpg"

I looked through the code and found that the pictures here need to be set up like this

> /*! @brief Try to find requested data file
> 
>   Search directories:
> 
>   0. TS::data_search_path (search sub-directories are not used)
>   1. OPENCV_TEST_DATA_PATH environment variable
>   2. One of these:
>      a. OpenCV testdata based on build location: "./" + "share/OpenCV/testdata"
>      b. OpenCV testdata at install location: CMAKE_INSTALL_PREFIX + "share/OpenCV/testdata"
> 
>   Search sub-directories:
> 
>   - addDataSearchSubDirectory()
>   - modulename from TS::init()
> 
>  */
I know the reason, but I don't know how to set the address here.
@mshabunin

**Comment by alalek** [comment]
Try `cvtest::findDataFile("cv/shared/lena.png")`.

`OPENCV_TEST_DATA_PATH` should point to `opencv_extra/testdata` directory.

**Comment by jsxyhelu** [comment]
test file have PR at  https://github.com/opencv/opencv_extra/pull/766
@alalek

**Comment by jsxyhelu** [comment]
now ,it is warnning
" warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]"
I have google at it,but did not find a method to remove

**Comment by alalek** [comment]
OpenCV 3.4 is written and must support C++98

**Comment by mshabunin** [comment]
I have some thoughts regarding this contribution. IMO, we should not add a single multitool function with giant `switch` inside, instead it should be either a set of higher-level header-only functions or even better a an example application. So my suggestion is to remove tests and move this function to the sample app.

**Review by jsxyhelu — COMMENTED** [review]
re-trigger

**Comment by jsxyhelu** [comment]
@mshabunin 
Buildbot reported this warnning
https://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/29402
```
/build/precommit_linux64/3.4/opencv/samples/cpp/blend.cpp:17:35: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
/build/precommit_linux64/3.4/opencv/samples/cpp/blend.cpp:17:45: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
……
```
 I tried some methods can not solve, hopping your guide, thank you!

**Comment by asenyaev** [comment]
jenkins cn please retry a build

**Comment by mshabunin** [comment]
> IMO, we should not add a single multitool function with giant `switch` inside, instead it should be either a set of higher-level header-only functions or even better an example application. So my suggestion is to remove tests and move this function to the sample app.

Let's close this PR since it is not clear whether these functions add value for computer vision applications or not.

**Pull request closed without merging**
