### PR TITLE
Kernel using events from OpenCL.

### PR DESCRIPTION
**Pull request by avieira**
### This pullrequest changes

Currently in OpenCV, the available OpenCL integration still does not include several tools defined by the standard. Among these features missing, I needed a way to use events.
For one of my current project, I need several Queues and synchronization between these using events. Since I am also using the OpenCL Kernels available in OpenCV, I thought it could be a nice idea to implement this Event class and add a way to run kernels using these events.
Also, from my point of view concerning the current goals for OpenCV, I think that these events could be a good tool for future developments. 

All comments (especially nice ones 😄 ) are welcome!

### CODE REVIEW

**Comment by avieira** [comment]
Could someone help me with the build please? ^^"

**Comment by catree** [comment]
@avieira 

In case you didn't see it, you can access the build logs by clicking on the red cross near the hash commit, or using [https://pullrequest.opencv.org/#/summary/opencv](https://pullrequest.opencv.org/#/summary/opencv).

**Comment by avieira** [comment]
@catree I know, I just have no idea how to fix that! If someone could give me a clue...

**Comment by asmorkalov** [comment]
Events support is very limited in current OpenCL implementations and there is no use-case for OpenCL events in library right now. Filed feature request https://github.com/opencv/opencv/issues/15933 with reference to patch to return to the PR later.

**Pull request closed without merging**
