### PR TITLE
videoio: deprecate Video for Windows (VFW)

### PR DESCRIPTION
**Pull request by alalek**
consider using MSMF backend

### CODE REVIEW

**Comment by vpisarev** [comment]
@alalek, pls do not merge it until we have MSMF backend fixed w.r.t video resolution settings.

**Comment by adamrankin** [comment]
Small inquiry:

If the DirectShow backend is being deprecated, could I ask for confirmation that webcam autofocus can be controlled via MSMF backend?

**Comment by alalek** [comment]
Reverted DSHOW changes.

**Comment by alalek** [comment]
:+1:

**Pull request merged**
