### PR TITLE
Clean up C API

### PR DESCRIPTION
**Pull request by sturkmen72**
https://github.com/opencv/opencv/issues/11000

<cut/>

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
buildworker:Linux x64 Debug=linux-1,linux-4,linux-6
allow_multiple_commits=1
```

### CODE REVIEW

**Comment by asmorkalov** [comment]
Relates to #19606

**Comment by sturkmen72** [comment]
i created two commits in order to seperate cleaned and changed lines

**Comment by alalek** [comment]
Could you please clean up commit message? (it refers to non-existed commit: "This reverts commit ...")

This can be done through `git rebase -i HEAD~2` and using "r" ("reword") commands.

**Comment by alalek** [comment]
@sturkmen72 Thank you for contribution! Is PR still in WIP status?

**Comment by sturkmen72** [comment]
@alalek as you know there are still remaining C functions can be cleaned up but needed more effort ( changing test codes , updating legacy codes etc. ). lets merge this PR for now. i will try to clean up more later..

**Review by alalek — APPROVED** [review]

**Comment by sturkmen72** [comment]
is there an estimated date to release 5.0 ?

**Pull request merged**
