### PR TITLE
cuda optflow TVL1 : run safely in async mode

### LINKED ISSUE #16013: Corrupted optical flow using cuda::DenseOpticalFlow asynchronously in multithreaded environment
##### System information (version)

- OpenCV => 4.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015
- Cuda => 10.1

##### Detailed description

I will duplicate the problem described here: 
https://stackoverflow.com/questions/59075944/why-do-i-get-corrupted-results-if-i-run-gpu-dense-optical-flow-algorithm-concurr

> While using OpenCV CUDA dense optical flow in parallel I noticed that sometimes I get corrupted optical flow results, though I run it on different `cuda::GpuMat`s and in separate `cuda::Stream`s with separate Algorithm instances.
> 
> After some experiments with the code I found out that if I protect `DenseOpticalFlow::calc()` call with `mutex` or run only one thread, I always get correct (not corrupted) results.
> 
> I reduced my code to minimum reproducible example where I run optical flow algorithm on same input images multiple times in multiple threads

Furthermore, I checked that calling `cuda::Stream::waitForCompletion()` before calling `DenseOpticalFlow::calc()` asynchronously still causes the corruption.

However, if i use default stream `cuda::Stream::Null()` or use only `DenseOpticalFlow::calc()` synchronously, no corruption occurs.

Seems like using `DenseOpticalFlow::calc()` asynchronously causes data races.

##### Steps to reproduce

To reproduce the problem, you can use the example provided by the link above.

### PR DESCRIPTION
**Pull request by nglee**
Fixes #16013

We are going to use texture object, rather than texture reference.
It allows us to run the algorithm asynchronously.
This is similar to what's been done in #11483

<cut/>

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

```
allow_multiple_commits=1
force_builders=Custom
buildworker:Custom=linux-4
build_image:Custom=ubuntu-cuda:18.04
```

### CODE REVIEW

**Comment by alalek** [comment]
@nglee Thank you for the contribution!

Could you please take a look on this error message (from Custom builder)?
```
/build/precommit_custom_linux/3.4/opencv/modules/cudaimgproc/src/cuda/canny.cu:93:8: error: 'struct canny::SrcTex' has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
     struct SrcTex
        ^~~~~~
/build/precommit_custom_linux/3.4/opencv/modules/cudaimgproc/src/cuda/canny.cu:104:8: error: base class 'struct canny::SrcTex' has accessible non-virtual destructor [-Werror=non-virtual-dtor]
     struct SrcTexRef : SrcTex
        ^~~~~~~~~
/build/precommit_custom_linux/3.4/opencv/modules/cudaimgproc/src/cuda/canny.cu:104:8: error: 'struct canny::SrcTexRef' has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
/build/precommit_custom_linux/3.4/opencv/modules/cudaimgproc/src/cuda/canny.cu:114:8: error: base class 'struct canny::SrcTex' has accessible non-virtual destructor [-Werror=non-virtual-dtor]
     struct SrcTexObj : SrcTex
        ^~~~~~~~~
/build/precommit_custom_linux/3.4/opencv/modules/cudaimgproc/src/cuda/canny.cu:114:8: error: 'struct canny::SrcTexObj' has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
cc1plus: some warnings being treated as errors
```

(perhaps it is enough to define destructor of the base class as `virtual`)

**Comment by nglee** [comment]
@alalek Build error fixed!

**Comment by nglee** [comment]
It is ready to be merged. I've also tested with OP's test code in #16013.

**Comment by tomoaki0705** [comment]
Hi @nglee , I see build error on Jetson TX1 and TX2.

```
/opencv-fork/modules/cudaimgproc/src/cuda/canny.cu(131): error: namespace "std" has no member "enable_if_t"

/opencv-fork/modules/cudaimgproc/src/cuda/canny.cu(131): error: expected a "," or ">"
```

The direct cause come from [this line](https://github.com/opencv/opencv/blame/9755ab160d94f4ad2a672653cf657ad421d46837/modules/cudaimgproc/src/cuda/canny.cu#L131)

https://github.com/opencv/opencv/blame/9755ab160d94f4ad2a672653cf657ad421d46837/modules/cudaimgproc/src/cuda/canny.cu#L131

We only enable C++11 feature on master, not on 3.4, but it seems `enable_if_t` is a [c++14 feature](https://en.cppreference.com/w/cpp/types/enable_if)
> template< bool B, class T = void > using enable_if_t = typename enable_if<B,T>::type; |   | (since C++14)

I appreciate if you could have a look on this.
Still it's unknown why I didn't face this on Jetson Xavier and Jetson Nano.

**Comment by nglee** [comment]
@tomoaki0705 

Thank you for investigation. Would you please check your g++ version?
> The default mode is C++98 for GCC versions prior to 6.1, and C++14 for GCC 6.1 and above. ([Link](https://www3.ntu.edu.sg/home/ehchua/programming/cpp/gcc_make.html))

To enable c++14 via cmake, maybe we can try this flag: `-DCMAKE_CXX_STANDARD=14`.

Just removing the lines with `enable_if_t` would also work.

**Comment by tomoaki0705** [comment]
Jetson TX1 GCC 5.4.0
Jetson TX2 GCC 5.4.0
Jetson Nano GCC 7.5.0
Jetson Xavier GCC 7.5.0
That makes sense.

**Pull request merged**
