### PR TITLE
dnn: moved NMSBoxes to imgproc module

### PR DESCRIPTION
**Pull request by mshabunin**
_Motivation:_ non-maximum suppression can be used not only as postprocessing in DNN-based algorithms, so we move it to _imgproc_ module together with other geometry- and contour-related algorithms (bounding rect, intersections, etc.).

##### Notes: 
- I tried to preserve ABI and API compatibility with existing code, thus declaring aliases in `cv::dnn` namespace and keeping old functions in _dnn_ module (hidden from user, header file not installed). Maybe it is not really necessary because _dnn_ ABI is still considered experimental.
- Python API will probably be broken (cv.dnn.NMSBoxes -> cv.NMSBoxes) (maybe we can put these functions to the `dnn` namespace in the _imgproc_ module to fix it...? :thinking:)
- I did not check other bindings (JS?)

### CODE REVIEW

**Comment by opencv-alalek** [comment]
IMO, it should be `objdetect` instead. Similar to `groupRectangles()` API.

(but need to resolve dependency issue).

**Comment by mshabunin** [comment]
Originally I wanted to move all NMS stuff to the _core_ module to be close with `Rect` and `RotatedRect`, but turned out NMS for `RotatedRect` uses `rotatedRectangleIntersection` and `contourArea` to calculate IOU which are in _imgproc_.

It seems impossible to move NMS to _objdetect_ because then _dnn_ would depend on it and we already have inverse dependency (_objdetect_ on_dnn_).

I think, ideally all geometry-related classes and algorithms should be moved to the _core_ or a separate module - large part of `core/types.hpp`, operations with rectangles and contours (but not `findContours`) - all of this does not operate with pixels and does not depend on `Mat`.

**Comment by fengyuentau** [comment]
> IMO, it should be objdetect instead.

I agree with this. `imgproc` is more like a **image** processing module but `NMSBoxes` or `NMSBoxesBatched` is operation on **boxes**.

If the API move is being proceeding still, we can leave the legacy API calling the new one from other module, and leave a warning for API deprecation.

**Comment by asmorkalov** [comment]
Discussed on OpenCV core team meating. Found alternative solution. Closed.

**Comment by dkurt** [comment]
@asmorkalov, Once an alternative solution will be published, may I ask to refer it here? Just to be on touch. Thanks in advance!

**Pull request closed without merging**
