### PR TITLE
Move workflows to a dedicated repository for 5.x branch

### PR DESCRIPTION
**Pull request by asenyaev**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by fengyuentau** [comment]
How about putting all gha workflows in one single file for different branch. Different workflows can be distinguished by different job names. For example, instead of having `PR-4.x-(ARM64|W10|U20).yaml`, we can have one single file named `PR-4.x.yaml` with the following workflows:
```yaml
jobs:
  ARM64-BuildAndTest:
    ...
  ARM64-BuildContrib:
    ...
  W10-BuildAndTest:
    ...
  ....
```

**Comment by asenyaev** [comment]
@fengyuentau it's a good point. In your idea we will reduce an amount of files in repositories, but will increase an amount of lines there. In addition, we will not be able to check the certain platform in Actions, I mean this part:

image

we will open the whole build and check what was wrong there, but on the PR page it will be shown almost without any changes.

I've tried to reproduce your idea, you can check it here:
- [Opened PR](https://github.com/asenyaev/opencv/pull/38)
- [Repository with workflows](https://github.com/asenyaev/opencv-ci/tree/4.x/.github/workflows)

**Comment by asenyaev** [comment]
@fengyuentau, I've updated a PR with a merged file for all platforms, but kept them split for the dedicated repository as we discussed on the meeting.

**Review by fengyuentau — APPROVED** [review]

**Comment by alalek** [comment]
We need to check how we would use workflow "re-run" in this case. It would be nice to have ability to re-trigger job for single platform only (e.g. ARM only) in case of infrastructure failures/instability. Currently we have such ability.

**Comment by fengyuentau** [comment]
If I am understanding correctly, there are two cases of re-running jobs after all jobs of a PR are done:
- There is a 'Re-run all jobs' button on the top-left in the 'Checks' section. If it is clicked then all jobs will re-run regardless of success or fail.
- Also in the 'Checks' section, if one wants to re-run lets say jobs for ARM64, then click 'PR: 4.x ARM64' and it leads to a summary page. On the top-left, there is a 'Re-run all jobs' button where you can select 'Re-run all jobs' or 'Re-run failed jobs' triggering only jobs for ARM64.

I did not find a button triggering only failed jobs for all platform though.

**Comment by alalek** [comment]
> 'Re-run failed jobs'

should work.

**Review by alalek — APPROVED** [review]
Thank you!

**Comment by asenyaev** [comment]
> > 'Re-run failed jobs'
> 
> 
> 
> should work.

Yes, it works. In addition, there are different use cases for re-run. Usually it works using "Re-run failed jobs", but you can re-run only one failed using a phone.

**Comment by alalek** [comment]
Actually it is possible to re-run any job from workflow (UI is hidden until you hover over the job's element).
So there is not problem at all.

gha-single-job

**Comment by asenyaev** [comment]
Oh, great. It was a bit different some time ago, I thought they removed it from desktop UI.

**Comment by fengyuentau** [comment]
> Actually it is possible to re-run any job from workflow (UI is hidden until you hover over the job's element). So there is no problem at all.
> 
> gha-single-job

It seems we have to access from the 'Actions' -> 'All workflows' to get to the summary page of all platforms. I don't see a button in the 'Checks' section in a PR's page leading to the the summary page of all platforms, but only the summary page of a certain platform.

image

**Pull request merged**
