### PR TITLE
Add support for Swift version independence

### PR DESCRIPTION
**Pull request by komakai**
- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch

This PR addresses #18489

- when building with CMake 3.19 or greater and Xcode 12 or greater generate **swiftinterface** files
- improvements to the autogenerated Xcode project for Xcode New Build system
- add support for standard module properties **VersionNumber** and **VersionString**
- when build with older versions of CMake and/or Xcode continue to build as before (without generating **swiftinterface** files)

```
force_builders=Custom Mac
build_image:Custom Mac=osx_framework
```

### CODE REVIEW

**Comment by alalek** [comment]
@AlvarHHM Could you please check this patch in your configuration?

**Comment by AlvarHHM** [comment]
It will certainly work if I compile it myself with my own Xcode 12. The question should be does this patch solve the forward compatibility issue, i.e. can I import the binary compiled with Xcode 11 in Xcode 12.

**Comment by alalek** [comment]
@AlvarHHM I have [scheduled](http://pullrequest.opencv.org/buildbot/builders/master_iOS-mac/builds/11330) iOS package build for PR on our CI with Xcode 11.

Artifacts should be available in 60-90 minutes (link is provided by step 7 "upload artifacts", but please expect that network external bandwidth of CI is limited)

**Comment by komakai** [comment]
@AlvarHHM @alalek as per the explanation in the PR - you will only get a version independent build when building with Xcode 12 (or greater) together with CMake 3.19 (or greater). This is due to the required functionality (support for Xcode new build system) not being available in earlier CMake versions due to bugs in Xcode that have only now been fixed in Xcode 12

**Comment by AlvarHHM** [comment]
I just tried, [this](https://pullrequest.opencv.org/buildbot/builders/master_iOS-mac/builds/11330) does not work. 

It shows the same error `Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.3 compiler`

**Comment by alalek** [comment]
@AlvarHHM Thank you for the checking!

Unfortunately there is no CMake 3.19 on our Mac OS X machines yet. This is critical for this patch as @komakai mentioned above.

**Review by alalek — APPROVED** [review]
Thank you :+1:

**Comment by sjang42** [comment]
Is this tested? I just built master branch with Xcode12.1 and run it with Xcode12.2 but it does not work.
Below is the error message.
Failed to build module 'OpenCV' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'

**Pull request merged**
