### PR TITLE
fix doc.

### PR DESCRIPTION
**Pull request by csukuangfj**
fix doc.

### CODE REVIEW

**Comment by alalek** [comment]
Thank you!
Could you please rebase this patch to 3.4 branch too?

We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

**Comment by csukuangfj** [comment]
Done.

**Comment by sturkmen72** [comment]
@csukuangfj could you fix https://github.com/opencv/opencv/blob/master/cmake/OpenCVFindLibsPerf.cmake#L46

**Comment by csukuangfj** [comment]
@sturkmen72 
Sure. Done.

**Pull request merged**
