### PR TITLE
improve the mkl search procedure

### PR DESCRIPTION
**Pull request by cyyever**
I use the MKL package provided by nuget. Please check this link(https://software.intel.com/en-us/articles/installing-intel-performance-libraries-using-nuget) for related information.

MKL 2020.1.216

### CODE REVIEW

**Comment by alalek** [comment]
Please add more information, so we can validate that:
- which MKL version are you using?

**Comment by asmorkalov** [comment]
@cyyever Could you provide details on MKL version?

**Comment by cyyever** [comment]
> @cyyever Could you provide details on MKL version?

2020.1.216

**Comment by asmorkalov** [comment]
@alalek friendly reminder.

**Pull request merged**
