### PR TITLE
[evolution] Stitching for OpenCV 4.0

### PR DESCRIPTION
**Pull request by hrnr**
I have received a very little feedback on evolution proposal #11039. I have decided to come with some code, to start the discussion. Here are some minimal changes in the stitching module, that I think should go to OpenCV 4.0. Large parts of the evolution proposal are not implemented and I'm awaiting further feedback.

- [ ] remove `detail::FeaturesFinder` and `detail::FeaturesMatcher` wrapper classes. Use `cv::Feature2D` and `cv::DescriptorMatcher` from features2d module. This will allow to use all features and descriptors with stitching modules. Move all estimation code from `detail::FeaturesMatcher` to `detail::Estimator`. This also solves problems with dependencies on xfeatures2d.
- [x] allow user to explicitly set `detail::Estimator`
- [x] consolidate creation methods for stitcher. Keep only `Stitcher::create`, wrap this method for Python. Drop `try_use_gpu` flag, rely on T-API or user explicitly setting CUDA classes to use.
- [ ] allow users to set FeaturesFinder, DescriptorMatcher, BundleAdjuster etc. from Python
- [ ] drop legacy usage of legacy Levenberg–Marquardt API from bundle adjusters. Replace with new LevMarq API.
- [ ] remove direct usage of CUDA from stitching module (OpenCL alternatives are already available). Move to CUDA modules where it makes sense.

```
force_builders=linux,Linux OpenCL,windows,macosx,docs,Custom,Win64 OpenCL
docker_image:Custom=ubuntu-cuda:16.04
**WIP**
```

### CODE REVIEW

**Comment by hrnr** [comment]
I have dropped `try_use_gpu` flag. OCL will be utilised automatically in enabled paths. To use CUDA paths user needs to explicitly set CUDA classes in stitching.

 What do you think about dropping `detail::FeaturesFinder`, `detail::FeaturesMatcher` and the wrapper code in favour of `cv::Feature2D`, `cv::DescriptorMatcher` and classes from features2d? Should I go forward with that? That will be a big change and quite a lot of work, so I want some approval before I continue.

**Comment by alalek** [comment]
> favour of cv::Feature2D, cv::DescriptorMatcher and classes from features2d

Sounds good.

**Comment by LaurentBerger** [comment]
May be too late but in this [example ](https://github.com/LaurentBerger/Traitement_d_images_et_de_videos_avec_OpenCV3/blob/master/ch5PanoCam/main.cpp)I can save all results of stitching process except ExposureCompensator. Is it possible to add a method to get ExposureCompensator result?

**Comment by hrnr** [comment]
I don't get what you want to achieve. There is `ExposureCompensator::apply` to get the results of exposure compensation. What are you missing? Is there any other info that is not exposed?

**Comment by LaurentBerger** [comment]
I need to investigate more but I think it is [gain_maps](https://github.com/opencv/opencv/blob/master/modules/stitching/src/exposure_compensate.cpp#L234-L237)
You can everything in yml file except results of those lines : 
```
       pp.algoCorrectExpo = ExposureCompensator::createDefault(pp.correctionExposition);
        pp.algoCorrectExpo->feed(pp.posCoin, imagesProjetees, pp.masqueCompo);

``` 
Example I have two webcam and I stitch images. I save everything . Then I can run my program without any initialize stitching (except ExposureCompensator)

**Comment by hrnr** [comment]
I have rebased the brach due to merge conflict.

**Comment by vpisarev** [comment]
:+1: can be merged as soon as buildbot becomes green

**Comment by hrnr** [comment]
Thanks for the review. You are right, @alalek, `INTER_NEAREST` is the correct interpolation there. Fixed. Many thanks for fixing the issue in SURF.

Squashed fixup commits, rebased.

As you know I wanted a bigger scope for this, but I don't have much of a free time nowadays to put into this as I'm starting in a new job. At least, I'd love to see something similar done for `detail::FeaturesMatcher`, but I'm not sure if I find a free day for coding to take on that. Anyone from the community please feel free to take this further, I can help if you run into any issues, just mention me so I receive an email.

For the time being, I'm glad that at least this part goes in.

**Comment by LaurentBerger** [comment]
@hrnr I can work on stitching module. I already wrote an[ example in C++](https://github.com/LaurentBerger/Traitement_d_images_et_de_videos_avec_OpenCV3/tree/master/ch5PanoCam). I need to translate this example in python. I need your PR. If something is missing I can make a new PR.

**Comment by hrnr** [comment]
Sure go for it. My plan for `detail::FeaturesMatcher` was to replace it with `cv::DescriptorMatcher` everywhere, then delete almost all the code in the stitching module related to matches. One caveat there is that the transform estimation code (now sitting in the high-level Matchers) needs to moved to `detail::Estimator`, which will be solely responsible for the geometry model used. Apart from that it should be fairly straightforward job, requiring only small amount of the glue code to do the parallel matching - the code is already there, probably only needs to be moved around.

**Pull request merged**
