### PR TITLE
don't treat 3rd protobuf headers as system as then they will be mixed…

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by alalek** [comment]
Probably you have catched problem from here: #13328
There are an workaround and an unmerged bugfix.

---

"system" headers must be used for any external dependency, because we don't care about warnings from there.

**Comment by cyyever** [comment]
> Probably you have catched problem from here: #13328
> There are an workaround and an unmerged bugfix.
> 
> "system" headers must be used for any external dependency, because we don't care about warnings from there.

This is probably not a good use case of system· Using system means the dir will be searched after any other locations. Then if the system protobuf is in a previous location , it will cause a version mismatch. In my opinion ， using system make it hard to adjust dir search order.

**Comment by alalek** [comment]
> system protobuf is in a previous location

This usually happens when other 3rdparty dependency don't use "-isystem" with common include location like `/usr/include` or `/usr/local/include`.

(this is not a protobuf only problem at least)

**Comment by cyyever** [comment]
> 
> 
> > system protobuf is in a previous location
> 
> This usually happens when other 3rdparty dependency don't use "-isystem" with common include location like `/usr/include` or `/usr/local/include`.
> 
> (this is not a protobuf only problem at least)

Yes, but I have to change it case by case. Anyway, I think the same package installed on /usr/local/include is a common case. For example, I met this problem on FreeBSD when 3rd packages are installed on /usr/local/include. I am not sure how this patch would break existing systems. Anyway, we should make sure the bundled locations are searched first if we use them.

**Comment by alalek** [comment]
We should detect and fix these other 3rdparty packages first instead of touching protobuf.

"Fixing" protobuf only is a wrong way.

---

You may want to play with `CMAKE_INCLUDE_SYSTEM_FLAG_CXX` variable.

**Comment by cyyever** [comment]
> 
> 
> > system protobuf is in a previous location
> 
> This usually happens when other 3rdparty dependency don't use "-isystem" with common include location like `/usr/include` or `/usr/local/include`.
> 
> (this is not a protobuf only problem at least)

After a quick search under 3rdparty , I found that only protobuf and tbb use SYSTEM, so we may just remove them? A more systematic way is use target-based linking, but that would change almost every bit of CMake code.

**Pull request closed without merging**
