### PR TITLE
fix: traincascade, use C++ persistence API to compile with 4.x

### PR DESCRIPTION
**Pull request by fdivitto**
This pull allows to compile traincascade application with OpenCV 4.6. Changes uses new persistence C++ API in place of legacy one.

https://github.com/opencv/opencv/issues/13231

Contains changes requested by https://github.com/asmorkalov

### CODE REVIEW

**Comment by opencv-alalek** [comment]
Please don't re-open PRs. Use the fist one.
At least to keep history of discussions and decisions.
Refer to GitHub and Git documentation how to work with that.

**Comment by fdivitto** [comment]
> Please don't re-open PRs. Use the fist one.

the first one is closed. I cannot find a way to do that, I'm sorry.

**Comment by opencv-alalek** [comment]
Because you should not delete your source repository.

Again,

> Refer to GitHub and Git documentation how to work with that.

---

As there is no way to recover on GitHub after repository removal - please create 3rd PR using the meaningful source branch name instead of `4.x`.

**Comment by fdivitto** [comment]
> As there is no way to recover on GitHub after repository removal - please create 3rd PR using the meaningful source branch name instead of `4.x`.

I've just done this, but there is a problem:

[23588](https://github.com/opencv/opencv/pull/23588)

**Pull request closed without merging**
