### PR TITLE
Fix typo calibaration/calibration

### PR DESCRIPTION
**Pull request by traversaro**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by traversaro** [comment]
fyi @singhbal-baljinder @AngeloRendiniello @giusenso

**Comment by asmorkalov** [comment]
Thanks for the contribution! The issue is present in branch 3.4 too. Please rebase the patch to 3.4 and retarget the PR too. OpenCV team will merge the patch to 4.x and 5.x during regular merge procedure.

**Comment by asmorkalov** [comment]
Already fixed in https://github.com/opencv/opencv/pull/22045. Will be merged from 3.4 to master soon.

**Comment by traversaro** [comment]
> Already fixed in https://github.com/opencv/opencv/pull/22045. Will be merged from 3.4 to master soon.

Thanks! Sorry I forgot about the previous message.

**Pull request closed without merging**
