### PR TITLE
more sprintf removals

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@asmorkalov I've been waiting to hear from an OpenCV developer.

I marked it as WIP just so no one would merge it as-is.

Biggest thing to discuss is if the approach of either/both of the 2 WIP commits is acceptible...

**Comment by seanm** [comment]
@asmorkalov  this is ready to commit IMHO.  Care to review?

I dropped the WIP commit and will make another PR with it.

**Review by asmorkalov — APPROVED** [review]

**Comment by asmorkalov** [comment]
@opencv-alalek Could you take a look too?

**Comment by seanm** [comment]
> I dropped the WIP commit and will make another PR with it.

And here is the other/followup PR: https://github.com/opencv/opencv/pull/23502

**Review by opencv-alalek — APPROVED** [review]
LGTM :+1:

**Pull request merged**
