### PR TITLE
Optimize the cvCeil and cvFloor functions for LoongArch

### PR DESCRIPTION
**Pull request by CNClareChen**
This patch optimizes the cvCeil and cvFloor functions on
the LoongArch platform.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
Relates to https://github.com/opencv/opencv/pull/21833

**Comment by vpisarev** [comment]
@CNClareChen, thank you! I wonder, if `(int)__builtin_floor(value), (int)__builtin_ceil(value), (int)__builtin_floorf(value), (int)__builtin_ceilf(value)` produce equivalent code on LoongArch?

**Comment by CNClareChen** [comment]
> @CNClareChen, thank you! I wonder, if `(int)__builtin_floor(value), (int)__builtin_ceil(value), (int)__builtin_floorf(value), (int)__builtin_ceilf(value)` produce equivalent code on LoongArch?

Thanks， these __builtin_ finterfaces are not currently integrated in the compiler for the LoongArch platform. Therefore, in OpencV I use the way of embedded assembly to achieve these functions quickly.

**Comment by asmorkalov** [comment]
@CNClareChen @fengyuentau The base PR for loongArch support has been merged. Please rebase the PR and fix merge conflicts.

**Comment by asmorkalov** [comment]
@fengyuentau Could you sqaush commits? "Merge branch '4.x' into 4.x" - it'll be merged to history too.

**Comment by fengyuentau** [comment]
I could but I do not know the safe way to do this without dropping @CNClareChen 's status as a contributor.

**Comment by asmorkalov** [comment]
@CNClareChen could you squash commits on your side?

**Comment by CNClareChen** [comment]
OK, thanks for reminding me. I'll deal with it tomorrow.---- Replied Message ----FromAlexander ***@***.***>Date09/12/2022 16:31 ***@***.***> ***@***.******@***.***>SubjectRe: [opencv/opencv] Optimize the cvCeil and cvFloor functions for LoongArch (PR #22040)
@CNClareChen could you squash commits on your side?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/opencv/opencv/pull/22040#issuecomment-1243395049",
"url": "https://github.com/opencv/opencv/pull/22040#issuecomment-1243395049",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by CNClareChen** [comment]
@asmorkalov Now, this patch is merged. Should I resubmit a patch to modifies the commits?

**Comment by asmorkalov** [comment]
@CNClareChen I apologize, I disoriented you. Yuantao merged upstream 4.x to your branch, but not rebase it. It leads to incompatible commit history in you branch and upstream. I fixed the issue by cherry-picking of proper commit on top of upstream 4.x. Please pay attention, that I have to rewrite commits history for it. Please chech the branch with real hardware to ensure the patch works correctly.

**Comment by fengyuentau** [comment]
Tested on loongarch server and all tests are passed except the known `Calib3d_StereoBM.regression` regression test.

**Comment by CNClareChen** [comment]
> @CNClareChen I apologize, I disoriented you. Yuantao merged upstream 4.x to your branch, but not rebase it. It leads to incompatible commit history in you branch and upstream. I fixed the issue by cherry-picking of proper commit on top of upstream 4.x. Please pay attention, that I have to rewrite commits history for it. Please chech the branch with real hardware to ensure the patch works correctly.

Thank you very much for your kind help. This patch can work normally in my branch with real hardware.

**Review by asmorkalov — APPROVED** [review]

**Pull request merged**
