### PR TITLE
[GSoC 2022] enable inline assembly/nasm in libjpeg-turbo

### PR DESCRIPTION
**Pull request by ocpalo**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [X] The PR is proposed to the proper branch
- [X] There is a reference to the original bug report and related work
- [X] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [X] The feature is well documented and sample code can be built with the project CMake

Perf Test Result without NASM/SIMD
Screenshot from 2022-08-02 21-30-25

Perf Test Result with NASM/SIMD
Screenshot from 2022-08-02 21-29-25

I updated to the latest libjpeg-turbo source files and added SIMD extension to the 3rd party library.

Edit: Test environment lacks of NASM. How can i solve this issue?

### CODE REVIEW

**Comment by vpisarev** [comment]
@ocpalo, thank you for the PR.

1. you need to agree to contribute this PR under Apache 2 license and also check the other required marks in the checklist.
2. please, make our CI "green", now there are some issues with compiling your PR

**Comment by ocpalo** [comment]
@vpisarev Yes, I am aware of these issues. I will try to solve it as soon as possible. CI environment does not have NASM installed in different OS's. Is there a way to change this for this pull request to see if it works?

**Comment by ocpalo** [comment]
@asmorkalov @vpisarev could you run workflow one more?

**Comment by ocpalo** [comment]
@asmorkalov @vpisarev  Can someone check if macOS-ARM64 BuildAndTest fail is related to my commit? I don't think it is. 

Thanks in advance

**Comment by ocpalo** [comment]
With the latest change, I can approve that NASM is working for Windows environment. Thanks to @sturkmen72 . He helped me to test this.

https://ci.appveyor.com/project/sturkmen72/opencv-image-reading/builds/44381948

**Comment by asmorkalov** [comment]
Hello @ocpalo Thanks for the contribution! The patch was discussed on OpenCv core meeting and proposal is the following:
- Split the change on 2 PRs: JPEG-turbo version update without modifications and then PR with assembler enabled. Fot the first part it's important to have link to origin and version.
- NASM dependency should be optional. Please add assembler status to CMake status to make it visible in cv::getBuildInformation().

**Comment by ocpalo** [comment]
> Hello @ocpalo Thanks for the contribution! The patch was discussed on OpenCv core meeting and proposal is the following:
> 
> * Split the change on 2 PRs: JPEG-turbo version update without modifications and then PR with assembler enabled. Fot the first part it's important to have link to origin and version.
> * NASM dependency should be optional. Please add assembler status to CMake status to make it visible in cv::getBuildInformation().

Thanks for the update! Vadim also informed me about these. I will try to finish this today.

**Pull request closed without merging**
