### PR TITLE
G-API: Fix optional move constructor

### PR DESCRIPTION
**Pull request by smirnov-alexey**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
Xforce_builders_only=linux,docs
force_builders=Custom,Custom Win,Custom Mac
build_gapi_standalone:Linux x64=ade-0.1.1f
build_gapi_standalone:Win64=ade-0.1.1f
build_gapi_standalone:Mac=ade-0.1.1f
build_gapi_standalone:Linux x64 Debug=ade-0.1.1f

build_image:Custom=centos:7
buildworker:Custom=linux-1
build_gapi_standalone:Custom=ade-0.1.1f

Xbuild_image:Custom=ubuntu-openvino-2021.1.0:20.04
build_image:Custom Win=openvino-2021.1.0
build_image:Custom Mac=openvino-2021.1.0

Xtest_modules:Custom=gapi
test_modules:Custom Win=gapi
test_modules:Custom Mac=gapi

Xbuildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
Xtest_opencl:Custom=OFF
Xtest_bigdata:Custom=1
Xtest_filter:Custom=*
```

### CODE REVIEW

**Comment by smirnov-alexey** [comment]
Example:
```
cv::util::optional<std::unique_ptr<MyClass>> m_opt;
m_opt(std::move(std::unique_ptr<MyClass>(new MyClass(...))))
```
Didn't work before the fix

**Comment by smirnov-alexey** [comment]
@dmatveev @TolyaTalamanov @rgarnov, please, take a look

**Comment by TolyaTalamanov** [comment]
You're right, cool! 👍

**Comment by TolyaTalamanov** [comment]
> Example:
> 
> ```
> cv::util::optional<std::unique_ptr<MyClass>> m_opt;
> m_opt(std::move(std::unique_ptr<MyClass>(new MyClass(...))))
> ```
> 
> Didn't work before the fix

Sorry for being so boring, but the `std::move` is redundant :)

**Comment by smirnov-alexey** [comment]
@alalek can we merge this?

**Pull request merged**
