### PR TITLE
Fix compilation when HAVE_QUIRC is not set.

### PR DESCRIPTION
**Pull request by vrabaud**
One variable is unknown while the other one is unused.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch

### CODE REVIEW

**Comment by asmorkalov** [comment]
Without QUIRC:
```
In file included from /home/alexander/Projects/OpenCV/opencv-master/modules/objdetect/test/test_qrcode.cpp:6:0:
/home/alexander/Projects/OpenCV/opencv-master/modules/objdetect/test/test_qr_utils.hpp: In function ‘void opencv_test::check_qr(const string&, const string&, const string&, const std::vector<cv::Point_<int> >&, const std::vector<std::__cxx11::basic_string<char> >&, int, bool)’:
/home/alexander/Projects/OpenCV/opencv-master/modules/objdetect/test/test_qr_utils.hpp:11:44: warning: unused parameter ‘decoded_info’ [-Wunused-parameter]
                 const std::vector<string>& decoded_info, const int max_pixel_error,
                                            ^~~~~~~~~~~~
```

**Comment by vrabaud** [comment]
I do get an error though for the first decoded_info:
```
modules/objdetect/test/test_qrcode.cpp:389:68: error: use of undeclared identifier 'decoded_info'
  389 |     check_qr(root, name_current_image, "multiple_images", corners, decoded_info, pixels_error, true);
      |                                                                    ^
modules/objdetect/test/test_qrcode.cpp:541:28: error: unused variable 'expect_msg' [-Werror,-Wunused-variable]
  541 |         const std::string &expect_msg = flipped_image.second;
```
(line numbers are slightly off due to modify includes for internal code)

**Review by asmorkalov — APPROVED** [review]
:+1:

**Comment by asmorkalov** [comment]
@vrabaud Thanks a lot for the fix! I updated solution a bit and fixed build warning.

**Pull request merged**
