### PR TITLE
G-API: Added an arbitrary-argument version of cv::gapi::combine

### PR DESCRIPTION
**Pull request by dmatveev**
- Now user doesn't need to do `combine(x, combine(y, combine(z, zz)))` but
  just `combine(x, y, z, zz)`

### CODE REVIEW

**Comment by dmatveev** [comment]
@TolyaTalamanov please review

**Comment by TolyaTalamanov** [comment]
LGTM 👍

**Comment by dmatveev** [comment]
@TolyaTalamanov thanks! @alalek can we merge this?

**Comment by dmatveev** [comment]
Thanks!

**Pull request merged**
