### PR TITLE
Fix error in documentation for RGB->HSV convertion

### PR DESCRIPTION
**Pull request by Liangda-w**
### Pull Request Readiness Checklist

Resolves https://github.com/opencv/opencv/issues/19406

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by Liangda-w** [comment]
#19406

**Comment by asmorkalov** [comment]
@Liangda-w Please pay attention that you modifies RGB ↔ HLS documentation. It's ok, but the ticket says about RGB ↔ HSV. Please add the same to previous section too. Documentation preview for your PR: http://134.191.240.118/buildbot/export/pr/19419/docs/de/d25/imgproc_color_conversions.html

**Comment by vpisarev** [comment]
I can confirm that if R=G=B then H=S=0. @Liangda-w, please, update both RGB <=> HSV and RGB <=> HSL documentation, as @asmorkalov suggested, then your patch will be merged.

**Comment by Liangda-w** [comment]
Thanks for pointing it out! :) @asmorkalov @vpisarev

**Comment by asmorkalov** [comment]
Rendered documentation page: https://pullrequest.opencv.org/buildbot/export/pr/19419/docs/de/d25/imgproc_color_conversions.html

**Review by asmorkalov — APPROVED** [review]
Well Done! :+1: 
Please squash commits to have clear Git history in core repository after merge.

**Pull request merged**
