### PR TITLE
Added BUILD_WHITELIST

### PR DESCRIPTION
**Pull request by mshabunin**
### This pullrequest changes

adds ability to build only modules which you really need:
```
> cmake -DBUILD_LIST=dnn ../opencv && make
> ls -1 lib
libopencv_core.so
libopencv_core.so.3.3
libopencv_core.so.3.3.0
libopencv_dnn.so
libopencv_dnn.so.3.3
libopencv_dnn.so.3.3.0
libopencv_imgproc.so
libopencv_imgproc.so.3.3
libopencv_imgproc.so.3.3.0
```
**Notes:**
- modules should be named as folders: _core_, _imgproc_, ...; not _opencv_core_
- modules can be delimited by space, comma, colon, semicolon: `-DBUILD_LIST=dnn,imgcodecs`; don't forget to escape shell's special characters `-DBUILD_LIST=dnn\;imgcodecs`
- to build a _world_ module:
    - add  _imgcodecs_, _videoio_, _highgui_ to the list: `-DBUILD_LIST=dnn,imgcodecs,videoio,highgui`
    - add `-DBUILD_opencv_world=ON` option
- to build tests add a _ts_ module: `-DBUILD_LIST=dnn,ts`
- to build samples add `-DBUILD_EXAMPLES=ON` option and enable dependent modules as follows:
    - _opencv/samples/cpp_ :arrow_right:  `flann,imgcodecs,videoio,highgui,ml,video,objdetect,photo,features2d,calib3d,stitching,videostab,shape`
    - _opencv/samples/dnn_ :arrow_right:  `dnn,imgcodecs,videoio,highgui`
    - _some_module/samples_ :arrow_right: `some_module,imgcodecs,videoio,highgui`
- to build wrappers add them to the list: `-DBUILD_LIST=dnn,imgcodecs,python3,java` (_java_ has hidden dependency on _imgcodecs_, it should be fixed)
- optional dependencies (`ocv_define_module(<module> <required_deps> OPTIONAL <optional_deps>`) are not taken in account so you should enable them manually
- tested with cmake 3.7.2

### CODE REVIEW

**Comment by alalek** [comment]
Implementation looks good to me.

But current name seems confusing ("whitelist" usually should not disable anything).
There are possible changes of option name:
- `OPENCV_MODULES`
- `OPENCV_ENABLE_MODULES`
- `OPENCV_FORCE_MODULES`
- `MODULES_LIST` / `OPENCV_MODULES_LIST`
- `BUILD_MODULES` (very generic) / `OPENCV_BUILD_MODULES`
- `BUILD_WISHLIST` (non-formal)

BTW, there are internal CMake vars:`OPENCV_MODULES_BUILD` / `OPENCV_MODULES_PUBLIC`.

/cc @vpisarev

**Comment by alalek** [comment]
Ping, another variant for variable name is `OPENCV_SELECT_MODULES`

**Comment by mshabunin** [comment]
In my opinion, word _whitelist_ is quite intuitive, for example it can be defined as follows ([source](https://techterms.com/definition/whitelist)):

>A whitelist is a list of items that are granted access to a certain system or protocol. When a whitelist is used, all entities are denied access, except those included in the whitelist. The opposite of a whitelist is a blacklist, which allows access from all items, except those included the list.

I also like variants `BUILD_WISHLIST` (because it does not guarantee that chosen modules will be built) and `BUILD_ONLY` / `BUILD_ONLY_MODULES` / `BUILD_NOTHING_BUT`.

**Comment by vpisarev** [comment]
I vote for `BUILD_LIST`

**Comment by mshabunin** [comment]
Renamed.

**Comment by xiebaiyuan** [comment]
wow i vote for it too

**Comment by rosaline1995** [comment]
May I ask if it's enough to create a normal CMakeList.txt file and then run "cmake -DBUILD_LIST=mgcodecs,videoio,highgui" so that opencv will work as expected, which means, all modules are turned off except those in the options? 

But after I did so on my MacBook (with macOS 10.15.1), why did I get a warning saying that 
"CMake Warning:
  Manually-specified variables were not used by the project:"?
And then, my program ran with this line of code "std::cout << cv::getBuildInformation() << std::endl;" and still printed:
"Parallel framework:            TBB (ver 2019.0 interface 11008)

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2019.0.0 Gold [2019.0.0]
           at:                   /tmp/opencv-20190826-34514-r5q5gz/opencv-4.1.1/build/3rdparty/ippicv/ippicv_mac/icv
    Intel IPP IW:                sources (2019.0.0)
              at:                /tmp/opencv-20190826-34514-r5q5gz/opencv-4.1.1/build/3rdparty/ippicv/ippicv_mac/iw
    Lapack:                      YES (/usr/local/opt/openblas/lib/libopenblas.dylib)
    Eigen:                       YES (ver 3.3.7)
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  OpenCL:                        YES (no extra features)
    Include path:                NO
    Link libraries:              -framework OpenCL".

I felt that it meant at least OpenCL and IPP were not turned off. Is that correct? So did I use this option in a wrong way or is it simply because cmake doesn't work well with macOS 10.15+?

Thanks!

**Pull request merged**
