### PR TITLE
test_stereomatching.cpp: validate min disparity affect on valid ROI

### PR DESCRIPTION
**Pull request by opalmirror**
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/394

This pull request _adds stereomatching tests_ to the master branch for different settings of _StereoBM::minDisparity_.

- An additional parameter, minDisparities, is expected in the StereoBM test cases under opencv_extra/testdata

- The valid disparity region of interest (ROI) for both StereoBM and StereoSGBM is calculated and validated as well.

It requires a corresponding commit in the opencv_extra repository, commit id b201581e5f7bf303df750d8d6242c74ddc703583 (which will be the subject of another pull request, opencv/opencv_extra#394, same branch name, _test_stereo_min_disparity_master_).

This pull request is a follow up to pull request #9816 which fixed issue #9783 and was suggested by @alalek (thanks again).

### CODE REVIEW

**Comment by opalmirror** [comment]
@alalek I looked at each automated build, and verified that the extra test cases were run and everything passed.

**Comment by alalek** [comment]
@opalmirror Well done! Thank you!

**Comment by opalmirror** [comment]
@alalek note the optimal merge order here is:

1. #9844 this commit to 2.4 branch (creating a new 24 branch merge commit ID)

2. #9854 and opencv/opencv_extra#394 to add testing to master branch of both opencv and extras

3. A new PR (I need to wait for 1. above to rebase it) which updates the 2.4 branch to pass tests.

So, before creating a pull request for 3. I'm waiting for 1. to happen.

**Comment by opalmirror** [comment]
@alalek I am curious when this may be merged. Not frustrated, just wondering if you have an ETM, and sending a gentle ping. Thanks! James

**Comment by opalmirror** [comment]
@alalek, thanks for the merge of #9844 to 2.4 backport branch. I've pulled that and am rebasing my backport for test to the 2.4 stable branch. When that's done (an hour or so) I'll pass along the new PR number to commit along the master branch PRs #9854 and opencv/opencv_extra#394 .

**Comment by opalmirror** [comment]
@alalek, the functional changes to backport this PR to 2.4 is now tested and filed. It is PR #9974. The optimal merge sequence is:

- opencv/opencv_extra#394 - testdata updates needed for both master and 2.4 branch
- #9854 (master) and #9974 (2.4) functional changes in any order

Thanks! I've enjoyed contributing.

**Pull request merged**
