### PR TITLE
(5.x) Merge 4.x

### PR DESCRIPTION
**Pull request by asmorkalov**
OpenCV Extra: https://github.com/opencv/opencv_extra/pull/1199

#25199 from olpipi:fix_openvino_2024_0
#25643 from cpoerschke:issue-25635-find-existing-file-tests
#25644 from DaniAffCH:blockwise-quantization
#25786 from plctlab:rvp_3rdparty
#25930 from opencv-pushbot:gitee/alalek/cmake_try_detect_feature_without_flags
#25932 from asmorkalov:as/HAL_cvtColor_aprox
#25940 from Kumataro:fix25928
#25943 from asmorkalov:as/fisheye_distrort_newk
#25952 from alexlyulkov:al/java-orb-test
#25955 from Kumataro:fix25946
#25961 from gblikas:gblikas_4.x_ts_js
#25975 from asmorkalov:as/bmp_error_check
#25978 from chacha21:cuda_stdallocator
#25979 from asmorkalov:as/custom_allocator
#25983 from stepkamipt:4.x
#25987 from AvenSun:fix-namespace
#25991 from MaximSmolskiy:improve-corners-matching-in-ChessBoardDetector-NeighborsFinder-findCornerNeighbor

Previous "Merge 4.x": #25953

```
ci_branch=pr25998
```

### CODE REVIEW

**Comment by asmorkalov** [comment]
@fengyuentau Could you take a look on the patch? I see test failure in DNN after merge of block quantization:
```
2024-08-06T11:10:23.7211780Z [ RUN      ] Test_ONNX_conformance.Layer_Test/test_dequantizelinear_blocked_OCV_CPU, where GetParam() = (test_dequantizelinear_blocked, OCV/CPU)
2024-08-06T11:10:23.7213089Z Exception during net.forward() call!
2024-08-06T11:10:23.7213718Z unknown file: Failure
2024-08-06T11:10:23.7217903Z C++ exception with description "OpenCV(5.0.0-pre) /home/ci/opencv/modules/dnn/src/int8layers/quantization_utils.cpp:44: error: (-2:Unspecified error) in function 'void cv::dnn::block_repeat(cv::InputArray, const MatShape&, int, int, cv::OutputArray)'
2024-08-06T11:10:23.7220016Z > Axis out of range:
2024-08-06T11:10:23.7220568Z >     'axis >= 0 && axis < src.dims()'
2024-08-06T11:10:23.7221166Z > where
2024-08-06T11:10:23.7221636Z >     'axis' is 1
2024-08-06T11:10:23.7222157Z " thrown in the test body.
2024-08-06T11:10:23.7223682Z [  FAILED  ] Test_ONNX_conformance.Layer_Test/test_dequantizelinear_blocked_OCV_CPU, where GetParam() = (test_dequantizelinear_blocked, OCV/CPU) (1 ms)
```

**Comment by asmorkalov** [comment]
The mentioned tests are disabled for new and will be fixed with dedicated PR.

**Comment by opencv-alalek** [comment]
DNN tests on Linux32 has been crashed. Somewhere since this weekly build: https://pullrequest.opencv.org/buildbot/builders/5_x_noOCL-lin32/builds/100632

**Review by opencv-alalek — APPROVED** [review]

**Comment by fengyuentau** [comment]
> DNN tests on Linux32 are crashed. Somewhere since this weekly build: https://pullrequest.opencv.org/buildbot/builders/5_x_noOCL-lin32/builds/100632

Looks like memory leaks somewhere in einsum layer.

```
[ RUN      ] Layer_Einsum_Test.Accuracy_01D/2, where GetParam() = ({}, { 1 }, ",i->i")
*** longjmp causes uninitialized stack frame ***: /build/5_x_noOCL-lin32/build/bin/opencv_test_dnn terminated
======= Backtrace: =========
/lib/i386-linux-gnu/libc.so.6(+0x67387)[0xf67aa387]
```

**Review by fengyuentau — APPROVED** [review]

**Comment by asmorkalov** [comment]
Reproduced with my jetson tk1 and submitted bug: https://github.com/opencv/opencv/issues/26008

**Pull request merged**
