### PR TITLE
Fix upper bound for number of labels in Grana and Wu algorithms

### LINKED ISSUE #7607: LabelingGrana: Incorrect upper bound for the number of components
##### System information (version)

- OpenCV => master
- Operating System / Platform => OSX 10.12.1
- Compiler => Apple LLVM version 8.0.0 (clang-800.0.42.1)

##### Detailed description

New implemented algorithm LablelingGrana has incorrect upper bound for the number of components. And now it's default algorithm for this common case of usage:

   ```.cpp
cv::connectedComponents(image, labels);
   ```

This cause an BAD_ACCESS issue.

##### Steps to reproduce

Here is an example code that may reproduce an issue.
Here number of components is ROWS * COLS / 3,
But in [implementation](https://github.com/sokian/opencv/blob/master/modules/imgproc/src/connectedcomponents.cpp#L351-L353) it's ROWS * COLS / 4.

   ```.cpp
#include <iostream>
#include <opencv2/imgproc.hpp>

const int ROWS = 1;
const int COLS = 500;
int sum = 0;

void testConnectedComponents() {
    cv::Mat img(cv::Size(COLS, ROWS), CV_8U);
    for (int i = 0; i < COLS * ROWS; i += 3) {
        img.data[i] = 1;
    }
    cv::Mat lab;
    sum += cv::connectedComponents(img, lab);
}

int main() {
    int t = 1000000;
    for (int i = 0; i < t; ++i) {
        testConnectedComponents();
    }
    std::cerr << "Sum: " << sum << std::endl;
    return 0;
}

   ```

##### Solution

And, of course, it can be replaced by upper bound from LabelingWu algorithm
[link to commit](https://github.com/sokian/opencv/commit/b2a54ea614916becefdb02ae555401a842eb0df5)

### PR DESCRIPTION
**Pull request by sokian**
### This pullrequest changes

resolves #7607
Fix upper bound for the maximimum number of labels in LabelingGrana.

…Components computation

### CODE REVIEW

**Comment by prittt** [comment]
Hi @sokian, 
thank you very much for your contribution but I think that the upper bound for the maximum number of labels in LabelingGrana that you have defined is too big. I think that: 

`const size_t Plength = (h+1)*(w+1)/4 + 1;`

is absolutely enough!! I will explain it in the following with some examples.

First of all it is important to highlight that Grana’s algorithm treats only 8-way connectivity. So, for example, considering a binary image of 6x6 some of the worst cases (i.e. in which the maximum number of labels will be generated) are given by configurations reported in figures 1, 2, 3 and 4. In that cases the maximum number of labels is given by the following formula:

(h*w)/4 + 1   (1)

one label for every 2x2 block + one label for the background. 

Now, if we consider the case of images with odd number of columns, rows or both (6x5 or 5x6 or 5x5) some examples of the worst cases are the ones presented in figures 5, 6, 7. In such cases, the formula (1) may fails because some of 2x2 blocks are “incomplete”. In these cases, just adding one to the matrix width and height (i.e h+1 and w+1 in the general formula above) we solve the issue obtaining an effective general upper bound. 

<table border="0">
<tr>
 <td>figure1</td>
 <td>figure2</td>
 <td>figure3</td>
</tr>
<tr>
<td>Figure 1</td>
<td>Figure 2</td>
<td>Figure 3</td>
</tr>
</table>

<table border="0">
<tr>
 <td>figure4</td>
 <td>figure5</td>
 <td>figure6</td>
</tr>
<tr>
<td>Figure 4</td>
<td>Figure 5</td>
<td>Figure 6</td>
</tr>
</table>

<table border="0">
<tr>
 <td>figure7</td>
</tr>
<tr>
<td>Figure 7</td>
</tr>
</table>

**Comment by sokian** [comment]
Hi @prittt,

Oh, I see, if this algorithm will be used only for 8-connectivity case, then there should be an Assert
```.cpp
CV_Assert(connectivity == 8);
```
But now it has Assert:
```.cpp
CV_Assert(connectivity == 8 || connectivity == 4);
```

And, of course, I agree with you for upper bound in 8-connectivity case, it's obvious right (thanks for such beautiful explanation with example images).

**Comment by sovrasov** [comment]
@sokian could you commit your test from the issue too?

**Comment by vpisarev** [comment]
There is another PR with complete rewrite of connectedComponents pending. Let's merge that one first, and then, if this one is still relevant, it should be updated.

**Comment by vpisarev** [comment]
ok, let's close this one for now. please, reopen if it's still relevant

**Pull request closed without merging**
