### PR TITLE
Enable Matx & Vec pointing to external datasource

### PR DESCRIPTION
**Pull request by Sahloul**
cv::Matx and cv::Vec are very helpful, especially their utility functions.
But sometimes it is troublesome to copy the data back and forth just to use such utilities.
If Matx/Vec power can be applied to external data and manipulate it in place, that would be great!

### This pullrequest changes
- Introduces new Matx constructor that can point to external data-source (defaults `copyData` to `true` for backwards compatibility)
- Utilizes the new Matx constructor to initialize the Vec similarly
- Enables Vec to point to another Vec
- Adds new Matx constructor to copy (or point to) another Matx
- Provides unit tests for all the above functionalities

With this patch, Matx/Vec keeps their static-allocation speed, remains backward compatible, and yet, can manipulate data inplace 😄 😄

### CODE REVIEW

**Comment by alalek** [comment]
Could you add test for this functionality? Probably it will not compile at all.

**Comment by Sahloul** [comment]
@alalek How about now ;)

**Comment by alalek** [comment]
This will not pass ABI check.

cv::Matx is fast alternative for cv::Mat. cv::Matx should not use additional pointer - cv::Matx objects processing can be optimized very well in this case (cv::Mat works via pointer to data).
So there is no reason to duplicate existed functionality.

**Comment by Sahloul** [comment]
@alalek Well, I believe since the static data is still used, it should remain optimized the same way. Further, there are other concerns:
- When an argument is declared as `Vec3d`, the size and type is checked, `Mat` is not.
- Performing some operations (e.g. `a.cross(b)`) requires using these smaller types. But copying the data again to a `Mat` or other container is not straightforward.
- Even when we copy data back and forth, using `copyTo` all over the code is not ideal since it keeps checking for the dimensions, and many times, using `reshape` in conjugation is needed. `std::copy` is more low-level and there does not seem any good container offering data integrity and ease of use.

The hope it to find a clean way to manipulate data while reducing the complication of casting, reshaping, copying, and most of all, declarative types indicating dimension and type.

**Comment by Sahloul** [comment]
There is no need for this PR!
I got convinced by [the comment here](https://github.com/opencv/opencv/pull/8381#issuecomment-286393899).

**Pull request closed without merging**
