### PR TITLE
Adding Official OpenCV course link

### PR DESCRIPTION
**Pull request by spmallick**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@spmallick Are the courses designed for 3.4 branch too? Could you rebase the patch to 3.4 and re-target existing PR to 3.4? 3.4 is merged to master regularly and the link will be visible in documentation for both branches.

**Comment by dkurt** [comment]
Do we really need to have subdomains in the list while there is "Homepage: https://opencv.org"?

**Comment by spmallick** [comment]
> @spmallick Are the courses designed for 3.4 branch too? Could you rebase the patch to 3.4 and re-target existing PR to 3.4? 3.4 is merged to master regularly and the link will be visible in documentation for both branches.

We have not tested it extensively for OpenCV 3.4, so I do not want to put it on that branch.

**Comment by spmallick** [comment]
> Do we really need to have subdomains in the list while there is "Homepage: https://opencv.org"?

Currently, courses are our only source of revenue other than help from Intel, GSOC, Microsoft. So, it will really help to have the link at a few different places.

**Comment by dkurt** [comment]
@spmallick, maybe we can at least structure it in this way?

* Homepage: https://opencv.org
  * Courses: https://opencv.org/courses
* Docs: https://docs.opencv.org/master/
* Q&A forum: http://answers.opencv.org
* Issue tracking: https://github.com/opencv/opencv/issues

**Comment by spmallick** [comment]
> @spmallick, maybe we can at least structure it in this way?
> 
> * Homepage: https://opencv.org
>   
>   * Courses: https://opencv.org/courses
> * Docs: https://docs.opencv.org/master/
> * Q&A forum: http://answers.opencv.org
> * Issue tracking: https://github.com/opencv/opencv/issues

Perfect.

**Comment by spmallick** [comment]
I have recommitted with you changes and squashed previous commit.

**Pull request merged**
