### PR TITLE
Move background subtraction python tutorial, set references in video subfolder

### PR DESCRIPTION
**Pull request by mehlukas**
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/2120

relates #5673

This PR strives to clean up the video folder of the OpenCV-Python tutorials.

First, it removes the [background subtraction tutorial](https://docs.opencv.org/3.4/db/d5c/tutorial_py_bg_subtraction.html), which contains documentation on `BackgroundSubtractorMOG`, `BackgroundSubtractorMOG2` and `BackgroundSubtractorGMG`.
This is because
* `BackgroundSubtractorMOG` and `BackgroundSubtractorGMG` are `bgsegm` algorithms and belong into the opencv_contrib documentation (They are added [here](https://github.com/opencv/opencv_contrib/pull/2120))
* `BackgroundSubtractorMOG2` is already covered in the [tutorial on background subtraction](https://docs.opencv.org/3.4/d1/dc5/tutorial_background_subtraction.html), which is better and conforming to the [Documentation improvement plan](https://github.com/opencv/opencv/wiki/Documentation-improvement-plan).

Then, since all content in the OpenCV-Python tutorials / video folder is moved, set this reference to the OpenCV Tutorial / video folder.

### This pullrequest changes

* move the [background subtraction tutorial](https://docs.opencv.org/3.4/db/d5c/tutorial_py_bg_subtraction.html) to opencv_contrib (see [PR](https://github.com/opencv/opencv_contrib/pull/2120)), remove `BackgroundSubtractorMOG2` part
* since the three tutorials in the OpenCV-Python tutorials / video folder are now all moved, add a message for moved content and switch the references to the central OpenCV-Tutorial section

```
opencv_contrib=3.4-addbgsegm
```

### CODE REVIEW

**Comment by alalek** [comment]
MOG2 is [in `opencv` repository](https://github.com/opencv/opencv/blob/3.4.6/modules/video/include/opencv2/video/background_segm.hpp).
MOG has been moved into `opencv_contrib` as old algorithm which is kept for comparison/research reasons only.

I believe we can keep this tutorial in OpenCV repository.

**Comment by mehlukas** [comment]
Yes, you are right, I missed that. In the [new tutorial](https://docs.opencv.org/3.4/d1/dc5/tutorial_background_subtraction.html), MOG2 is also presented.
My proposal would be to still go forward with this PR, since the tutorial content is still covered in the new tutorial and to remove the MOG2 part from the python tutorial in [this PR](https://github.com/opencv/opencv_contrib/pull/2120).
What do you think?

**Comment by mehlukas** [comment]
I updated the description above for clarification.

**Comment by alalek** [comment]
Sound good.
It would be nice to add cross-link from opencv_contrib MOG to MOG2 tutorial in OpenCV.

**Comment by mehlukas** [comment]
Yes, that's a good idea. I added it [here](https://github.com/opencv/opencv_contrib/pull/2120)

**Pull request merged**
