### PR TITLE
Update test_fitellipse.cpp resolving #10270

### PR DESCRIPTION
**Pull request by Samsomyajit**
Resolves:  #10270

PULL REQUEST CHANGES:
It seems the ```fitEllipseDirect(pts)``` should have worked but I am using ```fitEllipseAMS(pts)``` in its place I think that will solve our problem. with respect to PR #9923

### CODE REVIEW

**Comment by asmorkalov** [comment]
@Samsomyajit The patch replaces function for test in test code, but does not resolve the original issue.

**Comment by Samsomyajit** [comment]
Yeah I am working on it @asmorkalov

**Comment by asmorkalov** [comment]
@Samsomyajit any progress on this?

**Comment by Samsomyajit** [comment]
@asmorkalov  As per test_precomp.hpp : ```CV_EXPORTS_W RotatedRect fitEllipse( InputArray points );``` :  The function calculates the ellipse that fits a set of 2D points. It returns the rotated rectangle in which the ellipse is inscribed. The Approximate Mean Square (AMS) proposed by @cite Taubin1991 is used. Now I think it should work fine.

**Comment by asmorkalov** [comment]
@Samsomyajit The patch does not resolve the original issue, but just changes the function under test. It's not appropriate solution and unit tests signal about it: https://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/24912/steps/test_imgproc/logs/stdio

**Pull request closed without merging**
