### PR TITLE
accelerate bilateralFilter using NEON

### PR DESCRIPTION
**Pull request by vpisarev**
### What does this PR change?

 * Accelarate bilateral filter using NEON as same as SSE3
 * align some lines in SSE3 part

### Former #6759

### CODE REVIEW

**Comment by vpisarev** [comment]
@cuda-geek, could you please review it?

**Comment by cuda-geek** [comment]
@tomoaki0705, could you please provide the performance numbers for your version, original OpenCV and measure achieved uplift. You can use OpenCV's performance testing framework to get all the data. Please, mention the hardware you used to benchmark.

**Comment by tomoaki0705** [comment]
Test condition | SIMD version | normal 
------------ | ------------- | ------------- 
640x480, 3, CV_8UC1 |  14.26 |  11.07
640x480, 3, CV_8UC3 |  20.40 |  14.38
640x480, 3, CV_32FC1 |  22.44 |  27.08
640x480, 3, CV_32FC3 |  39.83 |  44.20
640x480, 5, CV_8UC1 |  26.64 |  22.36
640x480, 5, CV_8UC3 |  40.43 |  28.73
640x480, 5, CV_32FC1 |  37.26 |  58.98
640x480, 5, CV_32FC3 |  63.61 |  84.47
1920x1080, 3, CV_8UC1 |  64.10 |  51.78
1920x1080, 3, CV_8UC3 |  110.72 |  69.81
1920x1080, 3, CV_32FC1 |  120.91 |  142.50
1920x1080, 3, CV_32FC3 |  220.80 |  252.26
1920x1080, 5, CV_8UC1 |  131.03 |  110.64
1920x1080, 5, CV_8UC3 |  217.16 |  141.94
1920x1080, 5, CV_32FC1 |  200.28 |  312.28
1920x1080, 5, CV_32FC3 |  371.68 |  497.14

The accelerated version is b101a7f and the normal version is da69cd08db9
I picked up the mean value from the output of opencv_perf_imgproc on test TestBilateralFilter_BilateralFilter.BilateralFilter

It seems my modification is making progress on 32F version, but not on 8U version.
Hmm.., I didn't realize that.
How should I go ? should I try more to optimize, on 8U version, or shall I just remove the 8U part and commit only 32F version ?

**Comment by cuda-geek** [comment]
@tomoaki0705, any contribution that don't introduce performance degradation would be fine. So it's up to you what path to take since you are the contributor of the feature. 

If you have time and aspiration for it I would recommend you to look into the code once more in order to improve your current optimization for 8U types.

**Comment by vpisarev** [comment]
@tomoaki0705, thanks for PR! to keep things going, I'd suggest to remove 8u part for now and then we can merge it in. Then, sometimes later when you have time, you can submit another PR with accelerated 8u version

**Comment by tomoaki0705** [comment]
Test condition | SIMD version | normal 
------------ | ------------- | ------------- 
640x480, 3, CV_8UC1 | 11.15 | 11.07
640x480, 3, CV_8UC3 | 14.81 | 14.38
640x480, 3, CV_32FC1 | 23.06 | 27.08
640x480, 3, CV_32FC3 | 40.15 | 44.20
640x480, 5, CV_8UC1 | 24.24 | 22.36
640x480, 5, CV_8UC3 | 29.97 | 28.73
640x480, 5, CV_32FC1 | 35.54 | 58.98
640x480, 5, CV_32FC3 | 61.06 | 84.47
1920x1080, 3, CV_8UC1 | 49.72 | 51.78
1920x1080, 3, CV_8UC3 | 68.00 | 69.81
1920x1080, 3, CV_32FC1 | 116.37 | 142.50
1920x1080, 3, CV_32FC3 | 221.73 | 252.26
1920x1080, 5, CV_8UC1 | 111.30 | 110.64
1920x1080, 5, CV_8UC3 | 142.16 | 141.94
1920x1080, 5, CV_32FC1 | 199.02 | 312.28
1920x1080, 5, CV_32FC3 | 364.78 | 497.14

@cuda-geek , @vpisarev thank you for the comments.
I removed the 8U version and pushed again.

I'll keep digging to optimize 8U version.

**Comment by vpisarev** [comment]
thank you! :+1:

**Pull request merged**
