### PR TITLE
Update py_svm_opencv.markdown

### PR DESCRIPTION
**Pull request by MauryaRitesh**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
This patch should go into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first.
We will merge changes from 3.4 into 4.x regularly (weekly/bi-weekly).

Please:
- change "base" branch of this PR: 4.x => 3.4 (use "Edit" button near PR title)
- rebase your commits from 4.x onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/4.x`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

---

BTW, This PR is locked from maintainers updates. If you need help then please enable allow "edits by maintainers"

**Comment by MauryaRitesh** [comment]
Do I need to create all future PRs into the 3.4 base branch?

**Comment by MauryaRitesh** [comment]
@alalek I got the following list of commits after running `git rebase -i --onto upstream/3.4 upstream/4.x`.

    pick eca2d92791 fix: submodules creation and registration
    pick 82818e7324 cmake(highgui): update handling of OpenGL libraries
    pick 51e8af9e5f cmake(link): add '-Wl,--no-undefined'
    pick b304730225 dnn: fix API - explicit ctors, const methods

These are not the PRs that I have created.
Should I push the rebased commits?

**Comment by alalek** [comment]
Only your commit should be in this list.

Ensure that you have fetched upstream branches.

**Comment by alalek** [comment]
> from MauryaRitesh:patch-1

Source branch is removed (or source repository). No way to test this PR on CI.

**Pull request closed without merging**
