### PR TITLE
Adding Support for RTX64 Vision to OpenCV 3.4

### PR DESCRIPTION
**Pull request by owenmonahan**
Adding support for RTX64 Vision to OpenCV 3.4.  Primarily involves adding a new class derived from IVideoCapture to the VideoIO module.

previous PR: #13288

### CODE REVIEW

**Comment by owenmonahan** [comment]
Hi,

Is there a timeline for how long it generally takes to get feedback on a PR?  I ask simply because I am eager to get this addition approved.  Thanks!

**Comment by owenmonahan** [comment]
Thank you very much for the feedback.  Apologies for the confusion with the two PRs, I didn't mean to cause trouble.  I made a new PR, as in the original PR, you instructed us to implement IVideoCapture, instead of using the legacy code, as we were doing before.  We had to postpone doing this for a few months, so by the time I got to come back to this, I thought it would be best to start anew, especially since so much of the code and CMake was changing.  Again sorry for this, it won't happen again.

Though I understand your concerns about the maintainability of our code, going forward, we would still like to get our code into the true OpenCV repository (not just in our fork), if you are willing to allow it (once I make any and all changes/fixes you have requested).  I have attempted to keep all of our code #ifdefed out when in non-RTX64 builds of OpenCV.  Will this help to get our additions approved?

**Comment by owenmonahan** [comment]
This will be difficult for you guys to build unfortunately, @mshabunin.  You would need to have access to our SDK.  If you would like to do this, I may be able to get you guys access to it.  Let me know!

**Comment by mshabunin** [comment]
@owenmonahan , I agree with @alalek , this patch does not have value for majority of the OpenCV community and we can not maintain it. I can see that you want to add custom _VideoCapture_ backend and I propose the following approach:
* create a custom module with your backend, it is simple process - see our [coding guidelines](https://github.com/opencv/opencv/wiki/Coding_Style_Guide) for details. 
  * Take a look at the [fuzzy module](https://github.com/opencv/opencv_contrib/tree/master/modules/fuzzy) for example. 
  * You can add this module to your OpenCV build process by setting `OPENCV_EXTRA_MODULES_PATH` CMake option (it [accepts lists](https://github.com/opencv/opencv/pull/10758) too). 
  * You can limit modules being built by setting `OPENCV_BUILD_LIST` [option](https://github.com/opencv/opencv/pull/9893). 
  * Your custom build can be distributed with your SDK or as a standalone product and repository can be published on GitHub.
  * You can have a single class in you module - `cv::VideoCaptureRTX` which can be compatible with `cv::VideoCapture`.
* those little changes left in your patch after moving _VideoCapture_ backend to separate module should be rewritten in more generic manner (e.g. `#ifdef MY_PLATFORM` should be changed to `#ifdef HAVE_SOME_FEATURE`). Although, I believe it won't be needed at all, since most of options can be easily passed via CMake parameters.

**Comment by owenmonahan** [comment]
@mshabunin , okay, we will go in a different direction then.  We will either do as you suggested, or do as @alalek suggested and maintain our own OpenCV fork.  Thank you very much for the input!  Should we close this PR for now?

**Comment by mshabunin** [comment]
Let's close it for now. Feel free to reopen or create new if you come up with more generic and compact changes.

**Pull request closed without merging**
