### PR TITLE
Fix ARM builds

### PR DESCRIPTION
**Pull request by alalek**
resolves 6784

### CODE REVIEW

**Comment by alalek** [comment]
This PR is ready to review.

**Comment by tomoaki0705** [comment]
I confirmed that this PR fixes
[39 tests on perf_core](https://gist.github.com/tomoaki0705/81073b6228e259ad5eed441a715bc8b7/revisions) and [3 tests from test_calib3d](https://gist.github.com/tomoaki0705/22b550c769c40b0140a1597abb1ac8ad/revisions)

Best.

**Comment by alalek** [comment]
@tomoaki0705 Thank you!

Do you have error messages for "OCL_LogFixture_Log.Log/3" "OCL_LogFixture_Log.Log/5" "OCL_LogFixture_Log.Log/6" test failures?

**Comment by tomoaki0705** [comment]
@alalek , yes, I have it [here](https://gist.github.com/tomoaki0705/7643507e853c20c2090e043344a3036f)

Basically, it's slightly over the eps.
````
expect_min evaluates to 0.0019512200960889459,
actual_min evaluates to 0.0017863045213744044, and
eps evaluates to 9.21034049987793e-05.
```

**Comment by tomoaki0705** [comment]
resolves #6784

**Comment by vpisarev** [comment]
thanks! :+1:

**Pull request merged**
