### PR TITLE
Warnings fix on Windows.

### PR DESCRIPTION
**Pull request by asmorkalov**
Related: https://github.com/opencv/opencv/pull/24201
Warnings: https://pullrequest.opencv.org/buildbot/builders/precommit_windows64/builds/102818/steps/compile%20release/logs/warnings%20%2816%29

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by LaurentBerger** [comment]
What's about 
https://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/104634/steps/test_video/logs/tests%20summary?

**Comment by asmorkalov** [comment]
I asked alalek to upload the model to all hosts on buildbot.

**Comment by opencv-alalek** [comment]
> I asked alalek to upload the model to all hosts on buildbot.

It is already a part of opencv_extra. Extra steps are not needed.
Mistake is in the merged test code (and completely missed CI runs for merged PR)

**Comment by asmorkalov** [comment]
@opencv-alalek I fixed the issue. The PR is ready for integration.

**Review by mshabunin — APPROVED** [review]
**cc** @hanliutong (possible calib3d conflicts with refactoring projects)

**Pull request merged**
