### PR TITLE
Handle BGRA streams in GStreamer backend

### PR DESCRIPTION
**Pull request by asmorkalov**
Safer replacement for https://github.com/opencv/opencv/pull/25557
Jetson Orin provides BGRx stream in some cases.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@Liedermaus could you try the patch? I changed format priorities a bit to not break existing behavior.

**Comment by asmorkalov** [comment]
@opencv-alalek @mshabunin Could you take a look? I fixed regressions and re-order GStreamer caps options.

**Review by mshabunin — APPROVED** [review]
Overall looks good to me.

I'm wondering whether GRAY should be placed before or after Bayer. If we assume this list is sorted in order of required postprocessing, then GRAY should go before Bayer. And if we assume that color image has higher priority, than GRAY should be last.

**Comment by asmorkalov** [comment]
Color image has higher priority, IMHO.

**Pull request merged**
