### PR TITLE
Remove redundant "if" condition and unused variables in libjasper and…

### PR DESCRIPTION
**Pull request by danbey**
1. Improve and simplify if statement by reducing condition that is not needed.
2. Remove unused variables function.
3. Fix uninitialized  char array.

Signed-off-by: Dan Ben Yosef danbey@gmail.com

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
Do you have the real problem with that?

Touching 3rdparty files is a bad idea in general.
Prefer to contribute to upstream project instead.
Nobody wants to resolve conflicts with 3rdparty version upgrades in the future.

**Comment by asenyaev** [comment]
jenkins cn please retry a build

**Comment by danbey** [comment]
Sure , do you mean to contribute here : https://github.com/jasper-software/jasper , right ? 

Anyway these are not major issues so we can close this PR  ... 

On which folder can i run my static analyzer check ? all the folders other than the 3rdparty ?

**Comment by alalek** [comment]
> all the folders other than the 3rdparty

This is the right way.
For example, 3rdparty code is ignored in [Coverity scans for OpenCV](https://scan.coverity.com/projects/opencv).

Also prefer to use external system packages instead of sources from "3rdparty".

**Pull request closed without merging**
