### PR TITLE
Libraw

### PR DESCRIPTION
**Pull request by LaurentBerger**
### Pull Request Readiness Checklist

- [X] I agree to contribute to the project under Apache 2 License.
- [] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [X] There is a reference to the original bug report and related work https://github.com/opencv/opencv/issues/15269
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by LaurentBerger** [comment]
@asmorkalov 
I need to set 
-DBUILD_RAW:BOOL=ON \
-DWITH_RAW:BOOL=ON \
before build. how can i do It?

**Comment by asmorkalov** [comment]
Unfortunately, you cannot. The only way to test it with CI right now is to change defaults in CMake.

**Comment by asmorkalov** [comment]
@LaurentBerger Thanks a lot for the contribution! CI is broken right now and my colleague works on the issue right now.
We discussed the proposal on the OpenCV core team meeting and outcome is the following:
- The library integration is very useful. Agreed in general.
- LGPL license in viral. We cannot include such code into OpenCV code base. CDDL license is under review right now. I'll let you know, later.
- We propose not to put to OpenCV into 3rdparty, but use external library instance found by CMake. The library is not widely used and is kind of advanced option. I'm looking on CI options to just include in into environment (Docker) and be sure that it's built and tested regularly.

**Comment by asmorkalov** [comment]
I was able build and run OpenCV tests on Ubuntu 18.04. Couple of notes:
- `-DBUILD_LIBRAW=OFF` do not disable libraw build from 3rdparty. I want to build against of system instance of the lib.
- The library version is not detected/reported in cmake.
- There are now tests for now.

**Comment by LaurentBerger** [comment]
OK nice

Now I can build on windows opencv with libraw as an external lib(not in 3rdparty lib). I can push and remove all libraw file. I make some change in loadsave.cpp. Now opencv can read raw files but opencv try first libtiffreader

**Comment by asmorkalov** [comment]
With Ubuntu 18.04 and default apt package (ver 0.18.8) I see the following build error:
```
[ 36%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/stereosgbm.cpp.o
/home/alexander/Projects/OpenCV/opencv-master/modules/imgcodecs/src/grfmt_raw.cpp: In member function ‘virtual bool cv::LibRawDecoder::checkSignature(const String&) const’:
/home/alexander/Projects/OpenCV/opencv-master/modules/imgcodecs/src/grfmt_raw.cpp:76:47: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
         ((LibRaw*)rawProcessor)->open_buffer((&signature[0]), signature.length());
                                              ~^~~~~~~~~~~~~~
In file included from /home/alexander/Projects/OpenCV/opencv-master/modules/imgcodecs/src/grfmt_raw.cpp:51:0:
/usr/include/libraw/libraw.h:132:33: note:   initializing argument 1 of ‘int LibRaw::open_buffer(void*, size_t)’
     int                         open_buffer(void *buffer, size_t size);
                                 ^~~~~~~~~~~
modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/build.make:285: recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_raw.cpp.o' failed
make[2]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/grfmt_raw.cpp.o] Error 1
make[2]: *** Ожидание завершения заданий…
[ 36%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/triangulate.cpp.o
CMakeFiles/Makefile2:2379: recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all' failed
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
```

**Comment by asmorkalov** [comment]
The same with ver 0.19.5 in Ubuntu 20.04.

**Comment by asmorkalov** [comment]
https://github.com/opencv-infrastructure/opencv-gha-dockerfile/pull/16

**Comment by asmorkalov** [comment]
https://github.com/opencv/ci-gha-workflow/pull/92/

**Comment by LaurentBerger** [comment]
> With Ubuntu 18.04 and default apt package (ver 0.18.8) I see the following build error:

I remove code. libraw does not check signature using file header. 
When libtiff check signature sometimes it is true but readheader failed, sometimes readheader is true but tiff failed to read file. Code in loadsave.cpp becomes complicated because libtiff failed to read raw files.

**Comment by asmorkalov** [comment]
@LaurentBerger Thanks a lot for accuracy test. OpenCV CI system tests OpenCV and OpenCV Extra patches together, if they are propose with the same person and the same branch name. I added libraw to Desktop Ubuntu configuration and there is test failure:
```
2023-04-13T14:50:25.4765816Z [ RUN      ] Imgcodecs_Raw.decode_raw
2023-04-13T14:50:25.4767743Z [ WARN:0@4.310] global loadsave.cpp:247 findDecoder imread_('/home/ci/opencv_extra/testdata/highgui/../cv/rawfiles/RAW_CANON_PRO70_SRGB.CRW'): can't open/read file: check file path/integrity
2023-04-13T14:50:25.4770696Z imread_('/home/ci/opencv_extra/testdata/highgui/../cv/rawfiles/RAW_CANON_PRO70_SRGB.CRW'): can't read header: OpenCV(4.7.0-dev) /home/ci/opencv/modules/imgcodecs/src/grfmt_raw.cpp:101: error: (-213:The function/feature is not implemented) Input/output error in function 'readHeader'
2023-04-13T14:50:25.4771991Z 
2023-04-13T14:50:25.4772434Z /home/ci/opencv/modules/imgcodecs/test/test_raw.cpp:15: Failure
2023-04-13T14:50:25.4773198Z Value of: img1.empty()
2023-04-13T14:50:25.4773789Z   Actual: true
2023-04-13T14:50:25.4774363Z Expected: false
2023-04-13T14:50:25.4775033Z [  FAILED  ] Imgcodecs_Raw.decode_raw (0 ms)
2023-04-13T14:50:25.4776099Z [----------] 1 test from Imgcodecs_Raw (0 ms total)
```
Please re-create PR to extra repo with the same branch name as this PR.

**Comment by LaurentBerger** [comment]
@asmorkalov I don't understand this warnings https://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/103681/steps/patch%20size%20opencv_extra
My patch size is 90.5 kbytes https://github.com/opencv/opencv_extra/pull/1056/files

**Pull request closed without merging**
