### PR TITLE
Updates grfmt_gdal.cpp

### PR DESCRIPTION
**Pull request by sturkmen72**
#6567
additional fix to #7064

### CODE REVIEW

**Comment by alalek** [comment]
@sturkmen72 Thank you!
Could you share some small image for this (for regression test)?

**Comment by sturkmen72** [comment]
i have no valid image but a code snippet like https://github.com/opencv/opencv/blob/master/samples/cpp/train_HOG.cpp#L72-L81
should work without crash with this fix.

**Comment by sturkmen72** [comment]
indeed according the documentation i think `GdalDecoder ` should be active only when `imread( files[i],IMREAD_LOAD_GDAL)`

**Comment by alalek** [comment]
:+1:

**Pull request merged**
