### PR TITLE
Python: Enable opencv to act as an installable module

### PR DESCRIPTION
**Pull request by smokey42**
- introduce a setup.py file to enable pip installs
- compile opencv statically into the loadable module
  so that each virtualenv can have its own
  opencv installation.

What works:
- pip install git+https://github.com/stylight/opencv#egg=opencv into a virtualenv
  this enables other modules to specify opencv as a dependency and get it resolved
  automatically (given the build dependencies are met)

Known Bugs:
- "pip uninstall opencv" fails to remove cv2.so
- uploading to pypi not tested and probably doesn't work yet.
- missing build dependencies are probably not handled gracefully.

### CODE REVIEW

**Comment by fbender** [comment]
@smokey42 Did you manage to create an updated PR, yet? Some review comments might be outdated now, though -- is OpenCV now compatible with Python v3?

**Comment by smokey42** [comment]
@fbender No, we did not create the PR. We also stopped using opencv years ago, so I can't help you here. Sorry.

**Comment by fbender** [comment]
@smokey42 may I ask what you str using instead?

**Comment by smokey42** [comment]
Nothing. The use case disappeared. For content aware cropping we use something far simpler based on Pillow now, the rest we ditched completely.

**Pull request closed without merging**
