### PR TITLE
export Python signatures information

### PR DESCRIPTION
**Pull request by alalek**
related #9260

### CODE REVIEW

**Comment by Cartucho** [comment]
@alalek I get the following error:
image

**Comment by alalek** [comment]
Looks like you observe conflict with this patch: #8895
Did you rebase on latest OpenCV master?
I don't observe similar issue on OpenCV builders.

**Comment by Cartucho** [comment]
Yes, you are right, now it worked

**Comment by Cartucho** [comment]
So the generated json file contains the functions with the name, ret and args:
image

But now we still need to add the signatures to the generated docs, right?

**Comment by alalek** [comment]
I have some experiments with adoption here: https://github.com/alalek/opencv/commits/pr9260_r (please check [comment](https://github.com/opencv/opencv/pull/9260#issuecomment-327382462) )

**Comment by alalek** [comment]
JSON file is a dictionary with:
- key: C++ function/method name
- value: array of function "variants" (overloads):
  - element: dictionary of
    - arg: function/method arguments (there is no "self" for methods, probably we should add it later)
    - dst: rhs expression (output results)
    - name: Python name (useful for handling of CV_WRAP_AS).

**Comment by vpisarev** [comment]
cool! :+1:

**Pull request merged**
