### PR TITLE
RFC: videoio: remove cap_libv4l in favour of cap_v4l

### LINKED ISSUE #4563: libv4l capturing backend diverged from v4l backend
Transferred from http://code.opencv.org/issues/3006

```
|| Hans Meine on 2013-05-03 10:57
|| Priority: Normal
|| Affected: branch 'master' (2.4.9)
|| Category: highgui-camera
|| Tracker: Bug
|| Difficulty: None
|| PR: 
|| Platform: None / None
```
## libv4l capturing backend diverged from v4l backend

```
Currently, we have cap_v4l.cpp and cap_libv4l.cpp with a lot of duplicated code, but also some unwanted differences.

For instance, the recent addition of CV_CAP_PROP_POS_MSEC support to the v4l backend was not merged to the libv4l backend.

Do we really want to maintain both completely separately?
```

### PR DESCRIPTION
**Pull request by paroj**
cap_libv4l depends on an external library (libv4l) yet is still larger(1966 loc vs 1822 loc).
It was initially introduced copy pasting cap_v4l in order to offload various color conversions to libv4l.
However nowadays we handle most of the needed color conversions inside OpenCV. Our own implementation is better tested and (probably) also better performing. (as it can optionally leverage IPP/ OCL)

Currently cap_v4l is better maintained and generally the code is in better shape. There is however an API difference in getting unconverted frames:
* on cap_libv4l one need to set `CV_CAP_MODE_GRAY=1` or
`CV_CAP_MODE_YUYV=1`
* on cap_v4l one needs to set `CV_CAP_PROP_CONVERT_RGB=0`

the latter is more flexible though as it also allows accessing undecoded JPEG images.

fixes #4563

### CODE REVIEW

**Comment by vpisarev** [comment]
@paroj, thanks for the patch! Let's postpone such a radical solution till 3.2 perhaps. For now it's always possible to use WITH_LIBV4L=OFF option

**Comment by alalek** [comment]
This patch works for me.

**Comment by paroj** [comment]
how about merging now? there are still PRs coming for libv4l.

**Comment by mshabunin** [comment]
Transferred to new PR

**Pull request closed without merging**
