### PR TITLE
[WIP] Support ROI + UMat in own::Mat

### PR DESCRIPTION
**Pull request by andrey-golubev**
### This pullrequest

- Adds ROI-related fields to `cv::gapi::own::Mat` and enables support of ROIs outputs (also inputs) for OCL backend (UMat use case)
- Adds tests for new behavior (unit test + backend-level)

---
**Problem**: if user passes ROI `cv::Mat` to G-API, in case of OCL backend we lose track of original data source when doing `own::Mat -> cv::Mat -> cv::UMat` conversion and this results in a failure at checking that populated UMat data equals original cv::Mat data (according to assert message this means that output was reallocated internally and graph execution result was written into that new memory)

**Solution**: the most obvious would be to propagate ROI-related fields through `cv::gapi::own::Mat` directly to internally (re-)constructed `cv::Mat`. Better ideas are appreciated

```
build_gapi_standalone:Linux x64=ade-0.1.1d
build_gapi_standalone:Win64=ade-0.1.1d
build_gapi_standalone:Mac=ade-0.1.1d
build_gapi_standalone:Linux x64 Debug=ade-0.1.1d
```

### CODE REVIEW

**Comment by andrey-golubev** [comment]
@anton-potapov @dmatveev please look at the patch. This is still WIP: I need to make sure that we actually write into the wrong memory in the described case

**Comment by asmorkalov** [comment]
@andrey-golubev @dmatveev Is the patch still relevant? Please update it or close PR, if it's not relevant any more.

**Comment by asmorkalov** [comment]
@andrey-golubev @dmatveev Do you have a chance to finish the PR? The PR is still in WIP stage and has several merge conflicts. Please close it, if you do not plan to finish work in reasonable time.

**Comment by andrey-golubev** [comment]
@asmorkalov thanks for being meticulous in tracking OpenCV's issues! I plan to close it in couple of days, current solution doesn't seem feasible right now but I aim to create an issue out of this PR (need to verify the issue still exists).

**Comment by dmatveev** [comment]
@andrey-golubev thanks! please handle it and mention this PR attemt in that issue description. So far it doesn't gate any known G-API cases.

**Comment by andrey-golubev** [comment]
@dmatveev indeed, current stuff seems to live just fine. My only concern is that this might "fire" when someone decides to split the image into 2 parts with one part being handled by Fluid backend and the other - by OCL

Anyhow, I plan to look at this one last time to check if I got correct impression of the situation, submit an issue for later resolution and mention this PR there

**Comment by asmorkalov** [comment]
@andrey-golubev @dmatveev do you have conclusion on the patch? Can we close it?

**Comment by asmorkalov** [comment]
@andrey-golubev @dmatveev friendly reminder. The PR is in WIP stage for more than half of year.

**Comment by andrey-golubev** [comment]
opened a corresponding issue, so closing this PR

**Pull request closed without merging**
