### PR TITLE
Incorrect Naming

### LINKED ISSUE #9544: cannot open source file "dynlink_nvcuvid.h"	opencv_cudacodec
##### System information (version)
- OpenCV => : 3.3:
- Operating System / Platform => : Windows 10 , 64 Bit:
- Compiler => :Visual Studio 2015:

## i meet two bugs:

**1.first enable preformance test cause error same as https://github.com/opencv/opencv/issues/6716**

**2.cannot open source file "dynlink_nvcuvid.h"**
 ```
Severity Code Description Project File Line Suppression State
Error C1083
Cannot open include file: 'dynlink_nvcuvid.h': No such file or directory
opencv_cudacodec	opencv-master\modules\cudacodec\src\precomp.hpp	59	
 ```
## cmake configure output
 ```
CUDA detected: 8.0
CUDA NVCC target flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-D_FORCE_INLINES
  ```
General configuration for OpenCV 3.3.0-dev 

  Extra modules:
    Location (extra):            opencv_contrib-master/modules
 ```
  Platform:
    Timestamp:                   2017-09-02T15:37:49Z
    Host:                        Windows 10.0.15063 AMD64
    CMake:                       3.9.1
    CMake generator:             Visual Studio 14 2015 Win64
    CMake build tool:            C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe
    MSVC:                        1900
  ```
```
  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_2
      SSE4_2 (3 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
```
```
    Use Lapack:                  NO
    Use Eigen:                   NO
    Use Cuda:                    YES (ver 8.0)
    Use OpenCL:                  YES
    Use OpenVX:                  NO
    Use custom HAL:              NO
  ```
```
  NVIDIA CUDA
    Use CUFFT:                   YES
    Use CUBLAS:                  YES
    USE NVCUVID:                 YES
    NVIDIA GPU arch:             50 52
    NVIDIA PTX archs:
    Use fast math:               NO
 ```
```
  OpenCL:                        <Dynamic loading of OpenCL library>
    Include path:               opencv-master/3rdparty/include/opencl/1.2
    Use AMDFFT:                  NO
    Use AMDBLAS:                 NO


  Tests and samples:
    Tests:                       NO
    Performance tests:           NO
    C/C++ Examples:              NO

Configuring done
Generating done

 ```

### PR DESCRIPTION
**Pull request by whizzzkid**
Resolved #9544 

### This pullrequest changes
There is a filename error because of which the build fails.

### CODE REVIEW

**Comment by alalek** [comment]
`dynlink_nvcuvid.h` is correct too, but not for current versions of CUDA SDK.
I believe there is should be version check and two includes.
Fixes must be robust and they should not break existed functionality.

**Comment by lucaspbordignon** [comment]
@whizzzkid adding the following piece of code may solve the version problem:
```
#ifdef HAVE_NVCUVID
    #include <cuda.h>
    #if CUDA_VERSION >= 9000
        #include <dynlink_nvcuvid.h>
    #else
        #include <nvcuvid.h>
    #endif
```

I'm almost certain that this is not the best approach, mainly because of the ```#include <cuda.h>``` , but is an idea :)

**Comment by whizzzkid** [comment]
Thanks @lucaspbordignon this was what I was looking for. I am not a c/c++ guy and these pre-processor rules were giving me a hard time. 

Now this should fix builds for cuda 8 and keep the builds consistent with cuda 9.

@alalek please review again.

**Comment by alalek** [comment]
Thank you! Looks good to me :+1:

In the future please create merge requests from separate branch instead of "master".

**Pull request merged**
