### PR TITLE
Universal intrinsics implementation with RISC-V vector extension

### PR DESCRIPTION
**Pull request by joy2myself**
This PR From GSoC Project "Optimize OpenCV for RISC-V"

### Project introduction
The main objective of the project is adding implementation of OpenCV wide universal intrinsics for RISC-V vector in OpenCV Hardware Acceleration Layer (HAL).
This PR is now working in progress.

### Two previous PRs related to the project
Following two previous PRs mainly provided the toolchain files for cross-compiling OpenCV with target riscv64 on Linux platform. The first PR is with Clang and the second is with riscv-gnu-toolchain.
https://github.com/opencv/opencv/pull/17922
https://github.com/opencv/opencv/pull/18227

### Main contents of my work
Added toolchain file for target `riscv64-clang`.
Added toolchain file for target `riscv64-gcc`.
Added universal intrinsics implementation with RISC-V vector extension.
Added some native intrinsics in C++ that are unsupported by compiler temporarily.

### Current progress
Universal intrinsics implementation with RISC-V vector extension is almost done. But the way universal intrinsic vector types are declared right now needs some changes. See the following issue for specific reasons.
https://github.com/riscv/riscv-gnu-toolchain/issues/701
Use empty functions instead of missing native intrinsics temporarily.

### Near future work
Change the universal intrinsic vector types with in-memory vectors and add extra loads/stores to get functional code.
Implement missing native intrinsics in C++ which are now still empty functions.

### Long future work
Performance improvements. Maybe the current universal intrinsic framework need some change to fit scalable vector architecture.
RISC-V vector extension and rvv-intrinsics are still in the process of development. The compiler support is not completely ready at present and there may be changes in riscv-v-spec and rvv-intrinsics in the future. Therefore, this implementation needs to be maintained continuously according to the development of RISC-V.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
```
/home/alexander/Projects/riscv/opencv/modules/core/test/test_intrin_utils.hpp:339:46: error: no matching function for call to 'v_reinterpret_as_f64(cv::hal_baseline::v_float32x4&)'
  339 |         v_float64 vf64 = v_reinterpret_as_f64(r1); out.a.clear(); v_store((double*)out.a.d, vf64); EXPECT_EQ(data.a, out.a);
      | 
```

**Comment by asmorkalov** [comment]
```
In file included from /home/alexander/Projects/riscv/opencv/modules/core/test/test_intrin128.simd.hpp:19,
                 from /home/alexander/Projects/riscv/opencv/modules/core/test/test_intrin.cpp:6:
/home/alexander/Projects/riscv/opencv/modules/core/test/test_intrin_utils.hpp: In instantiation of 'opencv_test::hal::intrin128::cpu_baseline::TheTest<R>& opencv_test::hal::intrin128::cpu_baseline::TheTest<R>::test_popcount() [with R = cv::hal_baseline::v_int8x16]':
/home/alexander/Projects/riscv/opencv/modules/core/test/test_intrin_utils.hpp:1641:24:   required from here
/home/alexander/Projects/riscv/opencv/modules/core/test/test_intrin_utils.hpp:829:35: error: conversion from 'cv::hal_baseline::v_int8x16' to non-scalar type 'opencv_test::hal::intrin128::cpu_baseline::Data<cv::hal_baseline::v_uint8x16>' requested
  829 |         Data<Ru> resB = v_popcount(a);
      |                         ~~~~~~~~~~^~~
```

**Comment by vpisarev** [comment]
:+1:

**Comment by vpisarev** [comment]
@asmorkalov, you requested some changes. Are you happy with what has been done. I tested this PR and from side I do not see any showstoppers, except for the two:

@joy2myself:
1. please, squash the commits into one; I've sent you the instructions by e-mail.
2. please, copy our checklist about licenses and other conditions from another pull request into the first message of this pull request and click the checkboxes. Without your "written" agreement with our conditions that we put into each pull request we cannot integrate your patch

**Comment by joy2myself** [comment]
Hi dear @asmorkalov and @vpisarev ,

I reverted some unnessesary commits before squash. I tested the current version and it works as well as before. Even so, I recommend that you test it again before merging to make sure there are no problems.

**Pull request merged**
