### PR TITLE
CUDA: add Ada Lovelace and Hopper CC

### PR DESCRIPTION
**Pull request by cudawarped**
Update automatic CC detection script with CC introduced in CUDA SDK 11.8
- Ada Lovelace has CC 8.9
- Hopper has CC 9.0

cc @tomoaki0705

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by tomoaki0705** [comment]
Thank you for your contribution.

Does this PR goes to 4.x ?
Why not following the ordinary procedure ? (first to 3.4 branch and then propagate to master)

**Comment by cudawarped** [comment]
> Does this PR goes to 4.x ?
> Why not following the ordinary procedure ? (first to 3.4 branch and then propagate to master)

I have now pushed the changes from the 3.4 branch.  The PR title still states opencv:4.x do I need to close this and open a new PR to the correct branch?

**Comment by tomoaki0705** [comment]
Please DON'T close the branch but follow the correct procedure.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by asmorkalov** [comment]
The branch is still based on 3.4. Please rebase it on top of 4.x.

**Review by asmorkalov — APPROVED** [review]
:+1: No chance to check with real GPU, but build is ok. Tested with Ubuntu 20.04 and CUDA 12.

**Pull request merged**
