### PR TITLE
Add some functions to OpenCV JS API

### PR DESCRIPTION
**Pull request by sturkmen72**
Closes : #20133

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
build_image:Docs=docs-js
Xbuild_image:Custom=javascript
Xbuild_image:Custom=javascript-simd
Xbuild_image:Custom=javascript-simd:3.1.64
build_image:Custom=javascript:3.1.64
buildworker:Custom=linux-4
```

### CODE REVIEW

**Comment by sturkmen72** [comment]
The functions added
```
applyColorMap
approxPolyN
arrowedLine
blendLinear
boxPoints
clipLine
drawMarker
fitEllipseAMS
fitEllipseDirect
HuMoments
invertAffineTransform
minEnclosingTriangle
preCornerDetect
sqrBoxFilter
stackBlur
```

The functions below are still unavailable
```
accumulate 
accumulateProduct
accumulateSquare
accumulateWeighted
buildPyramid
convertMaps
cornerEigenValsAndVecs
cornerSubPix
createGeneralizedHoughBallard
createGeneralizedHoughGuil
createHanningWindow
divSpectrums
EMD
findContoursLinkRuns
getDerivKernels
getFontScaleFromHeight
getGaborKernel
getGaussianKernel
getRectSubPix
getTextSize
HoughLinesPointSet
intersectConvexConvex
morphologyDefaultBorderValue
phaseCorrelate
preCornerDetect
pyrMeanShiftFiltering
rotatedRectangleIntersection
spatialGradient
wrapperEMD
```

**Comment by sturkmen72** [comment]
@asmorkalov Do we need to test for all the functions added? Are there any functions that need to be added from the list of unavailable functions?

**Comment by asmorkalov** [comment]
The functions list is too long. I propose to add test for major functions and non-trivial interfaces.

**Comment by sturkmen72** [comment]
@asmorkalov please review. I've added the functions I consider most important and made some adjustments to enhance the code's readability and structure. I'll focus on adding more functions once this PR is merged.

**Review by asmorkalov — APPROVED** [review]

**Comment by Yrij-Zhavoronkov** [comment]
opencv.js 4.11 getTextSize() still unavailable

**Pull request merged**
