### PR TITLE
add VideoCapture / VideoWriter AVFoundation implementation for Mac

### PR DESCRIPTION
**Pull request by yoffy**
Problem:

* QTKit implementation is legacy. File capturing does not work on my OS X 10.11.4.

Solution:

* I wrote `cv::VideoCapture` with AVFoundation.
* `cv::VideoWriter` is copied from cap_avfoundation.mm.

Difference VideoCapture from QTKit implementation:

* improve performance
* add some capabilities of `VideoCapture::get` / `set`

### CODE REVIEW

**Comment by yoffy** [comment]
What's wrong?
Are these tests using VideoCapture?

**Comment by mself** [comment]
@yoffy, Why did you create a separate WITH_AVFOUNDATION_MAC rather than just enabling WITH_AVFOUNDATION to work on both iOS and Mac?  Is there some reason that the code needs to be different on Mac and iOS?  I see that you added new features that are not in the iOS version, but would those also apply to iOS?

**Comment by mself** [comment]
I reviewed and tested this change and it worked perfectly for me.  Using AVF is SO much faster than QT.  Plus, this code includes code for seeking with CAP_PROP_xxx and reading camera properties, too.  The iOS version doesn't even have these.  I recommend merging this.

**Comment by mself** [comment]
Implements #4930

**Comment by yoffy** [comment]
Thank you your reviewing.

> Why did you create a separate WITH_AVFOUNDATION_MAC rather than just enabling WITH_AVFOUNDATION to work on both iOS and Mac?

Because I hope that I want this code to work on all environment, but it's not been tested with iOS.

**Comment by vpisarev** [comment]
this PR will be recreated because of CI issues

**Pull request closed without merging**
