### PR TITLE
V4L2: Add V4L2_PIX_FMT_Y12 (12 bit grey) support

### LINKED ISSUE #16620: missing V4L2_PIX_FMT_Y12 support
I am trying to get an AMG88xx infra red camera working see [question](https://answers.opencv.org/question/226432/videoio-error-v4l2-pixel-format-of-incoming-image-is-unsupported-by-opencv/) which only outputs Y12

after exploring the source for video4linux capture i noticed that [cap_v4l.cpp](https://github.com/opencv/opencv/blob/master/modules/videoio/src/cap_v4l.cpp#L572) is missing V4L2_PIX_FMT_Y12 but supports V4L2_PIX_FMT_Y10 and V4L2_PIX_FMT_Y16

im not very familiar with the inner working of OpenCV but the supported y10 format is very similar to the Y12 see [YUV picture formats](https://linuxtv.org/downloads/v4l-dvb-apis/uapi/v4l/yuv-formats.html) the both are stored as 16bit words with the y10 having more zero padding than the y12 which was added by this [patch](https://github.com/opencv/opencv/commit/4997a6bf06ce008ed750da8f199f27aedccf0139#diff-8afbfaee78cb993ca4836dd4ccb5ae9b)

could i do the same and would anything else be needed to add support for Y12?

### PR DESCRIPTION
**Pull request by firebladed**
resolves #16620

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

---
- [ ] Test using [AMG88xx](http://industrial.panasonic.com/cdbs/www-data/pdf/ADI8000/ADI8000C66.pdf) infrared camera and [video-i2c](https://github.com/raspberrypi/linux/blob/rpi-4.19.y/drivers/media/i2c/video-i2c.c) Linux Kernel Driver

### CODE REVIEW

**Comment by asmorkalov** [comment]
Hello @firebladed Thanks for the patch! Please pay attention that CI bot reports compilation issue on linux: https://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/24932/steps/compile%20release/logs/stdio

```
/build/precommit_linux64/3.4/opencv/modules/videoio/src/cap_v4l.cpp: In member function 'void cv::CvCaptureCAM_V4L::convertToRgb(const cv::Buffer&)':
/build/precommit_linux64/3.4/opencv/modules/videoio/src/cap_v4l.cpp:1591:90: error: expected ')' before ';' token
         cv::Mat(imageSize, CV_16UC1, currentBuffer.start).convertTo(temp, CV_8U, 1.0 / 16;
                                                                                          ^
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_v4l.cpp.o] Error 1
make[2]: Leaving directory `/build/precommit_linux64/build'
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
```
Also could you provide list of cameras or other hardware you used to test the solution or you expect that it should work for?

**Comment by alalek** [comment]
@firebladed Thank you for contribution!
Did you have a chance to validate patch on your camera?

**Comment by firebladed** [comment]
not yet, im going to look into it tommorow

**Comment by firebladed** [comment]
Ive tested it and get images out of it, processing the limited range greyscale outputs is not something i am experienced with so i am unsure of their "accuracy" but it is defiantly functioning

**Pull request merged**
