### PR TITLE
Truetype font support in OpenCV

### PR DESCRIPTION
**Pull request by vpisarev**
```
build_image:Docs=docs-js
force_builders=Win32,Linux32,ARMv7
buildworker:Mac=macosx-1
buildworker:iOS=macosx-1
```

<cut/>

# Overview of the patch:
Added complete solution for truetype fonts rendering in OpenCV.
* Added several fonts that are embedded into OpenCV binary: Rubik, a.k.a. "sans" (variable-weight san serif font with Latin, Cyrillic and Hebrew glyphs; OFL license), Rubik-Italic a.k.a. "italic" (variable-weight italic variation of Rubik) and WQY MicroHei a.k.a. "uni" (sans serif font with myriads of glyphs, including Latin, Cyrillic, Greek and CJK (Chinese, Japanese and Korean characters); distributed under Apache2 license). To reduce OpenCV binary size, the fonts are compressed using gzip and uncompressed before the first use.
* Added freetype and harfbuzz libraries into OpenCV to: 1) make sure they are always available, 2) to make sure they are fresh enough. Only fresh enough versions of freetype handle variable fonts correctly, and so we need them for the embedded fonts.
* Many languages are supported, including most of Latin and Cyrillic scripts, Greek, Hebrew as well as CJK. Many more are supported by providing custom fonts. In order to render text in any supported language, just pass `UTF8` string to `putText()`.
* When a text is printed using any of the embedded fonts: "sans", "italic" or "uni" or using user-supplied font, and if there are some missing glyphs in this font, they are searched in all embedded fonts. That is, the set of supported characters is the union of all the embedded fonts' characters sets and the currently used user-supplied font (if any).
* There are new overloaded variants of `putText()` and `getTextSize()` that take FontFace class on input.
* The old variants are preserved for backward compatibility, but internally they call the the new API.
* Hershey fonts are removed from the library.
* The introduced FontFace class can be initialized with a standard font ("sans", "italic" or "uni") or a user-supplied font (in .ttf, .otf or any other format, supported by Freetype).
* The printed text can now include `\n` characters, which will automatically start a new line. The spacing between lines is now computed automatically and for some fonts it may be not quite good. For the currently used embedded fonts it's fine.
* Text can now be aligned on the right boundary instead of the left boundary. Center alignment is not implemented yet.

# TODO/Known issues:
- [x] (done) ~~the regression tests are not updated yet.~~
- [x] (done) ~~It's planned to add the cache of rendered characters (glyphs), which should accelerate text rendering significantly.~~
- [x] (done) ~~Composite Unicode characters are not supported yet (beyond the support that already exists in Freetype).~~
- [x] (done) ~~There is no any support for ligatures yet.~~
- [x] (done) ~~Right-to-left and bi-directional text support.~~ (_Bidi text support is not as good and versatile as professional solutions, but it can handle some very simple cases like Arabic text with English word or a number inside_)
- (cannot be completely solved, those are just different fonts). Some mapping from Hershey fonts to the embedded Truetype fonts is done, but it's approximate. Usually the new text will look more "condensed" and will take less space, which should be fine most of the time.

# Commit checklist:
- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

# Some references
* Evolution proposal about UI improvements: https://github.com/opencv/opencv/wiki/OE-24.-Module-HighGUI
* feature request about adding UTF-8 support to putText(): https://github.com/opencv/opencv/issues/17980
* Truetype font support in G-API module: https://github.com/opencv/opencv/pull/15972
* Dedicated freetype2+Harfbuzz-based truetype text rendering module in opencv_contrib: https://github.com/opencv/opencv_contrib/tree/master/modules/freetype

### CODE REVIEW

**Comment by khaledhosny** [comment]
> (several megabytes in size; ~same size as libfreetype + all the bundled fonts)

I’m not sure what you are measuring, but HarfBuzz is as lightweight as it gets.

**Comment by vpisarev** [comment]
@khaledhosny, you are right! HarfBuzz is several times smaller than I thought. It's not tiny, but the size is reasonable. I will add support for it shortly. It looks like for Arabic scripts Harfbuzz is necessary.

**Comment by vpisarev** [comment]
@alalek, mac builder gives some random, non-reproducible warnings at cmake stage:

```
CMake Warning at modules/python/python3/CMakeLists.txt:10 (message):
CMake Warning at modules/python/python3/CMakeLists.txt:10 (message):
```

how to deal with it?

**Comment by alalek** [comment]
1. Warning comes with this patch: #18422 (need to rebase patch on fresh master branch)
2. `PYTHON3_LIMITED_API` is enabled on half on builders on CI after the fix above.
3. `macosx-1` has old broken numpy version. Will update dependencies on this machine tomorrow.

**Pull request closed without merging**
