### PR TITLE
Fix bug while loading onnx model in debug

### PR DESCRIPTION
**Pull request by cesarpgouveia**
### PR description

- Fixed bug while loading onnx model in debug. Blob is 4d and you are trying to access it with at() which is 2d. This error does not occur in Release because CV_DbgAssert only asserts under debug. For more info please check lines  937-950 of \opencv\modules\core\include\opencv2\core\mat.inl.hpp.

### CODE REVIEW

**Comment by alalek** [comment]
@cesarpgouveia Thank you for contribution!

Does this problem reproducible with `opencv_test_dnn`? Or you have run another model?

**Comment by cesarpgouveia** [comment]
Hi @alalek !
> Does this problem reproducible with `opencv_test_dnn`? Or you have run another model?

I haven't tested with 'opencv_test_dnn' but I don't think the problem happens in that test. The problem was caused while loading a specific architecture of mine that uses 1x1 convolutions (in order to replace dot layers). However I can try to run opencv_test_dnn tomorrow and see what happens.

**Comment by alalek** [comment]
Got it.
Looks like this problem is not reproducible with `opencv_test_dnn` (with used test models) on debug build (unable to reproduce it locally).

**Comment by alalek** [comment]
I fixed other similar cases too (in more robust way).
Also this patch is rebased on 3.4 branch: https://github.com/opencv/opencv/wiki/Branches
Please check updated patch with your model.

**Comment by cesarpgouveia** [comment]
> I fixed other similar cases too (in more robust way).

Alright I see what you did on the code changes!

> Also this patch is rebased on 3.4 branch: https://github.com/opencv/opencv/wiki/Branches
> Please check updated patch with your model.

I didn't fully understand your question. I discover this while testing in the most recent version of opencv (4.5.3). Do you want me to follow this process (rebasing to 3.4, is that it)? https://github.com/opencv/opencv/wiki/Branches#rebasing-a-pull-request-from-master-to-34

Thanks, César.

**Comment by alalek** [comment]
> Do you want me to follow this process (rebasing to 3.4, is that it)?

No. The patch is already rebased to 3.4 branch.

Please check it locally in your environment (you can cherry-pick commit the last commit, no "conflicts" are expected here).

**Review by alalek — APPROVED** [review]

**Pull request merged**
