### PR TITLE
Disabled resize and wrapAffine OpenVX HAL API

### PR DESCRIPTION
**Pull request by terfendail**
### This pullrequest changes
Temporary disabled OpenVX HAL API for resize and wraps.

### CODE REVIEW

**Comment by vpisarev** [comment]
this magic number (4194304) replicated several times looks bad. Could you define some constant with clear name (using "enum") and use it?

**Comment by alalek** [comment]
BTW, this magic number is not related to OpenVX specification. It is specific to current implementation of sample implementation.

**Comment by terfendail** [comment]
I've replaced magic numbers. Unfortunately there is no special const defined by OpenVX that can be used to distinguish implementations at compile time(at least there is no in sample implementation) but vendor id could be acquired at runtime, so at the moment every implementation will use the same value for maximum supported image dimension.
I'm going to prepare separate PR to update cmake OpenVX detection and provide vendor id at compile time

**Comment by vpisarev** [comment]
thanks! :+1:

**Pull request merged**
