### PR TITLE
G-API: Add default initialization for primtitives

### PR DESCRIPTION
**Pull request by TolyaTalamanov**

### CODE REVIEW

**Comment by TolyaTalamanov** [comment]
@dmatveev

**Comment by dmatveev** [comment]
Nice but for a proper Doxygen these constructors need `@param` comments

**Comment by TolyaTalamanov** [comment]
@dmatveev Could you look at [docs](https://pullrequest.opencv.org/buildbot/export/pr/16062/docs/d8/d07/structcv_1_1gapi_1_1wip_1_1draw_1_1Circle.html#af2c26d99260ff2fe878cd6cfe620c0ce) ?

**Comment by dmatveev** [comment]
Looks nice now, thanks! 👍 approved

**Comment by TolyaTalamanov** [comment]
@alalek

**Pull request merged**
