### PR TITLE
HitMiss tutorial

### PR DESCRIPTION
**Pull request by LorenaGdL**
This PR adds a tutorial for the Hit-or-Miss morphological operation. Related #5515

### CODE REVIEW

**Comment by LorenaGdL** [comment]
The OpenCL test fails, but I don't really know why or how to solve it...

**Comment by StevenPuttemans** [comment]
👍 Great!

**Comment by alalek** [comment]
Thank you!

There are missed images in the end of tutorial:
http://pullrequest.opencv.org/buildbot/export/pr/7948/docs/db/d06/tutorial_hitOrMiss.html

Could you change extension of these files (to `.png` lowercase) and squash commits please:
- doc/tutorials/imgproc/hitOrMiss/images/hitmiss_example2.PNG
- doc/tutorials/imgproc/hitOrMiss/images/hitmiss_example3.PNG

**Comment by LorenaGdL** [comment]
Done! Damn mistery uppercase extension...

Btw, happy new year guys :smile:

**Comment by alalek** [comment]
:+1:

**Pull request merged**
