### PR TITLE
Optimize the neighbor finding algorithm in CirclesGridFinder

### PR DESCRIPTION
**Pull request by Octopus136**
### Pull Request Readiness Checklist

Optimize the neighbor finding algorithm from O(n^3) to O(n^2 \log n)
Resolved a TODO

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by AleksandrPanov** [comment]
@Octopus136, thank you for your work!
Could you check performance? Could you write the tests?

There are not enough tests in OpenCV for CirclesGridFinder and therefore algorithm changes can cause regressions that we may not catch.

We probably won't be able to merge your PR quickly.

**Comment by Octopus136** [comment]
@AleksandrPanov In fact, I have also noticed that the test of CirclesGridFinder is a bit limited. I will try to complete the unit tests in the next few days. 

As for performance, I will also evaluate it asap.

**Comment by asmorkalov** [comment]
@Octopus136 friendly reminder.

**Comment by asmorkalov** [comment]
I tried synthetic board benchmark with the patch (https://github.com/opencv/opencv_benchmarks/pull/8). There is no regression or accuracy changes against 4.x. Execution time reduced, but the difference is low 5.2597 sec in 4.x against 5.1280 sec with the patch. The benchmark time is volatile, not sure if it's pure optimization result.

**Comment by asmorkalov** [comment]
@Octopus136 do you plan to do something with the PR? Is it ready for review?

**Comment by asmorkalov** [comment]
I made more detailed benchmarking with performance test `asymm_circles_grid`. With desktop CPU result is volatile. With old arm chip I see stable 3-5 % degradation in both cases with and without my improvements. So I propose to reject the patch.

**Comment by asmorkalov** [comment]
@vpisarev what do you think?

**Comment by AleksandrPanov** [comment]
@Octopus136 do you plan to do something with the PR? Is it ready for review?

**Comment by asmorkalov** [comment]
@Octopus136 Do you plan to add something else? Is the PR ready for review and merge?

**Pull request closed without merging**
