### PR TITLE
CUDA/BgSegm: fix the threshold of MOG2.Update test

### PR DESCRIPTION
**Pull request by cv3d**
related #12561

```
force_builders=Custom
docker_image:Custom=ubuntu-cuda:16.04
```

### CODE REVIEW

**Comment by cv3d** [comment]
@alalek Any reason for CUDA to remain in 3.4 main repo?
I thought it is already moved to contrib in all repos..

**Comment by tomoaki0705** [comment]
@vpisarev , could you describe a bit more why this PR was closed ?

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
