### PR TITLE
fix cv::CommandLineParser.

### PR DESCRIPTION
**Pull request by csukuangfj**
### This pullrequest changes
Fix commandline parser.

It should handle bool value not only of "true" but also of "TRUE" and "True".

### CODE REVIEW

**Comment by terfendail** [comment]
AFAIK parser always know the type of the value, so IMHO it would be useful to handle 0 and 1 as well.

**Comment by dkurt** [comment]
I've always wanted to use OpenCV's parser with key-value pairs separated by space. That means
`--key value` equals to `--key=value`. Now `.get<std::string>` produces `true` in the first case and `value` in the last one. We could write something like `--key ~/myfile` instead `--key=/home/$(whoami)/myfile` and autocomplete paths in shell.
It would be very cool if you add mentioned functionality here.

**Comment by csukuangfj** [comment]
Hi, thank you for the comment.

Currently, the commandline parser supports only "--key=value" or "-key=value"

If you provide "--key value", it will set "key" to "true" and consider "value" as
a positional argument.

It would be impossible to distinguish key value pairs from positional argument without the "equal" sign.

**Comment by catree** [comment]
Maybe something like [this](https://stackoverflow.com/a/3613424) to be able to parse generic boolean representation?

```
bool parse_bool(std::string str)
{        
    std::transform(str.begin(), str.end(), str.begin(), ::tolower);
    std::istringstream is(str);
    bool b;
    is >> (str.size() > 1 ? std::boolalpha : std::noboolalpha) >> b;
    return b;
}
```

[Demo code](http://cpp.sh/6wr7j).

**Comment by csukuangfj** [comment]
@catree Thank you. It has been updated.

**Comment by terfendail** [comment]
The change looks fine for me. Since space separated parameter handling IMO will require deeper rework of `CommandLineParser` I prefer to handle it with separate PR and merge existing change as is.
@csukuangfj @dkurt What's your opinion?

**Comment by alalek** [comment]
It would be nice to add new test cases for `CommandLineParser` [here](https://github.com/opencv/opencv/blob/3.3.0/modules/core/test/test_utils.cpp) .

**Comment by csukuangfj** [comment]
@alalek  Done.

**Comment by alalek** [comment]
@csukuangfj Thank you! Looks good to me.

**Comment by terfendail** [comment]
👍

**Pull request merged**
