### PR TITLE
build: portable integer types

### PR DESCRIPTION
**Pull request by alalek**
related #10855 

```
docker_image:Docs=docs-js
docker_image:Custom=powerpc64le
```

### CODE REVIEW

**Comment by tomoaki0705** [comment]
I confirmed this fix ( c020a7bb67864760573c9dccd933eff9f11dc425 ) makes build goes through both on Visual Studio 2012 and 2013.
Thank you very much !

**Comment by AdamWill** [comment]
This seems to break build of libfreenect on Linux:

https://koji.fedoraproject.org/koji/taskinfo?taskID=25506808

    make -f OpenNI2-FreenectDriver/CMakeFiles/FreenectDriver.dir/build.make OpenNI2-FreenectDriver/CMakeFiles/FreenectDriver.dir/depend
    In file included from /usr/include/opencv2/core/types_c.h:59,
                     from /usr/include/opencv2/core/core_c.h:48,
                     from /usr/include/opencv/cv.h:63,
                     from /builddir/build/BUILD/libfreenect-ddf092cce09ab4bc97529827a061f1a54a046a17/wrappers/opencv/libfreenect_cv.h:7,
                     from /builddir/build/BUILD/libfreenect-ddf092cce09ab4bc97529827a061f1a54a046a17/wrappers/opencv/libfreenect_cv.c:3:
    /usr/include/opencv2/core/cvdef.h:485:1: error: unknown type name 'namespace'
     namespace cv {
     ^~~~~~~~~
    /usr/include/opencv2/core/cvdef.h:485:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
     namespace cv {
                  ^

I think the conditionals here are a bit borked, perhaps? But not entirely sure what the right fix is.

**Comment by mshabunin** [comment]
@AdamWill , looks like libfreenect wrappers are built using C compiler. We can guard new typedefs with `#ifdef __cplusplus` to hide them.

**Comment by NCBee** [comment]
https://github.com/opencv/opencv/issues/10963#issuecomment-379155798

**Pull request merged**
