### PR TITLE
Local objects optimization in calibration init

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by asmorkalov** [comment]
@cyyever Please pay attention on CI status. BuildBot found trailing white spaces in the code.

**Comment by asmorkalov** [comment]
@@cyyever Friendly reminder.

**Comment by cyyever** [comment]
> 
> 
> @@cyyever Friendly reminder.

I removed the tailing space.

**Review by alalek — APPROVED** [review]
Looks good to me! Thank you for contribution :+1:

**Pull request merged**
