### PR TITLE
dnn: remove Darknet importer for 5.0

### PR DESCRIPTION
**Pull request by WanliZhong**
**Merge with extra https://github.com/opencv/opencv_extra/pull/1135**
**Merge with contribute https://github.com/opencv/opencv_contrib/pull/3694**

TODO:
- [x] Convert samples and tutorials  to onnx version
- [ ] Add other YOLO models: ~~v2-voc~~, v2 tiny, , v3, v4, v4 tiny,  ~~v7~~
https://github.com/opencv/opencv/issues/25200
- [x] Convert tests to onnx version

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by Compaile** [comment]
Any reason for this? We still use those quite a lot as do others.
There aren't onnx alternatives for every darknet based network

**Comment by WanliZhong** [comment]
@Compaile Hi, removing darknet will happen on OpenCV 5.0. It's the result of our discussion. You can try to convert darknet model to other format like onnx.

**Comment by fengyuentau** [comment]
@opencv-alalek Could you update models on CI?

**Comment by WanliZhong** [comment]
Only 1 model needs to be updated since the yolov3, v4, and tiny-yolov4 lack links.

```python
url='https://github.com/onnx/models/raw/main/validated/vision/object_detection_segmentation/tiny-yolov2/model/tinyyolov2-8.onnx',
sha='7ad8395edc8057030d17c14459de6d07f4d11ac6',
filename='tiny-yolov2-voc.onnx')
```

**Comment by LaurentBerger** [comment]
> OpenCV 5.0. It's the result of our discussion.

Why not move all this in opencv_contrib in dnn_legacy?

**Comment by WanliZhong** [comment]
> > OpenCV 5.0. It's the result of our discussion.
> 
> Why not move all this in opencv_contrib in dnn_legacy?

Thanks for the suggestion. However, as our discussion, it's hard to maintain all dnn model importers with good compatibility. So we still choose to remove darknet and caffe from OpenCV 5.0. This change will not happen on 4.x

**Comment by LaurentBerger** [comment]
> Thanks for the suggestion. However, as our discussion, it's hard to maintain all dnn model importers with good compatibility. So we still choose to remove Darknet and Caffe model support from OpenCV 5.0. This change will not happen on 4.x

relative to https://github.com/opencv/opencv/issues/25462

**Comment by asmorkalov** [comment]
Closed. Core team decided to presume the Darknet loader for now.

**Comment by Compaile** [comment]
Presume means keep? (resume?)

**Comment by WanliZhong** [comment]
> Presume means keep? (resume?) 

Yes, we will keep darknet and caffe support for 5.x (but may not put too much effort into maintaining them)

**Pull request closed without merging**
