### PR TITLE
Fix OpenCV.js tests

### PR DESCRIPTION
**Pull request by dkurt**
### Pull Request Readiness Checklist

* Firefox tests passed

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
build_image:Docs=docs-js
build_image:Custom=javascript
buildworker:Custom=linux-1,linux-4,linux-f1
```

### CODE REVIEW

**Comment by asmorkalov** [comment]
I was able to build the PR, but not test. Firefox dev console says:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/vlad/Projects/opencv-build/bin/haarcascade_frontalface_default.xml. (Reason: CORS request not http).

Uncaught Loading data file "haarcascade_frontalface_default.xml" failed. [opencv.js:31:9911237](file:///home/vlad/Projects/opencv-build/bin/opencv.js)
    asyncLoad file:///home/vlad/Projects/opencv-build/bin/opencv.js:31
```

**Comment by asmorkalov** [comment]
@dkurt how do you fixed CORS requirement?

**Comment by dkurt** [comment]
@asmorkalovб sorry, tested everything without the latest changes with data file.

**Comment by dkurt** [comment]
@asmorkalov, FF test passed for me
```
QUnit 2.0.1; Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0

Tests completed in 2210 milliseconds.
610 assertions of 610 passed, 0 failed.
```

**Comment by opencv-alalek** [comment]
> how do you fixed CORS requirement

This is the problem with "file://". Need to emulate web-server.

Use @dkurt  suggestion or run `python -m http.server` and open `http://localhost:8000/bin/tests.html`

**Comment by asmorkalov** [comment]
Yes, I got the point. I used local file without web server. Server version works for me!

**Review by asmorkalov — APPROVED** [review]

**Pull request merged**
