### PR TITLE
OCL: update programs processing

### PR DESCRIPTION
**Pull request by alalek**
- lazy initialization
- limited in-memory cache

### CODE REVIEW

**Comment by vpisarev** [comment]
@alalek, limiting cache may degrade the performance significantly. What's the reason of limiting it?

**Comment by alalek** [comment]
Agree, probably there should be other defaults:
- disabled cache limit for applications (and enable it for tests)
- or added one time warning message with information about cache size control

Memory usage `opencv_test_core` is about 3.8+ GB (2900 programs, where ~50% memory usage is related to 150 DFT programs) on my system in case of Intel OpenCL CPU device (for debug purposes). With Intel GPU OpenCL device memory usage is about 0.65Gb. The similar problem is with opencv_test_imgproc (2900 programs and 4.2GB with OpenCL CPU device / 0.6GB with GPU).

**Comment by alalek** [comment]
Default value for in-memory cache is updated.

**Comment by vpisarev** [comment]
ok, disabling this limitation by default is great solution!

**Pull request merged**
