### PR TITLE
Try to solve I21853 mouse wheel problem with GTK3

### PR DESCRIPTION
**Pull request by LaurentBerger**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [X] The PR is proposed to the proper branch
- [X] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv/issues/21853

**Comment by asmorkalov** [comment]
@LaurentBerger Thanks for the patch. Unfortunately it's not complete. I do not have mouse with horizontal scroll, but with regular mouse I see this in logs:
```

  GUI:                           GTK3
    GTK+:                        YES (ver 3.22.30)
      GThread :                  YES (ver 2.56.4)
      GtkGlExt:                  NO
    VTK support:                 NO

....

  Install to:                    /usr/local
-----------------------------------------------------------------


EVENT_LBUTTONDOWN
EVENT_LBUTTONDOWN
EVENT_MOUSEHWHEEL
EVENT_MOUSEWHEEL
EVENT_MOUSEWHEEL
EVENT_MOUSEWHEEL
EVENT_MOUSEWHEEL
EVENT_MOUSEWHEEL
EVENT_MOUSEWHEEL
```

My code to reproduce the issue:
```
void onMouse(int event, int x, int y, int flags, void *userdata)
{
    if (event == cv::EVENT_MOUSEWHEEL)
        std::cout << "EVENT_MOUSEWHEEL" << std::endl;
    if (event == cv::EVENT_MOUSEHWHEEL)
        std::cout << "EVENT_MOUSEHWHEEL" << std::endl;
    if (event == cv::EVENT_LBUTTONDOWN)
        std::cout << "EVENT_LBUTTONDOWN" << std::endl;
    if (event == cv::EVENT_RBUTTONDOWN)
        std::cout << "EVENT_MOUSEHWHEEL" << std::endl;

}

int main(int argc, char**argv)
{
    std::cout<< cv::getBuildInformation();
    cv::Mat img = cv::imread("/mnt/projects/Projects/OpenCV/opencv-master/samples/data/lena.jpg", cv::IMREAD_COLOR);
    char key = 0;
    cv::namedWindow("Test Event");
    cv::setMouseCallback("Test Event", onMouse);
    while (key != 27)
    {
       if (img.empty())
            return 0;
       cv::imshow("Test Event", img);
       key = cv::pollKey();
    }

    return 0;
}
```

BTW, `if (flags & cv::EVENT_MOUSEWHEEL)` is incorrect check in your repro.

**Comment by asmorkalov** [comment]
Platform: ubuntu 18.04 amd64 with KDE, if it's important.

**Comment by LaurentBerger** [comment]
My version is 
  GUI:                           GTK3
    GTK+:                        YES (ver 3.24.24)
      GThread :                  YES (ver 2.66.8)
      GtkGlExt:                  NO
    VTK support:                 NO

**Review by asmorkalov — APPROVED** [review]
Thanks a lot!

**Comment by asmorkalov** [comment]
@LaurentBerger Thanks a lot for the patch! The same issue is present in 3.4 too. I re-based and re-targeted the PR to 3.4. The fix will appear in 4.x after regular 3.4->4.x merge.

**Pull request merged**
