### PR TITLE
aravis-8.0 is NOW compatible.

### PR DESCRIPTION
**Pull request by jiapei100**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by mshabunin** [comment]
Is it possible to make the code compatible with both old and new versions with help of preprocessor macros?

**Comment by ArkadiuszRaj** [comment]
Absolutely I am fan of supporting both old and new Aravis versions.
Preprocessor in this case is enough, however this new method with "error" variable is better when it comes to detection cause of error.

**Comment by asmorkalov** [comment]
@jiapei100 Do you have progress with the patch?

**Comment by jiapei100** [comment]
@asmaloney 
Sorry I myself haven't been using Windows for over 15 years, and NOW I ONLY have Ubuntu 20.04 on my computer. So, I think Ubuntu 18.04 or Windows 10 won't be given any support from me.

It looks RISC-V and Ubuntu 20.04 are now built successfully with aravis--8, which is good enough...

Cheers

**Comment by asmaloney** [comment]
@jiapei100 I think you meant that for @asmorkalov.

**Comment by asmorkalov** [comment]
@jiapei100 Friendly reminder. Please ignore non-default CI items for now. They are optional.

**Comment by asmorkalov** [comment]
@jiapei100 Friendly reminder

**Comment by mshabunin** [comment]
@asmorkalov , I think we should accept PR #20363 instead of this one. While both are breaking compatibility with Aravis 0.6, that one uses `NULL` instead of a dummy variable and removes some deprecated things.

**Pull request closed without merging**
