### PR TITLE
G-API: Fix for deownification

### PR DESCRIPTION
**Pull request by mpashchenkov**
### Fix (IE)backend build problems

Returned:
- Header for to_own Mat's conversion.

Removed:
- to_ocv for Mat (Mats should be identical (cv or own) now).

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under OpenCV (BSD) License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2019r2.0:16.04
build_image:Custom Win=openvino-2019r2.0
build_image:Custom Mac=openvino-2019r2.0

test_modules:Custom=gapi
test_modules:Custom Win=gapi
test_modules:Custom Mac=gapi

buildworker:Custom=linux-1
test_opencl:Custom=ON
test_bigdata:Custom=1
test_filter:Custom=*

build_gapi_standalone:Linux x64=ade-0.1.1f
build_gapi_standalone:Win64=ade-0.1.1f
build_gapi_standalone:Mac=ade-0.1.1f
build_gapi_standalone:Linux x64 Debug=ade-0.1.1f
```

### CODE REVIEW

**Comment by mpashchenkov** [comment]
@alalek Late ...

**Comment by mpashchenkov** [comment]
Need to close?

**Comment by asmorkalov** [comment]
@dmatveev could you look on it?

**Comment by dmatveev** [comment]
The issue is already fixed in `master` by @alalek here: #17133 

This PR can be closed I believe

**Pull request closed without merging**
