### PR TITLE
Add ocl version BackgroundSubtractorKNN

### PR DESCRIPTION
**Pull request by GlueCrow**
### This pullrequest changes

Add bgfg_knn.cl.
Work in progress.

TODO:
- [x] OpenCL perf test

### CODE REVIEW

**Comment by GlueCrow** [comment]
@alalek I added a perf test, please let me know if I need to add or fix anything else.
Thank you.

**Comment by alalek** [comment]
What OpenCL device are you using?

I observe these results for KNN/Mog2 on i5-6600 (Intel iGPU as OpenCL device):

|Name of Test|base noocl|patch noocl|base ocl|patch ocl|
|---|:-:|:-:|:-:|:-:|
|KNN::KNN_Apply::("gpu/video/768x576.avi", 1)|31.438 ms|31.725 ms|32.004 ms|41.706 ms|
|KNN::KNN_Apply::("gpu/video/768x576.avi", 3)|54.570 ms|54.454 ms|54.041 ms|89.283 ms|
|KNN::KNN_Apply::("gpu/video/1920x1080.avi", 1)|156.672 ms|157.428 ms|156.381 ms|200.664 ms|
|KNN::KNN_Apply::("gpu/video/1920x1080.avi", 3)|238.459 ms|238.090 ms|236.746 ms|388.502 ms|
|KNN::KNN_GetBackgroundImage::("gpu/video/768x576.avi", 5)|76.450 ms|76.469 ms|75.997 ms|110.789 ms|
|KNN::KNN_GetBackgroundImage::("gpu/video/1920x1080.avi", 5)|348.150 ms|347.231 ms|346.754 ms|501.998 ms|
|KNN::OCL_KNN_Apply::("gpu/video/768x576.avi", 1)|33.045 ms|31.825 ms|32.534 ms|24.265 ms|
|KNN::OCL_KNN_Apply::("gpu/video/768x576.avi", 3)|54.727 ms|54.593 ms|54.299 ms|84.901 ms|
|KNN::OCL_KNN_Apply::("gpu/video/1920x1080.avi", 1)|157.646 ms|157.603 ms|156.782 ms|134.017 ms|
|KNN::OCL_KNN_Apply::("gpu/video/1920x1080.avi", 3)|237.286 ms|237.003 ms|237.150 ms|420.804 ms|
|KNN::OCL_KNN_GetBackgroundImage::("gpu/video/768x576.avi", 5)|76.412 ms|76.082 ms|76.712 ms|93.949 ms|
|KNN::OCL_KNN_GetBackgroundImage::("gpu/video/1920x1080.avi", 5)|347.909 ms|347.795 ms|348.896 ms|563.479 ms|
|Mog2::MOG2_Apply::("gpu/video/768x576.avi", 1)|10.642 ms|10.951 ms|14.064 ms|13.871 ms|
|Mog2::MOG2_Apply::("gpu/video/768x576.avi", 3)|19.591 ms|19.598 ms|28.497 ms|28.388 ms|
|Mog2::MOG2_Apply::("gpu/video/1920x1080.avi", 1)|55.647 ms|55.145 ms|80.790 ms|78.798 ms|
|Mog2::MOG2_Apply::("gpu/video/1920x1080.avi", 3)|89.089 ms|89.498 ms|129.842 ms|130.172 ms|
|Mog2::MOG2_GetBackgroundImage::("gpu/video/768x576.avi", 5)|41.703 ms|41.728 ms|50.286 ms|53.320 ms|
|Mog2::MOG2_GetBackgroundImage::("gpu/video/1920x1080.avi", 5)|196.755 ms|197.181 ms|240.628 ms|242.585 ms|
|Mog2::OCL_MOG2_Apply::("gpu/video/768x576.avi", 1)|10.325 ms|10.596 ms|4.081 ms|4.240 ms|
|Mog2::OCL_MOG2_Apply::("gpu/video/768x576.avi", 3)|19.357 ms|19.603 ms|9.307 ms|14.957 ms|
|Mog2::OCL_MOG2_Apply::("gpu/video/1920x1080.avi", 1)|55.971 ms|55.154 ms|60.138 ms|42.166 ms|
|Mog2::OCL_MOG2_Apply::("gpu/video/1920x1080.avi", 3)|89.234 ms|89.237 ms|112.027 ms|84.604 ms|
|Mog2::OCL_MOG2_GetBackgroundImage::("gpu/video/768x576.avi", 5)|41.749 ms|42.175 ms|22.458 ms|23.163 ms|
|Mog2::OCL_MOG2_GetBackgroundImage::("gpu/video/1920x1080.avi", 5)|197.172 ms|197.316 ms|167.544 ms|131.809 ms|

The first two columns should have the same result (CPU mode should be unchanged).
Third column should has the same result too, but it doesn't for Mog2 (some OpenCL runtimes are initialized - related #10629)
KNN OpenCL gray mode (cn=1) has some improvement ~20-35%, color modes has performance degradation)

**Comment by GlueCrow** [comment]
@alalek I have i7-7700 and a GTX1060 6GB.
And what does "patch" mean?
This patch should only affect KNN and #10629 should only affect MOG2.

**Comment by GlueCrow** [comment]
MOG2 and new KNN do an unnecessary initialize() when OpenCL is enabled and output is not a UMat.
Maybe we should fix MOG2 first and then I do the same on this pull request?

**Comment by GlueCrow** [comment]
Fix MOG2 with #10657.
The means of results:

| Name of Test | base noocl | #10657 noocl | base iGPU (i7-7700) | #10657 iGPU (i7-7700) | base GTX1060 | #10657 GTX1060 |
| --- | --- | --- | --- | --- | --- | --- |
| Mog2::MOG2_Apply::("gpu/video/768x576.avi", 1) | 9.26 | 9.29 | 13.51 | 9.08 | 10.60 | 9.08 |
| Mog2::MOG2_Apply::("gpu/video/768x576.avi", 3) | 17.54 | 17.44 | 25.47 | 17.60 | 19.63 | 17.40 |
| Mog2::MOG2_Apply::("gpu/video/1920x1080.avi", 1) | 51.45 | 50.96 | 69.94 | 51.35 | 56.45 | 50.84 |
| Mog2::MOG2_Apply::("gpu/video/1920x1080.avi", 3) | 83.48 | 83.22 | 118.54 | 83.30 | 91.61 | 83.13 |
| Mog2::MOG2_GetBackgroundImage::("gpu/video/768x576.avi", 5) | 37.07 | 37.51 | 44.45 | 37.03 | 38.60 | 36.44 |
| Mog2::MOG2_GetBackgroundImage::("gpu/video/1920x1080.avi", 5) | 182.40 | 180.91 | 216.50 | 182.65 | 189.85 | 181.84 |
| Mog2::OCL_MOG2_Apply::("gpu/video/768x576.avi", 1) | 9.30 | 9.18 | 4.25 | 4.26 | 4.07 | 4.02 |
| Mog2::OCL_MOG2_Apply::("gpu/video/768x576.avi", 3) | 17.34 | 17.43 | 9.15 | 14.38 | 5.80 | 5.81 |
| Mog2::OCL_MOG2_Apply::("gpu/video/1920x1080.avi", 1) | 51.20 | 50.93 | 44.52 | 43.26 | 11.33 | 11.30 |
| Mog2::OCL_MOG2_Apply::("gpu/video/1920x1080.avi", 3) | 83.88 | 83.27 | 84.09 | 84.29 | 21.98 | 21.93 |
| Mog2::OCL_MOG2_GetBackgroundImage::("gpu/video/768x576.avi", 5) | 37.12 | 36.85 | 17.33 | 21.93 | 10.30 | 10.15 |
| Mog2::OCL_MOG2_GetBackgroundImage::("gpu/video/1920x1080.avi", 5) | 182.04 | 182.27 | 139.50 | 139.29 | 39.05 | 38.81 |

**Comment by alalek** [comment]
"Base" is code from commits of this PR except added KNN OpenCL optimizations (KNN perf test included only)
"Patch" is code from all commits of this PR.
"noocl" means that OpenCL subsystem is disabled (I use `OPENCV_OPENCL_RUNTIME=disabled` env variable)

> MOG2 and new KNN (this patch) do an unnecessary initialize() when OpenCL is enabled and output is not a UMat.

Right, I will take a look on #10657 . Performance report looks good. Thank you!

**Comment by GlueCrow** [comment]
Updated.

**Comment by alalek** [comment]
OpenCL KNN results on i5-6600 (with Intel iGPU):

|Name of Test|base|patch|improvement|
|---|:-:|:-:|:-:|
|KNN::OCL_KNN_Apply::("gpu/video/768x576.avi", 1)|32.360 ms|25.920 ms|1.25|
|KNN::OCL_KNN_Apply::("gpu/video/768x576.avi", 3)|54.012 ms|105.062 ms|0.51|
|KNN::OCL_KNN_Apply::("gpu/video/1920x1080.avi", 1)|157.485 ms|140.854 ms|1.12|
|KNN::OCL_KNN_Apply::("gpu/video/1920x1080.avi", 3)|237.667 ms|417.743 ms|0.57|
|KNN::OCL_KNN_GetBackgroundImage::("gpu/video/768x576.avi", 5)|76.706 ms|104.763 ms|0.73|
|KNN::OCL_KNN_GetBackgroundImage::("gpu/video/1920x1080.avi", 5)|347.275 ms|557.923 ms|0.62|

Report is generated by these commands:
```
... build base (with KNN perf test) ...
./bin/opencv_perf_video --gtest_filter=*KNN*:*Mog2* --perf_force_samples=20 --perf_min_samples=20 --gtest_output=xml:../perf/20180122_video_pr10553_0.xml

... build patch ...
./bin/opencv_perf_video --gtest_filter=*KNN*:*Mog2* --perf_force_samples=20 --perf_min_samples=20 --gtest_output=xml:../perf/20180122_video_pr10553_1.xml

... show report (remove "-o markdown" for human readable format) ...
python <opencv_src>/modules/ts/misc/summary.py ../perf/20180122_video_pr10553_* -f OCL_KNN -o markdown
```

**Comment by alalek** [comment]
BTW, OpenCL "CPU" device is not so bad (`OPENCV_OPENCL_DEVICE=:CPU:`):

|Name of Test|base|patch|improvement|
|---|:-:|:-:|:-:|
|KNN::OCL_KNN_Apply::("gpu/video/768x576.avi", 1)|32.360 ms|32.016 ms|1.01|
|KNN::OCL_KNN_Apply::("gpu/video/768x576.avi", 3)|54.012 ms|57.583 ms|0.94|
|KNN::OCL_KNN_Apply::("gpu/video/1920x1080.avi", 1)|157.485 ms|131.679 ms|1.20|
|KNN::OCL_KNN_Apply::("gpu/video/1920x1080.avi", 3)|237.667 ms|263.798 ms|0.90|

At least OpenCL code works, but OpenCL code is not performance portable between devices and additional tuning required for GPU architecture.

Could you measure KNN performance on your GTX1060 ?

**Comment by GlueCrow** [comment]
Results of `OPENCV_OPENCL_DEVICE=NVIDIA:GPU:`(GTX1060 6GB):

|Name of Test|base|patch|improvement|
|---|:-:|:-:|:-:|
|KNN::OCL_KNN_Apply::("gpu/video/768x576.avi", 1)|30.589 ms|12.811 ms|2.39|
|KNN::OCL_KNN_Apply::("gpu/video/768x576.avi", 3)|56.422 ms|20.473 ms|2.76|
|KNN::OCL_KNN_Apply::("gpu/video/1920x1080.avi", 1)|163.766 ms|50.502 ms|3.24|
|KNN::OCL_KNN_Apply::("gpu/video/1920x1080.avi", 3)|248.477 ms|87.643 ms|2.84|
|KNN::OCL_KNN_GetBackgroundImage::("gpu/video/768x576.avi", 5)|76.413 ms|30.859 ms|2.48|
|KNN::OCL_KNN_GetBackgroundImage::("gpu/video/1920x1080.avi", 5)|332.047 ms|131.491 ms|2.53|

**Comment by alalek** [comment]
@GlueCrow I pushed condition to disable OpenCL for color KNN on Intel devices. Please take a look.

**Comment by GlueCrow** [comment]
Tested.
Looks good to me, too. :+1:

**Comment by GlueCrow** [comment]
I see the Mac OpenCL check have failed.
A bad news is that I am also unable to run OCL_KNN* tests on my macbook pro with iGPU(i5-5257U).

**Comment by alalek** [comment]
Mac issue:
- code freezes under OpenCL `clBuildProgram()` call
- there is CVMCompiler process: it consumes several GB of memory.

**Pull request merged**
