### PR TITLE
Add new layer forward interface

### PR DESCRIPTION
**Pull request by pengli**
Add layer forward interface with InputArrayOfArrays and
OutputArrayOfArrays parameters, so we can abstract mat/umat
buffers in one layer forward interface.

### CODE REVIEW

**Comment by vpisarev** [comment]
@pengli, thank you for the patch! I was thinking of using `InputArrayOfArrays`, `OutputArrayOfArrays` instead of explicit `vector<Mat>/vector<UMat>`. That should be more flexible solution.

**Comment by pengli** [comment]
@alalek @vpisarev ,  patch is updated with InputArrayOfArrays and OutputArrayOfArrays  parameters used in the layer forward. please review

**Comment by alalek** [comment]
To reduce amount of duplicated code in CPU code path and minimize patch for CPU code we could use this interface in `Layer` class:
```
    void forward(InputArrayOfArrays inputs_arr, OutputArrayOfArrays outputs_arr, OutputArrayOfArrays internals_arr)
    {
        CV_TRACE_FUNCTION();
        CV_TRACE_ARG_VALUE(name, "name", name.c_str());

        std::vector<Mat> inpvec;
        std::vector<Mat> outputs;
        std::vector<Mat> internals;

        inputs_arr.getMatVector(inpvec);
        outputs_arr.getMatVector(outputs);
        internals_arr.getMatVector(internals);

        std::vector<Mat*> inputs(inpvec.size());
        for (int i = 0; i < inpvec.size(); i++)
            inputs[i] = &inpvec[i];

        forward(inputs, outputs, internals); // call old CPU interface
    }
```

OpenCL layer:
```
    void forward(InputArrayOfArrays inputs_arr, OutputArrayOfArrays outputs_arr, OutputArrayOfArrays internals_arr)
    {
        CV_TRACE_FUNCTION();
        CV_TRACE_ARG_VALUE(name, "name", name.c_str());

        CV_OCL_RUN((preferableTarget == DNN_TARGET_OPENCL) &&
                   OCL_PERFORMANCE_CHECK(ocl::Device::getDefault().isIntel()),
                   forward_ocl(inputs_arr, outputs_arr, internals_arr))

        // Base class
        Layer::forward(inputs_arr, outputs_arr, internals_arr);
    }
```

**Comment by pengli** [comment]
@alalek , hi, new udpate is pushed with your comments included. pls review. Thanks

**Comment by alalek** [comment]
Well done! :+1:

Results on i5-6600 / Linux / Intel OpenCL SRB5 (24 CU):

|Name of Test|base|patch|ratio|
|---|:-:|:-:|:-:|
|AlexNet::DNNTestNetwork::(DNN_BACKEND_DEFAULT, DNN_TARGET_CPU)|17.746 ms|17.860 ms|0.99|
|AlexNet::DNNTestNetwork::(DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)|20.362 ms|16.862 ms|1.21|
|ENet::DNNTestNetwork::(DNN_BACKEND_DEFAULT, DNN_TARGET_CPU)|109.451 ms|109.076 ms|1.00|
|ENet::DNNTestNetwork::(DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)|48.792 ms|47.621 ms|1.02|
|GoogLeNet::DNNTestNetwork::(DNN_BACKEND_DEFAULT, DNN_TARGET_CPU)|29.964 ms|30.063 ms|1.00|
|GoogLeNet::DNNTestNetwork::(DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)|31.015 ms|22.299 ms|1.39|
|Inception_5h::DNNTestNetwork::(DNN_BACKEND_DEFAULT, DNN_TARGET_CPU)|31.838 ms|31.737 ms|1.00|
|Inception_5h::DNNTestNetwork::(DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)|35.348 ms|26.138 ms|1.35|
|ResNet50::DNNTestNetwork::(DNN_BACKEND_DEFAULT, DNN_TARGET_CPU)|62.747 ms|64.039 ms|0.98|
|ResNet50::DNNTestNetwork::(DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)|59.386 ms|49.162 ms|1.21|
|SqueezeNet_v1_1::DNNTestNetwork::(DNN_BACKEND_DEFAULT, DNN_TARGET_CPU)|8.504 ms|8.704 ms|0.98|
|SqueezeNet_v1_1::DNNTestNetwork::(DNN_BACKEND_DEFAULT, DNN_TARGET_OPENCL)|11.037 ms|7.155 ms|1.54|

**Pull request merged**
