### PR TITLE
 Fix some C++ compiler warnings (case fallthrough, negation of string)

### PR DESCRIPTION
**Pull request by eecsninja**
### This pullrequest changes

Replace {!"string"} with {false && "string"}
Replace case statement fallthroughs with break statements

The warnings appear in gcc 7.3.0 with -Wimplicit-fallthrough

### CODE REVIEW

**Comment by alalek** [comment]
BTW, Did you try to remove this [flag](https://github.com/opencv/opencv/blob/3.4/cmake/OpenCVCompilerOptions.cmake#L122)?

**Comment by eecsninja** [comment]
No I didn't. I'm building OpenCV with another build system, alongside dozens of other open-source packages. That's why I'd like to fix the code instead of relying on suppressing warnings.

**Comment by vpisarev** [comment]
@eecsninja, this is not very good fix for not very good coding style; I'd suggest to replace CV_Assert(!"msg") with CV_Error(Error::StsError, msg).

**Comment by eecsninja** [comment]
Closing to redo based on vpisarev's comment.

**Pull request closed without merging**
