### PR TITLE
Add ReLU Activation to DarkNet Importer

### PR DESCRIPTION
**Pull request by danielenricocahall**
Addressing the issue described in https://github.com/opencv/opencv/issues/17778 to enable using both leaky ReLU and ReLU.
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- *[x] I agree to contribute to the project under OpenCV (BSD) License.
- *[x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- *[x] The PR is proposed to proper branch
- *[x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
opencv_extra=add-relu-cfg-test
```

### CODE REVIEW

**Comment by dkurt** [comment]
Thanks for contribution!

Please choose 3.4 as a target branch (we will port to master in a week after merge). Add also sole simple test (just choose one of the existing Darknet tests and add "relu" actiovation to some of the layers.

**Comment by danielenricocahall** [comment]
> Thanks for contribution!
> 
> Please choose 3.4 as a target branch (we will port to master in a week after merge). Add also sole simple test (just choose one of the existing Darknet tests and add "relu" actiovation to some of the layers.

Sure thing - I added some test data in `opencv_extra` in this PR: danielenricocahall:add-relu-darknet-importer and I can add a corresponding test over here - is that sufficient?

**Comment by dkurt** [comment]
If you add a new model - you need to add a test in https://github.com/opencv/opencv/blob/master/modules/dnn/test/test_darknet_importer.cpp

**Comment by dkurt** [comment]
Please remove extra commits:
1. Rename this branch to something else
2. Create a new branch with this name from 3.4
3. Cherry-pick commits

**Comment by danielenricocahall** [comment]
> Please remove extra commits:
> 
> 1. Rename this branch to something else
> 2. Create a new branch with this name from 3.4
> 3. Cherry-pick commits
Thank you!

**Pull request closed without merging**
