### PR TITLE
Build A Dynamic Library for iOS

### PR DESCRIPTION
**Pull request by edc1591**
This PR builds a dynamic library for iOS instead of a static library. This allows better integration with Swift as static libraries are not supported there. This also allows CocoaPods users to use OpenCV as a dependency in Swift projects.

### CODE REVIEW

**Comment by edc1591** [comment]
I'm not sure why the build is failing on Windows and OpenCL, but it will fail on iOS since dynamic library require code signing and it appears there are no code signing identities installed on the build machine.

**Comment by edc1591** [comment]
Closing because of some issues with code signing that I need to work out.

**Comment by Legoless** [comment]
I've done some work on this issue, but as you cannot load arbitrary .dylibs, so I've packaged this into a dynamic .framework. I've managed to get everything together except for bitcode, which stores absolute paths in the linker options. More specifically, each bitcode archive (one for each architecture) contains `-install_name` parameter, which is incorrect and is added by cmake. I've tried fixing it with `INSTALL_NAME_DIR` parameter, but cmake will still append library name, which is `opencv_world` instead of `opencv2`. This breaks the loading paths in Mach-O file, recompiled on Apple App Store from Bitcode. Does anyone have any idea how to fix this?

**Comment by edc1591** [comment]
I should've added this earlier, but I've created a fork that can build OpenCV for iOS as a dynamic framework that is compatible with CocoaPods projects that use the `use_frameworks!` option. It's at https://github.com/edc1591/OpenCV-iOS/ and the pod is called `OpenCV-iOS`. I believe I use `install_name_tool` to make the necessary changes you're referring to.

**Comment by edc1591** [comment]
Ah, had no idea as I haven't used it in an App Store app yet. Please link to the PR here once it's up, if you could. I'd love to take a look.

**Comment by Legoless** [comment]
Opened a pull request: https://github.com/opencv/opencv/pull/8009
Let me know what you think @edc1591

**Comment by edc1591** [comment]
Looks great! Way more elegant than my solution haha. Hope it gets merged.

**Pull request closed without merging**
