### PR TITLE
Move SimulatedAnnealingSolver::Impl in cpp file

### PR DESCRIPTION
**Pull request by catree**
### This pullrequest changes
Move SimulatedAnnealingSolver::Impl in cpp file. Fix also some typos.
I use this [PImpl idiom](http://en.cppreference.com/w/cpp/language/pimpl) as reference.
My apologies if it breaks something.

related #10213

### CODE REVIEW

**Comment by alalek** [comment]
@catree Thank you! I will fix other issues.

**Comment by LaurentBerger** [comment]
@catree you are right  :[ line 158](https://github.com/opencv/opencv/blob/master/modules/ml/src/ann_mlp.cpp#L158) must be uncomment

**Comment by catree** [comment]
@LaurentBerger Maybe you can fix the issue in your pull request #10346 if you think it is appropriate.
Credit to @alalek btw.

**Pull request merged**
