### PR TITLE
NVIDIA Carotene - NVIDIA Hardware-Abstraction-Layer for ARM platforms

### PR DESCRIPTION
**Pull request by ealbuz**
Adds ARM NEON optimizations as a Hardware-Abstraction Layer 

### What does this PR change?
Please add your changes here.

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

**Comment by pzoltowski** [comment]
Is it currently integrated with OpenCV 3.2 binaries for iOS or is it in the form of OpenVX library and OpenCV framework for iOS have to be recompiled? Are there any instructions how to enable Carotene Acceleration in OpenCV 3.2 for iOS?

**Comment by alalek** [comment]
@pzoltowski 
It is [disabled](https://github.com/opencv/opencv/blob/3.2.0/CMakeLists.txt#L174) for iOS (not tested and not supported - probably there is hard dependency on GCC compiler features).

**Comment by cambridgewang** [comment]
Now we build opencv3.2 on NVIDIA TX1.but carotene build failed.
[ 10%] Building CXX object 3rdparty/carotene/hal/carotene/CMakeFiles/carotene_objs.dir/src/resize.cpp.o
[ 10%] Building CXX object 3rdparty/carotene/hal/carotene/CMakeFiles/carotene_objs.dir/src/convert_scale.cpp.o
/tmp/cc3xidKl.s: Assembler messages:
/tmp/cc3xidKl.s:1007: Error: unknown mnemonic `vld1.8' -- `vld1.8 {d4-d5},[x4]'
/tmp/cc3xidKl.s:1008: Error: unknown mnemonic `vmovl.u8' -- `vmovl.u8 q3,d4'
/tmp/cc3xidKl.s:1009: Error: unknown mnemonic `vmovl.u8' -- `vmovl.u8 q4,d5'
.....
How fix it ?
thank you.

**Pull request merged**
