### PR TITLE
cmake: reuse OpenCV NEON detection in carotene

### PR DESCRIPTION
**Pull request by alalek**
```
force_builders=ARMv7,ARMv8
```

### CODE REVIEW

**Comment by asmorkalov** [comment]
@alalek The patch disables Carotene in cross-compilation case:
```
cmake -DCPU_BASELINE=NEON -DCMAKE_TOOLCHAIN_FILE=/home/alexander/Projects/opencv/platforms/linux/arm-gnueabi.toolchain.cmake ../opencv
...
--   Other third-party libraries:
--     Lapack:                      NO
--     Custom HAL:                  NO
--     Protobuf:                    build (3.5.1)
```

**Comment by alalek** [comment]
What is the difference from [this log](
http://pullrequest.opencv.org/buildbot/builders/precommit_armv7/builds/12176/steps/cmake/logs/stdio)?

**Comment by mshabunin** [comment]
@asmorkalov , it could be a different problem. Workaround is to add `-DENABLE_NEON=ON` option.

**Comment by asmorkalov** [comment]
`-DENABLE_NEON=ON` restores Carotene back. Thanks. :+1:

**Pull request merged**
