### PR TITLE
 js: allow building with aruco 

### PR DESCRIPTION
**Pull request by paroj**
```
allow_multiple_commits=1
```

### CODE REVIEW

**Comment by alalek** [comment]
@paroj Thank you!
Could you please rebase patch onto [3.4 branch](https://github.com/opencv/opencv/wiki/Branches)?

**Comment by paroj** [comment]
this will conflict because the photo module is not wrapped in 3.4 either. should I proceed anyway?

**Comment by alalek** [comment]
OK, lets leave this in master only.
Will backport with photo module later.

**Comment by daubaris** [comment]
Build with `opencv_contrib` fails:
```
opencv-4.1.0/build_wasm/modules/js/bindings.cpp:101:17: error: expected namespace name
using namespace aruco;
                ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```

Occurs when `opencv_contrib` modules building instructions are added to cmake.

**Pull request merged**
