### PR TITLE
dnn: move module from opencv_contrib

### PR DESCRIPTION
**Pull request by alalek**
**Merge with contrib**: https://github.com/opencv/opencv_contrib/pull/1255

https://github.com/opencv/opencv_contrib/tree/e6f63c7a38ca40c5dc33e38736e3027e3528d6cb/modules/dnn

### CODE REVIEW

**Comment by abratchik** [comment]
you guys were superfast with moving it, I missed my java wrapper submission for dnn by 5 minutes may be :)

**Comment by alalek** [comment]
@abratchik I have rebased your patch on this repo: https://github.com/alalek/opencv/commits/pr1256_contrib

**Comment by vpisarev** [comment]
:+1:

**Comment by aigeek** [comment]
Sorry,I can not find folder "dnn" in master of "opencv" and "opencv_contrib".After I make the project  ,I can not use "#include <opencv2/dnn.hpp>" and other .h files. How can I use it?Thanks a lot!
I use this demo:https://github.com/alexkarargyris/Caffe_OpenCV_Android_App/blob/master/app/src/main/jni/com_example_alexandroskarargyris_myapplication_NativeClass.cpp @alalek

**Comment by mshabunin** [comment]
@aigeek , the dnn module is located here: https://github.com/opencv/opencv/tree/master/modules/dnn

**Pull request merged**
