### PR TITLE
calib3d: doc: remove C API link (For 4.x)

### LINKED ISSUE #25140: Doc: Suggest to remove C API links and blank pages for core/imgcodecs/...
### Describe the doc issue

Basically, C API has been deprecated/excluded at OpenCV4. ( https://github.com/opencv/opencv/wiki/Opencv4 )
It seems that there are some C API links and these linked C API pages are blank.
I suggests to remove them.

Some modules has been fixed at 5.x branch. What style of pull request is appropriate?

- 2 pull requests
  - For 4.x ( calib3d, core, imgproc, imgcodecs, photo, video and videoio )
  - For 5.x ( calib, core, imgcodecs, photo, video and videoio)
- 3 pull requests
  - For common (core, imgcodecs, photo, video and videoio)
  - For additional 4.x (calib3d, imgproc and highgui)
  - For additional 5.x ( calib )
- 1 pull request ( do not fix to 4.x branch)  
  - For 5.x ( calib, core, imgcodecs, photo, video and videoio)

| module    | 4.x  branch  | 5.x  branch |
|:---------:|:-----:|:-----:|
| calib     |       | Needs |
| calib3d   | Needs |       |
| core      | Needs | Needs |
| imgproc   | Needs |       |
| imgcodecs | Needs | Needs |
| highgui   | Needs |       |
| photo     | Needs | Needs |
| video     | Needs | Needs |
| videoio   | Needs | Needs |

### Fix suggestion

I think we can remove these links and pages.

- https://docs.opencv.org/4.x/d0/de1/group__core.html -> `C structures and operations`
- https://docs.opencv.org/4.x/d7/dbd/group__imgproc.html -> `C API`
- https://docs.opencv.org/4.x/d4/da8/group__imgcodecs.html -> `C API`
- https://docs.opencv.org/4.x/d7/dfc/group__highgui.html -> `C API`
- https://docs.opencv.org/4.x/dd/de7/group__videoio.html -> `C API for video I/O`
- https://docs.opencv.org/4.x/d7/de9/group__video.html -> `C API`
- https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html -> `C API`
- https://docs.opencv.org/4.x/d1/d0d/group__photo.html -> `C API`

```
kmtr@kmtr-None:~/work/opencv$ git reset --hard
HEAD is now at 500c55a808 Merge pull request #25122 from unnonouno:pqueue
kmtr@kmtr-None:~/work/opencv$ git grep "C API" | grep "\@defgroup"
modules/calib3d/include/opencv2/calib3d.hpp:    @defgroup calib3d_c C API
modules/highgui/include/opencv2/highgui.hpp:    @defgroup highgui_c C API
modules/imgcodecs/include/opencv2/imgcodecs.hpp:    @defgroup imgcodecs_c C API
modules/imgproc/include/opencv2/imgproc.hpp:    @defgroup imgproc_c C API
modules/photo/include/opencv2/photo.hpp:    @defgroup photo_c C API
modules/video/include/opencv2/video.hpp:    @defgroup video_c C API
modules/videoio/include/opencv2/videoio.hpp:    @defgroup videoio_c C API for video I/O
kmtr@kmtr-None:~/work/opencv$ git grep "C structure" | grep "\@defgroup"
modules/core/include/opencv2/core.hpp:    @defgroup core_c C structures and operations
```

```
kmtr@kmtr-None:~/work/opencv5$ git reset --hard
HEAD is now at 1d1faaabef Merge pull request #24411 from alexlyulkov:al/dnn-type-inference
kmtr@kmtr-None:~/work/opencv5$ git grep "C API" | grep "\@defgroup"
modules/calib/include/opencv2/calib.hpp:    @defgroup calib3d_c C API
modules/imgcodecs/include/opencv2/imgcodecs.hpp:    @defgroup imgcodecs_c C API
modules/photo/include/opencv2/photo.hpp:    @defgroup photo_c C API
modules/video/include/opencv2/video.hpp:    @defgroup video_c C API
modules/videoio/include/opencv2/videoio.hpp:    @defgroup videoio_c C API for video I/O
kmtr@kmtr-None:~/work/opencv5$ git grep "C structure" | grep "\@defgroup"
modules/core/include/opencv2/core.hpp:    @defgroup core_c C structures and operations
```

### PR DESCRIPTION
**Pull request by Kumataro**
Related to #25140 (for 4.x)

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Review by asmorkalov — CHANGES_REQUESTED** [review]
This should be removed too:
```
modules/calib3d/src/calib3d_c_api.h:54:/** @addtogroup calib3d_c
modules/calib3d/src/calib3d_c_api.h:419:/** @} calib3d_c */
```

**Comment by opencv-alalek** [comment]
Removal is not enough. That stuff would appear in the common lists.

Need to replace to `@cond IGNORED`

**Comment by Kumataro** [comment]
Thank you for comment, I added `@cond IGNORED` as a precaution.

Probably, since only the include directories of each module are targeted in doc/CMakeList.txt, this file under src may not be targeted even before modification.

https://github.com/opencv/opencv/blob/ef611df09b90e8860f9f70649f7a59700b8f490f/doc/CMakeLists.txt#L167-L169

https://github.com/opencv/opencv/blob/ef611df09b90e8860f9f70649f7a59700b8f490f/doc/Doxyfile.in#L102

**Review by asmorkalov — APPROVED** [review]
:+1:

**Pull request merged**
