### PR TITLE
BM3D noise reduction algorithm added

### LINKED ISSUE #6757: Add BM3D implementation
Hi,

Is anybody working on adding BM3D implementation to the OpenCV? I'm planning to add one and I wouldn't like to overlap if someone is already working on it.

BR

### PR DESCRIPTION
**Pull request by bpawlik**
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/301

resolves #6757

### This pullrequest adds

- BM3D denoising algorithm (both first and second step):
   http://www.cs.tut.fi/~foi/GCF-BM3D/BM3D_TIP_2007.pdf
- For performance reasons, only Haar transform is used.
- Template window sizes supported: 4x4 and 8x8
- Maximum number of elements in 3D group: 16

### CODE REVIEW

**Comment by vpisarev** [comment]
@bpawlik, thank you for the contribution! It looks like BM3D is patented algorithm; I'm not sure if we can include it to OpenCV without written permission from the authors. If they allow to put it in, I would still put it to opencv_contrib rather than the main repository.

**Comment by bpawlik** [comment]
@vpisarev  Thank you for your comment. I'm not sure neither, but isn't Non-Local Means patented as well? I'm open to any suggestions, I'm not familiar with the procedure in this kind of situation. In the meantime, I'll prepare a pull request to opencv_contrib repository instead of the main one.

**Comment by bpawlik** [comment]
I have created the following pull request in opencv_contrib repository:
https://github.com/opencv/opencv_contrib/pull/733

Should I close this pull request?

**Comment by bpawlik** [comment]
Whenever you have time, please take a look at: opencv/opencv_contrib#733
It's kind of complete at the moment. Thanks.

**Pull request closed without merging**
