### PR TITLE
Switch to argparse in gen_pattern.py from parsing manually

### PR DESCRIPTION
**Pull request by CSharperMantle**
Finish one TODO in gen_pattern.py. Switch the parser to `argparse` without changing APIs.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
This patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no need to re-open PR, apply changes "inplace".

**Comment by CSharperMantle** [comment]
Copy that. It will be done as soon as possible.

**Comment by CSharperMantle** [comment]
> 
>     * change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
> 

Hello @asmorkalov , 
Is it normal that after I change the base branch, there are a lot more commits that seems to conflict with the 3.4 branch? I wonder whether I should re-open this PR with commits in 3.4 branch in my fork, or just do as you has described above?
Many thanks.

**Comment by CSharperMantle** [comment]
Hello @asmorkalov ,
The `git reflog`command gives me the following output:
```text
49900e529 (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: pull origin: Merge made by the 'recursive' strategy.
7b619c684 HEAD@{1}: rebase -i (finish): returning to refs/heads/master
7b619c684 HEAD@{2}: rebase -i (pick): add a new line according to PEP 8
cdca7400c HEAD@{3}: rebase -i (pick): reformatted
1e14e0eab HEAD@{4}: rebase -i (pick): using argparse
0812207db (upstream/3.4) HEAD@{5}: rebase -i (start): checkout upstream/3.4
b24559b4a HEAD@{6}: clone: from https://github.com/CSharperMantle/opencv.git
```
I hope it works. :D
Many thanks.

**Comment by alalek** [comment]
Not yet.

> wants to merge 1,249 commits

should be

> wants to merge 1 commit

finally.

**Comment by CSharperMantle** [comment]
Hello @alalek ,
Does it mean that I should re-fork the repo and commit my changes after the 3.4 branch? I commited just in the master branch, and I got a lot of commits need merging. 
Many thanks.

**Pull request closed without merging**
