### PR TITLE
don't set event callback for ocl kernels in dnn module

### PR DESCRIPTION
**Pull request by pengli**
The async notification of CL_COMPLETE event can slow down
GPU pipeline efficiency, in dnn module the input/output blobs
are alive all over the net inference period. So it is safe to
enqueue all the dnn kernels and not wait for CL_COMPLETE event.

### CODE REVIEW

**Comment by alalek** [comment]
Could you share performance changes (via opencv_perf_dnn) and provide your platform configuration?

**Comment by alalek** [comment]
OS: ?
OpenCL driver/runtime version: ? (Did you use Intel OpenCL NEO?)

**Comment by pengli** [comment]
OS : ubuntu 16.04
OpenCL runtime : srb 5.0

**Comment by alalek** [comment]
Please try NEO OpenCL runtime from here: https://github.com/intel/compute-runtime/releases
NEO is faster up to 20% on dnn tests than SRB 5.0 (i5-6600 / i7-6700, Linux, without this patch).

**Comment by pengli** [comment]
with Neo, this event callback seems not a problem anymore, which is great. I will close this PR. Thanks for the info

**Pull request closed without merging**
