### PR TITLE
Fixed bug that made cuda::filter give corrupted output when different filters were used in different threads/streams.

### LINKED ISSUE #6742: cv::cuda::Filter thread safety
cv::cuda::Filter created by cv::cuda::createGaussianFilter(...) is not thread safe. And I don't mean the classical thread-safety of accessing one instance from multiple cpu threads. It is not safe to create separate instances of the Filter in multiple threads.
### system info
- OpenCV version: 3.1.0
- Host OS: Linux (Ubuntu 14.04)
- GPU: GeForce GTX TITAN X
- compiler: g++ 4.8.4
### Expected behaviour

filter_1
filter_2
### Actual behaviour

filter_1
filter_2
(not deterministic... each execution outputs slightly different results, but the first image is almost always badly distorted)
### Code example to reproduce the issue

```
#include <iostream>
#include <string>
#include <thread>
#include <opencv2/core/core.hpp>
#include <opencv2/cudafilters.hpp>
#include <opencv2/highgui/highgui.hpp>

void show(const std::string& win_name, const cv::Mat& im) {
  cv::Mat to_show;
  double min, max;
  cv::minMaxIdx(im, &min, &max);
  im.convertTo(to_show, CV_8UC1, 255 / (max-min), -min);
  cv::namedWindow(win_name, CV_WINDOW_NORMAL);
  std::cout << win_name << " - min: " << min << "; max: " << max << std::endl;
  cv::imshow(win_name, to_show);
  // cv::imwrite(std::string("/tmp/")+win_name+".png", to_show);
}

void filter_it(const cv::cuda::GpuMat& d_src, int ksize, cv::Mat& h_dst) {
  cv::cuda::GpuMat d_dst(d_src.rows, d_src.cols, CV_32FC1);
  cv::Ptr<cv::cuda::Filter> filter =
      cv::cuda::createGaussianFilter(CV_32FC1, CV_32FC1, cv::Size(ksize,ksize), 0, 0);
  filter->apply(d_src, d_dst);
  h_dst = cv::Mat(d_dst);
}

int main(int argc, char *argv[])
{
  cv::Mat dot1;
  const int size = 65;
  dot1.create(size, size, CV_32FC1);
  dot1.at<float>(size/2, size/2) = 1.0f;

  cv::Mat dot2;
  dot1.copyTo(dot2);

  cv::cuda::GpuMat d_src1(dot1);
  cv::cuda::GpuMat d_src2(dot2);

  cv::Mat h_dst1;
  h_dst1.create(size, size, CV_32FC1);
  cv::Mat h_dst2;
  h_dst2.create(size, size, CV_32FC1);

  std::thread thr1(&filter_it, std::ref(d_src1), 31, std::ref(h_dst1));
  std::thread thr2(&filter_it, std::ref(d_src2), 3,  std::ref(h_dst2));
  thr1.join();
  thr2.join();

  show("filter_1", h_dst1);
  show("filter_2", h_dst2);
  cv::waitKey(0);
  return 0;
}
```

### PR DESCRIPTION
**Pull request by flyingfalling**
… filters called in different threads. This was due to use of global texture variable shared by all filters.

resolves #6742

```
force_builders=linux,Docs,Custom
buildworker:Custom=linux-1,linux-2,linux-4
docker_image:Custom=ubuntu-cuda:16.04
```

### CODE REVIEW

**Comment by flyingfalling** [comment]
This looks like it succeeded on source builds but failed on "docs" build (something about whitespace?). What does that mean? Did I incorrectly use tabs or spaces or something? -R

**Comment by alalek** [comment]
[Here](http://pullrequest.opencv.org/buildbot/builders/precommit_docs/builds/19142/steps/whitespace%20opencv/logs/stdio):
```
modules/js/src/core_bindings.cpp:333: trailing whitespace.
+    
modules/js/src/core_bindings.cpp:334: trailing whitespace.
+    
```

Need to remove spaces from "empty" lines.

**Comment by nglee** [comment]
https://github.com/opencv/opencv/issues/6742#issuecomment-457570744

>This may have some downsides when it comes to 2D locality since it is accessing in 16x16 chunks, but on newer devices this downside will probably be negligible.

Comparing the "mean" value of `opencv_perf_cudafilters`, no significant performance loss was observed by this PR. In fact, in many cases, performance improved.

**Comment by flyingfalling** [comment]
To confirm, do I need to make a pull request for the opencv_contrib repo?

The source this patched was moved from opencv to opencv_contrib after opencv4, and I would like that to get patched ASAP too...

**Comment by alalek** [comment]
No, CUDA patches from 3.4 are moved to opencv_contrib here: https://github.com/opencv/opencv_contrib/pull/2040

**Pull request merged**
