### PR TITLE
calib3d: calibrateHandEye - allow using Rodrigues vectors for rotation

### PR DESCRIPTION
**Pull request by paroj**
the documentation [suggests using PnP](https://docs.opencv.org/trunk/d9/d0c/group__calib3d.html#gaebfc1c9f7434196a374c382abf43439b) for the camera pose, but solvePnP returns a Rodrigues vector and there are no checks warning you about this..

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by mshabunin** [comment]
@paroj , is it possible to extend existing test to catch this case? Or new test should be created for this pipeline?

**Comment by paroj** [comment]
added the easy modification, where branch coverage stays the same.

**Comment by catree** [comment]
Since I have contributed this function.

---

> the documentation suggests using PnP for the camera pose, but solvePnP returns a Rodrigues vector and there are no checks warning you about this..

@paroj Is it a typo or is it really meant to be three dots `...`?

---

I have put some efforts to write the documentation for this function. I wrote it to try to make it clear that it should be `3x3` rotation matrix. Capital `R`, `Rotation part extracted from the homogeneous matrix`, `This is a vector (vector<Mat>) that contains the rotation matrices`, plus some formulas.

For a newcomer, I can understand the confusion. Probably I should have explicitly write it like `3x3` rotation matrix.

In this case, I take it like documentation is useless. Nobody reads it.

---

I am fine with handling the Rodrigues conversion inside the function.
Not sure about the doc. For me it is obvious that `3x3` rotation matrices are expected. I guess there is no need to change the doc now.

---

Few words about this function. This is a translation of [Matlab code](http://math.loyola.edu/~mili/Calibration/). There are better methods nowadays. For instance methods that use non-linear optimization, for instance as a final refinement. Probably there are better methods in the ROS world.

I have added 5 methods for the following reasons:
- for "historical purposes", there are classical methods but from an user point of view, it is not really useful
- conversion from Matlab to C++ is quite direct thanks to the [available code](http://math.loyola.edu/~mili/Calibration/)

I can understand that only one method should be enough. For sure, in an ideal world, I would not have to contribute this function...

**Comment by paroj** [comment]
"documentation is to users as code comments are to compilers"

---
it is like an unwritten rule in opencv that, no matter what the docs say, you can throw both rotation matrices and rodrigues vectors at functions and they will complain if they dont like it. (most of them actually work with both)

that said, in the particular case I fell over the following:
- One part of my code computes poses and stores them as tuples of `(rot, trans)`, where `rot` is either `R` or `rvec`, depending on how they are computed.
- at some other point, at which I lost track where exactly the poses comes from, I feed them into `calibrateHandEye` which returned implausible results

after having disassembled my camera-to-robot matching logic, I discovered that the rotation is stored in the wrong format.
Initially, I merely wanted to add an assert on the `Mat` size, but then I realized that feeding the output of `solvePnP` or `calibrateCamera` is the typical use-case and both return rvecs.

---

having you at hand, I noticed that the last 2 methods fail with `DS1.zip` from:
https://data.nal.usda.gov/dataset/data-solving-robot-world-hand-eyes-calibration-problem-iterative-methods

see #17986 for a reproducer.

I think your implementations in OpenCV are quite useful to get a baseline result. If it is not good enough, one still can go looking for more sophisticated algorithms..

**Comment by mshabunin** [comment]
@paroj , looks like this patch is also applicable to _3.4_ branch. Could you please re-target the PR and rebase your branch to _3.4_?

**Comment by paroj** [comment]
rebase done

**Pull request merged**
