### PR TITLE
search in two directions when try to add new quad in addOuterQuad

### PR DESCRIPTION
**Pull request by spdfghi**
In ChessBoardDetector::addOuterQuad, previous code try to connect new quad with inner quad, if possible, but only search for one direction. I have made  three test images, one is normal(a.jpg), one lossed an outer quad(b.jpg), and then i flipped it vertically(c.jpg). Only last one fails. I fixed it by check two directions and row/col.

Here is the test code and images:
```
Mat img;
vector<Point2f> corners;
auto size = cv::Size(6, 6);
img = imread("D:/tmp/a.jpg", 0);
std::cout<<cv::findChessboardCorners(img, size, corners)<<"\n";
std::cout << corners.size() << "\n";
img = imread("D:/tmp/b.jpg", 0);
std::cout<<cv::findChessboardCorners(img, size, corners)<<"\n";
std::cout << corners.size() << "\n";
img = imread("D:/tmp/c.jpg", 0);
std::cout<<cv::findChessboardCorners(img, size, corners)<<"\n";
std::cout << corners.size() << "\n";
```
a
a
b
b
c
c

### CODE REVIEW

**Comment by spdfghi** [comment]
Since it's not an usual algorithm, so i have made a simple note image to show how it happends:
IMG_0039
i noted the index of missed quad, the privous code try to get another quad connected to the missed quad by first search the index prev_i quad, and then get the index i quad of prev_i quad. It works sometime, for example, A to C. However, it failed with the opposite direction, i.e., C to A. Which depends on who was first searched by dfs previously. The line begin in 1155 i made was followed line 924
```
for (int i = 0; i < 4; i++)
{
    CV_DbgAssert(q);
    ChessBoardQuad* neighbor = q->neighbors[i];
    switch (i)   // adjust col, row for this quad
    {           // start at top left, go clockwise
    case 0:
        row--; col--; break;
    case 1:
        col += 2; break;
    case 2:
        row += 2;   break;
    case 3:
        col -= 2; break;
    }
```  @asmorkalov

**Comment by asmorkalov** [comment]
@MaximSmolskiy Could you take a look and try with your dataset?

**Comment by asmorkalov** [comment]
@MaximSmolskiy Could you take a look and try with your dataset?

**Comment by MaximSmolskiy** [comment]
> @MaximSmolskiy Could you take a look and try with your dataset?

@asmorkalov I didn't deal with this function, so I amn't ready to review this pr.
These changes provide minor improvements on my `2` private datasets:
1. `294` -> `296` detected chessboards
2. `524` -> `527` detected chessboards

**Comment by asmorkalov** [comment]
@MaximSmolskiy Thanks a lot for the feedback. The patch does not change result of synthetic benchmark. Just want to get feedback for real images.

**Review by asmorkalov — APPROVED** [review]

**Pull request merged**
