### PR TITLE
 find the inner circle by using pointPolygonTest

### PR DESCRIPTION
**Pull request by jsxyhelu**
this is also a good example by using pointPolygonTest
the result is something like:

<cut/>

the_maximum_inner_circle_result

### CODE REVIEW

**Comment by LaurentBerger** [comment]
When I do a pr first I create a new branch: 
cd opencv
git checkout 3.4
git branch Innercircle
then I modify opencv source code and when my local compilation and link is OK then 
git commit -a 
git push

**Comment by jsxyhelu** [comment]
bug fix

**Comment by alalek** [comment]
?
Your current patch is here: #12206  (with source branch "3.4" - `jsxyhelu:3.4`)

**Comment by jsxyhelu** [comment]
> Your current patch is here: #12206 (with source branch "3.4" - jsxyhelu:3.4)

thanks

**Pull request closed without merging**
