### PR TITLE
Optional mask argument for MatchTemplate_Demo

### PR DESCRIPTION
**Pull request by acinader**
Accept and use optional mask argument for MatchTemplate_Demo.

Useful for visualizing effect of a mask on template matching.

### CODE REVIEW

**Comment by apavlenko** [comment]
Currently the added code isn't used in the demo, so to prevent adding a dead code please also extend the demo to use a mask.

**Comment by acinader** [comment]
Hi Andrey.  Glad to look into it.   When you say extend the demo, do you mean this demo: https://github.com/tsdconseil/opencv-demonstrator

If so, I'll take a look, thought i'd probably have to start with https://github.com/tsdconseil/opencv-demonstrator/issues/27

Or is there another demo you're referring to?  If so, can you give me a link to get me started.

Thanks.

**Comment by apavlenko** [comment]
Actually I meant `MatchTemplate_Demo`: you added the code that can use mask but now it's not used, to make it useful please extend the tutorial that uses this demo app with the mask use - without use the feature is useless.

**Comment by acinader** [comment]
Hi @apavlenko thanks for getting back to me.

I think I understand - update the doc: http://docs.opencv.org/master/de/da9/tutorial_template_matching.html#gsc.tab=0

by editing the doxygen markdown in this doc:
https://github.com/opencv/opencv/blob/2f4e38c8313ff313de7c41141d56d945d91f47cf/doc/tutorials/imgproc/histograms/template_matching/template_matching.markdown

edit the docs to include how to use the mask with an example. 

I am now able to build and view the doxygen files, so I think I should be able to do this.  

Please let me know if I am not understanding your request.

Will take me at least a few days to get around to it and get it right.

If there is some other demo app that needs extending, please send me a link to where it is on github and I'll work on that too.  Sorry if I am a little slow, but not very familiar with opencv (yet!).

Thanks!

**Comment by apavlenko** [comment]
Hi @acinader, yes, this is exactly what I mean, thanks for your contribution!

**Comment by acinader** [comment]
hm, so weird.  its like github is busted or something (not likely).  I updated the docs, pushed commit to my branch, but it isn't showing up here.  never happened to me before.  I do see that it is stuck on "checking for ability to merge automatically".

the commit shows up on my fork: https://github.com/acinader/opencv/commits/add-mask-to-match-template-demo

so odd! 

So I closed it thinking i would be able to reopen, will have to create a new pr now....sorry


screen shot 2016-07-05 at 1 37 23 pm

**Pull request closed without merging**
