### PR TITLE
Update videocapture_basic.cpp

### PR DESCRIPTION
**Pull request by HowardsPlayPen**
Minor bug - I believe you are using the wrong version of open() on line 28 - adding deviceID +appId together as integers does not make  any sense versus using the version of .open() taking two integers as parameter.

### CODE REVIEW

**Comment by alalek** [comment]
There is no bug. It is old API, but it is still supported.

> to backward compatibility usage of camera_id + domain_offset (CAP_*) is valid when apiPreference is CAP_ANY

https://docs.opencv.org/4.3.0/d8/dfe/classcv_1_1VideoCapture.html#aabce0d83aa0da9af802455e8cf5fd181

**Comment by asmorkalov** [comment]
@alalek @HowardsPlayPen I helped to rebased the PR to 3.4.

**Comment by alalek** [comment]
These items are still here:

- please follow OpenCV coding style (no space before comma): `cap.open(deviceID, apiID);`
- edit commit message (remove "bug", add "modern API")

**Comment by asmorkalov** [comment]
@alalek done.

**Comment by alalek** [comment]
What is about other cases of legacy usage? I believe patch should be consistent.

From 3.4 branch:
```
$ grep -Rni VideoCapture ./ | grep ' + '
./modules/videoio/src/cap_aravis.cpp:61:// Basic usage: VideoCapture cap(CAP_ARAVIS + <camera id>);
./modules/videoio/doc/videoio_overview.markdown:42:cv::VideoCapture cap(0 + cv::CAP_DSHOW);
$ grep -RnE 'ca[^\.]*\.open\(.* \+ ' ./
./modules/videoio/doc/videoio_overview.markdown:45:cap.open(0 + cv::CAP_DSHOW);
./samples/cpp/videocapture_basic.cpp:28:    cap.open(deviceID + apiID);
```

**Comment by asmorkalov** [comment]
@alalek I fixed all cases you found in the code.

**Pull request merged**
