### PR TITLE
Skip InferList.TestStreamingInfer

### PR DESCRIPTION
**Pull request by dkurt**
### Pull Request Readiness Checklist

similar workaround as https://github.com/opencv/opencv/pull/25294

resolves https://github.com/opencv/opencv/issues/25320

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Review by asmorkalov — APPROVED** [review]
:+1:

**Comment by asmorkalov** [comment]
@dkurt please let me know, when it's ready for merge.

**Comment by dkurt** [comment]
@asmorkalov, I have a concern that the test hangs not sporadically but because of memory issues. For example, after merge https://github.com/opencv/opencv/pull/25312 it executes fine. Let me move this PR to draft.

**Comment by dmatveev** [comment]
These tests shouldn't run at all with the newer versions of OpenVINO, @dkurt which OpenVINO version do you refer too?

**Comment by dkurt** [comment]
@dmatveev, Our actions CI still depend on OpenVINO 2023.0. Locally tests won't run with 2023.1

**Comment by dmatveev** [comment]
> @dmatveev, Our actions CI still depend on OpenVINO 2023.0. Locally tests won't run with 2023.1

@dkurt we can further lower down the check probably, to avoid the 2023.0 either. @TolyaTalamanov any ideas on this? Would it impact us much?

Meanwhile, there's OpenVINO 2024.0 already available and 2024.1 is coming soon.

Finally, the issue may be still irrelevant to the particular OpenVINO version or G-API's execution mechanics, let me prepare reproducer which will (sooner or later) hang without any of those components.

**Comment by asmorkalov** [comment]
@dkurt @dmatveev The issue is still reproducible with CI and I often see test hangs. I have to merge the PR. Please submit another path with fix and enable test back.

**Comment by dmatveev** [comment]
@asmorkalov no problem at all!

**Pull request merged**
