### PR TITLE
Fix for incorrect calcOpticalFlowPyrLK result evaluation with ARM NEON

### LINKED ISSUE #6979: Incorrect calcOpticalFlowPyrLK result on NEON 64-bit ARM
##### System information (version)
- OpenCV => 3.0
- Operating System / Platform => Linux ARM 64-bit
- Compiler => GCC 4.9

##### Detailed description
When CV_NEON is defined and compiling for 64-bit ARM, the eigenvalue calculation in calcOpticalFlowPyrLK is incorrect.  For the provided sample images and code, the "pyramid level 0" eigenvalue is a negative number when compiled with CV_NEON, and a positive number if "#undef CV_NEON" is placed before the code in lkpyramid.cpp.  When compiled and run on an Intel desktop computer, the eigenvalue is also computed as a positive number.

The difference comes down to a difference in the calculated "A" matrix.  When CV_NEON is defined, the "A" matrix calculated is:
   2048.822266,  -120.389381
  -120.389381,  -1765.508301
but when CV_NEON is not defined, the A matrix is calculated as:
   2048.832031,  -120.389458
  -120.389458,   2330.505615

##### Steps to reproduce
[lkpyr_neon_bug.zip](https://github.com/opencv/opencv/files/380490/lkpyr_neon_bug.zip)
Compile and run the attached file.  The images are included in the zip file.  Please add the appropriate includes for the "video" module.  Compile for both 64-bit ARM and for x86 and compare the results.

lkpyramid.cpp, around line 496, adding the following line prints out the A matrix:
          fprintf(stderr, "Level=%d\n%f,\t%f\n%f,\t%f\n", level, A11, A12, A12, A22);

### PR DESCRIPTION
**Pull request by terfendail**
resolves #6979

### This pullrequest changes

Update ARM NEON implementation of derivatives covariation matrix  computation in LK optical flow estimation

### CODE REVIEW

**Comment by terfendail** [comment]
I'm unable to test the fix due to lack of HW. So confirmation of #6979 author is necessary to ensure the fix solves the original issue.

**Comment by richardroberts** [comment]
Unfortunately I'm unable to compile using the patch in this PR.  I can confirm that the fix proposed by K-Shinotsuka in #6979 does fix the calculation issue.  Compiling with the patch in this PR though gives the following errors:

third_party/OpenCVX/v3_0_0/modules/video/src/lkpyramid.cpp:419:44: error: assigning to 'const long *' from incompatible type 'int64 *' (aka 'long long *')
                int64x2_t nq0l = vld1q_s64(nA11);
                                           ^~~~
third_party/crosstool/v18/stable/toolchain/bin/../lib/clang/google3-trunk/include/arm_neon.h:7628:46: note: expanded from macro 'vld1q_s64'
  __ret = (int64x2_t) __builtin_neon_vld1q_v(__p0, 35); \
                                             ^~~~
third_party/OpenCVX/v3_0_0/modules/video/src/lkpyramid.cpp:420:44: error: assigning to 'const long *' from incompatible type 'int64 *' (aka 'long long *')
                int64x2_t nq0h = vld1q_s64(nA11+2);
                                           ^~~~~~
third_party/crosstool/v18/stable/toolchain/bin/../lib/clang/google3-trunk/include/arm_neon.h:7628:46: note: expanded from macro 'vld1q_s64'
  __ret = (int64x2_t) __builtin_neon_vld1q_v(__p0, 35); \
                                             ^~~~
third_party/OpenCVX/v3_0_0/modules/video/src/lkpyramid.cpp:421:44: error: assigning to 'const long *' from incompatible type 'int64 *' (aka 'long long *')
                int64x2_t nq1l = vld1q_s64(nA12);
                                           ^~~~
third_party/crosstool/v18/stable/toolchain/bin/../lib/clang/google3-trunk/include/arm_neon.h:7628:46: note: expanded from macro 'vld1q_s64'
  __ret = (int64x2_t) __builtin_neon_vld1q_v(__p0, 35); \
                                             ^~~~
third_party/OpenCVX/v3_0_0/modules/video/src/lkpyramid.cpp:422:44: error: assigning to 'const long *' from incompatible type 'int64 *' (aka 'long long *')
                int64x2_t nq1h = vld1q_s64(nA12+2);
                                           ^~~~~~
third_party/crosstool/v18/stable/toolchain/bin/../lib/clang/google3-trunk/include/arm_neon.h:7628:46: note: expanded from macro 'vld1q_s64'
  __ret = (int64x2_t) __builtin_neon_vld1q_v(__p0, 35); \
                                             ^~~~
third_party/OpenCVX/v3_0_0/modules/video/src/lkpyramid.cpp:423:44: error: assigning to 'const long *' from incompatible type 'int64 *' (aka 'long long *')
                int64x2_t nq2l = vld1q_s64(nA22);
                                           ^~~~
third_party/crosstool/v18/stable/toolchain/bin/../lib/clang/google3-trunk/include/arm_neon.h:7628:46: note: expanded from macro 'vld1q_s64'
  __ret = (int64x2_t) __builtin_neon_vld1q_v(__p0, 35); \
                                             ^~~~
third_party/OpenCVX/v3_0_0/modules/video/src/lkpyramid.cpp:424:44: error: assigning to 'const long *' from incompatible type 'int64 *' (aka 'long long *')
                int64x2_t nq2h = vld1q_s64(nA22+2);
                                           ^~~~~~
third_party/crosstool/v18/stable/toolchain/bin/../lib/clang/google3-trunk/include/arm_neon.h:7628:46: note: expanded from macro 'vld1q_s64'
  __ret = (int64x2_t) __builtin_neon_vld1q_v(__p0, 35); \
                                             ^~~~
third_party/OpenCVX/v3_0_0/modules/video/src/lkpyramid.cpp:440:27: error: assigning to 'long *' from incompatible type 'int64 *' (aka 'long long *')
                vst1q_s64(nA11,   nq0l);
                          ^~~~
third_party/crosstool/v18/stable/toolchain/bin/../lib/clang/google3-trunk/include/arm_neon.h:25122:26: note: expanded from macro 'vst1q_s64'
  __builtin_neon_vst1q_v(__p0, (int8x16_t)__s1, 35); \
                         ^~~~
third_party/OpenCVX/v3_0_0/modules/video/src/lkpyramid.cpp:441:27: error: assigning to 'long *' from incompatible type 'int64 *' (aka 'long long *')
                vst1q_s64(nA11+2, nq0h);
                          ^~~~~~
third_party/crosstool/v18/stable/toolchain/bin/../lib/clang/google3-trunk/include/arm_neon.h:25122:26: note: expanded from macro 'vst1q_s64'
  __builtin_neon_vst1q_v(__p0, (int8x16_t)__s1, 35); \
                         ^~~~
third_party/OpenCVX/v3_0_0/modules/video/src/lkpyramid.cpp:442:27: error: assigning to 'long *' from incompatible type 'int64 *' (aka 'long long *')
                vst1q_s64(nA12,   nq1l);
                          ^~~~
third_party/crosstool/v18/stable/toolchain/bin/../lib/clang/google3-trunk/include/arm_neon.h:25122:26: note: expanded from macro 'vst1q_s64'
  __builtin_neon_vst1q_v(__p0, (int8x16_t)__s1, 35); \
                         ^~~~
third_party/OpenCVX/v3_0_0/modules/video/src/lkpyramid.cpp:443:27: error: assigning to 'long *' from incompatible type 'int64 *' (aka 'long long *')
                vst1q_s64(nA12+2, nq1h);
                          ^~~~~~
third_party/crosstool/v18/stable/toolchain/bin/../lib/clang/google3-trunk/include/arm_neon.h:25122:26: note: expanded from macro 'vst1q_s64'
  __builtin_neon_vst1q_v(__p0, (int8x16_t)__s1, 35); \
                         ^~~~
third_party/OpenCVX/v3_0_0/modules/video/src/lkpyramid.cpp:444:27: error: assigning to 'long *' from incompatible type 'int64 *' (aka 'long long *')
                vst1q_s64(nA22,   nq2l);
                          ^~~~
third_party/crosstool/v18/stable/toolchain/bin/../lib/clang/google3-trunk/include/arm_neon.h:25122:26: note: expanded from macro 'vst1q_s64'
  __builtin_neon_vst1q_v(__p0, (int8x16_t)__s1, 35); \
                         ^~~~
third_party/OpenCVX/v3_0_0/modules/video/src/lkpyramid.cpp:445:27: error: assigning to 'long *' from incompatible type 'int64 *' (aka 'long long *')
                vst1q_s64(nA22+2, nq2h);
                          ^~~~~~
third_party/crosstool/v18/stable/toolchain/bin/../lib/clang/google3-trunk/include/arm_neon.h:25122:26: note: expanded from macro 'vst1q_s64'
  __builtin_neon_vst1q_v(__p0, (int8x16_t)__s1, 35); \
                         ^~~~
12 errors generated.

**Comment by K-Shinotsuka** [comment]
@terfendail 

The problem is not fixed if you use 64bit integer.
If the number of loop is too many, 64bit integer will overflow.
You should use "from int to float" type conversion.

Example:
L297
org
         int CV_DECL_ALIGNED(16) nA11[] = {0, 0, 0, 0}, nA12[] = {0, 0, 0, 0}, nA22[] = {0, 0, 0, 0};
new
         itemtype CV_DECL_ALIGNED(16) nA11[] = {0, 0, 0, 0}, nA12[] = {0, 0, 0, 0}, nA22[] = {0, 0, 0, 0};

L421
org
                int32x4_t nq1 = vld1q_s32(nA12);
                int32x4_t nq2 = vld1q_s32(nA22);
                nq0 = vld1q_s32(nA11);
new
                float32x4_t nq1 = vld1q_f32(nA12);
                float32x4_t nq2 = vld1q_f32(nA22);
                float32x4_t nq3 = vld1q_f32(nA11);

L430-L432
org
                nq0 = vaddq_s32(nq0, q7);
                nq1 = vaddq_s32(nq1, q8);
                nq2 = vaddq_s32(nq2, q15);
new
                nq3 = vaddq_f32(nq3, vreinterpretq_f32_s32(q7));
                nq1 = vaddq_f32(nq1, vreinterpretq_f32_s32(q8));
                nq2 = vaddq_f32(nq2, vreinterpretq_f32_s32(q15));

L434-L436
org
                vst1q_s32(nA11, nq0);
                vst1q_s32(nA12, nq1);
                vst1q_s32(nA22, nq2);
new
                vst1q_f32(nA11, nq3);
                vst1q_f32(nA12, nq1);
                vst1q_f32(nA22, nq2);

L533
org
            int CV_DECL_ALIGNED(16) nB1[] = {0,0,0,0}, nB2[] = {0,0,0,0};
new
            itemtype CV_DECL_ALIGNED(16) nB1[] = {0,0,0,0}, nB2[] = {0,0,0,0};

L628-L629
org
                    nq11 = vld1q_s32(nB1);
                    int32x4_t nq15 = vld1q_s32(nB2);
new
                    float32x4_t nq16 = vld1q_f32(nB1);
                    float32x4_t nq15 = vld1q_f32(nB2);

L649-L650
org
                    nq11 = vaddq_s32(nq11, nq9);
                    nq15 = vaddq_s32(nq15, nq4);
new
                    nq16 = vaddq_f32(nq16, vreinterpretq_f32_s32(nq9));
                    nq15 = vaddq_f32(nq15, vreinterpretq_f32_s32(nq4));

L652-L653
org
                     vst1q_s32(nB1, nq16);
                     vst1q_s32(nB2, nq15);
new
                     vst1q_f32(nB1, nq16);
                     vst1q_f32(nB2, nq15);

**Comment by richardroberts** [comment]
Hi @K-Shinotsuka, I can understand that overflow is the cause, since your proposed fix in #6979 fixes it.  Also makes sense because it only occurs using our large 75x75 patch, and only on the first pyramid level.  We have already incorporated that fix into our local OpenCV 3.0 copy here.  Is there an action you would like me to take in regards to your last comment in this PR?  If you send me new lkpyramid.cpp file(s) I am glad to try compiling and running them on our ARM 64-bit platform.

**Comment by terfendail** [comment]
I've updated PR as suggested by @K-Shinotsuka 

@richardroberts Could you please test it?

**Comment by K-Shinotsuka** [comment]
Dear Mr. Richard Roberts

I have attached the file to this email.

Sincerely.

**Comment by K-Shinotsuka** [comment]
@terfendail 

Please fix compile error.

Example:
L628-L629
new
                    float32x4_t nB1v = vld1q_s32(nB1);
                    float32x4_t nB2v = vld1q_s32(nB2);
revised
                    float32x4_t nB1v = vld1q_f32(nB1);
                    float32x4_t nB2v = vld1q_f32(nB2);

L649-L650
new
                    nB1v = vaddq_s32(nB1v, vreinterpretq_f32_s32(nq9));
                    nB2v = vaddq_s32(nB2v, vreinterpretq_f32_s32(nq4));
revised
                    nB1v = vaddq_f32(nB1v, vreinterpretq_f32_s32(nq9));
                    nB2v = vaddq_f32(nB2v, vreinterpretq_f32_s32(nq4));

L652-L653
new
                    vst1q_s32(nB1, nB1v);
                    vst1q_s32(nB2, nB2v);
revised
                    vst1q_f32(nB1, nB1v);
                    vst1q_f32(nB2, nB2v);



@richardroberts 
Please tell me if you don't receive attached file at the previous comment.

**Comment by terfendail** [comment]
I've fixed mentioned errors. Sorry for my inattention.

**Comment by vpisarev** [comment]
:+1:

**Pull request merged**
