### PR TITLE
Split cv2.cpp

### LINKED ISSUE #21175: Task: split cv2.cpp compilation
Issue: weekly [valgrind build](http://pullrequest.opencv.org/buildbot/builders/master-contrib_valgrind-lin64-debug/builds/10204) is broken.

```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
modules/python2/CMakeFiles/opencv_python2.dir/build.make:62: recipe for target 'modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o' failed
```

Additional related feature:
- dedicated binary for opencv_contrib Python bindings

### PR DESCRIPTION
**Pull request by mshabunin**
* Hopefully fixes #21175
* Only static content extracted from cv2.cpp, generated types and functions are still there.
* I did not find conflicting PRs among active (slight intersection with #20370)

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
IMO problem is not about cv2.cpp code itself. It is related to huge generated files (by binding generator), which are included into cv2.cpp.
This approach is fine, could be used as a first step.

**Comment by mshabunin** [comment]
Yes, I have concerns too. But there is still a chance that this will help.

CLOC:
* cv2.cpp before change: ~2000
* cv2.cpp + cv2*.hpp after change: ~900

Tests seem to pass now. I can squash commits if necessary.

**Review by alalek — APPROVED** [review]
LGTM :+1:

**Comment by asmorkalov** [comment]
cc  @asenyaev

**Pull request merged**
