### PR TITLE
Fix mismatch and simplify code in ChessBoardDetector::findQuadNeighbors

### PR DESCRIPTION
**Pull request by MaximSmolskiy**
### Pull Request Readiness Checklist

Сode doesn't match comment. 
If we want check `1:4` edges ratio and `edge_len` is squared edge length, then we should check
```
ediff > 15*edge_len
```
with constant `15`, not `32`, because
```
ediff > 15*edge_len2 <=> edge_len1 - edge_len2 > 15*edge_len2 <=> edge_len1 > 16*edge_len2 <=> 1:4 edges ratio
```

But for me it's better and simpler to directly check `edge_len1 > 16*edge_len2`

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Review by AleksandrPanov — APPROVED** [review]
PR was tested with OpenCV [synthetic benchmark](https://github.com/opencv/opencv_benchmarks).

There is no accuracy regressions.
image

👍

Maybe it's better to add this line as a comment?
```
ediff > 15*edge_len2 <=> edge_len1 - edge_len2 > 15*edge_len2 <=> edge_len1 > 16*edge_len2 <=> 1:4 edges ratio
```

**Comment by MaximSmolskiy** [comment]
> Maybe it's better to add this line as a comment?
> 
> ```
> ediff > 15*edge_len2 <=> edge_len1 - edge_len2 > 15*edge_len2 <=> edge_len1 > 16*edge_len2 <=> 1:4 edges ratio
> ```

Added comment

**Comment by MaximSmolskiy** [comment]
@asmorkalov Can you merge this PR please?

**Comment by vpisarev** [comment]
The extended testing did not reveal any regressions, so potentially the patch can be integrated. However, maybe it's easier to fix the description rather than change the threshold.

**Review by asmorkalov — APPROVED** [review]
:+1:

**Pull request merged**
