### PR TITLE
Core fixes ported from 3.x

### PR DESCRIPTION
**Pull request by savuor**
Fixes from PR #3987 for 3.x ported to 2.4

### This pullrequest changes

All commits from the PR copied except the following ones:

* too many changes to port:
 - [9fbd1d68ad95d7bad2d09501110081ecd82d5ad8](https://github.com/opencv/opencv/pull/3987/commits/9fbd1d68ad95d7bad2d09501110081ecd82d5ad8)
* no Downhill solver found in opencv_core:
 - [96b5ec14d45a7e7d7b0d9acdf1dd9a473514ee95](https://github.com/opencv/opencv/pull/3987/commits/96b5ec14d45a7e7d7b0d9acdf1dd9a473514ee95)
 - [01e351de3725aaad52e1670bba97dbea269c0f6e](https://github.com/opencv/opencv/pull/3987/commits/01e351de3725aaad52e1670bba97dbea269c0f6e)
 - [5a31f6b4e1c7e3e5b5d2505113cea8bcba1c529e](https://github.com/opencv/opencv/pull/3987/commits/5a31f6b4e1c7e3e5b5d2505113cea8bcba1c529e) 
* no conjugage gradiend solver found in opencv_core:
 - [5b9182ba43da01a10e60b0735ce2a93003b26d82](https://github.com/opencv/opencv/pull/3987/commits/5b9182ba43da01a10e60b0735ce2a93003b26d82)
 - [63a63e3eaa1fb6e350fabcff29d1144229fc2ad6] (https://github.com/opencv/opencv/pull/3987/commits/63a63e3eaa1fb6e350fabcff29d1144229fc2ad6)
* no place to patch:
 - [931a5199698534b952ca72f61a9f74d443561457] (https://github.com/opencv/opencv/pull/3987/commits/931a5199698534b952ca72f61a9f74d443561457)
 - [73f760fdf09115009097725a213461c8016c845d] (https://github.com/opencv/opencv/pull/3987/commits/73f760fdf09115009097725a213461c8016c845d)
 - [d280205245b5c119bac689a058783fc8b9537b19] (https://github.com/opencv/opencv/pull/3987/commits/d280205245b5c119bac689a058783fc8b9537b19)
* exists as PR [#7218](https://github.com/opencv/opencv/pull/7218):
 - [a33d7928a4313be7fd6c0de4943b6698c7db47f5] (https://github.com/opencv/opencv/pull/3987/commits/a33d7928a4313be7fd6c0de4943b6698c7db47f5)

### CODE REVIEW

**Comment by savuor** [comment]
@vpisarev please look at this

**Comment by alalek** [comment]
Please leave bugfixes only.
- some feature-like stuff like `std::vector<bool>` support should be removed
- looks like `randShuffle` changes existed behaviour, so some user code (tests with fixed random seed) may break

**Comment by savuor** [comment]
@alalek done

**Comment by alalek** [comment]
:+1:

**Pull request merged**
