### PR TITLE
Improved chessboard detection

### PR DESCRIPTION
**Pull request by mshabunin**
Modified and improved the method for chessboard detection. It is now faster and detects chessboards under difficult lighting condition as well as when the chessboard has strong out of plane rotations

Restored #4046 and retargeted to master branch.

### CODE REVIEW

**Comment by mshabunin** [comment]
@HHI-VIT-IMC , could you please fix merge conflicts?

**Comment by HHI-VIT-IMC** [comment]
How can I identify merge conflicts? ... and if identified, how can I resolve them? I wish to have them resolved in order to get our improvements in the master branch.

**Comment by mshabunin** [comment]
@HHI-VIT-IMC , please check rebased commit https://github.com/opencv/opencv/compare/master...mshabunin:check-6851
If it is ok you can replace your branch with this one.

**Comment by HHI-VIT-IMC** [comment]
I checked https://github.com/opencv/opencv/compare/master...mshabunin:check-6851 and if this version is able to being merged, then it is fine. 
However, there is one algorithmic issue:
In    modules/calib3d/src/calibinit.cpp    in line 534
the if-statement
 `if ( !(flags & CV_CALIB_CB_ADAPTIVE_THRESH) )`
could be removed as it is performed once again in line 652.

A minor issue: in order to give easier reference, in  line 65 you may add my email address and replace the line as follows:
**Oliver Schreer (oliver.schreer@hhi.fraunhofer.de) and Stefano Masneri. This method works faster than the previous**

**Comment by mshabunin** [comment]
@HHI-VIT-IMC , will you update your branch with the rebased version?

Just run:
```.sh
# optional - if you have non-clean repository: git stash
git fetch https://github.com/mshabunin/opencv check-6851
git checkout FETCH_HEAD -B HHI_improvements
git push origin -f HHI_improvements # assuming your GitHub remote is called "origin"
# optional - restore from stash: git checkout <previous-version> && git stash pop
```

Or do you want me to create new PR from my fork?

**Comment by HHI-VIT-IMC** [comment]
I would appreciate, if you could create the new pull request. I'm not experienced with GIT version control.
Will be this version https://github.com/mshabunin/opencv check-6851 then be part of the master after merge? 

Is it possible for you to consider in the merge the two issues mentioned yesterday and copied below?

Thanks and best regards,
   Oliver

In modules/calib3d/src/calibinit.cpp in line 534
the if-statement
if ( !(flags & CV_CALIB_CB_ADAPTIVE_THRESH) )
could be removed as it is performed once again in line 652.

A minor issue: in order to give easier reference, in line 65 you may add my email address and replace the line as follows:
Oliver Schreer (oliver.schreer@hhi.fraunhofer.de) and Stefano Masneri. This method works faster than the previous

**Comment by mshabunin** [comment]
@HHI-VIT-IMC , I've created new PR #6895 , feel free to add your comments there.

Regarding your comments from this thread:
- instead of removing, I moved this block prior to old detection algorithm, because otherwise the _thresh_img_ would be uninitialised.
- we'd prefer to minimize number of e-mail addresses and personal websites in the codebase, because they can become obsolete. If anyone will want to contact authors he can find actual commiters via git blame and history here on GitHub.

Also, I've removed _cvCheckChessboardBinary_ from public interface.

**Pull request closed without merging**
