### PR TITLE
bug fix min_enclosing_triangle.cpp

### PR DESCRIPTION
**Pull request by sturkmen72**
https://github.com/Itseez/opencv/issues/4992
to compare current and fixed results you can use https://github.com/sturkmen72/opencv_samples/blob/master/bugtest_minEnclosingTriangle.cpp

### CODE REVIEW

**Comment by sturkmen72** [comment]
@IceRage could you check this modification

**Comment by IceRage** [comment]
First of all I do apologize for the late reply. 

Secondly, regarding the proposed change, by relaxing the constraints and setting the sideCValid flag to true when all sides are flush (i.e. VALIDATION_SIDES_FLUSH is true) invalid triangles which do not have a minimal area could be accepted as solutions. Therefore an alternative fix should be considered.

As a side note the condition (or invariant) that must hold for a minimal area triangle is that the midpoint of each side of the triangle must touch the enclosed polygon. For more details about this condition please see Theorem 1.1. and the corresponding proof given by Klee and Laskowski in the following paper:

V. Klee and M. C. Laskowski, “Finding the smallest triangles containing a given convex polygon,” Journal of Algorithms, vol. 6, no. 3, pp. 359–375, Sep. 1985.

**Comment by vpisarev** [comment]
@IceRage, @sturkmen72, so, what's the decision? As I see, without the patch the function sometimes returns no triangle (which is not very good, but happens rather rarely). With the patch the function does return triangle all the time (?), but it can be larger than minimal sometimes. Is that correct?

Does the following temporary solution make sense?:

1. add a flag to the function isValidMinimalTriangle, whether or not include the check added in the patch (validationFlag == VALIDATION_SIDES_FLUSH)

2. first run the algorithm with this flag turned off and if it fails to find a triangle, run the algorithm with this flag turned on. So that we always get a triangle but in some rare cases it may be not the optimal one.

**Comment by IceRage** [comment]
@vpisarev The algorithm should theoretically always return a minimal area enclosing triangle. Although I did not check, I assume the current problem is due to floating point approximation errors. Would it be to late if I would try to investigate and potentially fix the bug in the week 21-27 December 2015? If yes, then I would personally choose solution number 2 in your reply.

**Comment by vpisarev** [comment]
@IceRage, I think, it's never too late :) it's just that your fix will go to 3.2, whereas 3.1 will have the current version, which is already pretty good and fails very rarely.

**Comment by sturkmen72** [comment]
@vpisarev, @IceRage FYI
minenclosingtriangle test - opencv

Points:
[126, 218;
 181, 335;
 256, 339;
 288, 291;
 318, 243;
 354, 169;
 336, 145;
 230, 137;
 171, 134]

computed  area with current minEnclosingTriangle function  ( green lines ): 68339
computed  area with fixed minEnclosingTriangle function ( blue lines ): 40024.9

**Comment by IceRage** [comment]
@vpisarev, @sturkmen72 

Reducing the EPSILON value used to compare floating point numbers in modules/imgproc/src/min_enclosing_triangle.cpp from 1E-5 to 1E-6 fixes the bug and the correct minimal area enclosing triangle is returned for the unit test described in issue #4992. 

Therefore the bug was due to approximation errors. 

However when reducing the value of EPSILON other examples do not work (e.g. the previously working unit test Imgproc_MinTriangle.accuracy fails). 

A quick and dirty fix could be to start with a low value of EPSILON (e.g. 1e-7), run the main algorithm, and if no triangle was found, then multiply EPSILON by 10 and repeat, otherwise return. An alternative solution would be to go through the code and compute the value of EPSILON which should work for "all" cases, but this is tedious. A potentially better solution could be to use multi-precision arithmetic libraries (e.g. The GNU Multiple Precision Arithmetic Library).

**Comment by sturkmen72** [comment]
it is stated in the [GSoC_2016 page](https://github.com/Itseez/opencv/wiki/GSoC_2016)

"convexHull is implemented with Sklansky’s second, 1982 algorithm, which is incorrect in some case, and suboptimal complexity-wise"

maybe the source of the problem is **convexHull** that used in the beginning of **minEnclosingTriangle** code

**Comment by mshabunin** [comment]
Transferred to new PR

**Pull request closed without merging**
