### PR TITLE
(5.x) Merge 4.x

### PR DESCRIPTION
**Pull request by asmorkalov**
OpenCV Contrib: https://github.com/opencv/opencv_contrib/pull/3566
OpenCV Extra: https://github.com/opencv/opencv_extra/pull/1102

#23897 from fengyuentau:refactor_fc
#24037 from Abdurrahheem:ash/dev_einsum
#24058 from hanliutong:rewrite-imgporc
#24074 from Kumataro/fix24057
#24126 from AleksandrPanov:fix_charuco_checkBoard
#24131 from cudawarped:cuda_add_default_ptx
#24132 from hanliutong:rewrite-imgproc2
#24166 from hanliutong:rewrite-remaining
#24201 from lpylpy0514:4.x
#24239 from asmorkalov:as/msmf_returned_fourcc
#24247 from AleksandrPanov:fix_drawDetectedCornersCharuco_type_error
#24250 from dkurt:ts_fixture_constructor_skip_2
#24260 from vrabaud:ubsan
#24263 from georgthegreat:msan-include
#24266 from alexlyulkov:al/tf-argmax-default-dim
#24269 from FlyinTeller:patch-1
#24270 from dkurt:fix_24256
#24274 from vrabaud:webp_1.3.2
#24275 from alexlyulkov:al/fix-tf-graph-simplifier
#24278 from georgthegreat:compat-fixes
#24280 from casualwind:parallel_opt
#24283 from fengyuentau:halide_tests
#24286 from ashadrina:intel_icx_compiler_support
#24288 from tailsu:sd/emscripten-3.1.45-fixes
#24291 from visitorckw:fix-memory-leak
#24295 from fengyuentau:add_onnx_expand
#24301 from hanliutong:rewrite-stereo-sift
#24302 from dkurt:ts_setup_skip
#24303 from asmorkalov:as/vittack_warning_fix
#24305 from hanliutong:toolchain
#24309 from dkurt:gemm_ov_hotfix
#24316 from alexlyulkov:al/fix-caffe-read-segfault
#24329 from asmorkalov/as/openvino_ci
#24334 from fengyuentau:fix_24319

Temporary disabled new test Charuco.testSeveralBoardsWithCustomIds. PR [#23473](https://github.com/opencv/opencv/pull/23473) changed output shape for detector corners. More detailed investigation is required.

Previous "Merge 4.x: #24254

### CODE REVIEW

**Review by opencv-alalek — COMMENTED** [review]
Why do you not using the latest 4.x commits?

Missing commit: https://github.com/opencv/opencv/commit/c7ec0d599a958b185f8f8fcca81090e18c76df83
Merged at 1:24 PM UTC.

This PR is opened at 1:46 PM UTC (merge commit is created at 1:42 PM UTC).

Both events are handled by you.
Messing with date order is not a good practice for such synchronization points like merging of branches.

---

Memory corruption hotfixes for #24126 should be landed on 4.x first (instead of trying to provide fixes during the merge loosing the half of the patch).

Refer to email with subject `fix charuco checkBoard (60ae973)` from @vrabaud

/cc @AleksandrPanov

**Comment by opencv-alalek** [comment]
There is another fix which should be landed on 4.x before merging to 5.x: #24315
(to avoid propagation of test crashes due to memory corruption)

**Comment by asmorkalov** [comment]
@opencv-alalek I disabled failed test for now and we will debug the issue this week. Let's merge, if you do not have objections. I'll repeat the merge procedure, when https://github.com/opencv/opencv/pull/24315 is done.

**Comment by opencv-alalek** [comment]
> I disabled failed test

Single test is not enough.
Again, there is memory corruption in checkBoard() code of Charuco.
To properly avoid sporadic failures you need to disable almost all tests of Charuco.

Did you read comment from Vincent?

**Review by opencv-alalek — APPROVED** [review]
Fixes are postponed to the next iteration (more time is required)

**Pull request merged**
